### ISSUE TITLE
输入法候选词条有时会消失

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#103]
```
描述：
在使用ibus输入法时，输入法候选词条有时会消失，但仍然可以输入，通过键盘数字
键来选取候选字词，只是看不见候选字条，在使用pidgin聊天时发生，nautilus中输
入也有出现过，Ctrl＋空格 关闭和打开输入法仍然如此，只能重新启动ibus才能恢复
正常。

另外这个问题的出现比较偶然和随机，不方便进行重现，请问我需要进行什么操作来
向ibus项目提供更详细的信息？

系统：2.6.26.5-39.fc9.i686
ibus版本：0914




```

Original issue reported on code.google.com by `ph.linfan` on 2008-09-15 11:13:04

**Comment by SpongeBab** [comment]
ubuntu24.04
此bug 依旧存在。
我已经安装了python-notify2.

**Comment by Thundercup** [comment]
fedora 42 问题依旧存在，可以复现在flatpak版telegram，左上角搜索框可以显示，但是聊天的输入框没有显示

**Comment by tankoki** [comment]
我发现并没有消失，只是在外接显示屏的时候和输入框有个很远的距离，而且不知道如何设置，怎么贴图上来？

**Comment by tankoki** [comment]
我想我测试出问题了，只要显示器一设置缩放，不管是多少，输入选字窗口就会按比例偏移至屏幕右下方（实际超出屏幕，所以看不到），这个哪位大佬知道怎么解决呢？

**Comment by tankoki** [comment]
发现了一个最糟糕的解决办法，不过聊胜于无
1.去GNOME Shell Extensions安装Customize IBus https://extensions.gnome.org/extension/4112/customize-ibus/
2.进入设置，打开固定候选框>不记住位置>居中
                       打开拖拽移动候选框
enjoy

**Comment by Thundercup** [comment]
> 我发现并没有消失，只是在外接显示屏的时候和输入框有个很远的距离，而且不知道如何设置，怎么贴图上来？

没有办法，我选择安装 fcitx5，这完美解决了问题
