### ISSUE TITLE
Problem in Wubi phrase customisation.

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1142]
```
二笔用i开头进行全形输入,同一个字就有两个编码.自造词的时候,第一码排在i之后的字总是被认为第一码为i,比如 统计力学 编码被识别成 iiii, 正确的应该是 tjlx.
```

Original issue reported on code.google.com by `nothingatallx` on 2010-11-02 08:24:33

**Comment by mike-fabian** [comment]
issue on google code was: https://code.google.com/p/ibus/issues/detail?id=1124

**Comment by mike-fabian** [comment]
Caius commented:

Caius> 對不起，我不太明白，可否請你更詳細解釋和附截圖？謝謝

Which according to google translate means:

Caius> I'm sorry, I do not understand, could you explain in more
Caius> detail and attached screenshots?  THX

Then Caius pinged again but there was no response.

**Comment by mike-fabian** [comment]
So I think we should close this as there was no response explaining what the problem was.
