### ISSUE TITLE
Gdk-WARNING on every keystroke when using IBUS in GTK3 apps

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1265]
```
OS: ArchLinux
Architecture: x86_64
IBus version: 1.3.9
Python version: 3.2 / 2.7.1
dbus version: 1.4.8
dbus-python version: 0.83.1
gtk version: GTK2 2.24.4  GTK3 3.0.10

English:
If running any GTK3 apps in terminal, when pressing key in any text field, many errors
like following msg shows: 
(gedit:20407): Gdk-WARNING **: Event with type 8 not holding a GdkDevice. It is most
likely synthesized outside Gdk/GTK+

中文：
在终端中运行GTK3程序，开启IBUS，只要在能输文本的地方按键，就会弹出错误信息：
(gedit:20407): Gdk-WARNING **: Event with type 8 not holding a GdkDevice. It is most
likely synthesized outside Gdk/GTK+
这样的错误信息导致X的log文件不断变大。
关掉IBUS就正常了。


```

Original issue reported on code.google.com by `cuihao.leo` on 2011-06-06 09:30:47

**Comment by fujiwarat** [comment]
I cannot reproduce this issue with ibus 1.5.

**Comment by changwoo** [comment]
I still can reproduce this always in version 1.5.22. It only happens on forward-key-event.

**Comment by fujiwarat** [comment]
Right, GTK was changed probably when Wayland was implemented and I guess the warning cannot be stopped if you use forward-key-event.

**Comment by changwoo** [comment]
Ideally, the forwarded key event needs to have the `GdkDevice*` value from the original key event. But it's very difficult I guess. Then how about making a virtual `GdkDevice` for this purpose? gnoms-shell (or mutter) seems to do this for the forward-key-event in wayland gtk-text-input.

**Comment by fujiwarat** [comment]
@changwoo 
Right. I also think so.
Thank you for your evaluation.
