### ISSUE TITLE
Use key location to track combinations rather than from alphanumeric forms (touch-typing mode?)

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1508]
```
What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...): Archlinux
Architecture (i386, x86_64): x86_64
IBus version: 1.4.1
Input method name and version: array30/行列輸入法30 (ibus-table 1.3.9)
Python version: 2.7.3
dbus version: 1.6.4
dbus-python version: 1.1.1

What steps will reproduce the problem?
1. Install ibus-table
2. Add array30 input method in the list
3. Type something like "a"

What is the expected output? What do you see instead?
Actual output:     a  | 一  雨,    豕.    ……
Expected output: [1-] | 一  雨[8v] 豕[9v] ……

Please provide any additional information below.
If we have a look at Wikipedia (https://zh.wikipedia.org/zh-tw/%E8%A1%8C%E5%88%97%E8%BC%B8%E5%85%A5%E6%B3%95),
and on the official website (http://www.array.com.tw/class/class2.htm), we can see
that codes are given according to positions of fingers, and not according to letters
and symbols on the keyboard.

Plus, my keyboard isn't in qwerty mode, and I must say I don't know this layout at
all, which makes it very difficult, for me, to find the right key…
Therefore, I ask that codes are given according to positions.

Here is the equivalence table between positions and keys on a  qwerty keyboard:

 | Key    | Code           |
 |--------+----------------|
 | q      | [1↑]           |
 | w      | [2↑]           |
 | e      | [3↑]           |
 | r      | [4↑]           |
 | t      | [5↑]           |
 | y      | [6↑]           |
 | u      | [7↑]           |
 | i      | [8↑]           |
 | o      | [9↑]           |
 | p      | [0↑]           |
 |--------+----------------|
 | a      | [1-]           |
 | s      | [2-]           |
 | d      | [3-]           |
 | f      | [4-]           |
 | g      | [5-]           |
 | h      | [6-]           |
 | j      | [7-]           |
 | k      | [8-]           |
 | l      | [9-]           |
 | ;      | [0-]           |
 |--------+----------------|
 | z      | [1↓]           |
 | x      | [2↓]           |
 | c      | [3↓]           |
 | v      | [4↓]           |
 | b      | [5↓]           |
 | n      | [6↓]           |
 | m      | [7↓]           |
 | ,      | [8↓]           |
 | .      | [9↓]           |
 | /      | [0↓]           |
 |--------+----------------|
```

Original issue reported on code.google.com by `ma.jiehong` on 2012-08-08 15:34:21

**Comment by mike-fabian** [comment]
issue on google code was: https://code.google.com/p/ibus/issues/detail?id=1491

**Comment by mike-fabian** [comment]
If I understand the original report correctly, it requests to show
something like 1↑ instead of “q” if the key “q” has been typed.
According to this table in the report:

     | Key    | Code           |
     |--------+----------------|
     | q      | [1↑]           |
     | w      | [2↑]           |
     | e      | [3↑]           |
     | r      | [4↑]           |
     | t      | [5↑]           |
     | y      | [6↑]           |
     | u      | [7↑]           |
     | i      | [8↑]           |
     | o      | [9↑]           |
     | p      | [0↑]           |
     |--------+----------------|
     | a      | [1-]           |
     | s      | [2-]           |
     | d      | [3-]           |
     | f      | [4-]           |
     | g      | [5-]           |
     | h      | [6-]           |
     | j      | [7-]           |
     | k      | [8-]           |
     | l      | [9-]           |
     | ;      | [0-]           |
     |--------+----------------|
     | z      | [1↓]           |
     | x      | [2↓]           |
     | c      | [3↓]           |
     | v      | [4↓]           |
     | b      | [5↓]           |
     | n      | [6↓]           |
     | m      | [7↓]           |
     | ,      | [8↓]           |
     | .      | [9↓]           |
     | /      | [0↓]           |
     |--------+----------------|

This table seems to be exactly the same as this part in array30.head.in,
the source used to create the array30 table:

    ### Define the prompts of each valid input char.
    BEGIN_CHAR_PROMPTS_DEFINITION
    q 1^
    w 2^
    e 3^
    r 4^
    t 5^
    y 6^
    u 7^
    i 8^
    o 9^
    p 0^
    a 1-
    s 2-
    d 3-
    f 4-
    g 5-
    h 6-
    j 7-
    k 8-
    l 9-
    ; 0-
    z 1v
    x 2v
    c 3v
    v 4v
    b 5v
    n 6v
    m 7v
    , 8v
    . 9v
    / 0v
    END_CHAR_PROMPTS_DEFINITION

These character prompts were ignored in ibus-table, but
I have fixed this problem quite a while ago, not they are shown.

So I think this is fixed. Please try with a recent ibus-table
(current is ibus-table-1.9.6).

Closing as fixed.
