### ISSUE TITLE
Automatically user phrase creation.

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1546]
```
Automatically learn user phrases and create user phrase database.
```

Original issue reported on code.google.com by `Caius.Chance` on 2012-10-12 16:44:46

**Comment by mike-fabian** [comment]
This has been fixed long ago. In tables supporting it, for example in
the wubi-jidian86 table, which has these options in the table source:

    ### Whether user are allow to define their own phrase, default is true
    USER_CAN_DEFINE_PHRASE = TRUE

    ### If true then the phrases' frequencies will be adjusted dynamically.
    DYNAMIC_ADJUST = TRUE

    ### Rules for user define phrase construct:
    RULES = ce2:p11+p12+p21+p22;ce3:p11+p21+p31+p32;ca4:p11+p21+p31+p-11

“ce2” is a rule for phrases of length 2, “ce3” is a rule
for phrases of length 3, “ca4” is a rule for phrases of
length 4 *and* for all phrases with a length greater then
4. “pnm” in such a rule means to use the n-th character of
the phrase and take the m-th character of the table code of
that character. I.e. “p-11” is the first character of the
table code of the last character in the phrase.

Let’s assume the phrase is “天下大事”. The goucima (構詞碼
= “word formation keys”) for these 4 characters are:

    character goucima
    天        gdi
    下        ghi
    大        dddd
    事        gkvh

(If no special goucima are defined by the user, the longest
encoding for a single character in a table is the goucima for
that character).

The length of the phrase “天下大事” is 4 characters,
therefore the rule ca4:p11+p21+p31+p-11 applies, i.e. the
table code for “天下大事” is calculated by using the first,
second, third and last character of the phrase and taking the
first character of the goucima for each of these. Therefore,
the table code for “天下大事” is “ggdg”.

When the user enters “天下大事” and then commits it, the new
code “ggdg” is learned automatically and put into the user database.

**Comment by mike-fabian** [comment]
Original issue on google code: https://code.google.com/p/ibus/issues/detail?id=1529
