### ISSUE TITLE
Skin / template UI support.

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1548]
```
Add a function which user can change UI/toolbar with skin/template files.
```

Original issue reported on code.google.com by `Caius.Chance` on 2012-10-12 16:50:13

**Comment by mike-fabian** [comment]
Original Google code issue was: https://code.google.com/p/ibus/issues/detail?id=1531

**Comment by mike-fabian** [comment]
The UI/toolbar is done either by ibus or by Gnome, not by ibus-table. So I don’t think
anything can be done in ibus-table about this. Closing.
