### ISSUE TITLE
ibus-table在注销时不保存用户词组

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1555]
```
Please *DO NOT* ask question here! Please use
https://groups.google.com/group/ibus-user

请不要在这里提问，请使用ibus用户讨论组
https://groups.google.com/group/ibus-user

What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...):ubuntu 12.04 
Architecture (i386, x86_64):x86_64
IBus version:IBus 1.4.1
Input method name and version:ibus-wubi
Python version:
dbus version:1.4.18-1ubuntu1.3
dbus-python version:1.0.0-1ubuntu1
gtk version (if bug is about gtk applications):
qt version (if bug is about qt applications):

What steps will reproduce the problem?
1.使用Shift_L键在输入中的时候是把第一个候选词提交到预编辑词组中，
2.在预编辑模式下输入用户词组，按Space键提交并保存输入的字词，
3.注销系统。

What is the expected output? What do you see instead?
在完成上面1、2步骤时，候选词中有新添加的用户词组，如果现在关机，ibus会在/.ibus/tables目录下自动生成或者更新wubi-jidian86-user.db文件保存用户词组。我预期注销系统应该与关机一致，也会在/.ibus/tables目录下自动生成或者更新wubi-jidian86-user.db文件保存用户词组。但实际上没有。
Please provide any additional information below.
```

Original issue reported on code.google.com by `ubuntu.gary` on 2012-10-22 04:19:33

**Comment by mike-fabian** [comment]
Google code issue was: https://code.google.com/p/ibus/issues/detail?id=1538

**Comment by mike-fabian** [comment]
I cannot read Chinese.

Google translate translates the report as:

translate> ibus-table is not saved when you log off the user phrase
translate> 
translate> Please * DO NOT * ask question here! Please use
translate> https://groups.google.com/group/ibus-user
translate> 
translate> Please do not ask questions here, please use ibus user discussion group
translate> https://groups.google.com/group/ibus-user
translate> 
translate> What version of the product are you using? On what operating system?
translate> OS (Linux distributions, UNIX or ...): ubuntu 12.04
translate> Architecture (i386, x86_64): x86_64
translate> IBus version: IBus 1.4.1
translate> Input method name and version: ibus-wubi
translate> Python version:
translate> dbus version: 1.4.18-1ubuntu1.3
translate> dbus-python version: 1.0.0-1ubuntu1
translate> gtk version (if bug is about gtk applications):
translate> qt version (if bug is about qt applications):
translate> 
translate> What steps will reproduce the problem?
translate> 1. Use Shift_L key input when it is the first candidate to submit to pre-edit word phrase,
translate> 2. Enter the user phrase in the pre-edit mode, press the Space key word submit and save your entries,
translate> 3. To log off the system.
translate> 
translate> What is the expected output? What do you see instead?
translate> Upon completion of the above steps 1 and 2, the candidate word in the newly added user phrase, if we shut down, ibus will automatically generate or update wubi-jidian86-user.db file is saved in the user phrase /.ibus/tables directory. I expected out of the system should be consistent with the shutdown will automatically generate or update wubi-jidian86-user.db file is saved in the user phrase /.ibus/tables directory. But in fact it did not.
translate> Please provide any additional information below.

**Comment by mike-fabian** [comment]
This is surely fixed. I rewrote the code saving the user database. No newly added
words should be lost now when logging out or when the session crashes. The database
uses “PRAGMA user_db.journal_mode = WAL;”, user data is written immediately to the database
and not cached in memory anymore.
