### ISSUE TITLE
KDE lock screen

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1615]
```
OS (Linux distributions, UNIX or ...): Gentoo
Architecture (i386, x86_64): x86_64
IBus version: 1.5.1
Input method name and version: ibus-anthy 1.5.0
Python version: 2.7.3, 3.2.3
dbus version: 1.6.8
dbus-python version: 1.1.1
qt version (if bug is about qt applications): 4.8.4
KDE version: 4.10

What steps will reproduce the problem?
1. Switch to Japanese/Anthy layout.
2. Perform KDE screen lock
3. Try to deactivate the lock by enetering password.

What is the expected output? What do you see instead?
I can't switch back to English from Anthy using the trigger key, enter my password
and unlock.

In case this is a KDE problem I suggest implementing a list of apps for which a fixed
layout will be used.
```

Original issue reported on code.google.com by `renjoki` on 2013-02-22 10:39:05

**Comment by stalkerg** [comment]
This issue still exist with modern SDDM.

**Comment by fujiwarat** [comment]
@stalkerg I don't think this issue and yours are same.
Can you describe your issue with detail?

**Comment by stalkerg** [comment]
@fujiwarat sure, if I change my layout to Russian from English or Japanese and my screen will be locked I can't change the layout on the lock screen to enter a password (I am using the onscreen virtual keyboard now for that :( ).

**Comment by fujiwarat** [comment]
@stalkerg I still don't understand your issue.
It would be good to open a new issue to fill the issue template; which desktop and version, which distro, which ibus version.

**Comment by stalkerg** [comment]
@fujiwarat the same issue as in the main topic. 
1. Latest Plasma 20.20
2. Distr - Gentoo
3. Latest ibus version 

Again, if my current layout is not English I can't unlock screen because the password will input in the latest language (Russian or Japanese)
On lockscreen I can't change language, ibus hotkeys not working.
