### ISSUE TITLE
English (US) layout listed multiple times

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1774]
```
What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...): Lubuntu 14.10
Architecture (i386, x86_64): x86_64
IBus version: 1.5.8
Input method name and version: English (US) and Bengali itrans (m17n)
Python version: 2.7.9
dbus version: 1.8.8-1ubuntu2.1 from https://launchpad.net/ubuntu/+source/dbus
dbus-python version: 1.2.0-2build2
gtk version (if bug is about gtk applications):
qt version (if bug is about qt applications):

What steps will reproduce the problem?
1. ibus preferences > Input Method > Add > Bengali > itrans (m17n)
2. Logout/log back in
3. Click the layout icon on the system tray

See attachment for example

```

Original issue reported on code.google.com by `samee.zahur` on 2014-12-07 21:34:02

<hr>
- _Attachment: bug.png<br>![bug.png](https://storage.googleapis.com/google-code-attachments/ibus/issue-1758/comment-0/bug.png)_

**Comment by wujastyk** [comment]
I have the same issue, January 2016.
Linux Mint 17.3, 
Cinnamon 2.8.6, 
Ibus 1.5.5
using about four m17n keyboards.  UK English defaults on the system.

After using my system for a while, the English-English(US) keyboard gets surreptitiously added to the list of keyboards, and then begins to multiply.  The only way to get rid of it is to quit and restart Ibus.  I don't use US English, and it's not the default on my system.  I have UK English defaults and keyboard.  In the attached picture, the bottom keyboard, English (US), was *not* added by me in Ibus Prefs (see second image).

I had a look at "ibus reset-config" suggested above but that command parameter does not exist with ibus 1.5.5.

Dominik Wujastyk

![img_20160115_093539](https://cloud.githubusercontent.com/assets/762246/12358666/a94db95a-bb6b-11e5-81d4-bfb0ab77c35b.jpg)

And my actual prefs at the time:

![ibus prefs](https://cloud.githubusercontent.com/assets/762246/12358714/e1f68156-bb6b-11e5-8dfd-edb74445e723.png)

**Comment by fujiwarat** [comment]
ibus 1.5.5 is an old version and this problem has been fixed in the later ibus.
This bug happened because your session XKB keymaps are not supported by ibus and it's fallen back to "us" layout but ibus does not remove the existent "us" layout.

We won't update ibus 1.5.5.
The workaround is to change your default keymaps in Cinnamon to "us" layout and reset the ibus keymaps:

% gsettings get org.freedesktop.ibus.general preload-engines
['xkb:us::eng', 'xkb:us::eng']
% gsettings reset org.freedesktop.ibus.general preload-engines

You could confired your default keymap after disable ibus, log into the session again and run 'setxkbmap -query'.

**Comment by wujastyk** [comment]
Thank you!  I've updated ibus to a more recent version.
DW
​
