### ISSUE TITLE
Add support for keyboard LED

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#1785]
```
Standard Xorg server have built-in support for keyboard LED (scroll, caps and num locks).
Selected LED is enabled when keyboard is switched to alternate layout. You can see
it by your side vision of eyes without focusing to other screen area.
IBus, which replaces Xorg input on some distributions, have no support of this simple
but very usefull feature. I think it is not difficult to add it.
```

Original issue reported on code.google.com by `Sergey.Belyashov` on 2015-04-01 20:05:33

**Comment by Hi-Angel** [comment]
> > I try run setxkbmap -option "grp_led:scroll" manually, and then switch layout
> > and back, but led keept in off state
> 
> I don't know which feature you asked. Please investigate how to enable it by yourself.

The likely reason is that input source switch for non-gnome desktop is done in ibus by running *(for example)* `setxkbmap -layout us` and `setxkbmap -layout ru,us`. As result, *every* input source is primary from XKB POV, so the LED never lights on.

That actually seems to be a bug.

**Comment by Hi-Angel** [comment]
Hmm, sorry, I didn't unassign anyone o.o

**Comment by fujiwarat** [comment]
> setxkbmap -layout us and setxkbmap -layout ru,us

setxkbmap option won't be changed by the layout change.
You can check the option is not cleared with ``setxkbmap -query`` after you run ``setxkbmap -layout anything``.

**Comment by Hi-Angel** [comment]
> setxkbmap option won't be changed by the layout change.

It won't. The problem is that `grp_led:scroll` should enable the LED for secondary source. I.e. if you have `us,ru`, then LED lights on/off when you switch to/from ru.

But as ibus runs `setxkbmap -layout us` and `setxkbmap -layout ru,us`, so whatever input source is chosen, it's never secondary.

**Comment by fujiwarat** [comment]
OK, good to hear ibus's solution also resolves your issue.
You might like to report your issue in XKB instead.

**Comment by Hi-Angel** [comment]
> OK, good to hear ibus's solution also resolves your issue.

But it's not! In whatever way, ibus doesn't support LED indication of layout.

**Comment by fujiwarat** [comment]
> But it's not! In whatever way, ibus doesn't support LED indication of layout.

I think you switch 'us' and 'ru,us' with a IBus shortcut key and you don't see your problem because IBus does not switch layouts in 'ru,us' and you don't use the secondary?

**Comment by Hi-Angel** [comment]
Right, this is why `grp_led:scroll` option never actually lights on the LED.

But I want to point out the wider issue: ibus doesn't support it in any way, i.e. even for gnome desktop with a very special settings.

**Comment by fujiwarat** [comment]
> even for gnome desktop with a very special settings.

OK, got your meaning. However using XkbLockGroup() is implemented in "gnome-shell" ("mutter" internally) but not ibus and I guess gnome-shell won't change using XkbLockGroup() to using setxkbmap with their some reasons.
And actually your issue is caused by XKB API - XkbLockGroup() so it would be good to file your issue to XKB and probably we have nothing to discuss about this issue here.

It's not an IBus issue and I have no workaround in GNOME.

**Comment by fujiwarat** [comment]
> ibus doesn't support it in any way

No, ibus does not touch the GNOME implementation.

**Comment by Hi-Angel** [comment]
> It's not an IBus issue and I have no workaround in GNOME.

Fine. Then what's with non-gnome desktop? For them ibus doesn't have an option to enable LED, and the one native to XKB *(i.e. `grp_led:scroll`)* doesn't work well with the way ibus implements switching of input sources.

**Comment by Hi-Angel** [comment]
I [reported a bug to mutter](https://bugzilla.gnome.org/show_bug.cgi?id=773263).

**Comment by Hi-Angel** [comment]
> And actually your issue is caused by XKB API - XkbLockGroup() so it would be good to file your issue to XKB

Yeah, I don't think that XKB doesn't have a function to enable LED, so it's rather a mutter issue, I reported to them.

**Comment by fujiwarat** [comment]
> Fine. Then what's with non-gnome desktop? F

Don't say the same thing again.

>> I think you switch 'us' and 'ru,us' with a IBus shortcut key and you don't see your problem because IBus does not switch layouts in 'ru,us' and you don't use the secondary?

**Comment by Hi-Angel** [comment]
I thought you wanted to say "and you **do** see your problem because IBus does not switch layouts in 'ru,us' and you don't use the secondary?", then it's right, it's the explanation why the `grp_led:scroll` doesn't light a LED.

But I doesn't see how does it answer the "Fine. Then what's with non-gnome desktop?". It's just restatement of the fact.

**Comment by fujiwarat** [comment]
Because ibus does't expect to switch layout with the XKB shortcuts.
Using ibus shortcut key ``Super-space`` by default switches "us" and "ru,us" and I don't expect to switch layouts in "ru,us"

**Comment by Hi-Angel** [comment]
Right. So, may be would it worth to modify ibus in such a way so that it would light on/off a LED for a layout on its own?

The demand for the option is high, [see e.g. this bug](https://bugs.launchpad.net/ubuntu-gnome/+bug/1245188).

**Comment by fujiwarat** [comment]
> The demand for the option is high

I think there is no reason to use XKB switching shortcut keys instead of IBus switching shortcut keys on IBus.

**Comment by Hi-Angel** [comment]
> I think there is no reason to use XKB switching shortcut keys instead of IBus switching shortcut keys on IBus.

I'm not talking about using XKB shortcut, I'm talking about implementing the LED light internally to IBus.

**Comment by fujiwarat** [comment]
> I'm not talking about using XKB shortcut

But you said the first layout enables LED but the second layout does not enable LED. IBus does not expect to use the second layout.
