### ISSUE TITLE
ibus在Tweetdeck的New Tweet页面里候选词框可能会移出屏幕

### ISSUE THREAD

**Issue by carlnerv** [ibus/ibus#1801]
OS (Linux distributions, UNIX or ...): Fedora
Architecture (i386, x86_64): x86_64
IBus version: 1.5.10
Input method name and version: ibus-libpinyin-1.7.1
Python version: 3.4.1
dbus version: 1.8.18
dbus-python version:  1.2.0

What steps will reproduce the problem?
1. 打开 tweetdeck.twitter.com, 并登录
2. 打开 New Tweet, 然后输入一些中文，这时候选词框与光标是右对齐状态，即候选词框在光标左下，如果浏览器贴着屏幕左端，候选词框会移出屏幕，严重影响输入

What is the expected output? What do you see instead?
希望候选词框不要移出屏幕

Please provide any additional information below.
thx for your work.

**Comment by fujiwarat** [comment]
Please try ibus-libpinyin and if you have any problems, file it to https://github.com/libpinyin/ibus-libpinyin/issues .
Thanks.

**Comment by fujiwarat** [comment]
It seems you're describing the lookup window position.
Can you attach the screenshot of your problem?

% gnome-screenshot -i

**Comment by carlnerv** [comment]
![Uploading 截图 - 2015年06月11日 - 12时07分40秒.png…]()
![Uploading 截图 - 2015年06月11日 - 12时10分53秒.png…]()

It's hard to take screenshot.

**Comment by carlnerv** [comment]
![- 2015 06 11 - 12 07 40](https://cloud.githubusercontent.com/assets/1898460/8099717/d659bbda-1033-11e5-9795-51af2ce9092b.png)
![- 2015 06 11 - 12 10 53](https://cloud.githubusercontent.com/assets/1898460/8099718/d65a98b6-1033-11e5-95ba-dde74dfec28b.png)

It's hard to take screenshots.

**Comment by fujiwarat** [comment]
CC'ing @epico

**Comment by fujiwarat** [comment]
OK, I understood your problem.
I guess tweetdeck.twtter.com has a hidden gdk window and a part of it is the input box.
I'd suggest another gdk window for the input box to tweetdeck.twtter.com to give the right cursor position.
However I accept ibus should not show the lookup window at the minus position of the screen.

**Comment by fujiwarat** [comment]
Fixed.
https://github.com/ibus/ibus/commit/bd7673e73c2a8c54d2a827603a960d76dab7be1b
