### ISSUE TITLE
RFE: please offer a way to exclude input sources from the switch ring

### ISSUE THREAD

**Issue by leggewie** [ibus/ibus#1803]
https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1304293

I have four input sources defined for ibus: de1,de2,anthy and mozc. Normally, I switch between de1 and anthy and use de2 and mozc only occasionally. It would be nice to be able to exclude them from the "switch ring" when hitting Super+Space for easier and quicker switching. In that case, I'd have to explicitly choose them from the ibus applet.

**Comment by fujiwarat** [comment]
Could you explain why you need that function with detail?
I think you wish to switch de1 and anthy with Super+space.
Then you don't have to press space more than twice?
Even if you would press space twice by mistake, you could bring back the selection with Super+Shift+space?

**Comment by leggewie** [comment]
Fujiwara-san, thank you for your question which I will gladly answer.

I was not aware of the hotkey for switching backwards.  Thank you for educating me.

Since the ring of input methods looks like "de1-de2-anthy-mozc" I'd still have to hit whichever hotkey twice.  The real problem though is that I first need to make a visual check of what input method I am currently in.  If the "ring" included only two options "de1-anthy" it would require a lot less attention.  I would *not* have to trigger my brain between forward- and backward-switching, it would simply be Super+space every time.  Furthermore, I do not need to check if I am at position 3 "anthy" or position 4 "mozc" when attempting to switch to de1 and then adjust the number of hotkey hits accordingly. Whenever I realize I am in the wrong input environment I'd simply have to hit the switcher hotkey once and be in the proper environment.

This sounds trivial but is a great hindrance to efficiency.  I hope you can see what I mean.  It's like having to position your hand for the mouse which only takes a split second but still breaks the flow of typing work.

**Comment by beroal** [comment]
Hi, leggewie. Once upon a time, there was a suggestion to allow to assign a distinct hotkey to every input method. Than, after you press a hotkey for X, X is active regardless of the input method that was active before. Maybe this suggestion better match your case?

**Comment by leggewie** [comment]
@beroal I'd be fine with that, I guess.

**Comment by fujiwarat** [comment]
> The real problem though is that I first need to make a visual check of what input method I am currently

Why do you need it?
The current ibus engine is shown on the ibus panel icon.
And if you would use the first two engines frequently, you could know what are the engines.
I guess Super+Shift+space can resolve your problem when you type Super+space by mistake.
Also you could release the space key quickly before the IME switcher list would be shown with Super+space.
You can set Super+space with the first two engines only with hiding the switcher list:
% gsettings get org.freedesktop.ibus.general switcher-delay-time
400
% gsettings set org.freedesktop.ibus.general switcher-delay-time -1

**Comment by leggewie** [comment]
Fujiwara-san, it's sad to see this closed in such a rush.

On 23.06.2015 10:34, Takao Fujiwara wrote:
>     The real problem though is that I first need to make a visual check
>     of what input method I am currently
> 
> Why do you need it?

I thought I had explained that.

Repositioning of the eye or hand causes a break in the work-flow and is
detrimental to efficiency.  Typing efficiently is important.

> The current ibus engine is shown on the ibus panel icon.

Yes, I can check there.  And it only takes a split-second or so.  But it
is still an interruption.  Just like grabbing for the mouse which is
also quick but still an interruption.　　These kind of things kill
efficiency by forcing the brain to drop what it is doing and switch states.

> I guess Super+Shift+space can resolve your problem when you type
> Super+space by mistake.

I'm afraid that no, this will not resolve the problem as described above.

> Also you could release the space key quickly before the IME switcher
> list would be shown with Super+space.

I don't think that happens in my setup (Ubuntu trusty and Unity). The
only switcher list that I can think of requires use of the mouse.

> You can set Super+space with the first two engines only with hiding the
> switcher list:
> % gsettings get org.freedesktop.ibus.general switcher-delay-time
> 400
> % gsettings set org.freedesktop.ibus.general switcher-delay-time -1

See above, I think this does not apply to my setup somehow.

**Comment by leggewie** [comment]
I thought that the idea of having the possibility to assign fixed keys to jump to a certain input method was a great idea and it would have resolved my issue.  Since that has come up in the past why is it not even considered?

**Comment by fujiwarat** [comment]
> And it only takes a split-second or so. But it is still an interruption. 

I don't understand your mention. the ibus panel shows permanently and you can check the current ibus engine anytime.

> I don't think that happens in my setup (Ubuntu trusty and Unity).

It would be an Unity issue. If you use XFCE or LXDE or KDE or else, this and gsettings works.
Then your issue is not an upstream bug.

**Comment by leggewie** [comment]
Fujiwara-san, thank you for staying with this topic at least for now.

On 24.06.2015 12:24, Takao Fujiwara wrote:
>     And it only takes a split-second or so. But it is still an
>     interruption.
> 
> I don't understand your mention. the ibus panel shows permanently and
> you can check the current ibus engine anytime.

Yes, I noticed you don't understand why I think this is an issue.

Again, it is about efficiency.  Interruptions cause the brain a great
deal of pain and result in loss of efficiency.  I mentioned a few
examples.  There's countless scientific and work ergonomics studies on
this. Just because the information *is* there, which noone is disputing,
doesn't mean that being forced to actually get it won't cause a state
break and resulting efficiency loss.

I hope someone can pitch in with the scientific term for this effect.
Unfortunately, I cannot remember.  I think it's something along the
lines of a "state break", the brain has to switch from one mode to
another and back.  It's possible, but slow.

>     I don't think that happens in my setup (Ubuntu trusty and Unity).
> 
> It would be an Unity issue. If you use XFCE or LXDE or KDE or else, this
> and gsettings works.
> Then your issue is not an upstream bug.

I cannot dispute this with authority without seeing what you are
referring to with the "switcher list".

But I do think you can't make the claim of this being an upstream bug
either without understanding what the bug is actually about (see above).

I do believe you are talking about some visual pop-up or something.  If
so, this would do *nothing* to address the issue I raised here. I have a
hard time imagining how this would be a downstream issue.

**Comment by fujiwarat** [comment]
> But I do think you can't make the claim of this being an upstream bug

You should try other DEs if you see your problem. Ubuntu has the own panel and the short cut keys are managed by the panel.

**Comment by fujiwarat** [comment]
Hope you will test other DEs immediately and notice why this is not an upstream bug.
