### ISSUE TITLE
Not working on Mate desktop environment

### ISSUE THREAD

**Issue by syamgk** [ibus/ibus#1805]
While typing, the input does not show up in the text box/display area 
but in phonetic mode the drop down is coming.

On,
Mate 1.8.1
IBus 1.5.9

**Comment by fujiwarat** [comment]
I cannot reproduce your problem with mate 1.8.1

![mate-desktop-fujiwara](https://cloud.githubusercontent.com/assets/105929/8590349/b72b9b2e-265a-11e5-9bd6-74b503f254e1.png)
