### ISSUE TITLE
candidate window isn't located under composing string when HiDPI setting

### ISSUE THREAD

**Issue by makotokato** [ibus/ibus#1806]
# ENV
- GNOME 3.16
- GTK 3.16
- ibus 1.5.10
# STEP
1. gsettings set org.gnome.desktop.interface scaling-factor 2
2. Restart GNOME Shell
3. Launch gnome-terminal
4. Input ああああ using fcitx-mozc
# RESULT

Candidate window position isn't under composing string.  ibus should consider scaling factor.
![screenshot from 2015-07-09 12-48-33](https://cloud.githubusercontent.com/assets/965338/8587598/feba86b6-2638-11e5-8fda-92601f0165f2.png)

Also, fcitx has same bug as https://github.com/fcitx/fcitx/issues/211

**Comment by fujiwarat** [comment]
I can reproduce this bug with ibus engines.
Reported https://bugzilla.gnome.org/show_bug.cgi?id=752160

**Comment by ahxxm** [comment]
can reproduce this in chromium, but not in xfce4-terminal, i'm using i3wm, dell p2415q with dpi 175/200

**Comment by ahxxm** [comment]
补图。。 

![image](https://cloud.githubusercontent.com/assets/1286225/19293982/729814ee-905b-11e6-9fae-78e39b8305ed.png)

![image](https://cloud.githubusercontent.com/assets/1286225/19293985/76c2ca5a-905b-11e6-93e5-8efc2e00eca4.png)

**Comment by aizigao** [comment]
我也想遇到了，怎么解决这个问题呢

**Comment by aizigao** [comment]
我也遇到了，你怎么解决的

**Comment by Hexcles** [comment]
Still unsolved, unfortunately.

**Comment by fujiwarat** [comment]
The 'scaling-factor ' issue happens in gnome-shell only and does not afffect GNOME2 desktop.

**Comment by fujiwarat** [comment]
@sfanxiang Provided the patch.
I didn't think this can be fixed in IBus side.
