### ISSUE TITLE
Add a release note to future versions of Ibus

### ISSUE THREAD

**Issue by Jiehong** [ibus/ibus#1809]
Hello,

Currently, finding the release notes for Ibus is not quite easy without Git, and not that easy to read.

For example, the NEWS file could certainly be used for that, but is currently empty.

I would see 2 options for this:
- either the NEWS file contains the description of changes for each version;
- either the NEWS file is only present in the tag commit, thus showing changes specific to the given tag only.

Either way, it would be great to have such a thing :)

**Comment by fujiwarat** [comment]
Why do you need git?
You can see the release notes on web: https://github.com/ibus/ibus/releases
Also ChangeLog in the tarball can explains the commit logs.
ChangeLog is generated from ibus/Makefile.am

**Comment by Jiehong** [comment]
Oops, I didn't see the release are on github.

However, what is the point of having an empty NEWS file in the repository then?

**Comment by fujiwarat** [comment]
NEWS file is needed for a GNU build tool but probably we won't update the file by manual.
ChangeLog is enough for us.

**Comment by fujiwarat** [comment]
The later ibus tarball has includes NEWS file which is generated automatically.
https://github.com/ibus/ibus/commit/350140e2db5af88c05a4de8a13ce0589c057424e
