### ISSUE TITLE
Building ibus-1.5.5-1ubuntu3 fails with Makefile "missing separator" error

### ISSUE THREAD

**Issue by dbarnett** [ibus/ibus#1810]
I'm trying to build the Ubuntu source package of ibus from Ubuntu 14.04 and after `apt-get source`, `./configure`, and `make` I see this error:
```
Making all in gtk3
make[3]: Entering directory `/home/dbarnett/Downloads/ibus-1.5.5/ui/gtk3'
 cd ../.. && /bin/sh ./config.status ui/gtk3/Makefile depfiles
config.status: creating ui/gtk3/Makefile
config.status: executing depfiles commands
make[3]: Leaving directory `/home/dbarnett/Downloads/ibus-1.5.5/ui/gtk3'
make[3]: Entering directory `/home/dbarnett/Downloads/ibus-1.5.5/ui/gtk3'
Makefile:1067: *** missing separator.  Stop.
make[3]: Leaving directory `/home/dbarnett/Downloads/ibus-1.5.5/ui/gtk3'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/dbarnett/Downloads/ibus-1.5.5/ui'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/dbarnett/Downloads/ibus-1.5.5'
make: *** [all] Error 2
```

The referenced ui/gtk3/Makefile file looks like this around line 1067:
```
1060 gtkpanel.xml: gtkpanel.xml.in
1061 »	$(AM_V_GEN) sed \
1062 »	»	-e 's|@VERSION[@]|$(VERSION)|g' \
1063 »	»	-e 's|@libexecdir[@]|$(libexecdir)|g' $< > $@.tmp && \
1064 »	»	mv $@.tmp $@
1065 
1066 @ENABLE_LIBGNOMEKBD_TRUE@$(srcdir)/gkbdlayout.vala: $(top_builddir)/bindings/vala/gkbd.vapi
1067 @ENABLE_LIBGNOMEKBD_TRUE@»	@cp $(srcdir)/gkbdlayout.vala.true $(srcdir)/gkbdlayout.vala
1068 @ENABLE_LIBGNOMEKBD_FALSE@$(srcdir)/gkbdlayout.vala:
1069 @ENABLE_LIBGNOMEKBD_FALSE@»	@cp $(srcdir)/gkbdlayout.vala.false $(srcdir)/gkbdlayout.vala
```

I'm not too familiar with GNU autotools, but it doesn't look like normal valid Makefile syntax. Maybe some kind of autoconf directive failed to expand?

(Note: I also had to edit a hard-coded `am__api_version='1.13'` in the configure script to 1.14, which was the automake version installed on my system, but I don't know that's directly related.)

**Comment by fujiwarat** [comment]
Since you try to get the sources from apt system, the build should be successful. Otherwise the integration would be failed.
I don't think running configure directly is the right way in Ubuntu apt.
https://wiki.debian.org/HowToPackageForDebian
