### ISSUE TITLE
Anthy Command "on_off" Has No Effect in Firefox

### ISSUE THREAD

**Issue by NoSuck** [ibus/ibus#1811]
Hello.  I do not use Firefox often and only recently discovered its inability to accept input from ibus-anthy.  Program versions (on Arch Linux):

* ibus 1.5.11-1
* ibus-anthy 1.5.7-1
* firefox 40.0.2

Other GTK2 applications, like kasumi, react to on_off accordingly, so the problem is probably with Firefox!  I was wondering, however, if anyone else experiences this problem.

**Comment by fujiwarat** [comment]
I don't understand your problem.
kasumi does not have on_off command.
Did you try other input method engines besides ibus-anthy?

**Comment by NoSuck** [comment]
I explained that poorly.

I should have said that ibus is okay with GTK2 applications in general, just not Firefox.  Kasumi was one example that I tested.  I also tested GTK3 and Qt applications.  They were all fine.

I have ibus-anthy's on_off bound to Ctrl + space.  Normally, this changes from direct input to Japanese input, but the change never happens in Firefox.  It stays direct input.

**Comment by beroal** [comment]
> I do not use Firefox often and only recently discovered its inability to accept input from ibus-anthy.
test おしえる　教える
I use the same Linux distribution and program versions. I've switched to Anthy with Ctrl+Space.

**Comment by fujiwarat** [comment]
>  ibus is okay with GTK2 applications in general

Really? Did you confirm your problem is not reproduced with thunderbird or xchat-gnome?
I still don't understand why you indicate kasumi which does not have Ctrl+space shortcut key.

> What other engine would be good to try?

You could choose one of ibus-hangul, ibus-libpinyin or ibus-m17n.

Can you check the result of strace?

% strace /usr/lib*/firefox/firefox 2>&1 | grep immodules

**Comment by fujiwarat** [comment]
Any updates?

**Comment by picsi** [comment]
I just had this bug, and it happened because I ran `ibus restart` while Firefox was opened. Restarting Firefox fixed it for me.
