### ISSUE TITLE
Can't use Alt+Shift for switching layouts on Ubuntu Studio 15.04

### ISSUE THREAD

**Issue by techtonik** [ibus/ibus#1816]
I wasn't able to enter Alt+Shift combination in Xfce to switch layouts. Is by design or just a bug?

**Comment by fujiwarat** [comment]
ibus-setup requires Modifiers key + normal key bindings but both Alt  and Shift is modifiers keys so you cannot register Alt+Shift with ibus-setup.
But command line can register the keybinding:

```
% gsettings get org.freedesktop.ibus.general.hotkey triggers
['<Super>space']
% gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt>Shift_L']"
```

**Comment by fujiwarat** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/1128
