### ISSUE TITLE
Super+Space cannnot change IMEs in Cinnamon desktop

### ISSUE THREAD

**Issue by Frederick888** [ibus/ibus#1817]
如题，Super+Space会输入一个空格，Super+Space+Space...才开始切换输入法

运行环境是Fedora 22 + Cinnamon，ibus版本为1.5.10

不知如何解决？多谢

**Comment by fujiwarat** [comment]
Thank you for the report. I can reproduce your problem.
The workaround is:
Run "cinnamon-settings" command and select "Applet" -> "Menu" and click "Settings" button.
Change the short cut "Super_L" in "Keyboard shortcut to open and close menu" to "<Super>Up".

I think this is a bug in cinnamon and filed https://bugzilla.redhat.com/show_bug.cgi?id=1260850

**Comment by Frederick888** [comment]
@fujiwarat Thanks a lot.

**Comment by madmalkav** [comment]
The Fedora bug never got solved .This still happens with Cinnamon in Manjaro Linux , so probably addressing a bug report to the Cinnamon team at https://github.com/linuxmint/Cinnamon/issues will be needed.

**Comment by fujiwarat** [comment]
> so probably addressing a bug report to the Cinnamon team at https://github.com/linuxmint/Cinnamon/issues will be needed.

Please file the bug. Probably I think the Fedora maintainer and upstream one is same and said no resource in the downstream bug. Myself is also busy for other tasks and I provided the workaround above.

**Comment by madmalkav** [comment]
Ok.
