### ISSUE TITLE
the pinyin for love does not appear

### ISSUE THREAD

**Issue by josephchum** [ibus/ibus#1818]
tried to type ai into pinyin but no result

**Comment by fujiwarat** [comment]
I cannot reproduce your problem with both ibus-pinyin and ibus-libpinyin.

**Comment by josephchum** [comment]
Hi,

You could use the pinyin to type out the word love? i tried 'ai' is it
using alternative pinyin?

**Comment by fujiwarat** [comment]
See ![ai](https://cloud.githubusercontent.com/assets/105929/9754421/fabb6930-5703-11e5-9a9d-1c2e6f1f1a74.png)
