### ISSUE TITLE
Type dead keys without dead keys

### ISSUE THREAD

**Issue by Riamse** [ibus/ibus#1820]
In some cases it's useful to be able to type combining characters, such as U+0302. 
In /usr/share/X11/locale/en_US.UTF-8/Compose there is this line:
```
<dead_circumflex> <nobreakspace>      : "̂"   U0302               # COMBINING CIRCUMFLEX ACCENT
```
Unfortunately, this is literally untypable if you don't have dead keys. This is problematic. Are there any solutions?

**Comment by fujiwarat** [comment]
Create a new keymap in /usr/share/X11/xkb with dead_circumflex or use xmodmap.
