### ISSUE TITLE
Allow setting Alt+Shift combination in ibus-setup

### ISSUE THREAD

**Issue by techtonik** [ibus/ibus#1821]
From #1816 it is possible to set Alt+Shift as language switch combination from command line, but not from ibus-setup.

**Comment by fujiwarat** [comment]
It would be a limitation in GTK+.
'gnome-control-center keyboard' also cannot configure Modifiers key + Modifiers key.

**Comment by techtonik** [comment]
@fujiwarat I am not sure what are you speaking about. After ditching ibus I could resolve the problem and get `Alt+Shift` working - http://askubuntu.com/a/671187/51852

I am not sure why you don't want `ibus` to support this feature. For me closing this issue clearly contradicts with one of the primary IBus goals - `providing full-featured and user-friendly input-method user-interfaces` https://en.wikipedia.org/wiki/Intelligent_Input_Bus

**Comment by fujiwarat** [comment]
I mean the problem is in gtk3 but not ibus.

**Comment by fujiwarat** [comment]
I filed the bug for you.
https://bugzilla.gnome.org/show_bug.cgi?id=756107

**Comment by techtonik** [comment]
@fujiwarat FYI I am not using Gnome - the issue I experienced is on Xfce.

**Comment by fujiwarat** [comment]
See the source code.

**Comment by exebook** [comment]
Just to add two cents here, in Russia and ex-USSR countries, 99% of computers use Alt-Shift to switch between RU/EN/UKR/KAZ etc. So this is an important issue for us, millions and millions are just used to Alt-Shift.

**Comment by techtonik** [comment]
@exebook we need to escalate the issue through other channels somehow. This issue is already closed and @fujiwarat is not interested to resolve it as we are.

**Comment by fujiwarat** [comment]
> @fujiwarat is not interested to resolve it as we are.

As I explained, this is not a bug in ibus.

**Comment by techtonik** [comment]
@fujiwarat but `ibus-setup` is `ibus` application, right? So until upstream bug is fixed, it may have a user level instruction how to achieve that and where to find the bug.

**Comment by techtonik** [comment]
@fujiwarat well, I see you've attached the patch, so I am not right here. But how can we bring somebody to take a look at the patch?

**Comment by fujiwarat** [comment]
gtk staffs already reviewed the patch and added it's an accessibility issue.

I provided a workaround for this issue in bug #1816

**Comment by techtonik** [comment]
@fujiwarat this workaround is not visible to users. They have no chance even to discover this tracker.

**Comment by fujiwarat** [comment]
You can see this report otherwise no easy workaround until gtk is fixed.
You can still add a custom keymap in /usr/share/X11/xkb/symbols directly so that the position of Alt is not Alt.

**Comment by techtonik** [comment]
@fujiwarat fixing problem for me doesn't fix it for other 1.000+ Ubuntu users.

**Comment by techtonik** [comment]
Is it possible to provide user level details in UI?

**Comment by fujiwarat** [comment]
> Is it possible to provide user level details in UI?

GUI is GTK.

**Comment by techtonik** [comment]
Whose program is `ibus-setup` then?

**Comment by fujiwarat** [comment]
yes.

**Comment by techtonik** [comment]
whatever.

**Comment by fujiwarat** [comment]
?

**Comment by fujiwarat** [comment]
Anyway, you should convince gtk.

**Comment by techtonik** [comment]
I mean that the `ibus-setup` is maintained in this repository, not in GTK, so user warnings about current workarounds should be implemented here, not in upstream lib. Am I right?

**Comment by fujiwarat** [comment]
ibus-setup is based on GTK and ibus-setup does not touch the key event.

**Comment by techtonik** [comment]
Well, I am behind a different screen right now, so there is no actual screenshot of `ibus-setup` in front of me. Is that the latest picture?

![](https://desktopi18n.files.wordpress.com/2012/05/ibus-setup-for-1-5.png)

In that case it could provide a field to enter key name manually without relying on buggy "key event" from Gtk until this bug is fixed upstream.

**Comment by fujiwarat** [comment]
> Is that the latest picture?

No, it's too old against IBus upstream. That way is no verification for the user typing and now deprecated.
Actually the current gsettings workaround and the old GUI is not so different. gsettings is fully supported by ibus upstream.

I don't think it's the right way not to use a library if it has a bug but should be fixed.
The discussion point seems GTK staffs thinks double modifiers keys "<Alt><Shift>" is not a good shortcut key against a11y. E.g. another application could have "<Alt><Shift>c" and the shortcut keys would be conflict.
Then "<Alt><Shift>" is a deprecated shortcut key but ibus provides the workaround with gsettings.

**Comment by techtonik** [comment]
> The discussion point seems GTK staffs thinks double modifiers keys "<Alt><Shift>" is not a good shortcut key against a11y. 

I don't get that point. Should we all cripple our left hand to enjoy this new a11y? "<Alt><Shift>" is convenient - I thought that Gnome is about usability and UX - what's going on? Why don't give people a choice to use those keys that they want without additional obstructions?

**Comment by fujiwarat** [comment]
I think here is not the right place to discuss it.
I also think there is no reason not to fix gtk.
It would be good for you to convince gtk in https://bugzilla.gnome.org/show_bug.cgi?id=756107
