### ISSUE TITLE
preedit text should be forgotten if the candidate panel was closed when window lost focus

### ISSUE THREAD

**Issue by salty-horse** [ibus/ibus#1826]
Using 1.5.9-1ubuntu3

1) Open gedit, and gnome-terminal, with both visible side-by-side
2) Use an IME with a candidate panel, such as Pinyin, and type some letters in the gedit window.
3) Without confirming, click the gnome-terminal window. The candidate panel will disappear.
4) Focus on the gnome-terminal window and type some letters. The pre-edit text previously typed will be restored in the new window.

I think that if a candidate panel was closed for any reason, the preedit text should always start empty.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem in XFCE4.
If it's Unity specific, it's not a bug in ibus.
![fujiwara-pinyin](https://cloud.githubusercontent.com/assets/105929/11025985/745817b8-86e6-11e5-9b4a-0b51fe2cd82a.png)

**Comment by salty-horse** [comment]
I'm sorry, you're right. I tested it with an IME other than Pinyin (in "Classic Gnome" and XFCE), so the bug must be there.
Sorry again :(
