### ISSUE TITLE
Update dependency list

### ISSUE THREAD

**Issue by timrae** [ibus/ibus#1829]
Hi I'm trying to install from source (tried both git clone and tar) but I can't get past the following error:

```
checking for DBUS... yes
checking for DCONF... no
configure: error: Package requirements (dconf >= 0.7.5) were not met:

No package 'dconf' found
```

I'm on Ubuntu 14.04.

**Comment by fujiwarat** [comment]
Ubuntu should provide dconf devel package.

**Comment by mkulak** [comment]
I have the same problem. Could you please provide some details how to install dconf >= 0.7.5?

**Comment by fujiwarat** [comment]
http://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=d-conf&searchon=sourcenames

**Comment by lv7777** [comment]
@fujiwarat 
i can't understand...
prease tell me i should install `apt-get install ???`

**Comment by fujiwarat** [comment]
Install dconf devel package from above site.

**Comment by wi24rd** [comment]
In ubuntu 18.04, there has only these packages:
dconf-cli                dconf-editor             dconf-gsettings-backend  dconf-service            dconf-tools
I installed all of these, but it still say break say lack of dconf.
Could you help me?

**Comment by wi24rd** [comment]
BTW, when I try to compile and install dconf, when I run "ninja -C builddir install" it says:
ModuleNotFoundError: No module named 'mesonbuild'

**Comment by wi24rd** [comment]
fine, just install libdconf-dev
