### ISSUE TITLE
How to put candidate window next to the actual input

### ISSUE THREAD

**Issue by allan-simon** [ibus/ibus#1830]
currently the candidate window always show in the bottom left border of the software, but it would be easier to use if it was possible to have it right below where the text is being input.  It makes sense especially on huge screen, where I currently have to  look down , look up while typing.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.
![fujiwara-candidate](https://cloud.githubusercontent.com/assets/105929/11356794/756ef206-92a4-11e5-93e0-1f96332d6f53.png)

**Comment by allan-simon** [comment]
well it's a bit harsh to close the issue without asking me more precision :/ 
on lubuntu (lxce desktop) I can reproduce it on all my laptop/desktop,  both 14.04 / 14.10. and 15.04

**Comment by fujiwarat** [comment]
I can accept any questions but I think this is not a bug in upstream since LXDE works fine with IBus.
Did you try gedit or gnome-terminal?
Probably you don't install ibus gtk2 module or set GTK_IM_MODULE=ibus.

**Comment by allan-simon** [comment]
thanks, i'm gonna try this and i'll come back to you.
