### ISSUE TITLE
GEN ibusmarshalers.h /bin/bash: --prefix=_ibus_marshal: command not found ?

### ISSUE THREAD

**Issue by atlance** [ibus/ibus#1832]
[![asciicast](https://asciinema.org/a/5ay4k09n9g4q84jvdp6s1jtae.png)](https://asciinema.org/a/5ay4k09n9g4q84jvdp6s1jtae)

**Comment by fujiwarat** [comment]
Because you don't install glib-2.0.pc file you could ask your distribution the package name of glib2 devel.
