### ISSUE TITLE
layout varient for m17n

### ISSUE THREAD

**Issue by rhoit** [ibus/ibus#1833]
I'm trying to fix, layout variant (dvorak for me) for m17n, 

I see there is the layout variant for xkb only:
![screenshot28](https://cloud.githubusercontent.com/assets/1684754/11598099/ff65daec-9ae7-11e5-9f3f-7f48eb1390c1.png)

but for m17n there no such option.
![screenshot29](https://cloud.githubusercontent.com/assets/1684754/11598109/14a17e98-9ae8-11e5-9dc2-6dffc6ace213.png)

# solution tried so far
## editing component xml (failed)
After reading issue #1467 about the `<layout_variant>dvorak</layout_variant>`
looking at the `/usr/share/ibus/component/m17n.xml` there was nothing like it then I realize
`/usr/lib/ibus/ibus-engine-m17n --xml` is generating xml for `m17n.xml` engine.

but still `layout_variant` tag was empty

```xml
    <layout_variant></layout_variant>
```
I tried to modify as

```xml
    <engines exec="/usr/lib/ibus/ibus-engine-m17n --xml | /usr/bin/sed 's/\(layout_variant.\)/\1dvorak/g'" />
```
but still there is no success.

## run setkbmap (temporary)
only way i could use old mapping is every time i change layout run `setxkbmap dvorak`. but ibus automatically resets it when I toggle it.

## rewrite mim file (workable)
I re-wrote m17n mim file in dvorak, but still shortcuts keys are big problem.

**Comment by rhoit** [comment]
i finally found the work around, since ibus calls the `setxkbmap` i wrote the wrapper around it and kept is as setxkbmap

```bash
args=$(echo "$*" | sed 's/us -option/dvorak/')
>&2 echo modified_args: ${args[*]}
/usr/bin/setxkbmap ${args[*]}
```

**Comment by fujiwarat** [comment]
I guess you could add some lines in /usr/share/ibus-m17n/default.xml while I don't try it actually.
E.g.
'''
&lt;engine&gt;
&nbsp;&nbsp;&lt;name&gt;m17n:hy:kbd&lt;/name&gt;
&nbsp;&nbsp;&lt;layout_variant&gt;drorak&lt;/layout_variant&gt;
&lt;/engine&gt;
'''
The m17n bug report is https://github.com/ibus/ibus-m17n/issues

**Comment by rhoit** [comment]
thanks @fujiwarat, sorry I posted in wrong repo will be looking at ibus-m17n.
Any way i got the temporary fix working.
