### ISSUE TITLE
Use a proper value for xkb status icon label.

### ISSUE THREAD

**Issue by galtgendo** [ibus/ibus#1834]
-- sorry, hit enter to early

For xkb engine labels ibus seems to use first two letters of "language" field from /usr/share/ibus/component/simple.xml.

However, that's a bogus value.

It should either use full field value (however some of those look bogus too), last part of name field or layout field.

For example, for Polish, either PL or POL are valid values, PO isn't one.

**Comment by fujiwarat** [comment]
Thank you for the report.
Currently just trim the three alphabets to two.
Probably ibus needs the conversion ISO 639-2 to ISO 639-1 or have an exception of Polish.

**Comment by galtgendo** [comment]
Chances are Polish isn't the only such case - it's simply that most people don't bother to raise stink about it (even here it took quite a few months till I grew sufficiently annoyed with it).
