### ISSUE TITLE
Invalid tag in fr.po translation of ibus-pinyin

### ISSUE THREAD

**Issue by happyaron** [ibus/ibus#1836]
There is an invalid tag in fr.po on master branch of ibus-pinyin, which affects the build process:

#: ../setup/ibus-pinyin-preferences.ui.h:15
msgid "<b>UI</b>"
msgstr "<b>UI<b/>"

https://github.com/ibus/ibus-pinyin/blob/master/po/fr.po#L117

**Comment by fujiwarat** [comment]
@phuang 
Do you update fr.po ?

  msgid "&lt;b&gt;UI&lt;/b&gt;"
\- msgstr "&lt;b&gt;UI&lt;b/&gt;"
\+ msgstr "&lt;b&gt;UI&lt;/b&gt;"

**Comment by fujiwarat** [comment]
You can use ibus-libpinyin.
