### ISSUE TITLE
IBusPanelService::set-cursor-location my report wrong cursor location

### ISSUE THREAD

**Issue by lanoxx** [ibus/ibus#1838]
Hi IBus devs,

I think that IBus sometimes reports wrong x,y coordinates in the `set-cursor-location` signal callback.

Here is an example. 

1. I open a terminal and press enter until I am at the last line of the terminal.
2. At the same time I am printing the results of the signals callback in another terminal.
3. When I have reached the last line of the terminal then my y position should not change anymore, because each time I hit enter again I am still on the last line of the terminal window and it cannot go any further down.

However what I am observing is this:

** Message: set_cursor_location_cb: x: 1062, y: 845  # reached the last line
** Message: set_cursor_location_cb: x: 1062, y: 881  # pressed enter again
** Message: set_cursor_location_cb: x: 1062, y: 845  # pressed the backspace key

As you can see, pressing enter again adds 36 pixels to the y location even though the character did not change its position -- since I just pressed enter and I was on the last line.

You can also notice that when I hit backspace, then the location is reported correct again.

I searched through the open issues but could not find a matching issue. Please let me know if there is anything you guys can do to fix this.

Oh, I tried this with ibus 1.5.5 and 1.5.10, I currently do not have 1.5.11 available so cannot try with it.

**Comment by fujiwarat** [comment]
It's a vte bug from gnome-terminal.

**Comment by lanoxx** [comment]
@fujiwarat Thanks for the response, do you happen to have a bug report number or some other clue for me, so I can track the issue in VTE?

**Comment by fujiwarat** [comment]
Please file a bug for vte.

**Comment by lanoxx** [comment]
I this bug looks like the right one: https://bugzilla.gnome.org/show_bug.cgi?id=756141
