### ISSUE TITLE
ibus_lookup_table_get_number_of_candidates sometimes reports wrong number of candidates

### ISSUE THREAD

**Issue by lanoxx** [ibus/ibus#1839]
Hi IBus devs,

I think that `ibus_lookup_table_get_number_of_candidates` sometimes reports a wrong number of candidates. For example when I switch to Chinese input and type `d`, then there are obviously more than 5 candidates available. I also know that there are more than 5 candidates available, because I can press the `Page Down` key on my keyboard and in the candidate popup the next candidates are shown. Still when I invoke that function it often returns 5 even though more candidates are available.

**Comment by lanoxx** [comment]
P.S. I could reproduce this using iBus 1.5.5 and 1.5.10

**Comment by fujiwarat** [comment]
ibus 1.5.10 includes the following change:
https://github.com/ibus/ibus/commit/a7abce698f40e60275c46f05967e8cc369769e4b

This would not be a bug because the chinese engine sends 5 candidates only until you type page down.

**Comment by fujiwarat** [comment]
+ @epico

**Comment by epico** [comment]
Right, because the engine used ibus_engine_update_lookup_table_fast.

With latest ibus and ibus-libpinyin, it may return 10 candidates to show the page down arrow on ibus panel.
