### ISSUE TITLE
Download of 1.5.12 at https://github.com/ibus/ibus/releases/ 

### ISSUE THREAD

**Issue by shevegen** [ibus/ibus#1840]
Hello people,

Sorry for this issue request but I think it is a small one and can quickly be closed :)

At https://github.com/ibus/ibus/releases/ there is currently no header such as the "Release 1.5.11" for
1.5.12 available. (I don't necessarily need the changelog, only a link to an archive variant similar to 1.5.11)

That is, I can do a:

    wget https://github.com/ibus/ibus/releases/download/1.5.11/ibus-1.5.11.tar.gz

And this works fine, but I can not do a:

    wget https://github.com/ibus/ibus/releases/download/1.5.12/ibus-1.5.12.tar.gz

currently.

Perhaps this is resolved in a few hours automatically lateron, I have no idea.

I ask because I use a set of scripts in general, so the wget variant works
fine for 1.5.11 but for 1.5.12 it does not yet work. Perhaps someone could
provide a link at that download pages to 1.5.12 so that it can be wget-ed
too, similar to 1.5.11? Thanks a lot for your time anyway and feel free to
close this small issue request!

**Comment by fujiwarat** [comment]
Currently working. Just wait for it.
