### ISSUE TITLE
After invoking ibus_panel_service_candidate_clicked UI is not updated properly

### ISSUE THREAD

**Issue by lanoxx** [ibus/ibus#1841]
Hi IBusDevs,

I think I might have found a bug in IBusPanelService. When I click on a given candidate widget in my implementation, then my callback calls `ibus_panel_service_candidate_clicked` and passes the `index` of the candidate that was clicked, as well as the `button` and `state` information.

Now I would expect that I receive an `update_lookup_table` signal, so I can refresh the list of candidates in the lookup table. However no such signal is arriving! I am currently not sure where to look for the source of this bug, could it be ibus itself or is would it be a problem in the engine that I am using (e.g. Intelligent Pinyin)? I have tried to add Intelligent Bopomofo and I have the same problem with it.

My relevant call to `ibus_panel_service_candidate_clicked` happens here and I have confirmed that indeed it is called with proper indexes such as 1, 2, 4 etc.:

https://git.gnome.org/browse/gnome-flashback/tree/gnome-flashback/libinput-sources/gf-candidate-popup.c#n309

Looking forward to hear your reply.

**Comment by fujiwarat** [comment]
I think ibus sends update-lookup-table signal if the ibus engine sends that signal so it would not be an issue of ibus core.

+ @epico

**Comment by epico** [comment]
Fixed in https://github.com/epico/ibus-libpinyin/commit/5c0158fed5d62a1c995c36486328c577d1b1d194 .

**Comment by fujiwarat** [comment]
@lanoxx 
Probably it might help to file the same bug in https://github.com/libpinyin/ibus-libpinyin/issues

**Comment by lanoxx** [comment]
@fujiwarat, Could you explain why it is necessary to open this bug again in `libpinyin/ibus-libpinyin`? Didn't @epico just fix it in `ibus-libpinyin`? What is the difference between those two repositories?

**Comment by fujiwarat** [comment]
@lanoxx 
This issue tracker is for ibus core and the status is not modified by each ibus engine maintainer.
The main problem is that any bugs won't be notified to each maintainer unless I cc'ed them.
And then if an issue repository is different, each bug submitter needs to file the same issue for the right repository unfortunately for the furthermore discussions.
So if you have more comments on this issue, please submit the issue again.
