### ISSUE TITLE
Restrict use-system-keyboard-layout to non xkb methods

### ISSUE THREAD

**Issue by Idlusen** [ibus/ibus#1842]
Hi,

If I'm not missing anything, xkb-based methods are useless when use-system-keyboard-layout=true

For instance, on my system with the latest ibus package for ArchLinux, my loaded engines are ['xkb:&#8203;fr:bepo:fra', 'rime', 'anthy', 'xkb:&#8203;fr::fra', 'xkb:&#8203;us::eng'] and the system layout fr-bépo. With use-system-keyboard-layout=true, switching to any of the xkb engines has no effect.

What I would expect is to keep the system keyboard layout on rime and anthy, and switch for the others.
A further improvement could be to let the user associate any keyboard layout to a given engine.

**Comment by fujiwarat** [comment]
If you'd wish the fixed layout to ibus-ibus-anthy, you can run /usr/libexec/ibus-anthy-setup -> "Typing Method" -> "Keyboard Layout".
I don't touch ibus-rime. You can try to search the setup dialog or modify "layout" element in /usr/share/ibus/component/rime.xml directly or file a bug for ibus-rime for the customization.

**Comment by Idlusen** [comment]
Thank you for your indications.
However the layouts available in anthy setup are only us and jp variants, or "default". With the latter the layout changes to whatever was the previous engine selected, eg. if I switch from xkb:​us::eng, this is the layout used for anthy, not the system default.
Modifying /usr/share/ibus/component/rime.xml worked as you indicated, but there is the same behavior as anthy, switching layouts with ibus seems to interfere.

But since this is engine specific, if there is no trivial solutions and if you don’t feel that my proposition (restrict use-sys-kbd-layout) is acceptable, I’ll head to the anthy and rime-specific bug trackers.

**Comment by fujiwarat** [comment]
You can add any layout in ibus-anthy:
% dconf write /desktop/ibus/engine/anthy/common/keyboard-layouts "['default', 'us', 'jp', 'us(dvorak)']"
I think use-system-keyboard-layout should follow all engines.
