### ISSUE TITLE
switching from one to another layout doesn't keep the original layout

### ISSUE THREAD

**Issue by Ericounet** [ibus/ibus#1843]
Hi,

my system is Debian /jessie (64).

My primary layout is French (azerty)

I use French (primary) Russian, Chinese hanzi, Chinese pinyin, and Korean inputs.

When I switch from French to Chinese hanzi, the layout remains coherent: the Hanzi pinyin input method (M17n) keeps the French layout in place: so if I want to enter 你好 I have to enter "nihao" and the a is on the same French place (azerty). But when I use the pinyin method, the layout changes and the letters are like on a US keyboard. No problem at all, but when I use afterward the precedent hanzi pinyin method, the layout stays as a US keyboard so I get "nihqo" and not the right hanzi.

The problem is, that it is inconsistent, depending on the order of switching.

If I switch from French to Hanzi : same azerty layout
then Hanzi-> pinyin: qwerty layout
pinyin back to hanzi: qwerty layout (and it was azerty on the first step).

Is there a way to fix this?

Best regards

**Comment by fujiwarat** [comment]
The default should follow the keymap of the previous XKB engine. I.e. input method engine does not have any keymaps.
If you'd specify a fixed keymap for input method engine, the engine could have the customized dialog.
I.e. /usr/lib*/ibus-setup-anthy -> "Typing Method" can set the fixed keymap from the no keymap.
Or you could modify the "layout" tag in your xml file in /usr/share/ibus/component directly by yourself.
Closing this issue as not an IBus core.

**Comment by Ericounet** [comment]
Thanks for your answer.

Eric
