### ISSUE TITLE
[RFE] Please show Wubi table code when in pinyin mode

### ISSUE THREAD

**Issue by epico** [ibus/ibus#1846]
In China, when people use Wubi to input some characters,
they may forget the Wubi code to input Chinese characters,
then they use pinyin mode to input that character.

But he may want to know the Wubi code to input that character,
next time he will use Wubi code to input it.

Fcitx Wubi will display Wubi table code when in pinyin mode.
Could ibus-table support this feature?

@mike-fabian

**Comment by mike-fabian** [comment]
The Wubi code is displayed already when committing the character to preëdit by typing
"Shift", i.e. not committing completely with the "Return" key but committing partly using the
"Shift" key.

**Comment by mike-fabian** [comment]
Probably this should be documented better.

But apart from documenting this better, should there be a more obvious options to display the wubi code?

Maybe, for all tables which allow the use of pinyin, show the table code (wubi code) as well in the candidate list?

**Comment by epico** [comment]
Right, maybe for all tables with pinyin mode, show the table code in the candidate list is better.

**Comment by mike-fabian** [comment]
I have put this in bugzilla as well: https://bugzilla.redhat.com/show_bug.cgi?id=1318109

**Comment by mike-fabian** [comment]
Fixed in 1.9.12: https://github.com/kaio/ibus-table/releases/tag/1.9.12
