### ISSUE TITLE
ibus crash when changing keyboard settings in Systemsettings (Plasma 5 session)

### ISSUE THREAD

**Issue by ariasuni** [ibus/ibus#1849]
How to reproduce crash: open Systemsettings → Input Devices → Keyboard. Make any change, even just make one and revert, and click on Apply. ibus always crash.

It seems to happens with any flags. I wonder if this is the reason I need to wait before starting it with Plasma (e.g., Plasma apply keyboard settings at the beginning of the session then ibus crash).

More info:
- ibus 1.5.13 (probably not new)

**Comment by fujiwarat** [comment]
Are you sure if the crashed application is ibus?

Can you attache the backtrace with gdb whe you get the crash?

% gdb --pid $pid
(gdb) cont
...
(gdb) where

**Comment by ariasuni** [comment]
gdb wasn’t useful because I don’t have any debug symbol, and there was no stack trace. After a bit of investigation:

- it seems that ibus is not crashing but stopped by the keyboard configuration module of KDE. (in journactl: `kdeinit5[605]: org.kde.kcm_keyboard: ibus successfully stopped`)
- it also happens when switching back to X.org from a TTY.
- it doesn’t happen on another machine on Fedora.

So I should probably comment on [the KDE bugtracker report](https://bugs.kde.org/show_bug.cgi?id=359109)?

**Comment by fujiwarat** [comment]
> ibus successfully stopped

That message comes from KDE.
http://api.kde.org/4.x-api/workspace-apidocs/plasma-desktop/html/xkb__helper_8cpp_source.html

> open Systemsettings → Input Devices → Keyboard
Do you mean KDE settings can configure IBus engines?
Can you attach the processes log of ibus with 'ps -ef | grep ibus' ?

I use Plasma 5.20 and doesn't see IBus settings in systemsettings5.
IBus engines can be configured by ibus-setup.

% ibus exit
% ibus-daemon --xim &

**Comment by fujiwarat** [comment]
I use Plasma 5.20 in Fedora 24.

**Comment by ariasuni** [comment]
> Do you mean KDE settings can configure IBus engines?

No, I was talking about standard X.org keyboard configuration.

Output of `ps -ef | grep ibus`:

```
ariasuni 13225     1  0 11:03 ?        00:00:06 ibus-daemon -drx
ariasuni 13243 13225  0 11:03 ?        00:00:00 /usr/lib/ibus/ibus-dconf
ariasuni 13244 13225  0 11:03 ?        00:00:01 /usr/lib/ibus/ibus-ui-gtk3
ariasuni 13247     1  0 11:03 ?        00:00:00 /usr/lib/ibus/ibus-x11 --kill-daemon
ariasuni 13260 13225  0 11:03 ?        00:00:01 /usr/lib/ibus/ibus-engine-simple
ariasuni 13280 13225  0 11:04 ?        00:00:00 /usr/bin/python /usr/share/ibus-anthy/engine/main.py --ibus
```

I use the latest version of Plasma (5.6) based on KDE Frameworks 5.20 on Arch Linux. I don’t know why this particular piece of code is triggered on Arch Linux but not on Fedora (is Fedora patching Plasma?).

**Comment by fujiwarat** [comment]
I reproduced your problem and understood what you figure out in this issue now.

> it seems that ibus is not crashing but stopped by the keyboard 

Actually it's not stopped but systemsettings5 terminates the process of ibus.

> kdeinit5[605]: org.kde.kcm_keyboard: ibus successfully stopped

The warning is not accurate message. ibus exited but not stopped.

> That message comes from KDE.
> http://api.kde.org/4.x-api/workspace-apidocs/plasma-desktop/html/xkb__helper_8cpp_source.html

From this source code, when you configure keyboard settings with systemsettings5, ibus exit.
It means I guess Plasma tries to handle ibus status icon with the Qt UI without ibus-daemon.

But the current IBus supports AppIndicator and can show the status icon so Plasma does not have to implment UI.
And you don't have to configure keyboard with systemsettings5.

Using ibus-setup only can configure both XKB engines and input method engines.
Probably we will return this topic again after Plasma implements Wayland.

**Comment by ariasuni** [comment]
Just for the sake of history, a year later, I commented on the [bug report on KDE’s side](https://bugs.kde.org/show_bug.cgi?id=379930), then [wrote a patch that was merged](https://phabricator.kde.org/D6956) and removed the problematic behavior.
