### ISSUE TITLE
Cannot input correct character when switching from Arabic to Japaense

### ISSUE THREAD

**Issue by makotokato** [ibus/ibus#1850]
###### Env ######
* Fedora 23
 * ibus-gtk3-1.5.11-1-fc23.x86_64
 * ibus-anthy-1.5.8-1-fc23.x86_64
 * ibus-moz-2.17.2077.102-5-fc23.x86_64
 * ibus-1.5.11-1.fc23.x86_64

###### Step ######
1. Setup the following language.
    English (US) / Japanese (Anthy) / Japanese (Mozc) / Arabic (qwerty)
2. Launch gnome-terminal
3. Switch to English (US)
4. Input 'aaaa'.  Of course, aaaa is inputted.
5.  Switch to Arabic (qwetry)
6. Press 'a' key.  Arabic character is inputtted.
7.  Switch to Japanese (Anthy)
8. Press 'a' key.

###### Result #######
Still input Arabic character, not "a".

###### Expected result #######
It should input 'a'.  After switching to English, it works fine.

**Comment by makotokato** [comment]
Also, when this occurs, show keyboard from gnome-shell's menu, layout is US (or JP layout), not Arabic.

**Comment by fujiwarat** [comment]
If you wish to type 'a' but not Arabic, you can customize the ibus-anthy layout to 'jp' or 'us' with /usr/lib*/ibus-setup-anthy.

**Comment by makotokato** [comment]
no way when using mozc... Is there this option on ibus-mozc?

**Comment by fujiwarat** [comment]
You could file a bug in mozc.
Or you can modify 'layout' tag in /usr/share/ibus/component/*.xml as a workaround.

**Comment by makotokato** [comment]
This occurs on ibus-pinyin too :-<

**Comment by fujiwarat** [comment]
Because using Arabic and Pinyin is minor.
Just found a bug - it might be low priority.
