### ISSUE TITLE
Cannot input spanish characters like í á é in QT4 apps in ubuntu 14.04

### ISSUE THREAD

**Issue by elpraga** [ibus/ibus#1851]
They get inserted always like 'i 'a 'e - tried in apps scudcloud tea JuffEd.

See:
https://github.com/raelgc/scudcloud/issues/431

**Comment by fujiwarat** [comment]
I don't understand your problem.
Can you explain your problem with steps?

ibus 1.5.11 supports .XCompose file.

**Comment by elpraga** [comment]
The problem is that if I try to write some Spanish characters, íéá - I can write them without any problems in gtk apps, but I cannot in QT4 apps, because I get 'i'e'a instead.

It is nice of you to point out that 1.5.11 supports .XCompose file, but ubuntu 14.04 LTS which will be supported for several more years has 1.5.5 version installed.

But it is besides the point, because for a regular user perspective, inserting these characters just does not work, and that is what I was trying to point out.

Of course, you can always say that I can use uim, but as ibus is the default one, I think it would be good if it worked.

I really do not understand why you closed the issue without even giving me a chance to write a reply.

**Comment by fujiwarat** [comment]
> Of course, you can always say that I can use uim, but as ibus is the default one, I think it would be good if it worked.

Because the latest ibus works fine with the compose key.
