### ISSUE TITLE
Cannot input √

### ISSUE THREAD

**Issue by thedoctar** [ibus/ibus#1852]
Hi,

In my table I have the following entry
`\sqrt	√	1`
and when I use the table, I can see the √ option when I type \sqrt however upon selecting it it does not appear.

I am using IBus 1.5.5 on Lubuntu 14.04.3

**Comment by fujiwarat** [comment]
Which ibus engine did you use?
You can check it with 'ibus engine' command.

**Comment by fujiwarat** [comment]
@mike-fabian 
I guess it might be ibus-table-latin.
If you can understand this issue, would you copy the bug in ibus-table-latin?
I'm about to close this issue with no reply.

**Comment by thedoctar** [comment]
Sorry I was busy with uni this week. The output from ibus engine is

xkb:us::eng

**Comment by fujiwarat** [comment]
> xkb:us::eng

That IBus XKB engine does not have the feature of '\sqrt'. You should try to find other engines if the format can be used.

> https://github.com/clarkgrubb/latex-input 

I think it works without IBus. You should ask the maintainers instead of here.
BTW the latest IBus supports compose keys and you can output '√' with Multi_key + / + v.

**Comment by thedoctar** [comment]
I installed the ibus compose pacakge but I cannot seem to find the sqrt symbol. I enabled the compose input method, but nothing corresponds to /v.

**Comment by mike-fabian** [comment]
There is a latex table for ibus-table  available already.
On Fedora, it is contained in the package ibus-table-code-1.3.7-3.fc23.noarch.

The upstream source for this latex table is here:

https://github.com/moebiuscurve/ibus-table-others/blob/master/tables/latex.txt

This is sort of the “official” latex table for ibus-table, created by
Giuseppe Castagna (http://www.pps.univ-paris-diderot.fr/~gc)

I am maintaining it and made updates according to Giuseppe Castagna’s suggestions.

This latex table  contains:


    ### Start characters, every key in the table starts with one of these characters
    START_CHARS = \_^

   ...

    \sqrt √ 0

And the input of √ works fine with this table by typing \sqrt

I recommend that you use this latex table.

**Comment by thedoctar** [comment]
This still doesn't work on my system... I cannot input square root, nothing is displayed when I try. I can input cube root and fourth root however, so it just seems to be the square root symbol. Maybe something is broken on my system.

**Comment by mike-fabian** [comment]
Even with https://github.com/moebiuscurve/ibus-table-others/blob/master/tables/latex.txt
you cannot input the square root symbol?

**Comment by thedoctar** [comment]
That is correct. I however do not use the provided install script, I just use 

`ibus-table-createdb -n /usr/share/ibus-table/tables/${name}.db -s latex.txt`
then run
`ibus-daemon -drx`.

For some reason my desktop environment then freezes (a bit weird, maybe suggestive of some other issue) so I `restart lightdm`. 

It seems I can still input all other symbols except square root.

**Comment by mike-fabian** [comment]
How you create the binary database is correct.

It is really weird that you can input all other symbols then but not the square root.

The source table has for example:

\bullet	∙	0
\surd	√	0
\sqrt	√	0
\sqrt[3]	∛	0
\sqrt[4]	∜	0
\propto	∝	0
\infty	∞	0

So you can input \bullet, \sqrt[3], \sqrt[4], \propto, \infty ?

What happens if you type \surd (which is an alternative way to type
the same square root symbol)?

Maybe you have a font problem and the square root symbol is just not
displayed for you?

**Comment by mike-fabian** [comment]
If you look into /usr/libexec/ibus-engine-table, you will see the
line:

# Set this variable to something > 0 to get more debug output.
# (Debug output may show up in the log file and/or in the lookup table):
# export IBUS_TABLE_DEBUG_LEVEL=1

Can you try to uncomment that line and set the debug level to 2?. Like this:

# Set this variable to something > 0 to get more debug output.
# (Debug output may show up in the log file and/or in the lookup table):
export IBUS_TABLE_DEBUG_LEVEL=2

Then restart ibus using "ibus restart"

and look at the log file using:

tail -F  .cache/ibus-table/debug.log

When I try this, while typing \sqrt followed by a space to commit,
the debug.log shows:

do_process_key_event()
_table_mode_process_key_event() repr(key)=r 0x40000000
do_process_key_event()
_table_mode_process_key_event() repr(key)=t 0x00000000
_table_mode_process_key_event() valid input: repr(keychar)=t
update_candidates() self._chars_valid=%(chars_valid)s self._chars_invalid=%(char
s_invalid)s self._chars_valid_update_candidates_last=%(chars_last)s self._candid
ates=%(candidates)s self.db.startchars=%(start)s self._strings=[]
select_words() best=[('\\sqrt', '√', 0, 4), ('\\sqrt[3]', '∛', 0, 1), ('\\sqrt[4
]', '∜', 0, 0)]
append_candidate() tabkeys=\sqrt phrase=√ freq=0 user_freq=4
append_candidate() remaining_tabkeys=%(remaining_tabkeys)s self._chars_valid=\sqrt phrase=√
append_candidate() tabkeys=\sqrt[3] phrase=∛ freq=0 user_freq=1
append_candidate() remaining_tabkeys=%(remaining_tabkeys)s self._chars_valid=\sqrt phrase=∛
append_candidate() tabkeys=\sqrt[4] phrase=∜ freq=0 user_freq=0
append_candidate() remaining_tabkeys=%(remaining_tabkeys)s self._chars_valid=\sqrt phrase=∜
do_process_key_event()
_table_mode_process_key_event() repr(key)=t 0x40000000
do_process_key_event()
_table_mode_process_key_event() repr(key)=space 0x00000000
commit_everything_unless_invalid()
clear_input_not_committed_to_preedit()
update_candidates() self._chars_valid=%(chars_valid)s self._chars_invalid=%(chars_invalid)s self._chars_valid_update_candidates_last=%(chars_last)s self._candidates=%(candidates)s self.db.startchars=%(start)s self._strings=['√']
commit_string() phrase=√
clear_all_input_and_preedit()
clear_input_not_committed_to_preedit()

You see that in my case, the square root symbol is committed
(the line "commit_string() phrase=√").

I wonder how this debug.log looks in your case.

**Comment by thedoctar** [comment]
Thanks for your response. It seems that my ibus-engine-table does not have the debug comment you mention, however upon inserting the debug line manually, I was not able to find the debug file! The unedited file is provided. It is located in /usr/lib/ibus/ for me.

I am able to input \bullet, \sqrt[3], \sqrt[4], \propto, \infty. Upon entering \surd, the same problem occurs and not square root symbol is inputted.

I am able to copy-paste the square root symbol from other sources.

Is there another way to get ibus to send debug messages?

`#!/bin/sh
# vim:set et sts=4 sw=4
#
# ibus-table - The Tables engine for IBus
#
# Copyright (c) 2008-2009 Yu Yuwei <acevery@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

prefix=/usr
datarootdir=${prefix}/share
datadir=${datarootdir}
export IBUS_TABLE_LOCATION=${prefix}/share/ibus-table

for arg in $@; do
	case $arg in
	--xml | -x)
		exec /usr/bin/python ${prefix}/share/ibus-table/engine/main.py --xml;;
	--help | -h)
		exec /usr/bin/python ${prefix}/share/ibus-table/engine/main.py $@;;
  *)
    # first running speedmeter as a daemon
    #/usr/bin/python ${prefix}/share/ibus-table/engine/speedmeter.py -d > /dev/null

    # then start our IME
    exec /usr/bin/python ${prefix}/share/ibus-table/engine/main.py $@
    exit 0
	esac
done`

**Comment by mike-fabian** [comment]
thedoctar> Thanks for your response. It seems that my
thedoctar> ibus-engine-table does not have the debug line you mention,
thedoctar> however upon inserting the debug line manually, I was not
thedoctar> able to find the debug file! The unedited ibus-table-engine
thedoctar> file is provided. It is located in /usr/lib/ibus/ for me.

Apparently you are using a very old version of ibus-table.

thedoctar> I am able to input \bullet, \sqrt[3], \sqrt[4], \propto,
thedoctar> \infty. Upon entering \surd, the same problem occurs and
thedoctar> not square root symbol is inputted.

Really weird.

thedoctar> I am able to copy-paste the square root symbol from other
thedoctar> sources.

Then it is probably not a font problem.

thedoctar> Is there another way to get ibus to send debug messages?

Maybe try upgrading to the latest version of ibus-table?

I fixed many bugs during the last years.

You can get the latest version from here:

https://github.com/kaio/ibus-table/releases
https://github.com/kaio/ibus-table/releases/download/1.9.12/ibus-table-1.9.12.tar.gz

If you use that version and the square root symbol still doesn’t work,
you can at least get the debug log as described, my versions have this
option to print a lot of extra debug messages by editing the
ibus-engine-table as described.

**Comment by thedoctar** [comment]
Thanks for the reply. I'll try and update some time next week and report back. At the moment I have exams so am busy.

**Comment by mike-fabian** [comment]
The investigation in https://github.com/ibus/ibus/issues/2422 finally led to a fix for this issue!
