### ISSUE TITLE
Fedora下文字候选框错位

### ISSUE THREAD

**Issue by chenzhekl** [ibus/ibus#1855]
如图：
http://ww2.sinaimg.cn/large/0060lm7Tgw1f3732iu2drj31b60m4whd.jpg

使用的是Fedora 23，安装在Macbook Pro late 2013上。猜这个问题和HiDPI支持有关系。

**Comment by fujiwarat** [comment]
I guess you use Wayland GNOME instead of X11 GNOME.
Please try IBus 1.5.13 on Fedora 24 which can improve the cursor position and if you still see that problem, let's reopen this.

**Comment by heavytail** [comment]
Reproduced on Archlinux/X11-Gnome with ibus 1.5.13-2 and ibus-libpinyin-1.7.3-2,
Several lines of output of `$ top`:
`  PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND                                          
  774 root      20   0  274.6m   6.8m   0.0  0.0   0:00.04 S  `- gdm                                          
  951 root      20   0  246.2m   7.7m   0.0  0.0   0:00.02 S      `- gdm-session-wor                          
  970 gdm       20   0  192.6m   5.2m   0.0  0.0   0:00.00 S          `- gdm-x-session                        
  972 root      20   0  165.6m  38.4m   0.0  0.1   0:02.69 S              `- Xorg                             
 1061 gdm       20   0  539.9m  13.3m   0.0  0.0   0:00.05 S              `- gnome-session-b                  
 1088 gdm       20   0 1446.2m 151.0m   0.0  0.5   0:05.05 S                  `- gnome-shell                  
 1148 gdm       20   0  327.0m   6.5m   0.0  0.0   0:00.02 S                      `- ibus-daemon              
 1152 gdm       20   0  254.4m   7.1m   0.0  0.0   0:00.00 S                          `- ibus-dconf           
 1187 gdm       20   0  180.4m   7.0m   0.0  0.0   0:00.00 S                          `- ibus-engine-sim `

This issue occurs after setting gnome scaling-fator to 2 by
`gsettings set org.gnome.desktop.interface scaling-factor 2`.
The lookup table still remains at original position as if the scaling-factor is 1.

**Comment by fujiwarat** [comment]
@sfanxiang Thank you for the pointer.

**Comment by fujiwarat** [comment]
OK, this is duplicated of #1806

**Comment by sfanxiang** [comment]
@fujiwarat
Could you please take a look at #1936? Thanks.

**Comment by AlynxZhou** [comment]
this bug still exists in my hidpi screen...

**Comment by sfanxiang** [comment]
@AlynxZhou I don't think ibus 1.5.16 includes the commit fixing HiDPI issues: 6a3301db85e77e0652f7e00894cce493b6a942f6. It's not released yet.

**Comment by ryanprior** [comment]
I'm still having this issue with ibus 1.5.17-3ubuntu4, is there a workaround?

**Comment by AlynxZhou** [comment]
> I'm still having this issue with ibus 1.5.17-3ubuntu4, is there a workaround?

Check your chromium version? Chromium before 70 has a bug that cause it too.

**Comment by ryanprior** [comment]
@AlynxZhou the issue happens in every app. In fact, ibus isn't working in Chromium at all for some reason, but I hadn't tried it until you suggested.

For what it's worth my Chromium is Version 81.0.4044.138 (Developer Build) (64-bit)

**Comment by AlynxZhou** [comment]
> @AlynxZhou the issue happens in every app. In fact, ibus isn't working in Chromium at all for some reason, but I hadn't tried it until you suggested.
> 
> For what it's worth my Chromium is Version 81.0.4044.138 (Developer Build) (64-bit)

That's strange, at least iBus works for me with 200% scale.

**Comment by ryanprior** [comment]
How does your system communicate the 200% scale? Maybe I need to set a env variable or something?

**Comment by AlynxZhou** [comment]
> How does your system communicate the 200% scale? Maybe I need to set a env variable or something?

I just use the settings in gnome-control-center.

**Comment by fujiwarat** [comment]
I don't see any problems about the cursor position in GNOME Xorg.
