### ISSUE TITLE
ibus-chewing unable to use numeric keypad (on a full-size keyboard)

### ISSUE THREAD

**Issue by kaxing** [ibus/ibus#1857]
The ten-key or so called "九宮格數字鍵" are not able to use while typing with ibus-chewing.
I could reproduce this on Ubuntu 16.04 with ibus-chewing 1.4.14-4.

So I wasn't notice this until I change the way I used to switch between English input.
If you are switching off ibus by system hotkey then you won't notice this, but by using shfit/capslock switching mode with ibus then the number keypad won't work.

**Comment by fujiwarat** [comment]
Please file it to https://github.com/definite/ibus-chewing/issues instead.
