### ISSUE TITLE
conflict with fcitx

### ISSUE THREAD

**Issue by shenxs** [ibus/ibus#1861]
I can't use fcitx with ibus .
fcitx gave me that

2.  根窗口上的 XIM_SERVERS:

    **Xim 服务名称: "ibus" 与环境变量中设置的值 "fcitx" 不同.**

after remove ibus  fcitx works find
but if I remove the ibus ,I will remove unity desktop,that's unacceptable
so how could I set the XIM_SERVERS to fcitx instead of ibus

**Comment by fujiwarat** [comment]
XMODIFIERS=@im=fcitx
