### ISSUE TITLE
No longer able to type in Spanish

### ISSUE THREAD

**Issue by el-gallo-azul** [ibus/ibus#1862]
I have used this function every couple of days for the last 18 months, switching between English and Spanish input keyboards. I first noticed yesterday that when I switch to Spanish, I am only able to type in English and I am unable to type in Spanish.

For example, since yesterday, it has become impossible to type the characters

á, é, í, ñ, ó, ú, ü, ¡, ¿

(I just found them for this bug report at http://spanish.typeit.org/)

I have restarted the computer, and tried various methods for changing the iBus setting (using the panel icon, and using keyboard shortcut keys), but even though the selected language changes from English to Spanish, I am still unable to type the above character examples.

**Comment by fujiwarat** [comment]
Which IBus engine did you use for Spanish?
You can check the current engine name with 'ibus engine' command.

**Comment by el-gallo-azul** [comment]
xkb:es::spa 


      De: Takao Fujiwara <notifications@github.com>
 Para: ibus/ibus <ibus@noreply.github.com> 
CC: el-gallo-azul <el_gallo_azul@yahoo.com>; Author <author@noreply.github.com>
 Enviado: Miércoles 8 de junio de 2016 17:41
 Asunto: Re: [ibus/ibus] No longer able to type in Spanish (#1862)
   
Which IBus engine did you use for Spanish?
You can check the current engine name with 'ibus engine' command.—

**Comment by el-gallo-azul** [comment]
xkb:es::spa

**Comment by fujiwarat** [comment]
Did you see any errors when you run ibus-daemon by manual?

```
% ibus exit
% ibus-daemon --xml --verbose
```

If ``xkb:es::spa`` is set correctly, ``setxkbmap -query`` command can show the Spanish layout.

**Comment by el-gallo-azul** [comment]
Oops
user@RIKOMAGIC:~$ ibus exituser@RIKOMAGIC:~$ ibus-daemon --xml --verboseOption parsing failed: Unknown option --xmluser@RIKOMAGIC:~$ 
I'll run it again without the --xml switch. Greg Flint

PO Box 642 
Parap 
NT 0804 
Australia

Currently, technological development happens as slowly as the main players can get it to happen. The concept of 'open source' means that it happens as fast as it can (like it does in science):1. Happy birthday to GNU (YouTube 2008)2. Free Software Foundation (FSF 2014)3. The internet wouldn't exist otherwise (The Telegraph 2014)4. Edward Snowden on Open Source (LibrePlanet 2016)5. How it works, and its application to law (TED 2012)
email: el_gallo_azul@yahoo.comSIP (not email): el_gallo_azul@ekiga.net
Phone +61 (0)8 8945 1725
Mobile +61 (0)428 279 021
Australian Central Standard Time (ACST) = UTC/GMT+9.5


      De: Takao Fujiwara <notifications@github.com>
 Para: ibus/ibus <ibus@noreply.github.com> 
CC: el-gallo-azul <el_gallo_azul@yahoo.com>; Author <author@noreply.github.com>
 Enviado: Miércoles 8 de junio de 2016 20:19
 Asunto: Re: [ibus/ibus] No longer able to type in Spanish (#1862)
   
Did you see any errors when you run ibus-daemon by manual?% ibus exit
% ibus-daemon --xml --verbose
If xkb:es::spa is set correctly, setxkbmap -query command can show the Spanish layout.—

**Comment by el-gallo-azul** [comment]
It still doesn't work, after;
user@RIKOMAGIC:~$ ibus-daemon --verbose
(process:7429): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.
(ibus-ui-gtk3:7429): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

I'm afraid I don't understand all of that.
I suppose it's possible that it has been caused by an error that I encountered one day when doing a system update, that is still there, and I don't know how to fix that either. Greg Flint

PO Box 642 
Parap 
NT 0804 
Australia

Currently, technological development happens as slowly as the main players can get it to happen. The concept of 'open source' means that it happens as fast as it can (like it does in science):1. Happy birthday to GNU (YouTube 2008)2. Free Software Foundation (FSF 2014)3. The internet wouldn't exist otherwise (The Telegraph 2014)4. Edward Snowden on Open Source (LibrePlanet 2016)5. How it works, and its application to law (TED 2012)
email: el_gallo_azul@yahoo.comSIP (not email): el_gallo_azul@ekiga.net
Phone +61 (0)8 8945 1725
Mobile +61 (0)428 279 021
Australian Central Standard Time (ACST) = UTC/GMT+9.5


      De: el_gallo_azul <el_gallo_azul@yahoo.com>
 Para: ibus/ibus <reply@reply.github.com> 
 Enviado: Jueves 9 de junio de 2016 9:09
 Asunto: Re: [ibus/ibus] No longer able to type in Spanish (#1862)
   
Oops
user@RIKOMAGIC:~$ ibus exituser@RIKOMAGIC:~$ ibus-daemon --xml --verboseOption parsing failed: Unknown option --xmluser@RIKOMAGIC:~$ 
I'll run it again without the --xml switch. Greg Flint

PO Box 642 
Parap 
NT 0804 
Australia

Currently, technological development happens as slowly as the main players can get it to happen. The concept of 'open source' means that it happens as fast as it can (like it does in science):1. Happy birthday to GNU (YouTube 2008)2. Free Software Foundation (FSF 2014)3. The internet wouldn't exist otherwise (The Telegraph 2014)4. Edward Snowden on Open Source (LibrePlanet 2016)5. How it works, and its application to law (TED 2012)
email: el_gallo_azul@yahoo.comSIP (not email): el_gallo_azul@ekiga.net
Phone +61 (0)8 8945 1725
Mobile +61 (0)428 279 021
Australian Central Standard Time (ACST) = UTC/GMT+9.5


      De: Takao Fujiwara <notifications@github.com>
 Para: ibus/ibus <ibus@noreply.github.com> 
CC: el-gallo-azul <el_gallo_azul@yahoo.com>; Author <author@noreply.github.com>
 Enviado: Miércoles 8 de junio de 2016 20:19
 Asunto: Re: [ibus/ibus] No longer able to type in Spanish (#1862)
  
Did you see any errors when you run ibus-daemon by manual?% ibus exit
% ibus-daemon --xml --verbose
If xkb:es::spa is set correctly, setxkbmap -query command can show the Spanish layout.—

**Comment by fujiwarat** [comment]
> I'll run it again without the --xml switch. Greg Flint 

Sorry, that's my mistake. It should be ``--xim`` but not ``--xml``.
I also updated the original comment.

> user@RIKOMAGIC:~$ ibus-daemon --verbose
> (process:7429): Gtk-WARNING **: Locale not supported by C library. Using the fallback 'C' locale.

This means your locale is not set correctly.
You could get the current locale with ``locale`` command and set the right locale with ``export LANG=en_US.UTF-8``

> (ibus-ui-gtk3:7429): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

This is an expected warning.

Did you see any other error messages when you switch the IBus engines?

When you switch to ``xkb:es::spa``, did you run ``setxkbmap -query`` command?

> Currently, technological development happens as slowly as the main players can get it to happen. T

I don't think the message is relative with this issue. You can correct your comment on this web by yourself.

**Comment by el-gallo-azul** [comment]
>  It should be --xim but not --xml.

```
user@RIKOMAGIC:~$ ibus-daemon --xim --verbose

(process:8338): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.

(ibus-ui-gtk3:8338): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
^C
```
...but I am still unable to type any Spanish characters.

> You could get the current locale with locale command and set the right locale with export LANG=en_US.UTF-8

Done

`user@RIKOMAGIC:~$ export LANG=en_AU.UTF-8
`

> Did you see any other error messages when you switch the IBus engines?

No. I have never seen **any** error messages when switching languages using the panel icon.

> When you switch to xkb:es::spa, did you run setxkbmap -query command?

While set to Spanish language:

`user@RIKOMAGIC:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
`

**Comment by fujiwarat** [comment]
> user@RIKOMAGIC:~$ setxkbmap -query
> rules: evdev
> model: pc105
> layout: us,es
> variant: ,

This means ibus's set engine does not work in your host correctly.

Did you see IBus IME Switcher window when you type Super+space?
![ibus-ime-switcher-fujiwara](https://cloud.githubusercontent.com/assets/105929/15918170/0c76bc02-2e3f-11e6-99e0-183d39448661.png)

Can you attach the screen shot with ``gnome-screenshot -i`` command to show how you switch IBus IMEs?

**Comment by el-gallo-azul** [comment]
In order to switch languages I either use the panel icon

![screenshot - 20160609 - 140913 ibus panel icon](https://cloud.githubusercontent.com/assets/19792633/15919014/4aff4f04-2e4c-11e6-8253-0b37812a8276.png)

which looks like this when I click it:

![screenshot - 20160609 - 141004 ibus panel icon clicked](https://cloud.githubusercontent.com/assets/19792633/15919026/5dc9b11a-2e4c-11e6-8ad2-f616d60e18f6.png)

or

ctrl-[space]

which only gives me a floating dialog box with the choice of the two languages that I have installed.

PS

`user@RIKOMAGIC:~$ gnome-screenshot -i
bash: gnome-screenshot: command not found
`

**Comment by fujiwarat** [comment]
> which only gives me a floating dialog box with the choice of the two languages that I have installed.

Do you mean your IME switcher dialog and one of my screenshot is similar? The dialog is not shown in your screenshot.

> bash: gnome-screenshot: command not found

It means you don't install gnome-screenshot but it's fine if you can take the pic with another application.

Can you take the following test?
```
% sudo mv /usr/bin/setxkbmap /usr/bin/setxkbmap.orig
% sudo vi /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
% setxkbmap -query
% cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
```

After you switch the engine to ``xkb:es::spa``, ``setxkbmap`` is executed and the content of ``/var/tmp/ibus.log`` should be updated.

Also which version of ibus do you use?
```
% ibus version
```

**Comment by el-gallo-azul** [comment]
> Do you mean your IME switcher dialog and one of my screenshot is similar? The dialog is not shown in your screenshot.

Yes it is similar to the one in your screenshot. except that yours has 14 squares and mine has two squares. I was not able to take a screenshot of it, although I tried.

I followed your suggestion:

`% sudo mv /usr/bin/setxkbmap /usr/bin/setxkbmap.orig
% sudo vi /usr/bin/setxkbmap`

...but when I reached that point, I was in the Vim editor and it's not clear what I am supposed to do next. I see that different lines start with %, # or $, and I don't even know what that means.

**Comment by fujiwarat** [comment]
I mean the content of /usr/bin/setxkbmap:
```
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
```

``%`` means the shell prompt in the terminal.

**Comment by fujiwarat** [comment]
Did you try the test?

**Comment by el-gallo-azul** [comment]
Not yet. I hope to try it within the next 6 hours.

**Comment by el-gallo-azul** [comment]
I'm doing it. What does the third line `% cat /usr/bin/setxkbmap` mean?

I am in Vim since the second line `% sudo vi /usr/bin/setxkbmap` so does that mean I am supposed to include `% cat /usr/bin/setxkbmap` as the first line within the new file `/usr/bin/setxkbmap`?

**Comment by fujiwarat** [comment]
Run ``sudo vi /usr/bin/setxkbmap`` and wrote the following content:
```
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
```

**Comment by el-gallo-azul** [comment]
OK. When am I supposed to `% cat /usr/bin/setxkbmap`?

**Comment by el-gallo-azul** [comment]
This is what happens when I attempt to copy

```
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
```

and paste it into `/usr/bin/setxkbmap` in Vim:

![screenshot - 20160610 - 164338 trying to create file setxkbmap](https://cloud.githubusercontent.com/assets/19792633/15956950/fb5a10bc-2f2a-11e6-8441-1c0bb4902255.png)

**Comment by fujiwarat** [comment]
Why you don't write the line of ``#!/bin/sh`` .
And save ``/usr/bin/setxkbmap``.

```
% sudo mv /usr/bin/setxkbmap /usr/bin/setxkbmap.orig
% sudo vi /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
% setxkbmap -query
% cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
```

**Comment by el-gallo-azul** [comment]
Yes sorry I didn't mention that after pasting didn't work, I tried to write it all manually. As soon as I try to write the first character, which is #:

![screenshot - 20160610 - 165758 try to write content](https://cloud.githubusercontent.com/assets/19792633/15957214/b9a10976-2f2c-11e6-9c91-a9635a1f69de.png)

**Comment by el-gallo-azul** [comment]
By the way, when I type the second line `% sudo vi /usr/bin/setxkbmap`, Vim starts, so do you want me to write the third and fourth lines

```
% sudo chmod a+x /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
```

as the first two lines of the new file `/usr/bin/setxkbmap`?

**Comment by fujiwarat** [comment]
Seems you don't know how to use vi.
If you don't know about vi, you can use any other text editor and create the test ``/usr/bin/setxkbmap``.

The content of ``/usr/bin/setxkbmap``  is.
```
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
```

**Comment by el-gallo-azul** [comment]
When am I supposed to use

```
% sudo chmod a+x /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
```

?

Am I supposed to use it AFTER creating and editing `/usr/bin/setxkbmap`?

**Comment by fujiwarat** [comment]
> Am I supposed to use it AFTER creating and editing /usr/bin/setxkbmap?

Yes

**Comment by fujiwarat** [comment]
``cat`` comand can confirm the content of ``/usr/bin/setxkbmap``.

**Comment by el-gallo-azul** [comment]
I am trying to follow your instructions. I am used to ALL applications accepting pasted text. I don't understand why trying to write # into `/usr/bin/setxkbmap` using Vim gave the message "E348: No string under cursor" before, so I suppose that means I don't know how to use Vim.

**Comment by fujiwarat** [comment]
So you don't have to use ``vi``. I have no time to tell vi.

```% sudo mv /usr/bin/setxkbmap /usr/bin/setxkbmap.orig
% sudo $YOUR_TEXT_EDITOR /usr/bin/setxkbmap
% sudo chmod a+x /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
% setxkbmap -query
% cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
```

**Comment by el-gallo-azul** [comment]
If I am supposed to use

```
% sudo chmod a+x /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
```
 AFTER creating the file, then I think it should be written BELOW those lines, like this:

```
% sudo mv /usr/bin/setxkbmap /usr/bin/setxkbmap.orig
% sudo vi /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
% sudo chmod a+x /usr/bin/setxkbmap
% cat /usr/bin/setxkbmap
% setxkbmap -query
% cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
```

**Comment by fujiwarat** [comment]
```
% cat /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@
```

This means ``cat`` command outputs the content of ``/usr/bin/setxkbmap`` and verify what you write in ``/usr/bin/setxkbmap``.

**Comment by el-gallo-azul** [comment]
I don't want you to tell me how to use Vim. Do you know why trying to type # makes Vim gives the message "E348: No string under cursor"?

**Comment by fujiwarat** [comment]
No

**Comment by el-gallo-azul** [comment]
Yes, that's why I think the content should be written into `/usr/bin/setxkbmap` before getting any command to say what's written in `/usr/bin/setxkbmap`.

**Comment by el-gallo-azul** [comment]
I'll go and find out now what editors are available in this computer, because neither of us know why Vim doesn't work.

**Comment by fujiwarat** [comment]
``vi`` use another buffer but not standard out so the output can see only with ``cat``.

**Comment by fujiwarat** [comment]
I should not see your error because I know vi.

**Comment by el-gallo-azul** [comment]
I just used a different editor:

```
user@RIKOMAGIC:~$ cat /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@user@RIKOMAGIC:~$ sudo chmod a+x /usr/bin/setxkbmap
user@RIKOMAGIC:~$ cat /usr/bin/setxkbmap
#!/bin/sh
echo ${0}.orig $@ >> /var/tmp/ibus.log
${0}.orig $@user@RIKOMAGIC:~$ setxkbmap -query
/usr/bin/setxkbmap: 2: /usr/bin/setxkbmap: cannot create /var/tmp/ibus.log: Permission denied
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ sudo setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ cat /var/tmp/ibus.log
/bin/bash.orig
/bin/bash.orig
user@RIKOMAGIC:~$ /usr/bin/setxkbmap.orig -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$
```

Now I shall test changing languages and see if it works.

**Comment by el-gallo-azul** [comment]
No. I still can't type Spanish characters.

**Comment by fujiwarat** [comment]
> /usr/bin/setxkbmap: 2: /usr/bin/setxkbmap: cannot create /var/tmp/ibus.log: Permission denied

Probably you followed bad instruction during the wrong usage of ``vi``.
Need to remove ``/var/tmp/ibus.log`` and try the same step:

``
% sudo rm /var/tmp/ibus.log
% setxkbmap -query
% cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
``

And after you switch your engine to ``xkb:es::spa``, confirm the content of /var/tmp/ibus.log again.

**Comment by fujiwarat** [comment]
> % sudo setxkbmap -query
Should not run setxkbmap with sudo.

**Comment by el-gallo-azul** [comment]
With English language chosen:

```
user@RIKOMAGIC:~$ sudo rm /var/tmp/ibus.log
user@RIKOMAGIC:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
user@RIKOMAGIC:~$ /usr/bin/setxkbmap.orig -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ 
```

Then I choose Spanish language, using ctrl-[space], and:

```
user@RIKOMAGIC:~$ sudo rm /var/tmp/ibus.log
[sudo] password for user: 
user@RIKOMAGIC:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
user@RIKOMAGIC:~$ /usr/bin/setxkbmap.orig -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$
```

**Comment by fujiwarat** [comment]
> sudo rm /var/tmp/ibus.log

I mean when you choose Spanich, ``/var/tmp/ibus.log`` should be updated so ibus.log should not be removed.

I expect the following result if IBus works correctly:
```
% cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
/usr/bin/setxkbmap.orig -l es
```

**Comment by el-gallo-azul** [comment]
With English language chosen:

```
user@RIKOMAGIC:~$ sudo rm /var/tmp/ibus.log
[sudo] password for user: 
user@RIKOMAGIC:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
user@RIKOMAGIC:~$ /usr/bin/setxkbmap.orig -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$
```

Then I choose Spanish language, using ctrl-[space], and:

```
user@RIKOMAGIC:~$ setxkbmap -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$ cat /var/tmp/ibus.log
/usr/bin/setxkbmap.orig -query
/usr/bin/setxkbmap.orig -query
user@RIKOMAGIC:~$ /usr/bin/setxkbmap.orig -query
rules:      evdev
model:      pc105
layout:     us,es
variant:    ,
user@RIKOMAGIC:~$
```

**Comment by el-gallo-azul** [comment]
Something seems quite broken, because `layout:     us,es` should be `layout:     us,en` in English, shouldn't it?

**Comment by fujiwarat** [comment]
> user@RIKOMAGIC:~$ cat /var/tmp/ibus.log
> /usr/bin/setxkbmap.orig -query

It means ibus does not work correctly when you switch ibus IMEs.

Which ibus version do you use?
```
% ibus version
```

I still doubt if any errors are output with ``--verbose`` option of ibus-daemon.
OK, Do you see any errors when you run the ibus panel directly after kill the process of the ibus panel?
```
% ps -ef | grep ibus-ui-gtk3
user $PID 11:40 tty1 00:00:01 /usr/libexc/ibus-ui-gtk3
% kill $PID
% ps -ef | grep ibus-ui-gtk3
% /usr/libexec/ibus-ui-gtk3
```

What is your desktop? LXDE?

**Comment by el-gallo-azul** [comment]
> Which ibus version do you use?
```
user@RIKOMAGIC:~$ ibus version
IBus 1.5.5
```

Is the text "user $PID 11:40 tty1 00:00:01 /usr/libexc/ibus-ui-gtk3" supposed to be the same command as the preceding "ps -ef | grep ibus-ui-gtk3"?
```
user@RIKOMAGIC:~$ ps -ef | grep ibus-ui-gtk3
user      1401  1367  0 Jun11 ?        00:00:26 /usr/lib/ibus/ibus-ui-gtk3
user     25739 25725  0 14:26 pts/0    00:00:00 grep --color=auto ibus-ui-gtk3
```
```
user@RIKOMAGIC:~$ kill $PID
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
```
```
user@RIKOMAGIC:~$ kill 1401
user@RIKOMAGIC:~$
```
```
user@RIKOMAGIC:~$ ps -ef | grep ibus-ui-gtk3
user     25760 25725  0 14:32 pts/0    00:00:00 grep --color=auto ibus-ui-gtk3
user@RIKOMAGIC:~$
```
```
user@RIKOMAGIC:~$ /usr/libexec/ibus-ui-gtk3
bash: /usr/libexec/ibus-ui-gtk3: No such file or directory
user@RIKOMAGIC:~$
```

**Comment by fujiwarat** [comment]
> Is the text "user $PID 11:40 tty1 00:00:01 /usr/libexc/ibus-ui-gtk3" supposed to be the same command as the preceding "ps -ef | grep ibus-ui-gtk3"?

yes

> user@RIKOMAGIC:~$ /usr/libexec/ibus-ui-gtk3
> bash: /usr/libexec/ibus-ui-gtk3: No such file or directory

Your distro path should be /usr/lib/ibus/ibus-ui-gtk3

**Comment by el-gallo-azul** [comment]
```
user@RIKOMAGIC:~$ ps -ef | grep ibus-ui-gtk3 user $PID 11:40 tty1 00:00:01 /usr/libexc/ibus-ui-gtk3
grep: user: No such file or directory
grep: 11:40: No such file or directory
grep: tty1: No such file or directory
grep: 00:00:01: No such file or directory
grep: /usr/libexc/ibus-ui-gtk3: No such file or directory
user@RIKOMAGIC:~$
```

**Comment by fujiwarat** [comment]
> ps -ef | grep ibus-ui-gtk3 user $PID 11:40 tty1 00:00:01 /usr/libexc/ibus-ui-gtk3

What did you do. See the instruction.
```
% ps -ef | grep ibus-ui-gtk3
user $PID 11:40 tty1 00:00:01 /usr/lib/ibus//ibus-ui-gtk3
% kill $PID
% ps -ef | grep ibus-ui-gtk3
% /usr/lib/ibus/ibus-ui-gtk3
```

**Comment by el-gallo-azul** [comment]
How do I type some command text on one line, and the remainder of the command text on the next line?

I only know how to enter one line of text for a command and then press [enter].

**Comment by fujiwarat** [comment]
Not sure what you ask here.

```
% ps -ef | grep ibus-ui-gtk3
```

``%`` means the shell prompt. In your case would be identified to ``@RIKOMAGIC:~$``.
and `` ps -ef | grep ibus-ui-gtk3`` is the suggested command line.
If the line is not started with ``%``, it's the output from the previous line.

**Comment by el-gallo-azul** [comment]
If I type

`ps -ef | grep ibus-ui-gtk3`

and press [enter], the text

`user     26371 26357  0 16:40 pts/0    00:00:00 grep --color=auto ibus-ui-gtk3`

appears, as I showed [before](https://github.com/ibus/ibus/issues/1862#issuecomment-225489811), which looks nothing like

`user $PID 11:40 tty1 00:00:01 /usr/lib/ibus//ibus-ui-gtk3`

**Comment by fujiwarat** [comment]
> user 26371 26357 0 16:40 pts/0 00:00:00 grep --color=auto ibus-ui-gtk3

This means you already killed the process of ibus-ui-gtk3 so now you cannot see the ibus panel icon.
If you wish to restart the instruction from the first, you can run 'ibus restart' and ibus-ui-gtk3 will bring up.

**Comment by el-gallo-azul** [comment]
Yes OK I understand that, but I got

```
user@RIKOMAGIC:~$ ps -ef | grep ibus-ui-gtk3
user      1401  1367  0 Jun11 ?        00:00:26 /usr/lib/ibus/ibus-ui-gtk3
user     25739 25725  0 14:26 pts/0    00:00:00 grep --color=auto ibus-ui-gtk3
```

before I killed the process, which is quite different to

`user $PID 11:40 tty1 00:00:01 /usr/lib/ibus//ibus-ui-gtk3`

Now, it looks like you put "$PID" as a variable to represent an actual process number, which I didn't know before. I don't understand why you get "11:40 tty1" and I don't get anything of the sort.

I've restarted and tested iBus, and I can only type English characters, no matter which language is selected.

**Comment by fujiwarat** [comment]
Quit different? I don't think so.

> user      1401  1367  0 Jun11 ?        00:00:26 /usr/lib/ibus/ibus-ui-gtk3

So now the process id of ibus-ui-gtk3 is 1401 and you can read the instruction "kill $PID" as "kill 1401".

**Comment by el-gallo-azul** [comment]
Yes, that why I typed `kill 1401` [as I mentioned](https://github.com/ibus/ibus/issues/1862#issuecomment-225489811).

I'll try the entire process again tomorrow.

**Comment by el-gallo-azul** [comment]
```
user@RIKOMAGIC:~$ ps -ef | grep ibus-ui-gtk3
user     15431 26357  0 12:36 pts/0    00:00:00 grep --color=auto ibus-ui-gtk3
user     26409 26404  0 Jun13 ?        00:00:13 /usr/lib/ibus/ibus-ui-gtk3
user@RIKOMAGIC:~$ kill 26409
user@RIKOMAGIC:~$ ps -ef | grep ibus-ui-gtk3
user     15437 26357  0 12:36 pts/0    00:00:00 grep --color=auto ibus-ui-gtk3
user@RIKOMAGIC:~$ /usr/lib/ibus/ibus-ui-gtk3

(process:15438): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
[comment: ibus started]
^C
user@RIKOMAGIC:~$ ibus restart
user@RIKOMAGIC:~$
```

> What is your desktop? LXDE?

This machine with the iBus issue uses Xubuntu 14.04, which is XFCE desktop.

I just tested it again after restarting ibus a few more times, and I am not able to type Spanish characters.

**Comment by fujiwarat** [comment]
> (process:15438): Gtk-WARNING **: Locale not supported by C library.

Why do you still use the bad locale?
You should set the right locale from the login.
And you don't see any other error messages from ibus-ui-gtk3?

> which is XFCE desktop.

That's fine.

**Comment by el-gallo-azul** [comment]
> Why do you still use the bad locale?
I don't know. I have only used this computer since I bought it 18 months ago. Does something need to be fixed?

> You should set the right locale from the login.
When I want to use the computer, I turn it on, wait for about 25 seconds, and then it is ready to use. I don't log in to anything.

> And you don't see any other error messages from ibus-ui-gtk3?
I have never received **any** error messages **at all** from iBus. I was able to type Spanish characters until one day last week, and then I have not been able to type Spanish characters since that day.

**Comment by fujiwarat** [comment]
> I don't know. I have only used this computer since I bought it 18 months ago. Does something need to be fixed?

As I explained before, you should set LANG=en_US.UTF-8.
You can confirm the current bad locale with ``locale`` command.
You can set the correct LANG in $HOME/.profile

**Comment by fujiwarat** [comment]
You have too many wrong usage, vi, locale and maybe in ibus...

**Comment by el-gallo-azul** [comment]
That's a shame. That's why I stopped using Windows - it became more and more difficult to keep it running, and then in about 2008 I had had enough. Linux was much more reliable, so I decided to use it 100% since then. But it seems unexplainable and unfixable problems happen in Linux too. At least I am confident that the kernel is stable and reliable, but some of the settings seem to go bad, even though the user doesn't change anything (knowingly).

**Thanks for your time and contributions**. It's a shame that I am no longer able to type in Spanish on this computer - from now on, I'll just leave the webpage http://spanish.typeit.org/ running on this computer.

**Comment by fujiwarat** [comment]
Did you try a new user account instead of the current user account?

**Comment by tddsg** [comment]
I encountered the same issue and spent months to discover from this post https://github.com/vn-input/ibus-unikey/issues/4 that there is an option in IBus setting that forces it to use the system keyboard layout.  (See this attached photo: https://cloud.githubusercontent.com/assets/3521898/10677334/f790bac4-790b-11e5-9496-a4276b0f7037.jpg)

By unchecking this option, I can set the Spanish keyboard layout using IBus. Hope that this will helps other people who face the same issue.

**Comment by fujiwarat** [comment]
@tddsg I don't think your issue is same and you need to explain your issue with a new issue using the issue template.
