### ISSUE TITLE
Keyboard combination don't work with fresh IBus

### ISSUE THREAD

**Issue by webarchitect609** [ibus/ibus#1863]
Facts: 
IBus 1.5.13
Ubuntu 14.04 LTS ( Linux WS-303533 3.16.0-73-generic #95~14.04.1-Ubuntu SMP Thu Jun 9 08:00:04 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux )
programm KeePass 2.25
Keyborad language switching configured on Ctrl + Shift

Description: 
When I have older version of Ibus(older than 1.5.11), I could press `Ctrl + Shift + U`to copy URL to clipboard. Now such combination don't work. 
Screenshot: http://joxi.ru/4AkeOlfMgp5omq?d=1

**Comment by fujiwarat** [comment]
Right. Ctrl+Shift+u is assigned to input Unicode code point directly with IBus in any text editors.
If the application provides the shortcut customization, it would be nice.

**Comment by webarchitect609** [comment]
Thank you! Unfortunately, KeePass can't reassign shortcut. Try to live without such shortcut :(
