### ISSUE TITLE
ibus-x11 crashes with xterm and emacs

### ISSUE THREAD

**Issue by akssri** [ibus/ibus#1866]
This occurs on my system when using the XIM client. The input bubble box appears when entering a character, but crashes as soon as "Enter" is pressed; attached is the backtrace. 
[ibus-backtrace.txt](https://github.com/ibus/ibus/files/347024/ibus-backtrace.txt)

I'm running Arch Linux using the build 1.5.13 from the repositories. Please let me know if there is someway I can help get this resolved. Thanks!

**Comment by fujiwarat** [comment]
> /usr/lib/libX11.so.6(XFree+0x9)[0x7f001ea89cd9]
> /usr/lib/ibus/ibus-x11[0x40347c]

This backtrace lacks the API information.
You need to install ibus debug package and try to get the backtrace again.

**Comment by fujiwarat** [comment]
> /usr/lib/libgobject-2.0.so.0(g_signal_emit+0x8f)[0x7f001dc65fff]

> /usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x15a)[0x7f001d975c8a]

It also would be better to install glib2 debug packages.

**Comment by akssri** [comment]
It looks like this was caused by an incorrect LANG env variable (I found this out while testing with debug build). Closing this issue; thank you for the quick reply (and the project).
