### ISSUE TITLE
<Control_R>Shift_R doesn't work

### ISSUE THREAD

**Issue by Hi-Angel** [ibus/ibus#1867]
How do I switch layout with <kbd>Right Ctrl</kbd> + <kbd>Right Shift</kbd>?

Grepping trough the sources reveals that <kbd>Right Ctrl</kbd> is labeled Control_R. So I tried to change with dconf-editor the hotkey to `'<Control_R>Shift_R'` and to `'Control_R+Shift_R'`, but neither worked.

I'm always using those keys because any combination of <kbd>Left Ctrl</kbd>, <kbd>Left Alt</kbd>, <kbd>Left Shift</kbd> interferes to Emacs combinations; like, <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>f</kbd> is to select a word.

**Comment by fujiwarat** [comment]
There is no such a modifier key Control_R:
```
% gsettings get org.freedesktop.ibus.general.hotkey triggers
['<Super>space']
% gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Control>Shift_R']"
```

> I'm always using those keys because any combination of Left Ctrl, Left Alt, Left Shift interferes to Emacs combinations

I don't see why IBus combination follows Emacs one.

**Comment by Hi-Angel** [comment]
@fujiwarat then why did you close it? Isn't that a bug? I'm using <kbd>Right Control</kbd> + <kbd>RIght Shift</kbd> just fine on my old system. But I wanted to move to IBUS from XIM input method, that's why I reported.

> I don't see why IBus combination follows Emacs one.

Sorry, I'm not sure I understood you. May be you misunderstood that part — I said this just for you to see why would I want that shortcut.

**Comment by Hi-Angel** [comment]
> I don't see why IBus combination follows Emacs one.

Ah, I see, you mean the <kbd>Alt</kbd>+<kbd>Space</kbd>. Well, this is also a used shortcut. The only keys that goes unused is the right modificators, i.e. right shift, right ctrl, etc.

**Comment by fujiwarat** [comment]
@Hi-Angel 

Did you run the gsettings command? 
That's why I close this issue.

**Comment by Hi-Angel** [comment]
@fujiwarat  err… I didn't because I'm not at home, but anyway i see is that gsettings can't install <kbd>Right Ctrl</kbd> as the shortcut just because ibus doesn't allow to. it's the problem of ibus, and is deficiency compared to an ancient XIM. So how is that not a bug of ibus?

**Comment by Hi-Angel** [comment]
@fujiwarat okay, even though I'm in office, I managed to chroot to other installation on disk, and ran the

	dbus-launch --exit-with-session gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Foo>Shift_R']"

*(dbus-launch is because there's no Xorg)*

Unsurprisingly, it accepted even Foo, because the end meaning is the deal of ibus. Now, why did you close the bug?

	# gsettings get org.freedesktop.ibus.general.hotkey triggers
	['<Foo>Shift_R']

**Comment by fujiwarat** [comment]
It would be good for you to run gsettings on the destkop since you don't understand dbus.

**Comment by Hi-Angel** [comment]
@fujiwarat oh, please, stop making silly excuses. I ran `gsettings` just for you, even though I guessed what it does at the very moment I saw the command you posted. If you'd have a technical reason to no do it, you would say it long ago instead of walking around. Just tell that you don't want to fix something which you do not use, and let's walk away. I'll try to use SCIM then, and if it won't work, I'd look at whether I could do a patch.

**Comment by fujiwarat** [comment]
Did you play the shortcut with ibus?
So what is the problem with <Ctrl>Shift_R? It should work with riight Ctrl.

**Comment by Hi-Angel** [comment]
Hm… Well, you're right, in fact, I could use <kbd>Right Shift</kbd> with any <kbd>Ctrl</kbd>, because I'd never press the combination of <kbd>Left Ctrl</kbd>+<kbd>Right Shift</kbd> anyway. Thanks.
