### ISSUE TITLE
Test Suite Error on 1.5.13 on Ubuntu 14.04

### ISSUE THREAD

**Issue by zelda14** [ibus/ibus#1868]
Build the 1.5.13 version on an Ubuntu 14.04
Run the test suite with a **make -k check** command.
Here is the failure report:

   ibus 1.5.13: src/tests/test-suite.log

TOTAL: 13
PASS:  12
SKIP:  0
XFAIL: 0
FAIL:  1
XPASS: 0
ERROR: 0

.. contents:: :depth: 2

FAIL: ibus-engine-switch

/ibus/engine-switch/global-engine: 
(/home/xavier/Downloads/ibus-1.5.13/src/tests/.libs/lt-ibus-engine-switch:28232): GLib-CRITICAL **: Source ID 4 was not found when attempting to remove it
Trace/breakpoint trap
FAIL ibus-engine-switch (exit status: 133)

Thanks

**Comment by fujiwarat** [comment]
I thought this problem was fixed but actually not.
Thanks for your report.

**Comment by fujiwarat** [comment]
The suggested patch is here:
[ibus-xx-test.txt](https://github.com/ibus/ibus/files/377506/ibus-xx-test.txt)
