### ISSUE TITLE
Unicode input not available when using an IME

### ISSUE THREAD

**Issue by MCManuelLP** [ibus/ibus#1869]
I've tested this with mozc and some others and with none, the Ctrl+Shift+U shortcut does anything.

I suppose this 'affects' all input methods that are not xkb based.

I'm not sure if this is intended behaviour or not.

I'd like to use it while using an IME because I generally don't switch input method, but rather just switch the input mode.

**Comment by fujiwarat** [comment]
I explained this feature is available in XKB engines only and the plan is that to enhance the GUI.
And then other engines will be able to the API. Actually ibus already provides ibus_emoji_dict_load().
ibus-anthy already provides the localized emoji typing and we don't maintain mozc.
