### ISSUE TITLE
Build failed with emoji.json not found

### ISSUE THREAD

**Issue by yochenhsieh** [ibus/ibus#1870]
version: ibus-1.5.14
distro: Mageia Cauldron

what happend: rpm package build process failed because file 'emoji.json' does not exist.

  CCLD     emoji-parser
./emoji-parser --xml ./../data/annotations/en.xml \
--json /usr/lib/node_modules/emojione/emoji.json --out emoji.dict

(emoji-parser:13574): IBUS-ERROR **: Failed to open file '/usr/lib/node_modules/emojione/emoji.json': No such file or directory
Makefile:1352: recipe for target 'emoji.dict' failed
make[4]: *** [emoji.dict] ???????? (core dumped)
make[4]: Leaving directory '/home/user/rpmbuild/BUILD/ibus-1.5.14/src'
Makefile:1033: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/user/rpmbuild/BUILD/ibus-1.5.14/src'
Makefile:773: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/user/rpmbuild/BUILD/ibus-1.5.14/src'
Makefile:679: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/rpmbuild/BUILD/ibus-1.5.14'
Makefile:586: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fujiwarat** [comment]
See https://groups.google.com/forum/#!topic/ibus-devel/UfmHhxDMZlA

**Comment by midhunanew** [comment]
I ran into another situation, I had changed some npm settings visiting this link.

[fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions)

which made the npm modules to be in my home directory and broke the installation.

Please ensure your settings by `npm config ls -l` when you start thinking the above comment doesn't work. ;)

**Comment by fujiwarat** [comment]
Yes, `-g` option requires the write permission.
You can install it locally with npm or get https://github.com/Ranks/emojione
