### ISSUE TITLE
background is too black in a selected candidate in ibus lookup table

### ISSUE THREAD

**Issue by liangjs** [ibus/ibus#1871]
the background is so black that I cannot see the word.

**Comment by fujiwarat** [comment]
Which background?
Can you explain more?

**Comment by liangjs** [comment]
I don't know how to show you a picture.
I'm using KDE5.
When I input some text, ibus show me a small window that contains some word for me to select. The first word is the default one, and it has a very black background under the first word which I think is telling me that this is the word provided when you press 'space'.

**Comment by fujiwarat** [comment]
It would be good to attach your screenshot to explain your problem and  you can choose one of the screenshot applications:
```
# dnf search screenshot
Last metadata expiration check: 1:39:51 ago on Fri Aug 12 14:14:34 2016.
=========================== N/S Matched: screenshot ============================
vdr-screenshot.i686 : VDR plugin: Takes screenshots
vdr-screenshot.x86_64 : VDR plugin: Takes screenshots
gnome-screenshot.x86_64 : A screenshot utility for GNOME
gnome-shell-extension-screenshot-window-sizer.noarch : Screenshot window sizer
                                                     : for GNOME Shell
mate-screenshot.x86_64 : A utility to take a screen-shot of the desktop
screenie-composer.x86_64 : Fancy screenshot composer
spectacle.x86_64 : Screenshot capture utility
screenfetch.noarch : A "Bash Screenshot Information Tool"
xfce4-screenshooter-plugin.x86_64 : Screenshot utility for the Xfce panel
xfce4-screenshooter.x86_64 : Screenshot utility for the Xfce desktop
lximage-qt.x86_64 : The image viewer and screenshot tool for LXQt
shutter.noarch : GTK+2-based screenshot application written in Perl
```

Which version of QT is used? I think Qt 5.6.0 fixes preedit color:
```
# rpm -qf /usr/lib64/libQt5Gui.so.5.6.0 
qt5-qtbase-gui-5.6.0-9.fc24.x86_64
# rpm -ql qt5-qtbase-gui | grep ibus
/usr/lib64/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so
```

**Comment by liangjs** [comment]
![ibus](https://cloud.githubusercontent.com/assets/10512425/17646673/dae237ec-6206-11e6-883d-e6a30b18ae18.png)


`
% ls /usr/lib/libQt5Gui.so -l                                                                                                                     :(
lrwxrwxrwx 1 root root 18 Aug  2 15:37 /usr/lib/libQt5Gui.so -> libQt5Gui.so.5.7.0
`

**Comment by fujiwarat** [comment]
I haven't tried Qt 5.7 yet but Fedora 25 Alpha is scheduled at August 23th.
Which distro do you use?

**Comment by liangjs** [comment]
Archlinux

**Comment by esmeetu** [comment]
same with that. 
os info: `arch + kde plasma 5.7.4`, the input method is [`RIME IME`](http://rime.im/), using `librime` on ibus.
By now i just can use `ibus-daemon --panel=/usr/lib/kimpanel-ibus-panel -dx` to change another style.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem with plasma-workspace 5.8.1 in Fedora 25.
I don't think kimpanel works with ibus 1.5.y.
![ibus-back-fujiwara](https://cloud.githubusercontent.com/assets/105929/20133207/df08a968-a6a9-11e6-9251-fc8cd7e8cffe.png)

Do you have /usr/lib*/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so ?
Do you set QT_IM_MODULE=ibus ?
How is the output of "env QT_IM_MODULE=ibus strace kwrite |& grep platform" ?

**Comment by liangjs** [comment]
there's no libibusplatforminputcontextplugin.so
I've set QT_IM_MODULE=ibus

"env QT_IM_MODULE=ibus strace kwrite |& grep platform" show the following output:
`stat("/usr/lib/qt/plugins/platforms/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/qt/plugins/platforms", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
statfs("/usr/lib/qt/plugins/platforms/", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=103179114, f_bfree=94414491, f_bavail=89167515, f_files=26214400, f_ffree=25738289, f_fsid={2874739619, 913469720}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/KWinQpaPlugin.so", {st_mode=S_IFREG|0755, st_size=457904, ...}) = 0
open("/usr/lib/qt/plugins/platforms/KWinQpaPlugin.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqeglfs.so", {st_mode=S_IFREG|0755, st_size=10560, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqeglfs.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqlinuxfb.so", {st_mode=S_IFREG|0755, st_size=346584, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqlinuxfb.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqminimal.so", {st_mode=S_IFREG|0755, st_size=143704, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqminimal.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqminimalegl.so", {st_mode=S_IFREG|0755, st_size=181304, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqminimalegl.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqoffscreen.so", {st_mode=S_IFREG|0755, st_size=143992, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqoffscreen.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqxcb.so", {st_mode=S_IFREG|0755, st_size=10560, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqxcb.so", O_RDONLY|O_CLOEXEC) = 3
stat("/usr/bin/platforms/.", 0x7ffbffffa430) = -1 ENOENT (No such file or directory)
open("/usr/lib/qt/plugins/platforms/libqxcb.so", O_RDONLY|O_CLOEXEC) = 3
stat("/usr/lib/qt/plugins/platformthemes/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/qt/plugins/platformthemes", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
statfs("/usr/lib/qt/plugins/platformthemes/", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=103179114, f_bfree=94414491, f_bavail=89167515, f_files=26214400, f_ffree=25738289, f_fsid={2874739619, 913469720}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
lstat("/usr/lib/qt/plugins/platformthemes", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so", {st_mode=S_IFREG|0755, st_size=214688, ...}) = 0
open("/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so", O_RDONLY|O_CLOEXEC) = 6
lstat("/usr/lib/qt/plugins/platformthemes", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platformthemes/libqgtk3.so", {st_mode=S_IFREG|0755, st_size=325600, ...}) = 0
open("/usr/lib/qt/plugins/platformthemes/libqgtk3.so", O_RDONLY|O_CLOEXEC) = 6
stat("/usr/bin/platformthemes/.", 0x7ffbffffa410) = -1 ENOENT (No such file or directory)
open("/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so", O_RDONLY|O_CLOEXEC) = 6
stat("/usr/lib/qt/plugins/platforminputcontexts/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
statfs("/usr/lib/qt/plugins/platforminputcontexts/", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=103179114, f_bfree=94414491, f_bavail=89167515, f_files=26214400, f_ffree=25738289, f_fsid={2874739619, 913469720}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=48048, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
lstat("/usr/lib/qt/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=93880, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
lstat("/usr/lib/qt/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=114616, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
stat("/usr/bin/platforminputcontexts/.", 0x7ffbffffa5c0) = -1 ENOENT (No such file or directory)
open("/usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6`

**Comment by liangjs** [comment]
there is `libibusplatforminputcontextplugin.so` in `/usr/lib/qt/plugins/platforminputcontexts/` but not in `/usr/lib*/qt5/plugins/platforminputcontexts/`
I've set QT_IM_MODULE=ibus
output of "env QT_IM_MODULE=ibus strace kwrite |& grep platform":
`stat("/usr/lib/qt/plugins/platforms/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/qt/plugins/platforms", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
statfs("/usr/lib/qt/plugins/platforms/", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=103179114, f_bfree=94414491, f_bavail=89167515, f_files=26214400, f_ffree=25738289, f_fsid={2874739619, 913469720}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/KWinQpaPlugin.so", {st_mode=S_IFREG|0755, st_size=457904, ...}) = 0
open("/usr/lib/qt/plugins/platforms/KWinQpaPlugin.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqeglfs.so", {st_mode=S_IFREG|0755, st_size=10560, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqeglfs.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqlinuxfb.so", {st_mode=S_IFREG|0755, st_size=346584, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqlinuxfb.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqminimal.so", {st_mode=S_IFREG|0755, st_size=143704, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqminimal.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqminimalegl.so", {st_mode=S_IFREG|0755, st_size=181304, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqminimalegl.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqoffscreen.so", {st_mode=S_IFREG|0755, st_size=143992, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqoffscreen.so", O_RDONLY|O_CLOEXEC) = 3
lstat("/usr/lib/qt/plugins/platforms", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforms/libqxcb.so", {st_mode=S_IFREG|0755, st_size=10560, ...}) = 0
open("/usr/lib/qt/plugins/platforms/libqxcb.so", O_RDONLY|O_CLOEXEC) = 3
stat("/usr/bin/platforms/.", 0x7ffbffffa430) = -1 ENOENT (No such file or directory)
open("/usr/lib/qt/plugins/platforms/libqxcb.so", O_RDONLY|O_CLOEXEC) = 3
stat("/usr/lib/qt/plugins/platformthemes/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/qt/plugins/platformthemes", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
statfs("/usr/lib/qt/plugins/platformthemes/", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=103179114, f_bfree=94414491, f_bavail=89167515, f_files=26214400, f_ffree=25738289, f_fsid={2874739619, 913469720}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
lstat("/usr/lib/qt/plugins/platformthemes", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so", {st_mode=S_IFREG|0755, st_size=214688, ...}) = 0
open("/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so", O_RDONLY|O_CLOEXEC) = 6
lstat("/usr/lib/qt/plugins/platformthemes", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platformthemes/libqgtk3.so", {st_mode=S_IFREG|0755, st_size=325600, ...}) = 0
open("/usr/lib/qt/plugins/platformthemes/libqgtk3.so", O_RDONLY|O_CLOEXEC) = 6
stat("/usr/bin/platformthemes/.", 0x7ffbffffa410) = -1 ENOENT (No such file or directory)
open("/usr/lib/qt/plugins/platformthemes/KDEPlasmaPlatformTheme.so", O_RDONLY|O_CLOEXEC) = 6
stat("/usr/lib/qt/plugins/platforminputcontexts/.", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 6
statfs("/usr/lib/qt/plugins/platforminputcontexts/", {f_type=EXT2_SUPER_MAGIC, f_bsize=4096, f_blocks=103179114, f_bfree=94414491, f_bavail=89167515, f_files=26214400, f_ffree=25738289, f_fsid={2874739619, 913469720}, f_namelen=255, f_frsize=4096, f_flags=ST_VALID|ST_RELATIME}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=48048, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
lstat("/usr/lib/qt/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=93880, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
lstat("/usr/lib/qt/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
lstat("/usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", {st_mode=S_IFREG|0755, st_size=114616, ...}) = 0
open("/usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6
stat("/usr/bin/platforminputcontexts/.", 0x7ffbffffa5c0) = -1 ENOENT (No such file or directory)
open("/usr/lib/qt/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 6`

**Comment by fujiwarat** [comment]
OK, your qt side settings are right.
Looking at your image again, you have a color problem in IBus lookup window - it's drawn by IBus and GTK.
Which ibus version do you use?
Which gtk3 version do you use?

```
% ibus version
IBus 1.5.14
% ldd /usr/lib*/ibus-ui-gtk3 | grep gtk
	libgtk-3.so.0 => /lib64/libgtk-3.so.0 (0x00007f64335f3000)
% rpm -qf /lib64/libgtk-3.so.0
gtk3-3.22.2-2.fc25.x86_64
```

**Comment by liangjs** [comment]
```
% ibus version
IBus 1.5.14
% ldd /usr/lib/ibus/ibus-ui-gtk3 | grep gtk
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007efbf74d2000)
% pacman -Q gtk3
gtk3 3.22.3-1
```

**Comment by huanle0610** [comment]
I have the same problem in Manjaro(arch heart), I hope to be given a setting file where I can change the foreground or background color.

**Comment by fujiwarat** [comment]
Seems arch specific issue but not ibus upstream one.
I will have no chance to try arch since the installation is complicated.

**Comment by huanle0610** [comment]
I understand your situation and thank for your source files.
![screenshot_20170111_015716](https://cloud.githubusercontent.com/assets/953028/21818078/6aaf0548-d7a1-11e6-987e-0b0462e2d419.png)

**Comment by fujiwarat** [comment]
In GTK 3.22 or later, '-gtk-secondary-caret-color' is used for the selected background color:

https://git.gnome.org/browse/gtk+/tree/gtk/theme/Adwaita/gtk-contained.css#n16

And 'background-color' no longer returns the right color by default.
I guess the Arch GTK theme does not have '-gtk-secondary-caret-color'  property.

**Comment by huanle0610** [comment]
You are right, and I tried  ~/.config/gtk-3.0/gtk.css with content
`* {
  -gtk-secondary-caret-color: #dbdee6; 
}
`
and then

`ibus-daemon -rdx`

It works.

![screenshot_20170112_002850](https://cloud.githubusercontent.com/assets/953028/21856830/4191a31a-d85e-11e6-9acc-aaf134777ac0.png)

**Comment by fujiwarat** [comment]
Great.
You can get the current theme name:
```
% cat a.py
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

settings = Gtk.Settings.get_default()
print 'theme-name:', settings.get_property('gtk-theme-name')

% python a.py
```

The theme is installed in /usr/share/themes and probably I think it's good to file a bug for the theme to have '-gtk-secondary-caret-color' property.

**Comment by fujiwarat** [comment]
The GTK default theme 'Adwaita' works fine.

**Comment by huanle0610** [comment]
theme-name: Maia
```
$ lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        16.10
Codename:       Fringilla
```

**Comment by fujiwarat** [comment]
The color is common between GTK applications but not IBus lookup window only.
E.g. Activate any strings on gedit text buffer, any strings on GTK open dialog.
So if both the selected color and foreground color is dark on ibus, I think you could see the same problem on others.

**Comment by huanle0610** [comment]
It shows like this.
![screenshot_20170113_210452](https://cloud.githubusercontent.com/assets/953028/21931020/17e03d3e-d9d4-11e6-8d3b-fe1395fcc3c1.png)
```
$ gedit --version
gedit - Version 3.22.0
```

I found a version of [Maia theme](https://api.kde-look.org/p/1013512/), it doesn't have  -gtk-secondary-caret-color property.
Anyway,  ~/.config/gtk-3.0/gtk.css works well and I could chose any color I like as background color in ibus.

**Comment by fujiwarat** [comment]
I expect IBus lookup window color and other text application colors are same so I'd fix your result.
I tried Maia theme but it does not work with either XFCE or MATE or Plasma desktop which are provided in Fedora.

[window.txt](https://github.com/ibus/ibus/files/705620/window.txt)

Can you compile the above C file?
```
% mv window.txt window.c
% gcc -o window window.c `pkg-config --cflags --libs gtk+-3.0`
% ./window
```
When you click "Get CSS" button, the program outputs the test result on the terminal.

**Comment by huanle0610** [comment]
```
$ ./window 
background-color (r: 1.000000, g: 1.000000, b: 1.000000, a: 1.000000)
-gtk-secondary-caret-color (r: 0.094118, g: 0.156863, b: 0.129412, a: 1.000000)
```

**Comment by fujiwarat** [comment]
From your result, 'background-color' property is not relative with your green color.
Can you investigate which css value is used for the selected background green color?
You can comment out /usr/shre/themes/$THEME/gtk-3.0/*.css and run gedit and 'window' for the debugging to identify the css value.
If you uncomment "gtk_box_pack_start (GTK_BOX (vbox), entry, ..." and compile the file again, 'window' will show the entry box for the testing.
I cannot test Maia theme in my Fedora.

**Comment by huanle0610** [comment]
With inspector opened, I found Maia has  -gtk-secondary-caret-color. (#182128 / rgb(24,33,40)) 
```
gcc -o window window.c `pkg-config --cflags --libs gtk+-3.0` && GTK_DEBUG=interactive ./window 
```
![screenshot_20170116_000519](https://cloud.githubusercontent.com/assets/953028/21964047/9d81fdd6-db7f-11e6-9a5a-d84e8864c1b5.png)

ibus gets the color correctly, but the color is too dark.   
![screenshot_20170116_001228](https://cloud.githubusercontent.com/assets/953028/21964092/a23771f2-db80-11e6-984f-d8d7b85fdff8.png)

For label, Maia use those style
```
color: rgb(24,33,40);
-gtk-secondary-caret-color: rgb(24,33,40);
background-color: rgba(0,0,0,0);   
```
The last zero saves it.

![screenshot_20170116_002311](https://cloud.githubusercontent.com/assets/953028/21964175/067bbd20-db82-11e6-87b5-ce16d495b2ed.png)

For css designers, they might care textselection of entry,textview more about label.
I suggest ibus pick selection color from entry instead of label.

**Comment by fujiwarat** [comment]
OK, thanks for the testing.

> -gtk-secondary-caret-color: rgb(24,33,40);

I think your label does not define the line because this issue happens.

When I test the color of entry, I cannot get the selected foreground color correctly.
(normal foreground is back and selected foreground is white but the entry returned black.)
Now I'm thinking to use textview.

Probably you can replace "gtk_entry_new ()" with "gtk_text_view_new ()" in window.c and compile it again.

If it's fine, I will try to integrate [ibus-1871-lookup-background-color.patch](https://github.com/ibus/ibus/files/707990/ibus-1871-lookup-background-color.txt)

**Comment by fujiwarat** [comment]
My patch means, IBusCandidateArea tries to get 'background-color' property at first.
If the selected 'background-color' is different from the normal 'background-color', IBusCandidateArea supposes the 'background-color' is defined correctly and use that value.
If not, IBusCandidateArea uses selected '-gtk-secondary-caret-color'.

Since there are several themes, I cannot assume all themes use the GTK 3.22 format now and I try 'background-color' property at first and verify the value can be used.

**Comment by huanle0610** [comment]
I tested "gtk_text_view_new ()", it's fine. 
The patch is also awesome.
![screenshot_20170116_210519](https://cloud.githubusercontent.com/assets/953028/21984192/c2a6d5ae-dc2f-11e6-9449-c90f18d69ad5.png)

**Comment by zhihhuang** [comment]
@huanle0610 Hi, I am having the same issue and it's pretty annoying. Following the conversation between you and @fujiwarat , I didn't catch much. Could you please give me some more straightforward procedures to fix the issue?
I am running IBus 1.5.12; and I can see that on my Plasma 5.8.3 --> System Settings --> Application Style --> GNOME Application Style (GTK), 'Breeze' is selected for both 'Select a GTK2 Theme' and 'Select a GTK3 Theme'.
Also, I have tried following 'solutions', but none of them could work:
1) Adding '* { -gtk-secondary-caret-color: #dbdee6; }' to /usr/share/themes/Breeze/gtk-3.0/gtk.css
2) Adding '* { -gtk-secondary-caret-color: #dbdee6; }' to /usr/share/themes/Breeze/gtk-3.20/gtk.css
3) Adding '* { -gtk-secondary-caret-color: #dbdee6; }' to .config/gtk-3.0/gtk.css
I would reallly appreciate your help.

**Comment by fujiwarat** [comment]
@zhihhuang 
I'd ask the same test below.
But I don't see any problems with Breeze theme in Plasma 5.7 without applying the patch, which is available in Fedora 25 by default.

1. Revert your changes in all gtk.css files
2. Get your theme name with the following script:
```
% cat a.py
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

settings = Gtk.Settings.get_default()
print 'theme-name:', settings.get_property('gtk-theme-name')

% python a.py
```
3. Get [window.txt](https://github.com/ibus/ibus/files/709895/window.txt) and click "Get CSS".
```
% mv window.txt window.c
% gcc -o window window.c `pkg-config --cflags --libs gtk+-3.0`
% ./window
```

**Comment by fujiwarat** [comment]
OK, I have to install breeze-gtk package for 'GNOME Application Style (GTK)' and confirmed my patch works.

**Comment by zhihhuang** [comment]
@fujiwarat Sorry that I am in the office now and away from my home laptop which has the issue. I will follow your procedures when I am back. Great thanks for your help!

**Comment by zhihhuang** [comment]
@fujiwarat Hi, I just got back from work. "theme-name: Breeze" is given after running you python script. And it is returned as follows after running the window program:
`color (r: 0.937255, g: 0.941176, b: 0.945098, a: 1.000000)
normal background-color (r: 0.988235, g: 0.988235, b: 0.988235, a: 1.000000)
background-color (r: 0.239216, g: 0.682353, b: 0.913725, a: 1.000000)
-gtk-secondary-caret-color (r: 0.192157, g: 0.211765, b: 0.231373, a: 1.000000)`

**Comment by fujiwarat** [comment]
From your result, selected foreground is almost white, normal background is almost white, selected background is blue, -gtk-secondary-caret-color is almost black.
Since the normal background and selected background is different in your result, my patch will show the blue background in your Breeze theme.

And I think gtk.css workaround should work.
background-color (r: 0.239216, g: 0.682353, b: 0.913725, a: 1.000000) is #3daee9
You can save '* { -gtk-secondary-caret-color: #3daee9; }' in $HOME/.config/gtk-3.0/gtk.css

**Comment by zhihhuang** [comment]
I have tried adding '* { -gtk-secondary-caret-color: #3daee9; }' in $HOME/.config/gtk-3.0/gtk.css (it does not exist so I created this file.) But unfortunately nothing changes, and the issue is still there.
I want to try your patch though, however I do not know how to apply it to my system. Could you please teach me how to apply the patch?

**Comment by zhihhuang** [comment]
Great news here, the issue disappeared after I upgraded the ibus to the latest version 1.5.14. I am running Gentoo and the latest stable version of ibus is 1.5.12, which I was running with the background issue. But anyway, the issue disappear now.
Really appreciate your help with the issue.

**Comment by fujiwarat** [comment]
Looks good and that's why I asked the ibus version at first.
Will integrate the patch.
