### ISSUE TITLE
Linux Mint 18 taskbar not responding to mouse clicks when IBus enabled

### ISSUE THREAD

**Issue by kochinc** [ibus/ibus#1874]
I recently upgraded my Linux Mint from 17.3 to 18 Cinnamon. Immediately I found the taskbar panel at the bottom of the screen didn't respond to mouse clicks. After some tests, I realized it was related to IBus.

When IBus was enabled and with 'Show property panel' set to 'Always' on the IBus Preferences dialog, the Cinnamon taskbar panel completely stopped responding to mouse clicks. When the setting was changed to 'Do not show', the taskbar processed clicks without any problems. It didn't matter whether there were input method added or not.

If 'Show property panel' was set to 'Hide automatically', the taskbar panel wouldn't respond to mouse clicks only when the input method's property panel was visible on the screen. I tried Chewing and Intelligent Pinyin, and both showed the behavior.

This had also been reported at https://bugs.launchpad.net/linuxmint/+bug/1598999.

**Comment by fujiwarat** [comment]
Which version cinnamon do you use?
```
% rpm -qf /usr/bin/cinnamon-session
cinnamon-session-3.0.1-3.fc25.x86_64
```

In my Fedora 25, Cinnamon panel menu and calendar applet works fine with mouse.

**Comment by fujiwarat** [comment]
Fedora does not have Mint desktop but I can try Cinnamon.

**Comment by kochinc** [comment]
This is the version of the cinnamon-session on my Linux Mint 18 box:
```
$ dpkg-query --show cinnamon-session
cinnamon-session	3.0.1+sarah
```

**Comment by fujiwarat** [comment]
I cannot reproduce your problem and I don't know what is the taskbar panel.
Can you indicate the taskbar panel with a screenshot?

**Comment by fujiwarat** [comment]
Do you have a chance to get a screenshot?
You can choose xfce4-screenshooter or 'gnome-screenshot -i'.

**Comment by kochinc** [comment]
When I said taskbar panel, I meant the panel across the bottom of the screen. Please see the screenshots below.

The first screenshot shows IBus was enabled with Chewing. I pointed the mouse at the Menu, the word Menu became brighter which indicated the Menu was usable. I could click on the Menu or any other icons in the taskbar panel to run its command. 
![mint-18-taskbar-working](https://cloud.githubusercontent.com/assets/1756865/18954079/4dab62f8-861f-11e6-9510-b4855fb6afef.jpg)

This screenshot shows that Chewing's property panel was on the screen. Again, the mouse was pointed at the Menu, but this time the Menu was not usable. In fact, none of the icons in the taskbar were usable. Clicking on them did nothing at all.
![mint-18-taskbar-not-working](https://cloud.githubusercontent.com/assets/1756865/18954083/51289d9c-861f-11e6-804c-385b23043cfa.jpg)

**Comment by fujiwarat** [comment]
I cannot reproduce your problem in Fedora 25 on VirtualBox.
![cinnamon-fujiwara](https://cloud.githubusercontent.com/assets/105929/18980834/2571e4d4-8713-11e6-9516-6c6d6819cb3f.png)

**Comment by kochinc** [comment]
Thank you for looking into this issue. I guess it must be unique to Linux Mint 18. I never experienced this problem in prior versions.

**Comment by jabbany** [comment]
I'm getting the same problem here too also from an upgrade 17.3->18. 
Thanks for the workaround/information! I had no idea it was an iBus issue and was debugging this for a while. 

The cinnamon panel "works" (i.e. I can get into edit mode, switching windows causes the panel to update etc.) but just that no clicks are being sent through. 

I'm temporarily working around this by turning off show properties panel as suggested.

**Comment by fujiwarat** [comment]
OK, I reproduced your problem.
I'm surprised the muffin bug is not fixed yet.

Fedora muffin has implemented an internal patch.
https://bugzilla.redhat.com/show_bug.cgi?id=1226680
http://pkgs.fedoraproject.org/cgit/rpms/muffin.git/tree/revert_ibus.patch

The workaround is to rename /usr/lib/ibus-ui-gtk3 to /usr/lib/ibus/ibus-ui-gtk3.orig .
```
% ibus exit
% ibus-daemon --xim &
% /usr/lib/ibus-ui-gtk3.orig &
```

The ibus panel settings is /usr/share/ibus/component/gtkpanel.xml

**Comment by kochinc** [comment]
@fujiwarat  
Thank you so much! Your workaround works beautifully.
