### ISSUE TITLE
Question: how to enable XCompose?

### ISSUE THREAD

**Issue by Hi-Angel** [ibus/ibus#1876]
Grepping through the ibus source I see it reads ~/.XCompose file at some moment. There's also [this solved issue](https://github.com/ibus/ibus/issues/1744) that's relevant to XCompose.

But so far come up with nothing. I see in my distro a package for compose in `ibus-table-others`, but neither it reads `~/.XCompose` *(I can say because I can type nothing from [a popular xcompose](https://github.com/kragen/xcompose) which worked with XIM)*, nor it seem to be part of the vanilla ibus code where I see XCompose.

**Comment by fujiwarat** [comment]
ibus-table-others is not used that feature.
You can choose "English - English (US)" on ibus-setup.
ibus 1.5.11 or later is required to read .XCompose.

**Comment by fujiwarat** [comment]
If you still have any questions, you can comment them here.

**Comment by Hi-Angel** [comment]
Whoa, you're awesome!! It was so easy, just if I knew how does input works a little bit better, I was searching for an answer for so long!

To sum-up: to make it working one have to set with `setxkbmap` the compose key, like `setxkbmap -option compose:rwin` to use the right logo key. E.g. here's a command I used:

	setxkbmap -layout us,ru -option grp:rctrl_rshift_toggle,grp_led:scroll,lv3:ralt_switch,compose:rwin

An important note: it does work on Wayland as well!

**Comment by Hi-Angel** [comment]
@fujiwarat a little technical question: does ibus using libxkbcommon somehow? Or does it rather reads xkb settings, and simulate them in some way?

It's just a bit confusing, as I've heard libxkbcommon is used by toolkits, but ibus is rather IM.

**Comment by fujiwarat** [comment]
> setxkbmap -layout us,ru -option grp:rctrl_rshift_toggle,grp_led:scroll,lv3:ralt_switch,compose:rwin

I think you need '-option' option only and you can switch IMEs using IME switcher dialog because IBus also runs 'ru,us' instead of 'us'.
For that option for GNOME, run 'gnome-control-center keyboard' -> 'Typing' -> 'Compose Key', 
and run gnome-tweak-tool -> 'Typing'.
You also can google the option settings for other desktops.

> does ibus using libxkbcommon somehow? 

The behavior is a little different between GNOME and non-GNOME desktops.
IBus just runs setxkbmap internally.
GNOME calls XkbLockGroup() internally.

**Comment by marmistrz** [comment]
How can I use XCompose with the Russian setup? I need a quick and easy way of inputting the [U0301](http://www.fileformat.info/info/unicode/char/0301/index.htm) character in Russian layout

**Comment by fujiwarat** [comment]
> How can I use XCompose with the Russian setup? I need a quick and easy way of inputting the U0301 character in Russian layout

You can create your $HOME/.XCompose and refer the system compose files:
E.g. in /usr/share/X11/locale/en_US.UTF-8/Compose
```
<Multi_key> <apostrophe> <apostrophe>   : "´"   acute # ACUTE ACCENT
<dead_acute> <nobreakspace>           : "́"   U0301      # COMBINING ACUTE ACCENT
```
E.g. in /usr/share/X11/locale/fi_FI.UTF-8/Compose
```
<dead_acute> <space>                    :  "´"  U00B4  #  ACUTE ACCENT
```

**Comment by Hi-Angel** [comment]
@marmistrz depending on your luck getting XCompose to work might be a daunting task. I have spent a vast amount of time on this, and to make sure it won't get lost [wrote it up here](https://hitechangel.wordpress.com/2016/10/28/archlinux-compose-key/). *(note though, it's not a blog ATM, just a stuff I couldn't find on google)*

**Comment by fujiwarat** [comment]
>  wrote it up here.

Your mention is quite wrong. ibus works fine with XKB.

**Comment by Hi-Angel** [comment]
@fujiwarat please can you quote instead the text you're talking about. I don't quite understand where did you get it from.

**Comment by fujiwarat** [comment]
>  they doesn’t even read ~/.XCompose.

Not right.

> but you didn’t really want ibus as it’s pretty raw. 

Not right

> CJK people doesn’t like ibus either, idk why

Not right.

It's your personal argument.

**Comment by Hi-Angel** [comment]
> > they doesn’t even read ~/.XCompose.
> 
> Not right.

Just to make sure we understand each other — are you talking [about this](https://wiki.archlinux.org/index.php/IBus#Entering_Special_Characters.E2.80.94The_Compose_Input_Method)? Because this is what I was talking about in this sentence.

> >but you didn’t really want ibus as it’s pretty raw.
> 
> Not right

Yeah, except that the rest of the paragraph explains why "it is raw".

>>CJK people doesn’t like ibus either, idk why
>
>Not right.

Mostly the source [is this article](https://lwn.net/Articles/503320/), and there is a bunch of references to mailing list.

> It's your personal argument.
Not right.

**Comment by fujiwarat** [comment]
> Just to make sure we understand each other — are you talking about this? 

No, IBus XKB engines read .XCompse.

> Yeah, except that the rest of the paragraph explains why "it is raw".

I don't think your rest indicates why it's raw but just your feeling.

> Mostly the source is this article, 

It does not indicate your mention.

>  there is a bunch of references to mailing list.

As I explained, your .XCompose file has the long sequences and it does not indicate "CJK people doesn’t like ibus either, idk why".

Stop to integrate your feeling here but leave it your blog only.

**Comment by Hi-Angel** [comment]
> No, IBus XKB engines read .XCompse.

Well, too bad in this sentence I wasn't talking about XKB engine, but about the Compose input method, and it is explicitly mentioned in the paragraph you quoted in the prev. comment.

> I don't think your rest indicates why it's raw but just your feeling.

This is not how discussions work. "The rest" are arguments. If you disagree with them, you write counter-arguments. Replying arguments with plain "I disagree" is childish and doesn't work.

> It does not indicate your mention.

Ok, that's fair, I'll edit the post to include the link.

> As I explained, your .XCompose file has the long sequences and it does not indicate "CJK people doesn’t like ibus either, idk why".

Err… I don't get this one. My sentence that CJK folks don't like ibus is completely irrelevant to XCompose problems.

**Comment by fujiwarat** [comment]
> Well, too bad in this sentence I wasn't talking about XKB engine, b

No, you wrote IBus does not read .XCompose.  Not right.

> This is not how discussions work. "The rest" are arguments.

That's *you* think but you wrote "you didn’t really want ibus as it’s pretty raw". Not right.

> My sentence that CJK folks don't like ibus is completely irrelevant to XCompose problems.

There is nothinkg that your problems are so important for CJK folks. It's your personal opinion.

**Comment by marmistrz** [comment]
Hmmm, I have the following line in my `~/.XCompose`:
```
<Multi_key> <apostrophe> <apostrophe> 	: U0301 # combining acute accent
```
but pressing `<compose> <apostrophe> <apostrophe>` doesn't give the combining acute, just the `\`` sign.

**Comment by Hi-Angel** [comment]
@marmistrz dunno, perhaps you need to have the character in `""` too. Just for the safe case, try [this one](https://github.com/kragen/xcompose/blob/master/dotXCompose), it does have `combining acute accent` as a <kbd>Compose</kbd><kbd>\\</kbd><kbd>'</kdb>

**Comment by marmistrz** [comment]
@Hi-Angel this works if I use the Polish keyboard layout. As soon as I switch to the Russian (phonetic) layout, the combination outputs a simple <kbd>'</kbd>

**Comment by Hi-Angel** [comment]
@marmistrz don't forget that it uses not keycodes but symbols which depends on the current layout. I.e. you can't type it in Russian layout simply because the layout doesn't have <kbd>'</kbd> symbol.

You can rebind it to symbols present on both layouts if you want to.

**Comment by marmistrz** [comment]
@Hi-Angel it's the phonetic Russian layout which has the apostrophe there.
`jkl;'` is `йкл;'` on this layout.

**Comment by fujiwarat** [comment]
@marmistrz You can debug ibus-daemon with `--verbose` option.
```
% ibus exit
% ibus-daemon --xim --verbose
```
When you switch your engine to an IBus XKB,  you will see a warning that your character should be enclosed by `"`.
Also the format `U0301` is not supported, you need to insert the character itself in .XCompose directly.
If you use the old ibus, Ctrl-Shift-u can insert the code point in .XCompose or Ctrl-Shift-e for the latest ibus.

**Comment by ttuegel** [comment]
I am also trying to use the Xcompose configuration from https://github.com/kragen/xcompose with IBus, but the wrong characters are inserted. For example, my `~/.Xcompose` has:
```
<Multi_key> <asterisk> <a> : "α" U03B1 # GREEK SMALL LETTER ALPHA
```
but when I type that combination, I get `å` instead of `α`. Other combinations don't work at all, for example I have
```
<Multi_key> <A> <less> : "Ɐ" U2C6F # LATIN CAPITAL LETTER TURNED A
```
but typing this combination doesn't insert anything at all. Is there a default Xcompose I have to disable? Or is there something else I have to do for IBus to recognize my `~/.Xcompose`?

**Comment by Hi-Angel** [comment]
@ttuegel did you set in `/etc/profile/`

	export GTK_IM_MODULE="ibus"
	export QT_IM_MODULE="ibus"

From my experience what you're seeing looks like result of an internal gtk IM, you need to set the aforementioned variables for ibus to be used.

**Comment by fujiwarat** [comment]
Can you try to restart ibus-daemon with verbose if you could see any warnings about the compose?
```
% ibus exit
% ibus-daemon --xim --verbose &
```

Also which keymap do you use?
```
% ibus engine
% setxkbmap -query
```

**Comment by ttuegel** [comment]
> From my experience what you're seeing looks like result of an internal gtk IM, you need to set the aforementioned variables for ibus to be used.

@Hi-Angel 
I have `GTK_IM_MODULE` and `QT_IM_MODULE` set. Other IBus features work, such as emoji input, so I think IBus is being used for input, it's just not respecting my `$HOME/.Xcompose`.

> Can you try to restart ibus-daemon with verbose if you could see any warnings about the compose?

@fujiwarat 
`ibus exit` leaves me with no input, so I had to restart the daemon this way, which produces only the one warning:
```
$ ibus-daemon --xim --verbose --replace &
(ibus-dconf:7492): dconf-WARNING **: unable to open named profile (ibus): using the null configuration.
```
```
$ ibus engine
xkb:us:dvorak:eng
```
```
$ setxkbmap -query
rules:      evdev
model:      pc101
layout:     us,us
variant:    dvorak,
options:    ctrl:swapcaps,compose:menu,grp:shifts_toggle
```

**Comment by ttuegel** [comment]
If I set `XCOMPOSEFILE=$HOME/.Xcompose` I get lots of warnings about entries in that file, but (most) of the keys work. It only seems to be a problem if `XCOMPOSEFILE` is unset.

**Comment by fujiwarat** [comment]
OK, $HOME/.Xcompose is not correct but $HOME/.XCompose
See also XCompose(1) man page.

**Comment by Shamaoke** [comment]
According to `man 5 Compose`,

    The compose file is searched for in the following order:
    
    - If the environment variable $XCOMPOSEFILE is set, its value is used as the name of the Compose file.
    
    - If the user's home directory has a file named .XCompose, it is used as the Compose file.
    
    - The system provided compose file is used by mapping the locale to a compose file from the list
      in /usr/share/X11/locale/compose.dir.

I have the `.XCompose` file with my personal compose sequences in my home directory. I suppose, having this file present should prevent loading the system compose file. However, the system sequences are still loaded in spite of that, so I have my sequences and system sequences both working.

The content of my compose file is the following:

    <Multi_key> <o> <equal>       : "◦" # U+25E6 WHITE BULLET
    <Multi_key> <greater> <equal> : "‣" # U+2023 TRIANGULAR BULLET

What's the reason of this behavour? How to prevent the system compose file to be loaded?

_Linux (Arch); Openbox 3.6.1; ibus 1.5.22_

**Comment by mike-fabian** [comment]
I don’t know what the reason is. But when I implemented compose support in ibus-typing-booster I noticed that the compose support in ibus core loads the system compose file, then '~/.config/ibus/Compose', then '~/.XCompose'. If sequences conflict, sequences in  files loaded later override sequences from the earlier files, but no sequences are  removed. You noticed the same thing.

I found this behaviour more useful than the behaviour described in the XCompose(1) man page:

> Compose files can use an "include" instruction.  This allows local modifications  to
> be  made  to  existing  compose files without including all of the content directly.
> For example, the system's iso8859-1 compose file can be included with  a  line  like
> this:
>     include "%S/iso8859-1/Compose"
> 
> There  are  several  substitutions  that can be made in the file name of the include
> instruction:
> 
> %H  expands to the user's home directory (the $HOME environment variable)
> 
> %L  expands  to  the   name   of   the   locale   specific   Compose   file   (i.e.,
>     "/usr/share/X11/locale/<localename>/Compose")
> 
> %S  expands   to  the  name  of  the  system  directory  for  Compose  files  (i.e.,
>     "/usr/share/X11/locale")
> 
> For example, you can include in your compose file the default Compose file by using:
>        include "%L"
> and then rewrite only the few rules that you need to change.  New compose rules  can
> be added, and previous ones replaced.

I found this useful because I could not see a reason to prevent
loading the system compose file. One can add personal compose
sequences in ~/.XCompose, if they conflict with system compose
sequences, then the personal ones are used.

But why prevent loading  the system compose sequences? Is it really useful to limit
the loading of the compose sequences to only ~/.XCompose and load other files only if
"include" statements are used?

**Comment by Shamaoke** [comment]
@mike-fabian 

> I could not see a reason to prevent loading the system compose file.

I could not see a reason to not allow a user to decide by himself, whether to load the system compose file along with a user compose file or not, whatever the motives for this a user would have.

> But why prevent loading the system compose sequences?

I do not propose _to prevent_ loading the system compose file, I propose to follow the well-established paradigm — do not load the system configuration file if a user configuration file exists.

**Comment by fujiwarat** [comment]
> Is it really useful to limit the loading of the compose sequences to only ~/.XCompose and load other files only if
"include" statements are used?

Why do you wish to load ~/.XCompose only?
The file can override the compose sequences but I think other system compose keys are still useful.

**Comment by mike-fabian** [comment]
> > Is it really useful to limit the loading of the compose sequences to only ~/.XCompose and load other files only if
> > "include" statements are used?
> 
> Why do you wish to load ~/.XCompose only?
> The file can override the compose sequences but I think other system compose keys are still useful.

Yes, I completely agree. It is better if a sequence which is not in ~/.XCompose does something (which might be useful) rather than just silently discarding it.

Actually ibus-typing-booster even does something going even further since recently, it automatically interprets even undefined dead key sequences:

https://github.com/mike-fabian/ibus-typing-booster/commit/d3b7e59f5a22613d735e1e7c276ab6d9e43bd900
