### ISSUE TITLE
Howto debug "No Global Engine"

### ISSUE THREAD

**Issue by lanoxx** [ibus/ibus#1878]
Hi,

I am trying to debug a problem on my computer, which prevents me from properly using the pinyin input. 

I always see the following message in the log and my Chinese input engine does not work. Switching between US English and German is no problem.

> Oct 11 11:03:39 earth gnome-session[3181]: ** (gnome-flashback:3303): WARNING **: Failed to get global engine - GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

How can I debug that?

When I run `ps aux |grep ibus` I see the following processes are running:

    ibus-daemon --xim --panel disable
    /usr/lib/ibus/ibus-dconf
    /usr/lib/ibus/ibus-x11 --kill-daemon
    /usr/lib/ibus/ibus-engine-simple

Any idea how I can continue?

**Comment by fujiwarat** [comment]
> No global engine.

This is an expected warning but not an error. The warning happens whether your pinyin has a problem or not.

> ibus-daemon --xim --panel disable

Since you run ibus without panel, I presume you use GNOME3 desktop.
gnome-shell restarts ibus automatically but there are several ways.
One idea is:
```
# mv /usr/bin/ibus-daemon /usr/bin/ibus-daemon.orig
% ibus exit
% ibus-daemon.orig --xim --panel disable --verbose
```

And you can see if there are any error messages on the terminal.

**Comment by lanoxx** [comment]
I am running gnome-flashback which uses an implementation almost identical to that of `gnome-shell`. When I run your commands I see no errors on the shell, but gnome-flashback logs an error that it cannot start ibus-daemon because it cannot find it.

Is there anything that I can do to narrow down the issue a little bit more? I am sure the implementation in gnome-flashback is correct, since I already had it working before. I can also correctly switch between engines, the only problem is that the pinyin input dialog never opens.

**Comment by lanoxx** [comment]
I notice that `/usr/lib/ibus/ibus-engine-libpinyin` is not running, is that needed for pinyin input? If I start it manually it does not seem to have any effect.

**Comment by fujiwarat** [comment]
So did you see any errors with '--verbose' option?

>  is that needed for pinyin input? 

Yes.

I have no time to try gnome-flashback  at present.
Does it use ibus-ui-gtk3? gnome-shell does not use it.
Is it based on X11 or Wayland?

>  the only problem is that the pinyin input dialog never opens.

What is the input dialog?

**Comment by lanoxx** [comment]
We have implemented our own input dialog similar to how gnome-shell is doing it, its basically a port of the gnome-shell javascript code to C. I am on Ubuntu 16.04 running gnome-flashback in an X11 session. You do not need to try out gnome-flashback, but it would be great if you could help me understand what ibus is doing in the background, how it should be started, etc. Then maybe I can figure out the issue by myself. 

Currently in gnome-flashback we have code to start the ibus-daemon, but I feel there is something else on my system that is also starting the ibus-daemon, because when I look at a process tree, the ibus-daemon is never a child of gnome-flashback. 

Here is the output:

> $ibus exit & ibus-daemon --xim --verbose
[1] 27435

> (ibus-ui-gtk3:27445): IBUS-WARNING **: panel.vala:221: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
open /home/sebastiangeiger/.cache/ibus/libpinyin/user.conf failed.cannot open ../lua/base.lua: No such file or directory
lua script loaded.
cannot open /home/sebastiangeiger/.config/ibus/libpinyin/user.lua: No such file or directory

> (ibus-ui-gtk3:27445): Gdk-CRITICAL **: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

When I just did that I used a single `&` rather then `&&` and it seems that made the ibus-daemon start fast enough to actually "gain control", this time I see a lot more ibus processes in the process three:

    27436  1.1  0.0 423184 10088 pts/2    Sl+  12:09   0:01 ibus-daemon --xim --verbose
    27444  0.0  0.0 267600  5400 pts/2    Sl+  12:09   0:00 /usr/lib/ibus/ibus-dconf
    27445  0.0  0.2 481124 33500 pts/2    Sl+  12:09   0:00 /usr/lib/ibus/ibus-ui-gtk3
    27451  0.1  0.1 432540 22500 pts/2    Sl+  12:09   0:00 /usr/lib/ibus/ibus-x11 --kill-daemon
    27463  0.0  0.0 191684  5484 pts/2    Sl+  12:09   0:00 /usr/lib/ibus/ibus-engine-simple
    27497  0.6  0.1 321640 25228 pts/2    Sl+  12:09   0:00 /usr/lib/ibus/ibus-engine-libpinyin --ibus

So I guess the problem could be that something on my system is starting ibus before gnome-flashback?

**Comment by fujiwarat** [comment]
You don't answer my question.

> Does it use ibus-ui-gtk3?

> 27436  1.1  0.0 423184 10088 pts/2    Sl+  12:09   0:01 ibus-daemon --xim --verbose
You should run ibus-daemon without panel option if the gnome-flashback has the owned icon.

> We have implemented our own input dialog similar to how gnome-shell is doing

Which gnome-shell's dialog is referred to the gnome-flackback one?

> You do not need to try out gnome-flashback,

OK, if I don't try it, roughly say,
1. You need to debug ibus-daemon if ibus-daemon receives the set engine dbus method from a panel icon.
2. You need to debug gtk3 immodule(im-ibus.so) if it's loaded and focus-in/out event is received.
3. You need to debug ibus-libpinyin receives keyevents and send the output strings.
