### ISSUE TITLE
Custom fon't doesn't seem to work (II)

### ISSUE THREAD

**Issue by rr-** [ibus/ibus#1879]
Similar to #1856.
After upgrading GTK3 on Arch Linux:

```
[2016-10-16 01:30] [ALPM] upgraded gtk3 (3.20.9-1 -> 3.22.1+8+ge11df6c-2)
```

The custom font setting in ibus has stopped working and default one is used. I'm not entirely sure about the font face, but the font size is certainly ignored.

**Comment by fujiwarat** [comment]
Hmm.., you're right.
Thank you for the report.

**Comment by dgeibi** [comment]
The setting don't work still after upgrading to the latest IBus.

**Comment by fujiwarat** [comment]
Gtk 3.22 no longer supports Pango syntax:

```
% /usr/libexec/ibus-ui-gtk3 

(ibus-ui-gtk3:2537): Gtk-WARNING **: Theme parsing error: <data>:1:21: Using Pango syntax for the font: style property is deprecated; please use CSS syntax

(ibus-ui-gtk3:2537): IBUS-WARNING **: panel.vala:558: Failed css_provider_from_data: Sans 10: <data>:1:14not a number

```
