### ISSUE TITLE
切换状态无法提交输入, 双击选中内容自动删除

### ISSUE THREAD

**Issue by Hacksign** [ibus/ibus#1880]
1. ibus-pinyin输入法状态切换时, 已经输入的内容丢失.

> 复现步骤:
> > a. 切换到ibus-pinyin输入法
> > b. 在记事本中水边输入一下内容, 但是先不要提交输入
> > c. 使用shift切换到英文模式
> 结果 : 之前输入的内容丢失, 并没有提交

2. firefox & ibus-pinyin激活的状态下, 输入框中选中的内容被删除

> 复现步骤:
> > a. 打开firefox, 随便打开一个网页, 例如http://www.google.com
> > b. 在google的搜索输入框中输入一些文字.
> > c. 鼠标双击选中刚才输入的文字.
> 结果: 选中的文字被删除(其他应用无此问题, ff版本49.0.1)

**Comment by fujiwarat** [comment]
@epico Could you help to describe the problem?

I don't understand the description.

**Comment by Hacksign** [comment]
@fujiwarat 

Well, sorry ..... lol, here is English description :+1: 

1. lost input content when switch input method with shift.

> How to reproduce :+1: 
> > a. switch to ibus-pinyin input method
> > b. input something with ibus-pinyin in text editor, just input, dont commit
> > c. switch ibus-pinyin into English input mode
> result : contents which is inputed in step b lost

2. firefox with ibus-pinyin active, double click any text(in input component such as input or textarea)  will cause selected text be deleted

> how to reproduce :+1: 
> > a. open google with firefox, actvie ibus-pinyin input method .
> > b. input something in google's search input box
> > c. double click text which is inputed in step b
> result : inputed text disappears (deleted)

all above problem is not exists with another input method ibus-sunpinyin .

**Comment by fujiwarat** [comment]
It seems you don't commit pre-edit text with space key before focus changes or double clicks.
I'm not sure if the feature is needed in pinyin but ibus-anthy has the options.

@Hacksign Could you copy the bug description to https://github.com/libpinyin/ibus-libpinyin/issues ?
This is not an issue for ibus core.

**Comment by Hacksign** [comment]
sure, I'm reporting this 'bug' to ibus-pinyin ~

**Comment by zbjdonald** [comment]
请问解决了嘛，我的也是这个问题。

**Comment by epico** [comment]
在 ibus-libpinyin 1.10.91 中，已经修正。

**Comment by Hacksign** [comment]
> 请问解决了嘛，我的也是这个问题。

换回fcitx了 TAT
