### ISSUE TITLE
<Alt>Shift_L hotkey: order of keypresses matters

### ISSUE THREAD

**Issue by WGH-** [ibus/ibus#1882]
If you set hotkey to `<Alt>Shift_L`, it will only work if you press Alt first. If Shift is pressed first, hotkey won't be triggered.

**Comment by fujiwarat** [comment]
Of course, yes. If you set Shift+Alt, set <Shift>Alt_L

**Comment by WGH-** [comment]
If I set hotkey to `Shift+Alt_L` (`gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Shift>Alt_L']"`), it doesn't work. No hotkey works in this case.

**Comment by fujiwarat** [comment]
Sorry, it's my mistake.
Please try ``'Shift<Meta_L>'``

**Comment by WGH-** [comment]
It didn't work, however, `'<Shift>Meta_L'` did. Thanks!

So the final recipe is
```
gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt>Shift_L', '<Shift>Meta_L']
```

**Comment by fujiwarat** [comment]
Yeah, it was my typo :(.
