### ISSUE TITLE
Ibus cannot switch between input methods

### ISSUE THREAD

**Issue by TheNetAdmin** [ibus/ibus#1883]
System: Ubuntu 16.04
Problem: Ibus cannot switch between input methods
e.g. I add two input methods `EN-US` and `ibus-rime`, the keyboard shortcut `ctrl+space` or `super+space` doesn't work, the input method stays at ibus-rime.  The `super+space` do change the icon at menu bar, but the input method doesn't change. This almost made me mad.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.

![ibus-rime](https://cloud.githubusercontent.com/assets/105929/20046624/0e619196-a4ef-11e6-8f26-cd19b24fa152.png)

**Comment by TheNetAdmin** [comment]
I've figured how to solve this problem. It turned out to be that unity-tweak-tool messed up some system settings, which resulted in the mess of ibus. Sorry to bother you, it's not ibut that should be blame.
