### ISSUE TITLE
Pinyin input not working well when toggling from French to Pinyin on Debian Linux

### ISSUE THREAD

**Issue by karengabrielyan** [ibus/ibus#1884]
Pinyin input not working when toggling from French (France) input to Pinyin on Debian Linux.

Feels like when user switches to French input through IBus, and then switches to Pinyin, the kayboard layout stays as if in French.

What happens then is that typing key combinations does make Chinese characters to show up in Ibus tootip-like suggestion box, but it's not possible selecting the actual characters because pressing the number signs on the keyboard has no effect.

For example, I switch to French, then immediately switch to Pinyin and type "nu".
I see this choise of symbols: **1. 奴  2. 怒 3. 努 4. 弩 5. 驽.**
Pressing 1, 2...5 in the letter-portion of keyboar has no effect.

Seems like French keyboard layout affect the Pinyin and pressing [1], [2], [3] etc... gets interpretes as pressing [&], [é], ["], ['], [(] on French keyboard.

Note that selecting numbers on numeric keypad works.

**Comment by fujiwarat** [comment]
It's an expected result. ibus-libpinyin follows the previous layout.
E.g. Previous layout is us, us(dvorak), users wish to use the previous layout in libpinyin too.
If you wish to specify the libpinyin layout, you can modify "``<layout>default</layout>``" in /usr/share/ibus/component/libpinyin.xml by manual.
