### ISSUE TITLE
Ctrl-shift-e (emoji key) conflicts with IntelliJ Java IDE shortcut

### ISSUE THREAD

**Issue by mariuszs** [ibus/ibus#1885]
How to disable or change this shortcut?

https://www.jetbrains.com/help/idea/2016.2/ctrl-shift.html

**Comment by fujiwarat** [comment]
It's planed but not implemented yet.
I guess that application can provide the customization since there are too many shortcuts.

**Comment by jkubrynski** [comment]
Changing shortcuts after 10 years of using is really bad idea. I'd prefer to change the emoji shortcut which I'm not using at all.

**Comment by jkubrynski** [comment]
@fujiwarat Any progress on this issue? I had to completely remove ibus due to this problem.

**Comment by fujiwarat** [comment]
@jkubrynski You can run ``env GTK_IM_MODULE=gtk-im-context-simple XMODIFIERS=@im=none intellij``
Probably that application does not need IME and the shortcut customization is targeted at next release but not soon.
Note: ibus and gtk has already been implemented Ctrl-Shift-u and added Ctrl-Shift-e recently. I don't receive any problems with Ctrl-Shift-u and implemented Ctrl-Shift-e.

**Comment by mike-fabian** [comment]
I think one does not really need the Ctrl-Shift-e shortcut for the emoji because the existing
shortcut Ctrl-Shift-u could be used for the emoji as well. Hexadecimal Unicode code points and 
names for emoji almost never conflict, so the same shortcut could be used to input both.

**Comment by mariuszs** [comment]
Hmm, good to know Ctrl-Shift-U is also broken for IntelliJ for long time :facepunch: 

Ctrl+Shift+U	Toggle Case	Toggle case of the selected text fragment.

Btw, why more fancy keys are not used like Win key? Generally system shortcuts (gnome/gtk) prefers Win combination and Ctrl-Shift-XXX is prefered for applications/users.

**Comment by mariuszs** [comment]
Proof that <kbd>Super</kbd> is better:

https://wiki.gnome.org/Design/OS/KeyboardShortcuts

> The primary system modifier key should be <Super> (Super/Windows/Command key).

and comments below this page.

**Comment by mariuszs** [comment]
Default hotkey for ibus is:

> Super + Space: Change input method.

So, adding <kbd>Super</kbd>-<kbd>U</kbd> and <kbd>Super</kbd>-<kbd>E</kbd> looks like good idea.

**Comment by fujiwarat** [comment]
@mike-fabian 
> Hexadecimal Unicode code points and names for emoji almost never conflict,

I don't think so. You can try "100".

**Comment by fujiwarat** [comment]
I think GTK shortcuts are different from GNOME ones because GTK ones does not use gsettings so I think one modifier <kbd>Super</kbd> will be conflict with desktop ones.
I think intellij has too many shortcut keys and this would a rare case but I still think which shortcut key is better.
Anyway I accept to provide the shortcut customization for emoji.

**Comment by mike-fabian** [comment]
@fujiwarat

mike-fabian>    Hexadecimal Unicode code points and names for emoji almost never conflict,

fujiwarat> I don't think so. You can try "100

That’s why I wrote “almost”. They conflict so little that it does not hurt
to always show both in a candidate list.

The number of matched Unicode code points can never be greater then 1 anyway.
And the number of emoji matched at the same time will always be very small.
Therefore, it is no problem to always display both in the same candidate list.

For example, in ibus-typing-booster it looks like this:

![emoji-and-unicode-codepoints-at-the-same-time-ibus-typing-booster](https://cloud.githubusercontent.com/assets/2330175/21091299/91981064-c045-11e6-9e13-ab1cd20dc383.png)

**Comment by fujiwarat** [comment]
> That’s why I wrote “almost”. They conflict so little that it does not hurt to always show both in a candidate list.

OK, it seems a considerable option.
If I think the option, probably the implementation steps are,

1. Move Ctrl-Shift-e in IBusEngineSimple to IBus panel and give the shortcut customization.
2. Import the feature of Ctrl-Shift-u to Ctrl-Shift-e.
3. Think the better shortcut key and if we can drop the Unicode typing in Ctrl-Shift-u.

**Comment by VitoVan** [comment]
So what's the current fix?

**Comment by fujiwarat** [comment]
> So what's the current fix?

No fix at the moment. Customize your application settings or run `env GTK_IM_MODULE=gtk-im-context-simple your_app`.

**Comment by fujiwarat** [comment]
ibus 1.5.15 now move the shortcut setting to ibus-setup and you can customize it.
I will think which shorcut is better in the near future since I need more information.

**Comment by AlynxZhou** [comment]
I think there is a bug here now, even you can change the shortcut in ibus-setup, the ctrl-shift-e still blocked in my system, I cannot simply remove this in the setup because even I removed it, I cannot use ctrl-shift-e in other program, it was caught by ibus, I am using 1.5.16.

**Comment by fujiwarat** [comment]
@AlynxZhou The shortcut key works for non-GNOME desktop.

**Comment by AlynxZhou** [comment]
@fujiwarat After recent upgrade the bug was fixed.
