### ISSUE TITLE
Can't enter long unicode characters

### ISSUE THREAD

**Issue by yurivict** [ibus/ibus#1887]
Pressing Ctrl-U doesn't allow to enter U+1F3FB, it stops after 4 hexadecimal chars and enters "Ἷ" which is wrong.

**Comment by fujiwarat** [comment]
Cannot reproduce your problem with the latest ibus and the shortcut is Ctrl-Shift-u.

**Comment by yurivict** [comment]
Ctrl-Shift-u doesn't work. It enters ```Ἷb``` for ```U+1F3FB```.

```
ibus-1.5.14_2                  Intelligent Input Bus for Linux / Unix OS
ibus-m17n-1.3.3_5              The m17n IMEngine for IBus framework
ibus-table-1.5.0_1             Table based input method framework for IBus
```
on FreeBSD 11.1, xfce4.

**Comment by fujiwarat** [comment]
> Ctrl-Shift-u doesn't work. It enters Ἷb for U+1F3FB.

Ctrl-Shift-u should work in ibus 1.5.14.
Did you use IBus XKB engines? The feature is available in XKB engines only but not ibus-m17n and ibus-table.
You can check the current input method with `ibus enigne` command.
```
% ibus enigne
xkb:us::eng
```

BTW, the unicode typing was consolidated to Ctrl-Shift-e in ibus 1.5.15

**Comment by yurivict** [comment]
It doesn't work.

```
$ ibus engine
xkb:us::eng
```

```
$ pkg info | grep ibus
ibus-1.5.14_2                  Intelligent Input Bus for Linux / Unix OS
ibus-m17n-1.3.3_5              The m17n IMEngine for IBus framework
ibus-table-1.5.0_1             Table based input method framework for IBus
libftdi-0.20_7                 Library (using libusb) to talk to FTDI chips
zh-ibus-pinyin-1.5.0_4         PinYin engine for IBus
```

Typing Ctrl+Shift+u and 1f3fb produces:
```
Ἷb
```

**Comment by fujiwarat** [comment]
Which application do you use? Did you try gedit?

The layout itself of xkb:us::eng works fine for you? If you type "1f3fb" without pressing Ctrl-Shift-u, "1f3fb" is shown?
Seems "1f3f" is converted to "Ἷ" and "b" is output in your environment.
