### ISSUE TITLE
Make a 1.5.15 release?

### ISSUE THREAD

**Issue by graywolf** [ibus/ibus#1892]
Hi,
looking at git history there are some fixes already from last relase, I'm particulary interested in https://github.com/ibus/ibus/commit/aacf5adbba9b9b34a1ec07005e670d209513fb5b . Are you planning on making mini relase of 1.5.15 with the bugfixes so distros can update and I can keep using distribution version instead of packaging my own?

**Comment by fujiwarat** [comment]
1.5.15 is not planed yet.
You can ask the downstream to apply that patch internally.

**Comment by graywolf** [comment]
will do, thanks :)
