### ISSUE TITLE
Changing a standard input method's tray icon

### ISSUE THREAD

**Issue by rookah** [ibus/ibus#1893]
I've been trying to change some input method's tray icons without success.
Changing the "ibus-keyboard" icon only modifies the input method's context menu icon, not the system tray one. Meanwhile, modifying the "ibus-anthy" icon changes both. I believe this is due to standard inputs having "special" language icons.

Is there a way to change the standard input tray icons without tweaking the standard table?

**Comment by fujiwarat** [comment]
I don't understand your description at all.
What did you change 'ibus-keyboard' to?
What is the input mthod's context menu icon? I think context menu does not have any icons.
How did you modify 'ibus-anthy' icon?

**Comment by rookah** [comment]
Sorry, I'll try to give a better explanation.
First, "input method's context menu icon" was extremely bad wording from my part. By this I actually meant the icon that shows next to the input methods in `(ibus-setup)Preferences>Input Method`.
Basically, I'm trying to overwrite the icons in order to change some input method's system tray icons. I'm doing this by putting files such as 'ibus-keyboard.png' somewhere in my icon theme folder. In the case of Anthy, overwriting 'ibus-anthy.svg' (i.e. the default anthy icon) changes both the input method AND the system tray icons. However, for input methods such as English (as well everything shipped with stock ibus) this method doesn't work as while the `(ibus-setup)Preferences>Input Method ` icon reflects the new change, the tray icon remains unchanged.

Hence the question: is there a "built-in" or standard way to change the standard input method's tray icons?

**Comment by fujiwarat** [comment]
Which desktop do you use?

>  I'm doing this by putting files such as 'ibus-keyboard.png' somewhere in my icon theme folder. 

Where did you put your icon? It seems you use a XDG user directory.

If you run `ibus engine` command, you can know the current IBus engine name.
'xkb:us::eng' engine uses a String icon "EN" but not "ibus-keyboard.svg"

**Comment by rookah** [comment]
I'm using [Awesome](https://github.com/awesomeWM/awesome), a WM which has a builtin system tray module.

>  Where did you put your icon? It seems you use a XDG user directory.

I'm using the icon theme as set up in `$XDG_CONFIG_HOME/gtk-3.0/settings.ini`.

> `xkb:us::eng` engine uses a String icon "EN" but not "ibus-keyboard.svg"

How would one go about changing this icon?

**Comment by fujiwarat** [comment]
> I'm using the icon theme as set up in $XDG_CONFIG_HOME/gtk-3.0/settings.ini

I asked your icon location but not settings.ini location.
But anyway,

> How would one go about changing this icon?

IBus panel uses the string icons for IBus XKB engines and we won't provide to change the way.
