### ISSUE TITLE
ibus-daemon does not honor use-system-keyboard-layout=true, probably race condition

### ISSUE THREAD

**Issue by AndersBlomdell** [ibus/ibus#1898]
When having multiple keyboards configured (swedish (default), english), ibus-daemon does not honor
the the following contents of etc/dconf/db/ibus.d/01-use-default-keyboard ('dconf update' has been run), for new users at first login, i.e. they get english layout when the system keyboard is swedish:

```
desktop/ibus/general]
use-system-keyboard-layout=true
```

moving `usr/bin/ibus-daemon` to `/usr/bin/ibus-daemon.orig` and creating a new `/usr/bin/ibus-daemon` with this content:
```
#!/bin/sh
$0.orig -d "$@"
sleep 30
$0.orig "$@" --replace
```

Makes the problem go away (i.e. switch to swedish layout) after the 30 second timer has elapsed, indicating that the problem is some kind of race condition.

**Comment by fujiwarat** [comment]
If you can resolve your problem with sleep, I don't think your problem is ibus.
Your problem is how the invoker runs ibus-daemon.
Fedora uses imsettings to invoke ibus-daemon and works correctly.
