### ISSUE TITLE
A lot of English

### ISSUE THREAD

**Issue by mxa** [ibus/ibus#1900]
I have English, German and Korean in IBUS.

![screenshot from 2017-02-27 12-31-25](https://cloud.githubusercontent.com/assets/1220707/23359876/ac46b548-fce8-11e6-9b25-0d97dd1057ae.png)

However, there is way more than one English in the menu:
![screenshot from 2017-02-26 16-21-34](https://cloud.githubusercontent.com/assets/1220707/23359858/9385f500-fce8-11e6-9144-9d6597e11bb3.png)

And on Ctl+Space too:
![screenshot from 2017-02-26 13-05-58](https://cloud.githubusercontent.com/assets/1220707/23359859/956d7d2a-fce8-11e6-8826-84a8aa1f9a8c.png)

What can I do?

**Comment by fujiwarat** [comment]
I think your problem was fixed some years ago and you use the old ibus.
I think `ibus read-config` command can backup your settings and  `ibus reset-config` would be a workaround.

**Comment by mxa** [comment]
`ibus reset-config` did the trick. Thank you.
