### ISSUE TITLE
Customising latin (English US, French, etc.) layouts

### ISSUE THREAD

**Issue by ewtoombs** [ibus/ibus#1903]
Ibus supports latin layouts, but "Preferences" is always greyed out. It would be really nice if I could do custom key remappings, like xmodmap is capable of. It could be configured from that "Preferences" button. One thing I like to do is remap the caps lock key to escape, since I use escape way more than I use caps lock.

**Comment by ewtoombs** [comment]
It doesn't need to be a GUI. Even just an option to run a custom script after a layout change would be enough for me to be able to do the rest with xmodmap.

**Comment by fujiwarat** [comment]
I don't understand what is "Preference". Please explain your problem using precious words.
ibus runs `setxkbmap` command internally so if you wish to customize caps lock key, probably you can think the options to run 'setxkbmap -option ...` when your desktop is launched but ibus-daemon is not launched yet.
I think eash desktop environment or X11 provides to set the options.
E.g. /etc/X11/xinit/xinitrc-common calls $HOME/.Xkbmap
ibus runs layout and variant only wit `setxkbmap -layout foo -variant foo` so won't change the desktop settings of options.
while ibus also loads xmodmap file but I don't recommend to use it since xmodmap has a problem with setxkbmap.

**Comment by ewtoombs** [comment]
To access the per-layout "Preferences" I am referring to, right click on the tray icon > Preferences > Input Method > Click on any latin layout, i.e. US English. To the right, "Preferences" is greyed out. That's the preferences I'm referring to, and that's where a GUI for custom key remappings or a script to be run after the layout is changed could be put.

As for setxkbmap, it cannot do custom key remappings. xmodmap is responsible for that. And all xmodmap modifications are overwritten after ibus starts up and changes layouts. I'd like this to remain open at least as a feature request.

**Comment by fujiwarat** [comment]
OK, I got what you indicate the grayed preference.
The XKB engine just runs setxkbmap so it does not any preference dialogs.
If you choose "Hide automatically" in "Show property panel" pull down menu in "General" tab on ibus-setup utility, you can see the preferences will be shown on the property panel.
IBus has the two kind of engines; XKB engines and input method engines; likes ibus-m17n, ibus-anthy.
I don't wish to show any preferences for XKB engines.

Bring back to your problem, you can modify `$HOME/.xmodmap` but some settings cannot work with setxkbmap so I recommend to use the way of `setxkbmap -option ...`.
Of course, you can run `xmodmap` command by manual without .xmodmap file.
If you wish to integrate the custom layout:
1. Add your custom layout to /usr/share/X11/xkb/symbols/ .
2. Confirm your custom layout works with setxkbmap command.
3. Modify /usr/share/ibus/component/simple.xml to add your custom layout
4. Restart ibus-daemon

**Comment by ewtoombs** [comment]
No, I can't use xmodmap, because its changes are overwritten every time ibus changes the layout. That's why the ability to run a custom script after changing layouts would be useful. I'd really rather use a custom script than messing around with anything in /usr.

**Comment by fujiwarat** [comment]
setxkbmap supports -I option to specify the user directory which guarantees by the user.
If you can creates the user rule, I can provide to set the -I option in ibus.
Otherwise probably I don't have a plan to support other formats in X11 XKB.

**Comment by ewtoombs** [comment]
Good idea, fujiwarat! Something like an `-I "$XDG_CONFIG_HOME/xkbmaps"` would work just fine. So the idea is I put a custom keymap in there and it appears by itself as an input method in ibus?

**Comment by ewtoombs** [comment]
Wait, why is /usr/share/ibus/component/simple.xml static? Shouldn't that be automatically generated by looking at all of the xkb maps currently installed on the system? fujiwarat, your solution doesn't do me any good if I still have to modify /usr/share/ibus/component/simple.xml as root to use my custom layout.

**Comment by fujiwarat** [comment]
IBus does not expect to load all XKB keymaps at present. We support sysadmin to modify simple.xml.

**Comment by fujiwarat** [comment]
If you mind the root permission, ibus-daemon can change the component directory with IBUS_COMPONENT_PATH variable.

**Comment by fujiwarat** [comment]
> So the idea is I put a custom keymap in there and it appears by itself as an input method in ibus?

Currently the -I option is not implemented by ibus but you can check the behavior with setxkbmap(1).
