### ISSUE TITLE
Rename "Preferences" to "IBus Preferences" in context menu

### ISSUE THREAD

**Issue by baimafeima** [ibus/ibus#1904]
I find it confusing to see two different preferences when having ibus-libpinyin installed. The regular IBus preferences are accessed by a right-click, the ibus-libpinyin preferences are accessed by clicking on the same icon but with a left-click. A clearer naming policy can significantly reduce confusion for new users and improve the OOTB experience.

**Comment by fujiwarat** [comment]
IBus provides the engine menus on left click and core menus on right click.
I'd suggest it's a report for ibus-libpinyin.
E.g. ibus-anthy provides the  preference menu together with "anthy" name.
CC'ing @epico

**Comment by fujiwarat** [comment]
I think "IBus Preferences" is not clear and I think appending engine name to engine preference is better.

**Comment by baimafeima** [comment]
What do you think? @epico I am not sure how it is solved in ibus-anthy.

**Comment by epico** [comment]
I think rename "Preferences" to "IBus Preferences" is easier.

Or I need to change both ibus-libpinyin and ibus-libzhuyin.

**Comment by fujiwarat** [comment]
I don't think "IBus Preference" clarify the preferences. The preferences of ibus-libpinyin is also one of the "IBus Preferences".

**Comment by epico** [comment]
Right, I see.

**Comment by baimafeima** [comment]
Why don't you call one _IBus Preferences_, the other one _Libpinyin Preferences_? I would avoid introducing words such as engine and whatnot and go by the most accessible and intuitive word which is the name of the project itself.

**Comment by fujiwarat** [comment]
"LibPinyin Preferences" would be enough and "IBus Preferences" make people confuse.
