### ISSUE TITLE
Replace Chinese default icon with a more modern one

### ISSUE THREAD

**Issue by baimafeima** [ibus/ibus#1905]
I have previously raised this issue at ibus-libpinyin here: https://github.com/libpinyin/ibus-libpinyin/issues/67

The icon currently in use doesn't match the aesthetic requirements of a modern operating system. Steps how to reproduce:

Install ibus-libpinyin. Activate pinyin. It shows the character 拼 (pin) in a relatively ugly default rendering. We should replace this by a more beautiful Chinese font and a color which blends in better with other language engines available. Could you add a setting for a user to decide whether to display an icon or simply CN for Chinese and to replace the default icon with a more modern version?

**Comment by fujiwarat** [comment]
Which locale do you use on your desktop?
Can you attach the screenshot of your desktop?
I don't know how ugly rendering on your desktop.
Each desktop provides an application to take the screenshot.

**Comment by baimafeima** [comment]
![pin](https://cloud.githubusercontent.com/assets/23112309/24149292/f5bac692-0e7c-11e7-93ee-68d51a75d274.png)

**Comment by baimafeima** [comment]
The icon looks the same on any Linux-based operating system. My point is that it doesn't look good (too big, the color doesn't match the slightly darker blue text that you find when you have, for instance, EN locale enabled, and a more modern Chinese font could be chosen).

**Comment by fujiwarat** [comment]
Actually the " 拼 " icon is an image icon but "EN" is drawn as a string dynamically.
I don't think it's too big.
If you think it, you should attach a mock prototype to convince us.
Probably I think ibus-libpinyin can provide some image files which have a kind of colors.
Basically IBus icon is considered as image files because image provides much information than a string.
So I think The one char "拼 " itself does not give which Chinese engine is expressed.
CC'ing @epico

**Comment by epico** [comment]
For Solus project, maybe you could replace this icon when build ibus-libpinyin.

The icon is in /usr/share/ibus-libpinyin/icons/ibus-pinyin.svg .

**Comment by baimafeima** [comment]
The best is still a solution to be implemented upstream but regarding Solus icons, I think it is best to synchronize this effort with @snwh

**Comment by fujiwarat** [comment]
If you'd change the upstream icon, you should attach the improved svg file to explain the problem more clearly.

**Comment by fujiwarat** [comment]
Any contributions are welcome.
