### ISSUE TITLE
"ibus-x11 --kill-daemon" dies without killing ibus-daemon when I log out a desktop environment.

### ISSUE THREAD

**Issue by crocket** [ibus/ibus#1907]
When I log in GNOME, `ibus-daemon --xim --panel disable` is launched by GNOME.
`ibus-x11 --kill-daemon` is launched by ibus-daemon.

If I kill ibus-x11 by `pkill ibus-x11`, ibus-x11 kills ibus-daemon.
When I log out GNOME, only ibus-x11 dies while other ibus processes keep running.

If I log in GNOME for the second time, GNOME doesn't launch a new instance of ibus-daemon. Thus, ibus-x11 is missing after the second login.

After the second login, I executed

```
/usr/lib/ibus/ibus-x11 --kill-daemon --debug=3 > ibus-x11.log 2>&1 &
```

And, I logged out. The content of `ibus-x11.log` is

```
Gdk-Message: ibus-x11: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```

Without ibus-x11, I cannot type japanese characters in https://apps.ankiweb.net/
Anki is a QT application.

* ibus 1.5.14
* GNOME 3.22
* ArchLinux

## Workaround

If I put `ibus-daemon -xdr --panel disable` into `~/.xprofile`, I can work around the issue.

**Comment by crocket** [comment]
I executed

```
/usr/lib/ibus/ibus-daemon --kill-daemon --debug=3 > ibus-x11.log 2>&1 &
```

The content of `ibus-x11.log` is

```
Gdk-Message: ibus-x11: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```

**Comment by fujiwarat** [comment]
I think the problem is who runs ibus-daemon.
I don't see your problem on Fedora because Fedora uses imsettings to launch ibus-daemon.
After log out, `ps` command shows ibus-daemon besides ibus-x11 but imsettings die.
I think the Fedora state is also not good but I don't see your problem at least.
If you run `ibus exit` command, you will see ibus exits safely and it means any parent program can terminate ibus safely.

**Comment by crocket** [comment]
Can the issue be solved in ibus?
Solving the issue once in ibus could potentially solve the issue in all desktop environments.

**Comment by fujiwarat** [comment]
But I cannot reproduce your problem.

**Comment by crocket** [comment]
I reproduced this issue on GNOME and cinnamon in ArchLinux.
I surmise your ibus-daemon is executed with `-r` flag.
Am I wrong?

**Comment by fujiwarat** [comment]
Attached the patch. It would be great if you can build the patch.
[ibus-1907-logout-process.txt](https://github.com/ibus/ibus/files/838062/ibus-1907-logout-process.txt)

OK, now I can reproduce your problem in Fedora GNOME.
The `-r` option is not expected in gnome-shell. GNOME has a possibility to run one ibus-daemon by gnome-shell and another by another tools so we added `-r` option to override the another ibus-daemon historically but we don't expect to use `-r` for the second login so GNOME is better not to have `-r` option.
