### ISSUE TITLE
Compile fails - fatal error no such file ibusemojidialog.h

### ISSUE THREAD

**Issue by shevegen** [ibus/ibus#1909]
Hello.

Not sure if this is worth reporting since it seems trivial but
I report it anyway, perhaps the configure step could first
check for that .h file before failing at a later stage.

---

Making install in engine
make[1]: Entering directory '/Depot/Temp/ibus-1.5.15/engine'
make[2]: Entering directory '/Depot/Temp/ibus-1.5.15/engine'
 /System/Executables//mkdir -p '/Programs/Ibus/1.5.15/libexec'
  /bin/sh ../libtool   --mode=install /System/Executables//ginstall -c ibus-engine-simple '/Programs/Ibus/1.5.15/libexec'
libtool: install: /System/Executables//ginstall -c .libs/ibus-engine-simple /Programs/Ibus/1.5.15/libexec/ibus-engine-simple
 /System/Executables//mkdir -p '/Programs/Ibus/1.5.15/share/ibus/component'
 /System/Executables//ginstall -c -m 644 simple.xml '/Programs/Ibus/1.5.15/share/ibus/component'
make[2]: Leaving directory '/Depot/Temp/ibus-1.5.15/engine'
make[1]: Leaving directory '/Depot/Temp/ibus-1.5.15/engine'
Making install in ui
make[1]: Entering directory '/Depot/Temp/ibus-1.5.15/ui'
Making install in gtk3
make[2]: Entering directory '/Depot/Temp/ibus-1.5.15/ui/gtk3'
make[3]: Entering directory '/Depot/Temp/ibus-1.5.15/ui/gtk3'
 /System/Executables//mkdir -p '/Programs/Ibus/1.5.15/libexec'
  /bin/sh ../../libtool   --mode=install /System/Executables//ginstall -c ibus-ui-gtk3 '/Programs/Ibus/1.5.15/libexec'
libtool: install: /System/Executables//ginstall -c .libs/ibus-ui-gtk3 /Programs/Ibus/1.5.15/libexec/ibus-ui-gtk3
 /System/Executables//mkdir -p '/Programs/Ibus/1.5.15/share/ibus/component'
 /System/Executables//ginstall -c -m 644 gtkpanel.xml '/Programs/Ibus/1.5.15/share/ibus/component'
make[3]: Leaving directory '/Depot/Temp/ibus-1.5.15/ui/gtk3'
make[2]: Leaving directory '/Depot/Temp/ibus-1.5.15/ui/gtk3'
make[2]: Entering directory '/Depot/Temp/ibus-1.5.15/ui'
make[3]: Entering directory '/Depot/Temp/ibus-1.5.15/ui'
make[3]: Nothing to be done for 'install-exec-am'.
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/Depot/Temp/ibus-1.5.15/ui'
make[2]: Leaving directory '/Depot/Temp/ibus-1.5.15/ui'
make[1]: Leaving directory '/Depot/Temp/ibus-1.5.15/ui'
Making install in tools
make[1]: Entering directory '/Depot/Temp/ibus-1.5.15/tools'
  CC       main.o
main.c:36:29: fatal error: ibusemojidialog.h: No such file or directory
 #include <ibusemojidialog.h>
                             ^
compilation terminated.
make[1]: *** [Makefile:661: main.o] Error 1
make[1]: Leaving directory '/Depot/Temp/ibus-1.5.15/tools'
make: *** [Makefile:682: install-recursive] Error 1

---

My system:

========================================================================
  Operating System:                GNU/Linux                                           
  Os Bit Type:                     i686                                                
  CPU Model:                       Intel(R) Celeron(R) CPU G1630 @ 2.80GHz cores       
  CFLAGS in use:                   -O2 -fPIC -fno-strict-overflow -Wno-error           
  RAM:                             3319772 kB RAM (3242.0 MB) (3.2 Gig)                
  Gcc Version:                     6.3.0                                               
  Glibc Version:                   2.15                                                
  Kernel Version:                  3.2.29                                           

========================================================================

Ibus was the latest, 1.5.15 tarball release from URL

https://github.com/ibus/ibus/releases/download/1.5.15/ibus-1.5.15.tar.gz

**Comment by fujiwarat** [comment]
In case you run `./configure --disable-emoji-dict`, you need to create tools/main.c from tools/main.vala again.
You can run `make -C tools maintainer-clean-generic` by manual to delete tools/main.c .
The tarball includes main.c for who don't hava valac build environment.
I have no idea to resolve this issue without the manual operation.

**Comment by fujiwarat** [comment]
BTW why don't you run `./configure --enable-emoji-dict` ?
You can get `emoji.json` with `npm install -g emojione` or Fedora provides `nodejs-emojione-json` package.
You can get emoji annotation files from https://github.com/fujiwarat/cldr-emoji-annotation or Fedora provides `cldr-emoji-annotation` package.

**Comment by dankasak** [comment]
Yikes! I just hit this error on Gentoo. I don't run 'npm' as root. I see:
 ibus-1.5.15/ui/gtk3/ibusemojidialog.h
  ... under my build directory.

Seems like a legit but to me ...

**Comment by fujiwarat** [comment]
> Yikes! I just hit this error on Gentoo. I 
Why did you comment it.
Try `make -C tools maintainer-clean-generic` as I noted above.

**Comment by abucodonosor** [comment]
Well maintainer-clean-generic does not work .. but with vala installed
rm tools/main.c before running ./configure && make seems to fix that

**Comment by fujiwarat** [comment]
> Well maintainer-clean-generic does not work
Why do you think so? You can check maintainer-clean-generic in ibus/tools/Makefile, which deletes tools/main.c

**Comment by dankasak** [comment]
Doesn't work for me either. I interrupted the build and tried:

sabayon-latitude ibus-1.5.15 # make -C tools maintainer-clean-generic
make: Entering directory '/var/tmp/portage/app-i18n/ibus-1.5.15/work/ibus-1.5.15/tools'
make: *** No rule to make target 'maintainer-clean-generic'.  Stop.
make: Leaving directory '/var/tmp/portage/app-i18n/ibus-1.5.15/work/ibus-1.5.15/tools'
sabayon-latitude ibus-1.5.15 #

**Comment by fujiwarat** [comment]
```
# grep maintainer-clean-generic tools/Makefile
maintainer-clean-generic:
maintainer-clean-am: distclean-am maintainer-clean-generic
	maintainer-clean-generic mostlyclean mostlyclean-compile \
```

Probably your automake version is low but I think you should succeed if you don't run automake.

**Comment by maffblaster** [comment]
Build failure for `fatal error no such file ibusemojidialog.h` happens for me too!

**Comment by fujiwarat** [comment]
> Build failure for fatal error no such file ibusemojidialog.h happens for me too!

Because you didn't run `make -C tools maintainer-clean-generic`

**Comment by fujiwarat** [comment]
BTW why don't you run `./configure --enable-emoji-dict` ?

**Comment by fujiwarat** [comment]
The build error is now improved a little in git master.
