### ISSUE TITLE
Clicking blue cog wheel does nothing

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#1910]
The small rectangle in the upper right corner has a blue cog wheel on its
right half.

Clicking it does nothing.

**Comment by fujiwarat** [comment]
I don't understand what is the blue cog wheel.
Please attach your screenshot.

**Comment by jidanni** [comment]
![c](https://cloud.githubusercontent.com/assets/1230959/23868919/3b05ea50-085c-11e7-837e-f5d9cf6f09f5.jpg)

**Comment by fujiwarat** [comment]
Seems you use ibus-chewing. You can check the current ibus engine name with `ibus engine` command.
I don't know if that problem existed previously but I think it's no longer reproduced in ibus 1.5.14.
The button toggles half and full width of chewing characters and works fine with me.
The workaround is to click the ibus panel icon and shows the ibus menu which provides the same functions in case you use the old ibus.
