### ISSUE TITLE
IBus Property panel does not remember the window position after exit

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#1911]
With my mouse I move the small rectangle from the upper right corner to a place more noticeable.

The next day upon powering up it is back in the upper right corner.

**Comment by fujiwarat** [comment]
What is the small rectangle.
Please attach your screenshot.

**Comment by jidanni** [comment]
![c](https://cloud.githubusercontent.com/assets/1230959/23868948/4dae2316-085c-11e7-88d0-19b55690f807.jpg)

**Comment by fujiwarat** [comment]
Right. Restarting ibus-daemon, the Property Panel is located at the default position.
I don't think there are much requests for the default position from users.
BTW, you can disable to show the Property Panel with `ibus-setup` utility.

**Comment by jidanni** [comment]
It is very hard to tell what mode I am in except by looking around at
obscure parts of the screen.

I wish I could make a big red etc. blob in the middle of my screen that
would remind me I am in Chinese more.

And no blob would mean I am not in Chinese mode.

The more you help users to do something like this, the better.

**Comment by fujiwarat** [comment]
> I wish I could make a big red etc. blob in the middle of my screen that would remind me I am in Chinese more.

I don't understand what is the big red and blob.
We don't expect the location of the Property Panel tells what engine is used but expect the icons on the Property Panel tells that.
E.g. ibus-chewing shows "中" to indicate Chinese.
I agree the blue cog wheel is not clear to indicate which wide or narrow mode but it's a ibus-chewing bug not ibus core.

Seems your desktop does not provide a notification area.
E.g. XFCE4 desktop provides it:
![ibus-chewing-mode](https://cloud.githubusercontent.com/assets/105929/23885504/de3f1656-08b6-11e7-9e80-de3aa783d5ef.png)

**Comment by fujiwarat** [comment]
FYI @definite

**Comment by fujiwarat** [comment]
Currently I have no plan to do this but will consider again if other users request it.

**Comment by fujiwarat** [comment]
@jidanni Did you confirm notification area in my screenshot?
If your desktop does not have it, you can install [tint2](https://gitlab.com/o9000/tint2).

**Comment by jidanni** [comment]
Yes icewm provides icons in the lower left corner. Plus there is the cog wheel in the upper right corner. I just hope it will stay put where I put it between sessions.

**Comment by fujiwarat** [comment]
OK, can you attach the screenshot of whole the desktop?
Currently the IBus property panel is located at right down in KDE or LXDE and right top in other desktops.
I can put IBus property panel at right down in your desktop if you give the value of $XDG_CURRENT_DESKTOP on the ice desktop.
https://github.com/ibus/ibus/blob/master/ui/gtk3/propertypanel.vala#L317

**Comment by fujiwarat** [comment]
> OK, can you attach the screenshot of whole the desktop?

Any updates?

**Comment by jidanni** [comment]
OK well I see many different behaviours on each different computer so it is all so confusing so I'll close this for now.
