### ISSUE TITLE
 Delete behavior seems incorrect on Qt in Fedora 25

### ISSUE THREAD

**Issue by soiamsoNG** [ibus/ibus#1913]
Already report on libpinyin/ibus-libpinyin#78

I repeat here:

In program of Qt based. like Calibre ( I screen cast on) and Qt Creator

    1. when we still left suggestion on suggestion window

    2. I start to delete all characters use Backspace in the suggestion window, Qt widget will still have the most first character(with underline), even after delete them all from the pinyin suggestions window.

    3. If input new character(English or Chinese) immediately the still left character will disappear.

![bug](https://cloud.githubusercontent.com/assets/11811568/24177174/9192e654-0edb-11e7-94ad-bc82c6cc3048.gif)

**Comment by epico** [comment]
ibus-libpinyin used ibus_engine_hide_preedit_text.

But I can't find this function supported in qt5.
URL: https://github.com/qt/qtbase/blob/dev/src/plugins/platforminputcontexts/ibus/qibusplatforminputcontext.cpp

**Comment by fujiwarat** [comment]
Not committed yet.
https://codereview.qt-project.org/#/c/177665/

**Comment by epico** [comment]
Thanks! :)
