### ISSUE TITLE
Anthy's candidate_page_up/down keys (and mouse input) do nothing.

### ISSUE THREAD

**Issue by NoSuck** [ibus/ibus#1914]
I am fortunate to be able to use such a handy piece of software.  Thank you.

Neither Page_Up nor Page_Down demonstrate any effect on my system when the ibus-anthy candidate list is open.  Is this an IBus issue?  Please see the animation below.

IBus 1.5.14
Linux 4.10.3-1-ARCH #1 SMP PREEMPT Wed Mar 15 09:17:17 CET 2017 x86_64 GNU/Linux

![Both clicking and key presses fail.](https://nosuckdotorg.files.wordpress.com/2017/03/ibus-anthy-candidates_page_-failure.gif)

**Comment by fujiwarat** [comment]
Thank you for filing the bug.
It was a regression. I moved this issue to https://github.com/ibus/ibus-anthy/issues/6
