### ISSUE TITLE
How to implement configure panel to ime?

### ISSUE THREAD

**Issue by lv7777** [ibus/ibus#1915]
I read ibus 1.5 api reference, but I can't know. 
also I read ibus-tmpl, but the ime is not implement configure panel.
please teach how to implement ibus configure panel( this is not to prop_list panel).

![uac-jogt](https://cloud.githubusercontent.com/assets/8572307/24276886/c2126638-1007-11e7-94f9-e00ab2b33c5f.jpg)

**Comment by fujiwarat** [comment]
I think ibus-tmpl works fine but I don't know what you mean in configure panel.
Need more explanation.

**Comment by lv7777** [comment]
configure panel is bottom of set of buttons(設定 button) on above image.

> I think ibus-tmpl works fine,

surely ibus-tmpl is works fine, but ibus-tmpl is not implement configure panel(configure window)
e.g. ibus-mozc have original config panel about "convert table","change convert key".

![02](https://cloud.githubusercontent.com/assets/8572307/24286313/a5aaa9a2-1042-11e7-9c75-4ea0128333d8.png)

**Comment by fujiwarat** [comment]
> configure panel is bottom of set of buttons(設定 button) on above image.

OK, The button is "Preferences" button.
Next time you should run `env LANG=C ibus-setup` before submit an issue.
Also if I explain your problem exactly - all IMEs do not implement the "Preferences" button but ibus-tmpl disables the button or make the button insensitive.

If you need to enable "Preferences" button on ibus-setup, you need to prepare /usr/lib*/ibus-setup-$name . $name is retrieved from the engine's `name` tag in /usr/share/ibus/component/foo.xml .

**Comment by lv7777** [comment]
I can implement "preference" panel.
thanks!!
