### ISSUE TITLE
ibus centos7 compile fail

### ISSUE THREAD

**Issue by chinaluopiao** [ibus/ibus#1916]
My computer is centos7, in the compilation of the emergence of this error, which kind of people to help solve. Thanks

`Making all in engine
make[2]: 进入目录“/home/luopiao/workspace/github/ibus/engine”
  VALAC    ibus_engine_simple_vala.stamp
main.vala:50.13-50.24: warning: `null' incompatible with return type `IBus.Engine`
            return null;
            ^^^^^^^^^^^^
main.vala:80.21-80.43: error: The name `add_compose_file' does not exist in the context of `IBus.EngineSimple?'
                    simple.add_compose_file(user_file);
                    ^^^^^^^^^^^^^^^^^^^^^^^
main.vala:86.21-86.43: error: The name `add_compose_file' does not exist in the context of `IBus.EngineSimple?'
                    simple.add_compose_file(user_file);
                    ^^^^^^^^^^^^^^^^^^^^^^^
Compilation failed: 2 error(s), 1 warning(s)
make[2]: *** [ibus_engine_simple_vala.stamp] 错误 1
`

**Comment by fujiwarat** [comment]
`IBus.EngineSimple.add_compose_file()` is defined in `ibus-1.5.15/bindings/vala/ibus-1.0.vapi`.
Where did you get the tarball?
https://github.com/ibus/ibus/releases/tag/1.5.15 should provide the right file.
Also `make AM_DEFAULT_VERBOSITY=1` provides the verbose errors.
