### ISSUE TITLE
L10N - can you please explain two sentences?

### ISSUE THREAD

**Issue by Jibec** [ibus/ibus#1920]
Hi,

we get these two strings in Zanata:
* FONT for emoji chracters on emoji dialog.
* LANG for annotations on emoji dialog. E.g. "en"

They should be in #160; Refs: ../tools/main.vala:349 but we can't find them.

Can you please check we have the latests string to translate available in Zanata and tell us if we have to translate FONT & LANG? Does it refer to translatable content or parameters to some command?

thanks for your help

**Comment by fujiwarat** [comment]
Actually those strings are now moved to https://github.com/ibus/ibus/blob/master/ui/gtk3/emojierapp.vala#L74
So I didn't get a move on updating the pot file for a while.

Currently I gave "translated FONT (FONT) for emoji chracters on emoji dialog." in ja.po but thinking your issue again, probably the "FONT" also should be translated besides "FONT for emoji chracters on emoji dialog.". 
I will create another patch.

**Comment by fujiwarat** [comment]
https://codereview.appspot.com/322880043

**Comment by Jibec** [comment]
thanks a lot!

**Comment by fujiwarat** [comment]
Now I uploaded the latest POT file in Zanata.
