### ISSUE TITLE
API/ABI changes review for IBus

### ISSUE THREAD

**Issue by lvc** [ibus/ibus#1921]
The review of API/ABI changes for IBus since 1.5.0 version: https://abi-laboratory.pro/tracker/timeline/ibus/

Created with the help of open-source abi-tracker tool: https://github.com/lvc/abi-tracker. Hope it will be helpful for users and maintainers of the library.

![ibus-1](https://cloud.githubusercontent.com/assets/1517837/25384621/11997abe-29d2-11e7-8351-a2586253fd11.png)
![ibus-2](https://cloud.githubusercontent.com/assets/1517837/25384814/bf307650-29d2-11e7-901e-6c6eaeaebf17.png)

## Environment
* Linux x86_64
* GCC 4.9
* IBus 1.5.0 and higher

**Comment by fujiwarat** [comment]
Thank you for your info.
It's very useful for me.
