### ISSUE TITLE
Inserting Unicode characters by name

### ISSUE THREAD

**Issue by mark-otaris** [ibus/ibus#1922]
The feature in IBus 1.5.15 for inserting emojis and Unicode characters by hexadecimal code point with Ctrl+Shift+e is useful, but since I rarely know the code point of the character I want to insert, I would like a way to search for characters by their Unicode name as well. So I suggest this feature.

I understand that this was not done with Ctrl+Shift+e because the names would conflict with emoji names, which rarely happens with code points. So this would need to be a different customizable keyboard shortcut, unless having only one keyboard shortcut instead of two is worth having more name conflicts.

I also understand that this can be done indirectly [with Typing Booster](https://mike-fabian.github.io/ibus-typing-booster/documentation.html#unicode-symbols) and [UniEmoji](/salty-horse/ibus-uniemoji), but changing the input method is much less convenient than pressing Ctrl+Shift+u.

**Comment by fujiwarat** [comment]
> I understand that this was not done with Ctrl+Shift+e because the names would conflict with emoji names,

Did you understand the dialog mainly supports to type the emoji annotations?
https://desktopi18n.wordpress.com/2017/03/15/ibus-1-5-15-is-released/

**Comment by mark-otaris** [comment]
Yes.

**Comment by fujiwarat** [comment]
Are you requesting to type Unicode annotations besides emoji annotations?

**Comment by mark-otaris** [comment]
Sort of, but instead of annotations the matching would be done with the Unicode [character names](http://unicode.org/charts/charindex.html).

For some example use cases, say I am writing a novel or an article and I want to insert an asterism to separate two sections, ⁂, U+2042 ASTERISM. I would not remember the code point 2042, but I could search for 'asterism'. If I was creating a table and wanted to insert ✓, U+2713 CHECK MARK, I could similarly search for 'check' without remembering that the code point is 2713. Same for mathematical symbols (e.g., ÷, U+00F7, DIVISION SIGN), currency symbols (e.g., ¥, U+00A5 YEN SIGN), and other characters that cannot be created conveniently with the compose key.

**Comment by fujiwarat** [comment]
OK, I understand your request but I think the Unicode name is too long.
Currently the IBus Emojier hits with the exact match only.
E.g. U+00C1 is "A WITH ACUTE, LATIN CAPITAL LETTER".
I'm thinking to change the name to annotations.
Probably I can split the name by word and exclude "with", ",", "letter" and put into the annotations.
