### ISSUE TITLE
switching users requires restarting ibus to get user-specified layout

### ISSUE THREAD

**Issue by hugobuddel** [ibus/ibus#1923]
Setup: Ubuntu 16.04.2 with MATE and lightdm, IBus 1.5.11, 2 users using different layouts.

Desired behavior: The keyboard is set to the layout that the user has specified upon switching to that user.

Actual behavior: The keyboard gets reset to the system layout when switching users. IBus has to be restarted to get the proper layout.

**Comment by fujiwarat** [comment]
Can you explain more?
Which application did you try?
Which ibus engines did you switch?

**Comment by fujiwarat** [comment]
I think it's caused by your settings failure.

**Comment by hugobuddel** [comment]
What I did was simply:

Setup:
1. Install Ubuntu 16.04
2. Install mate-session
3. Create two users (perhaps I did step 2 and 3 in the inverse order)
4. Set different keyboard layouts for the users (us international and dvorak)


Usage:
1. Login to user 1
2. Switch to user 2
3. Observe that the keyboard is not set properly
4. Restart IBus
5. Observe that the keyboard is now set correctly

W.r.t. to your other questions: The keyboard was incorrect in all applications. I had it setup to use the same layout in all applications. I don't know what an IBus engine is, I don't think I switched them.

This is my first experience with IBus, using a freshly installed machine. IBus was enabled by default, replacing the old keyboard switcher thing. There shouldn't be weird settings or anything; I did experiment with the settings, but couldn't get it to work.

I have a workaround, so this bug report is mainly to inform you that there seems to be a problem with IBus on a fresh Ubuntu 16.04 installation with MATE. It's up to you what you do with it. Maybe the problem is with Ubuntu or MATE, but still I thought you'd like to know about it. If you want I can help investigate.

**Comment by fujiwarat** [comment]
> The keyboard was incorrect in all applications. 

What is all? Did you try gedit?

> , I don't think I switched them.

So which keymaps did you select with ibus-setup?

> I have a workaround, so this bug report is mainly to inform you that there seems to be a problem with IBus on a fresh Ubuntu 16.04 installation with MATE.

Currently I don't think it's a bug but it would be a setting error in your box.
Since you does not give to reproduce the exact problem yet, I have nothing to do on it.
I cannot reproduce your problem with mate 1.16 .
```
# rpm -q mate-session-manager
mate-session-manager-1.16.1-1.fc25.x86_64
```

**Comment by hugobuddel** [comment]
Here are some very specific instructions. I've just tested them on a fresh virtual machine (VirtualBox).

1. Install Ubuntu 16.04.2 (allow it to update while installing, and to install 3th party packages)
2. Set the user to login automatically (not sure whether this matters)
3. Install ubuntu-mate-desktop
4. Logout from unity and login with MATE
5. Create user2 (allow login without password, not sure this matters)
6. Login as user2
7. Add another keyboard layout (e.g. Dvorak)
8. The layout doesn't work, change settings to uncheck 'Use system keyboard layout' and restart IBus, layout does work.
9. Switch to the first user again, and back to the second user. (Not logging out, but switching users.)
10. The layout doesn't work, restart IBus, layout does work.
11. go to 9. etc.

Tried with gedit, firefox, terminal. The problem seems to disappear when logging out instead of switching users. I can make a video if you want, or provide you with a copy of the virtual machine if that would help you. 

This is an LTS release of Ubuntu, so I thought it might be important to you that your software works properly there.

    $ apt-cache show mate-session-manager
    ...
    Version: 1.12.2-1

**Comment by fujiwarat** [comment]
> 8. The layout doesn't work, change settings to uncheck 'Use system keyboard layout' and restart IBus, layout does work.

That should not be default.
Can you check the system default value of "use-system-keyboard-layout" in /usr/share/glib-2.0/schemas/org.freedesktop.ibus.gschema.xml ?

Can you also check the session default value to create the third user?
1. Create user3.
2. Log out from user2 session and log in user3 session.
3. Run `gsettings get org.freedesktop.ibus.general use-system-keyboard-layout` .

**Comment by hugobuddel** [comment]
The results of some investigation.

The default of use-system-keyboard-layout is set to false:
<pre>
$ less /usr/share/glib-2.0/schemas/org.freedesktop.ibus.gschema.xml
...
&lt;key type="b" name="use-system-keyboard-layout"&gt;&lt;default&gt;false&lt;/default&gt;...
</pre>

But the actual value for a new user is set to true:
<pre>
user4$ gsettings get org.freedesktop.ibus.general use-system-keyboard-layout
true
</pre>

Apparently this is because the default is overruled:
<pre>
$ grep "use-system-keyboard-layout" $(find /usr/share/glib-2.0 -type f)
...
/usr/share/glib-2.0/schemas/10_ibus.gschema.override:use-system-keyboard-layout=true

$ cat /usr/share/glib-2.0/schemas/10_ibus.gschema.override
[org.freedesktop.ibus.general]
use-system-keyboard-layout=true
</pre>

This file is provided by the ibus package, probably modified by Ubuntu:
<pre>
$ dpkg -S 10_ibus.gschema.override
ibus: /usr/share/glib-2.0/schemas/10_ibus.gschema.override

$ apt show ibus # removed some output
Package: ibus
Version: 1.5.11-1ubuntu2
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: IME Packaging Team <pkg-ime-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1360 kB
Homepage: https://github.com/ibus/ibus/releases
Supported: 5y
</pre>

Perhaps I should have filed the bug on the Ubuntu launchpad; I did not know that the package info contains a 'Bugs' section. Shall I still file a bug there as well? Nevertheless, it might still be important for you as well, to know that there is a problem with IBus in Ubuntu because it is such a major distribution. (I have not tried newer Ubuntu's, only 16.04.2 because it is an LTS that works with my video card.)

Just an hypothesis: perhaps the Ubuntu team wants to be able to use their own keyboard selector in combination with the other input functionality that IBus provides, but somehow didn't properly integrate that with MATE? Not sure whether that makes sense though.

**Comment by fujiwarat** [comment]
I apologize not to think the distribution modify the value.
I'm really surprised by that change.

Probably Ubuntu Unity succeeded to integrate IBus and Unity switches IBus engines but switches keymaps with its owned implementation.
And when you switch the desktops, the problem happens because normal desktops just use IBus.

It's a Ubuntu bug but probably I think IBus needs to provide an option to disable to setting keymaps.
E.g. `ibus-daemon --disable-keymap` for Unity.
