### ISSUE TITLE
Dvorak international is missing

### ISSUE THREAD

**Issue by hugobuddel** [ibus/ibus#1924]
The "Dvorak international with dead keys" layout is missing.

That is, the layout where typing "e leads to ë (a common letter in Dutch), but with the keys in the Dvorak location.

Dvorak international is the default keyboard layout on my system, so I can get the desired layout by user switching due to #1923 .

**Comment by fujiwarat** [comment]
You can insert the following lines in /usr/share/ibus/component/simple.xml and run `ibus restart` command:
```
                <engine>
                        <name>xkb:us:dvorak-intl:eng</name>
                        <language>en</language>
                        <license>GPL</license>
                        <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
                        <layout>us</layout>
                        <layout_variant>dvorak-intl</layout_variant>
                        <longname>English (Dvorak, international with dead keys)</longname>
                        <description>English (Dvorak, international with dead keys)</description>
                        <icon>ibus-keyboard</icon>
                        <rank>1</rank>
                </engine>
```

**Comment by hugobuddel** [comment]
OK thank you, I will try it out and let you know. Would it be appropriate to create a pull request to add it to [engine/simple.xml.in](engine/simple.xml.in)?

**Comment by fujiwarat** [comment]
If dvorak-intl should be default, we can accept the patch.
Modifying simple.xml by sysadmin is supported by ibus.

**Comment by fujiwarat** [comment]
I think you verified the change.
