### ISSUE TITLE
Export the fact that the language input needs a bigger font

### ISSUE THREAD

**Issue by hadess** [ibus/ibus#1928]
For some languages, it's important for the font showing up in the completion popup to be bigger than the currently configured system font, to avoid selecting the wrong character.

Exporting this information would allow front-ends to automatically make the popup bigger, without special-casing in the front-end, or a work-around configuration option.

See https://bugzilla.gnome.org/show_bug.cgi?id=708890

**Comment by fujiwarat** [comment]
What do you mean to export the information?
IBus provides the font-size in key `custom-font` in schema `org.freedesktop.ibus.panel`

```
% gsettings get org.freedesktop.ibus.panel custom-font
'Sans 10'
% gsettings get org.freedesktop.ibus.panel use-custom-font
false
```
`ibus-setup` can change the values and IBus Gtk panel use those settings.

I think gnome-shell ibus panel uses clutter and the original bug cannot change the font.
If you mean to export the font settings in ibus gtk panel, IBus already did it with gsettings.

**Comment by rtcm** [comment]
Instead of a gsetting it would be nice if IBus exported a recommended font size (as a hint) in the panel DBus API so that panel implementations can adjust the font size dynamically as needed.

**Comment by hadess** [comment]
> Instead of a gsetting it would be nice if IBus exported a recommended font size (as a hint) in the panel  DBus API so that panel implementations can adjust the font size dynamically as needed.

And by "font size", he means a ratio compared to the default font size (eg. 1.5x or 2.x)

**Comment by rtcm** [comment]
To make my proposal more concrete:

IBusPanelService signals like ::update-preedit-text, ::update-auxiliary-text and ::update-lookup-table could include in their IBusText instances a new (to be introduced) IBusAttribute type that would be similar to pango's PangoAttrSize using fractional values equivalent to pango's xx-small, medium, large, etc.[1]

[1] https://developer.gnome.org/pango/stable/pango-Text-Attributes.html#PANGO-SCALE-XX-SMALL:CAPS

**Comment by fujiwarat** [comment]
I think the whole UI also includes the ibus lookup table.
Do you wish to change the size of lookup table only? ibus gtk panel changes lookup table, IME switcher window, and panel menus at least.

**Comment by rtcm** [comment]
I did list the signals that I think should have this new attribute and that includes ::update-lookup-table.

But, the original request in [1] was:

"There is an option in ibus-setup to specify the font used to show the input method candidates."

and I think you probably know better which text exactly should be scaled.

[1] https://bugzilla.gnome.org/show_bug.cgi?id=708890#c0

**Comment by fujiwarat** [comment]
> "There is an option in ibus-setup to specify the font used to show the input method candidates."

I assume the option in ibus-setup does not for the candidate size only.

**Comment by fujiwarat** [comment]
I reported this issue to https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/7230 and seems `gnome-control-center` and `gnome-tweaks` already provide `org.gnome.desktop.interface text-scaling-factor`
