### ISSUE TITLE
lost ibus-table-wubi IM

### ISSUE THREAD

**Issue by JustinWuCN** [ibus/ibus#1931]
we use archlinux. and upgrade system with "pacman -Syu" at yestoday.
then, we can not find wubi IM again. at "IBus Preferences".

I am sure that we had install table-engine at system.

justin@meizu:/usr/share/kbd/keymaps$ pacman -Ss ibus-table
community/fcitx-table-other 0.2.3-2
    Provides some other tables for Fcitx, fork from ibus-table-others, scim-tables.
community/ibus-table 1.9.17-1 [已安装]
    IM Engine framework for table-based input methods, such as ZhengMa, WuBi, ErBi, CangJie and so on
community/ibus-table-chinese 1.8.2-2 [已安装]
    Some table-based input method of tables engines for IBus
community/ibus-table-extraphrase 1.3.9.20110826-2
    The extra phrases of tables engines for IBus

**Comment by mike-fabian** [comment]
> community/ibus-table-chinese 1.8.2-2 [已安装]
> Some table-based input method of tables engines for IBus

ibus-table-chinese should contain two Wubi tables.  On Fedora, these are sub-packabes of ibus-table-chinese:

$ rpm -qa | grep  ibus-table-chinese
ibus-table-chinese-stroke5-1.8.2-6.fc24.noarch
ibus-table-chinese-scj-1.8.2-6.fc24.noarch
ibus-table-chinese-cangjie-1.8.2-6.fc24.noarch
ibus-table-chinese-cantonese-1.8.2-6.fc24.noarch
ibus-table-chinese-easy-1.8.2-6.fc24.noarch
ibus-table-chinese-quick-1.8.2-6.fc24.noarch
ibus-table-chinese-erbi-1.8.2-6.fc24.noarch
ibus-table-chinese-wu-1.8.2-6.fc24.noarch
ibus-table-chinese-array-1.8.2-6.fc24.noarch
ibus-table-chinese-wubi-haifeng-1.8.2-6.fc24.noarch
ibus-table-chinese-yong-1.8.2-6.fc24.noarch
ibus-table-chinese-1.8.2-6.fc24.noarch
ibus-table-chinese-wubi-jidian-1.8.2-6.fc24.noarch

**Comment by JustinWuCN** [comment]
maybe this is ibus-table's problem. I use "ibus list-engine" command, it missing table engine. and when I install ibus-rime package, it will add a engine name "语言： 汉语  rime - Rime".

on "IBus Preferences" dialog, it just enum recognize IM, if ibus-table not add a new engine, the user can not call ibus-table engine to use.

@mike-fabian can you teach me how to add a new engine to ibus?

**Comment by fujiwarat** [comment]
@JustinWuCN You should confirm your engine is installed in /usr/share/ibus/component at first.
Also try to check `ibus read-cache` and `ibus read-cache --system` if your engine is registered.

**Comment by mike-fabian** [comment]
@JustinWuCN Does /usr/share/ibus/component/table.xml exist on your system?

It should contain a line  like: 

<engines exec='/usr/libexec/ibus-engine-table --xml'/>

(The path to ibus-engine-table might be different on your distribution)

If  you execute this:

    /usr/libexec/ibus-engine-table --xml

it should list the  available ibus-table engines.

**Comment by mike-fabian** [comment]
@JustinWuCN And in /usr/share/ibus-table/tables/ you should see which tables are installed,
for example for Wubi you should find something like /usr/share/ibus-table/tables/wubi-haifeng86.db
and/or /usr/share/ibus-table/tables/wubi-jidian86.db there.

**Comment by mike-fabian** [comment]
@JustinWuCN 
> @mike-fabian can you teach me how to add a new engine to ibus?

Do you mean how to write a new table for ibus-table?

**Comment by JustinWuCN** [comment]
@mike-fabian
Thanks for your help!
I list the /usr/share/ibus/component directory. table.xml is exist.

justin@meizu:/usr/share/ibus/component$ ll
总用量 52
drwxr-xr-x 2 root root  4096 6月  13 16:17 ./
drwxr-xr-x 6 root root  4096 10月 19 2016 ../
-rw-r--r-- 1 root root   418 5月  18 13:13 dconf.xml
-rw-r--r-- 1 root root   425 5月  18 13:13 gtkpanel.xml
-rw-r--r-- 1 root root   812 7月  19 2014 rime.xml
-rw-r--r-- 1 root root 24661 5月  18 13:13 simple.xml
-rw-r--r-- 1 root root   603 6月   4 10:23 table.xml

justin@meizu:/usr/share/ibus/component$ cat table.xml 
<?xml version='1.0' encoding='utf-8'?>

<component>
    <name>org.freedesktop.IBus.Table</name>
    <description>Table Component</description>
    <exec>/usr/lib/ibus/ibus-engine-table --ibus</exec>
    <version>1.9.17</version>
    <author>Yuwei Yu &lt;acevery@gmail.com&gt;</author>
    <license>LGPL</license>
    <homepage>http://code.google.com/p/ibus</homepage>
    <textdomain>ibus-table</textdomain>
    <observed-paths>
        <path>/usr/share/ibus-table/tables/</path>
    </observed-paths>
    <engines exec='**/usr/lib/ibus/ibus-engine-table** --xml'/>
</component>


I look like use ibus-engine-table to register the engine-table .
<engines exec='/usr/lib/ibus/ibus-engine-table --xml'/>
but, unfortunately, my system miss this program.

**Comment by JustinWuCN** [comment]
why the system delete this program on upgrade? i don't know.
now I can't find this program to install.

**Comment by fujiwarat** [comment]
> now I can't find this program to install.

Did you confirm `ibus read-cache` and `ibus read-cache --system` if your engine is registered.

Did you also confirm your table engine in /usr/share/ibus-table/tables/
```
@JustinWuCN And in /usr/share/ibus-table/tables/ you should see which tables are installed,
for example for Wubi you should find something like /usr/share/ibus-table/tables/wubi-haifeng86.db
and/or /usr/share/ibus-table/tables/wubi-jidian86.db there.
```

**Comment by JustinWuCN** [comment]
@fujiwarat  yes,table engine exist in /usr/share/ibus-table/tables/
justin@meizu:/usr/share/ibus-table/tables$ ll
总用量 45912
drwxr-xr-x 2 root root    4096 6月  13 10:02 ./
drwxr-xr-x 7 root root    4096 6月  13 09:59 ../
-rw-r--r-- 1 root root 4743168 4月  14 04:06 array30-big.db
-rw-r--r-- 1 root root 2056192 4月  14 04:06 array30.db
-rw-r--r-- 1 root root 1044480 4月  14 04:05 cangjie3.db
-rw-r--r-- 1 root root 2174976 4月  14 04:06 cangjie5.db
-rw-r--r-- 1 root root 1564672 4月  14 04:05 cangjie-big.db
-rw-r--r-- 1 root root  241664 4月  14 04:05 cantonese.db
-rw-r--r-- 1 root root  299008 4月  14 04:05 cantonhk.db
-rw-r--r-- 1 root root 3342336 4月  14 04:05 easy-big.db
-rw-r--r-- 1 root root 1273856 4月  14 04:06 erbi.db
-rw-r--r-- 1 root root 3252224 4月  14 04:06 erbi-qs.db
-rw-r--r-- 1 root root  274432 4月  14 04:05 jyutping.db
-rw-r--r-- 1 root root 1003520 4月  14 04:06 quick3.db
-rw-r--r-- 1 root root 2019328 4月  14 04:06 quick5.db
-rw-r--r-- 1 root root  339968 4月  14 04:05 quick-classic.db
-rw-r--r-- 1 root root 2273280 4月  14 04:06 scj6.db
-rw-r--r-- 1 root root  159744 4月  14 04:06 stroke5.db
-rw-r--r-- 1 root root    5109 6月   4 10:23 template.txt
-rw-r--r-- 1 root root 1970176 8月  28 2014 wubi.db
-rw-r--r-- 1 root root 5890048 8月  13 2014 wubi.db.bak
-rw-r--r-- 1 root root 4964352 4月  14 04:06 wubi-haifeng86.db
-rw-r--r-- 1 root root 5890048 4月  14 04:06 wubi-jidian86.db
-rw-r--r-- 1 root root  434176 4月  14 04:06 wu.db
-rw-r--r-- 1 root root 1785856 4月  14 04:05 yong.db

but the table engine is not be registered. read the configure on table.xml. it need to call use ibus-engine-table program to register the table engine. but , system miss  ibus-engine-table program.

**Comment by fujiwarat** [comment]
> but , system miss ibus-engine-table program.

Really? How did you install ibus-table packages? distro package command or `make install` from source codes?
I guess you didn't install a package of /usr/lib/ibus/ibus-engine-table or you installed it with a wrong path.

**Comment by JustinWuCN** [comment]
I use pacman to install. 
justin@meizu:/usr/share/ibus-table/tables$ sudo pacman -S ibus
[sudo] justin 的密码：
警告：ibus-1.5.16-1 已经为最新 -- 重新安装

**Comment by JustinWuCN** [comment]
this is list of  installed port.

justin@meizu:/usr/share/ibus-table/tables$ pacman -Ss ^ibus*
extra/ibus 1.5.16-1 [已安装]
    Next Generation Input Bus for Linux
extra/ibus-typing-booster 1.5.32-1
    Predictive input method for the IBus platform
extra/libibus 1.5.16-1 [已安装]
    IBus support library
community/ibus-anthy 1.5.9-1
    Japanese input method Anthy IMEngine for IBus Framework
community/ibus-chewing 1.5.1-2
    Chinese Chewing Engine for IBus Framework
community/ibus-googlepinyin 0.1.2-6
    IBus Wrapper for libgooglepinyin
community/ibus-hangul 1.5.0-3
    Korean input engine for IBus
community/ibus-kkc 1.5.22-1
    libkkc (Japanese Kana Kanji input method) engine for ibus
community/ibus-libpinyin 1.8.92-1
    Intelligent Pinyin engine based on libpinyin for IBus
community/ibus-m17n 1.3.4-4
    M17N engine for IBus
community/ibus-pinyin 1.5.0-5
    Pinyin (Chinese) input method for the IBus framework
community/ibus-qt 1.3.3-8
    IBus qt library and IBus qt input method plugin
community/ibus-rime 1.2-1 [已安装]
    Rime input method engine for ibus
community/ibus-skk 1.4.2-1
    Japanese input method SKK engine for IBus
community/ibus-sunpinyin 3.0.0rc1-3
    IBus Wrapper for sunpinyin
community/ibus-table 1.9.17-1 [已安装]
    IM Engine framework for table-based input methods, such as ZhengMa, WuBi, ErBi, CangJie and so on
community/ibus-table-chinese 1.8.2-2 [已安装]
    Some table-based input method of tables engines for IBus
community/ibus-table-extraphrase 1.3.9.20110826-2
    The extra phrases of tables engines for IBus
community/ibus-unikey 0.6.1-4
    IBus module for Vietnamese Keyboard

**Comment by JustinWuCN** [comment]
use ibus read-cache, it look the "engine" is null. and compare with rime IM.the engine have configure msg.

![image](https://user-images.githubusercontent.com/29391855/27211122-b8e7ca56-521c-11e7-9f78-0b1419191837.png)

![image](https://user-images.githubusercontent.com/29391855/27211166-008b3e56-521d-11e7-9656-2fa6910dd8cd.png)

**Comment by mike-fabian** [comment]
@JustinWuCN 

You seem to have  main ibus-table package installed:

community/ibus-table 1.9.17-1 [已安装]
IM Engine framework for table-based input methods, such as ZhengMa, WuBi, ErBi, CangJie and so on

This package should contain the file /usr/lib/ibus/ibus-engine-table

Can you list the files in that package? Maybe this is a packaging error if the file /usr/lib/ibus/ibus-engine-table is missing.

**Comment by JustinWuCN** [comment]
@mike-fabian @fujiwarat thank your help.

now we know what problem with it.
first, I find ibus-engine-table, it is stay on /usr/lib/ibus, and my $PATH not include this path, so, the console not Auto-Complete for me.

last, this problem reson is : my system is using python 2.7. when run "./ibus-engine-table --xml", it will error. so the table engine parameter is null.
justin@meizu:/usr/lib/ibus$ ./ibus-engine-table --xml
Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/main.py", line 304, in <module>
    main()
  File "/usr/share/ibus-table/engine/main.py", line 282, in main
    sys.stdout.buffer.write((egsout+'\n').encode('utf-8'))
AttributeError: 'file' object has no attribute 'buffer'


now , I change /usr/share/ibus-table/engine/main.py line 282 to "sys.stdout.write((egsout+'\n').encode('utf-8'))".

and run ibus write-cache. the table engine is filled correct.
![image](https://user-images.githubusercontent.com/29391855/27220892-47a07e94-524c-11e7-968a-b44f51f72372.png)



thank yours!!

**Comment by fujiwarat** [comment]
Your bug report confuse several parts.
1. You acutally had ibus-engine-table.
2. AttributeError: 'file' object has no attribute 'buffer'
Because you run python2. I think it works for python3.
3. Your issue is not ibus. Please file for ibus-table which should support python2.
https://github.com/ibus/ibus/wiki/BugReport
