### ISSUE TITLE
Typo in string

### ISSUE THREAD

**Issue by Jibec** [ibus/ibus#1933]
Hi,

> Whether emoji annotaions can be match partially or not
> Refs: ../data/ibus.schemas.in.h:57

> Match emoji annotaions with the specified length
> Refs: ../data/ibus.schemas.in.h:59

> Emoji annotaions can be match partially
> Refs: ../ui/gtk3/emojierapp.vala:83

It think it should be *annotations*

have a good day

**Comment by Jibec** [comment]
Again:

> Match emoji annotaions with the specified length
> Refs: ../data/ibus.schemas.in.h:59

**Comment by fujiwarat** [comment]
Thank you for the report.
Working on this; https://codereview.appspot.com/323330043/
