### ISSUE TITLE
Add macOS-like dead key preview (display compose state)

### ISSUE THREAD

**Issue by ariasuni** [ibus/ibus#1935]
On macOS, when you type a dead key, the character associated with this dead key (terminator) is displayed with a different style (yellow background), until we type another character or cancel the input.
![screenshot_20170730_210636_cropped](https://user-images.githubusercontent.com/2446451/28756255-34e22338-756b-11e7-8ebc-1b62a83079d9.png)

This is similar to how several IBus methods works. For example, ibus-anthy: if I type `k`, it’s displayed with an underline and not yet committed; then if I type a, it displays and commits か.

I guess IBus could be able to monitor the compose state to display inform the user if a dead key was previously typed, so the user understand better what’s going (e.g. when mistyping).

It could greatly improve the use of Compose too. For example, imagine that `⎄1/4` produce ¼:
- I type `multi_key`, so `⎄` is displayed with an underline
- Then I type `1`, so `⎄1` is displayed with an underline
- Then I type `/`, so `⎄1/` is displayed with an underline
- Then I type `4`, the compose sequence `⎄1/4` is found, so `¼` is displayed.

**Comment by fujiwarat** [comment]
If `Multi_key-a` is typed, `^` is shown?
If `dead_circumflex` is typed, 'a' is shown?
If `Multi_key-^` is typed, 'a' is shown?

I think if `Multi_key` is typed, there are may candidates.

**Comment by ariasuni** [comment]
I’m sorry, I don’t understand what you are saying at all.

I would that if I type `dead_circumflex`, `^` is shown with an underline (or something else). Then typing `a` would produce `â` as expected, and the underlined `^` disappear.

**Comment by fujiwarat** [comment]
Thank you, I understand your suggestion now.
I thought you mean to show the next candidates of `a` by mistake but actually you means to show the current preedit of `^`. I.e. to show the invisible keysym `dead_circumflex` with the visible '^'.

**Comment by gcms** [comment]
I created an ibus input method that does something similar to this: http://github.com/gcms/ibus-semidead . BTW it was working fine on Ubuntu 16.04 but I updated to a new Ubuntu version and suddenly the keyboard doesn't show up in the system keyboards. Using ibus-setup I can find and correctly add the new input method, but I can't use it in the system.

**Comment by fujiwarat** [comment]
I was busy for several tasks.
It's time to postpone this issue till 1.5.19

**Comment by ariasuni** [comment]
Do you think somebody that doesn’t know the IBus code base can help you, or is it too complicated? I’ll be glad if I could help even a little bit.

**Comment by fujiwarat** [comment]
I don't think the fix is complicated but I had been busy for other tasks. Probably I think ibus_engine_simple_update_preedit_text() has to be modified.

**Comment by ariasuni** [comment]
It works really well with pure GTK3 apps. Unfortunately, it doesn’t work as well with other apps.

- For Thunderbird and Firefox, the preedit accent is placed above the previous letter, which is confusing.
- For Qt apps, the preedit accent is placed on the cursor which is not very readable, and it doesn’t appear in Konsole.

Not sure what you can to to improve the situation on your side, but the Firefox/Thunderbird is especially bad because it makes dead keys more confusing.

**Comment by fujiwarat** [comment]
Thank you for the quick test.

> For Thunderbird and Firefox, the preedit accent is placed above the previous letter, which is confusing.

Could you give more info? What did you type?

> For Qt apps, the preedit accent is placed on the cursor which is not very readable, and it doesn’t appear in Konsole.

same.

Could you attach the screenshots of those cases? Each desktop environment provides a tool to capture the screenshot.

**Comment by ariasuni** [comment]
I made more tests and saw a lot of issues.

- Krunner — Qt (`e^`):
![screenshot_20180627_145356](https://user-images.githubusercontent.com/2446451/41975061-f67265fe-7a19-11e8-9033-2db319c2e397.png)
- Krunner (when you type a dead `` ` `` at the start of the input):
![screenshot_20180627_150549](https://user-images.githubusercontent.com/2446451/41975640-9b3dcdfc-7a1b-11e8-95d6-99cabfc15f9e.png)
- Virtualbox — Qt (`10^`, you can see the outline is one pixel wide too):
![screenshot_20180627_145740](https://user-images.githubusercontent.com/2446451/41975258-7d4a9df8-7a1a-11e8-992d-42f32b4fee76.png)
- Firefox (when pressing `^ee^`):
![screenshot_20180627_145900](https://user-images.githubusercontent.com/2446451/41975318-a9b009f0-7a1a-11e8-9548-f082ca8ffa7c.png)
- Firefox (`e[space]^`):
![screenshot_20180627_150010](https://user-images.githubusercontent.com/2446451/41975414-ea77fb46-7a1a-11e8-939a-666e69a34a04.png)
- Xfce4-terminal — GTK3 (`cat←¨`):
![screenshot_20180627_151039](https://user-images.githubusercontent.com/2446451/41976046-4d983690-7a1c-11e8-9ceb-a8193ca83b6e.png)

In Konsole, it just doesn’t show up. I don’t know why, because combining characters seems to work correctly for example.

Everything I reported here work perfectly well with e.g. ibus-anthy — except the issue with Xfce4-terminal which is just more annoying in this case.

**Comment by fujiwarat** [comment]
Thank you.
I enhanced the behavior; https://github.com/fujiwarat/ibus/commits/compose
Could you test it?

**Comment by fujiwarat** [comment]
I updated the dead_greek:
https://github.com/fujiwarat/ibus/commit/736c563c5e1415f84eead931ca9dc9aadfb7eddc

If there is no other issues, I will commit the changes tomorrow.

**Comment by jpleau** [comment]
Is there a setting to go back to the old behavior on this ? Not everyone uses macos, and honestly I have never seen this before. It is very distracting if you're not used to it.

**Comment by fujiwarat** [comment]
Currently I don't think to provide the option.

> It is very distracting if you're not used to it.

How does it distract you?

**Comment by jpleau** [comment]
> How does it distract you?

I've been typing for more than 20 years, like a lot of people I look at the monitor while typing, not the keyboard. I type `^` and then `e` to type `ê`, and I never saw anything appear until the final character was "done" being typed.

Now everytime I'm typing a character that needs 2 keystrokes, I'm second guessing myself since I now see something appear, unlike before.

I fixed the problem by disabling ibus on my ubuntu 20.04 install, but I don't think that's a good solution since I can't use many of the features ibus provides.

**Comment by Dheinny** [comment]
> > How does it distract you?
> 
> I've been typing for more than 20 years, like a lot of people I look at the monitor while typing, not the keyboard. I type `^` and then `e` to type `ê`, and I never saw anything appear until the final character was "done" being typed.
> 
> Now everytime I'm typing a character that needs 2 keystrokes, I'm second guessing myself since I now see something appear, unlike before.
> 
> I fixed the problem by disabling ibus on my ubuntu 20.04 install, but I don't think that's a good solution since I can't use many of the features ibus provides.

I completely agree with  @jpleau . I've updated my Ubuntu 20.04, so I got that unusual feature in IBUS.
I wouldn't like to uninstall the whole framework because of this functionality.
Is it very complicated to provide an option to disable it?

**Comment by mike-fabian** [comment]
I implemented this the same way (i.e. with preview) in ibus-typing-booster and one cannot disable it there either
(ibus-typing-booster has its own compose support because it also needs to work inside an preedit but it looks the same way as the compose support in the core of ibus).

I found the preview very helpful especially for longer compose sequences and I see no reason to disable this, 
I think it makes typing compose sequences much easier.

**Comment by fujiwarat** [comment]
> Now everytime I'm typing a character that needs 2 keystrokes, I'm second guessing myself since I now see something appear, unlike before.

You just explained the current state but I think you didn't answer my question; How does it distract you?

**Comment by jpleau** [comment]
> 
> 
> > Now everytime I'm typing a character that needs 2 keystrokes, I'm second guessing myself since I now see something appear, unlike before.
> 
> You just explained the current state but I think you didn't answer my question; How does it distract you?

I cannot explain how it distracts me. It just does. You can close this anyway, I have reverted to an old version and will maintain a fork.

**Comment by leo60228** [comment]
Sorry to bump this old issue, but is it possible to disable this? I preferred the old way.

**Comment by nfp0** [comment]
As a frequent user of dead keys, I also believe this is extremely distracting and should be an option.

> How does it distract you?
@fujiwarat We, speakers of languages with very frequent dead keys (such as portuguese, spanish, french, etc), have been grown accustomed to not expect a feedback from a dead key for decades. My instinct as soon as we see the preview is: "Woops! I mistyped.", and I almost reach for the backspace. It's very jarring to suddenly change this behavior and even though I believe it's a good feature, it should be toggleable.

**Comment by leo60228** [comment]
In addition, some applications like Discord completely break the preview. I
need to type the character in another application then copy it.

**Comment by fujiwarat** [comment]
> I need to type the character in another application then copy it.

I don't think this feature prevents you from copying it.

**Comment by fujiwarat** [comment]
After I had some discussion with GTK developers, IBus will follow the recent GTK change after Fedora 34 GA:
https://blog.gtk.org/2021/03/24/input-revisited/

**Comment by leo60228** [comment]
> I don't think this feature prevents you from copying it.

To clarify, the *visual feedback* is incompatible with Discord, meaning
that I have to type the character in another application.

Additionally, I think that GTK's behavior makes sense for dead keys. I do
think that visual feedback for the compose should at the very least be
optional, however.

**Comment by fujiwarat** [comment]
> To clarify, the *visual feedback* is incompatible with Discord, meaning
that I have to type the character in another application.

I won't touch Discord and probably your issue could be fixed in each application.

> Additionally, I think that GTK's behavior makes sense for dead keys. I do
think that visual feedback for the compose should at the very least be
optional, however.

OK, it's good to get a nod on the GTK's proposal. My understanding is GTK won't take any configurations on the compose behavior and you need to consider the better implementations with the direction.

**Comment by ariasuni** [comment]
> After I had some discussion with GTK developers, IBus will follow the recent GTK change after Fedora 34 GA:
> https://blog.gtk.org/2021/03/24/input-revisited/

I think it’s very clever and would like to see this changes added to IBus too. Is there an issue opened for this proposed change yet?
