### ISSUE TITLE
Can't chang fonts sizes

### ISSUE THREAD

**Issue by stevenGu** [ibus/ibus#1940]
i used ubuntu-gnome 16.04 LTS in chinese. i had run "sudo ibus-setup" and chang fonts size to "24",
because i'm old man ^-^!  but nothing happn! In ubuntu 16.04LTS i can chang it with same method.

How to chang fonts size ?
![2017-08-27 22-58-29](https://user-images.githubusercontent.com/1780889/29751226-55002372-8b7d-11e7-853c-860764347a48.png)

**Comment by fujiwarat** [comment]
ibus-setup works for IBus GTK panel icon. GNOME-Shell uses the own panel icon for IBus and ibus-setup does not effect for it.
You could refer issue #1928 and https://bugzilla.gnome.org/show_bug.cgi?id=708890
