### ISSUE TITLE
Ctrl+Shift+F快捷键冲突

### ISSUE THREAD

**Issue by zyddn** [ibus/ibus#1941]
Ctrl+Shift+F与Eclipse 代码格式化 快捷键冲突，请问如何更改该快捷键？

**Comment by fujiwarat** [comment]
I can open "Find in Files" dialog with Ctrl-Shift-f keys with IBus.
Which ibus engine did you use?
You can check the current ibus engine with `ibus engine` command.

**Comment by zyddn** [comment]
我用的是ibus-libpinyin 1.6.91，这版可能没有修改简繁切换快捷键的功能，谢谢解答！
