### ISSUE TITLE
when switching from xkb:ru::rus to libpinyin i can not type chinese characters. 

### ISSUE THREAD

**Issue by i4778370** [ibus/ibus#1943]
... i keep getting russian letters in this case. 
it does successfully switch to chinese characters when switching from m17n:ru:translit or m17n:ru:yawerty

I'm on Fedora 26 but i've been noticing the similar behaviour in other distros as well
uname -a: Linux localhost.localdomain 4.12.9-300.fc26.x86_64 #1 SMP Fri Aug 25 13:09:43 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

my  ibus read-config:

SCHEMA: org.freedesktop.ibus.general
  dconf-preserve-name-prefixes: ['/desktop/ibus/engine/pinyin', '/desktop/ibus/engine/bopomofo', '/desktop/ibus/engine/hangul']
  use-system-keyboard-layout: false
  embed-preedit-text: true
  enable-by-default: false
  use-global-engine: true
  use-xmodmap: true
  switcher-delay-time: 400
  version: '1.5.16'
  engines-order: ['xkb:us::eng', 'libpinyin', 'xkb:ru::rus', 'm17n:ru:translit', 'm17n:ru:yawerty', 'typing-booster:ru_RU']
  preload-engines: ['xkb:us::eng', 'libpinyin', 'xkb:ru::rus', 'm17n:ru:yawerty', 'typing-booster:ru_RU', 'm17n:ru:translit']
  xkb-latin-layouts: ['ara', 'bg', 'cz', 'dev', 'gr', 'gur', 'in', 'jp(kana)', 'mal', 'mkd', 'ru', 'ua']
SCHEMA: org.freedesktop.ibus.general.hotkey
  next-engine: ['Alt+Shift_L']
  disable-unconditional: @as []
  enable-unconditional: @as []
  trigger: ['Control+space', 'Zenkaku_Hankaku', 'Alt+Kanji', 'Alt+grave', 'Hangul', 'Alt+Release+Alt_R']
  previous-engine: @as []
  prev-engine: @as []
  next-engine-in-menu: ['Alt+Shift_L']
  triggers: ['<Super>space']
SCHEMA: org.freedesktop.ibus.panel
  x: -1
  property-icon-delay-time: 500
  y: -1
  show: 0
  lookup-table-orientation: 1
  xkb-icon-rgba: '#415099'
  auto-hide-timeout: 10000
  show-im-name: false
  follow-input-cursor-when-always-shown: false
  custom-font: 'Sans 10'
  show-icon-on-systray: true
  use-custom-font: false

will be glad to provide further info if needed!
Thanks a lot!

EDIT: for now the workaround is to switch from xkb:ru::rus to xkb:us::eng and then to libpinyin

**Comment by fujiwarat** [comment]
Yes, it's the expected result. Pinyin works with the several keymaps, us, dvorak us, jp so the engine does not change the current layout.
You can modify `<layout>` tag in /usr/share/ibus/component/libpinyin.xml by manual

**Comment by i4778370** [comment]
hm. alright then, as long as you guys are aware of the current state... 
once again thanks for your time and good luck with the further development!

**Comment by WGH-** [comment]
For what it's worth, I have the same issue with Japanese language with mozc, but, for some reason, not with anthy. It seems like anthy does it right somehow.

**Comment by mike-fabian** [comment]
Neither mozc nor  anthy nor kkc change the keyboard layout. And that is the way it should be
because phonetic Japanese input can be done with many different keyboard layouts.

**Comment by WGH-** [comment]
To clarify, I'm using Japanese IME, both Anthy and mozc, in "QWERTY mode", i.e. I input latin transliteration (romaji), which is then converted to Japanese writing semiautomatically.

**Comment by fujiwarat** [comment]
> I have the same issue with Japanese language with mozc, but, for some reason, not with anthy.

ibus-anthy has a setting dialog to set the default layout.

**Comment by fujiwarat** [comment]
I explained at https://github.com/ibus/ibus/issues/1943#issuecomment-327703243

**Comment by WGH-** [comment]
Aaah, thank you, I finally got this! So, for, mozc, the fix is just replace `default` with `jp`. I recon the fix for libpinyin would be similar.

```diff
diff --git a/component/mozc.xml b/-
index a7be498..0000000 100644
--- a/component/mozc.xml
+++ b/-
@@ -16,7 +16,7 @@
   <icon_prop_key>InputMode</icon_prop_key>
   <icon>/usr/share/ibus-mozc/product_icon.png</icon>
   <setup>/usr/lib64/mozc/mozc_tool --mode=config_dialog</setup>
-  <layout>default</layout>
+  <layout>jp</layout>
   <name>mozc-jp</name>
   <longname>Mozc</longname>
 </engine>
```

**Comment by WGH-** [comment]
On the second thought, this does seem like a bug.

What we have here is that basically any input method that uses `default` layout will depend on previously used input method, provided the latter changes the "layout" (?).

I can't imagine a scenario where it would be desired behaviour.

**Comment by fujiwarat** [comment]
> What we have here is that basically any input method that uses default layout

Most CJK users would use one input method and one XKB layout and toggles two and the case work fine.
In your case - three engines are switched, you need to use XKB engine before you use input method engine. Otherwise you could ask the custom UI for each engine.
The default 'jp' is not good for ja IME because there are many selections; jp, jp(dvorak), us, us(dvorak).
