### ISSUE TITLE
IBus Emoji Typing conflicts with Unicode Typing

### ISSUE THREAD

**Issue by dvorapa** [ibus/ibus#1944]
**Configuration**
Arch + Gnome + Xorg/Wayland (broken on both) + Gedit/Opera/LibreOffice/Nano/whatever

**Steps to reproduce**

1. Press Ctrl+Shift+u201E

**Expected result**
This keyboard shortcut should add Unicode [„ character](https://unicode-table.com/en/201E/)

**Current result**
The keyboard shortcut stopped working lately. Everything is ok until E is pressed, then everything is removed and only underlined "u" remains and no character is actually inserted. The bug appears for any Unicode code containing "E", therefore I think there is some conflict between Emoji and Unicode Typing

**Comment by fujiwarat** [comment]
IBus engines havn't used Ctrl-Shift-u since 1.5.15 because the shortcut key is hardcoded.
Now the default shortcut key is Ctrl-Shift-e and it can be customized and I don't see your problem.
But we don't migrate the feature in GNOME yet, you need to run `ibus emoji` command instead of Ctrl-Shift-e.

**Comment by dvorapa** [comment]
Okay, hold on. I don't understand the reason why did you close this issue, but Ctrl+Shift+u201E is the most used shortcut for Czech language. And it stopped working like all the other similar Unicode shortcuts containing "E" (Ctrl+Shift+u202E, u101E). Therefore this bug should be fixed. Is this a bug in ibus? I think so, but maybe I'm wrong and you did not specified the reason clearly in your message

**Comment by dvorapa** [comment]
(Side note: I don't understand anything what you wrote to me, I'm just a regular Linux user who can not use one of the basic features Linux has got)

**Comment by dvorapa** [comment]
@fujiwarat How can I turn off this Ctrl+Shift+e emoji function off completely? This is a feature I can spare

**Comment by fujiwarat** [comment]
> How can I turn off this Ctrl+Shift+e thing completely?

Did you install the latest ibus?
Also the shortcut key works for non-GNOME desktops. You need to run `ibus emoji` command in GNOME or register the CLI as a GNOME shortcut key.

**Comment by dvorapa** [comment]
There is the latest libibus 1.5.16-1 installed by Gnome as a dependency from Arch Linux repositories. I installed ibus today and run `ibus emoji`. Some empty zero-size window openned and there were multiple errors and warnings in terminal. But Ctrl+Shift+u was still broken.

**Comment by dvorapa** [comment]
On some forums, I've got two possible solutions:
`gsettings set  org.gnome.settings-daemon.plugins.xsettings overrides  "{'Gtk/IMModule':''}"`
`gsettings set org.gnome.desktop.interface gtk-im-module gtk-im-context-simple`
But I don't want to fix something that is not my fault. I did this in Windows and Ubuntu after some broken updates, once a year I had to reinstall completely the system because of some completely broken update and I hoped Arch's update approach is somewhat better and broken thing like this will never be in a production here.

**Comment by fujiwarat** [comment]
> Some empty zero-size window openned and there were multiple errors and warnings in terminal.

Can you paste the error?
I guess you use German locale which was a fixed bug.

**Comment by dvorapa** [comment]
I use Czech locale. What is `ibus emoji` supposed to do?

**Comment by dvorapa** [comment]
Sometimes it gives also another error and no window is shown.
No window:
```
$ ibus emoji
GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```
Empty zero-width window:
```
$ ibus emoji
(ibus-ui-emojier:4928): IBUS-WARNING **: emojier.vala:318: Failed css_provider_from_data: <data>:1:64Expected ')' in color definition

(ibus-ui-emojier:4928): Gtk-CRITICAL **: gtk_entry_set_text: assertion 'GTK_IS_ENTRY (entry)' failed

(ibus-ui-emojier:4928): Gtk-CRITICAL **: gtk_container_foreach: assertion 'GTK_IS_CONTAINER (container)' failed

(ibus-ui-emojier:4928): IBUS-CRITICAL **: ibus_emojier_etitle_label_box_set_lang_label: assertion 'self != NULL' failed

(ibus-ui-emojier:4928): Gtk-CRITICAL **: gtk_container_add: assertion 'GTK_IS_CONTAINER (container)' failed

(ibus-ui-emojier:4928): Gtk-CRITICAL **: gtk_entry_set_activates_default: assertion 'GTK_IS_ENTRY (entry)' failed
```

**Comment by dvorapa** [comment]
Side note: I don't like installing the whole ibus in order to fix a bug in libibus

**Comment by fujiwarat** [comment]
> ibus-ui-emojier:4928): IBUS-WARNING **: emojier.vala:318: Failed css_provider_from_data: <data>:1:64Expected ')' in color definition

It was a bug to fail to parse the color value of "(r, g, b)" because your locale's decimal point is `,`:
```
% env LANG=cs_CZ.utf8 locale -ck decimal_point
LC_NUMERIC
decimal_point=","
```

I got the same bug for German locale and it's fixed in git master https://github.com/ibus/ibus/commit/bc0f91342c6f3a6e554493af9430d634d906ee19

**Comment by fujiwarat** [comment]
> Side note: I don't like installing the whole ibus in order to fix a bug in libibus

OK, the workaround would be rename ibus-ui-emojier. E.g. I assume the installed path is `/usr/libexec/ibus-ui-emojier`.
```
# mv /usr/libexec/ibus-ui-emojier /usr/libexec/ibus-ui-emojier.orig
# vi /usr/libexec/ibus-ui-emojier 
# cat /usr/libexec/ibus-ui-emojier
#!/bin/sh
export LANG=en_US.UTF-8
${0}.orig $@
# chmod a+x /usr/libexec/ibus-ui-emojier
```

Then `ibus emoji` will work on cs_CZ.UTF-8 at the moment.

**Comment by luebking** [comment]
His problem is that libibus (or whatever) does not detect that the user in the middle of a unicode input sequence when reacting to ctrl+shift+e - it is *not* the inability to insert emojis.

Ie. there's a collision between the two input methods - I don't have libibus, but gtk+ provides the ability to insert random utf-8 codepoints through ctrl+shift+u.
This is not a problem for u+1234, but apparently *is* a problem for u+12e4 if (and only if) libibus is installed and registered as input handler, because libibus will consider the "e" in the codepoint (along the still pressed modifiers) as trigger to start an emoji sequence.

@dvorapa 
For the time being, you can also release the modifiers, enter the codepoint and press enter to finish the sequence.

**Comment by dvorapa** [comment]
@luebking Yeah, it works when releasing Ctrl+Shift, you're right, thank you. But I hope this conflict will be resolved soon.
@fujiwarat Your workaround brought me a broken window with some categories. But there was no possibility or option to disable Ctrl+Shift+e shortcut (btw emoji previews were messed - almost all of them just unknown character square - ▯)

**Comment by fujiwarat** [comment]
> His problem is that libibus (or whatever) does not detect that the user in the middle of a unicode input sequence when reacting to ctrl+shift+e - it is not the inability to insert emojis.

What is the middle of a unicode point sequence?
Did you see a Gtk input dialog which is same of /usr/libexec/ibus-ui-emojier ?
As I noted, Ctrl-Shift-e does not enable in GNOME desktop.

> Ie. there's a collision between the two input methods

? ibus won't use gtk shortcut keys.

>  but apparently is a problem for u+12e4 if (and only if) libibus is installed and registered as input handler

I think the latest ibus should not have such a problem because ibus no longer use Ctrl-Shift-u.
I guess you still use an old ibus or does not install the emoji features.

**Comment by fujiwarat** [comment]
> But there was no possibility or option to disable Ctrl+Shift+e shortcut 

Option to disable Ctrl-Shift-e? Do you use non-GNOME desktop?
If yes, you can customize the shortcut key with `ibus-setup` utility.

> (btw emoji previews were messed - almost all of them just unknown character square - ▯)

The font can be customized with ibus-setup.

**Comment by fujiwarat** [comment]
@dvorapa https://desktopi18n.wordpress.com/2017/05/29/ibus-1-5-16-is-released/

**Comment by dvorapa** [comment]
> What is the middle of a unicode point sequence?
Ctrl+Shift+u12**e**3
> As I noted, Ctrl-Shift-e does not enable in GNOME desktop.
It is enabled on Gnome desktop right now, using `libibus` (because I haven't got `ibus` installed)
> ibus won't use gtk shortcut keys.
But breaks their behavior and collides with them
> I guess you still use an old ibus or does not install the emoji features.
I don't want to have old ibus, it is a buggy and security risk. I've never installed any ibus emoji feature, this came installed with Gnome in some update. I'm not trying to insert an emoji, I'm trying to insert non-emoji character, though Ctrl+Shift+u, which is a function of gtk (as I learnt here) and it is broken by some Ctrl+Shift+e shortcut, which you say is ibus feature
> Option to disable Ctrl-Shift-e? Do you use non-GNOME desktop?
I use clean Gnome on Arch, with some Gnome themes from Gnome extensions website

**Comment by fujiwarat** [comment]
> It is enabled on Gnome desktop right now, probably by `libibus` (because I haven't got `ibus` installed)
> But breaks their behavior and collides with them

Seems you still install the old ibus. The latest ibus does not bind the shortcut keys in im-ibus.so.

> As I said I have got the latest ibus (libibus) possible and I've never installed any ibus emoji feature,

Not sure why you have ibus-ui-emojier which is only enabled when the emoji feature is enabled.

> I'm not trying to insert an emoji, 

Yes, you don't have to do. The latest emoji dialog support to type tye Unicode code points.

**Comment by dvorapa** [comment]
> Seems you still install the old ibus. The latest ibus does not bind the shortcut keys in im-ibus.so.

`pacman` says `1.5.16-1`
> Not sure why you have ibus-ui-emojier

I had this file only when I installed `ibus` to run `ibus emoji`, you suggested
> The latest emoji dialog support to type tye Unicode code points.

But I don't want to use this emoji dialog every time I want to insert Czech quotation marks („“ - u201e, u201c), I love the Ctrl+Shift+u approach

**Comment by dvorapa** [comment]
> The latest emoji dialog support to type tye Unicode code points.
Nobody wants to empty clipboard and place a paragraph to the temporary destination in order to type quotation marks.

**Comment by fujiwarat** [comment]
> I had this file only when I installed ibus to run ibus emoji, you suggested

You need to install whole the ibus with enabled emoji features.

> But I don't want to use this emoji dialog every time I want to insert Czech quotation marks („“ - u201e, u201c), I love the Ctrl+Shift+u approach

You don't have to use mouse for the dialog. Launching dialog by Ctrl-Shift-e and typing unicode and return then you can paste the selected unicode characters.
Currently you have to run the paste key, Ctrl-v, since the feature is not integrated in GNOME but I think other steps are same with the old Ctrl-Shift-u.
The old way has the hard-coded shortcut keys, and provided for CLI users.
Now the dialog supports both CLI and GUI users and can customize the shortcut key.

**Comment by dvorapa** [comment]
@luebking The problem with your solution comes on laptops without numeric keyboard with Czech/German layout. We have to press Shift in order to type numbers (because on that place we have got diacritics like ěščřžýáíéäëïüöÿ by default) and after releasing Shift it don't let me write the ending **e** :/

**Comment by fujiwarat** [comment]
> Nobody wants to empty clipboard and place a paragraph to the temporary destination in order to type quotation marks.

The clipboard way is the workaround for GNOME only until the emoji features are integarted into GNOME.
And the dialog is also effective to enable any IBus engines but not IBus XKB engines. I.e. now IBus emoji  annotations support to type a language besides English and typing code point is available in any IBus engines.

**Comment by dvorapa** [comment]
@fujiwarat I understand this will be a great feature after this will be integrated to Gnome. But now it doesn't work as expected and just breaks the old working behavior, the old good Ctrl+Shift+u feature we're used to. I would like to remind you, that on clean fully updated Gnome Ctrl+Shift+e just does nothing at all and in addition breaks old good gtk Ctrl+Shift+u shortcut

**Comment by dvorapa** [comment]
**e** is also in ∞ (infinity, u221e) and some of the greek alphabet I use quite often: these does not work for me too

**Comment by fujiwarat** [comment]
It's still unclear why you're still saying Ctrl-Shift-e on GNOME, which is not available until you register the shortcut key with `ibus emoji` and gnome-control-center.
I don't try Arch GNOME but pure GNOME never launch ibus-ui-gtk3 which binds ibus shortcut keys and that's why the shortcut key is not available in GNOME.

**Comment by fujiwarat** [comment]
> e is also in ∞ (infinity, u221e) and some of the greek alphabet I use quite often: these does not work for me too

But it does not happen in the latest ibus, i.e. `ibus emoji` command.

**Comment by dvorapa** [comment]
> It's still unclear why you're still saying Ctrl-Shift-e on GNOME, which is not available until you register the shortcut key with ibus emoji and gnome-control-center.

=>
> **Steps to reproduce**
> 1. Hold Ctrl+Shift
> 2. Write "u201E" (or other Unicode code containing **e**)
> 3. Release Ctrl+Shift

**Comment by luebking** [comment]
Germans don't use diacritics ;-)

@fujiwarat maybe some undesired setting/side effect?
Not using gnome myself - which switch in gnome-control-center would actvate the shortcut?
(ibus-ui-gtk3 is distributed with the ibus package which is not a dependency of gnome and claimed to not be installed by dvorapa but for testing purposes in the context of this issue)

**Comment by fujiwarat** [comment]
> **Steps to reproduce**
> 1. Hold Ctrl+Shift
> 2. Write "u201E" (or other Unicode code containing **e**)
> 3. Release Ctrl+Shift

The example uses Ctrl-Shift-u? I mean you're sometimes saying Ctrl-Shift-e besides Ctrl-Shift-u while you use GNOME.
And I don't reproduce your problem in the latest ibus.
You might also need another patch - https://github.com/ibus/ibus/commit/bbfb3d738b9d61d1eb0658a9ce56e3cd8c111ac4 .

**Comment by fujiwarat** [comment]
@luebking If you don't install GNOME, the shortcut key is handled by ibus-setup but not gnome-control-center. The emoji dialog also enables the unicode point typing:
https://desktopi18n.wordpress.com/2017/05/29/ibus-1-5-16-is-released/

**Comment by dvorapa** [comment]
> The example uses Ctrl-Shift-u? I mean you're sometimes saying Ctrl-Shift-e besides Ctrl-Shift-u while you use GNOME.

Yes, it uses Ctrl+Shift+u, but breaks, when I press **e** (which together with Ctrl+Shift is used by ibus)

**Comment by dvorapa** [comment]
@luebking I've tried to find out a workaround on laptop and it seems finally this is not an ibus issue, because:
1. Press Ctrl+Shift+u
2. Hold Shift and write 201e
3. Release Shift
makes the same problem without Ctrl (therefore Shift+e is broken in Ctrl+Shift+u mode)

**Comment by luebking** [comment]
Did you try the behavior in an openbox session?
(preferably removing libibus, in doubt ignoring dependencies - you can re-install it afterwards)

Maybe some co-incidental issue with the keyboard layout only randomly crossing the new ibus shortcut?

**Comment by dvorapa** [comment]
@luebking No, but I'm now trying to communicate this with gtk dev team on IRC as this looks more like gtk issue now
> Maybe some co-incidental issue with the keyboard layout only randomly crossing the new ibus shortcut?
Possibly, I was maybe thinking wrong about the bug origin (I was lead by people on SuperUser and Arch forum, that this could be a bug in ibus)

**Comment by dvorapa** [comment]
@fujiwarat Sorry for my confusion, finally a gtk bug. It looks like ibus and gtk are working on the same thing and the Ctrl+Shift+u and Ctrl+Shift+e in my Gnome are occupied by gtk

shortcut | ibus | gtk
------------ | ------------- | -------------
Ctrl+Shift+u | ~~removed~~ | old Unicode feature
Ctrl+Shift+e | new emoji feature, shortcut disabled by default | new emoji feature

**Comment by matthiasclasen** [comment]
See https://git.gnome.org/browse/gtk+/commit/?id=86f018c6a7a4187ed810163cfce290368b755ee3 for the gtk fix I pushed

**Comment by fujiwarat** [comment]
Hmm.., I didn't assume that feature was integrated in GTK3.

**Comment by matthiasclasen** [comment]
yes, it was - thats the version of gtk that everybody is using, after all
