### ISSUE TITLE
delete files under debian

### ISSUE THREAD

**Issue by osamuaoki** [ibus/ibus#1945]
Hi,

I am a Debian ibus maintainer.

In short, please erase everything under debian directory including the directory itself.

TL;DL

As I understand, im-switch is not used any more in Debian nor Ubuntu.  So https://github.com/ibus/ibus/tree/master/debian showing README.source is incorrect.

Also packaging style is so outdated and useless.  We use new dh syntax for debian/rules and we have multi arch things.

Besides, Debian prefers upstream not to include debian directory in the source.  (Even if you do, it will not be used.  It only confuses git repository management.)

Thanks for consideration.

Osamu

**Comment by fujiwarat** [comment]
Thank you for maintaining Debian IBus.
Since the debian package dependencies were difficult in debuild, we appreciate your great helps.
I sent a code review link to your address, if the patch is fine with you, please comment "lgtm" on the codereview messages?
