### ISSUE TITLE
Add surrounding text support to XIM client

### ISSUE THREAD

**Issue by thep** [ibus/ibus#1946]
When using IBus through XIM, some IBus engines like [ibus-libthai](https://linux.thai.net/projects/ibus-libthai) cannot retrieve or change surrounding text properly, and has to fall back to incomplete support based on previous key press.

```sh
ibus-daemon -d --xim
export GTK_IM_MODULE=xim
```

However, this is not the case when using IBus through GTK_IM_MODULE directly:

```sh
ibus-daemon -d
export GTK_IM_MODULE=ibus
```

The latter gives surrounding text access, and the IME can work properly.

Note that on Debian, the `im-config` tool always uses IBus through XIM. So, the IME is crippled by default. So, please add surrounding text support to the XIM client.

**Comment by fujiwarat** [comment]
If you set GTK_IM_MODULE=xim, it uses GTK IM module (im-xim.so) but not IBus one (im-ibus.so).
You disables IBus itself besides surrounding text feature.
I guess if you installed im-ibus.so why im-config set xim.

**Comment by thep** [comment]
It does use IBus. I just missed another piece in my report above:

```sh
ibus-daemon -d --xim
export GTK_IM_MODULE=xim
```

and then:

```sh
export XMODIFIERS=@im=ibus
```

**Comment by fujiwarat** [comment]
I don't recommend such a usage. If you set GTK_IM_MODULE=xim and then XMODIFERS=@im=none.
Your case is complicated to be handed by both GTK IM module and ibus-x11.

**Comment by thep** [comment]
I believe it's not too complicated. On the client side, both GTK+ and Qt already support surrounding text accessing with XIM. On the IME side, surrounding text manipulations have also been ready. What missing is the bridging between IBus and XIM.

The surrounding text is defined as "String Conversion" in libX11 terms, as described in Xlib interface: [overview](https://www.x.org/pub/current/doc/libX11/libX11/libX11.html#Input_Method_Overview), [callback semantics](https://www.x.org/pub/current/doc/libX11/libX11/libX11.html#Input_Method_Callback_Semantics). I even wish to work on it myself, based on [my experience in the past](https://linux.thai.net/~thep/th-xim/#XIM). I just need some guide on the relevant IBus APIs to work on. (I'm now reading `ibus/client/x11/main.c`.)

**Comment by fujiwarat** [comment]
> The surrounding text is defined as "String Conversion" in libX11 terms

It's a different topic. You have to set GTK_IM_MODULE=ibus and  XMODIFERS=@im=ibus.

**Comment by thep** [comment]
> It's a different topic. You have to set GTK_IM_MODULE=ibus and XMODIFERS=@im=ibus.

Sure. That's an obvious workaround which can easily be seen from my report above. But I'm filing this issue for another scenario, where XIM might be considered a suitable choice so it applies to X apps in general, not just those based on GTK+ or Qt. Unfortunately, that is also the default IBus config on Debian currently.
