### ISSUE TITLE
Not work in application based on electron, any idea?

### ISSUE THREAD

**Issue by lemos1235** [ibus/ibus#1948]
I can't type Chinese in "atom","vscode" or "discord" in linux, it just type English instead!!
All the software are based on electron,and I have no solution about this.Anyone has some idea?
PS:I am using ibus-rime IM,the linux os is named "solus" .

**Comment by fujiwarat** [comment]
What are "atom","vscode" or "discord" ?
Did you run ibus-daemon?
Did you try gedit?

**Comment by Ydcool** [comment]
Got the same problem. Everything works fine with other apps, like gedit, terminal, chrome ,etc,but in vscode or anyother apps based on electron , only english that I can type.
