### ISSUE TITLE
Command-line interface doesn't respect "Use system keyboard layout" option

### ISSUE THREAD

**Issue by cagprado** [ibus/ibus#1951]
I'm using arch-linux, stock kernel version 4.13.8-1 on a Dell XPS13 (9360).
iBus version is 1.5.16.

I use a customized version of the US keyboard in xkb, that is set up via xorg.conf files. Then I set the "Use system keyboard layout" in iBus options, which works fine as far as `Ctrl+Space` is concerned. However, if I use the commandline to change the input engine, then my keyboard layout is gone and it uses the engine layout.

```
$ ibus engine rime
```

Is this supposed to be the actual behaviour? (i.e. is there a way to specifically tell the command line to not set the keyboard layout) Or is it actually a bug? It seems to me that the command line should respect the config option as well.

Best

**Comment by fujiwarat** [comment]
Which desktop are you using? "Use system keyboard layout" option works for non-GNOME desktop.

> which works fine as far as Ctrl+Space is concerned. 

I don't understand what you mean here. Even if you switch ibus engines, ibus uses the system keyboard layout instead. And the default shortcut key of switching engines is Super+space.

> if I use the commandline to change the input engine, then my keyboard layout is gone and it uses the engine layout.

It should not happen if you use non-GNOME desktop.

**Comment by cagprado** [comment]
> Which desktop are you using? "Use system keyboard layout" option works for non-GNOME desktop.

I'm using i3, with SDDM as DM. I have setup `.xprofile` adding the following to it:

```
# Set keyboard and IM
setxkbmap -layout caio_us
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
```

where `caio_us` is my own keyboard layout, available in the `…/xkb/symbols` directory.
My i3 also starts up ibus in an initialization script with

```
ibus-daemon -dxr
```

> I don't understand what you mean here. Even if you switch ibus engines, ibus uses the system keyboard layout instead. And the default shortcut key of switching engines is Super+space.

Oh! I've changed my config… so, here is the dconf dump:

```
$ dconf dump /desktop/ibus/
[general]
engines-order=['xkb:us::eng', 'rime', 'anthy']
use-system-keyboard-layout=true
preload-engines=['rime', 'anthy', 'xkb:us::eng']
use-global-engine=false
version='1.5.16'

[general/hotkey]
triggers=['<Control>space']

[engine/anthy/dict/file/emoji]
long-label='Emoji'
short-label='😊'

[engine/anthy/dict/file/zipcode]
long-label='Zip Code Conversion'
short-label='〒'

[engine/anthy/dict/file/era]
long-label='Era'
short-label='年'

[engine/anthy/dict/file/oldchar]
long-label='Old Character Style'
short-label='旧'

[engine/anthy/dict/file/symbol]
long-label='Symbol'
short-label='記'

[panel/emoji]
favorites=['⌨️']

[panel]
custom-font='Sans 12'
use-custom-font=true
```

What I mean is that, with this configuration, if I use `Ctrl+Space` or if I use the systray to change the input engine, then I get the expected behaviour: ibus uses the system keyboard set by `setxkbmap` in my initialization scripts. However, if I issue a command-line to change the input engine, as in:

```
$ ibus engine rime
```

it disregards my `setxkbmap` and uses the engine keymaps instead, so my `caio_us` is gone =/

**Comment by fujiwarat** [comment]
Sorry, I forgot `ibus` command runs `setxkbmap`.

**Comment by cagprado** [comment]
> Sorry, I forgot ibus command runs setxkbmap.

I see! Do you think it should? I’d rather have it consistent with the global configurarion.

Cheers

**Comment by fujiwarat** [comment]
Attaching the patch.
[ibus-xx-ibus-use-sys-layout.txt](https://github.com/ibus/ibus/files/1409632/ibus-xx-ibus-use-sys-layout.txt)

If I could notice the issue, it should be integrated in 1.5.17.

**Comment by cagprado** [comment]
It happens =P hahaha…

Thank you!

**Comment by cagprado** [comment]
> Attaching the patch.
> ibus-xx-ibus-use-sys-layout.txt

I confirm that the patch solved the problem! Thank you again! =)
