### ISSUE TITLE
Compile Release 1.5.17 Error: undefined reference to symbol 'g_type_check_instance_is_a' in Ubuntu

### ISSUE THREAD

**Issue by huadong** [ibus/ibus#1952]
Souce code : commit 4f9fa092924b75084b3b9e3fc368d0744db8ad2a   

CCLD     emoji-parser
/usr/bin/ld: emoji_parser-emoji-parser.o: undefined reference to symbol 'g_type_check_instance_is_a'
//usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:865: recipe for target 'emoji-parser' failed
make[4]: *** [emoji-parser] Error 1

**Comment by huadong** [comment]
#1954

**Comment by fujiwarat** [comment]
Thank you for the patch and I have a question.
How did your libtool work?

```
% rpm -q libtool
libtool-2.4.6-20.fc27.x86_64

% make V=1
/bin/sh ../libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -O0  -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o emoji-parser emoji_parser-emoji-parser.o  -lglib-2.0  libibus-1.0.la  
libtool: link: gcc -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -g -O0 -Wl,-z -Wl,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -o .libs/emoji-parser emoji_parser-emoji-parser.o  ./.libs/libibus-1.0.so -lgio-2.0 -lgobject-2.0 -lglib-2.0

% grep dependency_libs= libibus-1.0.la 
dependency_libs=' -lgio-2.0 -lgobject-2.0 -lglib-2.0'
```

I.e. $(emoji_parser_LDADD) includes $(libibus) and $(libibus) is libibus-1.0.la and libtool pulls -lgobject-2.0

I wonder why you got your compile error.

**Comment by huadong** [comment]
> lsb_release -a
> 
> Distributor ID:	Ubuntu
> Description:	Ubuntu 17.10
> Release:	17.10
> Codename:	artful

> gcc --version
> gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0

> apt show libtool
> Package: libtool
> Version: 2.4.6-2

> ./autogen.sh --prefix='/usr' --sysconfdir='/etc' --libdir='/usr/lib' --enable-gtk-doc --enable-wayland --enable-python-library

```
gcc -DHAVE_CONFIG_H -I. -I..  -DG_LOG_DOMAIN=\"IBUS\" -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -pthread -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DIBUS_CACHE_DIR=\""/usr/var/cache/ibus"\" -DIBUS_DATA_DIR=\"/usr/share/ibus\" -DIBUS_DISABLE_DEPRECATION_WARNINGS -DIBUS_COMPILATION -DISOCODES_PREFIX=\"/usr\" -DX11_DATA_PREFIX=\"/usr\"  -DENABLE_EMOJI_DICT  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2 -MT emoji_parser-emoji-parser.o -MD -MP -MF .deps/emoji_parser-emoji-parser.Tpo -c -o emoji_parser-emoji-parser.o `test -f 'emoji-parser.c' || echo './'`emoji-parser.c
mv -f .deps/emoji_parser-emoji-parser.Tpo .deps/emoji_parser-emoji-parser.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2   -o emoji-parser emoji_parser-emoji-parser.o  -lglib-2.0 libibus-1.0.la  

libtool: link: gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -o .libs/emoji-parser emoji_parser-emoji-parser.o  -lglib-2.0 ./.libs/libibus-1.0.so
/usr/bin/ld: emoji_parser-emoji-parser.o: undefined reference to symbol 'g_type_check_instance_is_a'
//usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: error adding symbols: DSO missing from command line
```

**Comment by fujiwarat** [comment]
> /bin/bash ../libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2   -o emoji-parser emoji_parser-emoji-parser.o  -lglib-2.0 libibus-1.0.la  

I'm attaching the libtool.txt of `/bin/bash -x ../libtool  --tag=CC   --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include  -g -O2   -o emoji-parser emoji_parser-emoji-parser.o  -lglib-2.0 libibus-1.0.la >& libtool.txt`

It gets $dependency_libs by func_source() and assigns $deplibs with $dependency_libs and finally gets `libs=' libibus-1.0.la -lgio-2.0 -lgobject-2.0 -lglib-2.0'`

Could you compare my libtool.txt and yours?
I wonder if you could run libtoolize before you run autoreconf and configure.

**Comment by fujiwarat** [comment]
[libtool.txt](https://github.com/ibus/ibus/files/1425912/libtool.txt)

**Comment by huadong** [comment]
Smart!

the main different is: 
> link_all_deplibs=no

`/bin/bash -x ../libtool --tag=CC --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -o emoji-parser emoji_parser-emoji-parser.o -lglib-2.0 libibus-1.0.la >& libtool2.txt`

[libtool2.txt](https://github.com/ibus/ibus/files/1426005/libtool2.txt)

my libtool script:
[libtool.sh.txt](https://github.com/ibus/ibus/files/1426008/libtool.sh.txt)

If I change the option link_all_deplibs=unknow or yes, it works. 
But I don't know how to change this option when generate libtool script: 
link_all_deplibs=...

**Comment by fujiwarat** [comment]
Even I modified link_all_deplibs locally, my libtool works fine.

Seems your libtool was modified:
```
--- libtool     2017-10-30 15:49:36.883242365 +0900
+++ libtool.sh.txt      2017-10-30 16:17:58.061326741 +0900
@@ -8385,19 +8393,19 @@ func_mode_link ()
 	    # It is a libtool convenience library, so add in its objects.
 	    func_append convenience " $ladir/$objdir/$old_library"
 	    func_append old_convenience " $ladir/$objdir/$old_library"
+	    tmp_libs=
+	    for deplib in $dependency_libs; do
+	      deplibs="$deplib $deplibs"
+	      if $opt_preserve_dup_deps; then
+		case "$tmp_libs " in
+		*" $deplib "*) func_append specialdeplibs " $deplib" ;;
+		esac
+	      fi
+	      func_append tmp_libs " $deplib"
+	    done
 	  elif test prog != "$linkmode" && test lib != "$linkmode"; then
 	    func_fatal_error "'$lib' is not a convenience library"
 	  fi
-	  tmp_libs=
-	  for deplib in $dependency_libs; do
-	    deplibs="$deplib $deplibs"
-	    if $opt_preserve_dup_deps; then
-	      case "$tmp_libs " in
-	      *" $deplib "*) func_append specialdeplibs " $deplib" ;;
-	      esac
-	    fi
-	    func_append tmp_libs " $deplib"
-	  done
 	  continue
 	fi # $pass = conv

```

The part was pulled from $IBUS_BUILD/ltmain.sh
I got http://ftp.gnu.org/gnu/libtool/libtool-2.4.6.tar.xz and $IBUS_BUILD/ltmain.sh and libtool-2.4.6/build-aux/ltmain.sh is same.

**Comment by huadong** [comment]
Fixed after install **libgirepository1.0-dev**. It should be in system requirements?

Thank you! @fujiwarat 

Build options:
  Version                       1.5.17
  Install prefix                /usr
  Build shared libs             yes
  Build static libs             no
  CFLAGS                        -g -O2
  PYTHON                        /usr/bin/python
  PYTHON2                       /usr/bin/python2
  Gtk2 immodule dir             /usr/lib/gtk-2.0/2.10.0/immodules
  Gtk3 immodule dir             /usr/lib/gtk-3.0/3.0.0/immodules
  Build gtk2 immodule           yes
  Build gtk3 immodule           yes
  Build XIM agent server        yes
  Build wayland support         yes
  Build appindicator support    yes (enabled, use --disable-appindicator to disable)
  Build appindicator engine icon yes
  Build python library          yes
  Build gconf modules           no (disabled, use --enable-gconf to enable)
  Build memconf modules         no
  Build dconf modules           yes (enabled, use --disable-dconf to disable)
  **Build introspection           yes**
  IBus-1.0.gir scannerflags     "--warn-all --identifier-prefix=IBus --symbol-prefix=ibus"
  Build vala binding            yes
  Build document                yes
  Build UI                      yes (enabled, use --disable-ui to disable)
  Build engine                  yes (enabled, use --disable-engine to disable)
  Enable key snooper            yes
  No snooper regexes            "firefox.*,.*chrome.*,.*chromium.*,terminator"
  Panel icon                    "ibus-keyboard"
  Enable surrounding-text       yes
  Enable libnotify              yes (enabled, use --disable-libnotify to disable)
  Enable Emoji dict             yes (enabled, use --disable-emoji-dict to disable)
  Unicode Emoji directory       /usr/share/unicode/emoji
  CLDR annotation directory     /usr/share/unicode/cldr/common/annotations
  Run test cases                yes

**Comment by fujiwarat** [comment]
I think you closed another bug.

**Comment by huadong** [comment]
@fujiwarat Sorry. install `libgirepository1.0-dev` will not fix this bug. I found that I just compiled my forked code which patched with   #1954 .
I digged the source of libtool-bin in ubuntu, debian had patched the libtool and set `link_all_deplibs=no`.
This is the patch from libtool-bin of ubuntu: [link_all_deplibs.patch.txt](https://github.com/ibus/ibus/files/1426842/link_all_deplibs.patch.txt)

Any modification of configure.ac can be made to be compatiable with ubuntu?

**Comment by huadong** [comment]
compile under ubuntu 17.10: 

- change **link_all_deplibs** from `link_all_deplibs=no` to `link_all_deplibs=unknow` of file $IBUS_BUILD/libtool before make.

_OR_ 
- using path #1954

**Comment by fujiwarat** [comment]
I ported [the Ubuntu patch](https://github.com/ibus/ibus/files/1429510/libtool-2.4.6.diff.txt) to libtool 2.4.6 and works fine when I run `/bin/bash -x ../libtool --tag=CC --mode=link gcc -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -o emoji-parser emoji_parser-emoji-parser.o -lglib-2.0 libibus-1.0.la` even if link_all_deplibs=no and the log is [here](https://github.com/ibus/ibus/files/1429514/libtool.log.txt).

The $IBUS_BUILD/libtool is changed [a little](https://github.com/ibus/ibus/files/1429515/libtool.diff.txt).

I think the change of https://github.com/ibus/ibus/issues/1952#issuecomment-340366852 is your root cause.

I'm fine to integrate your patch but I'd like to know the root cause and why the change was applied.
My libtool is [libtool.txt](https://github.com/ibus/ibus/files/1429525/libtool.txt).

**Comment by fujiwarat** [comment]
Did you confirm my point?

**Comment by fujiwarat** [comment]
> Here, someone discuss the libtool behavior...

It's not my point.
As I replied, my libtool works even if link_all_deplibs=no and your libtool was modified in other parts as I pointed.

**Comment by huadong** [comment]
Yes. You are right!

I think there is a switch here:
```
libs="$deplibs %DEPLIBS%"
test "X$link_all_deplibs" != Xno && libs="$libs $dependency_libs"
 ;;
```
Accord to your comment #1952, your libtool maybe ignore the function of this switch in some case.
So Debian patch it.

**Comment by fujiwarat** [comment]
Sorry, I overrided your comment by mistake.
https://github.com/ibus/ibus/issues/1952#issuecomment-343384665 is now my comment.

**Comment by fujiwarat** [comment]
As I noted, link_all_deplibs=no is not your problem.

```
libs="$deplibs %DEPLIBS%"
test "X$link_all_deplibs" != Xno && libs="$libs $dependency_libs"
 ;;
```

This part is also pased in my libtool with `bash -x`:
```
+ case $pass in
+ libs=' libibus-1.0.la -lgio-2.0 -lgobject-2.0 -lglib-2.0 %DEPLIBS%'
+ test Xno '!=' Xno
```

It means the above $delibs is already `libibus-1.0.la -lgio-2.0 -lgobject-2.0 -lglib-2.0`.

> Accord to your comment #1952, your libtool maybe ignore the function of this switch in some case.

No, I think my libtool does not ignore those lines in my test. I think your root cause is the patch in https://github.com/ibus/ibus/issues/1952#issuecomment-340366852 .
Did you compare my libtool in https://github.com/ibus/ibus/issues/1952#issuecomment-340651805 and yours and also take the diff?

**Comment by huadong** [comment]
Sorry. I think the switch is here for _linkmode=prog_: **line 8556** in your libtool.
```
	if test prog = "$linkmode" && test link != "$pass"; then
...
	  linkalldeplibs=false
	  if test no != "$link_all_deplibs" || test -z "$library_names" ||
	     test no = "$build_libtool_libs"; then
	    linkalldeplibs=:
	  fi
...
	    # Need to link against all dependency_libs?
	    if $linkalldeplibs; then
	      deplibs="$deplib $deplibs"
	    else
	      # Need to hardcode shared library paths
	      # or/and link against static libraries
	      newdependency_libs="$deplib $newdependency_libs"
	    fi
...
	fi # $linkmode = prog...
```
But when _$pass=conv_, this code in your libtool break the rules of option **link_all_deplibs**:
```
	if test conv = "$pass"; then
	  # Only check for convenience libraries
	  deplibs="$lib $deplibs"
	  if test -z "$libdir"; then
	    if test -z "$old_library"; then
	      func_fatal_error "cannot find name of link library for '$lib'"
	    fi
	    # It is a libtool convenience library, so add in its objects.
	    func_append convenience " $ladir/$objdir/$old_library"
	    func_append old_convenience " $ladir/$objdir/$old_library"
	  elif test prog != "$linkmode" && test lib != "$linkmode"; then
	    func_fatal_error "'$lib' is not a convenience library"
	  fi
	  tmp_libs=
	  for deplib in $dependency_libs; do
	    deplibs="$deplib $deplibs"
	    if $opt_preserve_dup_deps; then
	      case "$tmp_libs " in
	      *" $deplib "*) func_append specialdeplibs " $deplib" ;;
	      esac
	    fi
	    func_append tmp_libs " $deplib"
	  done
	  continue
	fi # $pass = conv
```
The definition of $pass is here:
```
    case $linkmode in
    lib)
	passes="conv dlpreopen link"
	for file in $dlfiles $dlprefiles; do
	  case $file in
	  *.la) ;;
	  *)
	    func_fatal_help "libraries can '-dlopen' only libtool libraries: $file"
	    ;;
	  esac
	done
	;;
    prog)
	compile_deplibs=
	finalize_deplibs=
	alldeplibs=false
	newdlfiles=
	newdlprefiles=
	passes="conv scan dlopen dlpreopen link"
	;;
    *)  passes="conv"
	;;
    esac
```
The patch of Debian removes this hard-coding when $linkmode=prog, and leaves it only for $linkmode=lib.

**Comment by huadong** [comment]
I think Debian have done two jobs:

1. Fix the bug of libtool: Ignore the option **link_all_deplibs**.
2. Set the default value of option  **link_all_deplibs** to _no_.

**Comment by fujiwarat** [comment]
> Sorry. I think the switch is here for linkmode=prog: line 8556 in your libtool.

Again, your code also does not use those lines.

**Comment by fujiwarat** [comment]
```
+ dependency_libs='  -lgio-2.0 -lgobject-2.0 -lglib-2.0'
+ test lib,link = prog,conv
+ test prog,scan = prog,conv
+ test prog '!=' prog
+ test conv = conv
+ deplibs='libibus-1.0.la -lglib-2.0 '
+ test -z /usr/lib64
+ test prog '!=' prog
+ continue
+ test link = conv
+ dependency_libs=
```

After updating dependency_libs, your libtool also skips those lines with `continue` and go to 'test link =' line and skips link_all_deplibs  lines but the way of updating dependency_libs, is wrong in your libtool.
Not sure why you still don't read my evaluation.

**Comment by huadong** [comment]
In my analysis, modify only one line in my libtool will ignore the option link_all_deplibs.
diff -u libtool libtool.hardcode 
```
--- libtool	2017-11-13 17:34:44.840325706 +0800
+++ libtool.hardcode	2017-11-13 17:36:31.801667348 +0800
@@ -8564,6 +8564,7 @@
 		 ;;
 	    esac
 	    # Need to link against all dependency_libs?
+	    deplibs="$deplib $deplibs"
 	    if $linkalldeplibs; then
 	      deplibs="$deplib $deplibs"
 	    else
```
I had read your evaluation, and I knew that the root cause is
```
--- libtool     2017-10-30 15:49:36.883242365 +0900
+++ libtool.sh.txt      2017-10-30 16:17:58.061326741 +0900
@@ -8385,19 +8393,19 @@ func_mode_link ()
 	    # It is a libtool convenience library, so add in its objects.
 	    func_append convenience " $ladir/$objdir/$old_library"
 	    func_append old_convenience " $ladir/$objdir/$old_library"
+	    tmp_libs=
+	    for deplib in $dependency_libs; do
...
```
which you had pointed out in the comment above.

I just want to figure out why Debian patched these codes.

**Comment by fujiwarat** [comment]
Do you mean the change of https://github.com/ibus/ibus/issues/1952#issuecomment-340366852 is a part of  the patch about  link_all_deplibs ?
Your patch https://github.com/ibus/ibus/files/1426842/link_all_deplibs.patch.txt does not include the root cause.
Can you point out the Debian internal patch likes https://code.launchpad.net/ubuntu ?

**Comment by huadong** [comment]
Maybe I make some mistake, I will do some research from beginning. I will come back soon.
Thank you for your patient.

**Comment by fujiwarat** [comment]
Thank you. I'm still interested in why your libtool was changed.

**Comment by huadong** [comment]
My libtool is from: [ubuntu office(install by apt)](https://launchpad.net/ubuntu/+source/libtool/2.4.6-2).
The patch code is from: [libtool_2.4.6-2.debian.tar.xz](https://launchpad.net/ubuntu/+archive/primary/+files/libtool_2.4.6-2.debian.tar.xz)
The patch is deplib_binary.patch. [Some mail archive about the deplib_binary.patch](https://www.mail-archive.com/libtool@gnu.org/msg11616.html)
The patch from [libtool 2.2.6a-4](https://tracker.debian.org/news/550996)

TBD...

**Comment by fujiwarat** [comment]
Sounds good.

What I'd asked was here.
> The patch is deplib_binary.patch. Some mail archive about the deplib_binary.patch

Seems the internal patch was added to work without .la files.
But when `env DT_RPATH=/usr/lib bash ../libtoo ...` does not work.
I confirmed the behavior can be switched with `m4_define([link_all_deplibs], [yes])` in configure.ac.

Try to integrate your patch.
