### ISSUE TITLE
我编制了一个“单手笔顺输入法”的码表，希望ibus输入法能加入这个功能，为Linux版和windows版电脑用户提供一个新的选择

### ISSUE THREAD

**Issue by YQ-YSY** [ibus/ibus#1957]
ibus输入法的开发者：
你们好！
我编制了一个“单手笔顺输入法”的码表，希望ibus输入法能加入这个功能，为Linux版和windows版电脑用户提供一个新的选择

开源项目网址： https://github.com/YQ-YSY/stroke-seq_MB
发布在Ubuntu论坛的帖子介绍：
http://forum.ubuntu.org.cn/viewtopic.php?f=35&t=484603

**Comment by fujiwarat** [comment]
I think your description is not an issue but an information.
I'd like to suggest to use a mailing list; https://groups.google.com/forum/#!forum/ibus-devel
If you're interested in the ibus enigne, you could refer https://github.com/ibus/ibus-tmpl
Seems your link provides Chinese dictionaries. CC'ing @epico

**Comment by epico** [comment]
Please consider to create one table file for ibus-table.

Maybe also create a new project for the table file.
