### ISSUE TITLE
ibus-daemon dies on USB disconnect

### ISSUE THREAD

**Issue by vivia** [ibus/ibus#1958]
Hi,

I am using ibus 1.5.14 under KDE on Debian sid. I noticed that ibus-daemon dies every time I disconnect and reconnect my keyboard. It doesn't seem to be a crash, I run it under gdb and gdb reports that the process exited normally. I tried running ibus-daemon -v but couldn't get any debug output.

Is this expected behaviour? It's inconvenient, to say the least, to have to restart ibus-daemon every time I need to plug my keyboard to another device.

**Comment by fujiwarat** [comment]
I think Plasma allows either IBus panel icon or Plasma panel icon and guess you effect that issue.
Could you confirm to remove all configurations in systemsettings5 -> "Input Devices" -> "Keyboard" -> "Layouts"

**Comment by vivia** [comment]
Thank you for your quick reply. Indeed, disabling the built-in KDE layouts stops ibus-daemon from exiting. However, I am not sure what the connection is, could you explain a bit better or link to an existing issue?

The problem is that I wouldn't like to permanently remove the xkb layouts. I have a different keyboard shortcut for these and for ibus layout switching, so in practice it means I have one keyboard shortcut to switch from English to Japanese and back (ibus), and one other to switch from English to Greek and back (xkb).

**Comment by fujiwarat** [comment]
I guess Plasma don't wish to show the both IBus and Plasma layout icons on the panel.
Plasma runs `ibus exit` if Plasma layout is enabled.

I think your problem can be resolved with ibus only using `ibus-setup`.
