### ISSUE TITLE
Disabling "Shift toggle Chinese Mode" makes duplicate punctuation

### ISSUE THREAD

**Issue by alone8172** [ibus/ibus#1960]
## issue
The problem just like the title.
In setting --> Editing, uncheck "Shift toggle Chinese Mode".
Typing punctuation marks like ```：```, ```，```, ```。``` by holding shift and press the key.
There presents two punctuation marks that I type.
In action, that is: 
1. hold shift
2. press key <:>
3. ```：：``` present on screen

## my setting 
- Chi
- halt
![image](https://user-images.githubusercontent.com/29729024/32598067-aaa9bc68-c573-11e7-8908-43f33f3d37cf.png)
![image](https://user-images.githubusercontent.com/29729024/32598097-bfb4c4ae-c573-11e7-8f62-a753dfd8cbd8.png)
![image](https://user-images.githubusercontent.com/29729024/32598110-c89c26ca-c573-11e7-889c-c5872b713b21.png)

**Comment by fujiwarat** [comment]
Which Chinese engine did you use?
You can check the current engine with `ibus engine` command.
And please report it to the engine's issue tracker instead of the ibus core tracker.
https://github.com/ibus/ibus/wiki/BugReport
