### ISSUE TITLE
1.5.17: Compose key not working in KKC

### ISSUE THREAD

**Issue by Jimi-James** [ibus/ibus#1965]
Info:
Arch Linux x64
XFCE
Related packages that did not update anytime recently:
ibus-kkc 1.5.22
libkkc 0.3.5
libkkc-data 0.2.7

Specifically after I upgraded ibus and libibus from 1.5.16 to 1.5.17, and specifically when I set ibus' input mode via its tray icon to Japanese (not when I'm in English US mode), the compose key does nothing. I have it set to compose:ralt, and I don't know if this issue is specific to ralt or not.

Also, one weird bit: on my laptop, which also runs Arch Linux and the same versions of everything and the same home folder (at least as far as anything related to ibus is concerned), I could workaround the issue by unplugging the keyboard, plugging it back in, and re-assigning the compose key to ralt, though that would only fix it for a certain amount of time before it stopped working again. On my desktop, that does not fix it at all.

On both, using the English US input mode is a working workaround, but I'd like to stay in the Japanese mode, because it's much easier to switch between the alphabets with hotkeys, and its "Direct Input" mode was identical to English mode, for me, until this issue popped up.

**Comment by fujiwarat** [comment]
IBus does not change the XKB option settings in the desktop so you need to register the XKB options in your desktop.
AFAIK, XFCE does not provide such a mechanize.
So normally I save the options in $HOME/.Xkbmap
```
cat .Xkbmap
-option compose:ralt
```

**Comment by Jimi-James** [comment]
I think you may have misread my report? I know how to register XKB options in my desktop. I've been doing it with the setxkbmap command rather than an .Xkbmap file, so I'll go ahead and test this with that file as well, but I'm not saying that IBus makes XCompose not work at all. I'm saying that it makes XCompose not work when I'm in KKC's input mode, specifically, and that this behavior showed up when I upgraded ibus and libibus to 1.5.17. I don't know if this regression is ibus' fault or an upstream bug, in X perhaps, that ibus has exposed, but since I'm not a developer of either project, I'm not a great candidate to figure that out.

**Comment by fujiwarat** [comment]
Since you're described about XKB options, I explained it.
I don't think ibus-kkc implements XKB.
ibus-anthy works fine with XKB. 
Note ibus no longer fall back to gtk-im-context-simple since 1.5.17.

**Comment by Jimi-James** [comment]
Oh, wow, anthy is a lot better in every way, too. The last time I tried to use it was 3 years ago. I don't remember what made me pick kkc over it, but whatever it was, it must not be true anymore.
