### ISSUE TITLE
[Feature Request] Keyboard shortcut supports modifier keys only combination for switching between language input

### ISSUE THREAD

**Issue by anjari** [ibus/ibus#1966]
In Windows, I can use shortcut like `<Ctrl>` + `<Shift>` or `<Shift>` + `<Alt>` to switch between IME. With Ibus, it seems this can't be done, I have to combine with a key code, e.g. `<Ctrl>` + `<Shift>` + `<Space>` or such.

I wonder if you can make Ibus Preference to be able to support modifier key combinations only ?

---

Also, a small issue on the fonts. I'm using antergos linux (arch linux based) with cinnamon desktop and screen resolution 1920x1080. I found the candidate words shown are very small by default. So I increased the font size to 14 in Ibus Preference. However it also increase the font size on Ibus tray icon's context menu.

**Comment by fujiwarat** [comment]
You can set the shortcut keys using gsetting command directly.
```
% gsettings get org.freedesktop.ibus.general.hotkey triggers
['<Alt>Shift_L']
```
It's a limitation of GTK.

**Comment by fujiwarat** [comment]
> So I increased the font size to 14 in Ibus Preference. However it also increase the font size on Ibus tray icon's context menu.

Yes, all the size should be changed.

**Comment by anjari** [comment]
I did try:

`gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt>Shift_L']"`

and

`gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt><Shift>']"`

The shortcut keys was registered in Ibus Preference, however when I pressed `Alt + Shift`, the IME switch didn't work at all. So it seems Ibus engine itself doesn't support modifier key combination only. Can you confirm this to be true?

---

> Yes, all the size should be changed.

Can you separate them ? It doesn't make sense for the tray icon's contect menu text font to be affected by the candidate words font.

**Comment by fujiwarat** [comment]
> gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt><Shift>']"

It's not correct. As I noted, should be ``<Alt>Shift_L``

> The shortcut keys was registered in Ibus Preference, however when I pressed Alt + Shift

Did you confirm your Shift key has Alt modifiers with xev command.

> Can you separate them ? 

I don't think to change the preedit only but also lookup window, icon size and panel menus. The IBus setting is for desktops which does not have the font settings.

**Comment by anjari** [comment]
Here is the result:
```
$ gsettings set org.freedesktop.ibus.general.hotkey triggers <Alt>Shift_L
bash: Alt: No such file or directory

$ gsettings set org.freedesktop.ibus.general.hotkey triggers "<Alt>Shift_L"
unknown keyword:
  <Alt>Shift_L
   ^          
$ gsettings set org.freedesktop.ibus.general.hotkey triggers '<Alt>Shift_L'
unknown keyword:
  <Alt>Shift_L
   ^          
```
nothing works. 

I think the `gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Alt>Shift_L']"` command is the correct one, but as I said before, despite it's saved in the preference but the shortcut key doesn't work at all.

> Did you confirm your Shift key has Alt modifiers with xev command.

Can you show how to do this? I'm not familiar with linux command.

---

> I don't think to change the preedit only but also lookup window, icon size and panel menus. The IBus setting is for desktops which does not have the font settings.

I don't understand what are you saying, but perhaps you misunderstood me. Here is the screenshot of the candidate words small fonts issue on my laptop display (1920x1080): https://i.imgur.com/gvxFaQn.png (here I'm still using the default font size).

Then I enabled the custom font in settings to "Sans Regular 14". The candiate words size now looks bigger, however the tray icon's context menu text is getting bigger too: https://i.imgur.com/f1osAk5.png

**Comment by fujiwarat** [comment]
> command is already correct, 

I meant your `<Alt><Shift>` is not correct and `<Alt>Shift_L` is right.

> Can you show how to do this? I'm not familiar with linux command.

Just run `xev` command and check the window shows your Shift_L has the modifier state correctly.

**Comment by fujiwarat** [comment]
Remeber `<Alt>Shift_L` means Alt->Shift but not Shift->Alt.

**Comment by anjari** [comment]
Here is the result of xev for `<Alt>Shift_L` shortcut:

```
KeymapNotify event, serial 37, synthetic NO, window 0x0,
    keys:  2   0   0   0   0   0   4   0   1   0   0   0   0   0   0   0   
           0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   

KeyPress event, serial 37, synthetic NO, window 0x5000001,
    root 0x146, subw 0x0, time 109614, (171,-15), root:(1032,442),
    state 0x8, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x146, subw 0x0, time 109782, (171,-15), root:(1032,442),
    state 0x9, keycode 64 (keysym 0xffe7, Meta_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

KeyRelease event, serial 37, synthetic NO, window 0x5000001,
    root 0x146, subw 0x0, time 109821, (171,-15), root:(1032,442),
    state 0x1, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

**Comment by fujiwarat** [comment]
>     state 0x8, keycode 50 (keysym 0xffe1, Shift_L), same_screen YES,

Seems it's well configured. Your Shift_L has the Alt modifier.
Do you mean  only `<Alt>Shift_L` does not work?
When you configure `<Super>space` with `ibus-setup` command, does it work for you?

**Comment by anjari** [comment]
> Do you mean only `<Alt>Shift_L` does not work?

Any modifier keys only combination don't work, like `Ctrl + Shift` too.

> When you configure `<Super>space` with ibus-setup command, does it work for you?

I don't know how to use ibus-setup. But on Ibus preference UI, I set `Super + Space` shortcut key and it doesn't work when I pressed it. I also tried `Super + n` too and make sure it doesn't conflict with cinnamon's global shortcut, and it doesn't work too. I think `Super` combination shortcut don't work with Ibus.

**Comment by fujiwarat** [comment]
I guess you encounter a Cinnamon specific problem.
It's strange any shortcut keys does not work for you.

How about the following workaround?
https://github.com/ibus/ibus/issues/1874#issuecomment-259625488

**Comment by anjari** [comment]
> It's strange any shortcut keys does not work for you.

It's not entirely correct, `Alt + Shift + Space` works or any modifier key + normal key combination works. Only `Super` combination and modifier keys only combination that don't work. I don't care about Super combination so it doesn't matter if it doesn't work, I only want modifier key only combination to work, since in Windows I'm already getting used to use `Alt + Shift`.

> How about the following workaround?
> #1874 (comment)

I got error:

```
$ ibus-daemon --xim &
[1] 2052
Can not execute default panel program```

**Comment by fujiwarat** [comment]
Do you mean `<Alt><Shift>space` and `<Control>space` works but `<Alt>Shift_L` and `<Super>space` do not work?

> Can not execute default panel program

It's an expected result and why ibus-ui-gtk3.orig runs by manual.
The workaround does not work for your short cut keys?

**Comment by fujiwarat** [comment]
`<Super>space` means Windows key -> space key.

**Comment by anjari** [comment]
I know.

**Comment by fujiwarat** [comment]
I cannot reproduce your `<Alt>Shift_L` issue in Fedora which uses cinnamon 3.6.6 and ibus 1.5.17.

Regarding to `<Super>space` issue, probably I know it. Super->space does not work but Super->space->space works fine, I.e. while pressing Super key, the second space key can show IBus switcher window, which would be a bug in Cinnamon.

**Comment by anjari** [comment]
I'm also using Ibus v1.5.17. So perhaps it's Antergos (or perhaps Arch Linux) issue ?

**Comment by fujiwarat** [comment]
I'd ask you if your problem can happen with a new user account instead of the current user one.
And also ask you to check other desktop environments; XFCE or TWM + tint2

**Comment by anjari** [comment]
Yes, on second user account it works which is really strange. Then I checked again the first user account, I found out pressing `Alt + Shift + Shift` works. So I'm suspicious there is global shortcut key that interferes. I checked the shortcut key settings and found out the culprit, the "Copy screenshot of window to clipboard" shortcut key is set to "Alt_L", so this shortcut key interferes with the Ibus shortcut key. 

I remember I did press `Alt + Printscreen` on the key capture when modifying the copy screenshot shortcut key, but it seems there is a bug in cinammon that it can't capture `Alt + Printscreen` and instead it only captures the `Alt` key only. So that solves the `Alt + Shift` issue mystery in Ibus.

Now I got new issue that I can't set Alt + Printscreen shortcut for the Copy Screenshot. However I found out I can modify the setting directly wiht dconf editor. For anyone who got same issue, here is the Copy Screenshot shortcut key setting location in dconf: `/org/cinnamon/desktop/keybindings/media-keys/window-screenshot-clip`. To set it with `Alt + Printscreen`, the value is `['<Alt>Print']`.

**Comment by fujiwarat** [comment]
> Yes, on second user account it works which is really strange.

Then your issue would be caused by the user settings.

>  Then I checked again the first user account, I found out pressing Alt + Shift + Shift works. 

It's the similar issue with `<Super>space` so I guess your settings have some `<Alt>` binding.
My understanding is `<Super>space` issue is that cinnamon binds `<Super>` key for the desktop menu and cinnamon cannot distinguish `<Super>+alpha` and `<Super>` so if you change the shortcut key of `<Super>`, `<Super>space` will works for IBus.

Anyway it's a bug in cinnamon.

**Comment by anjari** [comment]
Nope, I think the `Alt + Shift + Shift` works because by holding the `Alt + Shift` first, it will keep registering the Alt key while the Copy Screenshot is only triggered once, then when pressed Shift key, it will invoke the ibus switch. While pressing `Alt + Shift` once doen't work because it triggers the Copy Screenshot instead.
