### ISSUE TITLE
ibus-setup fails when in a virtual environment (no shebang)

### ISSUE THREAD

**Issue by Trevortds** [ibus/ibus#1967]
When in a virtual environment, or if a python environment manager like Conda is installed, ibus-setup fails with 

```
trevor@tulkas:~$ ibus-setup
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 31, in <module>
    from gi import require_version as gi_require_version
  File "/home/trevor/anaconda3/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to `'print'
```

If the script is being run as an executable, it needs a shebang, or if it's being called by some other script, it needs an explicit call to `/usr/bin/python` rather than relying on shell's `python` which is variable as per the official Python spec.

**Comment by Trevortds** [comment]
I fixed it locally by editing /usr/bin/ibus-setup line 23 from 

```
exec python /usr/share/ibus/setup/main.py $@
```

to 

```
exec /usr/bin/python /usr/share/ibus/setup/main.py $@
```

But I can't find where this goes in the source repo

**Comment by fujiwarat** [comment]
You can select the path with `./configure --with-python=/usr/bin/python`
