### ISSUE TITLE
ui-gtk3 + AppIndicator: cannot hide tray icon using "Show icon on system tray" option

### ISSUE THREAD

**Issue by ftake** [ibus/ibus#1970]
On Plasma 5 (with AppIndicator), users cannot hide IBus tray icon by disabling on ibus-setup. This problem does not reproduce with traditional X11  system tray icon.

Reprocudibility:
Not always. Once I confirmed but currently I cannot reproduce for now.

Environment:
- openSUSE Tumbleweed
- IBus 1.5.17
- Plasma 5.11.3

Reference:
- openSUSE Bug Report: https://bugzilla.opensuse.org/show_bug.cgi?id=1068806

**Comment by fujiwarat** [comment]
Seems the problem happens in Fedora 27 (Plasma workspace 5.10.5) when XDG auto start launch ibus-daemon.
Fedora uses imsettings to launch ibus-daemon.

![plasma](https://user-images.githubusercontent.com/105929/34143397-e06dd2f0-e4cf-11e7-8121-3c84a8dc03d2.png)

The interesting GUI is to show the ordered IME icons; Anthy icon, input mode icon, dict icon.
And the right click menu has "Hide IBus" which can hide the IBus icon.
If you'd like to always hide the IBus icon,  we need to modify Plasma desktop.
In systemsettings5 -> Input Devices -> Layouts , 
I think the "Show layout indicator" check button could hide IBus icon and it's out of the control from ibus-setup.

You said KIM panel in the SuSE report but I'm not sure if the icon is relative with KIM panel.

After you run `ibus exit` and `ibus-daemon` again by manual, the ibus original GUI can appear.

Myself works for Qt5 but I'm not familiar with Plasma source codes.
Please file a bug for Plasma panel instead.

**Comment by ftake** [comment]
It's KIM panel (KDE IM Panel plasma widget), an alternative of ibus-ui-gtk3. It is implemented in the similar way with IBus GNOME keyboard.

KIM panel have not been well implemented yet. It should provide configuration dialogs like GNOME settings and still use ibus-setup.

BTW, under plasma 5 with KIM panel enabled, KIM panel starts IBus daemon. We need to stop XDG autostart/imsettings. It launch IBus daemon with --panel=/path/to/kimpanel-ibus-panel. I guess on Fedora 27, two IBus panels (kimpanel-ibus-panel and ibus-ui-gtk3) is running on Plasma 5.

At first, I thought I confirmed a problem with ibus-ui-gtk3. However, the original reporter seems to use KIM panel, and I cannot confirm this with ibus-ui-gtk3 anymore. So let's close this bug as "Not a bug".
