### ISSUE TITLE
gconf is required for build

### ISSUE THREAD

**Issue by yegortimoshenko** [ibus/ibus#1971]
https://github.com/ibus/ibus/blame/master/data/dconf/Makefile.am#L54

`gsettings-schema-convert` is in GConf package. That means it's impossible to build IBus without having GConf installed even when configured with `--disable-gconf`.

**Comment by fujiwarat** [comment]
Even if you call `--disable-gconf`, you need to install `gsettings-schema-convert` for ibus build but you don't need it for ibus runtime.
It would be a limitation until we remove gconf in IBusConfig because we don't wish to maintain both ibus.schemas.in and org.freedesktop.ibus.gschema.xml.in .

**Comment by yegortimoshenko** [comment]
Sure!
