### ISSUE TITLE
PYTHON2_PREFIX and PYTHON2_VERSION expanded at autoconf time

### ISSUE THREAD

**Issue by yegortimoshenko** [ibus/ibus#1972]
https://github.com/ibus/ibus/blob/1.5.17/configure.ac#L461

It should be instead evaluated at configure script runtime.

**Comment by fujiwarat** [comment]
I don't think so.
PYTHON2_PREFIX constructs pkgpython2dir and pkgpython2dir is the install path of ibus/*.py .
