### ISSUE TITLE
IBus on LXC not working

### ISSUE THREAD

**Issue by 1wxyz** [ibus/ibus#1974]
There is a problem when typing Chinese characters on GUI applications loaded from LXC container.
I have bind mount X11 socket to the container which when I switch keyboard on host machine (Super + space) from English to other keyboard, example Thai, Vietnamese. It works. For keyboards based on ibus (Chinese, Korean, Japanese). It will not work.

Is there a way for me to pass the ibus socket to the container?

**Comment by fujiwarat** [comment]
I don't try LXC but I guess the XKB settings are shared between the host and guests.
But IBus key events are processed between ibus-daemon in host and ibus clients in guests using DBus methods but not sockets.
You could consider Flatpak instead.
Sorry probably we have no resources to investigate LXC.
