### ISSUE TITLE
Compose key is broken with some inputs

### ISSUE THREAD

**Issue by Jehan** [ibus/ibus#1976]
I mapped the compose key to CapsLock (using GNOME tweak tool, which AFAIK sets the X option 'compose:caps'). That works fine for many inputs, but not for Ibus Hangul (when in non-hangul mode of course). This means I cannot output composed character (like 'œ' with Compose-o-e) anymore with this input, forcing me to switch to another input (this is extremely bothersome especially since ibus-hangul can otherwise perfectly output latin characters).

This used to work in Fedora 25 and stopped working since Fedora 26 (and still not working in Fedora 27). Looking at the repository for these, Fedora 25 had ibus 1.5.14, and both Fedora 26 and 27 have ibus 1.5.16.

Note that I am not sure which software is the actual culprit. I've tried libxkbcommon but they sent me to xkeyboard-config (and it doesn't look like this is the problem either). Ibus-hangul is likely not the issue since the same version (ibus-hangul 1.5.0) has been used since Fedora 25, and development is apparently quite slow.

So I am thinking that the change may have happened in ibus.
Could you confirm this? And if so, could it be fixed? :-)
Thanks!

**Comment by fujiwarat** [comment]
ibus-hangul has never implemented compose feature.
You could use other XKB engines. ibus-anthy also implement compse features.
The different between Fedora 25 and Fedora 26, probably ibus no longer inherits gtk-im-context-simple but use IBusEngine only.

**Comment by Jehan** [comment]
@fujiwarat I am not saying it has ever implemented the compose feature. But this feature is implemented in X and used to work fine through ibus-hangul. I should know, I have used this for years, and so has my wife, until we upgraded and it broke. ;-(

We both need to write regularly both in Korean and in French, which is why we were using such a setup. Originally we used to switch engines but we realized that staying with with the same engine and simply switching in and out of hangul mode is more effective for frequent switching.

We only sometimes switch to other engines, for instance when we need to write in Japanese (sometimes we need to; by the way, the compose key works fine in ibus-anthy with the Latin input mode!) but like staying in Ibus-Hangul otherwise.

>  The difference between Fedora 25 and Fedora 26 means, probably ibus no longer inherits gtk-im-context-simple but use IBusEngine only.

Could you tell me what it means with more details? I am a developer and don't mind the technical talk and in particular if that means that a patch may be possible. In which case, I'd be interested to know into which software I have to look into to look for a patch (which I may try to make myself if I figure out what is what). Is it in ibus or some other component that I should work? In ibus-hangul specifically?

What would be the required implementation to be done?

**Comment by fujiwarat** [comment]
> What would be the required implementation to be done?

ibus-hangul needs to inherit IBusEngineSimple if Compose key is needed.

**Comment by Jehan** [comment]
Thanks! I could patch upstream at ibus-hangul.

**Comment by fujiwarat** [comment]
Great to see the patch.
