### ISSUE TITLE
PT-layout on debian-live-stretch-9.3-xfce

### ISSUE THREAD

**Issue by githubcamel** [ibus/ibus#1978]
This is what happens with the portuguese -> portuguese input-method on the 
distro debian-live-stretch-9.3-xfce:

I' ve just restarted the distro and open a xfce4-terminal:
é :     I can write this character "é" with accent ...so far everything' s good !

But now I right-click the mouse button over ibus-daemon button (language-button) on the panel of the desktop and press "Quit":
When I restart again ibus-daemon executing it in the xfce4-terminal and try to write the same character with accent the accent key starts working separately from the "e" key which means what appears on screen is ´e

**Comment by fujiwarat** [comment]
Probably I think the focus is left when you restart ibus-daemon.
How about clicking desktop and clicking xfce4-terminal again?

**Comment by fujiwarat** [comment]
Any updates?
