### ISSUE TITLE
ibus-setup: ModuleNotFoundError: No module named 'gi'

### ISSUE THREAD

**Issue by AJNOURI** [ibus/ibus#1984]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 

> Distributor ID:	Debian
> Description:	Debian GNU/Linux 8.9 (jessie)
> Release:	8.9
> Codename:	jessie

Which desktop environment and version?: 

> echo $XDG_CURRENT_DESKTOP
> XFCE

Which session type?: 

> $ echo $XDG_SESSION_TYPE

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

> Any app

IBus version?: 
(Run `ibus version`)

> IBus 1.5.9

Issue description:
**Cannot configure ibus to add a new language neither from GUI nor CLI:**

> $ ibus-setup
> Traceback (most recent call last):
>   File "/usr/share/ibus/setup/main.py", line 31, in <module>
>     from gi.repository import GLib
> ModuleNotFoundError: No module named 'gi'

Steps to reproduce:
1. "ibus-setup" fails
1.  "right click on ibus language icon > Preference" --> nothing happens

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

> $ ibus exit
> $ 
> (ibus-daemon:8662): GLib-WARNING **: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). Most likely the process is ignoring SIGCHLD, or some other thread is invoking waitpid() with a nonpositive first argument; either behavior can break applications that use g_child_watch_add()/g_spawn_sync() either directly or indirectly.
> 
> [1]+  Done                    ibus-daemon --xim
> $ 
> $ ibus-daemon --xim &
> [1] 8693
> $ 
> $ ibus-setup
> Traceback (most recent call last):
>   File "/usr/share/ibus/setup/main.py", line 31, in <module>
>     from gi.repository import GLib
> ModuleNotFoundError: No module named 'gi'

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

> $ ibus-daemon --xim --verbose &
> [1] 8762
> $ 
> (ibus-ui-gtk3:8767): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

> yes

------------
Tried to install **python3-gi** without success

> $ sudo apt install python-gi python3-gi
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> python-gi is already the newest version.
> python3-gi is already the newest version.
> 0 upgraded, 0 newly installed, 0 to remove and 280 not upgraded.

**Comment by fujiwarat** [comment]
I don't know Debian packages.
Can you check the file content of /usr/bin/ibus-setup which python2 or python3 is used?

You could check where your python search the path with strace command.
```
% cat a.py
from gi.repository import GLib
% strace python3 a.py |& grep gi | grep __init__.py | head
stat("/usr/lib64/python2.7/site-packages/gi/__init__.py", {st_mode=S_IFREG|0644, st_size=5998, ...}) = 0
openat(AT_FDCWD, "/usr/lib64/python2.7/site-packages/gi/__init__.py", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib64/python2.7/site-packages/gi/__init__.pyc", O_RDONLY) = 4
```

**Comment by AJNOURI** [comment]
Thans for your reply @fujiwarat 

> cat /usr/bin/ibus-setup
> 
> prefix=/usr
> exec_prefix=${prefix}
> datarootdir=${prefix}/share
> libexecdir=/usr/lib/ibus
> export IBUS_PREFIX=/usr
> export IBUS_DATAROOTDIR=${prefix}/share
> export IBUS_LOCALEDIR=/usr/share/locale
> export IBUS_LIBEXECDIR=${libexecdir}
> exec python3 /usr/share/ibus/setup/main.py $@

> $ echo "from gi.repository import GLib" > a.py
> $ cat a.py 
> fom gi.repository import GLib
> $ strace python3 a.py |& grep gi | grep __init__.py | head
> {no output}

**Comment by fujiwarat** [comment]
Did you install `strace`?

You can try `strace python3 a.py |& grep gi` instead.

**Comment by AJNOURI** [comment]
`$ strace python3 a.py |& grep gi`

> getegid()                               = 1000
> getgid()                                = 1000
> read(3, "from gi.r", 9)                 = 9
> read(3, "from gi.repository import GLib\n", 4096) = 31
> read(4, "from gi.repository import GLib\n", 4096) = 31
> read(3, "from gi.repository import GLib\n", 8192) = 31
>     from gi.repository import GLib
> ModuleNotFoundError: No module named 'gi'

**Comment by fujiwarat** [comment]
Did you check your script is correct running it without strace?

> fom gi.repository import GLib

Not correct.

> getegid() = 1000
> getgid() = 1000
> read(3, "from gi.r", 9) = 9
> read(3, "from gi.repository import GLib\n", 4096) = 31
> read(4, "from gi.repository import GLib\n", 4096) = 31
> read(3, "from gi.repository import GLib\n", 8192) = 31
> from gi.repository import GLib
> ModuleNotFoundError: No module named 'gi'

Is it really all the log? If yes, your python is something broken.

Did you check the content of the packages python-gi and python3-gi?

**Comment by AJNOURI** [comment]
From python2, it looks OK
![selection_002_27_02](https://user-images.githubusercontent.com/1716020/36734056-b5551c74-1bd2-11e8-945d-bf86a80c1270.jpg)

But not on python3
![selection_003_27_02](https://user-images.githubusercontent.com/1716020/36734052-b2396e78-1bd2-11e8-85c6-b67063d5b7a1.jpg)

Eventhough both packages installed 
```
$ sudo apt install python-gi python3-gi
Reading package lists... Done
Building dependency tree
Reading state information... Done
python-gi is already the newest version.
python3-gi is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 280 not upgraded.
```

**Comment by fujiwarat** [comment]
> From python2, it looks OK

I don't ask this kind of test.

> Eventhough both packages installed

I don't ask the installation but asked the content of the packages python-gi and python3-gi.
Did you check the file list in each package?

**Comment by fujiwarat** [comment]
Did you check the package contents?

**Comment by a-eid** [comment]
I'm facing this issue?

**Comment by vivisl** [comment]
`$ sudo nano /usr/bin/ibus-setup
`

datarootdir=${prefix}/share
libexecdir=/usr/lib/ibus
export IBUS_PREFIX=/usr
export IBUS_DATAROOTDIR=${prefix}/share
export IBUS_LOCALEDIR=/usr/share/locale
export IBUS_LIBEXECDIR=${libexecdir}
exec python3 /usr/share/ibus/setup/main.py $@

Modify "python3" to "python2" in the last line and run `$ ibus-setup` will work fine

**Comment by fujiwarat** [comment]
You should check the content of `python3-gi` in which file are included. Probably I think the package name is not right for your purpose.
