### ISSUE TITLE
Persian or Farsi Language 

### ISSUE THREAD

**Issue by mrrb0t** [ibus/ibus#1985]
Hello 

I also want to mention if you can add the persion / farsi language would be good thanks 

Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 
(Run `ibus version`)

Issue description:

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
I think you mean a farsi translation.
If you can contribute the translation, you can send the PO file to [Fedora L10N](https://fedoraproject.org/wiki/L10N/Translate_on_Zanata) or this issue.
To create POT file:
```
% git clone https://github.com/ibus/ibus.git
% cd ibus/po
% intltool-update -p
% ls *.pot
```
Myself have no connection with each language translator but I always check Fedora translations before I release a new version.
