### ISSUE TITLE
Can you re-use translations from CLDR?

### ISSUE THREAD

**Issue by Jibec** [ibus/ibus#1986]
Hi there,

this commit introduced many many new strings to translate: https://github.com/ibus/ibus/commit/73b420f49ba54b6eac74fb59cb3af948f3a592d6

Most of them are really technical categories of Unicode tables, languages names, etc.
It really isn't interesting to translate, isn't easy to translate, and looks like to be content that could be found in CLDR. Any hope to take translation from there directly?

I don't know much of CLDR, I juste hope it may work :p

**Comment by fujiwarat** [comment]
> Most of them are really technical categories of Unicode tables

The new translations are category names only. 

> It really isn't interesting to translate

No, I'm interested in the category translations.
I grepped cldr directory but no translations for categories.

Did you see the comment in msgid how to translate them?

**Comment by Jibec** [comment]
Yes, I noticed the comment after creating this issue. I'm not sure how to extract the pot from Zanata, but I assume it should be possible.
-- 
Jean-Baptiste Holcroft

**Comment by fujiwarat** [comment]
If you see Zanata ibus page, Click "head" -> Click "Document" -> Click an arrow button in "ibus10" -> Choose "Download this document [.pot]".
Or I use zanata-cli command line.

Probably I think gucharmap has no link in Zanata. So you could get the tarball or donwload source dir with git command line directly.
```
% git clone git://git.gnome.org/gucharmap
% cd gucharmap/po
% intltool-update -p
```
