### ISSUE TITLE
ibus-setup fails to run

### ISSUE THREAD

**Issue by Vintodrimmer** [ibus/ibus#1987]
Which distribution and version?: 
Void Linux

Which desktop environment and version?: 
bspwm 0.9.3

Which session type?: 
X11

Which application and version?: 
N/A

IBus version?: 
IBus 1.5.17

Issue description:
```
➤ ibus-setup
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 33, in <module>
    from gi import require_version as gi_require_version
  File "/home/eichhorn/.local/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
```

If I change `exec /usr/bin/python /usr/share/ibus/setup/main.py $@` to `exec /usr/bin/python2 /usr/share/ibus/setup/main.py $@`, the error changes to

```
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 33, in <module>
    from gi import require_version as gi_require_version
ImportError: cannot import name require_version

```

Steps to reproduce:
1. Install iBus
1. run `ibus-setup`

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
```
(ibus-dconf:3863): dconf-WARNING **: unable to open file '/etc/dconf/db/ibus': Datei »/etc/dconf/db/ibus« konnte
nicht geöffnet werden: open() ist gescheitert: Datei oder Verzeichnis nicht gefunden; expect degraded performance

(ibus-ui-gtk3:3865): IBUS-WARNING **: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:3865): IBUS-WARNING **: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:3865): IBUS-WARNING **: Emoji dict does not exist: /usr/share/ibus/dicts/emoji-en.dict
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

**Comment by fujiwarat** [comment]
>   File "/home/eichhorn/.local/lib/python3.6/site-packages/gi/__init__.py", line 39
>     print url

Your python3 file is not correct. I think you added the `print` line by yourself.

>     from gi import require_version as gi_require_version
> ImportError: cannot import name require_version

python2 also has require_version in gi/__init__.py. I think you didn't install gi module for python2.

**Comment by Vintodrimmer** [comment]
Why did you close this unresolved issue?
>Your python3 file is not correct. I think you added the print line by yourself.

I didn't add anything. How do I fix it?

>I think you didn't install gi module for python2.

```
➤ pip2 show gi
Name: gi
Version: 1.2
Summary: Command line to private gist. Example: gi.py myFile
Home-page: http://github.com/inconditus/gi
Author: Edward Wang
Author-email: edward.auc@gmail.com
License: MIT
Location: /home/eichhorn/.local/lib/python2.7/site-packages
Requires: requests
```

```
➤ pip2 install --user gi
Requirement already satisfied: gi in ./.local/lib/python2.7/site-packages
Requirement already satisfied: requests in ./.local/lib/python2.7/site-packages (from gi)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in ./.local/lib/python2.7/site-packages (from requests->gi)
Requirement already satisfied: idna<2.7,>=2.5 in ./.local/lib/python2.7/site-packages (from requests->gi)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./.local/lib/python2.7/site-packages (from requests->gi)
Requirement already satisfied: certifi>=2017.4.17 in ./.local/lib/python2.7/site-packages (from requests->gi)
```

**Comment by fujiwarat** [comment]
> Why did you close this unresolved issue?

Because it's your installation failure. I still can answer your question but this is not a bug.

> I didn't add anything. How do I fix it?

It would be good to delete all and install again.

> pip2 install --user gi

Did you confirm your python can refer gi directory in the user directory?

Also you have to rebuild ibus after install the custom directory.
I'd suggest to install the ibus & python packages which are provided by your distribution if you don't understand the installation. I.e. all directories exists in /usr/share but not $HOME/.local

**Comment by Vintodrimmer** [comment]
> Because it's your installation failure

Fair enough,

>It would be good to delete all and install again.

Reinstalled iBus, Python3 `gi` and Python2 `gi`, but nothing changed.

>Did you confirm your python can refer gi directory in the user directory?

I can import it from the interactive console and work with it if that's what you mean. But the same errors persist.

```
➤ pip2 show gi
Name: gi
Version: 1.2
Summary: Command line to private gist. Example: gi.py myFile
Home-page: http://github.com/inconditus/gi
Author: Edward Wang
Author-email: edward.auc@gmail.com
License: MIT
Location: /home/eichhorn/.local/lib/python2.7/site-packages
Requires: requests

➤ pip show gi
Name: gi
Version: 1.2
Summary: Command line to private gist. Example: gi.py myFile
Home-page: http://github.com/inconditus/gi
Author: Edward Wang
Author-email: edward.auc@gmail.com
License: MIT
Location: /home/eichhorn/.local/lib/python3.6/site-packages
Requires: requests

➤ python2
Python 2.7.14 (default, Mar  7 2018, 16:47:17)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
>>> from gi import require_version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name require_version

➤ python
Python 3.6.4 (default, Mar  7 2018, 16:47:37)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eichhorn/.local/lib/python3.6/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(t url)?
```

It seems that `require version` is not part of `gi` in Python2?

>I'd suggest to install the ibus & python packages which are provided by your distribution if you don't understand the installation.

iBus is from the repository provided by my distribution, as is Python2/3. `gi` module is not available in the repository, so I installed it with `pip`.

**Comment by fujiwarat** [comment]
> iBus is from the repository provided by my distribution, as is Python2/3

If you can get ibus from your distro, I think your distro should provide gi too.
It's good to ask your distro.

>   File "/home/eichhorn/.local/lib/python3.6/site-packages/gi/__init__.py", line 39
>     print url

I don't think that gi is python3. I don't know how to find the python3 gi with pip but I guess the package name would not be 'gi'.
https://download.gnome.org/sources/pygobject/

**Comment by bamboospirit** [comment]
I'm having exactly the same issue!

**Comment by pabloab** [comment]
I had this problem [with other Python program](https://github.com/silverjam/Sysmods/issues/3#issuecomment-389298840). Maybe related to [Anaconda](https://anaconda.org/anaconda/python)?

I think this issue should be reopened. Is not clear if ibus can do something to avoid the problem.

```
pablo ~ $ which python
/home/pablo/anaconda3/bin/python
pablo ~ $ python -V
Python 3.6.4 :: Anaconda, Inc.
```

**Comment by fujiwarat** [comment]
> I had this problem with other Python program. Maybe related to Anaconda?

You can specify the python path with configure option in ibus build.

**Comment by Cbhihe** [comment]
Exactly same issue here as described in OP on Arch linux. 

Motivation: I want to run `ibus-setup` to correct what I believe is the key binding CTRL-SHIFT-E being hijacked by my GTK apps (Firefox + LibreOffice) to produce a emoji-picker window. 

Reproduce with: 
```
$ ibus-setup
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 33, in <module>
    from gi import require_version as gi_require_version
ModuleNotFoundError: No module named 'gi'

```

**Comment by TrinhDinhPhuc** [comment]
Please Open again this issue. I am getting exactly this error

**Comment by fujiwarat** [comment]
There are nothing to do for your problem in upstream.
You don't install the `gi` package and you need to ask your distribution which package includes it.

**Comment by alexanderdurr** [comment]
Solution I found was here: https://unix.stackexchange.com/questions/473231/no-module-named-gi-when-running-ibus-setup/630552
Just run export PATH=/usr/bin:$PATH in the terminal so that the system python is used. After that the command ibus-setup should work.
