### ISSUE TITLE
value error when trying to create database for custom input method

### ISSUE THREAD

**Issue by dylanjewel** [ibus/ibus#1989]
Which distribution and version?: 
Linux Mint 18.3

Which desktop environment and version?: 
Cinammon 3.6.7

IBus version?: 
1.5.11

Issue description:
I am trying to create an input method called "palibhasa". I've done this before. 

When I run...
sudo ibus-table-createdb -n usr/share/ibus-table/tables/palibhasa.db -s palibhasa.txt

I get...

Traceback (most recent call last):
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 397, in <module>
    main ()
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 324, in main
    phrases = phrase_parser ( table)
  File "/usr/share/ibus-table/engine/tabcreatedb.py", line 227, in phrase_parser
    xingma, phrase, freq = l.strip().split('\t')[:3]
ValueError: not enough values to unpack (expected 3, got 1)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

**Comment by fujiwarat** [comment]
@dylanjewel Can you reply on https://github.com/mike-fabian/ibus-table/issues/5 ?
