### ISSUE TITLE
Atom flatpak failed to trigger ibus, after adding and loading im-ibus.so

### ISSUE THREAD

**Issue by cheese** [ibus/ibus#1991]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 26.
Flatpak Atom based on source from flathub. io.atom.electron.BaseApp patched with

```
diff --git a/io.atom.electron.BaseApp.json b/io.atom.electron.BaseApp.json
index cea28b0..1766256 100644
--- a/io.atom.electron.BaseApp.json
+++ b/io.atom.electron.BaseApp.json
@@ -23,7 +23,6 @@
         {
             "name": "gtk2",
             "cleanup": [
-              "/bin",
               "/share/gtk-2.0",
               "/lib/gtk-2.0/include"
             ],
@@ -229,6 +228,53 @@
                     "dest-filename": "autogen.sh"
                 }
             ]
+        },
+        {
+            "name": "ibus",
+            "config-opts": ["--disable-xim", "--disable-static", "--disable-dconf", "--disable-schemas-compile", "--disable-unicode-dict",
+                            "--disable-setup", "--disable-ui", "--disable-engine", "--disable-libnotify", "--disable-emoji-dict",
+                            "--disable-appindicator", "--disable-tests"],
+            "cleanup": [
+                "/bin", "/libexec", "/share/bash-completion", "/share/dbus-1",
+                "/share/icons", "/share/man", "/share/ibus", "/lib/gtk-3.0" ],
+            "post-install": [ "gtk-query-immodules-2.0 --update-cache" ],
+
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://github.com/ibus/ibus/releases/download/1.5.18/ibus-1.5.18.tar.gz",
+                    "sha256": "8551f7d027fb65d48225642fc8f3b232412ea75a4eb375244dd72a4d73c2639e"
+                }
+            ]
+        },
+        {
+            "name": "extra-cmake-modules",
+            "cleanup-platform": ["*"],
+            "config-opts": ["-DENABLE_TESTING=OFF", "-DCMAKE_INSTALL_LIBDIR=lib"],
+            "cmake": true,
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://download.kde.org/stable/frameworks/5.39/extra-cmake-modules-5.39.0.tar.xz",
+                    "sha256": "b80536d7bed8c12fc492857d3d433b3859462402fe231e463efcd3bf44ffbcd1"
+                }
+            ]
+        },
+        {
+            "name": "fcitx",
+            "config-opts": ["-DENABLE_QT=Off", "-DENABLE_PINYIN=Off", "-DENABLE_TABLE=Off", "-DENABLE_GIR=Off", "-DENABLE_GTK3_IM_MODULE=Off",
+                            "-DENABLE_OPENCC=Off", "-DENABLE_CAIRO=Off", "-DENABLE_SPELL=Off", "-DENABLE_GTK2_IM_MODULE=On", "-DENABLE_LIBXML2=Off",
+                            "-DENABLE_X11=Off", "-DENABLE_ENCHANT=Off", "-DENABLE_PRESAGE=Off"],
+            "cleanup": ["/lib/fcitx", "/share", "/bin"],
+            "post-install": [ "gtk-query-immodules-2.0 --update-cache" ],
+            "cmake": true,
+            "sources": [
+                {
+                    "type": "archive",
+                    "url": "https://download.fcitx-im.org/fcitx/fcitx-4.2.9.5.tar.xz",
+                    "sha256": "9479cef9b66e53df0e874637d55759ec08a195cb8790513e133135d8e49ad911"
+                }
+            ]
         }
     ]
 }
```

Which desktop environment and version?: 
GNOME 3.24

Which session type?: 
X11

Which application and version?: 
atom 1.25.0

IBus version?: 
Host: ibus-1.5.17-6.fc26.x86_64
im-ibus.so in flatpak: 1.5.18

Issue description:
The current io.atom.Atom on flathub does not contain a im-ibus.so gtk2 module.
After I adding the im module with above patch to io.atom.electron.BaseApp, atom now loads im-ibus.so. But it still failed to trigger ibus.
If set GTK_IM_MODULE to xim, atom in flatpak can trigger ibus.
If atom installed in the host, atom can trigger ibus.
If run gtk-demo in the atom flatpak (flatpak run --command=gtk-demo   io.atom.Atom), gtk-demo loads im-ibus.so and can trigger ibus.

Steps to reproduce:
1. clone https://github.com/flathub/io.atom.electron.BaseApp.git https://github.com/flathub/io.atom.Atom
2. patch io.atom.electron.BaseApp
3. build and install io.atom.electron.BaseApp
4. build, install and run io.atom.Atom
5. try to trigger ibus

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
Not tried.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Not tried.

**Comment by fujiwarat** [comment]
You could refer https://github.com/ibus/ibus/blob/master/test/org.test.IBus.json
```
% flatpak-builder --force-clean app org.test.IBus.json
% flatpak-builder --run --nofilesystem=host app org.test.IBus.json zenity --entry
```

**Comment by fujiwarat** [comment]
> If set GTK_IM_MODULE to xim, atom in flatpak can trigger ibus.

It would not be an expected configuration because the GTK XIM module forwards the keyevents to ibus-x11. we should use GTK_IM_MODULE=ibus

**Comment by cheese** [comment]
Do you confirm this issue?

**Comment by fujiwarat** [comment]
No, I don't.
What is the Atom?
If it's an GTK3 application in GNOME, I think it can communicate with /usr/libexec/ibus-portal through the "org.freedesktop.portal.IBus" Bus name. So I provided the test application for you if you verify the general applications works fine in Flatpak.
If it's a desktop environment, it needs to accept the "org.freedesktop.portal.IBus" Bus name.

**Comment by cheese** [comment]
Atom is https://atom.io/ . It is based on electron that uses gtk2.
As I said, the 'gtk-demo' application works but not for Atom.

**Comment by fujiwarat** [comment]
I checked out https://github.com/atom/atom.git but I cannot grep gtk.

**Comment by cheese** [comment]
It seems we need to investigate how to make Chromium to support IBus portal. Atom is based Electron framework, which is based on Chromium.

**Comment by cheese** [comment]
I tested Fcitx for the same case and there is no such issue.

**Comment by fujiwarat** [comment]
OK, I got time to evaluate this issue.
Actually I verified the pure electron applications works fine with ibus under https://github.com/flathub/io.atom.electron.BaseApp .

E.g. Electron JavaScript:
```
function createWindow () {
  win = new electron.BrowserWindow({ width: 800, height: 800 })
  win.loadURL(url.format({
    pathname: path.join(__dirname, 'electron.html'),
    protocol: 'file:',
    slashes: true
  }))
  win.on('closed', () => {
    win = null
  })
}
```
E.g. the electron.html file:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello, world!</title>
  </head>
  <body>
    <textarea name="textarea" cols=30 rows=3>test</textarea>
  </body>
</html>
```

Then seems Atom and Slack have a special handling with gtk3.
After I investigated Atom, it seems the Atom GTK client cannot get the key events with gtk_key_snooper_install() but always get them with ibus_im_context_filter_keypress(). 
In that case, ibus gtk clients had a bug to check the DBUs activity in Flatpak.

Now I fixed it in ibus upstream and the fix needs to be integrated to the Flatpak platofrm, E.g. org.freedesktop.[Platform|Sdk], org, org.gnome.Platform

**Comment by fujiwarat** [comment]
Reported https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/681
