### ISSUE TITLE
切换输入法后托盘图标没有变化

### ISSUE THREAD

**Issue by yangdaweihit** [ibus/ibus#1992]
Which distribution and version?: 
Debian GNU/Linux 9 (stretch)

Which desktop environment and version?: 
XFCE 4.12

Which session type?: 
X11

IBus version?: 
IBus 1.5.14

Issue description:

When I  switch input mode between Chinese and English with `Left Space`, the icon in the tray does not change accordingly into English or Chinese, saying `五`. I believe this is tiny bug for so beautiful ibus.

BTW, how could I change icon in the tray for wubi input method? Thank you for your concerning my question.

**Comment by fujiwarat** [comment]
ibus-anthy and ibus-libpinyin can change the status icon by the input mode.

Which ibus engine do you use?
You can check the current engine with `ibus engine` command.

**Comment by yangdaweihit** [comment]
`xkb:us::eng`

my costumed input method is wubi

**Comment by fujiwarat** [comment]
> xkb:us::eng

I don't think xkb:us::eng is your engine. Your engine should be table:wubi-jidian86
Enable your engine and run `ibus engine` command.

> 是否可以将所有输入法的图标设计为统一风格，或可由用户自己配置。

Not sure why you tried to write the same thing in Chinese.

> 个人感觉五笔输入法中的那个红字五有点难看。

Probably it would be a different bug. Please submit a issue for  ibus-table-chinese instead of ibus core.

Your icon by input mode is a bug in ibus-table.

You can confirm the behavior to modify main.py
```
# cp /usr/share/ibus-table/engine/main.py /usr/share/ibus-table/engine/main.py.orig
# vi /usr/share/ibus-table/engine/main.py
# diff -urNp /usr/share/ibus-table/engine/main.py.orig /usr/share/ibus-table/engine/main.py
--- /usr/share/ibus-table/engine/main.py.orig	2018-03-23 15:48:17.471440383 +0900
+++ /usr/share/ibus-table/engine/main.py	2018-03-23 15:49:40.284391116 +0900
@@ -274,6 +274,9 @@ def main():
             _setup = SubElement (_engine, 'setup')
             _setup.text = setup_arg
 
+            _icon_prop_key = SubElement (_engine, 'icon_prop_key')
+            _icon_prop_key.text = 'InputMode'
+
         # now format the xmlout pretty
         indent (egs)
         egsout = tostring (egs, encoding='utf8').decode('utf-8')

# exit
% rm $HOME/.cache/ibus/bus/registry
% ibus restart
```
