### ISSUE TITLE
'org.freedesktop.ibus.general.panel' is not installed

### ISSUE THREAD

**Issue by hykwok1** [ibus/ibus#1999]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
BLFS 8.2

Which desktop environment and version?: 
LXDE

Which session type?: 
X11

Which application and version?: 
None

IBus version?: 
1.5.18

Issue description:
After execute the command "ibus read-config", it reports "'org.freedesktop.ibus.general.panel' is not installed" and then stop. 
I have cheked the source codes and find that "/tools/main.vala" is changed in order to fix "Do not change keymaps with 'use-system-keyboard-layout' ":
from "org.freedesktop.ibus.general.hotkey" to "org.freedesktop.ibus.general.panel" 
However, the file "/data/ibus.schemas.in" is not changed.

Steps to reproduce:
1. ibus read-config

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

**Comment by fujiwarat** [comment]
You should install org.freedesktop.ibus.gschema.xml from the ibus build directory and run `glib-compile-schemas`.
See https://github.com/ibus/ibus/wiki/Install
