### ISSUE TITLE
font color in candidate panel

### ISSUE THREAD

**Issue by yangdaweihit** [ibus/ibus#2001]
Please fill in the following items if you don't know the root cause.

- Which distribution and version?: 
Ubuntu 16.04

- Which desktop environment and version?: 
Unity

- Which session type?: 
X11

- IBus version?: 
1.5.11

- Issue description:
My windows theme is dark, so I guess the candidate list panel shows black for this reason.
I cannot change the skin of ibus that the fonts in candidate panel shows black. 
![s](https://user-images.githubusercontent.com/10682606/38961856-19ef9140-439d-11e8-8182-8ce85317c3cc.jpg)

Can I change the font default color `black` to others such as `light gray`?

**Comment by fujiwarat** [comment]
I think that was enhanced since ibus 1.5.15 or later.
