### ISSUE TITLE
Can't connect through DBus anymore as of 1.5.18

### ISSUE THREAD

**Issue by Caagr98** [ibus/ibus#2003]
I would assume this is due to https://github.com/ibus/ibus/commit/bfe57d20e9d39d52428e95e493d9af0bd034a82f , which appears to have changed something in the DBus handling.

The following Python 3 code used to work in 1.5.17, but just gives a timeout error in .18:

```python
import dbus
import ctypes
dll = ctypes.CDLL("libibus-1.0.so")
get_addr = dll.ibus_get_address
get_addr.restype = ctypes.c_char_p

dbusconn = dbus.connection.Connection(get_addr())
ibus = dbus.Interface(dbusconn.get_object("org.freedesktop.IBus", "/org/freedesktop/IBus"), dbus_interface="org.freedesktop.IBus")
ic = dbus.Interface(dbusconn.get_object("org.freedesktop.IBus", ibus.CurrentInputContext()), dbus_interface="org.freedesktop.IBus.InputContext")
ic.PropertyActivate("InputMode.Hiragana", 1)
```

**Comment by fujiwarat** [comment]
I don't think other applications can modify the input modes freely for the security issue but each engine owns the state.
If you need any features, I think it would be better to integrate them in each engine.

**Comment by Caagr98** [comment]
In my case, it's a Vim plugin that disables the IME while in normal mode (since only ASCII characters are useful there).

Why does the DBus interface exist if we can't use it?

Even you decide not to revert that commit, would it be possible to make it return an error immediately rather than having to wait for timeout?

I guess [this xkcd](https://xkcd.com/1172/) describes the situation quite well.

**Comment by fujiwarat** [comment]
> In my case, it's a Vim plugin that disables the IME while in normal mode (since only ASCII characters are useful there).

You could disable IME to export XMODIFIERS=@im=none before you run a terminal emulator.

> Why does the DBus interface exist if we can't use it?

I may not understand your question. But the DBus owners can use the interface.

> Even you decide not to revert that commit, would it be possible to make it return an error immediately rather than having to wait for timeout?

OK, I could add an error but I'm not sure if any messages should be shown for the security issues.

**Comment by Caagr98** [comment]
> You could disable IME to export XMODIFIERS=@im=none before you run a terminal emulator.

That would disable the IME in the whole terminal, rather than only Vim normal mode. The IME is useful in, for example, insert mode or the shell.

> I may not understand your question. But the DBus owners can use the interface.

I might have misunderstood something, but I thought DBus interfaces usually existed to let people communicate with your program.

**Comment by fujiwarat** [comment]
> That would disable the IME in the whole terminal, rather than only Vim normal mode. The IME is useful in, for example, insert mode or the shell.

OK, probably I'd suggest your feature to integrate into ibus core and ibus may has an exception for a specific connection.

> I might have misunderstood something, but I thought DBus interfaces usually existed to let people communicate with your program.

The current authentication might be too strict for your application but I think it's not good to open the connection for any applications including malware.

**Comment by Caagr98** [comment]
> OK, probably I'd suggest your feature to integrate into ibus core and ibus may has an exception for a specific connection.

What do you mean?

> The current authentication might be too strict for your application but I think it's not good to open the connection for any applications including malware.

Yeah, I agree that security is important. I personally tend to value flexibility more, though. After all, both keyloggers and key injectors are fairly trivial to make (at least under X), so I don't really see how preventing people from manipulating the IME helps.

**Comment by fujiwarat** [comment]
> What do you mean?

ibus core is everything in ibus package and an authorized application might be integrated in ibus core for your usage. But the current restriction still is kept for any external applications.

>  so I don't really see how preventing people from manipulating the IME helps.

I think contributing each IME would be better than creating another applications to override the IME.
Seems your add-on feature is not implemented for an specific IME but actually it modifies the behavior of ibus core so it's good to contribute ibus core.

Why don't you switch a Japanese IME to an XKB engine likes `xkb:jp::jpn` with `Super-space` key after you launch vim?

**Comment by Caagr98** [comment]
> I think contributing each IME would be better than creating another applications to override the IME.

If you try to support every single usecase anyone's ever had, that would just turn into an unmaintainable pile of spaghetti. Sometimes it's better to communicate with external applications instead - especially since that makes it easier for more obscure programs to use the same functionality, since the APIs already exist.

> Why don't you switch a Japanese IME to an XKB engine likes `xkb:jp::jpn` with `Super-space` key after you launch vim?

Imagine having to disable the IME every time you wanted to use for example ctrl-C or arrow keys. That'd be terribly inconvenient. This is no different.

**Comment by Caagr98** [comment]
> I don't understand if you try to answer my question. I also don't understand the relation to disable IME and Ctrl-C.

I'm trying to explain why manually switching doesn't work.

In one mode (insert mode), input is inserted just as written. In that mode, passing input through the IME is useful.

In another mode (normal mode), the input is instead interpreted as commands. For example, `daw` deletes the word the cursor is on. In this mode, the IME is not useful, since the input is transformed into `だw`, which is meaningless.

Users switch between these two modes quite frequently, usually several times per minute.

Thus, I want to automatically disable the IME while in normal mode. In 1.5.17, that was easy to do with a DBus call (though a bit limited; the code up there is specialized for ibus-kkc). I don't really care how, but I'd appreciate some officially supported way to do the same.

**Comment by fujiwarat** [comment]
I'd suggest to use vim macros and ibus keybindings to create new shortcut keys instead of hacking IBusInputContext.

I also think your usage is not useful generally. E.g. I search or replace multi-byte characters with the vim normal mode.

**Comment by fujiwarat** [comment]
```
% cat $HOME/.vimrc
nmap <silent> <F4> :!ibus engine anthy<CR>i
imap <silent> <F5> <Esc>:!ibus engine xkb:us::eng<CR><CR>
```

This works with vim but not vi. Fedora vim-minimal.rpm provides vi and vim-enhanced provides vim.
If you need to change the input modes in each engines, it's better to ask the engine to add new shortcut keys of Esc and switching input modes.
