### ISSUE TITLE
Only the first input uses selected input method

### ISSUE THREAD

**Issue by codl** [ibus/ibus#2005]
Which distribution and version?: Arch Linux

Which desktop environment and version?: XFCE 4.12

Which session type?: X11

Which application and version?: All I've tested. Google Chrome, XTerm, Krita, Thunar...

IBus version?: 1.5.18. Downgrading to 1.5.17 fixes it so it's something new in 1.5.18

Issue description:

When ibus is first started, or when switching to a new input method, only the first keystroke (or the first word in input methods with a pre-edit window) uses the input method. After that, the ibus tray icon reverts to the default "keyboard with earth" icon and anything I type uses my system keymap. Also dead keys don't work.

Steps to reproduce:
1. Restart ibus, or switch to a new input method
1. Type something

Can you reproduce your problem when you restart ibus-daemon? (yes / no): Yes

Do you see any errors when you run ibus-daemon with the verbose option?: No, except for "No global engine"

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): Yes

**Comment by fujiwarat** [comment]
> Which application and version?: All I've tested. Google Chrome, XTerm, Krita, Thunar...

OK, I'd ask you a simple GTK3 applications at first. E.g. gedit.
When you run `env GTK_IM_MODULE=ibus gedit`, can you use input method engines?

**Comment by codl** [comment]
Nope, same behaviour. It did dump some error messages once I started typing:

```
$ env GTK_IM_MODULE=ibus gedit
(gedit:14096): IBUS-WARNING **: 10:31:16.634: Process Key Event failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code18: The connection is closed.
(gedit:14096): IBUS-WARNING **: 10:31:16.634: Process Key Event failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code18: The connection is closed.
(gedit:14096): IBUS-WARNING **: 10:31:16.634: Process Key Event failed: GDBus.Error:org.gtk.GDBus.UnmappedGError.Quark._g_2dio_2derror_2dquark.Code18: The connection is closed.
(gedit:14096): Gtk-WARNING **: 10:31:16.636: Calling org.xfce.Session.Manager.Inhibit failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Method "Inhibit" with signature "susu" on interface "org.xfce.Session.Manager" doesn't exis
```

**Comment by fujiwarat** [comment]
Can you reproduce your problem with "English" engine? If you set "English" engine, you will see "xkb:us::eng" with `ibus engine` command.

Can you show the following results?
```
% ps -ef | grep ibus | grep -v $USER
user 12697 10571  0 19:19 pts/0    00:00:00 ibus-daemon --xim
user 12707 12697  0 19:19 pts/0    00:00:00 /usr/libexec/ibus-dconf
user 12708 12697  0 19:19 pts/0    00:00:00 /usr/libexec/ibus-ui-gtk3
user 12711 12697  0 19:19 pts/0    00:00:00 /usr/libexec/ibus-extension-gtk3
user 12713  8170  0 19:19 pts/0    00:00:00 /usr/libexec/ibus-x11 --kill-daemon
user 12717  8170  0 19:19 ?        00:00:00 /usr/libexec/ibus-portal

% ls $HOME/.config/ibus/bus/
9673704605d44edd9b93f3751ba7a73f-unix-0

% cat $HOME/.config/ibus/bus/9673704605d44edd9b93f3751ba7a73f-unix-0 
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-33Uwecff,guid=2634d58753ffb46d5de9e01a5ae99097
IBUS_DAEMON_PID=12697

% ibus address
unix:abstract=/tmp/dbus-33Uwecff,guid=2634d58753ffb46d5de9e01a5ae99097
```

Also can you reproduce your problem with a new user account instead of the current user account?

**Comment by codl** [comment]
i found a way to reproduce this even in a new user account: if I don't have a key bound to the emoji chooser then this happens

**Comment by codl** [comment]
oh sorry i didn't answer any of your questions did I

* yes this happens with the english engine

```
$ ps -ef | grep ibus | grep -v $USER
(no output)

$ ls $HOME/.config/ibus/bus/
e8487ee4d40c44f8b798b5da13176c3e-unix-0
e8487ee4d40c44f8b798b5da13176c3e-unix-1
e8487ee4d40c44f8b798b5da13176c3e-unix-2

$ cat $HOME/.config/ibus/bus/*
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-Jn1msDLD,guid=f5bd099342b2828fba31322c5ae9c693
IBUS_DAEMON_PID=2990
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-560hxK7d,guid=f801a798e61131f82a40a0ac58aeda57
IBUS_DAEMON_PID=21587
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-e9bfwQFS,guid=934de6ddf6edf834e4f51fe8589527a9
IBUS_DAEMON_PID=26591

$ ibus address
unix:abstract=/tmp/dbus-Jn1msDLD,guid=f5bd099342b2828fba31322c5ae9c693
```

and, like mentioned above, yes, i can reproduce this on a new account if I unset the default keybind for the emoji chooser

**Comment by fujiwarat** [comment]
> $ ps -ef | grep ibus | grep -v $USER
> (no output)

It means you didn't run ibus-daemon.
You can reply my question in https://github.com/ibus/ibus/issues/2005#issuecomment-385933704 again after you run `ibus exit; rm $HOME/.config/ibus/bus/*; ibus-daemon`.

**Comment by fujiwarat** [comment]
Ah, sorry. I mistook the commands.
Please try:
```
% ps -ef | grep ibus | grep -v grep | grep $USER
% ls -l $HOME/.config/ibus/bus/
-rw-rw-r--. 1 user user 169 May 4 16:00 9673704605d44edd9b93f3751ba7a73f-unix-0
% cat $HOME/.config/ibus/bus/9673704605d44edd9b93f3751ba7a73f-unix-0
% ibus address
```

**Comment by codl** [comment]
```
$ ps -ef | grep ibus | grep -v grep | grep $USER
codl      2990     1  0 May02 ?        00:00:47 ibus-daemon -drx
codl      2996  2990  0 May02 ?        00:00:00 /usr/lib/ibus/ibus-dconf
codl      2998  2990  0 May02 ?        00:00:14 /usr/lib/ibus/ibus-ui-gtk3
codl      3003  2990  0 May02 ?        00:00:09 /usr/lib/ibus/ibus-extension-gtk3
codl      3007     1  0 May02 ?        00:00:01 /usr/lib/ibus/ibus-x11 --kill-daemon
codl      3010  2494  0 May02 ?        00:00:00 /usr/lib/ibus/ibus-portal
codl      3031  2990  0 May02 ?        00:00:10 /usr/lib/ibus/ibus-engine-simple
codl      3568  2990  0 May02 ?        00:00:03 /usr/bin/python3 /usr/share/ibus-uniemoji/uniemoji.py --ibus

$ ls -l $HOME/.config/ibus/bus/
total 12
-rw-r--r-- 1 codl codl 168 May  2 16:09 e8487ee4d40c44f8b798b5da13176c3e-unix-0
-rw-r--r-- 1 codl codl 169 Feb 23  2017 e8487ee4d40c44f8b798b5da13176c3e-unix-1
-rw-r--r-- 1 codl codl 169 Feb  4  2017 e8487ee4d40c44f8b798b5da13176c3e-unix-2

$ cat $HOME/.config/ibus/bus/*
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-Jn1msDLD,guid=f5bd099342b2828fba31322c5ae9c693
IBUS_DAEMON_PID=2990
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-560hxK7d,guid=f801a798e61131f82a40a0ac58aeda57
IBUS_DAEMON_PID=21587
# This file is created by ibus-daemon, please do not modify it
IBUS_ADDRESS=unix:abstract=/tmp/dbus-e9bfwQFS,guid=934de6ddf6edf834e4f51fe8589527a9
IBUS_DAEMON_PID=26591

$ ibus address
unix:abstract=/tmp/dbus-Jn1msDLD,guid=f5bd099342b2828fba31322c5ae9c693
```

i'm guessing I can probably get rid of `e8487ee4d40c44f8b798b5da13176c3e-unix-1` and `2`

**Comment by fujiwarat** [comment]
@rokezu Thank you.
I think the value of hotkey in org.freedesktop.ibus.panel.emoji was blank and if you run `gsettings reset org.freedesktop.ibus.panel.emoji hotkey`, your ibus engines works fine.

But @cold shows his engines are running so I'm not sure if they are the same issues.
Can @cold also run the gsettings command if your problem disappears?

**Comment by rokezu** [comment]
@fujiwarat Indeed running the gsettings command sets it again to "<Control><Shift>e" and the issue disappears, now I remember I had to remove that keyboard shortcut because it was the same combination used in other applications, such as "Export As..." in GIMP, which I use a lot more than emojis. 

It seems that if the setting isn't blank, it will work fine.  

I also had the exact same symptoms as @codl (Reverting tray icon, IBus crashing after first keystroke, compose key stopped working... ). 

Thanks!

**Comment by fujiwarat** [comment]
@rokezu Thank you for your help. I will fix your SEGV in ibusengine.c next week.

Awaiting @codl reply.

**Comment by codl** [comment]
for me as well, running that command resets the key binding to ctrl shift e and then everything works fine
