### ISSUE TITLE
Ctrl+A/selection overwriting behaves weird

### ISSUE THREAD

**Issue by rugk** [ibus/ibus#2013]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 28

Which desktop environment and version?: 
GNOME 3.28.2

Which session type?: 
Wayland

Which application and version?: 
e.g. gedit, but not Firefox (which runs as XWayland, so could be related to that)

IBus version?: 
IBus 1.5.18

Issue description:
See my original issue report at https://github.com/mike-fabian/ibus-typing-booster/issues/35

Steps to reproduce:
See my original issue report at https://github.com/mike-fabian/ibus-typing-booster/issues/35

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes, even system restart does not fix it

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
N/A

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
 by someone else, so likely not related to current account

**Comment by fujiwarat** [comment]
Your problem does not depends on Wayland but GtkTextView.
`Ctrl-a` on GtkEntry (E.g. gedit search or save dialog )works fine but GtkTextView (E.g. gedit text buffer) has your problem.
But If you select strings with `Shift-Left` on GtkEntry, you will also see your problem on GtkEntry too.
I think GTK3 needs to calculate the selection position with the pre-edit string. I.e. ibus-typing-booster uses preedit. ibus-anthy does not have this problem.

**Comment by rugk** [comment]
So does this issue need to be reported somewhere else, or can you fix it/workaround here somehow?

**Comment by mike-fabian** [comment]
GtkTextView needs  to be  fixed. I don‘t  think a workaround in ibus is possible.

The behaviour in GtkEntry is OK in my opinion.

Fujiwara  San said  he would file a bug report against GtkTextView.

**Comment by rugk** [comment]
> Fujiwara San said he would file a bug report against GtkTextView.

Okay, so @fujiwarat does so? Otherwise, one has to point me to the place where to actually report it…

**Comment by fujiwarat** [comment]
https://gitlab.gnome.org/GNOME/gtk/issues/1123
Probably I will close this issue later since it's a GTK issue.

**Comment by fujiwarat** [comment]
Only GTK4 has this fix.
