### ISSUE TITLE
visual studio code can not input chinese by ibus 

### ISSUE THREAD

**Issue by frogPeng** [ibus/ibus#2016]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: 
Ubontu 18.04

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
visual studio code 1.23.1

IBus version?: 
1.9.2

Issue description:
It can be input chinese in other application except "visual studio code", even input character when press "Shift".

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
ping
