### ISSUE TITLE
Overwrite occurs when using ibus+m17n+tamil99 combination in Gnome Applications

### ISSUE THREAD

**Issue by mohan43u** [ibus/ibus#2019]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Archlinux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 3.28.2

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
gedit 3.28.1

IBus version?: 
(Run `ibus version`)
IBus 1.5.18

Issue description:
Overwrite happens when using <any-gnome-application>+ibus+m17n+tamil99 combination. This issue not happening whenusing <non-gnome-application-like-firefox>+ibus+m17n+tamil99 combination

Steps to reproduce:
1. Go to gnome-settings-daemon->Region&Language->Input Sources->Add Input Source->Tamil->Tamil(tamil99(m17n))
2. Open gedit
3. Press window+space and switch to Tamil(tamil99(m17n))
4. Press "vihfhkf" keys, it will type "வக்ம்"
5. Open Firefox
6. In the address bar Press same "vihfhkf" keys, but this time it will correctly type "வனக்கம்"
7.In gedit (or any gnome application), "ன" and "க" characters gets overwritten

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
Thank you for the brief bug description.
The issue was caused because mutter sent reset() whenever ibus-m17n committed the preedit text and it's fixed in mutter upstream in https://gitlab.gnome.org/GNOME/mutter/commit/bd36764b4ddb5e7756904005eb11e23d2a5a55c1
