### ISSUE TITLE
鹋 should not be offered as a candidate character in traditional Chinese mode

### ISSUE THREAD

**Issue by patrickdark** [ibus/ibus#2022]
Which distribution and version?: Ubuntu 18.04
Which desktop environment and version?: ubuntu:GNOME (I don't know how to determine the version)
Which session type?: x11
IBus version?: 1.5.17
Issue description: "鹋" is offered as a candidate character when using the traditional mode of the "Chinese (Intelligent Pinyin)" input method with the input "miao" and "ermiao" ("鴯鶓"). Furthermore, it's suggested with higher priority than the traditional variant, "鶓".

**Comment by fujiwarat** [comment]
Please file to ibus-libpinyin
https://github.com/ibus/ibus/wiki/BugReport

**Comment by patrickdark** [comment]
@fujiwarat There is no "Issues" page for that repository (https://github.com/ibus/ibus-pinyin/issues/), so I'm not able to file a bug report at https://github.com/ibus/ibus-pinyin.

**Comment by patrickdark** [comment]
@fujiwarat I've refiled this issue at https://github.com/libpinyin/ibus-libpinyin/issues/136.
