### ISSUE TITLE
Hope Ibus can add the function of digital keypad input coding, for the Chinese character stroke input method I wrote.我希望ibus能添加数字小键盘输入编码的功能，因为我编写了一个汉字单手笔顺输入法

### ISSUE THREAD

**Issue by YQ-YSY** [ibus/ibus#2023]
Hope Ibus can add the function of digital keypad input coding, for the Chinese character stroke input method I wrote.
https://github.com/YQ-YSY/stroke-seq_MB

我希望ibus能添加数字小键盘输入编码的功能，因为我编写了一个汉字单手笔顺输入法

我编制了一个“单手笔顺输入法”的码表，希望您能在您正在开发的输入法中加入这个功能。（我不会编程） 其中已经包括了近3万汉字、15万核心词汇、150万扩展词汇，全部都是TXT文本码表（而且都带拼音）。

 笔顺的国家标准编码就是数字12345，我设计的六全码和精简码是0～9， 因此，“单手笔顺输入法”使用数字小键盘作为输入工具，不会与您开发中的输入法有冲突， 相反，两个输入法能成为互补关系，大大提高汉字输入效率。 用户不记得您的输入法时，就输入笔顺；用户不记得笔顺时，就输入您的输入法。

 “单手笔顺输入法”开源项目网址： https://github.com/YQ-YSY/stroke-seq_MB 
发布在Ubuntu论坛的帖子介绍： http://forum.ubuntu.org.cn/viewtopic.php?f=35&t=484603 

因为笔顺码有个优点，它和拼音一样，每个人在上小学时就已经学会了，不用背字根。 所以，继五笔、拼音之后，笔顺输入也许是汉字输入法的又一个重大的改进机会， 未来甚至可以替代拼音输入法，成为最主流的汉字输入法。

**Comment by fujiwarat** [comment]
I guess it could be in ibus-m17n or ibus-table.
CC'ing @epico to get which engine is better.

**Comment by epico** [comment]
Maybe ibus-table.

**Comment by fujiwarat** [comment]
@YQ-YSY 
I think there is nothing to help your issue in ibus core.
Probably you can consult @mike-fabian how to create an engine in ibus-table for your issue.
And @mike-fabian would not understand long Chinese sentences too unfortunately.

**Comment by fujiwarat** [comment]
@YQ-YSY 
Probably you could refer [the source code of ibus-table-stroke5](https://github.com/mike-fabian/ibus-table-chinese/blob/master/tables/stroke5/stroke5.txt)

**Comment by YQ-YSY** [comment]
@fujiwarat 
In the code table I designed, I use digital code.
For example, input 1234 can get Chinese text 'wood'. 
the more information, you can see:
https://github.com/mike-fabian/ibus-table/issues/7

ibus-table-stroke5 use letter keyboard input code, 
If I use it, the operation is very inconvenient, and efficiency was very low.
I have to use digital keypad input my code,
it can input Chinese text and word, only use one hand, fast and convenient.
