### ISSUE TITLE
Question: What API to use?

### ISSUE THREAD

**Issue by mominul** [ibus/ibus#2024]
I am an [IM developer](https://github.com/OpenBangla/OpenBangla-Keyboard). But I am somewhat confused what API of iBus I should use. The main provided API is http://ibus.github.io/docs/ibus-1.5/index.html but why the [template engine](https://github.com/ibus/ibus-tmpl/blob/master/src/engine.c) doesn't use it? Are there any overheads to use the provided API?

Thanks!

**Comment by fujiwarat** [comment]
The template engine uses IBusEngine class and ibus_engine_* APIs in the API doc.
