### ISSUE TITLE
Make it possible to change or disable shortcut Ctrl+Shift+U

### ISSUE THREAD

**Issue by VadimKulagin** [ibus/ibus#2025]
**Which distribution and version:** 
Ubuntu 18.04 (bionic)

**Which desktop environment and version:** 
GNOME Shell 3.28.2

**Which session type:** 
X11

**Which application and version:** 
PhpStorm 2018.2 EAP Build #PS-182.3458.35

**IBus version:** 
IBus 1.5.17

**Issue description:**
I just want to use the familiar shortcut Ctrl+Shift+U in the PhpStorm and I do not need to enter Unicode characters using this key combination.

Questions on the deactivation of this shortcut often appear on the Internet:

* https://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux
* https://superuser.com/questions/1332853/how-to-disable-ctrlshiftu-in-ubuntu-18-04
* https://askubuntu.com/questions/1004230/how-to-disable-unicode-composition-keyboard-shortcut-in-xubuntu-17-10
* https://askubuntu.com/questions/367646/is-it-possible-to-unbind-or-change-the-unicode-input-global-shortcut

And before there were ways to disable this feature by setting `none` as the input method in the system language settings, but with the release of Ubuntu 18.04 (and probably 17.10) this became impossible. 
People just want to use their usual shortcuts in the Eclipse, PhpStorm and other programs, but now they can not do it.

I tried all the methods of solving this problem listed under the links above, but they did not help. 
I even tried to make a crutch with `xdotool` and `xte` to simulate pressing this key combination and passing it to PhpStorm. But it turned out to be a very unstable and buggy solution. I described this here: https://superuser.com/a/1340350/549263

I think it's worth making it possible to change or disable this shortcut to enter Unicode characters, because not everyone needs it.
This can be done through a file in /etc, via gsettings or whatever you want.
But the current hardcode implementation seems to me not the best solution.

Please help to solve this problem.

**Steps to reproduce:**
1. Open the PhpStorm (or another IDE from JetBrains) and type some text in lowercase.
1. Put the cursor on this text.
1. Press Ctrl+Shift+U. This should change the case of the text. But instead, the input of the Unicode character appears.

**Can you reproduce your problem when you restart ibus-daemon? (yes / no):** 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

**Do you see any errors when you run ibus-daemon with the verbose option?:**
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
Did not try

**Can you reproduce your problem with a new user account instead of the current your account? (yes / no):** 
Did not try

**Comment by fujiwarat** [comment]
1.5.17 consolidates Ctrl-Shift-u to Ctrl-Shift-e and you can type the Unicode code points on the emoji dialog with Ctrl-Shift-e if Ubuntu ibus was built with the emoji feature.
Since I received several similar requests, recently Ctrl-Shift-u is separated from Ctrl-Shift-e again and ibus 1.5.18 will be released sooner or later.

**Comment by vukasin-nikodijevic** [comment]
@fujiwarat - is it possible to disable it somehow by filling / removing some config file options ? 

I'm on Debian Stretch Stable and ibus version there is 1.5.14 which doesn't have ^^ options in UI ?

**Comment by fujiwarat** [comment]
@vukasin-nikodijevic I think 1.5.14 is a little old at present and it has no configuration about this.

**Comment by dorian-marchal** [comment]
Is there a configuration in 1.5.17? I can't find it.
I've been trying to disable ibus from Ubuntu 18.04 for about an hour but I can't find a way (even `sudo apt remote ibus` doesn't seem to work :thinking:).

I'd like to completely disable this behavior when I press <kbd>Ctrl + Shift + U</kbd>:

![screenshot from 2019-02-08 22-59-59](https://user-images.githubusercontent.com/6225979/52508592-73b90d00-2bf5-11e9-94b7-417599b464b1.png)

**Comment by fujiwarat** [comment]
It's 1.5.18 as I explained above.
