### ISSUE TITLE
property panel status doesn't sync correctly

### ISSUE THREAD

**Issue by kenhys** [ibus/ibus#2026]
Which distribution and version?: 

* Ubuntu 18.04

Which desktop environment and version?: 

* Xfce4

Which session type?: 

* XDG_SESSION_TYPE=x11

Which application and version?: 

* gedit 3.28.1-1ubuntu1

IBus version?: 

```
$ ibus version
IBus 1.5.17
```

Issue description:

Steps to reproduce:
1.  Select ibus-mozc
1.  Switch input kind by clicking property panel many times.

Then, selected input kind and displayed input kind on property panel is different.

Here is the capture which indicates this issue.

![ibus-status-mismatch](https://user-images.githubusercontent.com/225841/42932695-f33ca014-8b7d-11e8-85f0-9ed2c255b120.gif)

*NOTE*: **I can reproduce this behavior if ibus engine is implemented by C/C++. If ibus engine is implemented by other language such as Python(ibus-anthy), Vala(ibus-skk) and so on, it seems that this behavior doesn't occurs.**

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

* Reproducible after restarting ibus-daemon

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

* No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

* Yes.

**Comment by kenhys** [comment]
This issue is reproducible with master.
　
```
LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/ibus version
IBus 1.5.18
```

I mean master as 

```
6b47e41d (HEAD -> master, origin/master, origin/HEAD) Remove a misleading "const" modifier of a return value        
```

with xfce4 4.12.4 on debian/unstable.

**Comment by fujiwarat** [comment]
Thank you for the report.
Probably I need to check ibus-mozc later since I cannot reproduce this problem with ibus-anthy.

**Comment by kenhys** [comment]
As I added comment in `NOTE:`, It seems that this problem doesn't occur with ibus-anthy.

```
NOTE: I can reproduce this behavior if ibus engine is implemented by C/C++. If ibus engine is implemented by other language such as Python(ibus-anthy), Vala(ibus-skk) and so on, it seems that this behavior doesn't occurs.
```

**Comment by fujiwarat** [comment]
> I can reproduce this behavior if ibus engine is implemented by C/C++.

Your problem does not depend on the programming languages.
Since ibus-mozc  sends properties by focus-in and the mouse click causes focus-in events, ibus-mozc needs to send the received property to update the old properties.

**Comment by kenhys** [comment]
Hmm, even though the problem is ibus-mozc side, it seems that there is a unexpected behaviour about PRO_TYPE_RADIO.

Here is the sample code to reproduce the issue:
https://github.com/kenhys/ibus-examples/blob/master/radio-menu/main.c

I've expected that switching symbol from property panel works, but actually not.
It may be updating IBusProperty in wrong way, but I don't know well about it. Any thought @fujiwarat ?

**Comment by fujiwarat** [comment]
You don't have to call ibus_engine_update_property() for PROP_STATE_UNCHECKED because GTK buttons will be confused AFAIR.
Only if you receive PROP_STATE_CHECKED in property_activate(), you need to call ibus_engine_update_property().

https://github.com/ibus/ibus-anthy/blob/master/engine/python3/engine.py#L828

**Comment by kenhys** [comment]
@fujiwarat Thanks! I could fix the above example by your advice, and now it works!
By the way, I could prepare reproducible minimum examples, one works, the other doesn't work.

Works expectedly:
https://github.com/kenhys/ibus-examples/blob/master/radio-menu/imeonoff/main.c

Don't work expectedly: It can switch input kind by status bar but not property panel.
https://github.com/kenhys/ibus-examples/blob/master/radio-menu/imeonoff2/main.c

It is very confusing. As you pointed out for ibus-mozc, is it true for above examples?
If so, I'm happy if you could you explain how to fix in good shape in IBus way. (I could not understand well about https://github.com/ibus/ibus/issues/2026#issuecomment-409461397 )

**Comment by fujiwarat** [comment]
> Works expectedly:
> https://github.com/kenhys/ibus-examples/blob/master/radio-menu/imeonoff/main.c
> Don't work expectedly: It can switch input kind by status bar but not property panel.
> https://github.com/kenhys/ibus-examples/blob/master/radio-menu/imeonoff2/main.c

I don't understand the differences. I downloaded the two files and seems both works fine.

> If so, I'm happy if you could you explain how to fix in good shape in IBus way. (I could not understand well about #2026 (comment) )

I already confirmed the suggested change fixes ibus-mozc too with a tiny patch.

**Comment by roberthoffmann** [comment]
The panel status can be fixed in mozc:

```
diff --git a/src/unix/ibus/property_handler.cc b/src/unix/ibus/property_handler.cc
index cd2c77c..f8461c0 100644
--- a/src/unix/ibus/property_handler.cc
+++ b/src/unix/ibus/property_handler.cc
@@ -339,6 +339,7 @@ void PropertyHandler::UpdateCompositionModeIcon(
                              GetIconPath(entry->icon).c_str());
       // Update the radio menu item.
       ibus_property_set_state(prop, PROP_STATE_CHECKED);
+      ibus_engine_update_property(engine, prop);
     } else {
       ibus_property_set_state(prop, PROP_STATE_UNCHECKED);
     }

```

**Comment by fujiwarat** [comment]
The patch sounds good as I forgot the mozc codes.
If you confirm it works fine, please report it to mozc.

**Comment by roberthoffmann** [comment]
https://github.com/google/mozc seems quite dead, they aren't accepting pull requests since 2016.

**Comment by fujiwarat** [comment]
@roberthoffmann The code is sometimes updated and I think it would be worthwhile to submit the patch.
