### ISSUE TITLE
Input of Empathy and Gajim on LXDE/Lubuntu is Garbled

### ISSUE THREAD

**Issue by ilyaigpetrov** [ibus/ibus#2029]
#### Which distribution and version?

Lubuntu 18.04
```shell-session
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04 LTS
Release:	18.04
Codename:	bionic
```

#### Which desktop environment and version?

LXDE 10

#### Which session type?

X11

#### Which application and version?

Empathy 3.25.90+really3.12.14-0ubuntu1  
Gajim 1.0.1-3

#### IBus version

1.5.17

#### Issue description:

Input fields are garbled, their backgrounds are transparent.

![ibus-lubuntu-empathy](https://user-images.githubusercontent.com/1090811/43365944-22419cfc-934e-11e8-9ccf-b4cbb715a34d.jpg)

![ibus-lubuntu-empathy-2](https://user-images.githubusercontent.com/1090811/43365967-7e8b373e-934e-11e8-941f-d5ecc9811bff.jpg)

#### Steps to reproduce:

1. Install lubuntu 18.04
2. `sudo apt install ibus ibus-gtk ibus-qt4`
3. "Start" button -> Preferences -> Language Support -> input method -> IBus
4. Reboot ~~or relogin~~.
5. Install gajim or empathy, log in into a jabber account, try writing into the input field of a new message.

#### Can you reproduce your problem when you restart ibus-daemon?

Yes

#### Do you see any errors when you run ibus-daemon with the verbose option?

```shell-session
$ ibus-daemon --xim --verbose &

(ibus-ui-gtk3:6855): IBUS-WARNING **: 16:49:28.951: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:6855): IBUS-WARNING **: 16:49:29.071: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:6855): Gdk-CRITICAL **: 16:49:29.137: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

#### Can you reproduce your problem with a new user account instead of the current your account? 

Yes

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.

![empathy](https://user-images.githubusercontent.com/105929/43379634-5cd2598c-9408-11e8-9b5b-81885105b9ac.png)

Which ibus engine do you use? You can check the current engine with `ibus engine` command.

Your image shows Russian text so I don't know which GUI you referred.
I think it's good to attach the image to run `env LANG=en_US.UTF-8 empathy` after you kill the process of empathy.

**Comment by ilyaigpetrov** [comment]
Please, try input field of a new message, other input fields of Empathy or Gajim work fine:

![ibus-lubuntu-empathy-3](https://user-images.githubusercontent.com/1090811/43380037-ce20d084-93e8-11e8-8353-966b952ece1c.jpg)

```sh-session
$ ibus engine
xkb:us::eng
```
`env LANG=en_US.UTF-8 empathy` doesn't help.

**Comment by ilyaigpetrov** [comment]
To avoid creation of multiple accounts for testing you may add me to your contacts list: ilyaigpetrov@jabb.im (I will delete my address from here after some time).

**Comment by fujiwarat** [comment]
I don't know what is problem in your screenshot in issue 2029#issuecomment-408756958

![empathy](https://user-images.githubusercontent.com/105929/43381404-83ff3366-940f-11e8-8044-a03943f64e5c.png)
I don't see any problems.

Can you reproduce your problem if ibus-daemon is not running?
You can stop ibus with `ibus exit`.

**Comment by ilyaigpetrov** [comment]
Yes, the issue persists after I exit ibus:
```sh-session
$ ibus exit
$ env LANG=en_US.UTF-8 empathy
```

**Comment by fujiwarat** [comment]
And then your issue is not ibus.
