### ISSUE TITLE
cannot use ibus-pinyin on centos 7.5

### ISSUE THREAD

**Issue by JeffinWong** [ibus/ibus#2034]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

centos 7.5
kernel :3.10.0-862.9.1.el7.x86_64

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Gnome(Centos workstation)

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
all

IBus version?: 
(Run `ibus version`)

IBus 1.5.17

$XDG_SESSION_TYPE
Issue description:
cannot use pinyin to write Chinese

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
Did you confirm ibus-pinyin is running?
You can try ibus-libpinyin.
