### ISSUE TITLE
Failed to build if missing GTK3+ Wayland backend

### ISSUE THREAD

**Issue by obache** [ibus/ibus#2035]
In ui/gtk3/panelbinding.vala, wayland related things are used unconditionally,
so it is impossible to build it without GTK3+ Wayland backend,
missing gdk/gdkwayland.h error to compile panelbinding.c  in the first place.

**Comment by fujiwarat** [comment]
Do you have ibus/bindings/vala/gdk-wayland.vapi ?
It should be included in ui/gtk3/Makefile.am

**Comment by fujiwarat** [comment]
Fedora has one package `gtk3-devel` which includes /usr/lib64/pkgconfig/gtk+-3.0.pc and /usr/lib64/pkgconfig/gdk-wayland-3.0.pc .
You don't have gdk-wayland-3.0.pc ?

**Comment by obache** [comment]
As said "it is impossible to build it without GTK3+ Wayland backend", no GTK3+ Wayland backend related files, no *-wayland.pc, no */*wayland*.h, ...
I'm using self built GTK3+, only X11 backend is enabled.

**Comment by fujiwarat** [comment]
> I'm using self built GTK3+, only X11 backend is enabled.

OK, I see. Probably I should check if gdk-wayland-3.0.pc is available to resolve this issue.
