### ISSUE TITLE
Ibus input window does not display using Budgie desktop environment

### ISSUE THREAD

**Issue by baimafeima** [ibus/ibus#2038]
Note: This issue was first raised on the Solus as well as Budgie development tracker but no solution has been found so far:
https://dev.solus-project.com/T3066 (Solus development tracker)
https://github.com/solus-project/budgie-desktop/issues/729 (Budgie development tracker)

Maybe a very knowledgable Ibus user or someone from the Ibus development team can help track down the issue and solve it for Budgie users. I am not sure if other desktop environments are affected. It could simply be a Budgie issue but it may also be present in GNOME as Budgie is based on GNOME, or it is a compatibility issue which could be solved on the IBus side. Thank you for any help in getting this solved. 

Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Solus 3

Which desktop environment and version?: 
Budgie 10.4

Which session type?: 
X11

Which application and version?: 
Any (e.g. Gedit, Libreoffice, practically any text editor)

IBus version?: 
IBus 1.5.19

Issue description:
The Ibus input window does not display, so currently there is no option to choose among different characters.

Steps to reproduce:
1. Use Ibus in conjunction with ibus-libpinyin oder ibus-anthy. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
The Ibus input window is displayed after typing these commands. 

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
ibus exit
[2]+  Exit 255                ibus-daemon --xim --verbose

(ibus-daemon:15397): GLib-WARNING **: 23:49:54.313: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.

(ibus-daemon:15397): GLib-WARNING **: 23:49:54.315: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

**Comment by fujiwarat** [comment]
I have a look at Solus Budgie.
It runs ibus-daemon without panel:
```
% pstree -asp 953
systemd,1 --switched-root --system --deserialize 22
 └lightdm,651
   └lightdm,692 --session-child 12 15
     └gnome-session-b,707 --session-budgie-desktop
       └budgie-wm,931
         └ibus-daemon,953 --xim --panel disable
           ├ibus-dconf,960
           ├ibus-engine-sim,973
           └{gmain},956
```

I think budgie-wm should not run ibus-daemon with `--panel-disable` from your bug description.
https://github.com/solus-project/budgie-desktop/blob/master/src/wm/ibus.vala#L81

The workaround would be to restart ibus-daemon without `--panel disable`.
```
% ps -ef | grep ibus
% ibus exit
% ps -ef | grep ibus
% ibus-daemon --xim &
```
