### ISSUE TITLE
Candidate window appear at wrong location in Chrome with scaling-factor

### ISSUE THREAD

**Issue by Austaras** [ibus/ibus#2039]
Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
Gnome 3.28

Which session type?: 
X11

Which application and version?: 
Chrome and Chrome based applications including VS Code and Atom

IBus version?: 
1.5.19

Issue description:
Candidate window appear at wrong location, usually in lower right part of screen.Maybe caused by HiDPI

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by Austaras** [comment]
@fujiwarat 
Yes
ibus-libpinyin
Open chrome, type in anywhere I can type

**Comment by fujiwarat** [comment]
@chenzhiwei thx.
