### ISSUE TITLE
Can't enter special characters using compose key in terminals (only with multiple tabs)

### ISSUE THREAD

**Issue by ignatenkobrain** [ibus/ibus#2040]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Fedora 30)

Which desktop environment and version?: GNOME

Which session type?: wayland

Which application and version?: gnome-terminal-3.28.2-4.fc29.x86_64, tilix-1.8.3-2.fc30

IBus version?: IBus 1.5.19

Issue description:
Can't enter special characters using compose key in terminals (only with multiple tabs).

Steps to reproduce:
1. Run gnome-terminal/tilix
2. Use compose key, -, > to enter → (just to make sure it works)
3. Open tab in terminal
4. Try to input → same way

Can you reproduce your problem when you restart ibus-daemon? (yes / no): no

- Interestingly, when I restart it I don't see the special characters when I use compose key.

Do you see any errors when you run ibus-daemon with the verbose option?: I can't actually run this way because it says that session already has ibus.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
I think this is caused by the protocol change between gtk and mutter.
https://gitlab.gnome.org/GNOME/mutter/issues/302

**Comment by fujiwarat** [comment]
Now GTK is fixed.
