### ISSUE TITLE
ibus exit does not terminate some of its started processes

### ISSUE THREAD

**Issue by ghost** [ibus/ibus#2041]
I use ibus and mozc-jp on wayland/weston on Debian testing. IBus always works as expected, and thank you for the nice work! I observed a minor issue and report it here.
The below  is somewhat related to #1896 and #2030 but the below seems an independent issue. I also believe that the below is independent of wayland/weston.

I need to start ibus-daemon manually within weston, as wayland/weston does not seem to have an automatic mechanism to start ibus and `ibus -x` seems to need `DISPLAY` environment variable set (is it correct?). I start ibus as `systemd-run --user --scope  --unit=ibus-user ibus-daemon -d -r -x` (ibus version is 1.5.19 and systemd version is 239).

After the startup, the ibus related processes are as follows:

```
$ systemd-cgls --full --user-unit ibus-user.scope
Unit ibus-user.scope (/user.slice/user-1000.slice/user@1000.service/ibus-user.scope):
├─683 /usr/bin/ibus-daemon -d -r -x
├─686 /usr/lib/ibus/ibus-dconf
├─688 /usr/lib/ibus/ibus-ui-gtk3
├─690 /usr/lib/ibus/ibus-extension-gtk3
├─692 /usr/lib/ibus/ibus-x11 --kill-daemon
├─709 /usr/lib/ibus-mozc/ibus-engine-mozc --ibus
└─712 /usr/lib/mozc/mozc_server
```

When I stop the input method, I do `ibus exit`, and I have the following remaining process:

```
$ systemd-cgls --full --user-unit ibus-user.scope
Unit ibus-user.scope (/user.slice/user-1000.slice/user@1000.service/ibus-user.scope):
└─712 /usr/lib/mozc/mozc_server
```

I believe that `ibus exit` should gracefully terminate all its started sub-processes. But if the developer considers otherwise, then that's also fine and please close this issue.

Please fill in the following items if you don't know the root cause.

Which distribution and version?: 

Debian testing as of Sep. 1, 2018.

Which desktop environment and version?: 

Weston 4.0

Which session type?: 

Weston 4.0

Which application and version?: 

No application involved other than ibus itself.

IBus version?: 

1.5.19

Issue description:

See above.

Steps to reproduce: See above.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

If `ibus-daemon -v -x -r` is used, then I do not see the above problem. In addition, the process `/usr/lib/ibus/ibus-engine-simple` is observed, which does not exist with `ibus-daemon -d -x -r`. The problem appears with `ibus-daemon -v -d -x -r`. The error messages of `ibus-daemon -v -x -r` is as follows:

```
(ibus-ui-gtk3:677): IBUS-WARNING **: 10:33:29.237: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:677): IBUS-WARNING **: 10:33:29.316: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-daemon:664): GLib-WARNING **: 10:34:17.833: GChildWatchSource: Exit status of a child process was requested but ECHILD was received by waitpid(). See the documentation of g_child_watch_source_new() for possible causes.

(ibus-daemon:664): IBUS-WARNING **: 10:34:18.975: 10:34:18.975656: Not every child processes exited!
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
> └─712 /usr/lib/mozc/mozc_server

I think it's a mozc issue. Probably I think if the parent ibus-enigne-mozc died, the child mozc_server could die too.

BTW, I use weston.ini instead of systemd.
```
% cat $HOME/.config/weston.ini 
[input-method]
path=/usr/bin/ibus-weston
% cat /usr/bin/ibus-weston
#!/bin/sh
ibus-daemon $@ &
sleep 10
/usr/libexec/ibus-wayland
```
