### ISSUE TITLE
Not possible to type ~ or ^ in gnome-terminal

### ISSUE THREAD

**Issue by bigon** [ibus/ibus#2043]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Debian unstable

Which desktop environment and version?: 
GNOME 3.30

Which session type?: 
Wayland

Which application and version?: 
gnome-terminal 3.30

IBus version?: 
1.5.19

Issue description:
From time to time it's not possible to type ~ or ^ using a Belgian French keyboard in gnome-terminal

Steps to reproduce:
1. Open gnome-terminal
1. Type AltGr + (the ~ appears underlined)
1. Type AltGr +  a 2nd time (the ~ disappears)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes, looks like, but the ~ is not underlined at step 2 anymore (is ibus really used then?)

Do you see any errors when you run ibus-daemon with the verbose option?:
Nothing

**Comment by bigon** [comment]
Yes indeed, it's linked to multiple tabs

**Comment by bigon** [comment]
OK I can confirm it's fixed with GTK 3.24.1

**Comment by fujiwarat** [comment]
Duplicate of #2040
