### ISSUE TITLE
Using ibus-m17n with non us keyboards (deadkey problem)

### ISSUE THREAD

**Issue by voidray** [ibus/ibus#2045]
Which distribution and version?:  Ubuntu 18.10 Daily
Which desktop environment and version?:  GNOME 3.30
Which session type?: X11
Which application and version?:  (application independent)
IBus version?:  IBus version: 1.5.19; IBus m17n version: 1.3.4
(Also tested with Ubuntu 18.04, IBus 1.5.17, IBus m17n 1.3.4)

Issue description:
I'm trying to create a custom m17n layout, but I saw that the issues I have also occur with the layouts that come with the m17n package.
I have a German keyboard and I want to use for example the m17n layout grc-mizuochi.mim. Most of the mappings work, but none of the keys that are dead letter keys on normal layouts work. It is obvious that they end the input sequence (or whatever it is called when a letter is underlined as long as you can type letters that are defined in one of the mappings).

There is also an issue with at least two keys that are German-specific and not ascii charaters. If I want to map ö like this ((adiaeresis i) "test1") it works, if I want to map the uppercase version ((Adiaeresis i) "test2") the letter Ä is written instead (like on a normal German keyboard layout). I'm not sure if those to issues are related. The problem is that I couldn't find any information how non-ascii chacters could be used as input for a mapping.

Steps to reproduce:
1. install ibus and ibus-m17n
2. reboot
3. in system settings -> region & language settings -> select mapping "ancient greek (until 1453) (mizuochi) (m17n)". It is the file /usr/share/m17n/grc-mizuochi.mim
4. open an editor like libreoffice writer or gedit
5. enter "i" followed by "/". The output is "ί" (positive test)
6. enter "i" followed by "^". The output is "i" but should be ῖ (negative test with dead letter key)

I also made a simple custom layout where I could reproduce this behavior:
(input-method grc customqwertz)
(description "")
(title "test")
(map
 (map
  ("+i" "test1") ; works
  ("*i" "test2") ; works
  ("`i" "test4") ; doesn't work. output: i
  ("^i" "test5") ; doesn't work. output: i
))
(state
 (init
  (map)))

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
> enter "i" followed by "^". The output is "i" but should be ῖ (negative test with dead letter key)

I can output "ῖ" with 'i' and asciicircum (^) with `US` keymap with m17n:grc:mizuochi but I think I cannot output  "ῖ" with 'i' and dead_circumflex with m17n:grc:mizuochi since there is no map in the mim file.

If you wish to use dead_circumflex, ibus core supports compose keys.
You can save "<dead_circumflex>  <i> : "ῖ" small letter iota with perispomeni" to $HOME/.config/ibus/Compose or $HOME/.XCompose and it can be output with DE keymap without m17n:grc:mizuochi  .

But if you wish to output "ῖ" with dead_circumflex in m17n:grc:mizuochi, it would be an issue in ibus-m17n and please file to https://github.com/ibus/ibus-m17n/issues instead. 
ibus core can provide a new signal to send the compose preedit to the engine upon the request.

CC'ing @mike-fabian

**Comment by voidray** [comment]
I tried changing the keymap also to US by this command
   setxkbmap -layout "us"
With this setting I was able to enter the character ῖ with i + ^ (and all the other characters in m17n:grc:mizuochi).

**Comment by fujiwarat** [comment]
OK, if you wish to stick the layout for m17n:grc:mizuochi to US layout, you can configure it on the setup dialog.

1. Type Super-space and enable m17n:grc:mizuochi 
2. Click on a keyboard indicator on panel -> "Setup"
or
Run `gnome-control-center region` -> select m17n:grc:mizuochi  and click the setup button on the dialog

And you can enable the "Use US keyboard layout" button.

**Comment by voidray** [comment]
Nothing happens when I click "Setup" in the panel you mentioned. When I click "Show Keyboard Layout" then the "English (US)" keyboard dialog is opened (even though I still have the  m17n:grc:mizuochi selected). In the gnome-control-center the icon is grayed out. 

I'm not sure if it is the same dialog, but when I open ibus-setup in the terminal and then add the m17n:grc:mizuochi  layout on the tab "Input Method" and click "Preferences" the following output is logged in the terminal:

> ** (ibus-setup-m17n:7839): WARNING **: 12:48:15.122: can't read ibus-m17n-preferences.ui: /usr/share/ibus-m17n/setup/ibus-m17n-preferences.ui:60:37 Invalid property: GtkDialog.has_separator
> 
> ** (ibus-setup-m17n:7839): CRITICAL **: 12:48:15.122: file setup.c: line 533 (setup_dialog_new): should not be reached
>

**Comment by fujiwarat** [comment]
> ** (ibus-setup-m17n:7839): WARNING **: 12:48:15.122: can't read ibus-m17n-preferences.ui: /usr/share/ibus-m17n/setup/ibus-m17n-preferences.ui:60:37 Invalid property: GtkDialog.has_separator

From your error, your ibus-m17n-preferences.ui has an invalid property 'has_separator' in the line 60th.
But I find the property in neither https://github.com/ibus/ibus-m17n/blob/master/src/ibus-m17n-preferences.ui nor my local ibus-m17n.

Can you attach your ibus-m17n-preferences.ui ?

Did your distro modify that file?

**Comment by voidray** [comment]
After I commented out the following two lines, the setup dialog opened up:
Line 60:
`<property name="has_separator">False</property>`

Line 70:
`<property name="tab_vborder">3</property>`

![ibus grc settings](https://user-images.githubusercontent.com/1024256/46647775-6c1f2400-cb81-11e8-8dab-33c7843ca076.jpg)

This didn't change anything regarding the actual problem (not being able to type all characters of the m17n:grc:mizuochi  layout on non us keyboard).
When I open the dialog window that normally displays all the keybindings for a layout, with m17n:grc:mizuochi it only shows the us layout. I don't know if that's normal fur ibus-m17n layouts:
![show keyboard layout dialog](https://user-images.githubusercontent.com/1024256/46647874-e64fa880-cb81-11e8-82f7-32b08e14e060.jpg)

**Comment by fujiwarat** [comment]
OK, seems you don't have the patch of https://github.com/ibus/ibus-m17n/commit/6c88539733be30886e93583414a2d5ca1c60743c .
Which was applied after ibus-m17n 1.3.4 is released.

But I don't think the patch is good since m17n.xml specifies 'default' layout. I may try to delete that patch in the future.
