### ISSUE TITLE
Any plan to support wayland multi monitors?

### ISSUE THREAD

**Issue by YangKeao** [ibus/ibus#2048]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
gentoo

Which desktop environment and version?: 
GNOME 3.30
 GTK+3.24.1

Which session type?: 
Wayland

Which application and version?: 
Any GTK application

IBus version?: 
ibus 1.5.19

Issue description:
IBus UI will freeze on the primary display.

Steps to reproduce:
1. Plug an external display to a PC or laptop.
2. Open any GTK application like gnome-terminal or nautilus.
3. Input in it and after the auxiliary's length beyond two, the UI will freeze.
4. If I hover my cursor onto the lookup table, the UI will refresh and update lookup table and auxiliary.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
After the restart, I can never input on any GTK application like gnome-terminal and nautilus.

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes. I can also reproduce it on another Arch Linux computer.

I don't know whether it's a bug in GTK+ or ibus. And I find the Wayland multi monitors support is in the todo list. So I wonder whether there is any plan to support it?

**Comment by fujiwarat** [comment]
Have you ever tried the previous GNOME versions 3.28 or lower?
Currently my laptop is GNOME 3.28 and IBus 1.5.19 and the input works fine with multi monitors in both dual and mirror mode.
So I guess your problem is new in GNOME 3.30 because the input protocol is changed considerably in 3.30. 
I will upgrade Fedora version in my laptop after Fedora GA.

**Comment by bahborben** [comment]
same here.
Fedora 29 with multi screens. 
1. pagination seems not response correctly in second screen.
2. some input character not display in panel, but do effect the current choosen result

**Comment by das-rob3rt** [comment]
Got the same problem here.
Kali Linux laptop with an external screen.
Sometimes even hovering above the UI won't work.

**Comment by fujiwarat** [comment]
> I don't think its an issue in gnome-shell. In sway I can also reproduce the bug.

I think your problem is not reproduced in other desktops.
So have you ever reproduced your problem with the previous GNOME 3.28 or lower?

**Comment by bahborben** [comment]
> > I don't think its an issue in gnome-shell. In sway I can also reproduce the bug.
> 
> I think your problem is not reproduced in other desktops.
> So have you ever reproduced your problem with the previous GNOME 3.28 or lower?

I upgrade from Fedora 28(GNOME 3.28) to Fedora 29(GNOME 3.30), and there is no problem before upgrading.

**Comment by fujiwarat** [comment]
@bahborben Thank you! 
I will find time to upgrade my laptop.

**Comment by theburn** [comment]
I also upgrade my OS from FC28 to FC29, and the bug has  reproduced

**Comment by lotem** [comment]
A lucky issue number here it is.
I've got a [bug report](https://github.com/rime/home/issues/295) for ibus-rime which seems relevant.
Symptom: when typing into a window in second screen, IME shows the suggestions for the first input character, then stops updating.
Please help triage if it the same issue discussed here.

**Comment by fujiwarat** [comment]
OK, I could reproduce this problem but I don't know where is the problem at the moment.
I filed https://gitlab.gnome.org/GNOME/gnome-shell/issues/901

**Comment by adityasuseno** [comment]
Got the same problem.
I use Ubuntu 18.10
GNOME 3.30.1
Only affect Wayland Session

**Comment by adityasuseno** [comment]
This is **Fixed** in Ubuntu 19.04 Disco Dingo 👍️

**Comment by YangKeao** [comment]
It seems that this bug has been fixed. So I close this issue.
