### ISSUE TITLE
[iBus on Mint 19]I have to click 3 times to change language input

### ISSUE THREAD

**Issue by ntd252** [ibus/ibus#2049]
Hello everyone! I have an issue related to changing language input from iBus, on my Linux Mint 19 Tara.

Every time I need to change language input (from English to Vietnamese and opposite), I have to click the iBus icon three times to close the context menu. If I don't click 3 times enough, the context menu will be on screen forever even when I click to other positions on display or windows.

I am not sure this is a problem of iBus, because it didn't happen on Mint 18 - 18.3, but posting it on Mint forum doesn't get any attention.
I hope to hear a solution for this issue.
https://www.youtube.com/watch?v=jNUn_n6udjU

**Comment by ntd252** [comment]
Sadly, no one cares? :(

**Comment by fujiwarat** [comment]
You didn't fill the bug template.
Probably I think Mint XFCE wroks fine.

**Comment by fujiwarat** [comment]
Did you confirm Mint XFCE?
