### ISSUE TITLE
get_surrounding_text() not working in firefox

### ISSUE THREAD

**Issue by sthibaul** [ibus/ibus#2054]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Debian Buster

Which desktop environment and version?: 
Fvwm, manually set GTK_IM_MODULE to ibus

Which session type?: 
X11

Which application and version?: 
firefox 63.0.1

IBus version?: 
1.5.19

Issue description:
get_surrounding_text() does not provide the text in firefox

Steps to reproduce:
1. Run ibus-daemon
1. Open firefox, open a webpage with a form, for instance https://www.google.fr/
1. Type text in the field
1. Run the attached ibus input module
1. move around with arrows

The module only gets

text is ''
cursor is 0
anchor is 0

while in other applications (e.g. gedit, libreoffice, etc.) the module properly gets the current line

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes
[ibus-braille.py.txt](https://github.com/ibus/ibus/files/2567003/ibus-braille.py.txt)
[braille2.xml.txt](https://github.com/ibus/ibus/files/2567004/braille2.xml.txt)

**Comment by fujiwarat** [comment]
Seems the 'retrieve-surrounding' signal failed with the first typing but it succeeded with the second typing and IBus GtkIMModule deleted the capability of IBUS_CAP_SURROUNDING_TEXT with the first typing.
Probably I think the first failure would be a bug in firefox but now I added a workaround not to delete the capability with the first typing.

Now you can see the surrounding text with the fix.
But the surrounding text is still not a latest and I filed a issue to firefox; https://bugzilla.mozilla.org/show_bug.cgi?id=1506768

**Comment by ShikiOkasaka** [comment]
firefox/fc30の動作
commit_text()にたいしてset-surrounding-textシグナルがこない。通常の文字キーにたいしては毎回きている。firefoxがわのバグという感じ。

chrome/fc30の動作
set-surrounding-textシグナルがそもそもきていない。それなのに、IBUS_CAP_SURROUNDING_TEXTがたつのがまずそう。

**Comment by ShikiOkasaka** [comment]
Sorry, the previous one should have been posted to ibus-replace-with-kanji: https://github.com/esrille/ibus-replace-with-kanji
That is how we see this issue from an engine side, anyway.
