### ISSUE TITLE
Being able to set cursor position from engine?

### ISSUE THREAD

**Issue by sthibaul** [ibus/ibus#2055]
Please fill in the following items if you don't know the root cause.

* Which distribution and version?: 
Debian Buster

* Which desktop environment and version?: 
fvwm  + GTK_IM_MODULE configuration

* Which session type?: 
X11

* Which application and version?: 
any

* IBus version?: 
1.5.19

* Issue description:
There does not seem to be a way to set the current cursor position from an ibus engine.

* Steps to reproduce:
1. Write an ibus engine
1. implement the do_process_key_event callback
1. use delete_surrounding_text to remove some text
1. use commit_text to add text

now that I have replaced some existing text with newer text, I would like to put the cursor within the commited text (and not necessarily at its end).

The idea is that I would like, with the ibus module, to switch between different representations of the same text, but keeping the cursor at the corresponding position between the representations.

* Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

* Do you see any errors when you run ibus-daemon with the verbose option?:
no

* Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
Why do you wish to put the cursor within the committed text?

> The idea is that I would like, with the ibus module, to switch between different representations of the same text, but keeping the cursor at the corresponding position between the representations.

I think you explained the reason but I don't understand what are the different representations.
I'd like to know an example with detail how to use that feature.

**Comment by sthibaul** [comment]
Here is a trivial example, converting braille input between the unicode representation and the BRF representation:

[ibus-braille.py.txt](https://github.com/ibus/ibus/files/2575788/ibus-braille.py.txt)
[braille2.xml.txt](https://github.com/ibus/ibus/files/2575808/braille2.xml.txt)

Type only capital letters (BRF representation), then press control-shift-b to make it unicode braille patterns, and control-shift-b again to get back to BRF. But the cursor position is lost, making it hard to continue editing the text.

The real use case involves contracted braille representations vs expanded braille representation, but basically the unicode/BRF switch is a good technical representative.

**Comment by sthibaul** [comment]
I should have been more specific, sorry. After typing a few characters, move left  a bit, then press control-shift-b. The cursor ends up at the end of the braille pattern text.

**Comment by fujiwarat** [comment]
OK, I understand the case.
But why do you wish to move the cursor after a commit text?
If you don't call ibus_enigne_delete_surrounding_text(), ibus_commit_text() commits the text likes "BF⠃⠋⠃B" and I think the cursor is the expected position before the last 'B' instead before the last "⠃B".
The commit_text() is to complete the current modifying text and output the text at the cursor position.
If you'd move the cursor, probably I assume it's an incomplete text for IME and I'd suggest to use the preedit text instead of the surrounding feature.

**Comment by fujiwarat** [comment]
> But I want to also be able to change existing text, to be able to have all possible interactions between a sighted user and a non-sighted user in the edition in all applications.

If you think the possible interactions between users, probably I think it's a task of an application but not input methods. I also think moving cursor would not be the task of input methods.

> I currently can't take it back without losing the cursor position.
I mean ibus_engine_update_preedit_text() has the cursor position so if you switch surrounding feature to preeedit feature, it could be resolved.

**Comment by sthibaul** [comment]
> If you think the possible interactions between users, probably I think it's a task of an application but not input methods.

But we need this interaction in all applications where it makes sense to type text (e.g. gedit, kate, libreoffice, firefox, etc.). Implementing in all of them would be tedious, while the feature is strongly related with typing the text: typing something, then coming back to a part of a word, fixing it a bit, then asking for help with it, which requires switching to another transcription, then continuing fixing it, which requires switching back the transcription.

> I mean ibus_engine_update_preedit_text() has the cursor position so if you switch surrounding feature to preeedit feature, it could be resolved.

You mean to make the whole piece of text to be transcribed a preedit text? That'd have the effect of showing it as underlined etc. but that could work indeed.

**Comment by sthibaul** [comment]
Thinking about it, it really makes sense to me to be able to commit some text with the cursor put inside the committed text, for instance typing all the enclosing characters: (), {}, “”, «», but also e.g. tags: <b></b>, \textbf{} etc.

**Comment by fujiwarat** [comment]
I don't think it is the good approach that IMEs can move the cursor. IMEs should output the expected characters only.
But probably you could move the cursor with ibus_engine_forward_key_event().
