### ISSUE TITLE
Mixing Colemak keyboard layout and Japanese IM confuses the use of CapsLock

### ISSUE THREAD

**Issue by b4284** [ibus/ibus#2056]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
**Arch Linux**

Which desktop environment and version?: 
**GNOME 3.30.2**

Which session type?: 
**X11**

Which application and version?: 
**Effects the entire desktop**

IBus version?: 
**IBus 1.5.19**

Issue description:
**If Colemak keyboard layout and any of the japanese input method are enabled at the same time, then the CapsLock key in Colemak has mixed effects. It's both CapsLock key and BackSpace key, i.e. pressing the CapsLock key changes the CapsLock, and deletes backward one character.** 

**In normal Xorg setup, the Colemak keyboard layout has the correct behavior for CapsLock key: it works as a BackSpace key.**

**Giving a `setxkbmap us -variant colemak` command in the terminal bring me back the normal Colemak behavior, but all other input methods for Chinese and Japanese are wrong because they are using a `us` layout.**  

Steps to reproduce:
1. Enable `colemak` layout. 
2. Remove the default `us` layout.
3. Install and enable `anthy` or `kkc`.
4. Observe the CapsLock behavior when `colemak` layout is active.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
**yes**

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
**no**

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
**yes**

**Comment by fujiwarat** [comment]
> Giving a setxkbmap us -variant colemak command in the terminal bring me back the normal Colemak behavior

Both ibus-anthy and ibus-kkc has a setting dialog to set  the keymap for the IME.
