### ISSUE TITLE
Language Names

### ISSUE THREAD

**Issue by glasseyes** [ibus/ibus#2062]
IBus parses the iso-codes iso_639-2.xml file to get the name of languages that IBus engines support. That has under 500 languages.

The iso639-3.xml file has codes and names for the known languages at its time of publication.

Keyman (www.keyman.com) already has support for over 1000 languages, many of which are only named in iso639-3. At the moment they are all grouped under "Other". An iIBus engine for Keyman will be released soon.

Other engines such as m17n may support some of these languages too.

I've made a PR for it #2061

**Comment by fujiwarat** [comment]
I don't see any engines in "Other" category and I don't think the script affects your problem.
Can you describe your problem exactly with the bug template? I.e. desktop versions.

**Comment by fujiwarat** [comment]
>  An iIBus engine for Keyman will be released soon.

It should be fixed in that engine.

**Comment by glasseyes** [comment]
This is in ibus-setup, Input Method tab. Click "Add" to add a keyboard

You get a list of languages. There is also a 'language' "Other".

If if it is a language like Northern Thai "nod" it doesn't appear in a language "Thai, Northern" but instead in "Other". This is the problem that this issue addresses.

**Comment by glasseyes** [comment]
Sorry, I don't know what I should say to distinguish between the IBus engine ibus-keyman and the individual engines it creates for each keyboard. It is the latter that currently mostly end up in the "Other" language.

This affects all versions on all distros and I think all desktop environments so the template didn't look relevant. I can still try that if you like.

**Comment by fujiwarat** [comment]
>  I think all desktop environments so the template didn't look relevant. I can still try that if you like.

No, the behavior is different by desktop and I asked to use the bug template.

> You get a list of languages. There is also a 'language' "Other".

The listed engines in Other is expected. E.g. the language ibus-input-pad is "other".
