### ISSUE TITLE
IBus candidates orientation donesn't work in gnome3

### ISSUE THREAD

**Issue by Titubery** [ibus/ibus#2072]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Manjaro Linux x86_64 and 4.19.12-2-MANJARO
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: gnome 3.30.2
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: X11
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: generally
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.19
(Run `ibus version`)

Issue description:
IBus cnadidates orientation donesn't work with pinyin methods such as sunpinyin, googlepinyin and rime except pinyin and libpinyin. It is always vertical though I have changed it with ibus-setup or dconf-editor. 

Steps to reproduce:
 It occurs every time I install ibus-rime and others in gnome3.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: 
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No, It  showed that 'current session already has an ibus-daemon.' then exit.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
They would be the issues in each input method engines of sunpinyin and googlepinyin.

**Comment by jacknlliu** [comment]
@fujiwarat   the candidate orientation also not working for  `ibus-typing-boosting`

**Comment by mike-fabian** [comment]
> @fujiwarat the candidate orientation also not working for `ibus-typing-boosting`
> 
> system: Fedora 31

Works for me in ibus-typing-booster. See screenshot. In the screenshot you also see the setup tool
of ibus-typing-booster where I selected 

Candidate window orientation         [Horizontal]

![Screenshot](https://user-images.githubusercontent.com/2330175/75677393-a06e1580-5c8b-11ea-91d8-d8b5b4c42bb7.png)

**Comment by jacknlliu** [comment]
@mike-fabian  thanks for your reply. I just test the setup from `ibus-typing-booster`, and it also works. But if I use the `ibus-setup` commandline from terminal, the settings does not work.

**Comment by mike-fabian** [comment]
> @mike-fabian thanks for your reply. I just test the setup from `ibus-typing-booster`, and it also works. But if I use the `ibus-setup` commandline from terminal, the settings does not work.

You wrote that you are using Gnome: 

> Which desktop environment and version?: gnome 3.30.2

I think ibus-setup is only intended  to be  on non-Gnome desktops. When you add input methods using ibus-setup, it has no effect on Gnome either. 

The following screenshot shows XFCE.

You can see that in ibus-setup, I did choose 

Candidates orientation:  Horizontal

And in ibus-typing-booster setup I did choose:

Candidate window orientation:  System default

(System default means that ibus-typing-booster does not try to set the candidate window orientation itself, it just uses what happens to be the default already).

On XFCE you can see that this has the effect that the candidate window shown by ibus-tying-booster is horizontal: 

![Screenshot](https://user-images.githubusercontent.com/2330175/75703776-6f580a00-5cb8-11ea-934b-8f12c96c74f0.png)

**Comment by jacknlliu** [comment]
@mike-fabian I really appreciate what you said, and it makes things very clear to me. I'm using gnome 3, so `ibus-setup` doesn't work.
