### ISSUE TITLE
X11 compose does not work with certain Unicode characters (non-BMP)

### ISSUE THREAD

**Issue by dangelog** [ibus/ibus#2074]
### Which distribution and version?
Ubuntu 18.04

### Which desktop environment and version?
GNOME  3.26

### Which session type?
X11

### Which application and version?
gedit, firefox, thunderbird, Qt Creator

### IBus version?
1.5.17

### Issue description:
Applications using ibus as their input method (GTK, Qt) do not seem to receive compose sequences if the result is a non-BMP Unicode character.

The default X11 Compose file shipped with Ubuntu 18.04 contains these lines:

```<Multi_key> <colon> <parenright>        : "☺"   U263A # WHITE SMILING FACE
<Multi_key> <colon> <parenleft>         : "☹"   U2639 # WHITE FROWNING FACE
<Multi_key> <backslash> <o> <slash>             : "🙌"          # PERSON RAISING BOTH HANDS IN CELEBRATION

<Multi_key> <p> <o> <o>                 : "💩"  U1F4A9 # PILE OF POO

<Multi_key> <F> <U>                     : "🖕"  U1F595 # REVERSED HAND WITH MIDDLE FINGER EXTENDED
<Multi_key> <L> <L> <A> <P>             : "🖖"  U1F596 # RAISED HAND WITH PART BETWEEN MIDDLE AND RING FINGERS
```

As you can see, some lines yield code points that don't land in the BMP. Pressing the corresponding composition sequence has no effect. 

I'm not sure how to verify if it's ibus not picking those up and/or it's also a fault in GTK/Qt not handling those sequences correctly.

### Steps to reproduce:
Attempt any of the composition sequences above (specifically the ones that yield codepoints >U+FFFF), and it won't work.

### Can you reproduce your problem when you restart ibus-daemon? (yes / no)
yes

### Do you see any errors when you run ibus-daemon with the verbose option?
no

### Can you reproduce your problem with a new user account instead of the current your account? (yes / no)
yes

**Comment by fujiwarat** [comment]
I tried the 4 characters and I can output those with ibus.
Can you show the result of the command `gsettings get org.gnome.desktop.input-sources sources`?
I can check if you use ibus with the result.

**Comment by dangelog** [comment]
Hi, this is the result:
`$ gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'it'), ('xkb', 'us')]`

Nothing changes if I switch the keyboard layout between en_US and it_IT.

**Comment by fujiwarat** [comment]
It means you don't use ibus but gtk-im-context-simple and your gtk version is old.

To use ibus with `('xkb', 'us')`, you need to add one of ibus engines:

1. Install an ibus engine likes ibus-m17n and log in the GNOME session again
2. Run `gnome-control-center region` and add the installed engine. In this case the language is "Other" -> "Other (unicode(m17n))".

And the above gsettings command will show an ibus entry and you can use compose key.

**Comment by dangelog** [comment]
I can't choose my GTK version, unfortunately :) It's a stock Ubuntu 18.04.

So GTK apps do NOT use ibus by default on Ubuntu? 

What about Qt apps? There's a default of using the ibus engine (QT_IM_MODULE=dbus set in the environment, not exactly sure where it's coming from -- probably some post-login script) and they also suffer from the very same issue. Bug in Qt?

**Comment by fujiwarat** [comment]
> So GTK apps do NOT use ibus by default on Ubuntu?

The default is gtk-im-context-simple if you don't enable any ibus engines in GNOME.

> I can't choose my GTK version,

And then I noted the workaround above using the example of ibus-m17n.

If you set QT_IM_MODULE=ibus, your Qt application will use ibus and the compose key works.

**Comment by dangelog** [comment]
> If you set QT_IM_MODULE=ibus, your Qt application will use ibus and the compose key works.

Are the ibus composition rules unrelated to the ones written in X11's Compose file?

Because under QT_IM_MODULE=ibus , compose L L A P does not yield 🖖, it yields "AP" (it's as if the the "compose L L" sequence got discarded somehow).

**Comment by fujiwarat** [comment]
> Are the ibus composition rules unrelated to the ones written in X11's Compose file?

I meant to write those lines in $HOME/.XCompose or $HOME/.config/ibus/Compose but seems you meant the compose file of en_US and now I can reproduce it.

I will investigate the issue tomorrow.

**Comment by dangelog** [comment]
Thanks for the feedback, and sorry for being a nuisance :)
