### ISSUE TITLE
IBUS:ERROR:candidatearea.c:509:candidate_area_set_candidates: assertion failed: (candidates.length < 16)

### ISSUE THREAD

**Issue by Caagr98** [ibus/ibus#2076]
**Which distribution and version?:**
Arch

**Which desktop environment and version?:**
i3

**Which session type?:**
X11

**Which application and version?:**
Seemingly any, including but probably not limited to gnome-terminal, firefox, and discord

**IBus version?:**
1.5.19

**Issue description:**
Sometimes when typing in japanese with ibus-kkc, the key for switching input methods stops working until I restart the ibus-daemon. While I've only seen the issue with ibus-kkc, the error appears to be in ibus itself.

**Steps to reproduce:**
1. Switch to ibus-kkc
1. Write つく (*tsuku*)
1. Activate conversion (default space)
1. A message appears in the daemon's output and the hotkey for toggling the IME stops working. Japanese writing still works, but no candidate popup.

**Can you reproduce your problem when you restart ibus-daemon? (yes / no):**
Yes, it happens every time.

**Do you see any errors when you run ibus-daemon with the verbose option?:**
```
(ibus-ui-gtk3:8722): IBUS-WARNING **: 09:32:53.001: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:8722): IBUS-WARNING **: 09:32:53.047: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
**
IBUS:ERROR:candidatearea.c:509:candidate_area_set_candidates: assertion failed: (candidates.length < 16)
```
(The first two appear immediately when starting the daemon, the last appears when triggering the bug)

**Can you reproduce your problem with a new user account instead of the current your account? (yes / no):**
Haven't tried. I did try deleting all config files I could find (~/.config/ibus and ~/.config/ibus-kkc) though; it didn't change anything.

**Comment by Caagr98** [comment]
Apparently, it's because I set the number of candidates in ibus-kkc to 16, which is above the allowed amount. I'll file a bug report to them instead, but I still think ibus shouldn't crash if it receives too many candidates (why even have a limit?).

**Comment by fujiwarat** [comment]
Sorry for the late response.
I understood the problem and will fix it.
