### ISSUE TITLE
Hotkey or shortcut key

### ISSUE THREAD

**Issue by scootergrisen** [ibus/ibus#2080]
I see this sentence using the word "hotkey" in the translations (po files):

    Super+space is now the default hotkey.

But i dont see "hotkey" used in other strings.
Should it be "shortcut key" or is there a difference between "hotkey" and "shortcut key"?
"shortcut keys" is used 20 times in the translation po files. "hotkey" only 1 time.

**Comment by fujiwarat** [comment]
It's a good point.
You're right. The "hotkey" and "shortcut key" used as the same meaning.
Super-space has been the default shortcut key since 1.5.3 and it was called hotkey in the previous releases.
Probably I think it's a good time to delete the notification dialog since 1.5.3 is an old release.
