### ISSUE TITLE
ui/gtk3/panelbinding.c needs to be regenerated on build

### ISSUE THREAD

**Issue by tsutsui** [ibus/ibus#2082]
Which distribution and version?: 
NetBSD/i386 8.0 and pkgsrc HEAD (I'm trying to update ibus package to 1.5.20)

Which desktop environment and version?: 
Build issue

Which session type?: 
X11

Which application and version?: 
Build issue

IBus version?: 
1.5.20

Issue description:
ibus-1.5.20.tar.gz includes both ibus-1.5.20/ui/gtk3/panelbinding.c and ibus-1.5.20/ui/gtk3/panelbinding.vala:
```
% tar -ztvf ibus-1.5.20.tar.gz | grep panelbinding
-rw-r--r--  1 root     wheel      38104 Mar  1 20:43 ibus-1.5.20/ui/gtk3/panelbinding.vala
-rw-r--r--  1 root     wheel     107649 Mar  1 20:59 ibus-1.5.20/ui/gtk3/panelbinding.c
```
panelbinding.c is newer so make doesn't explicitly regenerate panelbinding.c.
However, panelbinding.vala has "#if USE_GDK_WAYLAND" conditional lines. panelbinding.c in the tar.gz seems generated with USE_GDK_WAYLAND and it has a line "#include <gdk/gdkwayland.h>".
Then it causes build failure on X11 environment without Wayland.

Steps to reproduce:
1. configure and build ibus-1.5.20 on X11 environment without Wayland
1. build fails:
```
  CC       panelbinding.o
panelbinding.c:35:28: fatal error: gdk/gdkwayland.h: No such file or directory
compilation terminated.
gmake[3]: *** [Makefile:1339: panelbinding.o] Error 1
```
Removing ui/gtk3/panelbinding.c and re-running make works. Should it be excluded from the release tar ball?

**Comment by fujiwarat** [comment]
I understand your point however we hope vala would not be needed by the default build.
Since your case would not be default, could you delete panelbinding.c in your build in every release?

E.g.
```
./configure $CONFIGURE_FLAGS
make -C ui/gtk3 maintainer-clean-generic
make
```

**Comment by tsutsui** [comment]
Ok, I will keep to add explicit rules to rebuild panelbinding.c on pkgsrc build.

BTW, it looks the "maintainer-clean-generic" target in ui/gtk3/Makefile.in doesn't remove panelbinding.c:
```
(cd /usr/pkgsrc/inputmethod/ibus/work.i386/ibus-1.5.20 && /usr/bin/make -C ui/gtk3 maintainer-clean-generic)
This command is intended for maintainers to use
it deletes files that may require special tools to rebuild.
rm -f ./application.c
rm -f ./bindingcommon.c
rm -f ./candidatearea.c
rm -f ./candidatepanel.c
rm -f ./emojier.c
rm -f ./handle.c
rm -f ./ibus_ui_gtk3_vala.stamp
rm -f ./iconwidget.c
rm -f ./indicator.c
rm -f ./keybindingmanager.c
rm -f ./panel.c
rm -f ./pango.c
rm -f ./property.c
rm -f ./propertypanel.c
rm -f ./separator.c
rm -f ./switcher.c
rm -f ./xkblayout.c
rm -f application.c
rm -f bindingcommon.c
rm -f candidatearea.c
rm -f candidatepanel.c
rm -f emojier.c
rm -f handle.c
rm -f iconwidget.c
rm -f indicator.c
rm -f keybindingmanager.c
rm -f panel.c
rm -f pango.c
rm -f property.c
rm -f propertypanel.c
rm -f separator.c
rm -f switcher.c
rm -f xkblayout.c
```
panelbinding.vala (and also emojierapp.vala) should be added to ibus_ui_gtk3_SOURCES in ui/gtk3/Makefile.am ?

**Comment by fujiwarat** [comment]
Thank you for your change and the point.
If we have the better solution, I.e. the default build does not need vala but it can rebuilt the vala sources when enable_gdk3_wayland=no, we may enhance configure and makefiles later.

I think ibus_extension_gtk3_SOURCES has panelbinding.c and AFAIK, `make` or `make check` sometimes will causes a build error depended on a machine specs if I use ibus_extension_gtk3_SOURCES=panelbinding.vala instead of ibus_extension_gtk3_VALASOURCES=panelbinding.vala .

Probably I will add `MAINTAINERCLEANFILES=emojierapp.c extension.c panelbinding.c` in Makefile.am to be able to delete the source files with `make maintainer-clean-generic`
