### ISSUE TITLE
Error: ibus-libpinyin select window places wrong

### ISSUE THREAD

**Issue by HsunGong** [ibus/ibus#2084]
![screenshot from 2019-03-05 19-57-51](https://user-images.githubusercontent.com/32933986/53804111-92ef5400-3f81-11e9-8c17-3c4eba1e8f38.png)

Ibus 1.5.17
Ibus Intelligent Pinyin 1.9.2

I can't use libpinyin right the place for vscode. But for gedit, vim, browser, it's all right.

**Comment by XunGong99** [comment]
Anyone Help??

**Comment by fujiwarat** [comment]
Did you enlarge the screen size?
If yes, how did you do?

**Comment by qiangzhao** [comment]
@fujiwarat Hi:
I think I can reproduce this case could you please check from your side:
1) in Fedora 30, Firefox 66.0.2, ibus-1.5.20
2) open "www.google.com" in firefox.
3) switch input engine to anthy
4) click the search box in Google webpage.
5) keyboard input "asas" or something else to wait for select.
6) Move the Firefox window to a new place.
7) press space key to pop out candidate window.

check the candidate window position, 
The window is in the old position, not moved with Firefox.

After the candidate word is selected, continue to input something which needs select. eg: "asas"
then check the candidate window position:
The window is still in the old position. not flushed.

**Comment by qiangzhao** [comment]
I suppose this maybe a Mozilla's bug,  because all Gnome related programme behaviour is good; only firefox have this problem. even though it is also using Gtk.

**Comment by fujiwarat** [comment]
@qiangzhao I think the original submitter said the browser works fine.
Anyway no reply from the submitter.

**Comment by qiangzhao** [comment]
It's fine for me.
Just  a little words in addition: I think https://github.com/ibus/ibus/issues/2075 is happened with the same root cause, and with on responding for more than 1 month, So maybe can be close together.
