### ISSUE TITLE
Candidate phrase show error

### ISSUE THREAD

**Issue by wmzy** [ibus/ibus#2085]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 29.

Which desktop environment and version?: 
GNOME 3.24. 

Which session type?: 
Wayland. 

Which application and version?: 
vscode or gnome-terminal

IBus version?: 
1.5.19

Issue description:
![image](https://user-images.githubusercontent.com/5526525/54169010-13471500-44ac-11e9-8050-33429be2438f.png)

Steps to reproduce:
I couldn't reproduce it.The frequency of occurrence is high, but it does not have to be.
不能复现，发生的频率很高，但不必现。

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
after run `ibus exit` and `ibus-daemon --xim &` I could not input chinese.

**Comment by fujiwarat** [comment]
> Issue description:

I don't see any errors in your screenshot. What is your problem?

**Comment by wmzy** [comment]
My input is `shu` and the first candidate should be `书`.But as then screenshot,I only see an `s`.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem with gnome-terminal.
Probably you could update `dnf update --enablerepo=updates-testing gnome-shell mutter gtk3` ?

**Comment by wmzy** [comment]
After I run the command and reboot the system, the problem still appears.

**Comment by wmzy** [comment]
I try with a new user account and all thing is ok. Is there a way to clean all cached data?

**Comment by fujiwarat** [comment]
I suppose you use the latest ibus.
I guess you use ibus-libpinyin and you can back up the results of `ibus read-config` and `ibus read-config --engine-id com.github.libpinyin.ibus-libpinyin.libpinyin`.
And you can reset the settings by `ibus reset-config` and `ibus reset-config --engine-id com.github.libpinyin.ibus-libpinyin.libpinyin`

**Comment by fujiwarat** [comment]
You should not delete the lines of the bug template which includes the question for the new account.

**Comment by wmzy** [comment]
Reset config dons't work.

**Comment by fujiwarat** [comment]
> Reset config dons't work.

Do you mean the command output any errors? or the reset-config command does not reset the settings? or the reset-config does not resolve your problem?

**Comment by wmzy** [comment]
Sorry for the vague expression.
The reset-config does not resolve my problem.

**Comment by fujiwarat** [comment]
And then your problem would not be caused by ibus settings.
You can rename `$HOME/.config`, `$HOME/.cache`, `$HOME/.local` and log out and in the wayland session again.

**Comment by wmzy** [comment]
I do as what you say, and solved the problems of vscode and gnome-shell.
But after sometimes, the problem appears in chrome.
When I am free, I will try out which file cause this.

**Comment by wmzy** [comment]
I found out what caused this problem.
When I exchanged the two display, the problem will appear, and the problem will disappear after the exchange.
![image](https://user-images.githubusercontent.com/5526525/54666791-b8ee2a00-4b25-11e9-86ba-9f6523f58b67.png)
