### ISSUE TITLE
ibus-setup should specify a system python instead of using that in current environment 

### ISSUE THREAD

**Issue by thautwarm** [ibus/ibus#2086]
https://github.com/ibus/ibus/blob/407756521617f8514b65ddfa35512183fd22d38d/setup/ibus-setup.in#L30

Users always use a non-system python distribution(e.g., Anaconda) and prefer to add it to PATH.
ibus-setup just failed in this case, for the configured file shows that it uses environment python which will not have corresponding dependencies(e.g., gi)

**Comment by fujiwarat** [comment]
I think users always wish to launch ibus-setup with a non-system python against your case.

The possible solution would be:
```
diff --git a/setup/ibus-setup.in b/setup/ibus-setup.in
index bb5c85cf..4a6830af 100644
--- a/setup/ibus-setup.in
+++ b/setup/ibus-setup.in
@@ -27,5 +27,5 @@ export IBUS_PREFIX=@prefix@
 export IBUS_DATAROOTDIR=@datarootdir@
 export IBUS_LOCALEDIR=@localedir@
 export IBUS_LIBEXECDIR=${libexecdir}
-exec @PYTHON@ @prefix@/share/ibus/setup/main.py $@
+exec ${PYTHON:-@PYTHON@} @prefix@/share/ibus/setup/main.py $@
```

And you could run `env PYTHON=/usr/bin/python3 ibus-setup`.

**Comment by thautwarm** [comment]
A more straightforward way is to change `ibus-setup`.
```shell
sudo emacs `which ibus-setup`
```
Then change 
```
exec python3 /usr/share/ibus/setup/main.py $@`
```
to
```
exec /usr/bin/python3 /usr/share/ibus/setup/main.py $@
```

**Comment by thautwarm** [comment]
IMO it deserves a commit to ibus.

**Comment by fujiwarat** [comment]
You issue would be an downstream issue and I don't agree with that change in Fedora.
