### ISSUE TITLE
ctrl+shift+e hijacked (hardcoded?) 

### ISSUE THREAD

**Issue by atomi** [ibus/ibus#2088]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Mint 19.1 
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
X-Cinnamon
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
x11
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
all
IBus version?: 
(Run `ibus version`)
IBus 1.5.17
Issue description:
removing ctrl+shift+e shortcut does not work

Steps to reproduce:
1. ibus preferences
1. Emoji tab
1. delete Emoji choice shortcuts
1. ctrl+shift+e is still hijacked

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes
Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no output

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes new install

**Comment by atomi** [comment]
Also "Input method framework" is set to IBus as well.

**Comment by atomi** [comment]
Looks like this was dropped in gtk 3 latest https://gitlab.gnome.org/GNOME/gtk/commit/66a7da8eb9cecc6fcc646a5f7a32ae9823738584

**Comment by atomi** [comment]
If anyone is having trouble with this and stuck using gtk 3.22 or lower switch to XIM.    
That fixed it for me.

**Comment by fujiwarat** [comment]
The shortcut keys can be customized with the latest ibus. Fedora 27 is no longer supported.
