### ISSUE TITLE
Amharic language Keyboard missing characters

### ISSUE THREAD

**Issue by barukasu** [ibus/ibus#2089]
Which distribution and version?: 
Ubuntu 18.04

Which desktop environment and version?: 
Gnome

Which session type?: 
X11

Which application and version?: 
All applications using system text input

IBus version?: 
1.5.17

Issue description:
**The Amharic keyboard is missing characters and conjugations.
If you look at the keyboard layout, there are several characters missing.
All of the keys A,E,I,O,U, Z have random ASCII characters that are not part of the Amharic language. 
There are no errors reported and the language switching works well. The keyboard just doesn't type the entire Amharic Alphabet.

Please take a look at the keyboard layout.**

![IBUS-m17n-amharic-keyboard](https://user-images.githubusercontent.com/7257403/54966044-6360b580-4f49-11e9-8282-45ae037799ae.png)

Steps to reproduce:
1. Install Ubuntu 18.04
2. Install Amharic language from the Install/Remove Languages
3. choose IBus as a keyboard input method system
4. Switch keyboard to Amharic and type

Can you reproduce your problem when you restart ibus-daemon? (yes / no):  yes

Do you see any errors when you run ibus-daemon with the verbose option?: NO ERRORS
No Errors are reported

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
> Switch keyboard to Amharic and type

I guess you use ibus-m17n Amharic.

Can you confirm your engine is `"m17n:am:sera"` when you enable Amharic and run `ibus engine` command?
If yes, you could report your issue to http://www.nongnu.org/m17n/

I confirmed I can insert U+FE67 with type "a" with the below patch after I modified am-sera.mim and run `ibus restart`:
```
--- /usr/share/m17n/am-sera.mim.orig
+++ /usr/share/m17n/am-sera.mim
@@ -362,7 +362,7 @@ For more information, see the page http:
   ("u" ?ኡ)
   ("U" ?ኡ)
   ("i" ?ኢ)
-  ("a" ?አ)
+  ("a" ?﹧)
   ("A" ?ኣ)
   ("E" ?ኤ)
   ;; ("ee" ?ኤ) ; Alef-E is rare vs Aynu-I, so ee = Aynu-I
```

I don't see what '?' expresses. CC'ing @pnemade

**Comment by pnemade** [comment]
@barukasu You modified the keymap hence you can type U+FE67 but I do not see that character part of https://unicode.org/charts/PDF/U1200.pdf and that character actually not present in Unicode character database. See http://unicode.org/charts/PDF/UFE50.pdf
I don't see what can be the bug here?
