### ISSUE TITLE
High CPU usage, unusable in GIMP

### ISSUE THREAD

**Issue by manhnt9** [ibus/ibus#2090]
### Which distribution and version?
Ubuntu 18.04

### Which desktop environment and version?
XFCE 4.12

### Which session type?
X11

### Which application and version?
GIMP 2.8 (apt) and GIMP 2.10 (snap)

### IBus version?
IBus 1.5.17

### Issue description
I discovered this issue on [Sep 8, 2018](https://github.com/teni-ime/ibus-teni/issues/32), after experimenting a while I think it's because of ibus core instead of input engines.
IBus causes high CPU usage when typing in GIMP. Sometimes it causes disfunction of the input engine.
Tested with 3 different Vietnamese input engine (ibus-teni, ibus-bamboo, ibus-unikey) and 2 GIMP versions (snap and apt).

### Steps to reproduce:
1. Open GIMP, Ctrl N to create new image
2. Press T to use text tool
3. Switch input method to Vietnamese
4. Start typing 

### Can you reproduce your problem when you restart ibus-daemon?
Yes.

### Do you see any errors when you run ibus-daemon with the verbose option?
Looks like a loop error.
```
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
```

### Screenshots
![](https://user-images.githubusercontent.com/11463928/45261201-f2cbce80-b426-11e8-8267-ea470c0c5587.png)

![](https://user-images.githubusercontent.com/11463928/48242671-e48e3480-e40e-11e8-850e-04273f892c22.png)

### Video
https://www.youtube.com/watch?v=k9OJqpqzsro

**Comment by fujiwarat** [comment]
I cannot reproduce your problem ibus 1.5.20 and ibus-unikey in Fedora 30.
Also it's strange when your ibus-x11 spends CPU time because GIMP should not use it.
Can you run ibus-daemon without `--xim` option and reproduce your problem?

**Comment by manhnt9** [comment]
Hi @fujiwarat, I always run ibus-daemon without --xim and the problem still presents.

**Comment by fujiwarat** [comment]
> I always run ibus-daemon without --xim and the problem still presents.

But you run ibus-daemon with --xim in your image file of CPU usage.

And then CPU 20% of ibus-daemon is not so high when you don't run ibus-x11?
Also can you reproduce your problem without --address option?

**Comment by manhnt9** [comment]
I'm not sure why it has --xim here. From what I can understand, ibus is constantly killed and respawned due to a loop error. I only have a startup config for ibus as `ibus-daemon` command.

**Comment by fujiwarat** [comment]
Can you attach the image of the CPU usage when you run ibus-daemon without --xim and --address ?

**Comment by manhnt9** [comment]
I kill my ibus and call `ibus-daemon` in terminal. I can't switch to another input method to test the bug. It happens with Vietnamese input with 3 different engines. English input is normal.

**Comment by fujiwarat** [comment]
I don't know why you said you always run ibus-daemon without --xim. If you can't switch to another input method, it means you don't run ibus-daemon without --xim every day.

**Comment by manhnt9** [comment]
Yeah I was misunderstanding my system. Normally I would have to add ibus-daemon to system's startup application so I did it and thought that was my constant config. But I've just removed the startup config and ibus still starts so I think the system does this automatically.

**Comment by fujiwarat** [comment]
Can you reproduce your problem with a new user account instead of the current one?

**Comment by fujiwarat** [comment]
ping

**Comment by manhnt9** [comment]
I've been busy so I haven't tested, will do it in this week. Thank you.

**Comment by qiangzhao** [comment]
@fujiwarat Hi:
I have tried in ibus-1.5.19 and Gimp 2.10, it works fine. So at least the latest edition dont have this problem.

**Comment by fujiwarat** [comment]
@qiangzhao I'm not sure if your issue was same.
Anyway it would be good to try ibus 1.5.20.

**Comment by qiangzhao** [comment]
@fujiwarat 
Ibus 1.5.20 also works fine with Gimp. but I confirmed 1.5.20 in Fedora 30 x86_64.

**Comment by qiangzhao** [comment]
I mean Ubuntu would be the same.

**Comment by manhnt9** [comment]
It only presents on Vietnamese input engines I think. Please try ibus-teni, ibus-bamboo or ibus-unikey if you can. Thanks.

**Comment by qiangzhao** [comment]
Yes, I use ibus-unikey. and the result is as below:
![1](https://user-images.githubusercontent.com/13212081/58313045-3e040100-7e3f-11e9-82fd-0079a0eb94b6.png)

**Comment by manhnt9** [comment]
Thanks, so there may be one suspicion left: my environment is XFCE. Other users with different desktop environments tell that they don't meet this issue. But I'm still having despite software upgrades.

**Comment by qiangzhao** [comment]
I think maybe you can have a check if other XFCE user have the same problem,  and this is very like a downstream's problem.

**Comment by manhnt9** [comment]
I've just tested with another user. It reproduces the problem. Slow typing and add ~10% to the CPU usage, some words aren't correctly modified by the input engine too.
![vlcsnap-2019-05-25-00h22m50s720](https://user-images.githubusercontent.com/11463928/58345779-5eee4580-7e83-11e9-8817-33c8075111c5.png)

**Comment by fujiwarat** [comment]
When you tested another user, how did you launch ibus-daemon?

**Comment by manhnt9** [comment]
I launch with `ibus-daemon -drx`.

**Comment by fujiwarat** [comment]
So can you reproduce your problem without `--xim` option with the new account?
You should check the process with `ps` command.

**Comment by manhnt9** [comment]
This time I ran with ibus-daemon -dr.
Normal CPU is 3-6 %, but when typing in GIMP, it's 14-30%.
Sometimes word doesn't processed right by my input engine.
I think it's time for some person to try reproducing this issue on XFCE as well.

**Comment by fujiwarat** [comment]
> Sometimes word doesn't processed right by my input engine.

Do you mean you sometimes can output Vietnamese with `ibus-daemon -dr` but sometimes doesn't?
And then I need to know which key sequences causes your problem.

**Comment by manhnt9** [comment]
From my basic observation, it's caused by a general issue so any keys, any time it can become wrong. As you can see in the first issue description, seems like ibus-daemon is killed by a loop bug then respawned. So I think it causes wrong Vietnamese output.

**Comment by fujiwarat** [comment]
> As you can see in the first issue description, seems like ibus-daemon is killed by a loop bug then respawned.

I don't see such a loop in your description but if you think so, it's good to connect the process of ibus-daemon with gdb. and you can call `where` command to get the backtrace when ibus-daemon dies.

% gdb --pid $PID
(gdb) where

**Comment by manhnt9** [comment]
Do I have to build ibus in debug mode? Anyways you can look at the first image, second process is spawned to kill ibus I think.

**Comment by fujiwarat** [comment]
```
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
2019/04/06 11:29:47 keyCode 0x001d keyval 0xffe3 | ￣ | 0
2019/04/06 11:29:47 keyCode 0x002a keyval 0xffe1 | ￡ | 0
```
Seems you mean this one. How did you get this log? I think the messages do not come from ibus.
I don't know which you indicate about the second process.

If you installed the ibus packages from your distribution, probably I think your distro provides the debug packages. E.g. Fedora provides ibus-debuginfo, ibus-gtk3-debuginfo, ibus-libs-debuginfo, ...

**Comment by manhnt9** [comment]
![](https://user-images.githubusercontent.com/11463928/48242671-e48e3480-e40e-11e8-850e-04273f892c22.png)

Second process in this image.
I get the console output by running ibus-daemon in verbose mode I guess.

**Comment by fujiwarat** [comment]
Did you really run `ibus-daemon -dr`? Your image is different.
Please test without `--xim`.
