### ISSUE TITLE
visual studio code - some Korean keys error

### ISSUE THREAD

**Issue by wonhyeongseo** [ibus/ibus#2091]
Which distribution and version?: Ubuntu 18.04.2 LTS

Which desktop environment and version?: ubuntu:GNOME

Which session type?: x11

Which application and version?: Visual Studio Code 1.32.3 

IBus version?: IBus 1.5.17

Issue description: Some characters do not render correctly on VSCode, and it is specific to IMEs in Ubuntu (I've tried fcitx, uim, and ibus). It is the same as this [issue](https://github.com/Microsoft/vscode/issues/10769) on VSCode, but the issuer did not mention the solution.
May you please show how to workaround or better, solve this?

Steps to reproduce:
1. Please refer to the linked issue.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
The issue describes the issue can be reproduce when the string is pasted to VSCode but copy & paste should not use any input methods.
I guess your problem can be reproduced without ibus.
