### ISSUE TITLE
CTRL+SHIFT+U stolen

### ISSUE THREAD

**Issue by gurgl** [ibus/ibus#2094]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
ubuntu 18.04

Which desktop environment and version?: 
gnome 3.28

Which session type?: 
x11

Which application and version?: 
intellij 18 community edition (but id guess this problem probebely can be reproduced in any application that can assign hokeys )

IBus version?: 
IBus 1.5.17

Issue description:
CTRL+SHIFT+u is impossible to assign as a shortcut in intellij because ibus is said to have stolen the shortcut (https://superuser.com/questions/358749/how-to-disable-ctrlshiftu-in-ubuntu-linux) 

Steps to reproduce:
1. Install ubuntu18.04
2. Install intellij 18+ 
3. Open a file in intelliij, mark some lower case text, press CRTL+SHIFT+U
4. observe that only  "u" is registered and not the shortcut associated to "CRTL+SHIFT+U"

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
no
Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no 

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):
yes

**Comment by fujiwarat** [comment]
1.5.19 or later provides the shortcut key customization with `ibus-setup` command.
If you use the old version, the workaround would be to run `env GTK_IM_MODULE=gtk-im-context-none intellij `
