### ISSUE TITLE
Unable to open the picture of keyboard layout for ibus-libzhuyin

### ISSUE THREAD

**Issue by laichiaheng** [ibus/ibus#2096]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Manjaro

Which desktop environment and version?: 
GNOME 3.32.1

Which session type?: 
X11

Which application and version?: 
gnome-control-center

IBus version?: 
IBus 1.5.20

Issue description:
Can't open the picture of keyboard layout.

Steps to reproduce:
1. Open gnome-control-center
2. Choose Region and Language
3. Click the button of ibus-libzhuyin
![2019-04-25 18-09-49 的螢幕擷圖](https://user-images.githubusercontent.com/9532105/56728466-6a1b5c00-6785-11e9-9b41-0a755c56b603.png)

Can you reproduce your problem when you restart ibus-daemon?  
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
current session already has an ibus-daemon.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
Because ibus-libzhuyin does not have any layouts and inherits the current layout.
