### ISSUE TITLE
error launching Ibus Preferences

### ISSUE THREAD

**Issue by pcnate** [ibus/ibus#2098]
Which distribution and version?: Ubuntu Pop!_OS 19.04

Which desktop environment and version?: Gnome 3.32.1

Which session type?:  X11

Which application and version?: ibus-setup

IBus version?: 1.5.19

Issue description:
Cannot launch `Ibus Preferences` from command line. Program not available though Applications Menu

When trying to execute `ibus-setup` on terminal as normal user i get the following traceback. If I run it as sudo I get a warning about user of the config file not being root which makes sense.
```
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 699, in <module>
    setup = Setup()
  File "/usr/share/ibus/setup/main.py", line 119, in __init__
    self.__init_ui()
  File "/usr/share/ibus/setup/main.py", line 412, in __init_ui
    self.__init_hotkeys()
  File "/usr/share/ibus/setup/main.py", line 129, in __init_hotkeys
    self.__init_hotkey(name, label)
  File "/usr/share/ibus/setup/main.py", line 143, in __init_hotkey
    entry.set_text("; ".join(shortcuts))
AttributeError: 'NoneType' object has no attribute 'set_text'
```

Steps to reproduce:
1. Open Terminal
1. Type `ibus-setup`

Can you reproduce your problem when you restart ibus-daemon? (yes / no): errors
(Run `ibus exit` and `ibus-daemon --xim &`)
```
pcnate@pop-os: ~$ current session already has an ibus-daemon.

[1]+  Exit 255                sudo ibus-daemon --xim
```

Do you see any errors when you run ibus-daemon with the verbose option?: errors
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
pcnate@pop-os: ~$ current session already has an ibus-daemon.

[1]+  Exit 255                sudo ibus-daemon --xim
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): checking on this

**Comment by fujiwarat** [comment]
I think you had a wrong installation.
Does your setup.ui include "entry_switch_engine", "entry_emoji_dialog" and "entry_unicode_dialog"?
``% grep entry_  /usr/share/ibus/setup/setup.ui``
