### ISSUE TITLE
Auto turn off

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#2099]
Mostly I just want to type a line or two of Chinese.

So my main problem is not remembering to turn on Chinese (via
CTRL+SPACE) but to turn it off later.

So maybe there could be a timed mode option, that turns off the input
mode after one minute etc. of non-use,
or better yet, turns it off upon switching windows, perhaps detected by
listening for the ALT-TAB X window switch... I don't know.

Else I start typing English and only after a few letters do I realize I still have Chinese mode enabled.

No I am not advocating bigger icons to remind me what mode I am in.

**Comment by jidanni** [comment]
Or maybe "one line mode:" turns off after one line of entry.

**Comment by fujiwarat** [comment]
I don't understand your problem. Please use the issue template.
Also probably I think your problem does not happen in ibus-anthy and it would be good to file your problem to your ibus engine. (You could run `ibus engine` to check your engine name)

**Comment by jidanni** [comment]
It is not a bug!
It is a wishlist item!

**Comment by jidanni** [comment]
Wouldn't automatic turnoff mode be good for all engines?

**Comment by fujiwarat** [comment]
What is the turnoff mode? As I noted, please use the bug template to describe your issue with the steps.

**Comment by jidanni** [comment]
We turn ibus, type some foreign language, and then turn it off.

 With a new one sentence mode, we turn on ibus, type some foreign language, and then when we press a period to end the sentence, ibus turns off automatically too!

Let's  say we didn't want to press that period, well pressing period then DEL is still pretty easy.

**Comment by fujiwarat** [comment]
IBus is always enabled and won't be disabled with any languages.

> Let's say we didn't want to press that period, well pressing period then DEL is still pretty easy.

I don't understand this too.

**Comment by jidanni** [comment]
I see. I mean "select next input method just for this sentence". And when a period is typed, insert the period, and the automatically revert to the previous input method.

**Comment by fujiwarat** [comment]
Your description is too short. What is the current input method engine, what is the previous input method engine, and why do you wish to revert the previous input method with a period.
Again, you can check the current input method with `ibus engine` command.

**Comment by jidanni** [comment]
xkb:us::eng, chewing

Sometimes the user just wants to enter one phrase in the other language

> 524 007 01 0    Datura metel L. 曼陀羅  Ⅳ：531
> 524 007 03 0    Datura suaveolens Humb. & Bonpl. ex Willd.      大花曼陀羅      Ⅳ：531

So maybe have an easier way to automatically switch back at period or final selection...

**Comment by fujiwarat** [comment]
I don' like to apply your issues to all languages then your issue would not be ibus core.
From your issue, I suppose to switch English and chewing modes instead of `xkb::us:eng` and chewing engines and you should talk with ibus-chewing with a report.
But I don't agree with switching English and chewing mode with period key too.
You could switch the modes with Shift key.
Also you could try ibus-libzhuyin.
