### ISSUE TITLE
ibus iso-codes iso_639-3.xml not found in CentOS 7

### ISSUE THREAD

**Issue by CentUser** [ibus/ibus#2101]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

CentOS 7 (Linux localhost.localdomain 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux)

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

GNOME Shell 3.28.3

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11 xorg-x11-server 1.20.1-5.3.el7_6
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

No app. Just install ibus commit:82a728de97308f6ce36c814e30a292f96e76cc13
and Using Python:Python 2.7.5
In python 2.7.5 shell execute: import ibus

IBus version?: 
(Run `ibus version`)
commit:82a728de97308f6ce36c814e30a292f96e76cc13
Issue description:

In CentOS 7 Version of specified, once one have got the iso-codes.noarch and iso-codes-devel installed using yum, he actually have one file : /usr/share/xml/iso-codes/iso_639_3.xml, which is not the same as ibus initialization procedure requested. 

There are two methods to get rid of this:
1. make a soft link in dir /usr/share/xml/iso-codes/ of name iso_639-3.xml to iso_639_3.xml
2. We change the code here to verify if we could found one iso_639_3.xml

Steps to reproduce:
1. None 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

CONTRIBUTOR COULD CLOSE THIS ISSUE AS YOU WISH, JUST POST IT HERE FOR CENTOS USERS WHO ENCOUNTERED THIS ISSUE.

**Comment by fujiwarat** [comment]
Thank you for the report.

**Comment by abdelilah-design** [comment]
Hi please i want restore my ipad and i can't see it in my PC.
Any Help Please !

Have a good year!
