### ISSUE TITLE
how to disable Ctrl+Shift+F in CentOS

### ISSUE THREAD

**Issue by sduqlsc** [ibus/ibus#2102]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
CentOS 7
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

MATE 1.16.2

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Eclipse IDEA

IBus version?: 
(Run `ibus version`)
1.5.17
Issue description:

Ctrl+Shift+F has conflicted with other applications
Steps to reproduce:
1. open IDE
1. Ctrl+Shift+F not working at all
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
Which ibus engine do you use? You can check it with `ibus engine` command.

ibus core does not bind Ctrl-Shift-F.

**Comment by sduqlsc** [comment]
@fujiwarat ibus-pinyin

**Comment by fujiwarat** [comment]
OK, I can reproduce your problem with ibus-libpinyin.
I'm not sure which mode in ibus-libpinyin @sduqlsc uses with Ctrl-Shift-F but I think it's good to enable Ctrl-Shift-F in English mode in ibus-libpinyin. Probably I will move this issue to ibus-libpinyin.
CC'ing @epico

**Comment by epico** [comment]
I think Ctrl+Shift+F is for Simplified Chinese and Traditional Chinese switch in ibus-libpinyin.

In higher version of ibus-libpinyin, the shortcut key can be customized.
But the version of ibus-libpinyin in CentOS 7, the shortcut key can't be changed.

**Comment by sduqlsc** [comment]
@epico thanks for reply, btw, any solution to upgrade heigher version on centos 7?

**Comment by epico** [comment]
Compile it youself with libpinyin and ibus-libpinyin, or open bug on Red Hat bugzilla.

**Comment by fujiwarat** [comment]
@epico Thank you.
Closing this issue.
