### ISSUE TITLE
ibus-table-chinese-wubi-jidian  can not use in IntelliJ IDEA

### ISSUE THREAD

**Issue by MzoroHaHa** [ibus/ibus#2106]
I can't input chinese in idea ,but can input in firefox or other tools;

CentOS Linux release 7.6.1810 

IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
Licensed to jetbrains js
Subscription is active until November 27, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 3.10.0-957.21.3.el7.x86_64

ibus.1.5.17.x86_64
ibus-table-chinese-wubi-jidian.noarch       1.4.6-3.el7

**Comment by fujiwarat** [comment]
I can input Chinese with ibus-table-chinese-wubi-jidian in Fedora 30:
![fujiwara-ibus-wubi-jidian](https://user-images.githubusercontent.com/105929/61020320-42c54a00-a3d8-11e9-81e2-725a7fac71fb.png)

Did you run ibus-daemon with `--xim` argument?
