### ISSUE TITLE
Packaging an ibus engine with flatpak

### ISSUE THREAD

**Issue by subins2000** [ibus/ibus#2109]
Has anyone tried packaging an ibus engine with flatpak ? I'm trying to do one with [libvarnam-ibus](https://github.com/varnamproject/libvarnam-ibus).

Would like to know if someone has already done it so that I can retrace it easily for `varnam`.

**Comment by fujiwarat** [comment]
You could work in your distro to package an engine and I don't think your issue is relative with ibus upstream.
