### ISSUE TITLE
自定义引号类型

### ISSUE THREAD

**Issue by iridiumcao** [ibus/ibus#2113]
Which distribution and version?: 
Ubuntu 19.04

Which desktop environment and version?: 
Gnome 3

Which session type?: 
X11

Which application and version?: 
gedit 3.24

IBus version?: 
IBus 1.5.19

Issue description:
不能配置引号类型，比如可以选择引号类型为 “” ‘’ 「」 『』。
（参：https://github.com/phuang/ibus-pinyin/issues/4）

Steps to reproduce:
1. 切换到 iBus 拼音输入
1. 打引号

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account?:
yes

**Comment by fujiwarat** [comment]
This is not an ibus core issue.
@iridiumcao can you report the same issue to https://github.com/libpinyin/ibus-libpinyin/issues ?
CC'ing @epico

**Comment by epico** [comment]
Except for 「」, other punctuation can be input directly.

「」can be input with Traditional Chinese mode.

**Comment by iridiumcao** [comment]
谢谢，但我这里是希望简体中文模式下也能输出直角引号。

**Comment by iridiumcao** [comment]
@fujiwarat can you re-open this issue?
The Simplified Chinese mode does not support 「」.
And there is not an interface to define word by user himself.

**Comment by iridiumcao** [comment]
I'll report it to  https://github.com/libpinyin/ibus-libpinyin/issues.
Thank you @fujiwarat, @epico
