### ISSUE TITLE
Cannot cycle through more than three input methods

### ISSUE THREAD

**Issue by guicho271828** [ibus/ibus#2115]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Ubuntu 16.04

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Cinnamon 3.6.7

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Any

IBus version?: 
(Run `ibus version`)
1.5.11

Issue description:
Hitting the trigger key while the second IM is selected will switch back to the first IM

Steps to reproduce:

Add English, Japanese, German to the list of keyboards
hit shift-2 to check " or @ , also shift-3 to check # or §
also check the status in the system tray
screenshots:
![Screenshot from 2019-08-20 20-04-23](https://user-images.githubusercontent.com/1321968/63392799-34c6f980-c386-11e9-80ed-6daa57472700.png)
![Screenshot from 2019-08-20 20-04-28](https://user-images.githubusercontent.com/1321968/63392800-34c6f980-c386-11e9-828c-5944ae1588bf.png)
![Screenshot from 2019-08-20 20-04-32](https://user-images.githubusercontent.com/1321968/63392801-34c6f980-c386-11e9-917a-7d7ec44a8cfb.png)
![Screenshot from 2019-08-20 20-05-31](https://user-images.githubusercontent.com/1321968/63392802-34c6f980-c386-11e9-8fd0-3345e2da206c.png)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
> /usr/share/ibus/setup/main.py:38: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
>  from gi.repository import Gtk
> /usr/share/ibus/setup/main.py:39: PyGIWarning: IBus was imported without specifying a version first. Use gi.require_version('IBus', '1.0') before import to ensure that the right version gets loaded.
 > from gi.repository import IBus

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
not verified yet

**Comment by fujiwarat** [comment]
I think your Cinnamon is a little old. Fedora 31 now uses Cinnamon 4.2.3.
You need to use Control-Insert but not Zenkaku_Hankaku to switch three IMEs.
E.g. Control-Insert switches to the 2nd engine. Control-Insert-Insert switches to the 3rd engine.
Can you attach the screenshot of the desktop after you type Control-Insert ?

**Comment by guicho271828** [comment]
Thanks, I now see how it works ... 

> Control-Insert switches to the 2nd engine. Control-Insert-Insert switches to the 3rd engine.

So hitting the trigger key more than twice will open the small switcher window that you can cycle through the IMs, and otherwise it just goes back and forth. I get it.

Well, I'd say this is unintuitive and violating the law of least surprise though. You can at least note it somewhere in the setting window.
