### ISSUE TITLE
g_dbus_server_new_sync() is failed with address unix:tmpdir=/tmp/ibus

### ISSUE THREAD

**Issue by tsutsui** [ibus/ibus#2116]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
I'm trying to update pkgsrc/inputmethod/ibus to 1.5.21 on NetBSD/i386 8.1.

Which desktop environment and version?: 
jwm-2.3.7

Which session type?: 
X11

Which application and version?: 
ibus-daemon itself

IBus version?: 
ibus-daemon - Version 1.5.21

Issue description:
ibus-daemon gets SIGTRAP on starting if there is no /tmp/ibus dir.
```
% ibus-daemon --xim 

(ibus-daemon:7329): IBUS-ERROR **: 19:44:52.627: g_dbus_server_new_sync() is failed with address unix:tmpdir=/tmp/ibus and guid 2c81de5f383523c2f172b56f5d650a1c: Error binding to address: No such file or directory
Trace/BPT trap (core dumped)
```
Once /tmp/ibus is prepared manually it works fine:
```
% ibus-daemon --xim 

(ibus-daemon:7329): IBUS-ERROR **: 19:46:52.627: g_dbus_server_new_sync() is failed with address unix:tmpdir=/tmp/ibus and guid 2c81de5f383523c2f172b56f5d650a1c: Error binding to address: No such file or directory
Trace/BPT trap (core dumped)
% mkdir /tmp/ibus
% ibus-daemon --xim
```
/tmp/ibus was introduced on #2097 merge, but I wonder if /tmp/ibus is automatically created on Linux distributions (but not on *BSD)?

Steps to reproduce:
1. rm -rf /tmp/ibus
1. ibus-daemon --xim --replace

on NetBSD/i386 8.1. ibus 1.5.20 worked fine.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
% ibus-daemon --xim --verbose

(ibus-daemon:12437): IBUS-ERROR **: 19:45:03.825: g_dbus_server_new_sync() is failed with address unix:tmpdir=/tmp/ibus and guid e23141b43bcddf8617d7e2f45d6509af: Error binding to address: No such file or directory
Trace/BPT trap
% 
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by lantw44** [comment]
I just saw the same problem on FreeBSD with GNOME desktop. I tried to replace the `ibus-daemon` of the session with `ibus-daemon -r --xim --panel disable`, but it crashed because of missing `/tmp/ibus` directory.

**Comment by fujiwarat** [comment]
CC'ing @gunnarhj

**Comment by fujiwarat** [comment]
I created the tentative patch above.
Does it work for you?

**Comment by lantw44** [comment]
If the default is still `/tmp/ibus`, what will happen if `/tmp/ibus` already exists but owned by a different user? `chmod 0777` doesn't look correct, either, because other users can delete your file.

**Comment by fujiwarat** [comment]
I updated the patch a little. I think other users cannot delete your file in chmod 0777 for the directory since the file permission is different?

**Comment by lantw44** [comment]
> I think other users cannot delete your file in chmod 0777 for the directory since the file permission is different?

No, 0777 allows anyone to delete files in the directory, but I think it isn't the biggest problem. The problem of using `/tmp/ibus` is that a malicious user can create `/tmp/ibus` before ibus-daemon is started. The user can just chmod it to 0000 and crash everybody's ibus-daemon.

```
$ id
uid=1001(lantw44) gid=1001(lantw44) groups=1001(lantw44),0(wheel),44(video),920(vboxusers),2000(nas),2001(libvirt)
$ id testing
uid=1002(testing) gid=1002(testing) groups=1002(testing)
$ ls -lR /tmp/ibus
total 0
srwxr-xr-x  1 lantw44  wheel  0  8月 29 18:20 dbus-NlgPb5wA=
srwxr-xr-x  1 lantw44  wheel  0  8月 29 18:21 dbus-tY5Uy96M=
$ sudo -u testing rm /tmp/ibus/*
Password:
override rwxr-xr-x lantw44/wheel for /tmp/ibus/dbus-NlgPb5wA? y
override rwxr-xr-x lantw44/wheel for /tmp/ibus/dbus-tY5Uy96M? y
$ ls -lR /tmp/ibus
total 0
```

**Comment by fujiwarat** [comment]
OK, seems only the solution is to revert the patch of #2097

**Comment by lantw44** [comment]
If we really want to have `ibus` in the directory name, `/tmp/ibus-XXXXXXXX` with X filled by random characters may be used in a similar way to `mktemp -d`. ibus-daemon must be able to retry with a different name if the name is already used.

**Comment by gunnarhj** [comment]
@fujiwarat: The rational for suggesting `/tmp/ibus` is in #2095. We've had it in Ubuntu for a few years without issues known to me, and I decided to suggest it upstream to reduce the delta. If it causes issues for other distros, we can of course keep doing it in Ubuntu only.

@lantw44's idea with a `mktemp` like solution seems to be an option.

**Comment by tsutsui** [comment]
Note pulseaudio use /tmp/pulse-XXXXXXXXXX with the following code:
https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/pulsecore/core-util.c?h=v12.2#n1756

**Comment by jdstrand** [comment]
@gunnarhj - note that the patch in https://github.com/ibus/ibus/issues/2095 you listed my patch which discusses abstract sockets (the default as of 1.4.0). Abstract sockets are Linux only. For non-Linux, there needs to be a corresponding g_mkdir_with_parents() or similar to ensure that /tmp/ibus/ exists. Alternatively, you could use unix:tmpdir=/tmp/ibus on Linux and unix:tmpdir=/tmp everywhere else. The former is preferable IME.

**Comment by gunnarhj** [comment]
@jdstrand: So code wise:
```
#ifndef __linux__
g_mkdir_with_parents ("/tmp/ibus", 0777);
#endif
```
However, if #2121 (Arch Linux) is affected by this, I suppose that's not the whole truth.

**Comment by fujiwarat** [comment]
OK, I updated the patch.

**Comment by gunnarhj** [comment]
@fujiwarat: Looks like you have addressed all aspects of this which were pointed out above. FWIW I tested it successfully on Ubuntu.

Thanks!

**Comment by lantw44** [comment]
```c
gchar *g_address = "unix:tmpdir=${XDG_RUNTIME_DIR:-'/var/run/user/$UID'}/ibus";
```
What will happen if `XDG_RUNTIME_DIR` isn't set and `/var/run/user` doesn't exist? I just tested that it is possible to `ssh` into a FreeBSD machine and type `vncserver` to get a GNOME desktop without `XDG_RUNTIME_DIR` or `/var/run/user`.

```c
sh_command_line = g_strdup_printf ("sh -c \"echo %s\"", g_address);
if (!g_spawn_command_line_sync (sh_command_line,
                                &standard_output,
                                &standard_error,
                                &exit_status,
                                &error)) {
    g_warning ("Failed in echo: %s", error->message);
    g_clear_error (&error);
}
```
I think it will be easier to read if it uses `g_spawn_sync` directly, so GLib doesn't have to parse the command line. `%s` in `sh_command_line` should be quoted with double quotes to prevent unnecessary word splitting and globbing (although it is unlikely to cause problems for `g_address`).

**Comment by tsutsui** [comment]
> OK, I updated the patch.

Unfortunately https://github.com/fujiwarat/ibus/commit/2e46254f919d55f5925e6eb4605e71a6e8f89603 doesn't work on my NetBSD/i386 8.1 envronment:
```
% ibus-daemon --replace --daemonize --xim
% ibus-daemon --replace --xim

(ibus-daemon:15822): IBUS-ERROR **: 01:13:47.060: mkdir is failed in: /var/run/user/100/ibus: Permission denied
Trace/BPT trap (core dumped)
%
```

At least on NetBSD and pkgsrc, /var/run is not user writable and `ibus-daemon` is not setuid'ed.
```
mirage-% ls -ld /var/run
drwxr-xr-x  10 root  wheel  1024 Aug 25 23:30 /var/run/
% ls -l /usr/pkg/bin/ibus-daemon 
-rwxr-xr-x  1 root  wheel  171708 Sep  1 01:12 /usr/pkg/bin/ibus-daemon*
% 
```

**Comment by ohk2kt3t4** [comment]
So the original issue was that the default ibus-daemon socket file "/tmp/dbus-..." is indistinguishable from dbus-daemon socket files, so we need to change the default ibus-daemon socket file location or name.

- ibus-daemon specified "unix:tmpdir=/tmp" as the default socket file location. 
- When a directory is passed to g_dbus_server_new_sync it [creates a socket file](https://github.com/GNOME/glib/blob/b9e27b77ad86e5870015a98fdecf5d5a23dba699/gio/gdbusserver.c#L704-L717) at that path with the format "dbus-12345678" (it will be abstract if supported by the OS). 
- However as the "dbus-" prefix is hardcoded in glib, we decided to move the socket path to "unix:tmpdir=/tmp/ibus", however this has lead to some issues as above.

Would it be simpler if we set the socket filename ourselves instead and left the path as /tmp?

e.g. 
- generate random file name ibus-123456.socket
- set default socket to "unix:abstract=/tmp/ibus-123456.socket" on Linux systems and "unix:path=/tmp/ibus-123456.socket" on BSD/etc.

**Comment by fujiwarat** [comment]
I thought if your distro would not have `/var/run/user`, your IBus package could own the directory. But probably that way does not resolve the ssh login.
My understanding is `/run/user` is created by systemd with `/usr/lib/tmpfiles.d/systemd.conf` and /var/run is a sym link of /run.

> I think it will be easier to read if it uses g_spawn_sync directly,

Thank you.

> generate random file name ibus-12345678.socket

I think this means to own the implementation of g_dbus_server_new_sync() in ibus and I have a bit concern to maintain the owned API. Probably I think it's better to enhance glib.

Now I'm thinking:
1. sh can be configurable by configure.ac. (/bin/sh vs /usr/bin/sh and the default is /bin/sh)
2. echo can be configurable by configure.ac (/bin/echo vs /usr/bin/echo and the default is /bin/echo)
3. g_address can be configurable by configure.ac (the default is /var/run/user/$UID)
4. if invoking sh is a heavy performance. If we need only XDG_RUNTIME_DIR and UID, we could replace them without forking sh.

**Comment by ohk2kt3t4** [comment]
> I think this means to own the implementation of g_dbus_server_new_sync() in ibus and I have a bit concern to maintain the owned API. Probably I think it's better to enhance glib.

There might be a misunderstanding here, ibus just has to generate a random filename for the socket, similar to [what PulseAudio does](https://cgit.freedesktop.org/pulseaudio/pulseaudio/tree/src/pulsecore/core-util.c?h=v12.2#n1756) for generating its socket directory linked above. So basically the same as when a user passes an address themselves using --address arg, except ibus will generate the filename. To me it seems simpler than dealing with all the issues above.

**Comment by fujiwarat** [comment]
OK, I see to send "unix:abstract" to g_dbus_server_new_sync() instead of "unix:tmpdir".
But probably I think the default /var/run/user/$UID/ibus/dbus-* is better than /tmp/ibus-* ?

**Comment by ohk2kt3t4** [comment]
Yeah it was just a suggestion to solve the original issue regarding the filename being similar to dbus-daemon socket filenames. 

Changing the default directory to /var/run/... in order to conform with FHS is another issue I guess, but it happens to solve this one too.

**Comment by lantw44** [comment]
> I thought if your distro would not have `/var/run/user`, your IBus package could own the directory. But probably that way does not resolve the ssh login.

Since ibus-daemon isn't a privileged process, I doubt if it can be implemented securely. If the permission of `/var/run/user` has to be 1777, it has the same problem as `/tmp/ibus`. A malicious user can just create thousands of directories under `/var/run/user` and block other people from using IBus.

I am not sure what is the status of `/var/run/user` on NetBSD. On FreeBSD, it is possible to have `/var/run/user` and `XDG_RUNTIME_DIR` by using ConsoleKit2. However, since most PAM configurations, such as `sshd` and `login`, doesn't use to `pam_ck_connector.so` register a session with ConsoleKit2, it is likely that ConsoleKit2 doesn't know the login and doesn't create the directory for the user. On my system, the only PAM configuration file having `pam_ck_connector.so` is `gdm-password`.

> 4\. if invoking sh is a heavy performance. If we need only XDG_RUNTIME_DIR and UID, we could replace them without forking sh.

I didn't suggest that invoking sh is slow, but I did think that using a shell is unnecessary in this case.

> But probably I think the default /var/run/user/$UID/ibus/dbus-* is better than /tmp/ibus-* ?

Yes, it is better, but `XDG_RUNTIME_DIR` isn't guaranteed to exist. It should be able to fallback to `/tmp` or `XDG_CACHE_HOME` instead of just crashing.

**Comment by fujiwarat** [comment]
I updated the patch.

**Comment by tsutsui** [comment]
> I updated the patch.

https://github.com/fujiwarat/ibus/commit/2ade7d13985cca44814bd721cba587772669fb5c works fine on NetBSD/i386 8.1.

`config.h` has:
```
/* The default socket directory to connect ibus-daemon. */
#define IBUS_SOCKET_DIR "unix:tmpdir=/tmp"
```
as expected.

**Comment by fujiwarat** [comment]
>  I doubt if it can be implemented securely. If the permission of /var/run/user has to be 1777

Yeah, you're right. I see the directory cannot be created by the package manager.

> Yes, it is better, but XDG_RUNTIME_DIR isn't guaranteed to exist. It should be able to fallback to /tmp or XDG_CACHE_HOME instead of just crashing.

Sorry, I don't know the status  of `/var/run/user` on BSD systems but I hope BSD systems will have XDG_RUNTIME_DIR in the future to follow the freedesktop specs.
Probably I'd simplify the logic to decide the default directory in configure.ac and I also can add to parse XDG_CACHE_HOME in server.c

**Comment by lantw44** [comment]
The new patch works fine on FreeBSD.

**Comment by fujiwarat** [comment]
Thank you all.
The update patch is the almost final.

**Comment by tsutsui** [comment]
https://github.com/fujiwarat/ibus/commit/482395cead8560f9dabfe17863588ed22efffeee with changes in #2128 also works on NetBSD/i386 8.1. Thanks.

**Comment by ohk2kt3t4** [comment]
Would it be possible to tag a new release (1.5.22) which includes this commit?

**Comment by fujiwarat** [comment]
Yes, 1.5.22 will includes this commit however I think we need furthermore testings on the commits for a while to release 1.5.22 and basically 1.5.22 will follow the next GNOME 3.36 schedule.
Probably I will import this commit to Fedora as an internal patch for the testing and I think you also might consider to revert [the change](https://github.com/ibus/ibus/commit/91a256163427f04eb7763196b4ffe553911d2e01) as an internal patch at the moment to avoid the BSD systems' crash.

**Comment by fujiwarat** [comment]
Since ibus-daemon can be launched with `su` or `sudo` command, I think XDG_RUNTIME_DIR is not useful for ibus.
I will change the default value $XDG_RUNTIME_DIR/ibus to $XDG_CONFIG_HOME for Linux:
https://github.com/fujiwarat/ibus/commit/66e9e8feef1ac595e9d6dac4bba4fdc0dfeced51
