### ISSUE TITLE
manpage section mismatch on ui/gtk3/ibus-emoji.7.in

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2119]
https://github.com/ibus/ibus/blob/ae0040c73466bb6e78fce5e669a55fcce6ffd16d/ui/gtk3/ibus-emoji.7.in#L5

I got this Lintian warning while building debian package:
```
W: ibus: manpage-section-mismatch usr/share/man/man7/ibus-emoji.7.gz:5 7 != 1
```

**Comment by fujiwarat** [comment]
Thank you.
