### ISSUE TITLE
只要是electron研发的软件都存在输入法选词框，错位的问题。

### ISSUE THREAD

**Issue by ca2ju3** [ibus/ibus#2120]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 18.04.3 LTS

Which desktop environment and version?: 
GNOME Shell 3.28.4

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
electron研发的软件

IBus version?: 
IBus 1.5.17

Issue description:
只要是electron研发的软件都存在输入法选词框，错位的问题。
分辨率为3000 * 2000
200%的比例放大

**Comment by fujiwarat** [comment]
Duplicate of #1988

**Comment by AlynxZhou** [comment]
I think this is not an ibus bug, I suggest @ca2ju3 to check the chromium version that your electron uses, this bug is solved after chromium 70 at least, and electron may not use the latest version of chromium.

**Comment by ca2ju3** [comment]
I see. Thanks.
