### ISSUE TITLE
Ibus crashes repeatedly when attempting to unlock gnome session

### ISSUE THREAD

**Issue by jacobmischka** [ibus/ibus#2121]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
GNOME 3.32

Which session type?: 
Both

Which application and version?: 
GDM

IBus version?: 
1.5.21

Issue description:

When attempting to unlock after sleep, keyboard becomes unresponsive due to ibus crashing in a loop. On X, it's possible to slowly type my password until it's complete and log back in, after which it continues crashing in a loop for a while but eventually seems to stop. On Wayland, the crashes break Gnome Shell and the login session is lost. After downgrading to 1.5.20 I no longer experience the issue.

Steps to reproduce:
1. Log into gnome session
1. Lock the session
1. Attempt to unlock session

---

**Admittedly, I have not performed the following steps, because now that I've downgraded and have a functional session again I don't want to go back at the moment. Apologies. I know I should wait to report this until I've done so, but I would rather submit something incomplete and update later than forget to entirely.**

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
Seems Arch Linux has the similar issue with #2116 ?
How about running `mkdir /tmp/ibus` before you run ibus-daemon ?

**Comment by jacobmischka** [comment]
Oh wow, I copied the stacktrace and just forgot to paste it, so sorry.

<details>
<summary>
Stacktrace
</summary>
<pre>
Aug 28 09:39:01 mischka-work systemd-coredump[22974]: Process 22918 (ibus-daemon) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 22918:
                                                      #0  0x000055eafbb98859 n/a (ibus-daemon)
                                                      #1  0x00007f4c9430d584 n/a (libgio-2.0.so.0)
                                                      #2  0x00007f4c94312a87 n/a (libgio-2.0.so.0)
                                                      #3  0x00007f4c942b46fd n/a (libgio-2.0.so.0)
                                                      #4  0x00007f4c9430d584 n/a (libgio-2.0.so.0)
                                                      #5  0x00007f4c94312a87 n/a (libgio-2.0.so.0)
                                                      #6  0x00007f4c942c38a0 n/a (libgio-2.0.so.0)
                                                      #7  0x00007f4c9430d584 n/a (libgio-2.0.so.0)
                                                      #8  0x00007f4c9430d5b9 n/a (libgio-2.0.so.0)
                                                      #9  0x00007f4c9413ebb0 g_main_context_dispatch (libglib-2.0.so.0)
                                                      #10 0x00007f4c94140b11 n/a (libglib-2.0.so.0)
                                                      #11 0x00007f4c94141a63 g_main_loop_run (libglib-2.0.so.0)
                                                      #12 0x000055eafbb9debe n/a (ibus-daemon)
                                                      #13 0x000055eafbb89346 n/a (ibus-daemon)
                                                      #14 0x00007f4c93f18ee3 __libc_start_main (libc.so.6)
                                                      #15 0x000055eafbb8960e n/a (ibus-daemon)
                                                      
                                                      Stack trace of thread 22929:
                                                      #0  0x00007f4c93fe8e3d syscall (libc.so.6)
                                                      #1  0x00007f4c940f211b g_cond_wait_until (libglib-2.0.so.0)
                                                      #2  0x00007f4c9416f203 n/a (libglib-2.0.so.0)
                                                      #3  0x00007f4c94116e4b n/a (libglib-2.0.so.0)
                                                      #4  0x00007f4c9411da31 n/a (libglib-2.0.so.0)
                                                      #5  0x00007f4c940be57f start_thread (libpthread.so.0)
                                                      #6  0x00007f4c93fee0e3 __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 22927:
                                                      #0  0x00007f4c940c8636 waitpid (libpthread.so.0)
                                                      #1  0x00007f4c941399de n/a (libglib-2.0.so.0)
                                                      #2  0x00007f4c94140bba n/a (libglib-2.0.so.0)
                                                      #3  0x00007f4c9411da31 n/a (libglib-2.0.so.0)
                                                      #4  0x00007f4c940be57f start_thread (libpthread.so.0)
                                                      #5  0x00007f4c93fee0e3 __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 22928:
                                                      #0  0x00007f4c93fe3667 __poll (libc.so.6)
                                                      #1  0x00007f4c94140a80 n/a (libglib-2.0.so.0)
                                                      #2  0x00007f4c94141a63 g_main_loop_run (libglib-2.0.so.0)
                                                      #3  0x00007f4c942ada38 n/a (libgio-2.0.so.0)
                                                      #4  0x00007f4c9411da31 n/a (libglib-2.0.so.0)
                                                      #5  0x00007f4c940be57f start_thread (libpthread.so.0)
                                                      #6  0x00007f4c93fee0e3 __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 22936:
                                                      #0  0x00007f4c93fe8e3d syscall (libc.so.6)
                                                      #1  0x00007f4c940f211b g_cond_wait_until (libglib-2.0.so.0)
                                                      #2  0x00007f4c9416f203 n/a (libglib-2.0.so.0)
                                                      #3  0x00007f4c94116e4b n/a (libglib-2.0.so.0)
                                                      #4  0x00007f4c9411da31 n/a (libglib-2.0.so.0)
                                                      #5  0x00007f4c940be57f start_thread (libpthread.so.0)
                                                      #6  0x00007f4c93fee0e3 __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 22934:
                                                      #0  0x00007f4c93fe8e3d syscall (libc.so.6)
                                                      #1  0x00007f4c940f211b g_cond_wait_until (libglib-2.0.so.0)
                                                      #2  0x00007f4c9416f203 n/a (libglib-2.0.so.0)
                                                      #3  0x00007f4c94116e4b n/a (libglib-2.0.so.0)
                                                      #4  0x00007f4c9411da31 n/a (libglib-2.0.so.0)
                                                      #5  0x00007f4c940be57f start_thread (libpthread.so.0)
                                                      #6  0x00007f4c93fee0e3 __clone (libc.so.6)
Aug 28 09:39:01 mischka-work audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=getty@tty5 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 28 09:39:01 mischka-work systemd[1]: Started Getty on tty5.
Aug 28 09:39:01 mischka-work kernel: rfkill: input handler enabled
Aug 28 09:39:01 mischka-work systemd[1]: systemd-coredump@120-22966-0.service: Succeeded.
Aug 28 09:39:01 mischka-work audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@120-22966-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Aug 28 09:39:01 mischka-work systemd-coredump[22969]: Process 22953 (ibus-engine-sim) of user 1000 dumped core.
                                                      
                                                      Stack trace of thread 22953:
                                                      #0  0x00007f41f8621755 raise (libc.so.6)
                                                      #1  0x00007f41f860c851 abort (libc.so.6)
                                                      #2  0x00007f41f8663a38 __libc_message (libc.so.6)
                                                      #3  0x00007f41f866a25a malloc_printerr (libc.so.6)
                                                      #4  0x00007f41f866ba6e _int_free (libc.so.6)
                                                      #5  0x00007f41f8939237 n/a (libibus-1.0.so.5)
                                                      #6  0x00007f41f8815d28 g_list_foreach (libglib-2.0.so.0)
                                                      #7  0x00007f41f88170fc g_list_free_full (libglib-2.0.so.0)
                                                      #8  0x00007f41f893aa1d ibus_compose_table_new_with_file (libibus-1.0.so.5)
                                                      #9  0x00007f41f893b0c1 ibus_compose_table_list_add_file (libibus-1.0.so.5)
                                                      #10 0x00007f41f8953626 ibus_engine_simple_add_compose_file (libibus-1.0.so.5)
                                                      #11 0x00007f41f89538ec ibus_engine_simple_add_table_by_locale (libibus-1.0.so.5)
                                                      #12 0x0000562ea1ae21e0 n/a (ibus-engine-simple)
                                                      #13 0x00007f41f8812bb0 g_main_context_dispatch (libglib-2.0.so.0)
                                                      #14 0x00007f41f8814b11 n/a (libglib-2.0.so.0)
                                                      #15 0x00007f41f8815a63 g_main_loop_run (libglib-2.0.so.0)
                                                      #16 0x00007f41f8963a1e ibus_main (libibus-1.0.so.5)
                                                      #17 0x0000562ea1ae2679 n/a (ibus-engine-simple)
                                                      #18 0x00007f41f860dee3 __libc_start_main (libc.so.6)
                                                      #19 0x0000562ea1ae205e n/a (ibus-engine-simple)
                                                      
                                                      Stack trace of thread 22960:
                                                      #0  0x00007f41f86d8667 __poll (libc.so.6)
                                                      #1  0x00007f41f8814a80 n/a (libglib-2.0.so.0)
                                                      #2  0x00007f41f8814b51 g_main_context_iteration (libglib-2.0.so.0)
                                                      #3  0x00007f41f8814ba2 n/a (libglib-2.0.so.0)
                                                      #4  0x00007f41f87f1a31 n/a (libglib-2.0.so.0)
                                                      #5  0x00007f41f83a657f start_thread (libpthread.so.0)
                                                      #6  0x00007f41f86e30e3 __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 22962:
                                                      #0  0x00007f41f86d8667 __poll (libc.so.6)
                                                      #1  0x00007f41f8814a80 n/a (libglib-2.0.so.0)
                                                      #2  0x00007f41f8815a63 g_main_loop_run (libglib-2.0.so.0)
                                                      #3  0x00007f41f8497a38 n/a (libgio-2.0.so.0)
                                                      #4  0x00007f41f87f1a31 n/a (libglib-2.0.so.0)
                                                      #5  0x00007f41f83a657f start_thread (libpthread.so.0)
                                                      #6  0x00007f41f86e30e3 __clone (libc.so.6)
</pre>
</details>

I'll give that a try as soon as I get a chance, thanks!

**Comment by jacobmischka** [comment]
Creating `/tmp/ibus` does indeed prevent the crashes. Closing as a duplicate of #2116.

**Comment by jacobmischka** [comment]
Sorry, I lied, it's still happening.

**Comment by fujiwarat** [comment]
You don't answer of one of the issue template:

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
@jacobmischka any updates?

**Comment by jacobmischka** [comment]
Sorry for the delayed response. I recently got a new machine, and just installed ibus last night. 1.5.21 crashes immediately for me on the new machine as well.

<details><summary>journalctl excerpt</summary>
<pre>
Nov 16 14:12:30 mischka-laptop gnome-shell[7179]: Errors from xkbcomp are not fatal to the X server
Nov 16 14:12:30 mischka-laptop gnome-shell[7179]: >                   X11 cannot support keycodes above 255.
Nov 16 14:12:30 mischka-laptop gnome-shell[7179]: > Warning:          Unsupported maximum keycode 569, clipping.
Nov 16 14:12:30 mischka-laptop gnome-shell[7179]: The XKEYBOARD keymap compiler (xkbcomp) reports:
Nov 16 14:12:30 mischka-laptop electron[7628]: Version: 4.6.0
Nov 16 14:12:29 mischka-laptop systemd[1211]: Reached target GNOME Date & Time handling.
Nov 16 14:12:29 mischka-laptop systemd[1211]: Started GNOME Date & Time handling.
Nov 16 14:12:29 mischka-laptop gnome-shell[7179]: JS ERROR: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.Failed: Set global engine failed: The connection is closed
                                                  setEngine/<@resource:///org/gnome/shell/misc/ibusManager.js:236:21
Nov 16 14:12:29 mischka-laptop audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@4-7563-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Nov 16 14:12:29 mischka-laptop kernel: audit: type=1131 audit(1573935149.897:180): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@4-7563-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? >
Nov 16 14:12:29 mischka-laptop systemd[1]: systemd-coredump@4-7563-0.service: Succeeded.
Nov 16 14:12:29 mischka-laptop systemd-coredump[7570]: Process 7517 (ibus-engine-sim) of user 1000 dumped core.
                                                       
                                                       Stack trace of thread 7517:
                                                       #0  0x00007f28bc25ff25 raise (libc.so.6)
                                                       #1  0x00007f28bc249897 abort (libc.so.6)
                                                       #2  0x00007f28bc2a3258 __libc_message (libc.so.6)
                                                       #3  0x00007f28bc2aa77a malloc_printerr (libc.so.6)
                                                       #4  0x00007f28bc2ac1cc _int_free (libc.so.6)
                                                       #5  0x00007f28bc57d237 n/a (libibus-1.0.so.5)
                                                       #6  0x00007f28bc458498 g_list_foreach (libglib-2.0.so.0)
                                                       #7  0x00007f28bc45999c g_list_free_full (libglib-2.0.so.0)
                                                       #8  0x00007f28bc57ea1d ibus_compose_table_new_with_file (libibus-1.0.so.5)
                                                       #9  0x00007f28bc57f0c1 ibus_compose_table_list_add_file (libibus-1.0.so.5)
                                                       #10 0x00007f28bc597626 ibus_engine_simple_add_compose_file (libibus-1.0.so.5)
                                                       #11 0x00007f28bc5978ec ibus_engine_simple_add_table_by_locale (libibus-1.0.so.5)
                                                       #12 0x000055894d2b51e0 n/a (ibus-engine-simple)
                                                       #13 0x00007f28bc4552cf g_main_context_dispatch (libglib-2.0.so.0)
                                                       #14 0x00007f28bc457211 n/a (libglib-2.0.so.0)
                                                       #15 0x00007f28bc458123 g_main_loop_run (libglib-2.0.so.0)
                                                       #16 0x00007f28bc5a7a1e ibus_main (libibus-1.0.so.5)
                                                       #17 0x000055894d2b5679 n/a (ibus-engine-simple)
                                                       #18 0x00007f28bc24b153 __libc_start_main (libc.so.6)
                                                       #19 0x000055894d2b505e n/a (ibus-engine-simple)
                                                       
                                                       Stack trace of thread 7523:
                                                       #0  0x00007f28bc3189ef __poll (libc.so.6)
                                                       #1  0x00007f28bc457180 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f28bc458123 g_main_loop_run (libglib-2.0.so.0)
                                                       #3  0x00007f28bc0cdb48 n/a (libgio-2.0.so.0)
                                                       #4  0x00007f28bc433c11 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f28bbfdb4cf start_thread (libpthread.so.0)
                                                       #6  0x00007f28bc3232d3 __clone (libc.so.6)
                                                       
                                                       Stack trace of thread 7522:
                                                       #0  0x00007f28bc3189ef __poll (libc.so.6)
                                                       #1  0x00007f28bc457180 n/a (libglib-2.0.so.0)
                                                       #2  0x00007f28bc457251 g_main_context_iteration (libglib-2.0.so.0)
                                                       #3  0x00007f28bc4572a2 n/a (libglib-2.0.so.0)
                                                       #4  0x00007f28bc433c11 n/a (libglib-2.0.so.0)
                                                       #5  0x00007f28bbfdb4cf start_thread (libpthread.so.0)
                                                       #6  0x00007f28bc3232d3 __clone (libc.so.6)

<pre></details>

**Comment by fujiwarat** [comment]
I guess your issue is deprecated of https://github.com/ibus/ibus/commit/773420fad23078ceef83e8ae84bba4e139d0bea3

**Comment by jacobmischka** [comment]
Can confirm! Removed those entries from my `.XCompose` (I didn't use them anyway) and everything works great again now.

Sorry for the delays, I appreciate your patience and all of your work!
