### ISSUE TITLE
[Feature Request] inline_preedit mod

### ISSUE THREAD

**Issue by hosxy** [ibus/ibus#2122]
```
distribution: Archlinux
DE: xfce4.14
Session: X11
IBus version: 1.5.21
```

Could you please add inline_preedict mod  like windows10 / OSX, eg:
![批注 2019-08-30 112609](https://user-images.githubusercontent.com/17108640/63992733-dcc78a00-cb1f-11e9-936d-447c554cf411.png)
![深度截图_选择区域_20190830114425](https://user-images.githubusercontent.com/17108640/63992737-e0f3a780-cb1f-11e9-8af2-dfa254b10792.png)

This would be simple and save space, and it look likes pretty good.

**Comment by fujiwarat** [comment]
I think preedit is already inline in ibus as you mean and I guess you mean the inline lookup window?
I have Windows 10 but I'm not sure what you mean.
Could you attach the full screenshot in Windows?

**Comment by hosxy** [comment]
> I think preedit is already inline in ibus as you mean and I guess you mean the inline lookup window?
> I have Windows 10 but I'm not sure what you mean.
> Could you attach the full screenshot in Windows?

@fujiwarat  I will paste two screenshot,you can see
![Snipaste_2019-08-30_20-50-29](https://user-images.githubusercontent.com/17108640/64023734-9009a080-cb6b-11e9-8e9b-4ff3cf5ae7fa.png)

![深度截图_选择区域_20190830211204](https://user-images.githubusercontent.com/17108640/64023789-a9125180-cb6b-11e9-80b6-f75a1da67190.png)

On windows 10, you can see candidate box only have one line are candidate words，the chars you input are on inline_preedit.

On ibus, candidate box has two line, one is the chars you input, another is candidate words. and inline_preedit use to show first candidate words, but first candidate has been in obsious position on candidate box.  
why not move chars to inline_preedit,and  candidate box will only have one line are candidate words? (The default IM of windows10 and osx also do this)

**Comment by mike-fabian** [comment]
That could be added as an option of the Chinese input method you are using. 
Each input method can control what is seen in the preedit and what is seen in the area above the candidates. So this is not an ibus problem but rather a feature request for ibus-libpinyin.

**Comment by fujiwarat** [comment]
@mike-fabian is right.
I think it's a Japanese input style.
CC'ing @epico
I will copy this issue to ibus-libpinyin's one.

**Comment by epico** [comment]
I don't think this is good user experience.

The preedit line is very important, and need to be displayed inline.

Anyway, please copy to ibus-libpinyin issue, thanks.

**Comment by fujiwarat** [comment]
@hosxy Please participate https://github.com/libpinyin/ibus-libpinyin/issues/196 instead
