### ISSUE TITLE
ibus doesn't work in any softwares except for Gnome GUI

### ISSUE THREAD

**Issue by dtvn** [ibus/ibus#2125]
Which distribution and version? Ubuntu 18
Which desktop environment and version? GNOME 3.24
Which session type? X11

Which application and version?: All of GUI & terminal apps.
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5

Issue description:  
ibus-engine doesn't work, I cannot type Vietnamese or Japanese out. The only place can where ibus actually works is the DE, in my case is search bar.

Steps to reproduce:
1. Install ibus and ibus engines (in this case Bamboo and Mozc)
1. Run `ibus-setup` to add IME
1. Restart `ibus restart`
1. Open various apps to try but none of it works except search bar of DE.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): See below

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
![Screenshot from 2019-09-02 06-27-22](https://user-images.githubusercontent.com/43217335/64083470-c3565600-cd4a-11e9-855c-bf1219707f7f.png)

```bash
[2] 4003
2019/09/02 06:27:04 FocusIn.
WM_CLASS=(gnome-terminal-server:Gnome-terminal)
Enable.RECORD extension for local server is version 1.13

(ibus-daemon:4004): GLib-CRITICAL **: 06:27:04.069: g_variant_unref: assertion 'value != NULL' failed

(ibus-daemon:4004): GLib-CRITICAL **: 06:27:04.069: g_variant_unref: assertion 'value != NULL' failed
```

Ref: https://github.com/BambooEngine/ibus-bamboo/issues/72

**Comment by dtvn** [comment]
Today, I found a software was able to use ibus, it is https://launchpad.net/ubuntu/+source/tagainijisho

**Comment by fujiwarat** [comment]
> Run ibus-setup to add IME

ibus-setup is not used in GNOME but other DEs. You should use `gnome-control-center region` instead.

> (Run ibus-daemon --xim --verbose & and look ....

gnome-shell runs `ibus-daemon --xim --panel disable`.  You could see it with `ps` command.

**Comment by dtvn** [comment]
Mine `ps -a` looks like this:
```
  PID TTY          TIME CMD
  969 tty1     00:00:57 Xorg
 1003 tty1     00:00:00 gnome-session-b
 1095 tty1     00:00:45 gnome-shell
 1323 tty1     00:00:00 ibus-daemon
 1328 tty1     00:00:00 ibus-dconf
 1330 tty1     00:00:00 ibus-x11
 1448 tty1     00:00:00 gsd-power
 1455 tty1     00:00:00 gsd-print-notif
 1456 tty1     00:00:00 gsd-rfkill
 1458 tty1     00:00:00 gsd-screensaver
 1501 tty1     00:00:00 gsd-sharing
 1511 tty1     00:00:00 gsd-smartcard
 1512 tty1     00:00:00 gsd-xsettings
 1517 tty1     00:00:00 gsd-wacom
 1519 tty1     00:00:00 gsd-sound
 1539 tty1     00:00:00 gsd-a11y-settin
 1541 tty1     00:00:00 gsd-clipboard
 1544 tty1     00:00:00 gsd-color
 1546 tty1     00:00:00 gsd-datetime
 1548 tty1     00:00:00 gsd-housekeepin
 1549 tty1     00:00:00 gsd-keyboard
 1552 tty1     00:00:00 gsd-media-keys
 1557 tty1     00:00:00 gsd-mouse
 1590 tty1     00:00:00 gsd-printer
 1660 tty1     00:00:41 Telegram
 1684 tty1     00:00:00 gsd-disk-utilit
 1685 tty1     00:02:38 tixati
 1689 tty1     00:00:02 nautilus-deskto
 1984 tty1     00:00:00 ibus-engine-bam
 3759 tty1     00:00:00 ibus-engine-moz
 3763 tty1     00:00:00 mozc_server
 3846 tty1     00:00:00 update-notifier
 3848 tty1     00:00:04 gnome-software
 4668 tty1     00:00:00 deja-dup-monito
 5023 tty1     00:02:53 firefox
 5060 tty1     00:00:05 code
 5074 tty1     00:00:00 code
 5088 tty1     00:00:08 Web Content
 5131 tty1     00:00:02 code
 5155 tty1     00:00:07 Web Content
 5158 tty1     00:00:15 code
 5221 tty1     00:00:26 WebExtensions
 5280 tty1     00:00:01 code
 5303 tty1     00:00:04 code
 5338 tty1     00:00:26 Web Content
 5354 tty1     00:00:01 code
 5390 tty1     00:00:00 code
 5391 tty1     00:00:00 code
 5417 tty1     00:00:00 code
 5507 tty1     00:00:07 Web Content
 5913 tty1     00:00:13 Web Content
 6006 tty1     00:00:12 Web Content
 6149 tty1     00:00:00 ibus-engine-sim
 6231 tty1     00:00:01 Web Content
 6260 pts/0    00:00:00 hugo
 6942 pts/2    00:00:00 ps
```
So many `ibus-*`, is that normal?

Btw, after I uninstall snap, some of apps get to work (after reinstalled of course) such as telegram, krita.
