### ISSUE TITLE
bashism in src/tests/runtest

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2126]
Hello,

The ```src/tests/runtest``` script has ```pushd``` and ```popd``` but they are bash only. I think using bash is OK, but please use ```/bin/bash``` instead of ```/bin/sh```. In some systems like Debian /bin/sh is not bash.

https://github.com/ibus/ibus/blob/71ee904f000f9335ceb6ece054ce18f1291a8490/src/tests/runtest#L1
https://github.com/ibus/ibus/blob/71ee904f000f9335ceb6ece054ce18f1291a8490/src/tests/runtest#L114
https://github.com/ibus/ibus/blob/71ee904f000f9335ceb6ece054ce18f1291a8490/src/tests/runtest#L193

**Comment by fujiwarat** [comment]
I'd like to use Posix SH bot not GNU bash but Fedora uses BASH as SH unfortunately and I'd fix the problems upon the request.

Des the following fix works for you? 
https://github.com/fujiwarat/ibus/commit/f39cde71f78cc07ee326614fb982d4ce40ce35b4

**Comment by changwoo** [comment]
> Des the following fix works for you?
> [fujiwarat@f39cde7](https://github.com/fujiwarat/ibus/commit/f39cde71f78cc07ee326614fb982d4ce40ce35b4)

Yes it works!  👍

**Comment by fujiwarat** [comment]
Thank you for the report.
