### ISSUE TITLE
why don't allow using only one key to switch IM?

### ISSUE THREAD

**Issue by hosxy** [ibus/ibus#2127]
```
Which distribution and version?:   Archlinux

Which desktop environment and version?:  xfce4.14

Which session type?:  X11

Which application and version?: 

IBus version?:  1.5.21
```

Issue description:

I find I can't use only control to switch IM, through I have setted it. Why don't allow this operation?

![深度截图_选择区域_20190903190738](https://user-images.githubusercontent.com/17108640/64168439-1b41a980-ce7e-11e9-9544-f2062043b06c.png)

I feel too complex using two key to switch IM. Of course I can use control to switch English and
Chinese in libpinyin, but if I do this, I will can't use `Global input method settings`(I don't want to share same IM to different application),because whenever I'm in English or Chinese, I'm always in libpinyin . So I need use **English Method** ,rather than built-in English mod in libpinyin.

To solve this problem, what can I do?  And why don't allow control, shift or alt to switch IM?

**Comment by fujiwarat** [comment]
Currently the modifier keys only is not supported in GTK. You can register non-modifier keys likes Zenkaku_Hankaku, Hangul and etc.
You can set shortcut keys with CLI for the workaround:
```
gsettings get org.freedesktop.ibus.general.hotkey triggers
['<Super>space']
% gsettings set org.freedesktop.ibus.general.hotkey triggers "['<Super>space', 'Control_L']"
```

https://gitlab.gnome.org/GNOME/gtk/issues/1128
