### ISSUE TITLE
IMEs added to Fedora Silverblue ostree do not appear

### ISSUE THREAD

**Issue by juhp** [ibus/ibus#2132]
This was first report in fedora-silverblue/issue-tracker#9.

Which distribution and version?: Fedora 30 Silverblue

Which desktop environment and version?: Gnome

IBus version?: 1.5.20

Issue description:
ibus uses timestamps to detect newly added/installed IMEs.
However under ostree all system files under /usr get timestamp 1 Jan 1970.
There ibus currently does not notice any newly added xml files in `/usr/share/ibus/component/`.

Steps to reproduce:
1. On Silverblue rpm-ostree install ibus-mozc
1. reboot
1. login to desktop
1. try to add or list IMEs

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

A workaround should be `sudo ibus write-cache --system`, which forces the system cache under `/var/cache/ibus/bus/` to be updated.

IIUC `sudo ibus write-cache --system` doesn't look at the user's cache and so it finds the new xml file?

**Comment by fujiwarat** [comment]
Thank you for the report.
I created ibus-1.5.21-4.fc31 before the patch is merged in upstream.
Please test the Fedora package.

**Comment by fujiwarat** [comment]
None verify the fix. I will change the milestone to 1.5.23.

**Comment by juhp** [comment]
I believe this is long fixed in Fedora.
