### ISSUE TITLE
Add column numbers to CJK character choices

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#2134]
Here we see row numbers, but no column numbers,
![25504-0](https://user-images.githubusercontent.com/1230959/64815404-172d2e80-d5d8-11e9-97c1-22269b2d9e31.jpg)
There should be a "2" above 猞, to indicate we are currently looking at the second column of choices. In fact maybe use "2/4" meaning column two out of a maximum four.
(Seen with Chewing.)

**Comment by mike-fabian** [comment]
I am not sure what is  the right upstream for ibus-chewing, but the URL you mention is what Fedora uses as upstream, so my guess is that this is correct.

**Comment by fujiwarat** [comment]
I don't understand this issue.
What is "2/4" and what do you expect to describe in the 3rd and 4th columns?
Did you insert the blue strings in the image in your screenshot? Or did your IBus engine insert the blue strings in the lookup window?
Seems the strings are out ot the spaces on the lookup window and I cannot read the messages of the blue strings.

Anyway you can refer https://github.com/ibus/ibus/wiki/BugReport for engines issues.

**Comment by jidanni** [comment]
@fujiwarat The blue was just the underlying web page at the time.
2/4 represents the second page of choices out of four pages.
Each page having 10 choices, except the last, which usually has less.
