### ISSUE TITLE
New socket directory handling possibly affects the tests

### ISSUE THREAD

**Issue by gunnarhj** [ibus/ibus#2135]
The commit https://github.com/ibus/ibus/commit/a141a141 caused a bunch of tests to fail when I tried to build 1.5.21 with it for Ubuntu. It's these tests:

    ibus-config
    ibus-configservice
    ibus-factory
    ibus-inputcontext
    ibus-inputcontext-create
    ibus-engine-switch

and it complains about failed dbus connections.

Does that make sense? ( I can't exclude the possibility that I did some stupid mistake. ;) )

**Comment by fujiwarat** [comment]
I don't see any failures with `make check`.
Probably you could check ibus/src/tests/ibus-config.log or ibus/src/tests/test-suite.log
I have a plan to import that commit to Fedora and to run `make check` and try to check this issue again.
Do you mean your failure does not happen without that commit?

**Comment by fujiwarat** [comment]
I guess you switched a build user with `su` command and failed to make the socket directory.
Maybe you could avoid your problem to set `XDG_RUNTIME_DIR=/tmp/$USER` ?

**Comment by gunnarhj** [comment]
I didn't build manually, but uploaded the source and let the Launchpad builders do it.

> Do you mean your failure does not happen without that commit?

Yes. Please feel free to check out [this example buildlog](https://launchpadlibrarian.net/443014842/buildlog_ubuntu-eoan-amd64.ibus_1.5.21-1~exp2ubuntu1+test_BUILDING.txt.gz).

Since the build is made via dpkg-buildpackage, and affected by Debian packaging settings, I [reported the problem to Debian](https://bugs.debian.org/940594) too.

**Comment by fujiwarat** [comment]
Can you modify the Debian build to set DISABLE_DAEMONIZE_IN_TESTS=1 to get the error of ibus-daemon before you run `make check` ?
https://github.com/ibus/ibus/blob/master/src/tests/runtest#L174

I created a patch to revert XDG_RUNTIME_DIR to XDG_CONFIG_HOME above.

**Comment by gunnarhj** [comment]
Set `DISABLE_DAEMONIZE_IN_TESTS=1` and applied https://github.com/fujiwarat/ibus/commit/66e9e8fe . [Didn't help](https://launchpadlibrarian.net/443131385/buildlog_ubuntu-eoan-amd64.ibus_1.5.21-1~exp2ubuntu1+test5_BUILDING.txt.gz).

Did you possibly mix up CONFIG and CACHE?

**Comment by fujiwarat** [comment]
Yes, I did because the socket path is changed by PID and the address file is solid by display and machine ID.

> (ibus-daemon:22446): IBUS-ERROR **: 10:12:28.860: mkdir is failed in: /sbuild-nonexistent/.cache/ibus: Permission denied

From your log, mkdir was filed in the XDG_CACHE_HOME.
I expect the build user own the home directory  /sbuild-nonexistent.

**Comment by gunnarhj** [comment]
Well, such a 'name' of `$HOME` indicates that the build user does not have a home directory.

Anyway, I finally built it successfully with the help of your hints.

* Created the `/tmp/test_home/.cache` directory

* Passed `HOME=/tmp/test_home` to the `make check` command

https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus-test2/+packages

This means, I suppose, that the problem is a pure Debian/Ubuntu thing, and that this issue can be closed. Thanks for your helpful advice!

**Comment by fujiwarat** [comment]
Thank you for your investigation.
Since ibus supports to switch user accounts, I will apply this patch to revert XDG_RUNTIME_DIR.
If the user does not have the home directory, I think it would be a Debian/Ubuntu build issue and setting HOME env is a workaround.
I think you don't have to create the cache dir since ibus runs mkdir.

**Comment by gunnarhj** [comment]
> I think you don't have to create the cache dir since ibus runs mkdir.

If I remember correctly (I tested back and forth several times) it complained as long as the `.cache` dir was not there. My interpretation (didn't confirm) was that IBus runs `mkdir` without the `-p` option.

**Comment by fujiwarat** [comment]
ibus runs the similar API likes `mkdir -p`.
The error message is caused because `mkdir` was failed due to no permission.

**Comment by fujiwarat** [comment]
Thank you for the report.
