### ISSUE TITLE
Firefox drawing slowed significantly while running ibus-daemon in Ubuntu 18.04

### ISSUE THREAD

**Issue by markmeson** [ibus/ibus#2136]
Please fill in the following items if you don't know the root cause.

ibus-daemon - Version 1.5.17
fluxbox 1.3.5
Mozilla Firefox 69.0

Issue description:
Firefox drawing slowed significantly while running ibus-daemon in Ubuntu 18.04

Steps to reproduce:
1. Install Ubuntu 18.04
1. Install Fluxbox 1.3.5 and Firefox 69.0
1. Run ibus-daemon

Can you reproduce your problem when you restart ibus-daemon? yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Yes.

ibus-ui-gtk3:17413): IBUS-WARNING **: 20:58:17.697: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:17413): IBUS-WARNING **: 20:58:17.733: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:17413): Gdk-CRITICAL **: 20:58:17.837: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Can you reproduce your problem with a new user account instead of the current your account? Yes

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.
Can you reproduce your problem with `env GTK_IM_MODULE=ibus firefox` ?
Can you attach the output of `strace -f /usr/bin/firefox |& grep immodule`?

**Comment by markmeson** [comment]
env GTK_IM_MODULE=ibus firefox fixes the problem.

**Comment by fujiwarat** [comment]
You don't fill most of the questions of the bug template.

Also your steps to reproduce does not describe your problem. It asks how to run your application and what you typed and use mouse exactly but does not ask your installation.

You didn't attach the strace.

Your ibus-daemon is old and it would be good to update the version.
