### ISSUE TITLE
Steam ibus (CJK) input

### ISSUE THREAD

**Issue by jatin-cbs** [ibus/ibus#2140]
ibus japanese input (CJK) does not work in steam https://github.com/ValveSoftware/steam-for-linux/issues/781 This issue has been opened since years but neither steam devs or ibus are working on it, please support steam we dont have any IME working with steam on linux except fcitx still does work on gnome with steam (not with KDE). Ibus does not work with either of the desktop environments and on neither of the distros. Please support steam and steam games, this issue has been opened since 2013 and has been six years ! Fcitx is atleast working on gnome thats what i use mostly.. but many people do use KDE. And those people have no option currently. :+1: :100:

**Comment by fujiwarat** [comment]
From your web page, I don't understand which kind of applications you use. Java, GTK, QT, X11 apps

Can you  attach the screenshot of the application which has a input text entry?

Do you have a command line to run the application? Please take `file /usr/bin/foo` and `ldd /usr/bin/foo`.

**Comment by hiunnhue** [comment]
I don't use steam myself ... just install the client to test ...


Step to reproduce: 

1.  Install "steam for linux" from the official website (https://store.steampowered.com/about/).
2.  Start up "steam"
3.  Clink "I CAN'T SIGN IN"
4.  Scroll to the bottom of the page.
5.  Try to input text into the search field.

Result: 
* Unable to input CJK via ibus  (ibus-anthy, ibus-chewing, ibus-libpinyin ... etc.)

Env: 
* elementary OS 5.0 Juno (based on Ubuntu 18.04.2 LTS)
* pantheon-desktop
* GTK 3.22.30
* ibus 1.5.17

![image](https://user-images.githubusercontent.com/1015601/67043379-86a8b780-f15c-11e9-842b-7732d09017a0.png)

**Comment by fujiwarat** [comment]
I think the package format is Debian and probably I won't try it.

The field of "I have charges from Stream that I didn't make" is a text entry in your screenshot?

Can you try `file /usr/bin/stream` and `ldd /usr/bin/stream`?

**Comment by hiunnhue** [comment]
It's the field of "Search issues, features, and games".

The client seems to be a web browser?  I visit the link on the client with chromium, the page content is the same, and I can input with ibus.

Here's the reuslt for `file /usr/bin/stream` and  `ldd /usr/bin/stream`:  

```
$ file /usr/bin/stream
/usr/bin/stream: symbolic link to /etc/alternatives/stream

$ ldd /usr/bin/stream
	linux-vdso.so.1 (0x00007fff1634d000)
	libMagickCore-6.Q16.so.3 => /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.3 (0x00007f344c415000)
	libMagickWand-6.Q16.so.3 => /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.3 (0x00007f344c0fa000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f344bd09000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f344bab1000)
	liblqr-1.so.0 => /usr/lib/x86_64-linux-gnu/liblqr-1.so.0 (0x00007f344b8a3000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007f344b4a1000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f344b25c000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f344afa8000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f344ad96000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f344aa5e000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f344a84e000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f344a631000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f344a427000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f344a089000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f3449e5a000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3449c42000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3449a23000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f344cad8000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f344970c000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f34494da000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f34492a8000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f3449080000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3448e7c000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f3448c0a000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f3448a06000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f3448800000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f34485eb000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f34483e3000)
```

**Comment by jatin-cbs** [comment]
> I think the package format is Debian and probably I won't try it.
> 
> The field of "I have charges from Stream that I didn't make" is a text entry in your screenshot?
> 
> Can you try `file /usr/bin/stream` and `ldd /usr/bin/stream`?

Steam is available on all distros, ibus CJK is not working with steam client or any of the steam games, I can confirm Fcitx is working tho.

**Comment by fujiwarat** [comment]
> It's the field of "Search issues, features, and games".

OK, I see. Seems the appearance is neither GTK or QT. And from the `ldd` result, I guess it uses XIM.

Can you use IBus engines with X11 applications likes `xterm`?

> Steam is available on all distros

I checked https://steamcommunity.com/ and it provides `steam.deb` which is a Debian package format.

**Comment by hiunnhue** [comment]
> Can you use IBus engines with X11 applications likes xterm?

Yes, here's the screeshot: 

![image](https://user-images.githubusercontent.com/1015601/67192929-0b2e5b00-f427-11e9-9a47-8c3a1c88bbf0.png)

**Comment by fujiwarat** [comment]
And then probably I think steam needs to implement XIM.
E.g. xterm uses `XOpenIM()`
https://github.com/ThomasDickey/old-xterm/blob/master/charproc.c#L6029

GTK or QT applications are easy to enable input methods but X11 applications are more complicated.
I no longer have any comments about steam.

**Comment by jatin-cbs** [comment]
They provide only debian instaer on the website but its in official repos of most distros including fedora opensuse and others

**Comment by fujiwarat** [comment]
I have nothing to comment on the closed source codes.
