### ISSUE TITLE
Build error: "undefined reference to `g_abort'"

### ISSUE THREAD

**Issue by Slider-Whistle** [ibus/ibus#2142]
Haven't been able to compile ibus on Slackware version 14.2, though I'm sure this isn't a consistent issue with other people. The following error appears in the make build stage:

  CC       unicode_parser-unicode-parser.o
unicode-parser.c: In function ‘ucd_parse_file’:
unicode-parser.c:318:13: warning: implicit declaration of function ‘g_abort’ [-Wimplicit-function-declaration]
             g_abort ();
             ^
  CCLD     unicode-parser
unicode_parser-unicode-parser.o: In function `ucd_parse_file':
unicode-parser.c:(.text+0x573): undefined reference to `g_abort'
collect2: error: ld returned 1 exit status
Makefile:928: recipe for target 'unicode-parser' failed
make[4]: *** [unicode-parser] Error 1
make[4]: Leaving directory '/tmp/SBo/ibus-1.5.21/src'
Makefile:1150: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/tmp/SBo/ibus-1.5.21/src'
Makefile:840: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/tmp/SBo/ibus-1.5.21/src'
Makefile:678: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/SBo/ibus-1.5.21'
Makefile:585: recipe for target 'all' failed
make: *** [all] Error 2

In this case I'm using the slackbuild here https://slackbuilds.org/repository/14.2/misc/ibus/ where I simply changed the version number to the latest, but it hasn't worked without it either. I got the same error from versions 1.15.9 to 1.15.21, but haven't tried anything further back as I don't want to miss out on the control-shift-u functionality.

What are the program's current dependencies? These are the current versions I've got from the outdated wiki page here https://github.com/ibus/ibus/wiki/Install :
python 2.7.16
dbus-glib 0.106
dbus-python 1.2.4
notify-python 0.1.1
iso-codes 3.67

I'm guessing that only dbus-glib is relevant, but I thought it might be helpful to list the other dependencies. I'm probably the only one who gets this error, so sorry if this is a waste of time.

**Comment by fujiwarat** [comment]
`g_abort()` is defined in `/usr/include/glib-2.0/glib/gutils.h` :

```
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_50
#ifndef G_OS_WIN32
#  include <stdlib.h>
#  define g_abort() abort ()
#else
GLIB_AVAILABLE_IN_2_50
void g_abort (void) G_GNUC_NORETURN G_ANALYZER_NORETURN;
#endif
```

You could check the following test program.
```
% cat a.c
#include <glib.h>
int
main (int argc, char *argv[])
{
    g_abort ();
}
% gcc -o a a.c `pkg-config --cflags --libs glib-2.0`
```

The gcc should not output any errors.

**Comment by Slider-Whistle** [comment]
Okay, there's no g_abort in my gutils.h at all. Checking my packages, it seems like my version of "glib2" is 2.46.2, rather than >=2.5.0 where it needs to be right?

Thanks for helping out with this. Stuff broke even more when I tried to upgrade it, but I think I'll be able to figure it out myelf now.

**Comment by fujiwarat** [comment]
You're right. g_abort() has been available since 2.50 but I thought it was available in much old versions by mistake.
Are you able to upgrade your glib 2.46.2 to 2.50?
The latest stable glib is 2.62 and I think it's good to revise the minimum supported glib is 2.50 in ibus.

**Comment by Slider-Whistle** [comment]
If I upgrade glib2, then I think I need to upgrade or recompile to continue with ibus, and I haven't tried opening that can of worms yet. There's also a bunch of other programs I'll have to recompile to make work again. You probably don't have to worry too much about making this work for me, since I'm using kind of outdated stuff in the first place.

I'll look into my options for using two versions of glib at once. Apparently, if I want to, I should be able to install the newer version of glib in its own directory, and add that directory to LD_LIBRARY_PATH when I want to use it.

**Comment by fujiwarat** [comment]
I expect to use built packages built by distributions to upgrade libraries easily.
If your distro does not provide the built packages with the package dependencies, probably you might rebuild whole the GNOME desktop packages by release by yourself. glib 2.50 was released in Sep 2016 and it's still an old release.
I guess you also need to rebuild glibc and pkgconf.

**Comment by fujiwarat** [comment]
Since g_abort() is not so useful, I can replace g_abort with abort at the moment.
However the minimum supported version will be 2.50 in the near future.
