### ISSUE TITLE
ibus settings won't open

### ISSUE THREAD

**Issue by YoungLink4** [ibus/ibus#2143]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Linux Mint 18.3 64 bit
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: Cinnamon
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.11
(Run `ibus version`)

Issue description:
I noticed that I can't switch to Japanese anymore, so I wanted to go to the settings. When I try to open them, it just loads for a while without doing anything whether I try through the start menu or ibus tray icon.
While going through this post I figured out Python is the root. I did (try to) install it today. Now I'm not sure if this question is still right in this place or not.

Steps to reproduce:
1. Start ibus settings

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: Trying to open the settings while doing so gives me the following

> Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 31, in <module>
    from gi.repository import GLib
ModuleNotFoundError: No module named 'gi'
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): not tested

**Comment by fujiwarat** [comment]
Please ask your distro Linux Mint which package includes `gi.repository` Python.
Seems your distro didn't set the dependency of gi.repository to ibus-setup.
