### ISSUE TITLE
ibus-setup crashes systematically upon launching

### ISSUE THREAD

**Issue by Cbhihe** [ibus/ibus#2145]
Please fill in the following items if you don't know the root cause.

Which distribution and version?:  
Arch Linux kernel 5.3.7-arch1-1-ARCH 
(64-bit rolling release)  

Which desktop environment and version?: 
GDM 3.34.1-1 (gnome)

Which session type?: 
X11

Which application and version?: 
LibreOffice 6.3.2.2, Firefox 69.0.3  
(see "Motivation" in "Issue description" below to understand app context)
Issue occurs when launching ibus-setup in terminal window.

IBus version?: 
1.5.21

Issue description:
Motivation: I want to run `ibus-setup` to correct what I believe is the key binding CTRL-SHIFT-E being hijacked by my GTK apps (Firefox + LibreOffice) to open an annoying emoji-picker window. Concretely I want to suppress what I think might be a default GTK key binding. I thought I might try doing that by launching `ibus-setup` from a terminal window with: `$ ibus-setup`.

```
$ ibus-setup
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 33, in <module>
    from gi import require_version as gi_require_version
ModuleNotFoundError: No module named 'gi'
```

I found that "gi" is part of official Arch package repo. It shows up as `extra/python-gobject` which I installed, along with `extra/python2-gobject` and `extra/python-gobject2` for good measure.

I launched `ibus-setup` both in my global Python 3.7.4 env and in a Python 2.7.16 (pyenv) virtual environment, although the Python RTE outside the process(es) launched by `ibus-setup` should not matter. Same error.

Per the error message I got when attempting to launch `ibus-setup`, I peeked at `/usr/share/ibus/setup/main.py`. It is python2 code and I could not see anything blatantly wrong with how gi is invoked (not really surprising, given how long `ibus-setup` has been around!) 

I even tried the small python snippet [here](https://pygobject.readthedocs.io/en/latest/getting_started.html#arch-getting-started) to check that `gi` is correctly imported when called from `python` on my box, both in Python 3.7 and 2.7. It worked well, which means that `gi`can be and is correctly imported from the python console.

Steps to reproduce:
------ Just launch `ibus-setup`  from terminal

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
------ Yes, every time.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
------ Exactly the same error as shown earlier in code section.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
------ Yes
Changing to a new user, I get the following error, which corresponds to my exact message of the original error I got  before I installed `extra/python-gobject` packages to make `gi` available.
```
$ ibus-setup                                                                                           │
No protocol specified
Unable to init server: Could not connect: Connection refused
No protocol specified
Unable to init server: Could not connect: Connection refused
(ibus-setup:7515): Gtk-CRITICAL **: 14:16:19.146: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 54, in <module>
    from emojilang import EmojiLangButton
  File "/usr/share/ibus/setup/emojilang.py", line 40, in <module>
    from icon import load_icon
  File "/usr/share/ibus/setup/icon.py", line 36, in <module>
    icon_theme.prepend_search_path(icondir)
AttributeError: 'NoneType' object has no attribute 'prepend_search_path'
```

**Comment by fujiwarat** [comment]
> ModuleNotFoundError: No module named 'gi'

It's a distribution issue but not upstream. Please ask your distro which package has gi.
I think you don't install gi.

>  peeked at /usr/share/ibus/setup/main.py. It is python2 code

main.py works with either python2 and python3. Can you paste the content of /usr/bin/ibus-setup here whether python2 or python3 is used?

> I even tried the small python snippet here to check that gi is correctly imported 

Which test program is run actually?

> Unable to init server: Could not connect: Connection refused

I think you run ibus-setup without display.

**Comment by Cbhihe** [comment]
Hello @Fujiwarat, <BR>
Thank you for taking the time, but I don't quite understand why you close this thread, right upon asking me several questions for clarification.

`gi` is contained in the packages I already mentionned in my PO.   It shows up in `extra/python-gobject` which I installed, along with `extra/python2-gobject` and `extra/python-gobject2`.

The test program I ran is the small python snippet [here](https://pygobject.readthedocs.io/en/latest/getting_started.html#arch-getting-started). also included in my PO.

Forgive me but I don't understand what "paste the content of /usr/bin/ibus-setup here" means.  If you mean executing `/usr/bin/ibus-setup` from terminal, the output is strictly the same as the error reported. 

How can I ran `ibus-setup` from terminal with (gui) display ?

Thanks.

**Comment by fujiwarat** [comment]
> The test program I ran is the small python snippet here. also included in my OP.

I think you mean to run hello.py in the page. Can you attach the hello.py?

>  I don't understand what "paste the content of /usr/bin/ibus-setup here" means.

I'm asking to attach the ibus-setup file here.

> How can I ran ibus-setup from terminal with (gui) display ?

If you open the display, you can run ibus-setup.

**Comment by Cbhihe** [comment]
Thank you for your reply. Here is the `hello.py`:

```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

Here the ibus-setup configuration file. It is an executable. To execute simply strip its ".txt" suffix and make  itexecutable.
[ibus-setup.txt](https://github.com/ibus/ibus/files/3771556/ibus-setup.txt)

**Comment by fujiwarat** [comment]
Do you mean you can run the `hello.py` but cannot run ibus-setup?
If yes, I guess you run `hello.py` with `python` but not `python3` and your `python` would be a symlink of `python2` ?
I think you could try `python3 hello.py` or `/usr/bin/python3 hello.py`

**Comment by Cbhihe** [comment]
my `python` cmd is symlinked to `python3` which points to version 3.7.3. 

But no matter, I tried running `ibus-setup` in that environment AND in a python 2.7.16  RTE. It makes no difference. Error is the same as indicated above. 
I am kinda lost here. I don't have enough info (the error message is not explicit enough) for me to debug this. (Not even sure it is a bug in fact.) and I don't quite see where the hangup is, since I make sure package `gi` is correctly installed and available when called from the python script.

Thank you for your continued help in any case.

**Comment by fujiwarat** [comment]
Did you run `python3 hello.py` and `/usr/bin/python3 hello.py`?

Also I'd ask to run the following a.py with python3:
```
% cat a.py
import gi
from gi import require_version as gi_require_version

% python3 a.py
```

**Comment by Cbhihe** [comment]
`python3 hello.py` fails, while `/usr/bin/python3 hello.py` has no issue.  
```
% cat a.py
import gi
from gi import require_version as gi_require_version

% python3 a.py
```
does not work either.  It seems that I have a classical python PATH issue here.

**Comment by fujiwarat** [comment]
Seems you have more than two python3 and one has gi but another does not.
Then you could run `env PYTHON=/usr/bin/python3 ibus-setup`

**Comment by Cbhihe** [comment]
Yes, I do have `pyenv` installed. Sorry for the mishap an thank you for your pointers and solution.
