### ISSUE TITLE
ibus-dconf sets $DCONF_PROFILE but ibus-setup doesn't

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2150]
In ibus-dconf, $DCONF_PROFILE is hard-coded as "ibus" and dconf profile /etc/dconf/profile/ibus is installed. But ibus-setup doesn't set this environment variable so ibus-setup displays incorrect default settings when the system db is changed.

https://github.com/ibus/ibus/blob/efeb7b9689126e4f05bd1e10441cdc4a3720ff1c/conf/dconf/main.c#L73

I'm not sure settings this variable is a good practice or not. But as long as $DCONF_PROFILE has been set in ibus-dconf so ibus-setup should also set it as the same.

Steps to reproduce:
1. override system-db settings by copying some lines from ```/etc/db/ibus/00-upstream-settings``` and doing paste&edit ```/etc/db/ibus/10-something```
1. run ```dconf update``` as root
1. run ```ibus-setup``` to see not-overriden setings
1. run ```env DCONF_PROFILE=ibus ibus-setup``` to see overridden settings

Original report from Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=857115

**Comment by fujiwarat** [comment]
I think ibus clients use DConf via ibus-dconf and the clients do not have to know DCONF_PROFILE value.
Also ibus-setup accesses GSettings instead of DConf and now DConf is deprecated.
The setting file is `/usr/share/glib-2.0/schemas/org.freedesktop.ibus.gschema.xml`

**Comment by changwoo** [comment]
> I think ibus clients use DConf via ibus-dconf and the clients do not have to know DCONF_PROFILE value.
Yes. only ibus-setup is affected.

> Also ibus-setup accesses GSettings instead of DConf and now DConf is deprecated.
> The setting file is `/usr/share/glib-2.0/schemas/org.freedesktop.ibus.gschema.xml`

GSettings is a configuration API and it still uses dconf as its backend. Did you mean GConf which is deprecated?

**Comment by fujiwarat** [comment]
I mean ibus-dconf is now deprecated and I'd suggest to use GSettings only.
Most major IBus engines are migrated to GSettings; https://github.com/ibus/ibus/wiki/GSettingsMigration
I think ibus-setup is a frontend UI and it could use the GSettings configuration file `org.freedesktop.ibus.gschema.xml` instead of the backend DConf ones?

**Comment by changwoo** [comment]
I just want it to be consistent. So it's OK to remove dconf stuffs and to replace ibus-dconf with ibus-gsettings or like.  (Currently there is no alternative to ibus-dconf in usual Linux desktops.)

**Comment by fujiwarat** [comment]
If there is a non-GTK engine, it needs to consider another configuration but you're right. Such an engine cannot access IBus GSettings configuration.

I think users can use GSettings only. If you require dconf, let's discuss again.

**Comment by changwoo** [comment]
I didn't mean that dconf is required. I mean ibus currently uses dconf, but inconsistently. dconf is used in the daemon and gsettings is used in ibus-setup. So currently modifying DCONF system db won't work in ibus-setup and modifying GSettings schema won't work in ibus daemon.

**Comment by fujiwarat** [comment]
> modifying GSettings schema won't work in ibus daemon.

I think modifying gsettings schema works in ibus-daemon?

**Comment by changwoo** [comment]
> > modifying GSettings schema won't work in ibus daemon.
> 
> I think modifying gsettings schema works in ibus-daemon?

ibus-dconf uses dconf APIs only and they don't respect gsettings schema AFAIK.

**Comment by fujiwarat** [comment]
So ibus-dconf is now deprecated and I think you don't have to use dconf in your case.

**Comment by changwoo** [comment]
> So ibus-dconf is now deprecated and I think you don't have to use dconf in your case.

To be exact, the original Debian bug is not by me, but by a user when he found the **ibus-installed** dconf config didn't seem to work. If ibus-dconf is deprecated and should not be used, writing a new config backend is in need. Then the dconf stuff could be removed from ibus installation.

**Comment by fujiwarat** [comment]
My plan is to delete IBusConfig at all and I don't think to write a new confing backend.

> when he found the ibus-installed dconf config didn't seem to work.

So he can stop to use the ibus-config for ibus-setup.
