### ISSUE TITLE
How to edit a ibus-m17n keyboard?

### ISSUE THREAD

**Issue by NiranjanTambe** [ibus/ibus#2151]
This is a question about customizing an Ibus-keyboard. I want to develop a keyboard which will allow me to have multiple characters on one key-press. When I looked hi-inscript.mim file, it had a few such instances. eg.

("*" "श्र") means श + ् + र i.e. a set of three unicode characters.

When I tried to replace this with other unicode characters, it didn't work. Is there any guide to developing Ibus keyboards? I want to develop a completely new Ibus keyboard. Please help me.

**Comment by mike-fabian** [comment]
/usr/share/m17n/hi-inscript.mim is a good example for what you want to do, I think.
The replacing  you did should have worked. Maybe you introduced a syntax error by mistyping something?

**Comment by NiranjanTambe** [comment]
Am I supposed to only put the characters from the same unicode block? eg. If I am modifying Devanagari, can I put latin characters?

**Comment by NiranjanTambe** [comment]
Oh, I must have committed some syntax mistake. I managed to resolve it after doing it again carefully. Thanks, I am closing this issue.
