### ISSUE TITLE
ibus tray icon not updated in i3

### ISSUE THREAD

**Issue by ziima** [ibus/ibus#2152]
Which distribution and version?: 
Debian testing (bullseye)

Which desktop environment and version?: 
i3 4.17.1

Which session type?: 
x11

Which application and version?: 
ibus-ui-gtk3 1.5.19

IBus version?: 
1.5.19

Issue description:
When using i3 under debian an iBus tray icon shows up automatically. The icon show currently used keyboard layout, but it doesn't get updated, when I change layout using keyboard shortcut. I does update, when I change layout by using the menu from the tray icon (also the layout changes).

Steps to reproduce:
1. Install debian with i3
1. Set up layout switch shortcut, e.g. add `grp:alt_shift_toggle` to `XKBOPTIONS` in `/etc/default/keyboard`
1. Log in to i3 session
1. Set up multiple layouts, e.g. running `setxkbmap -layout us,cz_qwerty`.
1. Switch keyboard layouts by keyboard shortcut

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes, though I need to set up keyboard layouts again.

Do you see any errors when you run ibus-daemon with the verbose option?:
No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):
I was able to reproduce the problem on two different computers.

**Comment by fujiwarat** [comment]
Do you mean to try to switch layouts with Alt-Shift keys?
IBus's shortcut key is configured with `ibus-setup` command and it does not use the XKB shortcut keys.

**Comment by ziima** [comment]
Yes.

OK, is there a way I can convince the iBus to notice I've changed the keyboard with the XKB shortcut?

**Comment by fujiwarat** [comment]
No, there is not. XKB shortcut keys works in X11 applications only but IBus works in X11, GTK and Qt has the owned shortcut keys.
If you use XKB only, you can run `ibus exit` command.
