### ISSUE TITLE
Hangul text commit and key forward don't preserve order sometimes

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2156]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Debian sid/unstable

Which desktop environment and version?: 
GNOME 3.34

Which session type?: 
wayland

Which application and version?: 
gedit 3.34.0 
IBus version?: 
1.5.21

Issue description:

In gnome-shell and with GTK_IM_MODULE=wayland, ibus-hangul's text commit and immediate key forward often produces the forwarded key before the committed text. It's a typical use case in Hangul input; the current preedit text is implicitly committed by a non-Hangul key and the non-Hangul key is appended.

For me it isn't reproduced with GTK_IM_MODULE=ibus. I'm not sure whether gnome-shell needs fix or some support should be from ibus.

Steps to reproduce:
1. Use ibus-hangul with ibus
2. Switch to hangul mode (set "Hangul mode" from menu)
3. Open gedit with GTK_IM_MODULE=wayland environment variable
4. Type "r" and a space bar. It should produce text "ㄱ " (space next).
5. Repeat above step 4 many times and you can see incorrect " ㄱ" (space first) very often.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
Interesting.
I confirmed gtk 3.34 has the fix of https://gitlab.gnome.org/GNOME/gtk/merge_requests/384 and seems a new regression after mutter-4 is chaged to mutter-5.

I downgraded gnome-shell 3.34.1 to 3.32.1 with a custom patch and still reproduce this issue and I guess this might be caused between mutter 3.32 and 3.34.
I will downgrade mutter to find which change cause this issue.

**Comment by fujiwarat** [comment]
I confirmed this is caused by https://gitlab.gnome.org/GNOME/mutter/commit/5c617ac2864a7e040dd3646fbef9f5cd9c5fb788 

https://gitlab.gnome.org/GNOME/mutter/issues/948

**Comment by fujiwarat** [comment]
I think this kind of the regression always can happen in the future too.
Probably I propose a new API of `gboolean ibus_engine_process_key_event(IBusEngine* engine, guint keyval, guint keycode, guint state)`.
The current API does not ensure the order of keyval and commit-text.
Probably the new API is `gboolean ibus_engine_process_key_event_with_commit(IBusEngine* engine, guint keyval, guint keycode, guint state, IBusText **commit, gboolean *after_commit)`.

But I have no time in GNOME 3.34, sorry.

**Comment by fujiwarat** [comment]
The workaround is to export `GTK_IM_MODULE=ibus` to disable Wayland IM module.

**Comment by matthiasclasen** [comment]
Can you describe some problematic event sequences ? what are the key events, that go into the input method, what is the mix of text and forwarded key events that comes out, and what are the places where ordering is problematic ?

**Comment by fujiwarat** [comment]
As I indicated last week, gnome-shell/js/misc/inputMethod.js receives 'commit-text' signal during calling inputMethod.js:vfunc_filter_key_event() and the 'commit-signal' with text output expects to be sent to GTK at first and the returned key pressed event from vfunc_filter_key_event() is sent to GTK at second.

But actual result is that GTK receives the pressed GdkEventKey in gtk_im_context_wayland_filter_keypress() in GtkIMContextWayland at first and GTK emits the 'commit' in text_input_commit_apply() at second and the order of "ㄱ" of the 'commit' signal  and the output of " " from the pressed is reversed and the bug description happens.

Because the Wayland protocol has a time lag between text_input_commit() and text_input_commit_apply() in GtkIMContextWayland .

After the change of https://gitlab.gnome.org/GNOME/mutter/commit/5c617ac2864a7e040dd3646fbef9f5cd9c5fb788 was applied, the order is changed but probably I think the change itself is the right behavior.

**Comment by fujiwarat** [comment]
The current order is:
1. text_input_commit()
2. gtk_im_context_wayland_filter_key_press() -> gtk_im_context_simple_commit_char()
3. text_input_commit_apply()

**Comment by fujiwarat** [comment]
I confirmed this can be fixed when @epico 's update-preedit-with-mode patch is applied and mutter's workaround is deleted.

It was almost my proposed fix; https://gitlab.gnome.org/GNOME/gtk/-/issues/1365#note_344831

@epico could you revert https://gitlab.gnome.org/GNOME/mutter/-/commit/a1969c98cdc96202695134db822f82eb5152b43b in your patch ?

**Comment by epico** [comment]
Okay, I upload the revert patch to fedorapeople.org .

URL: https://pwu.fedorapeople.org/wayland/preedit_with_mode_v5/mutter-ibus-forward-key-event-revert.patch

For testing, here is the testing repo.

URL: https://copr.fedorainfracloud.org/coprs/pwu/wayland/

**Comment by fujiwarat** [comment]
@epico Thank you for the change.

I confirmed https://gitlab.gnome.org/GNOME/gtk/-/issues/1365 and this issue and infinite committing Enter or BackSpace key issue are not reproduced with those changes.

@changwoo It would be great if you could test all patches of https://pwu.fedorapeople.org/wayland/preedit_with_mode_v5/

**Comment by fujiwarat** [comment]
It might be a different issue when firefox and chrome sometimes freeze the input.

**Comment by fujiwarat** [comment]
Verified with mutter 3.37.92.
