### ISSUE TITLE
Lookup window away in HDPI

### ISSUE THREAD

**Issue by xijiang** [ibus/ibus#2157]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Fedora 30/31

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 3.34

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Every

IBus version?: 
(Run `ibus version`)
1.5.21

Issue description:
In Fedora 30/31, if the windows scaled to 200%, for example, the input bar is then scaled away from the input cursor. If the input point/cursor is near the bottom, or the right edge of the window, the input bar may disappear. This make it very difficult to select candidates.

Steps to reproduce:
1. Display settings -> Scale 200%+, save
1. Start ibus-libpinyin
1. input bar drift way from the input point
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

**Comment by fujiwarat** [comment]
Could you attach the screenshot with `gnome-screenshot -i` to know what you mean in input bar?

**Comment by xijiang** [comment]
Hi, after recent upgrades, the drifts look normal on some apps, e.g., emacs:
[Normal ones](https://pasteboard.co/IHz6APc.png)
but not for some others, e.g., Joplin
[Abnormal position](https://pasteboard.co/IHz5pvH.png)

I am confused now if this is due to Joplin or to ibus.

**Comment by fujiwarat** [comment]
I still cannot configure HDPI in my boxes. I run `gnome-control-center display` and set "1920 x 1400 (4 : 3)" and scale 2 and the lookup window position is fine with gedit and firefox.

**Comment by epico** [comment]
@xijiang Could you provide more details about how to setup the scaling factor?

**Comment by xijiang** [comment]
Hi, this was a problem for most apps on Fedora. But now it only limited to specific apps, like Joplin I am using as below.
![Screenshot from 2020-01-09 11-52-22](https://user-images.githubusercontent.com/1819383/72061636-93a9f280-32d6-11ea-8d3b-1066b1f58b5a.png)

During the past days, I have been using gnome tweak tools to scale font size (to 1.6). So, one is that the problem may be not a ibus issue. Two is using gnome tweak tools can circumvent the problem.

**Comment by hillwoodroc** [comment]
Set scale as 125% in gnome-control-center, the bug will occur.
![2020-01-08 20-30-01屏幕截图](https://user-images.githubusercontent.com/1880237/72118925-b814d600-338d-11ea-94f8-8b0b44bbd096.png)

**Comment by epico** [comment]
@hillwoodroc Are you using openSUSE?

In Fedora 31, gnome-control-center only shows 100% and 200%.

**Comment by hillwoodroc** [comment]
You should use gnome with wayland in laptop. Gnome supports non-interger scale in laptop with wayland.

**Comment by hillwoodroc** [comment]
I reported the bug in https://github.com/ibus/ibus/issues/2172 and http://bugzilla.opensuse.org/show_bug.cgi?id=1160092. I said this bug just occur on Gnome applications. GTK applications (non-gnome) and Qt applications don't have this issue.

**Comment by epico** [comment]
@hillwoodroc I am using wayland in GNOME.

**Comment by cheuksing** [comment]
Similar issues found in chromium, and vscode (probably all electron apps).
As well as other gnome apps, such as gnome-terminal.

Using a 4k screen, with i3. Running ubuntu, with lightdm.
Xft.dpi set to 192. Other is untouched.

![image](https://user-images.githubusercontent.com/21094909/72683235-7cf26f80-3b10-11ea-8c89-5ea885f47b2f.png)

**Comment by liangqi** [comment]
Tried with Ubuntu 22.04, GNOME on xorg, ibus(Chinese(Pinyin()), 125% / 200% scale, with FireFox, it works fine for the position of the candidate window.

**Comment by xijiang** [comment]
The problem is long gone now. I should have closed this issue also long before also :-)
