### ISSUE TITLE
请问如何固定候选栏位置？

### ISSUE THREAD

**Issue by yueduz** [ibus/ibus#2161]
因为我们有了预编辑功能，所以形码输入法用户希望能固定候选栏位置到系统顶栏或其他位置。ibus的候选栏总在打字时左右移动，大小也不停的变，特别晃眼睛。

**Comment by fujiwarat** [comment]
I'm not sure if I understand your question.
The IBus lookup window is located at the end of the preedit string in the horizontal lookup window.
You can change horizontal or vertical mode in `ibus-setup`.

If this does not reply your question. Please fill all of the questions in the bug template of the new issue and I also ask you to attach a screenshot which can indicate your problem.
