### ISSUE TITLE
CTRL+SHIFT+U remapping doesn't work

### ISSUE THREAD

**Issue by Racle** [ibus/ibus#2163]
Which distribution and version?: 
Pop!_os 19.10

Which desktop environment and version?: 
Gnome (GNOME Shell 3.34.1)

Which session type?: 
X11

IBus version?: 
IBus 1.5.21

Issue description:
I try to remap CTRL+SHIFT+U (on IDE it's lowercase/uppercase shortcut) but I cannot remap unicode input. Emoji annotation seems to be working, as it doens't trigger anymore.
My current settings: 
![image](https://user-images.githubusercontent.com/759091/70692425-fe5e1300-1cc3-11ea-8eee-6672d737dbbd.png)

Steps to reproduce:
1. Remap Unicode code point in `ibus-setup`
1. Reboot (not sure if needed)
1. Press ctrl+shift+u brings unicode "interface"(? or what do you call it), not applying uppercase/lowercase keybind on IDE (PHPStorm).

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

**Comment by fujiwarat** [comment]
I think your issue would be GNOME Wayland only but not GNOME X11.
Please double check it.

**Comment by Racle** [comment]
@fujiwarat Pop!_os uses X11, not wayland (they disabled it because it doesn't work as well as X11).

And `echo $XDG_SESSION_TYPE` outputs X11

**Comment by fujiwarat** [comment]
And then I cannot reproduce your problem.
Can you attach the screenshot of your application?
Did you export `GTK_IM_MODULE=ibus` and `XMODIFIERS=@im=ibus` ?

**Comment by fujiwarat** [comment]
I'm asking the screenshot of your application but not ibus-setup.
Also I'd ask run your application after the environment variables are set and you can confirm the value with `echo $GTK_IM_MODULE` and `echo $XMODIFIERS`

**Comment by fujiwarat** [comment]
Any reply?

**Comment by Racle** [comment]
> Any reply?

Well it does happen on that terminal screen also what i've screenshotted.
I don't know how to get any better screenshot, as when I press screenshot shortcut, u with underline goes away. But it still happens.

Terminal also outputs these
```
~ echo $GTK_IM_MODULE 
ibus
~ echo $XMODIFIERS
@im=ibus
```

What else do you need to know?

**Comment by fujiwarat** [comment]
Good to try `gnome-screenshot -i`.

**Comment by Racle** [comment]
> Good to try `gnome-screenshot -i`.

Doesn't work. if terminal loses focus it loses underline U.
I took video capture and added key-mon to show key presses.
![ibus](https://user-images.githubusercontent.com/759091/74718601-3725e580-523b-11ea-95d1-17fcd6cd4f43.gif)

**Comment by fujiwarat** [comment]
Since gnome-terminal-server is launched through D-Bus, testing gnoem-terminal only might not be good.

Can you run `env GTK_IM_MODULE=ibus gedit` and check if your problem is reproduced in gedit?

Can you also get the return value of `gsettings get org.gnome.desktop.interface gtk-im-module` ?

**Comment by Racle** [comment]
> Since gnome-terminal-server is launched through D-Bus, testing gnoem-terminal only might not be good.
> 
> Can you run `env GTK_IM_MODULE=ibus gedit` and check if your problem is reproduced in gedit?
> 
> Can you also get the return value of `gsettings get org.gnome.desktop.interface gtk-im-module` ?

I'm not neat that pc currently, but I can say this. 

It's Tilix, not Gnome-terminal what's on screenshot. I'll test gedit within an hour.

**Comment by Racle** [comment]
And ran `env GTK_IM_MODULE=ibus gedit`
pressing ctrl+shift+u (and after that 2117) still create unicode character.
![image](https://user-images.githubusercontent.com/759091/74806014-80cf0880-52ed-11ea-888b-5cb313cdec72.png)

**Comment by Racle** [comment]
@fujiwarat I tested this with pop_os 19.10 live disk in vmware. Same issue still even with clean OS.

You can also try this out that way easily.

**Comment by fujiwarat** [comment]
I'd double-check your issue.
Do you use ibus 1.5.21? (The previous ibus forwarded the key events to gtk-im-context-simple but it should be fixed in the latest ibus)

In your box, you can enable the Unicode prompt with both ctrl-shift-u and ctrl-al-shift-meta-super-hyper-u ?

You cannot enable emoji prompt with ctrl-shift-e but can enable with trl-al-shift-meta-super-hyper-e ?

Can you confirm ibus-extension-gtk3 is running with `ps -ef | grep ibus` ?

Can you attach the output of `env GTK_IM_MODULE=ibus strace gedit  |& grep immodule` ?

**Comment by Racle** [comment]
> Do you use ibus 1.5.21? 

```bash
ibus version
IBus 1.5.21
```

> In your box, you can enable the Unicode prompt with both ctrl-shift-u and ctrl-al-shift-meta-super-hyper-u ?

For testing, I changed that to `alt+shift+u` and i get unicode promt when I press that, and when I press `ctrl+shift+u`.  If I change that back to `ctrl-alt-shift-meta-super-hyper-u`, `alt+shift+u` doesn't work anymore, but `ctrl+shift+u` still works.

> You cannot enable emoji prompt with ctrl-shift-e but can enable with trl-al-shift-meta-super-hyper-e ?

Yes, emoji prompt (`ctrl+shift+e`) doesn't work anymore if I change that to `ctrl-alt-shift-meta-super-hyper-e`

>Can you confirm ibus-extension-gtk3 is running with `ps -ef | grep ibus` ?

```bash
vvi       1101  2708  1 13:42 ?        00:00:04 /usr/bin/python3 /usr/share/ibus/setup/main.py
vvi       1908   759  0 13:49 pts/7    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ibus
vvi       3004  2854  0 helmi18 ?      00:00:55 ibus-daemon --panel disable -r --xim
vvi       3010  3004  0 helmi18 ?      00:00:00 /usr/lib/ibus/ibus-memconf
vvi       3011  3004  0 helmi18 ?      00:00:15 /usr/lib/ibus/ibus-extension-gtk3
vvi       3013  2708  0 helmi18 ?      00:00:00 /usr/lib/ibus/ibus-x11 --kill-daemon
vvi       3015  2708  0 helmi18 ?      00:00:00 /usr/lib/ibus/ibus-portal
vvi       3123  3004  0 helmi18 ?      00:00:12 /usr/lib/ibus/ibus-engine-simple

```

>Can you attach the output of `env GTK_IM_MODULE=ibus strace gedit |& grep immodule` ?

```
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules.cache", O_RDONLY) = 14
stat("/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so", {st_mode=S_IFREG|0644, st_size=39104, ...}) = 0
openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-ibus.so", O_RDONLY|O_CLOEXEC) = 14
```

All in one image also: 
![image](https://user-images.githubusercontent.com/759091/74832202-6d3c9580-531f-11ea-98f4-485e42343a00.png)

**Comment by fujiwarat** [comment]
> For testing, I changed that to alt+shift+u and i get unicode promt when I press that, and when I press ctrl+shift+u

Curious.
When you can use both alt-shift-u and ctrl-shift-u, can you get the output of `gsettings list-recursively org.freedesktop.ibus.panel.emoji` ?

> Can you also get the return value of `gsettings get org.gnome.desktop.interface gtk-im-module` ?

You didn't reply the return value.

Also can you disable your OSK which I marked with a red pen in the image and try if you can reproduce your issue? I don't see such a GUI.

**Comment by Racle** [comment]
`gsettings list-recursively org.freedesktop.ibus.panel.emoji `:
```
org.freedesktop.ibus.panel.emoji has-partial-match false
org.freedesktop.ibus.panel.emoji favorite-annotations @as []
org.freedesktop.ibus.panel.emoji load-unicode-at-startup false
org.freedesktop.ibus.panel.emoji partial-match-length 3
org.freedesktop.ibus.panel.emoji favorites @as []
org.freedesktop.ibus.panel.emoji hotkey ['<Control><Alt><Shift><Meta><Super><Hyper>e']
org.freedesktop.ibus.panel.emoji lang 'en'
org.freedesktop.ibus.panel.emoji font 'Monospace 16'
org.freedesktop.ibus.panel.emoji load-emoji-at-startup true
org.freedesktop.ibus.panel.emoji unicode-hotkey ['<Control><Alt><Shift><Meta><Super><Hyper>u']
org.freedesktop.ibus.panel.emoji partial-match-condition 0
```
`gsettings get org.gnome.desktop.interface gtk-im-module`: (I missed this)
```
'gtk-im-context-simple'
```

> Also can you disable your OSK
That is not OSK, it only shows keypresses what I press. I cannot use that to press any keys.
I just used it in this occasion to show you what keys I did press.
And I only installed that just before I took that screencapture, so it wasn't even installed until yesterday.

You can find that app here: https://code.google.com/archive/p/key-mon/

**Comment by Racle** [comment]
I just tested, this issue is also on ubuntu 19.10. 

I used ubuntu-desktop .iso and booted up VM and pressed "try ubuntu".
Same thing as in pop_os VM or in real installation.

**Comment by Racle** [comment]
Just noticed that issue might be wrongly named as "remapping doesn't work", should be more like "remapping ctrl+shift+u doesn't unbind original keybind" as remapping works, but it leaves original keybind there also on unicode prompt. In emoji prompt it works as intented.

**Comment by Racle** [comment]
@fujiwarat did you ever found out why this is happening?

**Comment by fujiwarat** [comment]
Probably I need to try Pop!_os or Ubuntu but currently I'm a bit busy for other tasks.
I still guess it would be a setting failure something of you but not sure about the root cause. I cannot reproduce your problem.

It's a possible case that emoji shortcut works and unicode shortcut does not work because the emoji shortcut key is handled by ibus only but unicode shortcut key is handled by ibus and gtk-im-context-simple. Your problem might be that the key events are sent to gtk-im-context-simple unexpectedly and that's why I asked results of GTK_IM_MODULE and strace but seems they are correct in your box.

**Comment by Racle** [comment]
Odd problem indeed, and this is the reason why I also tested on VM with fully clean install to see if it's my configuration. 

I'll hope this will be resolved in ubuntu 20.04 release. I can report back when that is released.

**Comment by fujiwarat** [comment]
Do you confirm your problem is reproduce with `env GTK_IM_MODULE=ibus gedit` in Ubuntu too?

**Comment by Racle** [comment]
I already deleted my ubuntu .iso file, so cannot currenlty test it.

But you can boot up VM and try it in ubuntu 19.04 in that quikcly. You can also test that probably much better that way, as you can use commands yourself :P

**Comment by fujiwarat** [comment]
OK, I confirmed it's caused by an internal patch of Ubuntu EOAN; ibus-1.5.21/debian/patches/ubuntu-unicode-keybinding.patch
But I could not find it in https://salsa.debian.org/debian/ibus/-/tree/master/debian/patches
I don't check Pop!_os

CC'ing @gunnarhj @changwoo for the patch owner.

**Comment by changwoo** [comment]
> OK, I confirmed it's caused by an internal patch of Ubuntu EOAN; ibus-1.5.21/debian/patches/ubuntu-unicode-keybinding.patch
> But I could not find it in https://salsa.debian.org/debian/ibus/-/tree/master/debian/patches
> I don't check Pop!_os
> 
> CC'ing @gunnarhj @changwoo for the patch owner.

This default-changing patch is Ubuntu only and I (one of the Debian package maintainers) don't agree with this patch.

**Comment by gunnarhj** [comment]
@fujiwarat: The patch looks like this:

```
--- ibus-1.5.19.orig/src/ibusenginesimple.c
+++ ibus-1.5.19/src/ibusenginesimple.c
@@ -1146,7 +1146,7 @@ ibus_engine_simple_process_key_event (IB
         have_hex_mods = (modifiers & (HEX_MOD_MASK)) == HEX_MOD_MASK;
     }
 
-    is_hex_start = (keyval == IBUS_KEY_U) && priv->hex_mode_enabled;
+    is_hex_start = (keyval == IBUS_KEY_U);
     is_hex_end = (keyval == IBUS_KEY_space ||
                   keyval == IBUS_KEY_KP_Space ||
                   keyval == IBUS_KEY_Return ||
```
It was added to fix [LP #1760308](https://launchpad.net/bugs/1760308). I wrote a comment 6 on that bug report, which might shed some extra light on the nature of the problem. It's worth mentioning, also, that Ubuntu still defaults to X11, not Wayland.

Ping @seb128

**Comment by gunnarhj** [comment]
I can confirm the 'dont-unbind' issue on Ubuntu 19.10.

I built IBus for Ubuntu 19.10 and 20.04 with the patch disabled:

https://launchpad.net/~gunnarhj/+archive/ubuntu/ibus

Found that

1. \<Ctrl>+\<Shift>+U works without the patch

1. the 'dont-unbind' issue when changing to something else is no longer present

So it looks like we should drop `ubuntu-unicode-keybinding.patch`. Not sure that the issue is important enough to motivate backports to 19.10 and 20.04, though.

**Comment by fujiwarat** [comment]
@changwoo 

Thank you for explaining the difference between Debian and Ubuntu.

@Racle 

You could ask your distro to delete the similar internal patch.

**Comment by changwoo** [comment]
> Found that
> 
>     1. <Ctrl>+<Shift>+U works without the patch

The hex key input feature is in GTK 3+ and Qt. So it will work on most modern apps. And actually this feature was what caused this issue.

Removing the patch won't fix this issue as AFAIK users can't change this GTK key combination. It cannot be fixed in IBus anyway.

**Comment by gunnarhj** [comment]
@changwoo wrote:
> Removing the patch won't fix this issue as AFAIK users can't change this GTK key combination.

My test indicates that it does fix this issue, i.e. I could _change_ the shortcut via `ibus-setup`.

Possibly the explanation why IBus makes a difference is that `im-config` is installed by default in Ubuntu, i.e. `GTK_IM_MODULE` is set to "ibus" by default, while `GTK_IM_MODULE` is unset by default on vanilla GNOME (maybe including Debian) even if IBus is installed.

**Comment by changwoo** [comment]
> @changwoo wrote:
> 
> > Removing the patch won't fix this issue as AFAIK users can't change this GTK key combination.
> 
> My test indicates that it does fix this issue, i.e. I could _change_ the shortcut via `ibus-setup`.

I stand corrected. It also works for me. I was confused with the built-in GTK hex input feature.

> Possibly the explanation why IBus makes a difference is that `im-config` is installed by default in Ubuntu, i.e. `GTK_IM_MODULE` is set to "ibus" by default, while `GTK_IM_MODULE` is unset by default on vanilla GNOME (maybe including Debian) even if IBus is installed.

The GNOME default is Wayland "gtk-text-input" and it also uses IBus, just not the ibus immodule. Hex input also works in this. Ubuntu's choice to keep X11 does not do much about this. :)

**Comment by fujiwarat** [comment]
> I stand corrected. It also works for me. I was confused with the built-in GTK hex input feature.

IBus no longer uses the binding in IBus GtkIMModule but moved the feature to ibus-extension-gtk3 which can customize the shortcut keys with ibus-setup.
So you should not enable the binding in IBus GtkIMModule by default.

This customization works in Xorg but does not in Wayland because GNOME Wayland fallbacks the binding to gtk-im-context-simple unfortunately even if IBus engines returns FALSE with Ctrl-Shift-u.

**Comment by seb128** [comment]
@gunnarhj removing the patch seems fine to me, reading comments on the reports referenced at the time the patch was added it looks like the issue might have been addressed in 1.5.19

**Comment by mkurz** [comment]
@gunnarhj I see you finally dropped that patch:
https://git.launchpad.net/ubuntu/+source/ibus/commit/?id=8e8bba42433f3042271fa3fb374d62557f01a716
```
  * Dropped patches:
    ...
    - d/p/ubuntu-unicode-keybinding.patch (discussed at
      https://github.com/ibus/ibus/issues/2163)
```
So the patch is not applied anymore starting with version `1.5.22-4ubuntu1`, so Ubuntu Groovy already does _not_ contain the patch anymore ([because it's already on version `1.5.22-5` as of time of my writing](https://packages.ubuntu.com/groovy/ibus)).
Ubuntu Focal (20.04 LTS) however [still uses](https://packages.ubuntu.com/focal/ibus) `1.5.22-2ubuntu2` with that patch... Any chance Focal will also upgrade to `1.5.22-5`? Or at least backport the un-patching?
Would be great, thanks!

**Comment by gunnarhj** [comment]
@mkurz wrote:

> Any chance Focal will also upgrade to 1.5.22-5? Or at least backport the un-patching?

Stable release updates in Ubuntu come with some 'paper work', and I for one don't find it important enough to bother with such an update in focal for that reason only.

If you think otherwise, I would suggest that you file a Launchpad bug with a bug description which complies with [this template](https://wiki.ubuntu.com/StableReleaseUpdates#SRU_Bug_Template).

**Comment by gunnarhj** [comment]
> Stable release updates in Ubuntu come with some 'paper work', and I for one don't find it important enough to bother with such an update in focal for that reason only.

I changed my mind, and [it's about to be fixed](https://launchpad.net/bugs/1885914).

**Comment by mkurz** [comment]
> I changed my mind, and [it's about to be fixed](https://launchpad.net/bugs/1885914).

Fantastic news, thanks Gunnar!

**Comment by gunnarhj** [comment]
Fixed in Ubuntu 20.04.

**Comment by mkurz** [comment]
@gunnarhj thanks!

**Comment by pdkovacs** [comment]
I still seem to have this issue with Ubuntu 20.04. After resetting to `<Control><Shift><Super>u` in `ibus-setup` (and rebooting), `<Control><Shift>u` still switches into Unicode-input (as well as `<Control><Shift><Super>u` does).

**Comment by gunnarhj** [comment]
@pdkovacs: Do you have version **1.5.22-2ubuntu2.1** of the IBus packages? Did you "Apply" the alternative shortcuts properly?

(Rebooting isn't necessary. The new shortcut should be effective instantly.)

**Comment by pdkovacs** [comment]
@gunnarhj thanks for the quick comment. I have:
```
pkovacs@~ $ ibus version
IBus 1.5.22
```
Should I install a different version?

**Comment by gunnarhj** [comment]
> pkovacs@~ $ ibus version
> IBus 1.5.22

I rather asked for the output of this command:

    dpkg-query -W ibus

**Comment by pdkovacs** [comment]
Yep, sorry!
```
pkovacs@~ $ dpkg-query -W ibus
ibus	1.5.22-2ubuntu2.1
pkovacs@~ $ 
```

**Comment by gunnarhj** [comment]
> ibus	1.5.22-2ubuntu2.1

Ok, that's the latest version in Ubuntu 20.04.

I can't reproduce the issue you describe. Please note that what you set according to the screenshot was `<Control><Alt><Shift><Super>o`, i.e. not `<Control><Shift><Super>o` as you mentioned in a comment.

**Comment by pdkovacs** [comment]
Yes, I mistyped sorry.
Nonetheless, neither `<Control><Alt><Shift><Super>o` nor `<Control><Shift><Super>o` switch to Unicode input. `<Control><Alt><Shift><Super>u` and `<Control><Shift><Super>u` do, despite the setting in effect shown on the screenshot.

**Comment by gunnarhj** [comment]
Not sure what else to ask.. Well, to confirm that you have the right version of all the IBus related packages, can you please run this command:

    dpkg -l | grep 1.5.22-2ubuntu2.1

Also, are you on a standard Ubuntu installation, i.e. with GNOME? X or Wayland?

**Comment by pdkovacs** [comment]
```
pkovacs@~ $ dpkg -l | grep 1.5.22-2ubuntu2.1
ii  gir1.2-ibus-1.0:amd64                      1.5.22-2ubuntu2.1                     amd64        Intelligent Input Bus - introspection data
ii  ibus                                       1.5.22-2ubuntu2.1                     amd64        Intelligent Input Bus - core
ii  ibus-data                                  1.5.22-2ubuntu2.1                     all          Intelligent Input Bus - data files
ii  ibus-gtk:amd64                             1.5.22-2ubuntu2.1                     amd64        Intelligent Input Bus - GTK2 support
ii  ibus-gtk3:amd64                            1.5.22-2ubuntu2.1                     amd64        Intelligent Input Bus - GTK3 support
ii  libibus-1.0-5:amd64                        1.5.22-2ubuntu2.1                     amd64        Intelligent Input Bus - shared library
ii  python3-ibus-1.0                           1.5.22-2ubuntu2.1                     all          Intelligent Input Bus - introspection overrides for Python (Python 3)
```
```
pkovacs@~ $ loginctl show-session $(awk '/tty/ {print $1}' <(loginctl)) -p Type | awk -F= '{print $2}'
x11
pkovacs@~ $ 

```
Standard Ubuntu installation, and (based on the `loginctl` output) I guess it's X, not Wayland. And it is GNOME...I mean the Ubuntu-version of GNOME (Unity, I guess.)

**Comment by gunnarhj** [comment]
That's a bit worrying. Previously `GTK_IM_MODULE` was set automatically via `im-config`, but we have stopped doing that for GNOME. So the only IM related variables on my machine are:

    $ env | grep -E 'XMOD|_IM'
    XMODIFIERS=@im=ibus
    QT_IM_MODULE=ibus

And the Unicode code point shortcut still works fine for me with gedit. GNOME is supposed to handle that internally. At least that's what we assumed when changing it.

**Comment by pdkovacs** [comment]
I seem to have the same settings in effect:
```
pkovacs@~ $ env | grep -E 'XMOD|_IM'
XMODIFIERS=@im=ibus
QT_IM_MODULE=ibus
pkovacs@~ $ 
```

**Comment by gunnarhj** [comment]
Can you test some alternative shortcut with something else but gedit? For instance gnome-terminal or LibreOffice (without setting `GTK_IM_MODULE`).

**Comment by pdkovacs** [comment]
I can observe the issue with gnome-terminal...also with Slack (my original issue that I want to use Ctrl-Shift-U to add links on Slack :-) ). (Slack uses Elektron, which, in turn, is based on Chromium AFAIK.)

**Comment by gunnarhj** [comment]
@pdkovacs: Another thought: What's the output for you from this command:

    gsettings get org.gnome.desktop.interface gtk-im-module

**Comment by pdkovacs** [comment]
```
pkovacs@~ $ gsettings get org.gnome.desktop.interface gtk-im-module
'gtk-im-context-simple'
pkovacs@~ $ 
```

**Comment by pdkovacs** [comment]
If I put `export GTK_IM_MODULE=ibus` in my `.profile`, gnome-terminal and gedit works as expected, Slack in contrast doesn't.

**Comment by gunnarhj** [comment]
gunnarhj wrote:
> Previously GTK_IM_MODULE was set automatically via im-config, but we have stopped doing that for GNOME. So the only IM related variables on my machine are:
>
>     $ env | grep -E 'XMOD|_IM'
>     XMODIFIERS=@im=ibus
>     QT_IM_MODULE=ibus
>
> And the Unicode code point shortcut still works fine for me with gedit. GNOME is supposed to handle that internally.

I made some observations on how GNOME handles it. The `gtk-im-module` dconf key is set by `gnome-settings-daemon` (g-s-d) automatically.

- If either the _On Screen Keyboard_ is enabled, if your machine has a touch screen, or if you have an IBus input method in your list of input sources, g-s-d sets `gtk-im-module` to "ibus" and changing the Unicode code point shortcut works as expected.

- Otherwise g-s-d sets `gtk-im-module` to "gtk-im-context-simple" which breaks the ability to modify the Unicode code point shortcut.

The applicable g-s-d code can be found [here](https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/blob/master/plugins/keyboard/gsd-keyboard-manager.c#L295).

So, @pdkovacs, if you are in an experimental mode, can you please add some IBus input method to your input sources list (so `gtk-im-module` is set to "ibus") and drop the setting of `GTK_IM_MODULE` in `~/.profile`. It would be interesting to know if that makes a difference with respect to Slack.

But in any case I think we have identified a new problem. @fujiwarat: Your input on which route to take to fix it would be much appreciated.

- Should g-s-d be changed somehow?

- Can IBus be changed so the Unicode code point shortcut can be manipulated also under "gtk-im-context-simple"?

- Should Ubuntu and Debian go back to set `GTK_IM_MODULE=ibus` also on GNOME desktops? (That's a question with wider implications than this Unicode shortcut thing.)

**Comment by pdkovacs** [comment]
@gunnarhj
My machine doesn't have touch-screen. I tried `onboard`, but enabling it didn't change `gtk-im-module` to `ibus`. I am not sure where I can find my list of input sources.

**Comment by gunnarhj** [comment]
> I tried onboard, but enabling it didn't change `gtk-im-module` to `ibus`.

I didn't mean onboard, but gnome-shell's built-in On Screen Keyboard (OSK). You can enable it via _Settings -> Universal Access_ (under _Typing_ you find the control for enabling _Screen Keyboard_).

> I don't know where I can find my list of input sources.

Let's try with enabling OSK first. It's the easiest way to change `gtk-im-module` and with that make the Unicode code point shortcut work as expected.

**Comment by pdkovacs** [comment]
Enabling OSK
1. changed `gtk-im-module` to `ibus`
1. made the shortcuts behave as expected in gnome-terminal
1. didn't change the behavior in Slack. Actually, OSK didn't come up on keypress with Slack in focus (whereas it did comeup with gnome-terminal and Chrome for example)

**Comment by gunnarhj** [comment]
@pdkovacs: Maybe Slack is a separate problem. Btw, did you install it via .deb file or snap?

As regards the rest you seem to see the same thing as I see: For the shortcut to work, you either need to somehow make `gtk-im-module` have the value "ibus", or you need to set the `GTK_IM_MODULE` environment variable to "ibus".

**Comment by fujiwarat** [comment]
@pdkovacs 

> pkovacs@~ $ gsettings get org.gnome.desktop.interface gtk-im-module
> 'gtk-im-context-simple'

This means you do not enable ibus for gtk-im-module.
You have to enable one more than input method sources besides xkb sources using `gnome-control-center region`.
You could check if your sources have ibus with `gsettings get org.gnome.desktop.input-sources sources`.

**Comment by gunnarhj** [comment]
@fujiwarat: Do you mean that it's expected behavior? Are the answers to the three questions I asked in [this comment](https://github.com/ibus/ibus/issues/2163#issuecomment-707967589) "no"?

**Comment by pdkovacs** [comment]
@fujiwarat
Laymen here: Are then
* my _Keyboard input method system_ setting being set to `IBus` and
* `ibus` not being enabled for `gtk-im-module`

two settings in conflict with each other?

I have:
```
pkovacs@~ $ gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'us'), ('xkb', 'hu+102_qwertz_comma_dead')]
```
I am not exactly sure what to do with `gnome-control-center region`. I have two items in the _Input Source_ section. Should I add a third one?

**Comment by pdkovacs** [comment]
@gunnarhj I install Slack using snap. (Actually, I installed it via the graphical Ubuntu installer and I can execute `/snap/bin/slack`.)

**Comment by pdkovacs** [comment]
Still regarding Slack: I can get rid of the sticky Ctrl-Shift-U shortcut by changing _Keyboard input method system_ from `IBus` to `XIM`, but then I seem to lose the ability to enter Unicode characters.

**Comment by gunnarhj** [comment]
@pdkovacs: This is how you can enable an IBus input source:

- `sudo apt install ibus-libpinyin`
- Log out and log in again
- Go to _Settings -> Region & Language_
- In the _Input Sources_ section click the + button and add **Intelligent Pinyin** (you probably find it in the _Other_ window on your machine)

As regards Slack, besides the snap they offer a .deb file [here](https://slack.com/intl/en-se/downloads/linux). So you may want to uninstall the snap (`snap remove slack`) and install slack via that .deb instead. Not saying it will make a difference wrt the Unicode code point shortcut, but might be worth a try.

**Comment by pdkovacs** [comment]
@gunnarhj 
Thank you for the description of how to enable an IBus input source! I start to feel that the way for `ibus` to be enabled for `gtk-im-module` for my use case is to simply set the env var (as you also indicated). (I am not a big fan of pinyin any way, it ever comes to Chinese input, I will prefer a stroke-based system, I guess.)

And thanks for the tip on Slack from _deb_, I might try it sometime in the future and report back.

**Comment by mike-fabian** [comment]
> (I am not a big fan of pinyin any way, if it ever comes to Chinese input, I will prefer a stroke-based system, I guess.)

Then you might want to use ibus-table, ibus-table supports several stroke based input systems like wubi, cangjie, stroke5, ...

**Comment by fujiwarat** [comment]
@pdkovacs 

> I start to feel that the way for ibus to be enabled for gtk-im-module for my use case is to simply set the env var (as you also indicated). 

You can choose either way of adding IBus engines or setting GTK_IM_MODULE. But in Wayland, ibus is slave of gtk-im-context-simple, which behavior is different from Xorg.

`env GTK_IM_MODULE=ibus gedit` should enable ibus only.
If you use gnome-terminal, you have to run gnome-terminal-server at first. E.g.
`env GTK_IM_MODULE=ibus /usr/lib*/gnome-terminal-server && sleep 1 && gnome-terminal`

**Comment by sara-rodriguez** [comment]
This is a bug listed here: 

`https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1885914`

The solution that I found is to remove the ibus package:

`$ sudo apt-get remove ibus`
`$ sudo apt-get purge ibus`

Go to updates and set the repository for *focal fossa* version for Ubuntu and remove the remanescent *eoan*

Go to language suport and set the iBus method, for user and root

In the terminal for user and root:
`ibus-setup`
and change the shortcuts in the emoji tab

In the terminal for user and root:
`im-config`
and set ibus

For user in the terminal:
`gedit .bashrc`

Include the following lines at the end:
`export GTK_IM_MODULE=ibus`
`export XMODIFIERS=@im=ibus`
`export QT_IM_MODULE=ibus`

**Comment by gunnarhj** [comment]
@sara-rodriguez: Are you talking about a workaround for Ubuntu 19.10, i.e. an Ubuntu version which is no longer supported?

**Comment by sara-rodriguez** [comment]
> @sara-rodriguez: Are you talking about a workaround for Ubuntu 19.10, i.e. an Ubuntu version which is no longer supported?

In my case, I upgrade the Ubuntu version and I found that it can cause the issues related here for the ibus package

**Comment by gunnarhj** [comment]
@sara-rodriguez: If you are on Ubuntu 20.04, all you need to do is making sure that `-updates` is enabled (which it is by default) and update your packages. That would give you ibus 1.5.22-2ubuntu2.1.

**Comment by sara-rodriguez** [comment]
> @sara-rodriguez: If you are on Ubuntu 20.04, all you need to do is making sure that `-updates` is enabled (which it is by default) and update your packages. That would give you ibus 1.5.22-2ubuntu2.1.

yes, and it was updated, but unfortunately I had some old repositories, so I just deleted them
I had this ctrl+shift+u issue, conflicting with the change case in chrome, but following these steps it was finally solved
