### ISSUE TITLE
Three layers candidate box in XIM programs with embed preedit

### ISSUE THREAD

**Issue by tuberry** [ibus/ibus#2164]
Distribution : Arch Linux
DE : Gnome 3.34.2
Session : X11 
Application: Alacritty 0.4.0 / xterm 
IBus : ibus 1.5.21/ibus-libpinyin 1.11.1-2

Issue description:
A picture is enough.
![three](https://user-images.githubusercontent.com/17917040/70857787-015d3b80-1f30-11ea-8120-cf06b6c3d0af.png)

Steps to reproduce:
1. install ibus, ibus-libpinyin and alacritty 
1. setup ibus for XIM:`echo 'export XMODIFIERS=@im=ibus'  >>  ~/.xprofile`
1. turn on `Embed preedit text in appplication window` in `IBus Preferences/General`
1. input any words in alacritty or xterm

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes 

By the way, could IBus deprecate python2 dependency? It's the only program requiring python2 in my machine.  And the (tips) in issue template can mark as HTML comments to hide in last view.
Thanks!

**Comment by fujiwarat** [comment]
Because that setting does not work in many X11 applications.
You can run `xterm -xrm "XTerm*preeditType: Callback"` and you can see the warning message the callback mode is not supported.
I don't try Alacritty but probably it's a same issue.

**Comment by fujiwarat** [comment]
You can see gedit can work with the ibus setting.

**Comment by tuberry** [comment]
Yes, I do know that option works in gedit, but it's weird in programs only supporting XIM protocol like xterm. How about turning it off automatically in these applications.  Thanks!------------------ 原始邮件 ------------------
发件人: "Takao Fujiwara"<notifications@github.com>
发送时间: 2019年12月17日(星期二) 晚上7:31
收件人: "ibus/ibus"<ibus@noreply.github.com>;
抄送: "tubery"<orzun@foxmail.com>;"Author"<author@noreply.github.com>;
主题: Re: [ibus/ibus] Three layers candidate box in XIM programs with embedpreedit (#2164)



You can see gedit can work with the ibus setting.
 
&mdash;

**Comment by tuberry** [comment]
Yes, it's indeed works in gedit but wired in programs only supporting XIM protocol like xterm. How about disabling it automatically in these applications. Thanks!

**Comment by tuberry** [comment]
es, it's indeed working in gedit but wired in programs only supporting XIM protocol like xterm. How about disabling it automatically in these applications. Thanks!

**Comment by tuberry** [comment]
Yes, it's working in gedit but wired in programs only supporting XIM protocol like xterm. How about disabling it automatically in these applications. Thanks!
