### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [ibus/ibus#2165]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by fujiwarat** [comment]
Probably I think it's better to open the Fedora bugs for the Fedora maintainers instead of the upstream.

>    [mandatory] which branch is your development branch?
master

>    [mandatory] have you merged latest translation from Zanata and locked the project?
yes

>    [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
>    [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
It should be same with the license in the ibus SPEC file in Fedora.

>    [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
The comment lines for MSGID should be informed to translators.

>    [optional] do you need us to activate any specific checks? (this is a setting per component [3])
Hope not to change the header comments in each PO file while I reported the issue to Zanata but it's still not fixed.

>    [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)
No but the customizable option would be desireble.

**Comment by Jibec** [comment]
Do you have many translation platform and one maintainer per distribution?

**Comment by fujiwarat** [comment]
I'm the upstream maintainer and accept translation from upstream contributors here and also I also manage the Fedora l10n contributors in with Zanata the downstream. I recommended to use Zanata to l10n contributors but it would not be required. 
I think I replied your questions above and I already join trans@lists.fedoraproject.org

**Comment by Jibec** [comment]
configuration is done: https://translate.stg.fedoraproject.org/projects/ibus/ibus/
user fujiwarat got the administration rights on the Weblate project.

you may be interesting in activating one of the following checks:
https://docs.weblate.org/en/weblate-3.10/admin/checks.html#customizing-behavior

you can see the result of a pull request: https://github.com/ibus/ibus/pull/2169

a problem I can't solve myself: you don't store the pot file in your repository.
This prevents a one-click addition of a new language using Weblate. Only existing translation can be updated using Weblate.
Would you mind adding the pot file to you repository?

Suggestion about non Weblate translation contribution: any user can upload files with their translation in Weblate in one click. All Weblate user will be able to see changes. I suggest you to invite contributors to use this way of submitting translation.
You can also do it for them (you'll have the possibility to write their name and email address so attribution is respected).
This way also prevent file conflicts in PRs.

**Comment by fujiwarat** [comment]
thx for creating the repository.

I cannot find to check out the translations directly with `wlc` command line.
Seems `wlc pull` means pull from github/ibus to translate.stg/ibus but I wish to check out the translations on translate.stg to my local disc. Seems the GUI provides to checkout the ZIP file.
Also I'd disable the pull requests by languages. I'd commit all the PO files to github one time before the translations freeze.

> This prevents a one-click addition of a new language using Weblate.  Only existing translation can be updated using Weblate.

Which a new PO file or a new msgid do you mean?
I don't want to push unstable POT file automatically since we track the git master branch only. I'd push a POT file to translation.stg by manual until the translation freeze.
But I cannot find to push a POT file to translation.stg with `wlc` command while I did in Zanata.

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

> thx for creating the repository.
>
> I cannot find to check out the translations directly with `wlc` command line.
> Seems `wlc pull` means pull from github/ibus to translate.stg/ibus but
> I wish to check out the translations on translate.stg to my local
> disc. Seems the GUI provides to checkout the ZIP file.

I  use  something like

    git remote add https://github.com/weblate/ibus-table.git weblate
    git fetch weblate
    git checkout -b weblate-master -t weblate/master

Then I have the translations (from the current weblate pull request) on
my local dist and can look at them. If I want to this branch to be
up-to-date with the latest translations done in weblate, I use the
weblate graphical interface to "commit" and "push", then get the
updated branch from the git command line again.

**Comment by fujiwarat** [comment]
OK, seems the pull request is a digest to have many patches by languages until the pull request is closed. Also the patch author is the translator - it's good.

I will modify all the patches of the pull request.
1. Revert the null comment between the copy right lines and PO translators
2. Update my copyright 2015-2019 to 2015-2020
3. Squash the commit comments not to have multiple % progress

Then Weblate needs to override the PO files from github.

**Comment by fujiwarat** [comment]
@mike-fabian thx. Since the pull request is a digest to have many languages, the pull request is fine with me now.

> I use the weblate graphical interface to "commit" and "push", then get the
updated branch from the git command line again.

I often modify pull requests and need to bring back the upstream translations to Weblate again so probably I won't use the "commit" and "push" web interface.

**Comment by fujiwarat** [comment]
> Suggestion about non Weblate translation contribution: any user can upload files with their translation in Weblate in one click. 

I will invite translate contributors to Weblate but probably I won't ask to use Weblate forcibly. 

> You can also do it for them (you'll have the possibility to write their name and email address so attribution is respected).

OK, let me try it.

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

> OK, seems the pull request is a digest to have many patches by languages until the pull request is closed. Also the patch author is the translator - it's good.
>
> I will modify all the patches of the pull request.
> 1. Revert the null comment between the copy right lines and PO translators
> 2. Update my copyright 2015-2019 to 2015-2020
> 3. Squash the commit comments not to have multiple % progress
>
> Then Weblate needs to override the PO files from github.

I once made the mistake to push PO files I had changed locally.
I had done

   make dist

which updated the ibus-typing-booster.pot file *and* all the *.po
files, all the line numbers pointing to source code usually change in
the *.po files when doing that, that is normal.

But then I made the mistake to push not only that changed
ibus-typing-booster.pot file, which is fine, but also all the changed
*.po files.

That created lots of conflicts with the PO files Weblate had and Weblate
could not automatically resolve these conflicts. Jean-Baptiste solved
that problem somehow and told me that I should never push changed *.po
files to my github repo but let Webdate update the line numbers in the
*.po files by only pushing my .pot file. And then merge the pull
requests Weblate makes to get the updated PO files.

**Comment by fujiwarat** [comment]
> That created lots of conflicts with the PO files Weblate had and Weblate
could not automatically resolve these conflicts.

That sounds trouble with me to use Weblate.
I won't just integrate PO files on Weblate as I noted example.
I also won't bump the product version for just translation updates.
I hope a way to update POT files in Weblate without bumping the product version.

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

>> I use the weblate graphical interface to "commit" and "push", then get the
> updated branch from the git command line again.
>
> I often modify pull requests and need to bring back the upstream translations to Weblate again so probably I won't use the "commit" and "push" web interface.

I had upstream pull requests for translations for new languages twice
since moving to weblate. In these cases I took the new nl.po file from
the pull request and uploaded it into Weblate via the webinterface and
then got it back into my git via the pull request done by Weblate.

That worked fine because these translations were completely new, so
there were no conflicts.

I am not sure what to do if somebody makes a pull request in my github
repo which *updates* a po file which already exists in Weblate. If
nobody has changed that language in weblate at the same time, then
*maybe* it is OK to upload the updated po file from the upstream pull
request via the weblate interface then. I am not 100% sure, but it might
work.

If there have been changes in Weblate as well, then the changes need to
be merged somehow. I don’t yet know how to do that it didn’t happen so
far.  I hope there is an easy way to do it but I don’t know yet.  It is
still new for me.

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

>> Suggestion about non Weblate translation contribution: any user can upload files with their translation in Weblate in one click. 
>
> I will invite translate contributors to Weblate but probably I won't ask to use Weblate forcibly. 
>
>> You can also do it for them (you'll have the possibility to write their name and email address so attribution is respected).
>
> OK, let me try it.

Yes, I did this twice for non-Weblate contributions, it worked fine, the
languages were completely new. I didn’t want to force the contributors
to do it, I was happy to receive a contribution and didn’t want to make
it difficult for the contributors. I write a comment that they can use
Weblate next time if they like, but I don’t want to force them.

I am not sure what would happen if somebody makes a non-Weblate
contribution *updating* a translation which already exists in Weblate.

Would uploading such a updated po file into Weblate work? Would Weblate
merge it properly? I have no idea at the moment.

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

>> That created lots of conflicts with the PO files Weblate had and Weblate
> could not automatically resolve these conflicts.
>
> That sounds trouble with me to use Weblate.
> I won't just integrate PO files on Weblate as I noted example.
> I also won't bump the product version for just translation updates.
> I hope a way to update POT files in Weblate without bumping the product version.

I currently do it like this (not sure whether this is the best way to do
it, but at least it works for me):

1) Release ibus-typing-booster 2.7.3:
   push to github master, tag, update release tarball, ...
2) Make a branch like "next-release" in my local git clone
   and continue my development for the next release on that branch
3) When I see there is a pull request from Weblate, I merge it
   into origin/master.
   So my upstream master has the new translations, the pull request
   is closed but my unstable development code is *not* pushed to origin/master
   (If I want to have a backup, I push my "next-release" branch
   upstream, nobody else should touch that branch, I can just delete it
   any time I like)
4) When I want to release ibus-typing-booster 2.7.4:
   4a) Check if there is a pull request from Weblate again and repeat 3) if necessary.
   4b) Rebase my "next-release" branch on current origin/master
   4c) push "next-release" to origin/master, tag, update release tarball, ...

This seems to work well for me. I did it differently while using Zanata,
but I don’t mind the change, my new way of doing it also works well
enough for me.

There are probably other ways of doing it, this is just one way
which works for me.

**Comment by fujiwarat** [comment]
> 1) Release ibus-typing-booster 2.7.3:

Disagreed to make the tarball for POT files.
If there is no way to push POT files to Weblate directly, probably I continue to use Zanata.

**Comment by fujiwarat** [comment]
> I had upstream pull requests for translations for new languages twice
since moving to weblate. In these cases I took the new nl.po fi

But my examples 1, 2, 3 are caused by Weblate bugs. Your way does not resolve my problems.
I meant to modify the header of the PO files and commit messages.

**Comment by Jibec** [comment]
For the commit message, you should be able to change it using weblate interface and set whatever you require.

For the header comments, I have no idea. Please open an issue in weblateorg/weblate on github.

**Comment by fujiwarat** [comment]
After I push the commits into master, I go to https://translate.stg.fedoraproject.org/projects/ibus/ibus/ and click "Reset" and "Pull" and I guess the latest PO files including PO headers are integrated into Weblate?

I'm not sure how I could change the commit message on Weblate.
I mean to squash the commit comments.

E.g. I modified:
```
commit 3f4cfa7c8ad129f61307b4db133a36975af15e2e
Author: Mike FABIAN <mfabian@redhat.com>
Date:   Sun Jan 5 19:49:29 2020 +0100

    Translated using Weblate (German)
    
    Currently translated at 100.0% (514 of 514 strings)
    
    Translation: ibus/ibus
    Translate-URL: https://translate.stg.fedoraproject.org/projects/ibus/ibus/de/
    
    Translated using Weblate (German)
    
    Currently translated at 100.0% (514 of 514 strings)
    
    Translation: ibus/ibus
    Translate-URL: https://translate.stg.fedoraproject.org/projects/ibus/ibus/de/
    Translated using Weblate (German)
    
    Currently translated at 41.1% (211 of 514 strings)
    
    Translation: ibus/ibus
    Translate-URL: https://translate.stg.fedoraproject.org/projects/ibus/ibus/de/
```

to 

```
commit 3f4cfa7c8ad129f61307b4db133a36975af15e2e
Author: Mike FABIAN <mfabian@redhat.com>
Date:   Sun Jan 5 19:49:29 2020 +0100

    Translated using Weblate (German)
    
    Currently translated at 100.0% (514 of 514 strings)
    
    Translation: ibus/ibus
    Translate-URL: https://translate.stg.fedoraproject.org/projects/ibus/ibus/de/

    BUG=https://github.com/ibus/ibus/pull/2169
```

I don't want too long progress message

Currently I cannot update the POT file directly to Weblate without creating tarballs? If so, I will file the issue to weblateorg/weblate.

**Comment by fujiwarat** [comment]
Probably I'd like to know how to push PO files into https://translate.stg.fedoraproject.org/git/ibus/ibus/ forcibly by manual instead of the web interface?

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

>> 1) Release ibus-typing-booster 2.7.3:
>
> Disagreed to make the tarball for POT files.
> If there is no way to push POT files to Weblate directly, probably I continue to use Zanata.

Maybe there is a way, there seem to be other ways of doing it.

Maybe this thread helps:

https://lists.fedoraproject.org/archives/list/trans@lists.fedoraproject.org/thread/EJY6B73ZV52NXB5JZL5P77DASGD7AGQC/

-- 
📧 Mike FABIAN   <mike.fabian@gmx.de>
睡眠不足はいい仕事の敵だ。

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

> After I push the commits into master, I go to
> https://translate.stg.fedoraproject.org/projects/ibus/ibus/ and click
> "Reset" and "Pull" and I guess the latest PO files including PO
> headers are integrated into Weblate?

I don’t know what "Reset" actually does.

"Pull" seems to integrate the latest POT file from  upstream into
weblate. If the latest upstream also has changed PO files, this may
cause a problem. I don’t know whether it *always* cause problems but
it did cause a problem for me. So I know follow Jean-Baptiste’s advice
to let only Weblate do changes to the PO files.

> Currently I cannot update the POT file directly to Weblate without creating tarballs? If so, I will file the issue to weblateorg/weblate.

I use "make dist" to  create the POT file and "make dist" also happens
to create a tarball. But that is a side effect, I don’t use the tarball,
I can delete it again immediately if I like. I only want the POT file
which "make dist" creates.  And then I only commit that POT file to
master and push that to my upstream repository to get the new pot file
to Weblate.

"make dist" is just the  most convenient way for me  to trigger
regeneration of the POT file.

**Comment by fujiwarat** [comment]
> I don’t know what "Reset" actually does.

I check out the Weblate git directly and seems "Reset" and "Pull" works fine as I expected.
I.e. the copyright header is update from 2019 to 2020.
https://translate.stg.fedoraproject.org/git/ibus/ibus/

> I use "make dist" to  create the POT file and "make dist" also happens to create a tarball. But that is a side effect, 

OK, I see. Through the discussion, probably I think the realistic way is to push the POT file in ibus/po in github.com/ibus/ibus and manage the POT file with the Fedora schedule.

1. The POT file is up to date whenever translatable strings are updated before the translation freeze.
2. The POT file is not updated after the translation freeze until GA

How does Weblate recognize the POT file to update PO files?
I can find "Manage" -> "Settings" -> "Files" -> "Template for new translations"
I think this POT file is used for a new PO file for a user language likes `msginit` command.
But I'm searching a setting of the POT file to update PO files likes `msgmerge` command.
ibus POT file will be "po/ibus10.pot" with `make ibus10.pot`

**Comment by mike-fabian** [comment]
Takao Fujiwara <notifications@github.com> さんは書きました:

> How does Weblate recognize the POT file to update PO files?
> I can find "Manage" -> "Settings" -> "Files" -> "Template for new translations"
> I think this POT file is used for a new PO file for a user language likes `msginit` command.
> But I'm searching a setting of the POT file to update PO files likes `msgmerge` command.
> ibus POT file will be "po/ibus10.pot" with `make ibus10.pot`

If I push a new POT file to my ibus-typing-booster github and then click
"Pull" in the Weblate interface, Weblate gets the new POT file and
updates all the PO files, probably using something like msgmerge.

If I don’t click "Pull", Weblate also does this after a while, but it
may take a few days, clicking on "Pull" makes Weblate do it immediately.

**Comment by fujiwarat** [comment]
> If I push a new POT file to my ibus-typing-booster github and then click
"Pull" in the Weblate interface,

I mean if Weblate retrieve the textdomain name correctly. IBus's POT file is ibus10.pot but not ibus.pot. I can find a setting for the new languages only but not merge POT file in Weblate GUI.
Anyway I pushed ibus10.pot now and clicked "Pull" and I see a message of "Rebased repository" in Weblate GUI but I'm not sure if Weblate retrieves the IBus POT file.

**Comment by Jibec** [comment]
Looks like everything works fine, you did set the correct settings for 
the pot file.

I also added LINGUAS and POT Merge features:
https://translate.stg.fedoraproject.org/addons/ibus/ibus/

I suggest you to change commit messages to match your expectations:
https://translate.stg.fedoraproject.org/settings/ibus/ibus/#messages

for me this project is done migrating, thanks for your help
