### ISSUE TITLE
ibus-config test failure on some (slow) architectures

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2170]
I encountered Debian build failure regression on hppa and riscv64 architectures, on the "ibus-config" test.

Here is the build log:

> https://buildd.debian.org/status/fetch.php?pkg=ibus&arch=hppa&ver=1.5.21-5&stamp=1577880361&raw=0
> https://buildd.debian.org/status/fetch.php?pkg=ibus&arch=riscv64&ver=1.5.21-5&stamp=1577882332&raw=0

But I the only related difference with the previous successful build is the addition of environment variables $HOME and $XDG_CONFIG_HOME when running the tests:

```
@@ -91,13 +91,17 @@ override_dh_missing:
 
 override_dh_auto_test:
 ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
+	mkdir -p -m700 $(CURDIR)/debian/tmp-home
+	mkdir -p -m700 $(CURDIR)/debian/tmp-home/.cache
+	mkdir -p -m700 $(CURDIR)/debian/tmp-home/.config
+	mkdir -p -m700 $(CURDIR)/debian/tmp-home/.local/share
 	mkdir -p -m700 $(CURDIR)/debian/tmp-xdg-runtime-dir
-	mkdir -p -m700 $(CURDIR)/debian/tmp-xdg-cache-home
-	mkdir -p -m700 $(CURDIR)/debian/tmp-xdg-data-home
 	env \
+	  HOME=$(CURDIR)/debian/tmp-home \
+	  XDG_CACHE_HOME=$(CURDIR)/debian/tmp-home/.cache \
+	  XDG_CONFIG_HOME=$(CURDIR)/debian/tmp-home/.config \
+	  XDG_DATA_HOME=$(CURDIR)/debian/tmp-home/.local/share \
 	  XDG_RUNTIME_DIR=$(CURDIR)/debian/tmp-xdg-runtime-dir \
-	  XDG_CACHE_HOME=$(CURDIR)/debian/tmp-xdg-cache-home \
-	  XDG_DATA_HOME=$(CURDIR)/debian/tmp-xdg-data-home \
 	  dbus-run-session -- \
 	  xvfb-run --auto-servernum -- \
 	  dh_auto_test -- \
```

Does the "ibus-config" test depend on timing of the background daemon?  I suspect that because these architectures are very slow compared to other architectures. Newly added $XDG_CONFIG_HOME might make the background daemon a bit slower.

**Comment by changwoo** [comment]
https://github.com/ibus/ibus/blob/c662a02bf3b50914c697af12fc152ee97e2df961/src/tests/runtest#L183

Yes! I changed this delay to 2 seconds and the build succeeded! ( [hppa](https://buildd.debian.org/status/fetch.php?pkg=ibus&arch=hppa&ver=1.5.21-6%7Eexp1&stamp=1578048183&raw=0) [riscv64](https://buildd.debian.org/status/fetch.php?pkg=ibus&arch=riscv64&ver=1.5.21-6%7Eexp1&stamp=1578050161&raw=0) )

Please improve this; Theoretically it can fail even in fast machines if they have heavy CPU load. How about making it wait for ibus-daemon ready rather than arbitrary delay?

**Comment by fujiwarat** [comment]
Could you try to get your error message of ibus-config below?

```
diff --git a/src/tests/ibus-config.c b/src/tests/ibus-config.c
index 5e845f10..c7edb68f 100644
--- a/src/tests/ibus-config.c
+++ b/src/tests/ibus-config.c
@@ -16,6 +16,10 @@ finish_create_config_async_success (GObject      *source_object,
     IBusConfig *config =
           ibus_config_new_async_finish (res, &error);
 
+    if (error) {
+        g_print ("Failed to generate IBusConfig: %s\n", error->message);
+        g_error_free (error);
+    }
     g_assert (IBUS_IS_CONFIG (config));
 
     /* Since we reuse single D-Bus connection, we need to remove the
```

**Comment by fujiwarat** [comment]
Probably I think you need to set `DISABLE_DAEMONIZE_IN_TESTS=1` before you run `runtest` script to get the above error message.

**Comment by changwoo** [comment]
After patching:

```
FAIL: ibus-config
=================

/<<PKGBUILDDIR>>/src/tests/tmp-ibus-config /<<PKGBUILDDIR>>/src/tests
portal is not running: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.portal.IBus was not provided by any .service files
# random seed: R02Sd2a00206137586d09dbbe8ca356b1e1e
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
1..2
# Start of ibus tests
Failed to generate IBusConfig: Configuration daemon is not running.
**
ERROR:ibus-config.c:23:finish_create_config_async_success: assertion failed: (IBUS_IS_CONFIG (config))
Bail out! ERROR:ibus-config.c:23:finish_create_config_async_success: assertion failed: (IBUS_IS_CONFIG (config))
./runtest: line 115: 897846 Aborted                 "../$tst" ../$top_srcdir/src/tests ${1+"$@"}
/<<PKGBUILDDIR>>/src/tests
FAIL ibus-config (exit status: 134)
```

> Probably I think you need to set DISABLE_DAEMONIZE_IN_TESTS=1 before you run runtest script to get the above error message.

It has already been set.

**Comment by fujiwarat** [comment]
Thank you for the test.
From your log, ibus-config test would start before ibus-dconf was launched.
Now I changed the sleep time to 3 and confirmed it would not be so big change.
If 3 secs is still short time, we may need more customization.
