### ISSUE TITLE
The code table I made uses numbers 0-9 as the input code. I want to use the numeric keypad as the input terminal. How should I modify the program?

### ISSUE THREAD

**Issue by YQ-YSY** [ibus/ibus#2173]
I made a  "One-hand Stroke Order Input Method Code Table" , https://github.com/YQ-YSY/stroke-seq_MB, both words and vocabulary are encoded with numbers 0-9 (vocabulary separated by words). In this way, you can type on the small keyboard with one hand, which is much faster than pinyin, and it can also bring convenience to many people with disabilities.

May I ask, can Rime use the numeric keypad as an input terminal? Because there is almost no recoding in stroke order, I think that the Num Lock key on the numeric keypad can be used to switch the control mode. When the keypad's light is off, the word selection state can be used.

How do I modify the program if I want to modify ibus-pinyin to achieve the above functions? In this way, "Pinyin and stroke order input simultaneously" can be realized, because the stroke order code is a number, so they do not interfere with each other and complement each other-when you forget the pinyin, you can immediately enter the stroke order code; Other keys switch modes.

Sorry my English is not good, google translation used.

**Comment by fujiwarat** [comment]
Seems your issue is ibus-libpinyin or ibus-rime.
Please file to https://github.com/libpinyin/ibus-libpinyin/issues
