### ISSUE TITLE
imput shourtcuts didn't work

### ISSUE THREAD

**Issue by Jernel-dotcom** [ibus/ibus#2178]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Debian 10

Which desktop environment and version?: 
Xfce 4.12.1

Which session type?: 
xfce version

Which application and version?: 
all of them 

IBus version?: 
1.5.19

Issue description:
next input didn't switch languages 
alt+shift or any other combinations  

Steps to reproduce:
1. add any language 
2. add shortcut keys 
3. click on chosen keys

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
nothing 

Can you reproduce your problem with a new user account instead of the current your account? 
yes

**Comment by fujiwarat** [comment]
> 3. click on chosen keys

I don't understand what you mean in clicking on chosen keys.

Do you mean click shortcut keys on `ibus-setup` utility and why do you need to click it?

Also you didn't include how to type shortcut keys on the steps to reproduce. Please update the steps again.
