### ISSUE TITLE
候选栏位置

### ISSUE THREAD

**Issue by yueduz** [ibus/ibus#2180]
![2020-02-04 17-30-40 的屏幕截图](https://user-images.githubusercontent.com/1448159/73732050-743aa400-4774-11ea-9674-4960dcef7a96.png)
我认为在我没有按下空格键上屏前，候选条应该定位在图片红色标记位置。这样可以减少候选条过多的移动干扰输入。另外我还认为应该提供一个固定候选栏不跟随光标的选项，例如定位在屏幕顶部。

＃ 状态跟随建议
只要文本框被激活（即使还没开始输入）就让状态栏跟随在光标上，当有候选时，隐藏状态栏，跟随候选栏，当无候选时隐藏候选栏跟随状态栏。可以跟随显示部分状态，如中英状态，全／半角状态。

因为在开始输入法时我真的不知道我当前是中文状态还是英文状态啊。每次都输了四五个键又回头改。

**Comment by fujiwarat** [comment]
> 我认为在我没有按下空格键上屏前，候选条应该定位在图片红色标记位置。

I also wondered why the horizontal lookup window has been shown at the end of the string while vertical lookup window hasn't. I guess the original model exists in other platforms.

CC'ing @epico

BTW, I also proposed the similar fix in vte; https://bugzilla.gnome.org/show_bug.cgi?id=795319

> 这样可以减少候选条过多的移动干扰输入。另外我还认为应该提供一个固定候选栏不跟随光标的选项，例如定位在屏幕顶部。

Currently I don't think such an setting option.

> 只要文本框被激活（即使还没开始输入）就让状态栏跟随在光标上，当有候选时，...

You can show a property panel from ibus-setup -> "General" -> "Show property panel"

> 因为在开始输入法时我真的不知道我当前是中文状态还是英文状态啊。每次都输了四五个键又回头改。

ibus-anthy can show the input mode in the panel and ibus-libpinyin also could be. You can request the feature in https://github.com/libpinyin/ibus-libpinyin/issues .

**Comment by epico** [comment]
I think this is an input method issue, please report this issue to the input method.

The input method should call ibus_engine_update_preedit_text with cursor_pos = 0, to show the panel in the beginning of the preedit text.

**Comment by fujiwarat** [comment]
> I think this is an input method issue, please report this issue to the input method.

I think you mean an IME issue. Closing this now.
