### ISSUE TITLE
使用中文输入引起移动窗口卡顿

### ISSUE THREAD

**Issue by yueduz** [ibus/ibus#2181]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Arch
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: gnome 3.34.2
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: Wayland
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: All
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: IBus 1.5.21
(Run `ibus version`)

Issue description:
我没有在程序和窗口中共享输入法状态。当我在多个激活了中文输入法中的窗口中切换时会有个半秒左右的卡顿。如果不使用en英文键盘就不会卡。如果我在Gnome自动的终端里激活了中文，则每次移动终端窗口都会有卡顿。

我的中文输入法是使用 ibus-table 挂接的码表。

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
I cannot reproduce your problem with ibus-libpinyin and gedit and gnome-terminal.

Which ibus engine do you use? You can check it with `ibus engine` command.

**Comment by yueduz** [comment]
```
$ ibus engine
table:cqyx
```

**Comment by yueduz** [comment]
目前问题消失了。
