### ISSUE TITLE
Default input method not used after coming back from lock screen

### ISSUE THREAD

**Issue by exprosic** [ibus/ibus#2183]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
- Manjaro 18.1.15

Which desktop environment and version?: 
- Xfce 4.14

Which session type?: 
- X11

Which application and version?: 
- mousepad 0.4.2
- neovim 0.4.3
- xfce4-terminal 0.8.9.1
- firefox 72.0.2
- etc.

IBus version?: 
IBus 1.5.21

Issue description:
I replaced the original default input method (English US) with "English (US, international with dead keys)", but when coming back from lock/login screen, no input method is used before changing the input method at least once.

Steps to reproduce:
1. remove the input method "English (US)", replace it with "English (US, international with dead keys)", and then add another whatever input method, make sure both works.
2. lock screen, then unlock
3. go to mousepad/neovim/firefox, press "^", which should be an accent waiting for the following letter under the US-international layout, but instead, a ^ is directly typed
4. switch to another input method and switch it back, then type the same thing and it behaves correctly.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

**Comment by fujiwarat** [comment]
I don't understand your problem exactly.

> 2. lock screen, then unlock

If you set  us-intl before you lock screen, you will get us-intl again after you unlock the screen.
I tried XFCE 4.14 in Fedora 31 and see no problem.

**Comment by exprosic** [comment]
> If you set us-intl before you lock screen, you will get us-intl again after you unlock the screen.
> I tried XFCE 4.14 in Fedora 31 and see no problem.

Have you removed the default English US?

**Comment by fujiwarat** [comment]
> Have you removed the default English US?

Yes, I did.

> Can you reproduce your problem with a new user account instead of the current your account? (yes / no):
> Yes.

Did you really try the new user account?
ibus doesn't change the IMEs with focus changes by default so

> If you set us-intl before you lock screen, you will get us-intl again after you unlock the screen.

This should work.

**Comment by exprosic** [comment]
> Did you really try the new user account?

I just tried and indeed it worked at first.

But it broke after I put `ibus-daemon -drx` into `~/.profile` and login back. The us-intl refuses to work even after switching the input method a few times or `ibus-daemon -rd`. Other input methods work without problems though.

**Comment by fujiwarat** [comment]
Can you run ibus-daemon by manual after the login and check if us-intl works?
I guess ~/.profile would be your problem.

**Comment by exprosic** [comment]
> I guess ~/.profile would be your problem.
Indeed.
> Can you run ibus-daemon by manual after the login and check if us-intl works?
It goes like this:
1. Create a new user, login, `ibus-daemon -d`, setup the input methods. US-intl works.
2. lock&unlock. US-intl works.
3. logout&login. `ibus-daemon -d` manually. US-intl works.
4. add `ibus-daemon -drx` to `~/.profile`, logout&login. US-intl stops working.
5. switch back and forth the input method. US-intl still doesn't work.
6. **comment out `ibus-daemon -d` in `~/.profile`, logout&login. US-intl still doesn't work.**

**Comment by exprosic** [comment]
> > I guess ~/.profile would be your problem.
> > Indeed.
> > Can you run ibus-daemon by manual after the login and check if us-intl works?
> 
> It goes like this:
> 
>     1. Create a new user, login, `ibus-daemon -d`, setup the input methods. US-intl works.
> 
>     2. lock&unlock. US-intl works.
> 
>     3. logout&login. `ibus-daemon -d` manually. US-intl works.
> 
>     4. add `ibus-daemon -drx` to `~/.profile`, logout&login. US-intl stops working.
> 
>     5. switch back and forth the input method. US-intl still doesn't work.
> 
>     6. **comment out `ibus-daemon -drx` in `~/.profile`, logout&login, manually `ibus-daemon -dr`. US-intl still doesn't work.**
> 
>     7. switch back and forth the input method. US-intl still doesn't work.
> 
> 
> Just in case: by US-intl I mean “English (US, international **with** dead keys)”, instead of “English (US, international **AltGr** dead keys)”

It's weird. I did 1-4 again and the problem disappeared.

**Comment by fujiwarat** [comment]
Your comment-out-lines might be wrong.
I think writing .profile is not good since it's not expected in GUI. The us-intl feature is actually compose feature in ibus but not xkb and it needs to open display.
I don't know if Manjaro provides the IM frame work management likes Fedora and Ubuntu but XFCE4 provides xfce4-session-settings.

**Comment by exprosic** [comment]
> Your comment-out-lines might be wrong.
> I think writing .profile is not good since it's not expected in GUI. The us-intl feature is actually compose feature in ibus but not xkb and it needs to open display.
> I don't know if Manjaro provides the IM frame work management likes Fedora and Ubuntu but XFCE4 provides xfce4-session-settings.

But ibus still doesn't behave normally after I restored my `.profile`, relogin, and `ibus-daemon -rd` manually. I think it is still a problem for ibus to get itself into a corrupted and so far irrecoverable configuration.

Is there any diagnostics that can be used to identify the cause of the problem?

**Comment by fujiwarat** [comment]
> But ibus still doesn't behave normally after I restored my .profile

Because I guess your way of the comment-out would not be correct.

> Is there any diagnostics that can be used to identify the cause of the problem?

You could check the shell script of .profile.

**Comment by exprosic** [comment]
> Because I guess your way of the comment-out would not be correct.
> You could check the shell script of .profile.

I'm not sure I understand what you mean by that. My .profile consists of only a few lines, only one of which, `ibus-daemon -drx`, is about ibus. With a hashtag prefixing this line, I assume the .profile would be no longer responsible for any misbehavior of ibus.

**Comment by fujiwarat** [comment]
You could delete your .profile not to run ibus-daemon.
