### ISSUE TITLE
Emoji Choice does not work through C-S-e, but only via systray

### ISSUE THREAD

**Issue by NickHu** [ibus/ibus#2184]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
nixos

Which desktop environment and version?: 
xmonad

Which session type?: 
X11

Which application and version?: 
everything

IBus version?: 
1.5.21

Issue description:
Emoji annotation doesn't work when called through shortcut (CTRL-SHIFT-e), and only works once when going through the IBus system tray icon to "Emoji Choice"

Steps to reproduce:
1. Press `<CTRL>-<SHIFT>-e`
1. Type "smile"
1. See that no completions have come up:
![image](https://user-images.githubusercontent.com/450276/74202057-4c12df80-4c63-11ea-8eea-d09bbbf142db.png)

As I mentioned previously, it does seem to work if you use the IBus system tray icon:
1. Right-click the IBus system tray icon
1. Select "Emoji Choice" (a new Emoji Choice window is spawned)
1. Type "smile"
1. Observe the following completions
![image](https://user-images.githubusercontent.com/450276/74202184-a14ef100-4c63-11ea-9b4b-b0c15bd3d379.png)

Interestingly, no such "Emoji Choice" window is spawned when I hit `<CTRL>-<SHIFT>-e` - is it supposed to?

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Yes

Do you see any errors when you run ibus-daemon with the verbose option?:

No

Can you reproduce your problem with a new user account instead of the current your account?

Yes

**Comment by fujiwarat** [comment]
> Which application and version?:
> everything

That's strange. 

> See that no completions have come up:

GTK application doesn't have such a preedit by default.

Can you attach the screenshot of `env GTK_IM_MODULE=ibus gedit` with `gnome-screenshot -i` ?

**Comment by NickHu** [comment]
> Can you attach the screenshot of env GTK_IM_MODULE=ibus gedit with gnome-screenshot -i ?

When I hit `<CTRL>-<SHIFT>-e` and type `smile`:

![image](https://user-images.githubusercontent.com/450276/74424412-ce5cf880-4e49-11ea-83d0-17a41fb4a506.png)

If I use "Emoji Choice" from the system tray:

![image](https://user-images.githubusercontent.com/450276/74424813-8f7b7280-4e4a-11ea-9e6c-3c4596646f44.png)

(I'm on my work machine, so that's why the emoji font is slightly different - still, the same problem persists - IBus is the same version and my setup is more or less identical)

**Comment by fujiwarat** [comment]
Ah, OK, probably I understand it.
You have to type Space keys to show the candidate window.
The first Space key changes the emoji annotation to an emoji chracters and the second Space key shows the candidate windows and the third Space key shifts the selected emoji and Enter key commit the selected emoji.

The ctrl-shift-u assumes to use keyboard only.
The panel menu assumes to use mouse and I didn't notice the different behaviors.

**Comment by NickHu** [comment]
Ah, you're right, if I hit space then it does select the emoji I want! I think this behaviour is a little confusing - is it documented somewhere? 😃

**Comment by fujiwarat** [comment]
Currently only ibus-emoji(7) man page is provided to explain the behavior of Space key.
