### ISSUE TITLE
Character remain at the cursor

### ISSUE THREAD

**Issue by Denis-Oakley** [ibus/ibus#2185]
Which distribution and version?: 
Ubuntu 18.04

Which desktop environment and version?: 
GNOME 3.28

Which session type?: 
wayland

Which application and version?: 
gedit 3.28.1, terminal

IBus version?: 
IBus 1.5.17

Issue description:
Character remain at the cursor
Reboot, reinstall ibus, libpinyin don't work

Steps to reproduce:
In terminal、gedit:
type any character(eg. `ni`), then type `Esc` or (`Backspace` until delete all), the first character will remain at the cursor, like the last line in the picture, if then type `enter`, it is the picture
![Screenshot](https://user-images.githubusercontent.com/20573568/74599444-d7093500-50bc-11ea-827d-870ff68c7c59.png)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
it shows `current session already has an ibus-daemon.`, but can't use libpinyin in new window any more.

Do you see any errors when you run ibus-daemon with the verbose option?:
`current session already has an ibus-daemon.`

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
no, it works well

**Comment by fujiwarat** [comment]
ibus 1.5.17 is a bit old and I don't see your problem in the latest ibus.
