### ISSUE TITLE
How to use ibus in terminal emulator and code editor?

### ISSUE THREAD

**Issue by Photonico** [ibus/ibus#2186]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Solus 4

Which desktop environment and version?: 
Plasma 5

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: 
Konsole, VSCode

IBus version?: 
IBus 1.5.20

Issue description:
I can use ibus to put Chinese in text editor and Firefox, but I cannot use it in terminal emulator and code editor.

Steps to reproduce:
1. 
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
Can you run `konsole` wish `strace` from `xterm`?

`env QT_IM_MODULE=ibus konsole |& grep inputcontexts`

> Plasma 5

I'd like to know the minor version besides major version. 5.y
Probably you could check the version with `eopkg info` for a package including libQt5Gui.so.*

> Which session type?:
> (X11 or Wayland. Check $XDG_SESSION_TYPE)

Did you run `env | grep XDG` ?

**Comment by Photonico** [comment]
> Can you run `konsole` wish `strace` from `xterm`?
> 
> `env QT_IM_MODULE=ibus konsole |& grep inputcontexts`
> 
> > Plasma 5
> 
> I'd like to know the minor version besides major version. 5.y
> Probably you could check the version with `eopkg info` for a package including libQt5Gui.so.*
> 
> > Which session type?:
> > (X11 or Wayland. Check $XDG_SESSION_TYPE)
> 
> Did you run `env | grep XDG` ?

Thank u very very much.
I have fixed it by editing ~/.pam_environment
