### ISSUE TITLE
Linux Mint中文输入没有候选栏

### ISSUE THREAD

**Issue by thep0y** [ibus/ibus#2190]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Linux Mint 19.3
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Cinnamon 4.4.8
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
x11
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 
(Run `ibus version`)
IBus 1.5.17
Issue description:
中文输入没有候选栏，但能正常输入文字。

Steps to reproduce:

Can you reproduce your problem when you restart ibus-daemon? (yes / no):  yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
(ibus-ui-gtk3:5941): IBUS-WARNING **: 09:30:05.575: panel.vala:308: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:5941): IBUS-WARNING **: 09:30:05.598: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(process:5962): IBUS-WARNING **: 09:30:05.638: org.freedesktop.IBus.Config.GetValue: GDBus.Error:org.freedesktop.DBus.Error.Failed: Config value [engine/Rime:embed_preedit_text] does not exist.

(process:5962): IBUS-WARNING **: 09:30:05.640: org.freedesktop.IBus.Config.GetValue: GDBus.Error:org.freedesktop.DBus.Error.Failed: Config value [engine/Rime:lookup_table_orientation] does not exist.

(process:5962): IBUS-WARNING **: 09:30:05.641: org.freedesktop.IBus.Config.GetValue: GDBus.Error:org.freedesktop.DBus.Error.Failed: Config value [engine/Rime:color_scheme] does not exist.

(ibus-ui-gtk3:5941): IBUS-WARNING **: 09:30:05.657: panel.vala:737: Failed css_provider_from_data: 方正悠宋 GBK weight=450 13: <data>:1:21Expected a string.

(ibus-ui-gtk3:5941): Gdk-CRITICAL **: 09:30:06.007: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

![image](https://user-images.githubusercontent.com/51874567/75498983-9cc85d80-5a03-11ea-9478-80ea8838a7ff.png)

**Comment by fujiwarat** [comment]
Seems you get some warnings of ibus-rime when you rum `ibus-daemon --xim --verbose`.
Can you reproduce your problem with ibus-libpinyin?

**Comment by fujiwarat** [comment]
@thep0y ping
