### ISSUE TITLE
org.freedesktop.portal.IBus: Not connected to the ibus bus

### ISSUE THREAD

**Issue by AlynxZhou** [ibus/ibus#2192]
Which distribution and version?: 

Arch Linux

Which desktop environment and version?: 

GNOME 3.36.0

Which session type?: 

Wayland

Which application and version?: 

Not related.

IBus version?: 

IBus 1.5.22

Issue description:

After upgrade gnome-shell to 3.36.0, got such error when booting up, and ibus failed to autostart:

```
ar 09 10:02:12 pendragon dbus-daemon[630]: [session uid=120 pid=630] Activating service name='org.freedesktop.portal.IBus' requested by ':1.19' (uid=120 pid=688 comm="ibus-daemon --panel disable ")
Mar 09 10:02:12 pendragon org.freedesktop.portal.IBus[696]: Not connected to the ibus bus
Mar 09 10:02:12 pendragon dbus-daemon[630]: [session uid=120 pid=630] Activated service 'org.freedesktop.portal.IBus' failed: Process org.freedesktop.portal.IBus exited with status 1
Mar 09 10:02:12 pendragon gnome-shell[688]: portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1
```

PS There is currently a bug in gnome-shell, I've fixed it via <https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/1080>, and after that I got those error log.

Steps to reproduce:

1. upgrade to gnome-shell 3.36.0
1. apply the fix from the GitLab MR.
1. reboot and see error in log.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 

no, I can start ibus by myself.

Do you see any errors when you run ibus-daemon with the verbose option?:

no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

Not tested.

**Comment by AlynxZhou** [comment]
GNOME Xorg session has those error too, but iBus can start, I don't know why, hope this can help.

**Comment by fplust** [comment]
related: [https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/836](https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/836)

**Comment by AlynxZhou** [comment]
> related: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/836

The wrong method name in this MR has been fixed by myself, but I still got such error and cannot autostart ibus on a pure wayland.

**Comment by AlynxZhou** [comment]
It looks like still a gnome-shell issue instead of ibus issue:

https://gitlab.gnome.org/GNOME/gnome-shell/issues/2341

**Comment by fujiwarat** [comment]
Thank you for the report.
