### ISSUE TITLE
Vala: list_engines method returns nulls

### ISSUE THREAD

**Issue by baraclese** [ibus/ibus#2193]
Which distribution and version?: Arch Linux
Which desktop environment and version?: GNOME 3.36
Which session type?: X11
Which application and version?: valac 0.48.0
IBus version?: 1.5.22

Issue description:
The following simple vala program prints nulls instead of the engine names.

Steps to reproduce:
Compile the following code with valac --pkg ibus-1.0 test.vala
```vala
int main(string[] args)
{
    var bus = new IBus.Bus();
    if (!bus.is_connected())
    {
        return 0;
    }

    var enginelist = bus.list_engines();

    foreach (var engine in enginelist)
    {
        if (engine == null)
            print("null ");
        else
            print("%s\n", engine.get_name());
    }
   
    return 0;
}
```

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
Do you see any errors when you run ibus-daemon with the verbose option?: No
Can you reproduce your problem with a new user account instead of the current your account? (yes / no): I haven't tried.

**Comment by fujiwarat** [comment]
You should call `IBus.init()` before you call `IBus.Bus()`.
