### ISSUE TITLE
IBus systray icon can be unreadable in a systray with a dark background

### ISSUE THREAD

**Issue by ariasuni** [ibus/ibus#2199]
Which desktop environment and version?: KDE Plasma 5.18.3
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

IBus version?: 1.5.22

Issue description:

IBus displays the letter of the languages with a dark blue color that doesn’t work on some backgrounds.

![bildo](https://user-images.githubusercontent.com/2446451/77022923-1f04cb80-698b-11ea-8ee4-79d66b0a0c47.png)

This is a screenshot of my system tray. The second icon from the top in the screenshot is from IBus, telling me I’m using a French keyboard layout as IBus entry method, with the two letters FR in dark blue on black and very hard to read.

Steps to reproduce:
1. Open IBus Preferences
1. Go to Input Method tab
1. Add an entry method that’s just a keyboard layout, e.g. English → English (US)

The current color works well for light backgrounds, but we should at least have another option that works well on dark backgrounds.

**Comment by fujiwarat** [comment]
You could set the color with gsettings command:
```
% gsettings get org.freedesktop.ibus.panel xkb-icon-rgba
'#415099'
```

You can see the document about the value of xkb-icon-rgba in /usr/share/glib-2.0/schemas/org.freedesktop.ibus.gschema.xml
There is still not possible to make a suitable GUI to cover all properties of color names, color rgb values, transparent values and I keep the CLI with gsettings.
