### ISSUE TITLE
Remove errorneous glib_check_version() in gtk immodule

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2200]
In the gtk2/gtk3 immodule, glib_check_version() is being used to make sure that the installed glib is not older than the glib version which ibus is built with.

https://github.com/ibus/ibus/blob/1bdcf218eeda728391b5b4e33d536d2debfef1bc/client/gtk2/ibusim.c#L44

But I don't see a reason why glib version is checked in runtime. Library compatibility is already being checked more precisely by packaging systems and linkers.

This version check breaks ibus package in Debian testing (http://bugs.debian.org/954207), as ibus was built with glib 2.64.x and the available glib version is 2.62.x which is OK.

Please remove this check.

**Comment by fujiwarat** [comment]
OK, I'm fine to remove glib_check_version().
Could you create a pull request to describe the reason in the patch description?

**Comment by fujiwarat** [comment]
Thank you for the patch.
