### ISSUE TITLE
Move ~/.config/ibus/bus/ to XDG_RUNTIME_DIR ?

### ISSUE THREAD

**Issue by bigon** [ibus/ibus#2204]
Hello,

ibus seems to create files in `~/.config/ibus/bus/` that IMVHO belong to somewhere in `$XDG_RUNTIME_DIR` (`$XDG_RUNTIME_DIR/ibus/bus`?)

The advantage is that files in `$XDG_RUNTIME_DIR` will be automatically cleaned up when the user is closing it's session it will and reduce the risk of leaving stalled files.

Same could apply for the abstract socket created in `~/.cache/ibus/`

Edit: Specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by gunnarhj** [comment]
Did you see #2116? I have the impression that the current folders were selected after careful consideration.

**Comment by bigon** [comment]
I went (really) quickly through and I see the last comment (https://github.com/ibus/ibus/issues/2116#issuecomment-533013752), but I'm not really sure about it:

> Since ibus-daemon can be launched with su or sudo command, I think XDG_RUNTIME_DIR is not useful for ibus.

In which (normal) condition can or is advised to start ibus with `sudo` or `su`?

**Comment by fujiwarat** [comment]
ibus-daemon is a user process and it can be run by multiple users.
XDG_RUNTIME_DIR is set by login user and it does not work with sudo, su and the build environment.

**Comment by bigon** [comment]
Not sure I understand. You mean multiple sessions?

`XDG_RUNTIME_DIR` should be created by the 1st login and destroyed by the last one. So as long as the user is login at least once, the directory should exists. You already create multiple files in the ~/.config/ibus directory, what would prevent you to do the same in `XDG_RUNTIME_DIR`?

Regarding su, sudo, running desktop applications as root is definitely not advised for anybody. In addition to that switching user like that with wayland is not working anymore AFAIK, so the argument is a bit moot.

**Comment by fujiwarat** [comment]
> Not sure I understand. You mean multiple sessions?

No, a user in one session can switch the user ID.

**Comment by fujiwarat** [comment]
Anyway changing the location will lose the back compatibility in Qt5 applications.

**Comment by bigon** [comment]
> > Not sure I understand. You mean multiple sessions?
> 
> No, a user in one session can switch the user ID.

Like said this is not supported with wayland anymore

> Anyway changing the location will lose the back compatibility in Qt5 applications.
OK then
