### ISSUE TITLE
Words on candidate panel are too dark when system is using dark theme

### ISSUE THREAD

**Issue by conraddd** [ibus/ibus#2205]
Which distribution and version?: 
Linux Mint 19.3 Cinnamon

Which desktop environment and version?: 
X-Cinnamon
Cinnamon 4.4.8

Which session type?: 
x11

Which application and version?: 
any application

IBus version?: 
IBus 1.5.17

Issue description:
I am using Chinese quick classic input method. Words on candidate panel are too dark when system is using dark theme. Unselected words are black and background is dark grey which make the words hard to see. I guess background color is alright for dark mode but words should be in light color in contrast.
![Sublime text](https://user-images.githubusercontent.com/22273042/78668698-b2d41280-790d-11ea-9907-534ba807e9d1.png)

![Theme setting](https://user-images.githubusercontent.com/22273042/78668597-83bda100-790d-11ea-9002-6390b94ef70a.png)

Steps to reproduce:
1. Go to theme setting in Linux Mint Cinnamon
2. Select a dark theme

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account?:
yes

**Comment by fujiwarat** [comment]
I think the color is configured by the engine but ibus core does not touch it.
You can check the current engine with `ibus engine` command.

**Comment by mike-fabian** [comment]
mozbugbox’s improvment to add a dark theme is included ibus-table 1.13.0:

https://github.com/mike-fabian/ibus-table/releases/tag/1.13.0

**Comment by fujiwarat** [comment]
I don't think it's good to have the hard-coded settings since IBus does not depends on destro and user can configure various colors.

**Comment by mike-fabian** [comment]
Yes, it would be better to make all the colours configurable, but this dark/light-theme is better than nothing.
