### ISSUE TITLE
Japanese IME fail to work in chromium based browsers

### ISSUE THREAD

**Issue by galtgendo** [ibus/ibus#2206]
Observed initially with Opera, then verified with Chrome - has been happening for months now.

ibus-1.5.20
xorg-server-1.20.7

Local Japanese IME seems to be working with pretty much all other programs.

In chromium based browsers however, even though systray indicator notes IME switch, input fields seem to be ignoring that - not even ascii to kana phase gets initiated.

For me, that would hint at problem lying with the browsers, but I'm hoping for better response time here or at least a hint where the chain breaks.

No particular DE, just a collection of bits and pieces, but dbus-daemon is running (mostly for automount needs).

**Comment by fujiwarat** [comment]
I don't understand your problem. Please use the bug template.
I confirmed ibus-anthy works fine with chrome.
