### ISSUE TITLE
ibus showing icon in trayer but never popup when I type(ibus-libpinyin)

### ISSUE THREAD

**Issue by peigongdsd** [ibus/ibus#2207]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Archlinux, latest
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
xmonad. env XDG_CURRENT_DESKTOP is not defined. I started xmonad with xdm and maybe xdm or xmonad do not set such a env var.
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
x11
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
EVERY APPLICATION
IBus version?: 
(Run `ibus version`)
1.5.22
Issue description:
I'm a Chinese user. Ibus do show up in my system tray with the icon of ibus-libpinyin, but the input table never shows up when I start typing, thus no Chinese character is input. Ths issue comes up with every application so that I doubt that if this problem is not linked with a certain application, but the desktop environment.

Steps to reproduce:
1. I wonder too.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes
Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
krusl@127 ~> ibus-daemon --xim --verbose &

(ibus-ui-gtk3:32427): IBUS-WARNING **: 18:51:22.109: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
krusl@127 ~> 
(ibus-ui-gtk3:32427): IBUS-WARNING **: 18:51:22.220: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
cannot open ../lua/base.lua: 没有那个文件或目录
lua script loaded.
cannot open /home/krusl/.config/ibus/libpinyin/user.lua: 没有那个文件或目录
open /home/krusl/.cache/ibus/libpinyin/user.conf failed.
(ibus-ui-gtk3:32427): Gdk-CRITICAL **: 18:51:22.280: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
@epico
> cannot open /home/krusl/.config/ibus/libpinyin/user.lua: 没有那个文件或目录
Could it be a reason of this issue?

**Comment by epico** [comment]
I think that is just a warning.

@peigongdsd, Could you try other input method like Wubi in ibus-table?

We need to find out whether it affects all input methods or not.

**Comment by fujiwarat** [comment]
@peigongdsd Can you reply @epico 's question above?
