### ISSUE TITLE
Is the emoji list auto generated?

### ISSUE THREAD

**Issue by rodrigograca31** [ibus/ibus#2208]
Hi!

I'm a heavy user of emojis. 
With that said there's multiple emojis that IMHO (In My Humble Opinion) should have alternative words. For example 🗑️ (wastebasket) should also be found when searching "trash".

I know a couple of other ones and the ibus emoji list seems to be missing quite a few of the latest emojis from the spec but that is another conversation... 

**So I was wondering if this list was auto generated or I could simple send contributions (PRs) to this file?**
`data/annotations/en.xml`

https://github.com/ibus/ibus/blob/master/data/annotations/en.xml

I'd like to contribute with a few alternative words and maybe later update the emojis list to include the latest ones...? (Unicode 12.0 as of now)

**Comment by fujiwarat** [comment]
> https://github.com/ibus/ibus/blob/master/data/annotations/en.xml

I'm not sure if your distro uses that file. Currently I recommend to use  [cldr-emoji-annotation](https://github.com/fujiwarat/cldr-emoji-annotation) package or download the files from Unicode CLDR directory.
So you wish to contribute annotations, you could do on Unicode CLDR directly.

IBus already provides the customization. E.g.
```
% gsettings get org.freedesktop.ibus.panel.emoji favorites
% gsettings set org.freedesktop.ibus.panel.emoji favorites "['🗑️']"
% gsettings set org.freedesktop.ibus.panel.emoji favorite-annotations "['trash']"
```

**Comment by rodrigograca31** [comment]
Yeah I'm on Linux Mint 19.3.
And seems this repo doesnt include the skin tone variations and the one you link does so it probably uses that version instead.

but according to their readme its a copy from the original cldr one so I guess I will send contributions to https://github.com/unicode-org/cldr and hopefully one day they reach my OS.... :sweat_smile:
