### ISSUE TITLE
IBus StatusNotifierItem implementation is out of Spec

### ISSUE THREAD

**Issue by colonelpanic8** [ibus/ibus#2210]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
nixos

Which desktop environment and version?: 
None (just a window manager

Which session type?: 
X11

Which application and version?: 

IBus version?: 
1.5.21

Issue description:

The way ibus interacts with status notifier item seems to be out of spec. It does not seem to register with the watcher at all, and simply starts sending signals indicating that a new icon is ready. See https://github.com/taffybar/gtk-sni-tray/issues/22

**Comment by fujiwarat** [comment]
I don't know or remember how o register the icon with the watcher to appindicator.
It would be great if you could provide a patch.

**Comment by NickHu** [comment]
@fujiwarat It seems like the critical code section is in the `init_indicator()` function in `panel.vala`: https://github.com/ibus/ibus/blob/master/ui/gtk3/panel.vala#L273.

A related bug is that indicator support is only enabled if IBus detects that the user is running KDE, which is definitely incorrect - a better approach perhaps what NetworkManager applet does; if you pass it the `--indicator` flag
```
$ nm-applet --indicator
```
it will use the StatusNotifierItem implementation instead of XDG System Tray.

This bug is currently making IBus completely unusable on modern system tray implementations.

**Comment by NickHu** [comment]
@IvanMalison @fujiwarat Having had another brief look, is it not the case that IBus is trying to register with the watcher here: https://github.com/ibus/ibus/blob/master/ui/gtk3/indicator.vala#L189? I may be mistaken, but it might be that the early return from this void function on the line immediately above might be causing this to fail to happen.

**Comment by fujiwarat** [comment]
That implementation was copied from libappindicator.
https://launchpad.net/libappindicator

**Comment by fujiwarat** [comment]
"RegisterStatusNotifierItem" D-Bus method would be needed AFAIR.

**Comment by NickHu** [comment]
@fujiwarat Curious as to why libappindicator isn't simply used (the are Vala bindings in the main repository) instead of copying code from it? That way you wouldn't have to handle the indicator/systray stuff manually

**Comment by fujiwarat** [comment]
ibus-ui-gtk3 is used in other GTK desktops too and I don't wish to link libappindicator

**Comment by IvanMalison** [comment]
It seems like the issue is that ibus is registering on a different dbus address than it is actually serving on afaict.

**Comment by fujiwarat** [comment]
How is the different D-Bus address? Probably I think IBus follows libappindicator's way.
I can review a patch if you have.

**Comment by goatastronaut0212** [comment]
> How is the different D-Bus address? Probably I think IBus follows libappindicator's way. I can review a patch if you have.

I interest in this issue. I will give you a patch if I can but I have no clue what should I do? Can you give me some?

**Comment by fujiwarat** [comment]
I don't think the StatusNotifierItem is out of spec but I think the original issue would be fixed.
