### ISSUE TITLE
Japanese IME fail to work in chromium based browsers

### ISSUE THREAD

**Issue by galtgendo** [ibus/ibus#2212]
Which distribution and version?: 
Gentoo based, so version does not apply.

Which desktop environment and version?: 
none - it's openbox + PCManFm + lxsession

ibus-1.5.20

Observed currently in opera 66.0.3515.72, but confirmed with google-chrome.
Has been valid for months (literally).
Persistent across restarts.

Local Japanese IME seems to be working with pretty much all other programs.

In chromium based browsers however, even though systray indicator notes IME switch (upon pressing the combination to switch input method), input fields seem to be ignoring that - not even ascii to kana phase gets initiated.

(I don't really see what was missing in the first report (and why it was closed *before* clarification was asked for))

IME in question is kkc.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.
Can you show the reproducing steps with detail? Which keys are typed, How do you use mouse click and drag?

**Comment by luongthanhlam** [comment]
In my case, this bug appears when I startx on tty without gdm running. Ibus works well on chromium based apps when I start gdm and login with it.

**Comment by fujiwarat** [comment]
@luongthanhlam I guess your case is not this.

**Comment by galtgendo** [comment]
...OK, I hope you're responding to me, not someone else.

So, more details:
- the activating combination is the default <Super>space
- openbox is set up into "focus follows mouse"
- root account (mentioned because of chromium sandbox) is barren, that is almost no setup was done on it past system installation, so (among other) the envvars are likely not set up there
- xcompmgr is running
- 'dbus-launch --sh-syntax --exit-with-session' is a line in ~/.xsession (as xserver is launched via 'startx')

**Comment by galtgendo** [comment]
...sometimes, I hate markdown...
first line is: "...default Super-space"

**Comment by galtgendo** [comment]
...oh, when I first read luongthanhlam's comment, I thought it was off-topic, but having re-read it, it might be onto something...

**Comment by galtgendo** [comment]
That is to say:
- this is a non-systemd setup, even if both udev and logind originate from systemd
- I login at console, not via any display manager

**Comment by galtgendo** [comment]
...*elogind

**Comment by galtgendo** [comment]
Also I don't get "How do you use mouse click and drag?".
How does drag-and-drop enter into equation here ?
We're talking just about typing.

**Comment by fujiwarat** [comment]
> this is a non-systemd setup, even if both udev and logind originate from systemd

Probably I think the user systemd is needed which can be launched with login PAM.

> I login at console, not via any display manager

What is the result if you log into your session with GDM?

**Comment by galtgendo** [comment]
> What is the result if you log into your session with GDM?
Kind of untestable, as I neither use or have it.

**Comment by galtgendo** [comment]
OK, with that hint I finally figured it out.
It was a configuration error stemming from the old guides not being quite clear.

'dbus-launch --sh-syntax --exit-with-session' is the key point.

What some of the guides don't make quite clear is that if that line is *not* a prefix, it should be evaluated, so that DBUS_SESSION_BUS_ADDRESS gets exported.

fujiwarat: so, this is kind of invalid, though the conclusion should be propagated to the guides.
Yet, I've got a minor, tangentially related request:
  awhile ago I've filed https://github.com/ueno/libkkc/issues/21, but it seem the author has abandoned it; yet this question requires (the way I see it) at most a computer-literate native speaker, so could you answer that ?

**Comment by galtgendo** [comment]
...of course, the question arises: 'why no other apps seems to need this ?', but that's likely just a chromium oddity...

**Comment by galtgendo** [comment]
...OK, as for my request: I've just checked it with fcitx-anthy - the table there looks the same, so it seems it's just my lacking grounding in Japanese that makes me see some of those choices as odd...

Well, you live and learn...at least till you die.

**Comment by galtgendo** [comment]
To sum up some additional info from IRC:
The most likely reason it's so hard to reproduce is pam_systemd.
While it seems that pam_elogind should do about the same, it matters only if your pam configuration included it - mine didn't and somehow I don't think most elogind migration docs include a section on pam config; mine was done mostly for non-suid xserver.
You might get hit by this problem if you're still using startx with a custom .xsession and don't have  pam_elogind entry (if you're using that instead of full systemd).

**Comment by fujiwarat** [comment]
> Kind of untestable, as I neither use or have it.

I mean IBus works with a login manager. You could try GDM, lightDM, or anything else and compare the difference between your environment and other.
