### ISSUE TITLE
problem in kubuntu 20.04 and ibus 1.5.22

### ISSUE THREAD

**Issue by mehedeetalha** [ibus/ibus#2213]
Please fill in the following items if you don't know the root cause.

Which distribution and version?:  Kubuntu 20.04

Which desktop environment and version?:  KDE plasma 5.18.4

Which session type?: X11

Which application and version?:  In all app

IBus version?: 1.5.22

Issue description: when type ctrl+shift+e there is no emoji option opened. but in the screen there is "e" and it can not be deleted before restart of ibus

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
"e" is an Emoji prompt and you can type any Emoji annotations and space key.
I tried Plasma 5.18.4 in Fedora 32 and The IBus Emoji function works fine.

**Comment by mehedeetalha** [comment]
May be it is Debian problem. I faced same problem in Ubuntu, Kali linux

**Comment by fujiwarat** [comment]
Did you try my suggestion?
