### ISSUE TITLE
Unable to change candidates orientation to horizontal in GNOME

### ISSUE THREAD

**Issue by pCloudsp** [ibus/ibus#2215]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Arch Linux x86_64, 5.6.6-arch1
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: GNOME 3.36.1
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: Wayland
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: all applications
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: ibus 1.5.22
(Run `ibus version`)

Issue description:
With ibus-rime, the candidates orientation cannot be changed, both by ibus-setup and by `gsettings set org.freedesktop.ibus.panel lookup-table-orientation 0`

Steps to reproduce:
1. change candidates orientation using ibus-setup or editing dconf
2. type something

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
GNOME does not use the configuration in ibus-setup and there is no global setting of the orientation in GNOME.

Currently some input methods have the setting in the owned setting tool.
E.g. you can configure the orientation with the setting of ibus-libpinyin; /usr/lib*/*/ibus-setup-libpinyin
