### ISSUE TITLE
Switching from Ukrainian (or any other language with non-Latin character set) input to Japanese input with IBus seems broken

### ISSUE THREAD

**Issue by frp** [ibus/ibus#2216]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 31

Which desktop environment and version?: 
Reproduces in all of them (Gnome, KDE, i3, I use i3, but tested in all)

Which session type?: 
X11

Which application and version?: 
All of them. Let's say gedit 3.34.1, firefox 73.0.1 and so on.

IBus version?: 
1.5.21

Issue description:

If you switch from Ukrainian (or any other non-Latin) input to KKC (or any other Japanese IME, tested with Mozc), and try to type, the result produced is Ukrainian. Workaround is switching to English input first and then switching to Japanese.

Steps to reproduce:

1. Configure input methods as follows:
    * US English
    * Ukrainian
    * Japanese (reproducible with both Kana Kanji and Mozc)
1. Switch to Ukrainian.
1. Type some letters.
1. Switch to Japanese, try typing.
1. You get Cyrillic Ukrainian letters that obviously can't be converted to Japanese.
1. Switch to US English.
1. Switch to Japanese again.
1. Now everything works.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

Yes

**Comment by fujiwarat** [comment]
Some input method engines do not have keymaps because it works with US, US(drovak), JP and etc.
Your result is expected and IME inherits the previous layout.

If you desire to set the configuration of keymaps of IMEs, you could ask each IME. E.g. ibus-anthy has the setting of the keymap.

**Comment by frp** [comment]
Thank you, I set keymap in the IME config and now it works the way I want. Logically IBus working the way it does makes sense, but in Windows (and FCITX as well) this works "as expected by the user" out of the box => might still be worth improving, though I don't have a good specific proposal.
