### ISSUE TITLE
IBus on Qt5 and on non-GTK Flatpak - cannot switch "simple" layouts in program; cannot use "complex" at all

### ISSUE THREAD

**Issue by J-J-Chiarella** [ibus/ibus#2220]
Hello.

I am encountering issues with IBus being broken in Qt5 applications. I have tried exporting all that to my config files, export=..., all that. Apparently, some problems were supposedly fixed upstream and some things to do with glib, but I have seen no improvement. I know that everyone needs to prepare for the SNI switch (dropping xembed icons) and preparations for wayland, and I appreciate any attention that any developer can contribute to this issue. I am sure that there are several Asian-language users (outside of China where fcitx is somehow popular) who will experience issues when they upgrade their OSes now or in the near future.

Which distribution and version?
Xubuntu 20.04

Which desktop environment and version?
Xfce 4.14.0 and 4.14.1 parts

Which session type?
X11

Which application and version?
Any Qt5 application (Qt 5.12.8) or Flatpak (Flatpak 1.6.3)
glib 2.64.2
dbus 1.2.16

IBus version?
1.5.22

Issue description:
IBus will not properly switch layouts in a Qt5 or Flatpak window. One must use a workaround with some typing in a non-Qt window in order to get the change to take place. You must do this every time you want to switch IBus input methods. Additionally, IBus will absolutely not work at all in Qt5 or Flatpak windows with complex input methods such as ibus-hangul.

Steps to reproduce:
1. Run any Qt5 or Flatpak application
2. Switch input method for IBus. Visual popup indicates the change, but the typing in the Qt5 window will continue to produce characters as if in previous input method.
<workaround> . . .
3. Move to a GTK window or Firefox, etc.
4. Switch IBus input method (because the switch did not remain) to a "simple" IBus layout that remaps input: e.g., Dvorak, French.
5. Type. Notice that the characters that appear in the GTK window are what you expect for the currently selected input method for IBus.
6. Return to the Qt5 window and type. Notice that the characters are now what you expect for the currently selected input method for IBus.
. . . </workaround>
7. Try to change input method within the Qt5 window. Notice that the same problem happens, i.e., the previous input method continues on despite no longer indicated by that icon in the notification area.
8. Try to repeat the workaround for a complex input method such as Korean-Hangul (ibus-hangul). The workaround does not help at all. The only way to get those characters into a Qt5 or Flatpak window is to type them out in another program (GTK) and then copy-paste the text into the Qt5 window.

Can you reproduce your problem when you restart ibus-daemon?
Yes

Do you see any errors when you run ibus-daemon with the verbose option?
No

Can you reproduce your problem with a new user account instead of the current your account?
Yes

Addendum: The one thing that could possibly be an issue is the LTS version of Qt5 on Ubuntu (5.12.8). I would appreciate anyone with superior know-how  being able to test the same conditions I have described, but with a later upstream version of Qt5.

**Comment by fujiwarat** [comment]
Is QT_IM_MODULE=ibus environment variable available in your XFCE desktop?

Can you get the output of `strace kwrite |& inputcontexts` ?

**Comment by J-J-Chiarella** [comment]
> Is QT_IM_MODULE=ibus environment variable available in your XFCE desktop?
My ~/.bashrc has the following at the end:
`export GTK_IM_MODULE=ibus`
`export XMODIFIERS=@im=ibus`
`export QT_IM_MODULE=ibus`

> Can you get the output of strace kwrite |& inputcontexts ?
No, because I do not have kwrite installed. I tried it and yeah, nothing. If I install kwrite, then I get `inputcontexts: command not found`. I haven't used strace before (or know what it is) and when I run `strace kwrite` (without `|& input contexts`), then I get hundreds of lines of texts, if not thousands.

**Comment by fujiwarat** [comment]
> inputcontexts: command not found

Sorry, I revised the command line in my previous comment. Please try it again.

**Comment by J-J-Chiarella** [comment]
No problem.

I tried with KWrite and the same Qt problem persists. I'm not sure what KWrite has to do with this, but running your command `strace kwrite |& grep inputcontexts` gives the following output (see the bottom) and opens an instance of KWrite wherein IBus works strangely.

At first, IBus appears to work in the KWrite window opened with `strace kwrite |& grep inputcontexts` (and only with that command to launch as far as I can see -- the workaround is temporary). I can type hangul, do Hanja, cycle input methods ...

... but ...

The backspace key now registers a full-width opening/leftt parenthesis for IBus-hangul. Other quirks include: Left arrow yields a full-width lowercase `q`. The other direction arrows yield full-width lowercase `r`, `s`, `t`. The numpad yields half-width katakana, singly or in clusters, or isolated hangul jamo. In numlock mode, the .0-9 produce jamo. The ESCAPE key switches IBus-hangul into Latin( "English") mode and the backspace, arrow keys and numpad resume normal function. These phenomena only affect the KWrite window launched via the command `strace kwrite |& grep inputcontexts`.

Output of `strace kwrite |& grep inputcontexts`:

`access("/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/.", F_OK) = 0`

`openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts", O_RDONLY|O_NONBLOCK|O_CLOEXEC|O_DIRECTORY) = 9`

`lstat("/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0`

`lstat("/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", {st_mode=S_IFREG|0644, st_size=52272, ...}) = 0`

`openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 9`

`lstat("/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0`

`lstat("/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", {st_mode=S_IFREG|0644, st_size=127080, ...}) = 0`

`openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 9`

`access("/usr/bin/platforminputcontexts/.", F_OK) = -1 ENOENT (No such file or directory)`

`openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so.avx2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)`

`access("/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so.avx2", F_OK) = -1 ENOENT (No such file or directory)`

`openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libibusplatforminputcontextplugin.so", O_RDONLY|O_CLOEXEC) = 9`

**Comment by J-J-Chiarella** [comment]
If it matters (?) KDE programs seem to exhibit the same behavior as regular Qt apps and any Flatpak.

**Comment by fujiwarat** [comment]
> I can type hangul, do Hanja, cycle input methods ...

So I think you didn't set QT_IM_MODULE After setting it, you can use kwrite.

Now you report another issue.

> The backspace key now registers a full-width opening/left parenthesis for IBus-hangul. Other quirks include: Left arrow yields a full-width lowercase q. 

Probably I think your qtbase version is low and the following fix is needed:
https://code.qt.io/cgit/qt/qtbase.git/commit/?id=9b6222598c990512c78bd42f55d7d6dc635c8b48

**Comment by J-J-Chiarella** [comment]
Thank you for your help, but I think there may be some miscommunication and I apologize if I haven't been precise enough.

> So I think you didn't set QT_IM_MODULE After setting it, you can use kwrite.

This seems to be incorrect. I already had `export QT_IM_MODULE=ibus` set on my `.bashrc`. The command you suggested will make ibus work woth Qt *only if I launch that application via `strace [program name] |& grep inputcontexts `*. If I close that window that was created by launching kwrite via that command and try to launch that program in the normal way, then ibus ceases to work, even though I already have set `export QT_IM_MODULES=ibus` for the general environment.

Is there any way to make the fix you suggested -- is there any way to make the effect of running `strace [program that uses Qt5] |& grep inputcontexts` be permanent and universal to all Qt5-using programs, even when launched via other methods (launched automatically when opening files whose mime-types are associated with a program that uses Qt5)?

Thank you for your help and great work on iBus. Besides this issue, it's far better than the alternatives on *nix or even Windows.

**Comment by gunnarhj** [comment]
> My ~/.bashrc has the following at the end:
> ```
> export GTK_IM_MODULE=ibus
> export XMODIFIERS=@im=ibus
> export QT_IM_MODULE=ibus
> ```
`~/.bashrc` is not a proper place to set those variables, since it won't make them available in all graphical applications. Try `~/.profile` instead. (Or install `im-config`, if not installed already, and let that package handle the IM configuration.)

**Comment by J-J-Chiarella** [comment]
The `~/.profile` worked. (I already had `im-config` installed.) Thank you, @gunnarhj! 

The remaining issue is something I can live with, that I cannot use arrow keys (or Insert or Backspace or Home, End, PgUp, PgDn, or Caps Lock) as these insert full-width characters for some reason and Delete doe snot do anything. I can switch in Latin mode or another layout for that. I guess I will just wait until Debian (and then Ubuntu) gets the next Qt5 LTS in, Qt 5.15, to see if that fixes things. (Qt 5.12 did not incorporate @fujiwarat's [commit](https://code.qt.io/cgit/qt/qtbase.git/commit/?id=9b6222598c990512c78bd42f55d7d6dc635c8b48) and the next upstream Qt after March 2019 I would get would be 5.15.)

I'm just glad this makes my Qt applications mostly usable again. I was worried with the initial mention of KWrite that I would need to adopt KDE and abandon XFCE.

**Comment by fujiwarat** [comment]
> The ~/.profile worked. (I already had im-config installed.) 

And then your im-config would have a problem.
You could check the current environment variables with `env` command if im-config would export QT_IM_MODULE=ibus correctly.

**Comment by gunnarhj** [comment]
> And then your im-config would have a problem.

Not necessarily... `im-config` defaults to "none" on Xubuntu unless `LC_CTYPE` is a CJKV locale.

A better advice from me would have been: Open _Language Support_ and select "IBus" as the "Keyboard input method system". (Language Support is an Ubuntu tool with a simple UI to the im-config user settings.)
