### ISSUE TITLE
Hide UI for switching input source shortcut

### ISSUE THREAD

**Issue by gunnarhj** [ibus/ibus#2222]
If I start `ibus-setup`, the first thing I see is an interface for controlling the shortcut for switching to next input source. It's `<Super>space` by default, but I can change it to e.g. `<Control>space`:

    $ gsettings get org.freedesktop.ibus.general.hotkey triggers
    ['<Control>space']

However, if I am on a GNOME desktop (which I usually am), the dconf value which is controlled via Settings is unaffected:

    $ gsettings get org.gnome.desktop.wm.keybindings switch-input-source
    ['<Super>space', 'XF86Keyboard']

And `<Super>space` is still the working shortcut for switching source; `<Control>space` does not do anything as far as I can see.

This is not ideal, and may cause confusion.

This problem, i.e. that the shortcut set via IBus is overridden by the desktop's shortcut, is present on Unity too. A few years ago a patch was written for Ubuntu which hides that `ibus-setup` UI component on Unity. I [attached the patch](https://github.com/ibus/ibus/files/4566437/ubuntu-disable-trigger.patch.gz) to this issue even if it's obsolete today.

I will submit a PR which addresses the issue using the same approach as that old patch, and which is effective on both GNOME and Unity.

**Comment by fujiwarat** [comment]
Fedora simply adds "NoDisplay=true" in org.freedesktop.IBus.Setup.desktop not to confuse people in GNOME.

**Comment by gunnarhj** [comment]
So does Ubuntu for GNOME and Unity desktops. But people still find out about `ibus-setup` via various forums and tutorials out there, and quite a few of them get confused. I'm pretty sure that's true for some Fedora users too.

Do you think it's unnecessary?

My thought when seeing the old patch was: "good idea, but if anywhere this should be done upstream". When I had submitted the PR it struck me that more components ought to be hidden, not least the tab for setting input method. So, if you don't dislike the idea too much, we might want to have a `setup-gnome.ui` instead of the `setup-no_switch_shortcut.ui` I proposed.

Personally I think that would make sense. Hiding the icon is good but not sufficient in many cases.

**Comment by fujiwarat** [comment]
> Do you think it's unnecessary?

I think GNOME and Unity should provides the document to run gnome-control-center or else.
If some users don't read the document, we could inform them then.
I think your patch would be complicated a little while I think we could just inform of the setting.

Even if you hide the setting, I think the users could confuse to find where is the real setting.

On the other hand, I think some users would like to run ibus-setup in GNOME to configure other environments likes ibus-fbterm frame buffer environment.

**Comment by gunnarhj** [comment]
> I think GNOME and Unity should provides the document to run gnome-control-center or else.
If some users don't read the document, we could inform them then.

That's easier said than done in the Linux world...

But if I can't sell the idea to you, let's simply drop it. Carrying it as a downstream patch would be cumbersome and differences between distros would add to the confusion. We don't need that.

Please feel free to close this issue and the related PR if you consider the conversation to be ended.

**Comment by fujiwarat** [comment]
Probably I think a warning dialog would be better than maintaining two setup.ui.

**Comment by gunnarhj** [comment]
> Probably I think a warning dialog would be better than maintaining two setup.ui.

Maybe. Such a dialog would indeed be an improvement.
