### ISSUE TITLE
Korean (Hangul) words are incorrectly broken in facebook, twitter web sites with Chrome

### ISSUE THREAD

**Issue by realgsong** [ibus/ibus#2226]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Ubuntu 20.04 LTS

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 3.36

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Google Chrome 80.0.3987.132

IBus version?: 
(Run `ibus version`)
IBus 1.5.22

Issue description:
Korean(Hangul) word is typed as broken in Twitter, Facebook and any sites using draft.js

Steps to reproduce:
1. Run Google Chrome
1. open twitter.com
1. Type '안녕하세요'  Use Korean Input mode in ibus and type  dkssudgktpdy keys in order.
1. '안ㅕ하요' is typed in twitter message.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by changwoo** [comment]
It looks like a browser (and/or the websites) issue. If the website Javascript code modifies an input entry which have a preedit text without considering it, input will break and there's nothing ibus can do about it.

**Comment by fujiwarat** [comment]
I think this is a chrome issue. I don't see the same issue in firefox.
When "s" is typed after "dks", ibus-hangul commits "안", receives focus-out events from chrome and reset the preedit of "ㄴ".
