### ISSUE TITLE
Emoji wrong position when select

### ISSUE THREAD

**Issue by Paderman** [ibus/ibus#2228]
Emoji wrong position when select.

Kubuntu 20.04 with current KDE
IBus 1.5.22

When I select an Emoji, I get another icon that I don't selected.
Example: If I want a simple smile, I get another emoji and I must search for the correctly emoji that I want. If I change the size of window, the order is moved to another position

If necessary: used language is German

PS: it would be nice when a picked emoji can via click inserted in a text field (like Windows) instead via copy & paste.

Thank you.

**Comment by fujiwarat** [comment]
> When I select an Emoji, I get another icon that I don't selected.

How do you select an Emoji? Can you describe your issue by step as the bug template suggests?

Also can you attach the screenshots to explan your issue? I think Print key can take the screenshot in KDE.

> PS: it would be nice when a picked emoji can via click inserted in a text field (like Windows) instead via copy & paste.

You could see the man page of ibus-emoji(5) which explains Ctrl-Shift-c can copy the selected emoji.

**Comment by Paderman** [comment]
I use currently _KCharSelect_ and it hasn't this bug...
Please watch my little demonstrations video on https://youtu.be/n_58Q4VSY0s
Sorry, it's in German, but you can see if I want a emoji 'Cool' and I get other emoji... This is reproducible

**Comment by fujiwarat** [comment]
> https://youtu.be/n_58Q4VSY0s

It's not IBus.

**Comment by Paderman** [comment]
I don't know, but it seems be fixed now :1st_place_medal:
