### ISSUE TITLE
Request to freeze cangjie candidate order

### ISSUE THREAD

**Issue by hulloanson** [ibus/ibus#2229]
Which distribution and version?: 
Ubuntu 20.04

Which desktop environment and version?: 
GNOME 3.36.2

Which session type?: 
X11

Which application and version?: 
Irrelevant to the issue

IBus version?: 
IBus 1.5.22 (ibus-table-cangjie5 and ibus-table-cangjie3)

Issue description:
Experiened cangjie users remember character order as their candidate list is often short (2-3 characters mostly). It would be great to add a toggle to disable ordering candidates with input frequencies.

Example: inputting 有 / 冇
Usually cangjie users expect 有 to be always at position 1 and 冇 to be always at position 2. After a few inputs of 冇 however, it moves to position 1. Cangjie users reflexively pressing "2" would find themselves inputting 有 instead, impeding typing flow as they have to 1) delete the character; 2) type the code and look carefully at the candidate list for the position; 3) type the desired number. The process could take quite a few seconds.

This issue applies to other code combination that produces more than 1 candidate too.
Steps to reproduce:
1. typing "大月" produces a list of:
![0](https://user-images.githubusercontent.com/9977536/83716713-3cc8ff00-a663-11ea-9bab-4d5b026e0ab8.png)

1. Press "2" to select 冇 for a few times
1. It moves to the top of the list:
![1](https://user-images.githubusercontent.com/9977536/83716720-418db300-a663-11ea-8e70-bc0e14e941d8.png)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

Edit: smaller images

**Comment by hulloanson** [comment]
My bad. I should have just choose Cangjie Big instead of Cangjie 3 and 5. It is still my opinion that cangjie 3 and 5 have the `DYNAMIC_ADJUST` parameter set to `FALSE` though.

I have submitted a pull request here:
https://github.com/definite/ibus-table-chinese/pull/14

**Comment by mike-fabian** [comment]
Thank you very much ☺! Your pull request has been merged there.

**Comment by mike-fabian** [comment]
I will  probably add an option to choose this at runtime as well:

https://github.com/mike-fabian/ibus-table/issues/70
