### ISSUE TITLE
[ibus mozc feature request] option to set default input mode or remember last used one

### ISSUE THREAD

**Issue by iDarkTemplar** [ibus/ibus#2230]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Gentoo Linux amd64
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: KDE5 Plasma 5.18.5, Qt 5.14.2
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: X11
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: any. for example, kate 19.12.3 and konsole 19.12.3
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.22
(Run `ibus version`)

Issue description:
When switching to mozc input method, selected input mode of mozc is "direct", i.e. basically I continue to type plain english text. I want to write, for example, hiragana right after switching to mozc. For that I need to manually switch to "hiragana" input mode once per session, i.e. first time before using ibus+mozc for japanese input after each login or after manual ibus daemon restart. It'd be helpful if ibus would remember last selected input mode for mozc or it could be configured.

If this feature request should be made directly at mozc instead of ibus, please let me know.

Steps to reproduce:
1. Add and enable mozc input method if it's missing
2. Select mozc input method
3. Select input mode "hiragana" (or any other non-default one)
4. type some text in kanji.
5. restart ibus. logout and login back should work too.
6. select mozc input method
7. try typing
8. instead of "hiragana" selected previously, result is english text, until "hiragana" (or any other non-default input mode) is selected again.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

(ibus-extension-gtk3:26581): IBUS-WARNING **: 21:58:00.200: panelbinding.vala:246: Checking Wayland is disabled
(ibus-ui-gtk3:26579): Gtk-WARNING **: 21:58:08.794: no trigger event for menu popup
(ibus-ui-gtk3:26579): Gtk-WARNING **: 21:58:12.537: no trigger event for menu popup

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): It's fresh/first ibus install, so I didn't test this on another user account.

**Comment by fujiwarat** [comment]
Probably I don't need the feature.
I checked Notepad always resets the typing mode in MS-Windows 10.

**Comment by iDarkTemplar** [comment]
And that's why I suggested to implement it as an option: if you don't need it, just keep it default and it'd work as it currently does. When I need it, or someone else does, there's no need to patch source code and recompile ibus, ibus behaviour can be changed runtime. There's literally non-existent downside for end user.

And I don't think it is a good idea to use lack of features in MS-Windows as a reference.

**Comment by fujiwarat** [comment]
Sorry, I think the typing mode should be reset with restarting ibus and I even not agree with the option.
But your request can be implemented in each engine; mozc but not ibus core.
