### ISSUE TITLE
IBus fails to switch to Russian on FreeBSD

### ISSUE THREAD

**Issue by yurivict** [ibus/ibus#2232]
Installed packages:
```
ibus-1.5.22                    Intelligent Input Bus for Linux / Unix OS
ibus-m17n-1.4.3                m17n IM engine for IBus framework
ibus-table-1.9.25              Table-based input method framework for IBus
ibus-typing-booster-2.9.1      Faster typing by context sensitive completion
ibus-uniemoji-0.6.0.16         Input method for entering unicode symbols and emoji by name
zh-ibus-pinyin-1.5.0_9         PinYin engine for IBus
```

Mandarin works, but Russian through ```ibus-table``` doesn't work.

FreeBSD 12.1

**Comment by mike-fabian** [comment]
What do you mean by "doesn’t work̈? Which table are you trying to use? What exactly doesn’t work?

**Comment by yurivict** [comment]
When ```ibus-table``` is installed a number of new choices for languages appear. ```Russian``` is one of the choices. Russian is made available through the IBus menu, but when switched to Russian the keyboard still enters Latin characters.

**Comment by mike-fabian** [comment]
![Screenshot](https://user-images.githubusercontent.com/2330175/85689995-6b228300-b6d3-11ea-98ff-7135d333eb01.png)

**Comment by mike-fabian** [comment]
You may also want to add a Russian dictionary in ibus-typing-booster if you want to use Russian. You can also do this in the "Dictionaries and input methods" tab.

**Comment by yurivict** [comment]
The choices for me look like this: 
![image](https://user-images.githubusercontent.com/271906/85710019-af456180-b69a-11ea-8c2e-eaa73e7d59ad.png)

I choose the ```Russian``` option to emulate the Russian keyboard like this: 
![image](https://user-images.githubusercontent.com/271906/85710143-ce43f380-b69a-11ea-981f-5e984e39cb90.png)

It used to work but then stopped working after some packages update.

**Comment by mike-fabian** [comment]
In your screenshot, the three items which have "(m17n)" are from ibus-m17n, not from ibus-table.
These should work as well and I would like to know why it fails for you. 

Although I would still suggest to use them with ibus-typing-booster instead.

ibus-typing-booster supports everything ibus-m17n does and lots of extras. If one does not need all 
the extras ibus-typing-booster supports, one could switch them off.

http://mike-fabian.github.io/ibus-typing-booster/documentation.html#simulate-ibus-m17n

**Comment by mike-fabian** [comment]
The first two items in your screenshot, "Russian" and "Russian (phonetic)" are both keyboard layouts, they
are not from ibus-table, ibus-m17n, or ibus-typing-booster either, just keyboard layouts.

They should work as well.

**Comment by yurivict** [comment]
Yes, Russian keyboard layout doesn't work in IBus. A->"ф"

**Comment by mike-fabian** [comment]
> Yes, Russian keyboard layout doesn't work in IBus. A->"ф"

I cannot reproduce that, it works fine for me on Fedora 32. I tested in Gnome and Xfce.
