### ISSUE TITLE
Please support unicode-math shortcut for latex mode

### ISSUE THREAD

**Issue by bastien-roucaries** [ibus/ibus#2233]
Hi,

Could you support the unicode math symbols documented here in latex mode [1] ?

I could do a pull request if you indicate where to add the list 

[1] http://mirrors.standaloneinstaller.com/ctan/macros/latex/contrib/unicode-math/unimath-symbols.pdf

**Comment by bastien-roucaries** [comment]
List here could be processed by latex command to get any format
https://github.com/wspr/unicode-math/blob/master/unicode-math-table.tex

**Comment by mike-fabian** [comment]
I think the most useful way to to that would be to add them here:

http://git.savannah.gnu.org/cgit/m17n/m17n-db.git/tree/MIM/math-latex.mim

math-latex.mim can be used with ibus-m17n and with ibus-typing-booster.

You can also make a pull request to this table, if you want to use it with ibus-table:

https://github.com/mike-fabian/ibus-table-others/blob/master/tables/latex.txt

(You can of course update both of these files, if you have time).

Using it math-latex.mim with ibus-typing-booster is the most convenient way of using the latex symbols, I think.

**Comment by mike-fabian** [comment]
There is a related pull request here now: https://github.com/moebiuscurve/ibus-table-others/pull/22

**Comment by fujiwarat** [comment]
This would be an ibus-table-other issue.
