### ISSUE TITLE
ibus hangs when pressing Backspace or Supr in wxGUI application on Linux Mint 19.3 MATE, but not if I exit ibus before

### ISSUE THREAD

**Issue by ferdymercury** [ibus/ibus#2235]
Which distribution and version?: 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"

Linux mountain 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

System:    Host: mountain Kernel: 4.15.0-109-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 Desktop: MATE 1.22.2 
           Distro: Linux Mint 19.3 Tricia base: Ubuntu 18.04 bionic 
Machine:   Type: Laptop System: Notebook product: W650SZ v: N/A serial: <filter> 
           Mobo: Notebook model: W650SZ serial: <filter> BIOS: American Megatrends v: 1.00.04 date: 07/09/2013 
Battery:   ID-1: BAT0 charge: 43.1 Wh condition: 43.1/62.2 Wh (69%) model: Notebook BAT status: Full 
CPU:       Topology: Quad Core model: Intel Core i7-4800MQ bits: 64 type: MT MCP arch: Haswell rev: 3 L2 cache: 6144 KiB 
           flags: lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 43099 
           Speed: 2148 MHz min/max: 800/3700 MHz Core speeds (MHz): 1: 2318 2: 2291 3: 2282 4: 2311 5: 1979 6: 2256 7: 2356 
           8: 1904 
Graphics:  Device-1: Intel 4th Gen Core Processor Integrated Graphics vendor: CLEVO/KAPOK driver: i915 v: kernel 
           bus ID: 00:02.0 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel Haswell Mobile v: 4.5 Mesa 19.2.8 direct render: Yes 
Audio:     Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor HD Audio vendor: CLEVO/KAPOK driver: snd_hda_intel v: kernel 
           bus ID: 00:03.0 
           Device-2: Intel 8 Series/C220 Series High Definition Audio vendor: CLEVO/KAPOK driver: snd_hda_intel v: kernel 
           bus ID: 00:1b.0 
           Sound Server: ALSA v: k4.15.0-109-generic 
Network:   Device-1: Intel Wireless 7260 driver: iwlwifi v: kernel port: f040 bus ID: 03:00.0 
           IF: wlp3s0 state: up mac: <filter> 
           Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: CLEVO/KAPOK driver: r8169 v: 2.3LK-NAPI 
           port: e000 bus ID: 04:00.2 
           IF: enp4s0f2 state: down mac: <filter> 
Drives:    Local Storage: total: 817.88 GiB used: 1.09 TiB (136.3%) 
           ID-1: /dev/sda vendor: Toshiba model: THNSNH128GMCT size: 119.24 GiB 
           ID-2: /dev/sdb vendor: Western Digital model: WD7500BPKT-75PK4T0 size: 698.64 GiB 
Partition: ID-1: / size: 116.87 GiB used: 46.05 GiB (39.4%) fs: ext4 dev: /dev/sda1 
           ID-2: /home size: 678.38 GiB used: 531.96 GiB (78.4%) fs: ext4 dev: /dev/sdb1 
           ID-3: /var size: 9.10 GiB used: 4.41 GiB (48.5%) fs: ext4 dev: /dev/sdb5 
Sensors:   System Temperatures: cpu: 55.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Info:      Processes: 254 Uptime: 19m Memory: 15.59 GiB used: 2.02 GiB (13.0%) Init: systemd runlevel: 5 Compilers: gcc: 7.5.0 
           Shell: bash v: 4.4.20 inxi: 3.0.32 

Which session type?: 
X11

Which application and version?: 
KiCad 5.1.6

IBus version?: 
IBus 1.5.17

Issue description:
IBus hangs for ten or twenty seconds after pressing backspace or supr on KiCad, which relies on wxWidgets and GTK3.

![image](https://user-images.githubusercontent.com/10653970/86964932-ca04e500-c134-11ea-8bd0-944ff23c9cde.png)

See related report: https://gitlab.com/kicad/code/kicad/-/issues/4547#note_357429600

Steps to reproduce:
1. Use Linux Mint 19.3 MATE
1. Download the free KiCad application
1. Start it.
1. Run htop on parallel, and mark it as 'always on top'
1. Go to Preferences, Configure paths
1. Edit one of the paths and press backspace. Freeze for 20 seconds.
1. Finally, char is removed and one can continue normally

Can you reproduce your problem when you restart ibus-daemon? (yes / no): Yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
I see this 'before' the problem, not 'during':
_(ibus-ui-gtk3:21360): IBUS-WARNING **: 22:05:57.589: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine._

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
No

This is very surprising to me. With a fresh 'guest account', it does not happen. What is messing up? So weird... Can I clear the cache somehow???

**Comment by ferdymercury** [comment]
Ok, funny enough. If I do not use a guest account, but create a new 'full rights' account, it hangs again! So maybe the guest account has no ibus and that's why it does not freeze?

**Comment by ferdymercury** [comment]
Indeed, calling `ps aux | grep ibus` returns nothing on the guest account, whereas in a normal account, it returns
ibus-dconf, ibus-ui-gtk3, ibus-x11 --kill-daemon, ibus-portal, ibus-engine-simple

**Comment by ferdymercury** [comment]
In my normal account, if I call `ibus exit` and then start KiCad, no freeze happens.

**Comment by ferdymercury** [comment]
Ok, I solved it by doing:
`sudo apt install ibus-gtk ibus-gtk3
`and then restarting.
Now it does not freeze even with ibus on. Credit goes to https://forum.kicad.info/t/backspace-left-right-keys-not-working/8553/13

**Comment by fujiwarat** [comment]
Interesting. You mean the application could hang up if the IBus GTK module is not installed.
But I think it also should not happen. If the module is not found, GTK simply can disable IBus. I guess your GTK has a problem or you might set XMODIFIERS environment variable.

**Comment by ferdymercury** [comment]
Thanks for the reply!
Well, it does not really hang the application. It just takes 30 seconds to erase one character when I hit backspace. Everything works more or less well, just superslow.
And it is confusing because there is the ibus-ui-gtk3 installed, so one would expect this to be enough. But not, one needs additionally ibus-gtk ibus-gtk3
In any case, it looks easier to install these extra modules than to set extra environment variables.
