### ISSUE TITLE
Unable to use dead keys in Java apps (á, é, í, ö, ü, cedilla, etc.)

### ISSUE THREAD

**Issue by dennismayr** [ibus/ibus#2237]
Which distribution and version?: 
_Ubuntu 18.04_ / _elementary OS 5.1.6_

Which desktop environment and version?: 
_Pantheon_

Which session type?: 
_X11_

Which application and version?: 
_IntelliJ IDEA 2020, Android Studio 4.0_

IBus version?: 
_1.5.17_

Issue description:
Unable to use dead keys in Java apps (á, é, í, ö, ü, cedilla, etc.)
The workaround is the same, define XMODIFIERS='' before launching the app._

Steps to reproduce:
1. Fresh _Ubuntu 18.04 / elementary OS 5.1.6_  install.
2. Install `default-jre`
3. Download lastest _IntelliJ IDEA 2020_ and _Android Studio 4.0_
4. Edit a file in _IntelliJ IDEA 2020_ / _Android Studio 4.0_, you can't insert characters like _á_, _é_, etc.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
_yes_

Do you see any errors when you run ibus-daemon with the verbose option?:
_no_

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
_yes_

Additional information:
- JetBrains ticket: https://youtrack.jetbrains.com/issue/IDEA-59679
- Launchpad ticket: https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1863080

**Comment by fujiwarat** [comment]
I can type compose keys with the latest IntelliJ and IBus 1.5.22 in Fedora 22.

> you can't insert characters like á, é, etc.

Did you set compose or dead keys? You could check `xev` command.
