### ISSUE TITLE
When starting dota-2 in wayland mode, ibus input method cannot be used, xorg can be used

### ISSUE THREAD

**Issue by yueduz** [ibus/ibus#2239]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Archlinxuu

Which desktop environment and version?: 
 GNOME 3.36.4

Which session type?: 
Wayland

Which application and version?: 
steam doat-2

IBus version?: 
IBus 1.5.22

Issue description:

When starting dota-2 in wayland mode, ibus input method cannot be used, xorg can be used

在wayland模式启动 dota 2 不能使用ibus输入法，xorg则可以使用

**Comment by fujiwarat** [comment]
Running dota-2 with steam, seems steam open libSDL2.so and SDL2 connect to IBus directly.

```
% strings $HOME/.local/share/Steam/ubuntu12_32/libSDL2-2.0.so.0 | grep -i ibus
@im=ibus
IBUS_ADDRESS
type='signal',interface='org.freedesktop.IBus.InputContext'
```

https://github.com/libsdl-org/SDL/blob/main/src/core/linux/SDL_ime.c#L47
https://github.com/libsdl-org/SDL/blob/main/src/core/linux/SDL_ibus.c#L316

You have to export `XMODIFIERS=@im=ibus` before you run your browser likes firefox and steam in Wayland besides Xorg.

I also noticed SDL does not implement preedit text in SDL_ibus.
