### ISSUE TITLE
Using ibus with Telegram Desktop

### ISSUE THREAD

**Issue by Qwerty-Space** [ibus/ibus#2243]
### Which distribution and version?: 
`Arch Linux 5.8rc6-1`

### Which desktop environment and version?: 
Herbstluftwm

### Which session type?: 
X11

### Which application and version?: 
`Telegram-desktop 2.1.13`

### IBus version?: 
`IBus 1.5.22`

### Issue description:
Can't switch to Japanese input in telegram-desktop.  If I switch prior to opening Telegram, it will not input in Japanese

### Steps to reproduce:
1. Set Japanese input
1. Type

### Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

### Do you see any errors when you run ibus-daemon with the verbose option?:
Nothing related to my issue
```[samurai ~] ibus-daemon --xim --verbose  

(ibus-ui-gtk3:25352): IBUS-WARNING **: 00:13:24.959: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:25352): IBUS-WARNING **: 00:13:24.983: bindingcommon.vala:90: Parse accelerator '<Alt>shift' failed!

(ibus-ui-gtk3:25352): IBUS-WARNING **: 00:13:24.983: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:25352): IBUS-WARNING **: 00:13:25.038: bindingcommon.vala:90: Parse accelerator '<Alt>shift' failed!

(ibus-ui-gtk3:25352): Gdk-CRITICAL **: 00:13:25.045: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by fujiwarat** [comment]
> (ibus-ui-gtk3:25352): IBUS-WARNING **: 00:13:24.983: bindingcommon.vala:90: Parse accelerator '<Alt>shift' failed!

Your keybinding is not correct. You could run `ibus reset-config`.
