### ISSUE TITLE
First char not caught by IME while typing into GNOME Shell's search bar in overview.

### ISSUE THREAD

**Issue by AlynxZhou** [ibus/ibus#2246]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

Arch Linux, Linux 5.7.11.

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

GNOME 3.36.4.

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Currently X11, but also happens on my Wayland machine.

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

GNOME Shell, press Super into overview and type to search.

IBus version?: 
(Run `ibus version`)

IBus 1.5.22

Issue description:

Press Super into GNOME Shell's overview and type to search something, while using a Chinese IME (confirmed with RIME and libpinyin), sometimes first char is not caught by IME and goes directly into search bar, while following char was caught. And if you  press Enter (to let English words go to entry directly), the first selected search results is launched instead of IME sends English words.

This is more likely to happen if you didn't open overview for a long time.

Steps to reproduce:
1. Use a Chinese IME (maybe all IME with a candidate panel is OK, but I confirmed with ibus-rime and ibus-libpinyin).
2. Press Super and type some words instantly to start search.
3. If it works normally, quit overview and try again after some time.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Yes, even after restart.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

I cannot trigger it every time so I don't get some log.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

Yes, I use two computers, one is a fresh installation.

PS This might related to How GNOME Shell handle input, but I am not sure. So I ask here first.

I got a screenshot and attached it here:

![photo_2020-07-31_11-48-49](https://user-images.githubusercontent.com/8444615/88998088-d7705200-d323-11ea-850d-d1b65ee1a1be.jpg)

You can see the `c` goes directly into entry but `hrome` goes into input panel, and if I press enter, the selected app starts instead of `horme` goes into entry.

**Comment by qiangzhao** [comment]
Hi Alynx: 
I think you mean this bug only can happen when input on the gnome-shell, Am I right?
If so it maybe related to GNOME.
Thank you.

**Comment by AlynxZhou** [comment]
> Hi Alynx:
> I think you mean this bug only can happen when input on the gnome-shell, Am I right?
> If so it maybe related to GNOME.
> Thank you.

Sure, I'll try to report to GNOME Shell.

**Comment by AlynxZhou** [comment]
This sometimes also happens in Qt applications like Telegram Desktop.

**Comment by tuberry** [comment]
It looks similar to that in Nautilus which has a type-to-search feature. You can reproduce it 100%.

**Comment by cherrry** [comment]
It happens to me in Google Chrome too.
But I have no problem with other applications such as telegram-desktop and xfce4-terminal.

**Comment by fujiwarat** [comment]
It's caused by each desktop because IBus accepts typing with the input focus but some desktop accepts typing with the window focus.
E.g. https://gitlab.gnome.org/GNOME/gtk/-/issues/2636

**Comment by AlynxZhou** [comment]
Any possible workaround for it? That's really annoying.

**Comment by AlynxZhou** [comment]
> It's caused by each desktop because IBus accepts typing with the input focus but some desktops accept typing with the window focus.
> E.g. https://gitlab.gnome.org/GNOME/gtk/-/issues/2636

This GTK issue is about wayland, but I can also reproduce this problem in X11, that's strange.

**Comment by fujiwarat** [comment]
> > It's caused by each desktop because IBus accepts typing with the input focus but some desktops accept typing with the window focus.
> > E.g. https://gitlab.gnome.org/GNOME/gtk/-/issues/2636
> 
> This GTK issue is about wayland, but I can also reproduce this problem in X11, that's strange.

I don't think it's a Wayland specific but commented it there.

**Comment by liangqi** [comment]
Tried with Ubuntu 22.04, GNOME on xorg, ibus(Chinese(Pinyin()), 125% / 200% scale, with FireFox, it works fine for me.

**Comment by AlynxZhou** [comment]
Well, this is fixed in GNOME Shell: <https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3067>.

I'll close this issue, thanks!
