### ISSUE TITLE
Does not have close button?

### ISSUE THREAD

**Issue by vaeli** [ibus/ibus#2247]
Please fill in the following items if you don't know the root cause.

Which distribution and version?:
Mint 10 (sysinfo: debian 10.5 (x86-64))

Which desktop environment and version?: 
Cinnamon 3.8.8

Which session type?: 
X11

Which application and version?: 
Desktop / Tray

IBus version?: 
1.5.19

Issue description:
It opens a language selector, even randomly - then it won't close without clicking on current (or other) language selection several times. It does not close if I simply select other window.

I have another language selector, working well; some installer added this one - I probably turn it off manually, so it's currently kind of not-my-problem (something simply needed and installed it); definitely I cannot reproduce, how I installed it. Still could be an useful widget tomorrow :) Anyway, a clean practice is to ensure it works properly, first.

Steps to reproduce:
1. Install it somehow, without noticing (could be an important part in case it's far somewhere it does not belong) - meaningfully, I don't know if it talked with Cinnamon about it's time and place, first..
1. Click to open it, or, well, wait a few days until it pops out somehow randomly.
1. Then click on windows, itself, try to open it's context menu when it's visible - none of them works.
1. Finally, click-click-click-click it's selected language until it's closed; also try to open it unlike other mint tray elements, just by hovering the mouse on it.

I think this gives a list of items to check before it's done ..I think my problem is completely gone (and me too lazy to switch it off - maybe something really needs it and breaks that way), if you simply add "do not open when hovered" to it's configuration - it's not a big thing if it's not doing it all automatically :)

The following work ..well I can check all those questions if you really need, but now I just add that it's still like this after several computer restarts and it didn't appear on my previous Cinnamon install. I checked another user account and the same program looks fairly different - instead of letters "EN" it has an icon, and I know this one has appeared in my mint before, being fairly useful. That one does not have the issue of not closing.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
I don't understand your problem.

> Install it somehow, without noticing 

What did you install?

> Click to open it

What did you open?

> Then click on windows, itself, try to open it's context menu when it's visible - none of them works.

The context menu of window is not relative with ibus.

> Finally, click-click-click-click it's selected language until it's closed;

What did you click?

You should elaborate your problem. Maybe attaching some screenshots is better.
