### ISSUE TITLE
Issues with colour and light

### ISSUE THREAD

**Issue by vaeli** [ibus/ibus#2248]
This I actually had to send to another application developer, but I can not receive an issue registration e-mail. So much it has to do with my previous issue, that it is kind of generic for this.

That other program could not set a menu font into light, when the menu background was set to dark. My very generic issue, which also has to do with an icon appearing, which could belong to another windowing environment - us, developers, we often do not want to change layouts from standard-like to another; and we really do not have "issues with styles and look-likes" in our issue repositories.

Thus, my very generic call (to all of the Developers, Testers and Vievers):
- Do *NOT* set your Cinnamon, KDE, Gnome, Enlightenment, and other layout and style setters to non-relative standards, where applications look good ..but try to be different in a very serious sense: set them to colors and settings, which look nice, but where programs fail to set everything up and look nice, or where the "serious graphics" bugs appear with how they fit into system drawing environment.
- At least one programmer, tester or designer should often have an environment, which is different from the others and from the standard defaults; I think they should still follow the standards, because those are at least somewhat tested.
- When the programs do not fit into that, issues should be opened and resolved for those programs.
- We never want to set our boxes to something nice (unless we are going to recode whole of our design), because nicety always breaks programs into non-compability.
But where the Linux starts? We accept to set up new things and fail about half of our computers only because we know that we do our normal job (small fixes and reports) and things are finally better off; for shoemaker only needs a broken shoes and a mountain climber is not dreaming of world where all the mountains have roads. So I guess we never get a good free design if we don't first accept a buggy free design - "it does not work", for free community, had renamed into "we got some work" in the very beginning, no?

So what is the very generic of this issue, which in my senses and ideas now suddenly split from the Free Community Philosophy:
- We use some very generic, built-in layouts, and fear to do any change, because programs are developed for defaults of any given os. When I change some settings of design, I always find out things like blue-on-blue text or very-big-button in a row of very small buttons, or an unknown flying object inside my computer - and there is nothing to observe.
- But the underlying cause - all the programmers chose the designs, which fit. Why we don't think such partial flickery-and-lags is simply a sign that designer (or, rather, a designing programmer) did not have an option for "alpha 0.1" compability in their vocabularity? Why we do not have a normal issue that "load icon gray does not look good/readable or even, meaningful, with third standard design of my OS"? So we simply fall back to default design and change some very small thing we trust.
- So what is a GPL way there? Let's just *survive* if everything is a cluttery and broken inside our computer, in a great piece of artistic work, where only 10% of programs look like having a very promising design, and let's imagine that we installed a new operating system, which makes our theorem prover be bloody fast where all the other programs thing, where the hell is the clipboard and why you have to write filenames in reverse..

**Comment by fujiwarat** [comment]
> "load icon gray does not look good/readable or even, meaningful, with third standard design of my OS"?

I don't understand your problem.
Please use the bug template with reproducing steps.
