### ISSUE TITLE
No picker for unicode, no space allowed in emoji picker, and lack of documentation

### ISSUE THREAD

**Issue by champignoom** [ibus/ibus#2249]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Manjaro 20.0.3

Which desktop environment and version?: 
Xfce 4.14

Which session type?: 
X11

Which application and version?: 
mousepad, vscode, firefox, and everything

IBus version?: 
IBus 1.5.22

Issue description:

press ctrl-shift-u, type "forall[space]", then "forall" is literally typed
press ctrl-shift-u, type "for[space]", then the typed "for" disappears, without the chance of typing "all".
press ctrl-shift-e, type "forall[space]", then nothing happens
press ctrl-shift-e, type "for[space]", then a plethora of emojis and unicodes are displayed, still without the chance of typing "all" to reduce the candidates to "∀"
There doesn't seem to be any documentation on this specifying the right way to input, the expected behavior, or something configuration that one has to do.

// Steps to reproduce:

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

**Comment by fujiwarat** [comment]
> It seems that the searching was once there and then removed by 28d2217

I don't agree with deleting space. You could insert space with Shift-space key. See also ibus-emoji(7) man page.

> press ctrl-shift-u, type "for[space]", then the typed "for" disappears, without the chance of typing "all".

Probably only this is a bug and I will fix it.
