### ISSUE TITLE
make install failure on read-only system environment

### ISSUE THREAD

**Issue by tinywrkb** [ibus/ibus#2251]
I'm repackaging IBus as Flatpak app for my own personal use (no plans for Flathub publishing) and I notice a make install issue when `/usr` is read-only and when IBus is installed to a different prefix than `/usr`, which is `/app` in the case of Flatpak.

These are the changes I'm suggesting for working around the make install failure. I could send these as a PR but it might be better to let someone that actually understands autotools to do that.

```
 
diff --git a/configure.ac b/configure.ac
index 2917c10b..6c015178 100644
--- a/configure.ac
+++ b/configure.ac
@@ -439,7 +439,12 @@ PKG_CHECK_EXISTS([pygobject-3.0 >= $PYGOBJECT_REQUIRED],
 if test "x$enable_pygobject" = "xyes"; then
     PKG_CHECK_MODULES(PYTHON, [pygobject-3.0 >= $PYGOBJECT_REQUIRED])
 
-    pyoverridesdir=`$PYTHON -c "import gi; print(gi._overridesdir)"`
+    AC_ARG_WITH(pyoverridesdir,
+        AS_HELP_STRING([--with-pyoverridesdir[=DIR]],
+            [Set the Python overrides directory.]),
+        pyoverridesdir=$with_pyoverridesdir,
+        pyoverridesdir=`$PYTHON -c "import gi; print(gi._overridesdir)"`
+    )
     AC_SUBST(pyoverridesdir)
 
     if test x"$enable_python2" = x"yes"; then
diff --git a/data/dconf/Makefile.am b/data/dconf/Makefile.am
index 5360f033..691a0ea8 100644
--- a/data/dconf/Makefile.am
+++ b/data/dconf/Makefile.am
@@ -50,7 +50,7 @@ man_5dir = $(mandir)/man5
 
 install-data-hook:
 	if test -z "$(DESTDIR)"; then \
-	    dconf update; \
+	    dconf update $(sysconfdir)/dconf/db; \
 	fi
 
 EXTRA_DIST = \
```

**Comment by fujiwarat** [comment]
You don't have to install python modules and dconf update.
For GNOME; https://github.com/ibus/ibus/blob/master/test/org.test.IBus.json
For Freedesktop; https://github.com/ibus/ibus/blob/master/test/org.test2.IBus.json
