### ISSUE TITLE
About "show property panel". (not bug or error) 

### ISSUE THREAD

**Issue by queenmedley** [ibus/ibus#2252]
I used systray a while ago, and I was complaining that it didn't show the language to change.
But now I know that a preferences "show propety panel" shows the selected language whenever the language changes.
I think it would be better if that panel property is displayed in the panel like windows not pop up, but I am curious if I don't know how or if there is no such function yet.

**Comment by fujiwarat** [comment]
Systray spec can show one icon only. If two icons are shown, the order is not assured. IME icon is a image file and it could include any info as the workaround.
If you use ibus-anthy, the engine icon shows the engine image at one second and the typing mode later.
