### ISSUE TITLE
When inputing Chinese/Japanese in Inkscape, the ibus candidates popup window is misplaced off screen.

### ISSUE THREAD

**Issue by tfhavingfun** [ibus/ibus#2257]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Arch Linux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Gnome 3.36.6

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Inkscape 1.0 and above

IBus version?: 
(Run `ibus version`)
1.5.22

Issue description:
When inputing Chinese/Japanese into any text fields inside Inkscape, the ibus candidates popup window is misplaced off screen. So we couldn't really know what's being converted to Chinese/Japanese. 
This issue is also reported here for Inkscape: https://gitlab.com/inkscape/inkscape/-/issues/1009

Steps to reproduce:
1. Open inkscape
1. Choose text tool
1. Change input method to a Chinese or Japanese one.
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
I think it's an inkscape issue.
Seems the upstream bug was updated and it would be good for you to try the updated inkscape.
