### ISSUE TITLE
i3wm-gaps can't use switch IME shortkey

### ISSUE THREAD

**Issue by ThomasThongCE** [ibus/ibus#2258]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 20.04 with 5.6.15-050615-generic kernel

Which desktop environment and version?: 
i3wm-gaps version 4.18.1

Which session type?: 
X11

Which application and version?: 
Every application.

IBus version?: 
IBus 1.5.22

Issue description:
Can't switch IME using shortkey which is win+space key. But when press this key combination repeatedly, there is a chance for it to show the input method switching windows in the middle of the screen. But after open or using another application like chrome, it looks like no matter how many time you press, it won't switch anymore. 
I have to click on the icon at the i3status bar to switch input method.

Steps to reproduce:
1. Install ubuntu 20.04
2. Install i3wm (through apt) + gaps version ( according to [this](https://gist.github.com/boreycutts/6417980039760d9d9dac0dd2148d4783) )
3. Install ppa:bamboo-engine/ibus-bamboo and mozc
4. Add bamboo and mozc into input method using ibus-setup
5. Try to switch input method using shortcut windows+space 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
```
(ibus-ui-gtk3:13874): IBUS-WARNING **: 17:06:25.954: panel.vala:255: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:13874): IBUS-WARNING **: 17:06:26.005: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:13874): Gdk-CRITICAL **: 17:06:26.073: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
XGrabPointer: successfully grabbed mouse pointer
```

when the input method can switch or show a small method switching window, It show:
```
WM_CLASS=(x-terminal-emulator:X-terminal-emulator)
Disable.2020/09/12 17:06:33 FocusOut.
Enable.2020/09/12 17:06:33 FocusIn.
WM_CLASS=(x-terminal-emulator:X-terminal-emulator)
2020/09/12 17:06:33 FocusOut.
2020/09/12 17:06:33 FocusIn.
WM_CLASS=(x-terminal-emulator:X-terminal-emulator)

(ibus-ui-gtk3:13874): IBUS-WARNING **: 17:06:33.247: switcher.vala:210: Grab pointer failed! status = 1
Disable.2020/09/12 17:06:33 FocusOut.
2020/09/12 17:06:34 FocusIn.
Enable.WM_CLASS=(x-terminal-emulator:X-terminal-emulator)
Disable.2020/09/12 17:06:34 FocusOut.
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by mike-fabian** [comment]
By default, ibus uses <Super>space to switch between input methods.

This doesn't work well together with the default settings of i3, because i3 uses the left windows key for many things.

The very first line in my ~/.config/i3/config is 

```
    set $mod Mod4
```

This sets $mod to Mod4 and Mod4 is the left Windows key. Then $mod is used for all sorts of window management things.
So you cannot use the left windows key anymore to switch input methods.

So you can do either:

1) Choose a different key for $mod in your i3 setup
2) Choose a different key in ibus-setup to switch input  methods.

I am doing 2), I did set <Shift>space in ibus-setup to switch input methods, that works fine for me, I am happy with that.

**Comment by fujiwarat** [comment]
Seems i3 desktop has the conflict shortcut key against ibus and @mike-fabian ' s suggestion could resolve the issue.
