### ISSUE TITLE
Latest Ubuntu 20.04 update broke Emoji shortcut

### ISSUE THREAD

**Issue by marcoscannabrava** [ibus/ibus#2262]
Which distribution and version?: **Ubuntu 20.04.1 LTS**

Which desktop environment and version?: **GNOME 3.36.3**

Which session type?:  **X11**

Which application and version?: **Any application. Chrome, Gedit, etc.**

IBus version?: **1.5.22**

Issue description:

Steps to reproduce:
1. using emoji panel shortcut does nothing

Can you reproduce your problem when you restart ibus-daemon? **Yes**
Running `ibus emoji` opens the emoji panel. The shortcut doesn't.

Do you see any errors when you run ibus-daemon with the verbose option?: **No output whatsoever.**

Can you reproduce your problem with a new user account instead of the current your account? **Yes**

**Comment by DevotionGeo** [comment]
I also have the same problem, ctrl+shift+e stopped working.

**Comment by fujiwarat** [comment]
Is /usr/lib*/ibus-extension-gtk3 running in your system?

I guess you don't enable any ibus engines with `gnome-control-center region`.
E.g. ibus-hangul, ibus-typing-booster.
You could check it with `gsettings get org.gnome.desktop.input-sources sources` .

**Comment by DevotionGeo** [comment]
It outputs `[('xkb', 'us'), ('xkb', 'pk')]`

**Comment by marcoscannabrava** [comment]
ibus-extension-gtk3 is running here and the output for input-sources is empty
```
$> gsettings get org.gnome.desktop.input-sources sources
@a(ss) []

$> ps -aux | grep 'ibus'   
marcos      1718  0.0  0.0 311424  7512 ?        Sl   Sep24   0:04 ibus-daemon --panel disable --xim
marcos      1722  0.0  0.0 162700  6264 ?        Sl   Sep24   0:00 /usr/libexec/ibus-memconf
marcos      1723  0.0  0.1 275696 20212 ?        Sl   Sep24   0:03 /usr/libexec/ibus-extension-gtk3
marcos      1725  0.0  0.1 197904 22516 ?        Sl   Sep24   0:01 /usr/libexec/ibus-x11 --kill-daemon
marcos      1728  0.0  0.0 236632  6732 ?        Sl   Sep24   0:00 /usr/libexec/ibus-portal
marcos      1882  0.0  0.0 162692  6696 ?        Sl   Sep24   0:00 /usr/libexec/ibus-engine-simple
marcos     97073  0.0  0.0   9040  2560 pts/3    R+   09:36   0:00 grep --color ibus

```

**Comment by fujiwarat** [comment]
> It outputs [('xkb', 'us'), ('xkb', 'pk')]

It will show ibus input sources likes ('ibus', 'foo') if you add and then.
If you add xkb sources only, GNOME configure xkb sources as gtk-im-context-simple but not ibus.

**Comment by marcoscannabrava** [comment]
Sorry. I tried adding [('ibus', 'xkb:us::eng')], [('ibus', 'xkb')] and other variations but still couldn't get it to work. Any other ideas?
_I use a single keyboard layout for Portuguese._

**Comment by fujiwarat** [comment]
('ibus', 'xkb') does not exist. You should install ibus engines with gnome-control-center.

**Comment by marcoscannabrava** [comment]
When I run `ibus engine` I get `xkb:us::eng`. Do I still have to install an
ibus engine through gnome-control-center? How do I do that?

More info on the problem: the hotkey ctrl+shift+u works as the unicode
shortcut so it's just the emoji shortcut that's not working. I tried with
different key combinations and nothing seems to work.


*Marcos Provenzano Cannabrava*
*+1 (415) 992 5332 / **+55 (21) 99535 0555*
github <https://github.com/marcoscannabrava/> | linkedin
<https://www.linkedin.com/in/marcos-cannabrava/> | portfolio
<https://cannabrava.co/>

**Comment by fujiwarat** [comment]
Again,
> E.g. ibus-hangul, ibus-typing-booster.

`xkb:ibus:eng` should not be available in gnome-control-center.

> More info on the problem: the hotkey ctrl+shift+u works as the unicode
shortcut so it's just the emoji shortcut that's not working.

It's not the shortcut from ibus.

**Comment by fujiwarat** [comment]
> It's weird that I didn't have any ibus engines in gnome-control-center before and it worked.

I guess you don't install ibus engines likes ibus-hangul, ibus-typing-booster.
You could check it with `ibus list-engine | grep -v xkb`.

**Comment by ernstp** [comment]
Perhaps it was triggered by this?

`im-config (0.44-1ubuntu1.2) focal; urgency=medium

  * d/p/back-off-if-ibus-on-gnome.patch:
    - Let im-config back off if IBus on GNOME desktop (LP: #1893551)
  * d/p/make-usable-on-wayland.patch, d/README.Debian, d/install:
    - Use im-config on Wayland without uninstalling IBus (LP: #1893552)

 -- Gunnar Hjalmarsson <gunnarhj@ubuntu.com>  Thu, 03 Sep 2020 19:55:00 +0200`

**Comment by gunnarhj** [comment]
@ernstp: Yes, that's most likely it.

I'm not sure how to deal with this. With that change IBus works on GNOME desktops just as it's intended to work.

For now, if you are not using an IBus input method, the easiest way to make Ctrl+Shift+E work as before is to open the `~/.profile` file for editing and add this line:

    export GTK_IM_MODULE=ibus

(and then re-login).

**Comment by marcoscannabrava** [comment]
@gunnarhj suggestion works perfectly. Thanks.
