### ISSUE TITLE
key_press_event signal isn't fired when turn on ibus

### ISSUE THREAD

**Issue by makotokato** [ibus/ibus#2270]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Debian/sid

Which desktop environment and version?: 
GNOME 3.38. (This also occurs on previous version too)

Which session type?: 
Wayland.  This doesn't occurs on X session.

Which application and version?: 
Firefox 81 (with MOZ_ENABLE_WAYLAND=1)
At least, this occurs on all application (I check simple GTK sample. code is https://gist.github.com/makotokato/ca97bb7467deeef7a8a274623709b4d6)

IBus version?: 
1.5.22

Issue description:
When turning on IME and inputting composing string , `key_press_event` singal isn't fired.  If IME is off, this doesn't occur.
Although I test on ibus-kkc, ibus-mozc, ibus-hangul and ibus-pinyin, this occurs on all engines.

This is Wayland only.

Steps to reproduce:
1. Set current IM to ibus-kkc
2. Open Firefox
3. Browser https://w3c.github.io/uievents/tools/key-event-viewer.html
4. Set Input mode to あ
5. Hit 'A' to input ’あ' multiple

Result:
no keydown event

Expected Result:
Show keydown event when inputting 'あ'.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
I don't know

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

**Comment by makotokato** [comment]
Ah, I need more investigate this. Close at this time.

**Comment by fujiwarat** [comment]
ibus-daemon forwards key events from gnome-shell to IBus engines when you use GNOME Wayland and IBus GtkIMModule is not used by default.
