### ISSUE TITLE
chrome and gnome-terminal have no capability of surrounding-text feature

### ISSUE THREAD

**Issue by NattapongSiri** [ibus/ibus#2271]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 20.04

Which desktop environment and version?: 
Gnome 3.36.3

Which session type?: 
X11

Which application and version?: 
xterm and Chrome

IBus version?: 
1.5.22

Issue description:
Fail to type Thai combining character.
Log shows `gnome-terminal-[2589]: gnome-terminal-server has no capability of surrounding-text feature`

Steps to reproduce:
1. Boot up the machine.
2. Open Google Chrome.
3. Switch keyboard layout to `Thai (LibThai)`
4. Type Thai text "กิน" which is equals to following keystroke "dbo" but with Thai keyboard layout.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
```
(ibus-engine-libthai:4410): IBUS-WARNING **: 08:45:44.194: org.freedesktop.IBus.Config.GetValue: GDBus.Error:org.freedesktop.DBus.Error.Failed: Config value [engine/LibThai:kb_layout] does not exist.
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by gunnarhj** [comment]
The issue was [originally reported to Ubuntu](https://launchpad.net/bugs/1900640). I was able to reproduce it on Ubuntu 20.04 (ibus 1.5.22) and Ubuntu 20.10 (ibus 1.5.23), but the issue is not present on Ubuntu 18.04 (ibus 1.5.17). The same `ibus-libthai` upstream version (0.1.4) is used in all cases.

There is tlwg/ibus-libthai@d9b9973b which looks related, but building `ibus-libthai` with that commit does not fix the issue.

**Comment by gunnarhj** [comment]
@thep: This may be an `ibus-libthai` issue.

**Comment by NattapongSiri** [comment]
I'm trying to figure this out as well as it is effecting my daily usage experience.
The commit you referred to just make a call to this function:
https://github.com/ibus/ibus/blob/dd4cc5b028c35f9bb8fa9d3bdc8f26bcdfc43d40/src/ibusengine.c#L1816-L1820
Are you saying that before the call, it need some prerequisite work ?
Otherwise, why `Gnome Text Editor` work but not terminal or Chrome ?

**Comment by gunnarhj** [comment]
@NattapongSiri: I merely mentioned it, but I'm not able to tell the significance of it. All I know is that applying it didn't make a difference, and that it works on 18.04 without it, which indicates that the issue is caused by some change in the IBus code.

**Comment by NattapongSiri** [comment]
Per IBus doc [here](https://ibus.github.io/docs/ibus-1.5/IBusEngine.html#ibus-engine-get-surrounding-text),
The code here is used for telling IBus that ibus-libthai is going to need surrounding context.

https://github.com/tlwg/ibus-libthai/blob/bbca4167db6affb0c19441f44917ce700825273c/src/engine.c#L328-L333

I take a closer look in the source code of function get-surrounding-text and notice that it didn't do much. The main thing is done outside this function as shown in here.
https://github.com/ibus/ibus/blob/dd4cc5b028c35f9bb8fa9d3bdc8f26bcdfc43d40/src/ibusengine.c#L1840-L1847
It is just an indirect call to this function:
https://github.com/ibus/ibus/blob/dd4cc5b028c35f9bb8fa9d3bdc8f26bcdfc43d40/src/ibusservice.c#L613-L619

I also notice that my log also emit warning like
```
gnome-terminal-server has no capability of surrounding-text feature
```
even though, i just switch from my Chrome to terminal without switching any keyboard layout and my current layout is English.
I'm not expert on IBus. Where else do you think I should take a look at ?

**Comment by fujiwarat** [comment]
> It is just an indirect call to this function:

The function should work for surrounding text feature.

Which application gnome-terminal or chrome did you try?

> gnome-terminal-server has no capability of surrounding-text feature

gnome-terminal does not support the surrounding text feature yet.
gedit should works fine with the feature.

**Comment by NattapongSiri** [comment]
> Which application gnome-terminal or chrome did you try?

I'm not sure if I got your question right.
What I was doing is open Chrome and Terminal then just switching between my Chrome and terminal.
The log then have something like this:
```
gnome-terminal-server has no capability of surrounding-text feature
message repeated 17 times: [ gnome-terminal-server has no capability of surrounding-text feature]
(google-chrome-stable:2271): IBUS-WARNING **: 07:05:58.369: google-chrome-stable has no capability of surrounding-text feature
```

However, If I open `Gnome Text Editor` with Thai keyboard layout then switch to Chrome/Terminal then type Thai, it's working fine but the log still have those warning for each of my keystroke.
```
(google-chrome-stable:2271): IBUS-WARNING **: 07:12:06.719: google-chrome-stable has no capability of surrounding-text feature
gnome-terminal-[2180]: gnome-terminal-server has no capability of surrounding-text feature
```

**Comment by thep** [comment]
> @thep: This may be an `ibus-libthai` issue.

I don't think so. Surrounding text support needs client-side acceptance to access the application's input text, which most terminal emulators appear to lack, and, as reported here, so does Chrome. This is obviously individual application's issue.

So, how does `ibus-libthai` handle the case? You can turn off the input sequence check in its preferences by choosing **"No Check"** option under the **"Input sequence check mode"** category.

**Comment by NattapongSiri** [comment]
Based on the code below, isn't it going to user internal buffer if surrounding feature isn't available ?
https://github.com/tlwg/ibus-libthai/blob/bbca4167db6affb0c19441f44917ce700825273c/src/engine.c#L258-L263

**Comment by fujiwarat** [comment]
@NattapongSiri 
> message repeated 17 times: [ gnome-terminal-server has no capability of surrounding-text feature]
> (google-chrome-stable:2271): IBUS-WARNING **: 07:05:58.369: google-chrome-stable has no capability of surrounding-text feature

OK, you mean both gnome-terminal and chrome does not work with surround text feature.
I didn't check chrome but from your log, you have to report the issue to chrome.

We have already reported the issue to gnome-terminal.
https://gitlab.gnome.org/GNOME/vte/-/issues/214

**Comment by gunnarhj** [comment]
@thep wrote:
> So, how does ibus-libthai handle the case? You can turn off the input sequence check in its preferences by choosing **"No Check"** option under the **"Input sequence check mode"** category.

With that change it started to work for me both with gnome-terminal and Google Chrome. The warning messages are still spamming the log, but AFAICT it works.

**Comment by fujiwarat** [comment]
So your issue is not ibus. Please report them in each application.

**Comment by LeeiFrankJaw** [comment]
> So your issue is not ibus. Please report them in each application.

I also got the following message.
```
Feb 08 23:10:23 lei-Inspiron-3881 gnome-shell[1784]: JS ERROR: Gio.IOErrorEnum: Timeout was reached
                                                     setEngine/<@resource:///org/gnome/shell/misc/ibusManager.js:240:32
```
It seems to me that this is a problem of the interaction between iBus and GNOME Shell.
