### ISSUE TITLE
Belarusian keymap missing

### ISSUE THREAD

**Issue by vasyugan** [ibus/ibus#2273]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 

Debian Bullseye

Which desktop environment and version?: 
Mate 1.24.1

Which session type?: 
X11

Which application and version?: 
ibus-setup 

IBus version?: 

IBus 1.5.22

Issue description:

I cannot select a Belarusian keymap. Ukrainian and Russian are available, but not Belarusian, although it is available from the standard Mate keyboard settings

Steps to reproduce:
1. Run ibus-setup 
2. go to layouts 
3. Try to locate Belarusian

**Comment by fujiwarat** [comment]
Please try 1.5.23
