### ISSUE TITLE
iBus daemon could not be started in 5 seconds.

### ISSUE THREAD

**Issue by leoxu1007** [ibus/ibus#2275]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 20.04 LTS

Which desktop environment and version?: 
 GNOME latest

Which session type?: 
pop up window

Which application and version?: 
ibus

IBus version?: 
IBus 1.5.22

Issue description:
ibus doesn't work

Steps to reproduce:
1. ibus-setup
2. 
![image](https://user-images.githubusercontent.com/22413258/99031566-bd990900-25ba-11eb-93a8-dd9522a4db3f.png)

3. 
![image](https://user-images.githubusercontent.com/22413258/99031586-cc7fbb80-25ba-11eb-947f-2a39da7db0b3.png)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
ibus-daemon itself is not working

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

leoxu@leoxu-Ideapad-Z575:~$ ibus-daemon --xim --verbose &
[1] 7046
leoxu@leoxu-Ideapad-Z575:~$ 
Command 'ibus-daemon' not found, but can be installed with:

sudo apt install ibus

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by HowieHepburn** [comment]
hey bro, have you solve this problem yet?
