### ISSUE TITLE
Dead Keys Preview not showing/working

### ISSUE THREAD

**Issue by TheJoigoMan** [ibus/ibus#2282]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Ubuntu 20.04.1

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 3.36.3

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Any text app

IBus version?: 
(Run `ibus version`)
IBus 1.5.22

Issue description:
Sorry if I'm not very specific, I saw that standard GNOME, like in a Live USBs, have a dead keys preview visual feature (which I don't know how it's called, I believe its preedit but I'm not sure) that shows a   ´   symbol with an underscore, like a semidead key. So I pressed    ´   and the  ´  would show up, and then I would press the letter to get the corresponding compose (I use spanish - spanish keyboard). But at some point while using my Ubuntu, it stopped showing the preview. Now when I press the dead key it just stays blank and only shows up the composite after pressing a letter. I would like to find how to get the preview/preedit working again because I really liked it.

Steps to reproduce:
Unknown, happens as soon as I log in, but not at User Selection

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes it still doesn't show the preview.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
I don't understand this step, could you tell me what should I expect to see?

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I'm going to try that and respond

**Comment by TheJoigoMan** [comment]
Just created another user and tried, sadly no, it still doesn't show up the dead keys preview/preedit.

**Comment by TheJoigoMan** [comment]
https://blog.simos.info/using-ibus-typing-booster-for-predictive-typing-in-ubuntu-20-04-lts/
In case somebody didn't understand me, the first video in greek on this link shows up the dead keys preview that I'm referring to.

**Comment by mike-fabian** [comment]
Are you using ibus-typing-booster or other ibus input methods? Or are you only using keyboard layouts?

Is ibus running? I.e if  you do 

```
ps aux | grep ibus
```

does that list some ibus related processes for you?

**Comment by mike-fabian** [comment]
I cannot reproduce your problem.

```
mfabian@katatsumuri:~$ ps aux | grep ibus
mfabian     4791  0.2  0.4 327908  9652 ?        Ssl  10:57   0:01 /usr/bin/ibus-daemon --daemonize --xim
mfabian     4795  0.0  0.4 179108  8400 ?        Sl   10:57   0:00 /usr/libexec/ibus-memconf
mfabian     4796  0.1  3.1 720612 63184 ?        Sl   10:57   0:00 /usr/libexec/ibus-ui-gtk3
mfabian     4799  0.4  2.8 683340 57496 ?        Sl   10:57   0:01 /usr/libexec/ibus-extension-gtk3
mfabian     4803  0.0  2.6 605644 54540 ?        Sl   10:57   0:00 /usr/libexec/ibus-x11 --kill-daemon
mfabian     4806  0.0  0.4 252776  8556 ?        Sl   10:57   0:00 /usr/libexec/ibus-portal
mfabian     4892  0.0  0.4 179100  8484 ?        Sl   10:57   0:00 /usr/libexec/ibus-engine-simple
mfabian     5452  2.1 17.4 647132 354200 ?       Sl   10:58   0:07 /usr/bin/python3 /usr/share/ibus-typing-booster/engine/main.py --ibus
mfabian     7396  0.0  0.1  21616  2816 pts/5    S+   11:04   0:00 grep --color=auto ibus
mfabian@katatsumuri:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
mfabian@katatsumuri:~$ 
```

**Comment by mike-fabian** [comment]
![Screenshot](https://user-images.githubusercontent.com/2330175/100213272-b3f29800-2f0e-11eb-984a-64449943512b.png)

**Comment by TheJoigoMan** [comment]
> ps aux | grep ibus

This shows in my terminal 
![image](https://user-images.githubusercontent.com/75008901/100271936-494e5600-2f28-11eb-94b6-7318a5aa9412.png)

**Comment by TheJoigoMan** [comment]
I'm not using ibus typing booster, and I don't think I'm using any other IM

**Comment by TheJoigoMan** [comment]
> You can see the preview of the dead acute accent at the bottom of the terminal in this screenshot. Using the Spanish keyboard layout:
> 
> ![Screenshot](https://user-images.githubusercontent.com/2330175/100213272-b3f29800-2f0e-11eb-984a-64449943512b.png)

Yes that's the preview that I'm talking about, sadly I can't access it either in the terminal. As I mentioned before I do see the preview when I'm not in my session, while using the Not Listed option in the user selection.
![image](https://user-images.githubusercontent.com/75008901/100273892-8700ae00-2f2b-11eb-81a2-18cd34cb243f.png) (image is from google)

**Comment by TheJoigoMan** [comment]
> I cannot reproduce your problem.
> 
> ```
> mfabian@katatsumuri:~$ ps aux | grep ibus
> mfabian     4791  0.2  0.4 327908  9652 ?        Ssl  10:57   0:01 /usr/bin/ibus-daemon --daemonize --xim
> mfabian     4795  0.0  0.4 179108  8400 ?        Sl   10:57   0:00 /usr/libexec/ibus-memconf
> mfabian     4796  0.1  3.1 720612 63184 ?        Sl   10:57   0:00 /usr/libexec/ibus-ui-gtk3
> mfabian     4799  0.4  2.8 683340 57496 ?        Sl   10:57   0:01 /usr/libexec/ibus-extension-gtk3
> mfabian     4803  0.0  2.6 605644 54540 ?        Sl   10:57   0:00 /usr/libexec/ibus-x11 --kill-daemon
> mfabian     4806  0.0  0.4 252776  8556 ?        Sl   10:57   0:00 /usr/libexec/ibus-portal
> mfabian     4892  0.0  0.4 179100  8484 ?        Sl   10:57   0:00 /usr/libexec/ibus-engine-simple
> mfabian     5452  2.1 17.4 647132 354200 ?       Sl   10:58   0:07 /usr/bin/python3 /usr/share/ibus-typing-booster/engine/main.py --ibus
> mfabian     7396  0.0  0.1  21616  2816 pts/5    S+   11:04   0:00 grep --color=auto ibus
> mfabian@katatsumuri:~$ cat /etc/os-release 
> NAME="Ubuntu"
> VERSION="20.04 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> mfabian@katatsumuri:~$ 
> ```

Sorry I don't know how to reproduce the problem, I don't even know what made this happen, as soon as I log in the previews disappear. Funny thing is, it happens in any user I create, so it seems it's a global feature of IBus.

**Comment by TheJoigoMan** [comment]
Is there a way to check which text framework I'm using, because it seems that it changes as soon as I enter my session. But I don't know how to confirm it.

**Comment by TheJoigoMan** [comment]
Now that I realize, I don't have active the /usr/libexec/ibus-ui-gtk3 part, is that supposed to handle the UI?

**Comment by mike-fabian** [comment]
Another thing which would be interesting to try is to add ibus-typing-booster in the gnome settings.

There should be a package for ibus-typing-booster for ubuntu. The blog you mentioned shows you how to add it
in the gnome-control-center after the package is installed:

https://blog.simos.info/using-ibus-typing-booster-for-predictive-typing-in-ubuntu-20-04-lts/

Then chose your Spanish keyboard layout ('es') in the panel, then ibus-typing-booster (the 🚀 entry in the gnome panel).
Ibus-typing-booster uses the keyboard layout which was in use last before switching to ibus-typing-booster, that's why I wrote use 'es' first.

Ibus-typing-booster has its own dead key support, including preview, if ibus-typing-booster is working, you should definitely see the dead-key preview. My hope is that adding ibus-typing-booster as an extra input method forces proper startup of all the ibus stuff. 

If the ibus-typing-booster and its dead key preview works, switch back to 'es' in the gnome panel and check if the dead key preview works now. 

While using 'es' you see the dead key preview done by ibus, while using ibus-typing-booster you see the dead key preview done by ibus-typing-booster. They look the same but they are different implementations. 

The dead key preview should work without adding ibus-typing-booster, it does for me and I have no idea at the moment why this doesn't work for you. But maybe adding  ibus-typing-booster and checking whether that helps gives us an insight what is wrong.

**Comment by TheJoigoMan** [comment]
> > Now that I realize, I don't have active the /usr/libexec/ibus-ui-gtk3 part, is that supposed to handle the UI?
> 
> I am not sure. It is a bit surprising that this is not running in your case, but I don’t know whether this causes the problem.
> 
> In my Ubuntu vm, I removed all input methods except the Spanish keyboard layout in the gnome-settings. I still see /usr/libexec/ibus-ui-gtk3 running and the dead key preview still works.
> 
> The screenshot below also shows how some ibus related environment variables are set in my case. Are any of these environment variables set differently in your case?
> 
> ![Screenshot](https://user-images.githubusercontent.com/2330175/100338030-63e00800-2fd8-11eb-991d-09011f70313e.png)

You are right, I just have this two environments, and coincidentally no GTK.
![image](https://user-images.githubusercontent.com/75008901/100387138-56854680-2ff5-11eb-8262-31b12e6d2869.png)

**Comment by mike-fabian** [comment]
I am not sure whether GTK_IM_MODULE=ibus matters, but it cannot hurt to set it and try whether it helps.

**Comment by TheJoigoMan** [comment]
Just checked and yes, it works now. I downloaded the typing booster, which btw works amazing, and now I can see the previews.
![image](https://user-images.githubusercontent.com/75008901/100389588-c5fe3480-2ffb-11eb-862a-9b3449fd3dcb.png)
Good thing is that, I have both the typing booster and the spanish keyboard active and when I go back to spanish the previews are still working, so the typing booster made them work again.
![image](https://user-images.githubusercontent.com/75008901/100389681-052c8580-2ffc-11eb-8612-e71597511742.png)
The same env check give me the same result, the only difference is in the ps aux:
![image](https://user-images.githubusercontent.com/75008901/100389732-2a20f880-2ffc-11eb-9414-d1c9f634afaf.png)
which now shows the typing booster engine.

One side note: Correct me if I'm wrong but I believe you are the creator of typing booster, maybe this would be of your interest, it seems that I cannot write anything on the ubuntu search box with the typing booster, but I'm just mentioning the bug:
![image](https://user-images.githubusercontent.com/75008901/100389854-91d74380-2ffc-11eb-839d-987f949f5e62.png)

**Comment by TheJoigoMan** [comment]
So doing some tests, I see that when I remove the Typing Booster from the Input Methods it stops showing me the previews again. So It doesn't remain repaired. I don't know where to search the difference so I will wait for any commands you recommend.

**Comment by mike-fabian** [comment]
> One side note: Correct me if I'm wrong but I believe you are the creator of typing booster, maybe this would be of your interest, it seems that I cannot write anything on the ubuntu search box with the typing booster, but I'm just mentioning the bug:

I cannot reproduce that.

![Screenshot](https://user-images.githubusercontent.com/2330175/100428348-1a54f300-3094-11eb-873c-1d83864700e2.png)

**Comment by mike-fabian** [comment]
> Good thing is that, I have both the typing booster and the spanish keyboard active and when I go back to spanish the previews are still working, so the typing booster made them work again.

I think if there is at least one real input method configured, in this example ibus-typing-booster, then ibus is certainly used for the keyboard layouts like "es" as well. When ibus is used, you see the dead key preview, in case of the "es" layout the dead key preview implemented by ibus, in case of ibus-typing-booster the dead key preview implemented by ibus-typing-booster. These are two different implementations but they look the same.

If you remove ibus-typing-booster again, in your case ibus seems not to be used for the "es" layout because you loose the dead key preview and see the tradtional dead key behaviour from X11. But when I try to reproduce this and remove everything except the "es" keyboard layout, I still see the dead key preview, so ibus is still used even when I have only "es" in the settings. I don't know why this is different for you.

**Comment by mike-fabian** [comment]
> The same env check give me the same result, the only difference is in the ps aux:

So it seems that GTK_IM_MODULE does not make a difference.

**Comment by TheJoigoMan** [comment]
So is there a way I can test if ibus is not being used when I only have ES active? Or what do you recommend we do to find what's causing this behavior?

**Comment by TheJoigoMan** [comment]
Maybe I'm wrong, but I think I saw in the code that the ibus engine simple is in charge of the ibus compose preedit, could it be failing or maybe got reconfigured?

**Comment by TheJoigoMan** [comment]
> > One side note: Correct me if I'm wrong but I believe you are the creator of typing booster, maybe this would be of your interest, it seems that I cannot write anything on the ubuntu search box with the typing booster, but I'm just mentioning the bug:
> 
> I cannot reproduce that.
> 
> ![Screenshot](https://user-images.githubusercontent.com/2330175/100428348-1a54f300-3094-11eb-873c-1d83864700e2.png)

Just realized something, I can't put any dead keys in the search bar with ES, nor any text with the Typing booster. Can you write dead keys in the search bar? It seems mine doesn't admit any type of preedit for some reason

**Comment by mike-fabian** [comment]
> So is there a way I can test if ibus is not being used when I only have ES active? 

I think when you do not see the dead key preview, that proves that ibus is not being used.

> Or what do you recommend we do to find what's causing this behavior?

I have no idea why this happens at the moment, as I cannot reproduce it I really don’t know what I could investigate.

**Comment by mike-fabian** [comment]
> Maybe I'm wrong, but I think I saw in the code that the ibus engine simple is in charge of the ibus compose preedit, 

Yes, that is correct.

> could it be failing or maybe got reconfigured?

I don’t think so, it seems to me that it is not used at all in your gnome-terminal.

**Comment by TheJoigoMan** [comment]
I'm going to try and find what made this change. Something interesting I just found out, I also installed Ubuntu to a friend's laptop, and I imitated most of my configuration style with him, and Oh surprise it seems he doesn't have previews either. So maybe I'm going to reinstall my Ubuntu and do my configs again to find out what made it change.

**Comment by mike-fabian** [comment]
> Just realized something, I can't put any dead keys in the search bar with ES, nor any text with the Typing booster. Can you write dead keys in the search bar? It seems mine doesn't admit any type of preedit for some reason

Yes,  I can, and the preview works as well:

![Screenshot](https://user-images.githubusercontent.com/2330175/100554541-9702ef80-3295-11eb-9117-ed5dc5912044.png)

**Comment by mike-fabian** [comment]
> I'm going to try and find what made this change. Something interesting I just found out, I also installed Ubuntu to a friend's laptop, and I imitated most of my configuration style with him, and Oh surprise it seems he doesn't have previews either. So maybe I'm going to reinstall my Ubuntu and do my configs again to find out what made it change.

So it works before you do your special configuration?

**Comment by TheJoigoMan** [comment]
> > I'm going to try and find what made this change. Something interesting I just found out, I also installed Ubuntu to a friend's laptop, and I imitated most of my configuration style with him, and Oh surprise it seems he doesn't have previews either. So maybe I'm going to reinstall my Ubuntu and do my configs again to find out what made it change.
> 
> So it works before you do your special configuration?

I am almost sure It worked before I installed one of this
![image](https://user-images.githubusercontent.com/75008901/100559189-98292200-327f-11eb-95cc-2f0ec655dc8d.png)

**Comment by TheJoigoMan** [comment]
If I can't find what is changing the behavior I will reinstall Ubuntu and redo my installs to find out which one did it.

**Comment by TheJoigoMan** [comment]
Well to summarize, I did a fresh install of Ubuntu 20.04.1 and now I believe I can show how to replicate, it was very simple.
Did a fresh install, then went through basic configuration, asked for updates, and suddenly after the first restart the preedits were gone. The first batch of 20.04.1 updates killed them and I am searching for the list of things updated.

**Comment by TheJoigoMan** [comment]
![image](https://user-images.githubusercontent.com/75008901/100588471-e231f800-32bf-11eb-9998-e6faa7a8e80a.png)
well did another semi fresh install and reset the 20.04.1 to the Live USB version, without the extra updates, and here they are. One of this changed the input, most probably the one selected. Ask me for any detail you need.

**Comment by mike-fabian** [comment]
OK, I can reproduce this. After doing 
```
sudo apt update
sudo apt upgrade
sudo reboot
```

I see the same problem as you. The dead key preview only works if I add a "real" input method like ibus-typing-booster.
And input methods don't work in the search entry anymore.

**Comment by TheJoigoMan** [comment]
![image](https://user-images.githubusercontent.com/75008901/100659920-4fc14100-331f-11eb-9309-49c989370518.png)
This is my env and ps aux before updating im-config.
![image](https://user-images.githubusercontent.com/75008901/100660403-fa396400-331f-11eb-9d35-95482c072e67.png)
![image](https://user-images.githubusercontent.com/75008901/100661372-62d51080-3321-11eb-9869-5ee50e47faa0.png)

Sadly, I tried to uncheck both Input Method and Language support to install everything else, but the language support got installed anyway, and it seems it broke the search box dead keys again. But Input Method, which is im-config, didn't update and is the only thing left to update, and the preedits are still working. The image shows it tries to eliminate some kernels which I don't know if have something to do with the problem. The actual im-config version is im-config 0.44-1ubuntu1 and it wants to update to im-config 0.44-1ubuntu1.3.
![image](https://user-images.githubusercontent.com/75008901/100661021-d7f41600-3320-11eb-8010-72a530e7338b.png)
![image](https://user-images.githubusercontent.com/75008901/100661033-dcb8ca00-3320-11eb-984a-5ef1d5d202c8.png)
![image](https://user-images.githubusercontent.com/75008901/100661042-e17d7e00-3320-11eb-91f9-c75c4e1a99c1.png)
![image](https://user-images.githubusercontent.com/75008901/100661059-e93d2280-3320-11eb-96e7-e36a3b54659f.png)
Here the source packages:
https://launchpad.net/ubuntu/+source/im-config/0.44-1ubuntu1
https://launchpad.net/ubuntu/+source/language-selector/0.204
Here the update packages:
https://launchpad.net/ubuntu/+source/im-config/0.44-1ubuntu1.3
https://launchpad.net/ubuntu/+source/language-selector/0.204.2

**Comment by TheJoigoMan** [comment]
![image](https://user-images.githubusercontent.com/75008901/100683401-4bf4e500-3346-11eb-90b3-080cb60ca8e1.png)
This is the ps aux and env without any install, with everything working including the search box and the dead keys preedit.
Can see some differences.
My sudo apt-get upgrade results:
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libfprint-2-tod1
Use 'sudo apt autoremove' to remove it.
The following packages will be upgraded:
  accountsservice alsa-ucm-conf alsa-utils apport apport-gtk aptdaemon
  aptdaemon-data base-files bind9-dnsutils bind9-host bind9-libs bolt bsdutils
  busybox-initramfs busybox-static ca-certificates cheese cheese-common
  command-not-found cpp-9 distro-info-data enchant-2 evolution-data-server
  evolution-data-server-common fdisk file-roller firefox fonts-noto-mono
  fonts-opensymbol gcc-10-base gcc-9-base gdb gdbserver gdm3 ghostscript
  ghostscript-x gir1.2-accountsservice-1.0 gir1.2-gdm-1.0
  gir1.2-gnomebluetooth-1.0 gir1.2-gweather-3.0 gir1.2-javascriptcoregtk-4.0
  gir1.2-mutter-6 gir1.2-nm-1.0 gir1.2-nma-1.0 gir1.2-packagekitglib-1.0
  gir1.2-snapd-1 gir1.2-webkit2-4.0 gnome-bluetooth gnome-control-center
  gnome-control-center-data gnome-control-center-faces gnome-initial-setup
  gnome-shell gnome-shell-common gnome-shell-extension-desktop-icons
  gstreamer1.0-packagekit im-config initramfs-tools initramfs-tools-bin
  initramfs-tools-core intel-microcode krb5-locales language-selector-common
  language-selector-gnome libaccountsservice0 libasound2 libasound2-data
  libatopology2 libblkid1 libbrotli1 libc-bin libc6 libc6-dbg libcamel-1.2-62
  libcc1-0 libcheese-gtk25 libcheese8 libcryptsetup12 libcurl3-gnutls libcurl4
  libdns-export1109 libebackend-1.2-10 libebook-1.2-20 libebook-contacts-1.2-3
  libecal-2.0-1 libedata-book-1.2-26 libedata-cal-2.0-1 libedataserver-1.2-24
  libedataserverui-1.2-2 libefiboot1 libefivar1 libegl1 libenchant-2-2
  libexif12 libfdisk1 libfprint-2-2 libfprint-2-tod1 libfreerdp-client2-2
  libfreerdp2-2 libfreetype6 libgcc-s1 libgdm1 libgl1 libgles2 libglvnd0
  libglx0 libgnome-bluetooth13 libgnutls30 libgomp1 libgs9 libgs9-common
  libgssapi-krb5-2 libgssdp-1.2-0 libgupnp-1.2-0 libgweather-3-16
  libgweather-common libinput-bin libinput10 libisc-export1105
  libjavascriptcoregtk-4.0-18 libjuh-java libjurt-java libk5crypto3 libkrb5-3
  libkrb5support0 libldap-2.4-2 libldap-common libldb2 liblzma5 libmaxminddb0
  libmount1 libmutter-6-0 libmysqlclient21 libnetplan0 libnm0 libnma0
  libnss-systemd libnss3 libpackagekit-glib2-18 libpam-modules
  libpam-modules-bin libpam-runtime libpam-systemd libpam0g libperl5.30
  libplymouth5 libproxy1-plugin-gsettings libproxy1-plugin-networkmanager
  libproxy1v5 libpulse-mainloop-glib0 libpulse0 libpulsedsp libpython3.8
  libpython3.8-minimal libpython3.8-stdlib libraptor2-0 libreoffice-ogltrans
  libreoffice-pdfimport libreoffice-style-breeze libreoffice-style-colibre
  libreoffice-style-elementary libreoffice-style-tango libridl-java libsane
  libsane-common libsmartcols1 libsmbclient libsnapd-glib1 libsnmp-base
  libsnmp35 libssh-4 libstdc++6 libsystemd0 libuno-cppu3
  libuno-cppuhelpergcc3-3 libuno-purpenvhelpergcc3-3 libuno-sal3
  libuno-salhelpergcc3-3 libunoloader-java libuuid1 libuv1 libvncclient1
  libwbclient0 libwebkit2gtk-4.0-37 libwhoopsie0 libwinpr2-2 libx11-6
  libx11-data libx11-xcb1 linux-firmware memtest86+ mount mutter mutter-common
  netplan.io network-manager network-manager-config-connectivity-ubuntu
  network-manager-gnome packagekit packagekit-tools perl perl-base
  perl-modules-5.30 plymouth plymouth-label plymouth-theme-spinner
  plymouth-theme-ubuntu-text ppp pulseaudio pulseaudio-module-bluetooth
  pulseaudio-utils python3-apport python3-aptdaemon
  python3-aptdaemon.gtk3widgets python3-commandnotfound python3-cryptography
  python3-cupshelpers python3-distupgrade python3-gdbm python3-lib2to3
  python3-problem-report python3-software-properties python3-urllib3 python3.8
  python3.8-minimal rfkill rhythmbox-plugin-alternative-toolbar rsyslog
  samba-libs sane-utils simple-scan snapd software-properties-common
  software-properties-gtk spice-vdagent sudo system-config-printer
  system-config-printer-common system-config-printer-udev systemd systemd-sysv
  systemd-timesyncd thermald tzdata ubuntu-desktop ubuntu-desktop-minimal
  ubuntu-minimal ubuntu-release-upgrader-core ubuntu-release-upgrader-gtk
  ubuntu-standard unattended-upgrades uno-libs-private ure util-linux
  uuid-runtime vino whoopsie xdg-utils xserver-common xserver-xephyr
  xserver-xorg-core xserver-xorg-legacy xwayland xz-utils
  yaru-theme-gnome-shell yaru-theme-gtk yaru-theme-icon yaru-theme-sound
  zlib1g
269 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/330 MB of archives.
After this operation, 20,2 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
and the GUI:
![image](https://user-images.githubusercontent.com/75008901/100683963-68455180-3347-11eb-9b2d-5ca8c7f6f57a.png)
![image](https://user-images.githubusercontent.com/75008901/100683979-709d8c80-3347-11eb-899c-02180ed02738.png)
![image](https://user-images.githubusercontent.com/75008901/100683994-772c0400-3347-11eb-8180-c0d75ae9b01a.png)
![image](https://user-images.githubusercontent.com/75008901/100684006-7eeba880-3347-11eb-9773-bd98e0994d26.png)
![image](https://user-images.githubusercontent.com/75008901/100684025-857a2000-3347-11eb-992b-d2324ac89efc.png)
![image](https://user-images.githubusercontent.com/75008901/100684037-8ad76a80-3347-11eb-9c28-0753b4817a58.png)
![image](https://user-images.githubusercontent.com/75008901/100684051-91fe7880-3347-11eb-9652-0d6771f3403a.png)
![image](https://user-images.githubusercontent.com/75008901/100684065-9aef4a00-3347-11eb-8f95-787eb1302329.png)
![image](https://user-images.githubusercontent.com/75008901/100684078-a17dc180-3347-11eb-96b4-dca4b370390c.png)
![image](https://user-images.githubusercontent.com/75008901/100684090-a80c3900-3347-11eb-8a71-38df90a94333.png)
![image](https://user-images.githubusercontent.com/75008901/100684103-ae021a00-3347-11eb-92e4-d8ae9d029fb8.png)
![image](https://user-images.githubusercontent.com/75008901/100684116-b35f6480-3347-11eb-82e0-7615cee6efe3.png)
![image](https://user-images.githubusercontent.com/75008901/100684134-b9554580-3347-11eb-8c43-6de8096223e8.png)
![image](https://user-images.githubusercontent.com/75008901/100684140-beb29000-3347-11eb-9c2f-e6cd99b4a9d9.png)
![image](https://user-images.githubusercontent.com/75008901/100684148-c3774400-3347-11eb-851d-d1f4acb3ca09.png)
Couldn't load all the change list, doesn't load and would take an eternity

**Comment by TheJoigoMan** [comment]
> OK, I can reproduce this. After doing
> 
> ```
> sudo apt update
> sudo apt upgrade
> sudo reboot
> ```
> 
> I see the same problem as you. The dead key preview only works if I add a "real" input method like ibus-typing-booster.
> And input methods don't work in the search entry anymore.

Great, now is reproducible and we almost know for sure what is causing it.

**Comment by mike-fabian** [comment]
I now used my Fedora 33 vm again and upgraded it to all the latest packages. Similar to Ubuntu 20.04, the released Version of Fedora 33 shows the dead key preview in gnome-terminal with the Spanish 'es' keyboard layout even if ibus-typing-booster is *not* installed. Upgrading to the latest packages breaks this and adding an input method like ibus-typing-booster is needed to make it work again. So this is the same as in Ubuntu.

But the problem of not being able to input with an input method into the search entry of gnome-shell does not exist in Fedora 33, this still works even  with all updates.

**Comment by mike-fabian** [comment]
I guess that is probably on purpose that ibus is not used when only keyboard layouts are configured and no “real” input methods. In Fedora 32 the behaviour was the same as in Fedora 32 with current updates and Ubuntu 20.04 with current updates, i.e. ibus was not used when only keyboard layouts were configured. Only in the released versions of Fedora 33 and Ubuntu 20.04, ibus was used even when *only* keyboard layouts were configured. This was probably a “bug” which has been “fixed” by the updates, probably a bug in Gnome. 

Takao Fujiwara (main ibus developer) told me that he would prefer if Gnome always used ibus even if only keyboard layouts are configured because the difference in behaviour confuses users. I think so as well. But at the moment it looks like Gnome wants to use ibus only when “real” input methods are configured because then ibus is really required. When only keyboard layouts are required, ibus is optional. I agree, I also think it would be better to always use ibus to avoid the difference in behaviour you reported here.

At the moment you can use two workarounds:

1) Add a “real” input method like ibus-typing-booster, this forces the use of ibus for everything, including the keyboard layouts like "es".

2) Use `export GTK_IM_MODULE=ibus`. Like this:

```
mfabian@katatsumuri:~$ head -11 .profile
# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

export GTK_IM_MODULE=ibus
mfabian@katatsumuri:~$ 
```

I added the line `export GTK_IM_MODULE=ibus`.

Log out of Gnome and log in again.

```
env | grep ibus
```

should now show that `GTK_IM_MODULE=ibus` is set and the dead key preview should work even  if you have only keyboard layouts and no “real” input methods.

**Comment by mike-fabian** [comment]
About the second problem, input methods don't work in the Gnome search entry, I have no idea what causes this.

I could reproduce that this problem occurs on Ubuntu only after installing the upgrades, but I don't know yet what causes it.

On Fedora 33 with all current updates it still  works.

**Comment by TheJoigoMan** [comment]
> I guess that is probably on purpose that ibus is not used when only keyboard layouts are configured and no “real” input methods. In Fedora 32 the behaviour was the same as in Fedora 32 with current updates and Ubuntu 20.04 with current updates, i.e. ibus was not used when only keyboard layouts were configured. Only in the released versions of Fedora 33 and Ubuntu 20.04, ibus was used even when _only_ keyboard layouts were configured. This was probably a “bug” which has been “fixed” by the updates, probably a bug in Gnome.
> 
> Takao Fujiwara (main ibus developer) told me that he would prefer if Gnome always used ibus even if only keyboard layouts are configured because the difference in behaviour confuses users. I think so as well. But at the moment it looks like Gnome wants to use ibus only when “real” input methods are configured because then ibus is really required. When only keyboard layouts are required, ibus is optional. I agree, I also think it would be better to always use ibus to avoid the difference in behaviour you reported here.
> 
> At the moment you can use two workarounds:
> 
> 1. Add a “real” input method like ibus-typing-booster, this forces the use of ibus for everything, including the keyboard layouts like "es".
> 2. Use `export GTK_IM_MODULE=ibus`. Like this:
> 
> ```
> mfabian@katatsumuri:~$ head -11 .profile
> # ~/.profile: executed by the command interpreter for login shells.
> # This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
> # exists.
> # see /usr/share/doc/bash/examples/startup-files for examples.
> # the files are located in the bash-doc package.
> 
> # the default umask is set in /etc/profile; for setting the umask
> # for ssh logins, install and configure the libpam-umask package.
> #umask 022
> 
> export GTK_IM_MODULE=ibus
> mfabian@katatsumuri:~$ 
> ```
> 
> I added the line `export GTK_IM_MODULE=ibus`.
> 
> Log out of Gnome and log in again.
> 
> ```
> env | grep ibus
> ```
> 
> should now show that `GTK_IM_MODULE=ibus` is set and the dead key preview should work even if you have only keyboard layouts and no “real” input methods.

Thanks for solving it, I'm going to try it now.

**Comment by TheJoigoMan** [comment]
> I guess that is probably on purpose that ibus is not used when only keyboard layouts are configured and no “real” input methods. In Fedora 32 the behaviour was the same as in Fedora 32 with current updates and Ubuntu 20.04 with current updates, i.e. ibus was not used when only keyboard layouts were configured. Only in the released versions of Fedora 33 and Ubuntu 20.04, ibus was used even when _only_ keyboard layouts were configured. This was probably a “bug” which has been “fixed” by the updates, probably a bug in Gnome.
> 
> Takao Fujiwara (main ibus developer) told me that he would prefer if Gnome always used ibus even if only keyboard layouts are configured because the difference in behaviour confuses users. I think so as well. But at the moment it looks like Gnome wants to use ibus only when “real” input methods are configured because then ibus is really required. When only keyboard layouts are required, ibus is optional. I agree, I also think it would be better to always use ibus to avoid the difference in behaviour you reported here.
> 
> At the moment you can use two workarounds:
> 
> 1. Add a “real” input method like ibus-typing-booster, this forces the use of ibus for everything, including the keyboard layouts like "es".
> 2. Use `export GTK_IM_MODULE=ibus`. Like this:
> 
> ```
> mfabian@katatsumuri:~$ head -11 .profile
> # ~/.profile: executed by the command interpreter for login shells.
> # This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
> # exists.
> # see /usr/share/doc/bash/examples/startup-files for examples.
> # the files are located in the bash-doc package.
> 
> # the default umask is set in /etc/profile; for setting the umask
> # for ssh logins, install and configure the libpam-umask package.
> #umask 022
> 
> export GTK_IM_MODULE=ibus
> mfabian@katatsumuri:~$ 
> ```
> 
> I added the line `export GTK_IM_MODULE=ibus`.
> 
> Log out of Gnome and log in again.
> 
> ```
> env | grep ibus
> ```
> 
> should now show that `GTK_IM_MODULE=ibus` is set and the dead key preview should work even if you have only keyboard layouts and no “real” input methods.

Yeah I think that too, I don't understand why would they consider that as something to solve, if they're taking away the extra visual style.

**Comment by TheJoigoMan** [comment]
> About the second problem, input methods don't work in the Gnome search entry, I have no idea what causes this.
> 
> I could reproduce that this problem occurs on Ubuntu only after installing the upgrades, but I don't know yet what causes it.
> 
> On Fedora 33 with all current updates it still works.

I believe it has something to do with the language-selector-gnome or a gnome update that broke it, one of those has a ton of dependent updates.

**Comment by TheJoigoMan** [comment]
Ok so I did 
`sudo gedit ~/.profile` 
and inserted
`export GTK_IM_MODULE=ibus`
as you said and yes, It's now working again. Thank you very much!
Should I be closing this thread or leaving it to solve the second error?

**Comment by mike-fabian** [comment]
```
sudo gedit ~/.profile
```
You don’t need the `sudo` because that file is in your home directory.

**Comment by mike-fabian** [comment]
> Should I be closing this thread or leaving it to solve the second error?

Maybe a new one for the second error?

**Comment by TheJoigoMan** [comment]
Ok I will be closing this thread. The second error was resolved on a distro upgrade.

**Comment by TheJoigoMan** [comment]
Ok I will be closing this thread. The second error was resolved on a distro upgrade.
