### ISSUE TITLE
gtk4 immodule support

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2291]
Hello,

Now GTK 4.0 is out. An input module is needed to be installed for gtk4 to support GTK_IM_MODULE=ibus.

- FYI: https://blog.gtk.org/2018/03/06/input-methods-in-gtk-4/

**Comment by fujiwarat** [comment]
I've been discussing about GTK4 with upstream and and there are still some problems.

1. Control keys cannot be forwarded; https://gitlab.gnome.org/GNOME/gtk/-/issues/3465
2. Lookup window cannot be located; https://gitlab.gnome.org/GNOME/gtk/-/issues/3024#note_987835

> FYI: https://blog.gtk.org/2018/03/06/input-methods-in-gtk-4/

Thanks. But seems the article is a little old.
