### ISSUE TITLE
ibus candidate window missing background

### ISSUE THREAD

**Issue by ricwtk** [ibus/ibus#2295]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Manjaro

Which desktop environment and version?: GNOME 3.38.3

Which session type?: X11

Which application and version?: all application (Firefox 84.0.2 for example) 

IBus version?: 1.5.23

Issue description:
I installed ibus and ibus-libpinyin after a fresh installation of Manjaro with user theme extension enabled. Added the Intelligent Pinyin input method. I'm able to switch to the input method but the selection ui doesn't have any background. Tested with other themes, same issue.

Steps to reproduce:
1. Install ibus and ibus-libpinyin
2. Add Intelligent Pinyin input method
3. Restart
4. Enable user theme (extension)
4. Switch to the input method
5. Try to type anything

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
cannot open ../lua/base.lua: No such file or directory
lua script loaded.
cannot open /home/ricwtk/.config/ibus/libpinyin/user.lua: No such file or directory
open /home/ricwtk/.cache/ibus/libpinyin/user.conf failed.
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by hucuyuu** [comment]
same problem
![image](https://user-images.githubusercontent.com/22560245/105625382-dbf56d80-5e63-11eb-8366-73837752bdb2.png)

**Comment by hucuyuu** [comment]
Hi, ricwtk!

I found this might be a Matcha theme issue, not iBus issue. Any Matcha theme in `Extensions>>User Themes` will cause a candidate background missing problem. But Adwaita themes or gnome-classic themes will not cause the problem.

I think some attributes of `.candidate-box` in `/usr/share/themes/Matcha-*/gnome-shell/gnome-shell.css` might went wrong. But I haven't have time to verify it. 

Here are two temporary solutions for you:
1. Use other themes in `Extensions>>User Themes` 
2. Disable `User Themes` and change your theme in `Tweaks>>Appearance`


![Screenshot from 2021-01-25 01-09-44](https://user-images.githubusercontent.com/22560245/105637773-1a158000-5eaa-11eb-87be-e7479cde3791.png)

**Comment by ricwtk** [comment]
Ok, I agree with you. Somehow the first time I tried, changing the theme didn't solve the problem. But now I can confirm that it's the problem of Matcha shell theme. Other themes seem to work fine now. Thanks. I'll close the issue since it's not the issue with ibus.
