### ISSUE TITLE
Disable preedit for compose key

### ISSUE THREAD

**Issue by kauesena** [ibus/ibus#2302]
Linux 5.10.15-arch1-1
GNOME 3.38ib
X11 or Wayland.
IBus 1.5.23

Before installing [ibus-hangul](https://archlinux.org/packages/community/x86_64/ibus-hangul/), I used en-US keyboard layout with a composition key. The old behaviour was this: after pressing Compose Key (CapsLock in my case) nothing would appear and after completing the key sequence the desired character would be input. Now, after pressing Compose Key I get ⎄ followed by the key sequence. I've understood from the issue #2058 that this is a normal behaviour but I would like to turn it off in my computer because of two things:
- some programs display the composition sequence differently, such as Emacs in the image bellow; and 
- some of the combinations I have defined in .XCompose are just confortable ones and are not mnemonically reasonable, what makes seeing them on screen distracting. 
I did not manage to find a way to prevent ibus from showing the key sequence being typed via `ibus-setup`. How can I reset the old behaviour: no preedit shown? Thanks for your help.

**Comment by kauesena** [comment]
Emacs:
![image](https://user-images.githubusercontent.com/30255100/107852397-42303900-6def-11eb-8bc4-0dd8b31e30ba.png)

In gedit, firefox and vscodium, I get  `⎄;` inline with the cursor placed over `⎄`. In sublime text, I do not get any preview.

**Comment by behrmann** [comment]
I think you might have hit [this](https://gitlab.gnome.org/GNOME/gtk/-/issues/3669) instead of IBus behavious.

**Comment by kauesena** [comment]
It is nice to hear from someone who also finds this behaviour disturbing.

Perhaps you're right regarding the source of the issue. I'm yet far from
really understanding it. But it seems to me that this is in fact GTK
aligning with IBus.

What I manage to understand from reading some issues in the IBus repository
on github and from some comments on posts announcing new IBus features some
time ago is that the exhibition of composition preedit was introduced by
IBus and that there is no way to turn it off in IBus. The developer and
some users seemed even reluctant to the idea of allowing it to be disabled.
It appears that, before I installed ibus-hangul, Gnome wasn't really using
IBus, but xim.

**Comment by behrmann** [comment]
I don't use IBus, yet, so it was quite easy to pinpoint the source of the issue. 

I guess I will need to move to IBus, to keep my compose behaviour, once I finally make the jump to Wayland, but it would really be great, to somehow disable this feature at least in the compose key case.

**Comment by kauesena** [comment]
@behrmann I now believe that you are completely right, that the cause of the change of behaviour lies indeed in the gtk update.

**Comment by kauesena** [comment]
@behrmann Downgrading gtk solved the issue.

**Comment by fujiwarat** [comment]
It's good to try 1.5.25 at least and IBus won't change the preedit feature.

**Comment by kauesena** [comment]
Hi, @fujiwarat. I now use the latest gtk again. I suppose you mentioned trying it again due to it having been slightly changed. 

For anyone who ends up in this issue, I suggest forcing gtk apps to use not its native input method but `xim` or `fcitx`. I'm no longer on Gnome but, if you are, it is possible to change the input method framework from `ibus` to `fcitx` to write in a language like Korean and avoid the interference with the compose key behaviour.

**Comment by fujiwarat** [comment]
> some programs display the composition sequence differently, such as Emacs in the image bellow; and

You just explains the behavior is different.

> some of the combinations I have defined in .XCompose are just confortable ones and are not mnemonically reasonable, what makes seeing them on screen distracting.

I don't see any reasons you need to disable preedit here.

> , it is possible to change the input method framework from ibus to fcitx to write in a language like Korean and avoid the interference with the compose key behaviour.

IBus should work with Korean.

**Comment by kauesena** [comment]
IBus does work with Korean! and very well. I just would not like to have ibus as my default input method when I am writing corean because I interchange Korean and Portuguese in my notes (I'm currently learning the language) and the preedit feature is distracting when I am typing in Portuguese. I found Fcitx allows me to type in Korean too and does not introduce any visual feedback to composition strings (which I personally prefer).

**Comment by kauesena** [comment]
> I don't see any reasons you need to disable preedit here.
Extensive feedback on why that visual response bothers some users is given in the issue mentioned by @behrmann.

**Comment by fujiwarat** [comment]
>  I just would not like to have ibus as my default input method 
> the preedit feature is distracting when I am typing in Portuguese

They are just your feeling and you don't mention what prevent from your typing. 
Please don't refer other IMEs.

**Comment by behrmann** [comment]
Just commenting here to hopefully give some insight because I was mentioned here: 

My problem was not with ibus (which I don't use and don't know the current state of), but with a new preedit feature in GTK, using `⎄` as glyph showing that preedit is on, which was documented [here](https://gitlab.gnome.org/GNOME/gtk/-/issues/3669). 

The GTK people were very forthcoming with a fix and changed the glyph to a center dot, which is very unobtrusive and doesn't noticeably bounce around the letter being composed, unlike `⎄` which pushes the letters around by more than an em, which is quite noticeable, especially in languages with many diacritics like Czech.

**Comment by fujiwarat** [comment]
> The GTK people were very forthcoming with a fix and changed the glyph to a center dot

GTK and IBus 1.5.25 implement the following behavior.
https://blog.gtk.org/2021/03/24/input-revisited/

**Comment by behrmann** [comment]
Yes, this looks like what I'm talking about, although the series of screenshots omits the center dot that is shown once the compose key is pressed and before any diacritic is entered, but I trust you saying that GTK and IBus implement the same behaviour, which is an - in my opinion - good general solution.

**Comment by mike-fabian** [comment]
gtk, ibus, and ibus-typing-booster all implement this so it looks the same in all implementations.

The compose key (Multi_Key) is displayed as a middle dot but disappears again if further keys are  typed. But if the Multi_Key appears somewhere not as teh first key in a longer sequence, it is always shown. The table at the end of this paragraph shows some examples:

https://mike-fabian.github.io/ibus-typing-booster/docs/user/#5_2
