### ISSUE TITLE
German keyboard: dead key for typing "ñ" not working

### ISSUE THREAD

**Issue by maudgalyayana** [ibus/ibus#2310]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Debian 10.8 (64 bit)

Which desktop environment and version?: 
Cinnamon 3.8.8-1

Which session type?: 
X11

Which application and version?: 
Emacs 26.1 (but all applications affected)

IBus version?: 
1.5.19

Issue description:

I can't type "ñ" by typing the dead key "~" and then "n". Previously there used to be a keyboard layout called "German (legacy)" which didn't have this problem. It is now missing. The problem is also described here:
https://bugs.launchpad.net/ubuntu/+source/gnome-control-center/+bug/1277641 ("German keyboard layout loses tilde dead key")

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
No

**Comment by gunnarhj** [comment]
As I mentioned in a comment on that Ubuntu bug report, there is a _German (dead tilde)_ XKB layout nowadays. It's not selectable from version 1.5.19 of `ibus-setup`, but that was fixed in version 1.5.23.

**Comment by maudgalyayana** [comment]
Thank you for comment.

It is possible to add the _German_ (_dead tilde_) XKB layout to version 1.5.19 of ibus somehow? Version 1.5.23 and higher are only available in Debian unstable.

**Comment by maudgalyayana** [comment]
E.g. by adding the keymap file.

**Comment by mike-fabian** [comment]
> Thank you for comment.
> 
> It is possible to add the _German_ (_dead tilde_) XKB layout to version 1.5.19 of ibus somehow? Version 1.5.23 and higher are only available in Debian unstable.

Add this

```
        <engine>
            <name>xkb:de:deadtilde:deu</name>
            <language>de</language>
            <license>GPL</license>
            <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
            <layout>de</layout>
            <layout_variant>deadtilde</layout_variant>
            <longname>German (dead tilde)</longname>
            <description>German (dead tilde)</description>
            <icon>ibus-keyboard</icon>
            <rank>1</rank>
        </engine>
```

to 

```
/usr/share/ibus/component/simple.xml
```

That file ends with:

```
      ...
	</engine>
    </engines>
</component>
```

Change this part to:

```
      ...
      </engine>
       <engine>
            <name>xkb:de:deadtilde:deu</name>
            <language>de</language>
            <license>GPL</license>
            <author>Peng Huang &lt;shawn.p.huang@gmail.com&gt;</author>
            <layout>de</layout>
            <layout_variant>deadtilde</layout_variant>
            <longname>German (dead tilde)</longname>
            <description>German (dead tilde)</description>
            <icon>ibus-keyboard</icon>
            <rank>1</rank>
        </engine>
    </engines>
</component>
```

Then restart your Gnome session.

**Comment by maudgalyayana** [comment]
@mike-fabian 
Thank you very much! I added your code in the German keyboard section of the file you mentioned. It works perfectly. Have a nice day/evening!

Schöne Grüße aus Österreich :)
