### ISSUE TITLE
Add Map GTK_INPUT_HINT_PRIVATE to ibus

### ISSUE THREAD

**Issue by makotokato** [ibus/ibus#2315]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: Debian/sid
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: GNOME 3
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: all
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: all
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.24
(Run `ibus version`)

Issue description:
I requested new hint (`GTK_INPUT_HINT_PRIVATE `) as private/incognito mode on Web Browser (https://gitlab.gnome.org/GNOME/gtk/-/commit/3cf8904d0bf7549644c912ece587426829290735). But `IBusInputHints` doesn't still map to this value.  Please add `IBUS_INPUT_HINT_PRIVATE` for  `GTK_INPUT_HINT_PRIVATE`.

The detail of this value is https://gitlab.gnome.org/GNOME/gtk/-/issues/2261

**Comment by fujiwarat** [comment]
Seems the private hint was added to GTK4 only.

I think you also might like to report the issue to wayland-protocols for GNOME Wayland
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/issues/79
