### ISSUE TITLE
I need to exit and restart ibus-daemon to make ibus-chewing work.

### ISSUE THREAD

**Issue by laichiaheng** [ibus/ibus#2319]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
ArchLinux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 40.0.0

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Every application.

IBus version?: 
(Run `ibus version`)
IBus 1.5.24

Issue description:
Can't input any letter other than English.

Steps to reproduce:
1. Try to input Chinese or Japanese with ibus-chewing and ibus-mozc.
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
No

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
```
(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.438: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.448: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.458: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.464: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
ibus-chewing-Message: 22:43:48.465: * enable(): statusFlags=15

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
ibus-chewing-Message: 22:43:48.465: ***** set_capabilities(29): statusFlags=17
ibus-chewing-Message: 22:43:48.465: * focus_out(): statusFlags=17
ibus-chewing-Message: 22:43:48.465: * focus_in(): statusFlags=3

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.465: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
ibus-chewing-Message: 22:44:02.491: * reset
ibus-chewing-Message: 22:44:02.491: * focus_out(): statusFlags=17
ibus-chewing-Message: 22:44:02.492: * focus_in(): statusFlags=3

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:02.492: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:02.492: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:02.493: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:02.493: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
ibus-chewing-Message: 22:44:04.666: * focus_out(): statusFlags=17
ibus-chewing-Message: 22:44:04.666: * focus_in(): statusFlags=3

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:04.667: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:04.667: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:04.667: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:04.667: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
ibus-chewing-Message: 22:44:16.476: * reset
ibus-chewing-Message: 22:44:16.476: * focus_out(): statusFlags=17
ibus-chewing-Message: 22:44:16.477: * focus_in(): statusFlags=3

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:16.478: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:16.478: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:16.478: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:16.478: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
ibus-chewing-Message: 22:44:19.331: * focus_out(): statusFlags=17
ibus-chewing-Message: 22:44:19.332: * focus_in(): statusFlags=3

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:19.332: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:19.332: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:19.332: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

(ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:44:19.332: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

**Comment by laichiaheng** [comment]
Nobody knows what's happening? IBus is useless on Wayland.

**Comment by boogiefromzk** [comment]
For me I have to restart each time I switch language programmatically and after some time it makes system slow and stops working smoothly, until I totally stop and then after some time start ibus daemon.
On X11 + xfce4.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.
Did you try GNOME Xorg?

**Comment by laichiaheng** [comment]
@laichiaheng It happens on Gnome Wayland instead of Gnome Xorg.

**Comment by fujiwarat** [comment]
> Why does it happens to Gnome Wayland but not Gnome Xorg?

Not sure about your problem.

> (ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.438: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed

Seems you have a problem about the scaling. Can you reproduce your problem when you set the display scale to 100% using `gnome-control-center display` ?

How about using ibus-hangul or ibus-anthy?

Can you run the following a.py script?
```
% cat a.py

from gi import require_version as gi_require_version
gi_require_version('Gtk', '3.0')
from gi.repository import Gtk
import sys
Gtk.init(sys.argv)
im_context = Gtk.IMMulticontext()
(string, attrs, cursor_pos) = im_context.get_preedit_string()
im_context_id = im_context.get_context_id()
print(im_context_id)

% python3 a.py
```

**Comment by laichiaheng** [comment]
> > Why does it happens to Gnome Wayland but not Gnome Xorg?
> 
> Not sure about your problem.
> 
> > (ibus-engine-chewing:6446): Gtk-CRITICAL **: 22:43:48.438: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
> 
> Seems you have a problem about the scaling. Can you reproduce your problem when you set the display scale to 100% using `gnome-control-center display` ?
> 
> How about using ibus-hangul or ibus-anthy?
> 
> Can you run the following a.py script?
> 
> ```
> % cat a.py
> 
> from gi import require_version as gi_require_version
> gi_require_version('Gtk', '3.0')
> from gi.repository import Gtk
> import sys
> Gtk.init(sys.argv)
> im_context = Gtk.IMMulticontext()
> (string, attrs, cursor_pos) = im_context.get_preedit_string()
> im_context_id = im_context.get_context_id()
> print(im_context_id)
> 
> % python3 a.py
> ```

What does the script do?

**Comment by fujiwarat** [comment]
> What does the script do?

The script shows the current gtk-im-context with print()

Seems you don't reply about the scaling.

**Comment by laichiaheng** [comment]
> > What does the script do?
> 
> The script shows the current gtk-im-context with print()
> 
> Seems you don't reply about the scaling.

I am at 100% screen scaling.

**Comment by fujiwarat** [comment]
> I am at 100% screen scaling.

I see.
Did you get the result of my script?

> Do I need to switch to ibus-chewing to run that script?

Your script just restart ibus-daemon and you can choose by yourself whether you need to switch or not.

**Comment by laichiaheng** [comment]
@fujiwarat Wait, there is an issue, if I open Gnome Terminal, the input method will start to work. Does that affect the result?

**Comment by fujiwarat** [comment]
> if I open Gnome Terminal, the input method will start to work.

Because you run your XDG autostart script? I don't understand your issue.

> The result:
> wayland

OK, looks good. It means your application contacts ibus via GNOME Wayland but you have a problem between applications and GNOME Wayland.

**Comment by laichiaheng** [comment]
> Because you run your XDG autostart script? I don't understand your issue.
> 
No, the input method is activated without my autostart script. After I open Gnome Terminal, I can input Chinese with ibus-chewing.

**Comment by fujiwarat** [comment]
So your problem is fixed unexpectedly?
I think ibus-anthy also should work if ibus-chewing works.

**Comment by laichiaheng** [comment]
> So your problem is fixed unexpectedly? I think ibus-anthy also should work if ibus-chewing works.

No, it will not work again after I reboot PC, I need to open Gnome Terminal/XWayland apps every time.

**Comment by fujiwarat** [comment]
> I think that libpinyin does not have the problem, because ibus-libzhuyin is based on ibus-libpinyin.

If ibus-libpinyin works, ibus-anthy and ibus-hangul should work too. Seems ibus-chewing specific.

> No, it will not work after I reboot PC, I need to open Gnome Terminal/XWayland apps every time.

So you mean your problem does not happen with gnome-terminal but

> Which application and version?:
> Every application.

Your bug description looks broken. Did you try gedit?

**Comment by laichiaheng** [comment]
> If ibus-libpinyin works, ibus-anthy and ibus-hangul should work too. Seems ibus-chewing specific.

No, ibus-anthy doesn't work either, I don't know how to use ibus-hangul so I didn't try it, and ibus-mozc, ibus-rime, ibus-libzhuyin works perfectly.
  
> So you mean your problem does not happen with gnome-terminal but

It happens to every none Xwayland application except Gnome Terminal.
I'm using Arch Linux, I believe that packages are new enough.

> Your bug description looks broken. Did you try gedit?

Yes.

**Comment by fujiwarat** [comment]
> No, ibus-anthy doesn't work either, I don't know how to use ibus-hangul

OK, I guess you have unexpected setting.
When you run `ibus exit` and `ibus-daemon --verbose &`, do you see any errors with ibus-anthy?

I'd leave many errors of ibus-chewing at the moment..

BTW, you can type Hangul after you type Shift-space key with ibus-hangul.

**Comment by laichiaheng** [comment]
Oops! I remember it wrong, `ibus-anthy` only not work in the Gnome overview search bar, it works without issue in other applications.

**Comment by hiunnhue** [comment]
Hi all, 

I just tried to reproduce on Fedora Livs USB and here is my abervation. 

The main issue is that ibus-chewing seems not activiate properly, until user opens applications that trigger `ibus-x11` or `ibus-extension-gtk3`. Before `ibus-x11` or `ibus-extension-gtk3` appear, `ibus-chewing` won't work although user has switched to it and its icon indeed shows up at the right top corner. 

--

Step 1. 
By default, neither `ibus-x11` nor `ibus-extentions-gtk3` is not activated on Fedora Gnome. So at this step, when a user tries to swtich to ibus-chewing, he/she will actually stay at the original engine.
![Screenshot from 2022-02-19 12-14-34](https://user-images.githubusercontent.com/1015601/154812252-ebf104e2-f780-46bb-b729-bb893299420b.png)

Step 2.
When a user open applications that evoke `ibus-x11` or `ibus-extentions-gtk3`, for example an text editor named Leafpad, then ibus-chewing starts to work. Or we can use the command ``ibus-daemon -drx``.
![Screenshot from 2022-02-19 12-11-27](https://user-images.githubusercontent.com/1015601/154812614-c9766f09-a007-4a50-b11c-c648eb060893.png)

**Comment by fujiwarat** [comment]
>>   No, ibus-anthy doesn't work either, I don't know how to use ibus-hangul
> 
> OK, I guess you have unexpected setting.
> When you run ibus exit and ibus-daemon --verbose &, do you see any errors with ibus-anthy?

**Comment by fujiwarat** [comment]
Ping!
No reply from my query.

**Comment by laichiaheng** [comment]
@fujiwarat Nope.

**Comment by hiunnhue** [comment]
Hi @fujiwarat, 

Here's my result: 
![image](https://user-images.githubusercontent.com/1015601/155817571-e785c4a9-5894-44fd-9a3d-90d216dfc4d9.png)

I would like to correct my description in previous comment.  It looks like `ibus-x11` was not related to this issue, but the `Xwayland`. 

After I restart ibus with `ibus-daemon --verbose` or `ibus-daemon -drx`, the `Xwayland` appears and then `ibus-chewing` is working fine.

**Comment by fujiwarat** [comment]
> But something weird happened, I tried to type @, but it showed me ".

You have to set your keymap before you switch the engine to anthy because ibus-anthy does not have any keymaps but inherit the current session layout.
Seems you use ibus-anthy with the wrong usage and ibus-anthy should work.

I think your issue is in ibus-chewing only and this does not treat ibus-chewing.

**Comment by fujiwarat** [comment]
Probably I think you could try ibus-libzhuyin.

**Comment by laichiaheng** [comment]
@fujiwarat I have found a replacement, ibus-rime.
