### ISSUE TITLE
Within terminal, how can I change input method for browser?

### ISSUE THREAD

**Issue by loynoir** [ibus/ibus#2321]
# Question
Within terminal, how can I change input method for browser?

# Term
input method:
* gnome settings seems call it input source
* ibus cli seems call it input engine
* I might call it input method

# Settings
gnome settings > keyboard > `switch input sources individually for each window`

# Environment
Which distribution and version?: Arch Linux

Which desktop environment and version?:  GNOME

Which session type?: wayland

Which application and version?: firefox

IBus version?: 1.5.24

# Things I have tried within terminal
Both make changes only within terminal, browser no effect.
1. 
```sh
ibus engine rime
```
2. convert `/proc/$(pgrep firefox)/environment` to env.sh in format of 'export A=B'
```sh
(source env.sh; ibus engine rime)
```

# Things not related to question
<details>
<summary>may found a bug or feature</summary>
<pre><code>
$ ibus engine
A
$ # <Typing>using engine A</Typing>
$ ibus engine B
$ # <Typing>using engine B</Typing>
$ # switch to browser using engine A, and switch back to this terminal

$ # Expect typing is using engine B
$ # <Typing>using engine A</Typing>
</code></pre>
</details>

**Comment by fujiwarat** [comment]
I think it's good to just use Super-space key to switch IMEs.

I have no idea to perform your idea.
I think you wish to change IME with getting focus events but not launching firefox.
gnome-terminal loads your shell with focus events and you could configure your idea with the custom shell but firefox does not have such a feature.
