### ISSUE TITLE
Method to add new xkb layouts without modifying simple.xml

### ISSUE THREAD

**Issue by zyxw59** [ibus/ibus#2322]
I use the [`ibus`](https://archlinux.org/packages/extra/x86_64/ibus/) package on Arch Linux. I have created a custom xkb keyboard layout, which I use in addition to some other layouts provided by ibus. In order for ibus to recognize my xkb layout, I must manually add an entry to simple.xml. However, because that file is provided by the ibus package, whenever I update ibus, it gets overwritten, and I must re-add my entry.

Would it be possible to add a method to configure additional xkb layouts which does not require editing this file directly?

**Comment by zyxw59** [comment]
Apparently I can add another file in the same directory with the same format with just the additional entries and ibus includes them.

**Comment by zyxw59** [comment]
Actually, reopening this, since that solution no longer appears to work :slightly_frowning_face:

**Comment by fujiwarat** [comment]
You can modify evdev.xml file which is installed as /usr/share/X11/xkb/rules/evdev.xml in Fedora and simple.xml could be re-genarated by ibus/engine/gensimple.py .

**Comment by zyxw59** [comment]
I don't use Fedora. On Arch Linux, that file owned by the [`xkeyboard-config`](https://archlinux.org/packages/extra/any/xkeyboard-config/) package, so I'd just run into the same issue whenever that package updates. Additionally, if I still have to run `gensimple.py` after updating, I may as well just manually edit `simple.xml` myself.

**Comment by fujiwarat** [comment]
I think you could copy evdev.xml to your build environment?

**Comment by fujiwarat** [comment]
>  if I still have to run gensimple.py after updating, I may as well just manually edit simple.xml myself.

It's up to you.

**Comment by zyxw59** [comment]
> I think you could copy evdev.xml to your build environment?

what "build environment"? I don't manually build ibus, I use the package in the Arch Linux repository.

**Comment by fujiwarat** [comment]
>  I use the package in the Arch Linux repository.

I think you can copy the file during the packaging.

**Comment by zyxw59** [comment]
I am not packaging anything myself, I am just installing the existing package with `pacman`.

My goal here is to be able to add my keyboard layout exactly once, when installing on a new computer, and then never have to worry about updating it. Any solution where I have to take any steps when upgrading `ibus` beyond running `pacman -Syu` does not resolve this issue. If you aren't interested in that, fine, but I'd like it if you'd just say so.

**Comment by habazut** [comment]
So what is the method to add a keyboard variant to ibus when the variant is recognized as keyboard map? After creating the variant "personal" of keyboard "se" I can do `setxkbdmap se personal` but what do I do in the ibus dialog to get the same result?

Regards,
Harald

**Comment by fujiwarat** [comment]
> "personal" of keyboard "se" I can do setxkbdmap se personal but what do I do in the ibus dialog to get the same result?

My understanding is, xkeyboard-config now provides "custom" layout for that purpose.
