### ISSUE TITLE
Hong Kong Traditional Chinese support

### ISSUE THREAD

**Issue by windowsboy111** [ibus/ibus#2323]
<Versions and stuff doesn't matter>

Issue description:
There is an issue that frustrated me for long. Tried to type 着 using scj (basically Cangjie) with `廿手月山` (aka. `tqbu`) and it didn't work, until I realised that this word is listed as a Simplified Chinese word.
The thing is, it isn't.
The word 著 in Hong Kong is considered a wrong word. 着 is the correct word. However, 著 is used in Taiwan. Guess what happens? They thought Taiwan Chinese is Traditional Chinese, which is totally wrong. I don't blame on them because it's such a common misconception.
If you think 'twas the only exception: no, I haven't talked about 只, 云 (in 人云亦云, 人雲亦雲 is incorrect), and so many other words/characters.
This is not an exception, because Hong Kong Chinese is not Taiwan Chinese.

Steps to reproduce:
1. Add Cangjie to the input method list
2. Set the filter to Traditional first / Traditional only
3. Type `rc`. Find 只.
4. Type `mmi`. Find 云.
5. Type `rmnd`. 𭉝 doesn't appear. (Jyutping: syu4, Cantonese of "shh", same as 噓 in Guoyu / Mandarin.)

**Comment by mike-fabian** [comment]
For 只 I fixed this yesterday, see https://github.com/kaio/ibus-table/issues/74

The fix for 只 is included in the 1.13.2 release of ibus-table: https://github.com/kaio/ibus-table/releases/tag/1.13.2

**Comment by windowsboy111** [comment]
Thank you, Mike! I hope other characters apart from 只, including 着(tqbu) 云(mmi) 𭉝(rmnd) 枱(dir) and more, are fixed soon!

**Comment by mike-fabian** [comment]
For 着 see:

https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E7%9D%80

You find there at “Variants”

kTraditionalVariant  U+8457 著

As 着 is used in Hongkong, it is not only simplified Chinese but also traditional Chinese.
So the entry in the Unihan database for this character is wrong, it should look like:

kTraditionalVariant  U+7740 着  U+8457 著

For example, 面 has this entry in the Unihan database:

https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E9%9D%A2

kSimplifiedVariant 	U+9762 面
kTraditionalVariant 	U+9762 面 U+9EB5 麵

I.e. there is a traditonal variant U+9EB5 麵 listed but the character U+9762 面 is repeated in the list of traditonal variants, that means U+9762 面 is itself a tradtional character as well.

**Comment by mike-fabian** [comment]
> Thank you, Mike! I hope other characters apart from 只, including 着(tqbu) 云(mmi) 𭉝(rmnd) 枱(dir) and more, are fixed soon!

Just send me all you think are wrong and I’ll fix it.

**Comment by windowsboy111** [comment]
著　着
檯　枱
雲　云
　　𭉝 (Untypable)        Cantonese only
　裡　 (Untypable in S) used in all places, same meaning as 裏
　復　 (Untypable in S) used in all places, same meaning in S, diff in T
　采　 (Untypable in T) used in Hong Kong, not sure about TW
　　吓 (Untypable in T) used in Cantonese.
　　尸 (Untypable in T) idk where it is used, but Cangjie has that as a radical.
搵　揾

There may be more, but I can't think of them.

**Comment by mike-fabian** [comment]
Thank you, I am working on it ...

**Comment by mike-fabian** [comment]
> Type rmnd. 𭉝 doesn't appear. (Jyutping: syu4, Cantonese of "shh", same as 噓 in Guoyu / Mandarin.)

This seems to be a different problem.

You say you use scj, i.e. you are using this table:

https://github.com/definite/ibus-table-chinese/blob/master/tables/scj/scj6.txt

But this table does not contain rmnd. 𭉝

**Comment by windowsboy111** [comment]
Oh yeah, this doesn't exist in Cangjie either. Neither tables contain the word. I guess this is a separate issue.

**Comment by mike-fabian** [comment]
> Type rmnd. 𭉝 doesn't appear. (Jyutping: syu4, Cantonese of "shh", same as 噓 in Guoyu / Mandarin.)

This seems to be a different problem.

You say you use scj, i.e. you are using this table:

https://github.com/definite/ibus-table-chinese/blob/master/tables/scj/scj6.txt

But this table does not contain rmnd. 𭉝

**Comment by mike-fabian** [comment]
We could easily add it to the scj6.txt table.

**Comment by windowsboy111** [comment]
Yeah, ignore that for the moment.

**Comment by windowsboy111** [comment]
Thank you so much.

**Comment by mike-fabian** [comment]
枱 should work already, i.e. it should already be classified as both simplified **and** traditional. 
Because:

https://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=%E6%9E%B1

shows only: 

kSemanticVariant   U+5113 儓U+6AAF 檯

in the Variants section, there is neither an entry for kTraditionalVariant nor for kSimplifiedVariant.
If a character has neither kTraditionalVariant nor kSimplifiedVariant, ibus-table considers it as both, simplified and traditional.

**Comment by mike-fabian** [comment]
And I can type it already using the scj6 table. The scj6 table contains:

```
dir	檯	500
dir	枱	499
```
When I use traditional Chinese mode I get them both, when I use simplified Chinese mode I get only 枱	when typing 'dir'.

檯 U+6AAF has this entry in Unihan_Variants.txt:

```
U+6AAF	kSimplifiedVariant	U+53F0
```

Therefore it is detected as traditional only and not shown when ibus-table uses simplified only mode.

**Comment by mike-fabian** [comment]
![Screenshot](https://user-images.githubusercontent.com/2330175/121380561-4277b580-c945-11eb-80b6-d236303835a3.png)

**Comment by mike-fabian** [comment]
In case you are using Fedora you could try these builds:

https://copr.fedorainfracloud.org/coprs/mfabian/ibus-table/builds/

**Comment by mike-fabian** [comment]
This release contains the fix: https://github.com/kaio/ibus-table/releases/tag/1.13.3

**Comment by WhiteCzar** [comment]
Hey. Sorry to resurrect a closed issue. But are you sure 揾 is used in Trad Chinese? Seems rather unlikely to me. But anyways, if it's used in Hong Kong, then I guess 温 must also be used there? But it's also not possible to type with traditional cangjie only. So perhaps you should take a look at it as well.

**Comment by WhiteCzar** [comment]
There's also 藴

**Comment by windowsboy111** [comment]
I have been writing 温 with 日 but not 囚 for years and I have never seen anyone writing 溫.
Though things can get complicated when 戶 is used in computers but everyone here writes 户. 戶 is wrong word (錯字).

**Comment by windowsboy111** [comment]
And it's same for 揾, 藴, 蕰, and more.

**Comment by windowsboy111** [comment]
The thing about this is that when type 木戈口 I get 檯 as the first result (Trad. Chinese). In my opinion, I should get 枱 as the first candidate because supposedly I asked for 枱, not 檯. They are different, and 檯 really shouldn't appear in the first place.

**Comment by mike-fabian** [comment]
木戈口 = dir

You said you are using the scj6 table:

```
$ grep '枱\|檯' scj6.txt 
dgg     檯      499
dggs    檯      500
dgrg    檯      500
dgz     檯      494
dir     檯      500
dir     枱      499
dirs    枱      500
drz     檯      451
drz     枱      448
ztoi    檯      491
ztoi    枱      481
```
This table has 檯 with higher priority (500) than 枱 (499). I don’t know why the author of the table did this.

It is like that in the scj6.txt table since the first commit:

```
commit fa2654a88f25a682f43d29067107f2255d393296
Author: Caius 'kaio' Chance <k@kaio.me>
Date:   Tue Apr 6 11:41:54 2010 +1000

    First commit.
    Cloned from ibus-table-cangjie project: http://github.com/kaio/ibus-table-cangjie.
    Cloned from ibus-table-cantonese project: http://github.com/kaio/ibus-table-cantonese.
```

The two links  http://github.com/kaio/ibus-table-cangjie and
http://github.com/kaio/ibus-table-cantonese don’t exist anymore.

Is there some standard how the scj6.txt table should be and we can make it agree to that standard?

We can also just fix

``
dir     檯      500
dir     枱      499
```

The other cangjie tables have this:

```
$ grep '枱\|檯' cangjie*.txt 
cangjie-big.txt:dgrg    檯      1000
cangjie-big.txt:dir     枱      1000
cangjie3.txt:dgrg       檯      500
cangjie3.txt:dir        枱      10
cangjie5.txt:dgrg       檯      1000
cangjie5.txt:dir        枱      1000
```

I plan to add a GUI option to enable dynamic input if the use chooses
it.  Currently DYNAMIC_ADJUST is FALSE for all cangjie tables and it
can only be changed by editing and recompiling the table.

Usually that is a good thing because one wants a fixed position for the candidates when using cangjie to be able to type without looking at the candidate table popping up.

But it might be useful in some cases to have an option to switch on DYNAMIC_ADJUST from the setup tool GUI.

See also: https://github.com/definite/ibus-table-chinese/pull/14

Shall we fix

```
dir     檯      500
dir     枱      499
```

in the scj6 table?

**Comment by windowsboy111** [comment]
I am not sure if we should fix this. This issue was about HK Trad. support but alongside that we fixes other things. Apparently we are going to continuously find more and more characters to fix. Seems to be a long term issue.
I am also unaware of a rule that makes 檯 prioritised.

**Comment by mike-fabian** [comment]
If  we want to change the scj6 table we should open a new issue at https://github.com/definite/ibus-table-chinese/

> I am also unaware of a rule that makes 檯 prioritised.

You mean you are unaware of a rule in some standard?

That it is prioritized  over 枱 when using scj6 is only because the number in the 3rd column in scj6.txt is higher.

We could change that, but as you say changes might be necessary for many characters.

So the best case would be if there is some official specification of the priorities when using scj6, then we could change our table to agree with such a specification.

**Comment by WhiteCzar** [comment]
It sure is weird that 檯 appears is sjc6 for the `dir` code. Because the right code for that character is `dgrg`. At least that's how it is in cangjie5.

**Comment by WhiteCzar** [comment]
> I have been writing 温 with 日 but not 囚 for years and I have never seen anyone writing 溫.
> Though things can get complicated when 戶 is used in computers but everyone here writes 户. 戶 is wrong word (錯字).

I think this has to do more with fonts. As far as I'm aware those two characters are unified as different variants of one character in Unicode. Or am I wrong?

**Comment by mike-fabian** [comment]
> I think this has to do more with fonts. As far as I'm aware these two characters (戶 and 户) are unified as different variants of one character in Unicode. Or am I wrong?

They are not unified:

户 U+6237 CJK IDEOGRAPH-6237
戶 U+6236 CJK IDEOGRAPH-6236

If that had something to do with fonts, they would look the same for you in this github comment here because they are not tagged somehow to be displayed with different fonts.

**Comment by mike-fabian** [comment]
> If we want to change the scj6 table we should open a new issue at https://github.com/definite/ibus-table-chinese/

The upstream of ibus-table-chinese is now here:

https://github.com/mike-fabian/ibus-table-chinese/

If you want to report issues about the scj6 table or other Chinese tables, please report them here:

https://github.com/mike-fabian/ibus-table-chinese/issues
