### ISSUE TITLE
Pressing the Super key deletes the active syllable in ibus-hangul

### ISSUE THREAD

**Issue by Silejonu** [ibus/ibus#2333]
Which distribution and version?: 
Arch Linux / Fedora 34

Which desktop environment and version?: 
GNOME 40.3.0

Which session type?: 
Wayland and X11

Which application and version?: 
Any

IBus version?: 
1.5.24

Issue description:
Active syllable is being removed when hitting the Super key on GNOME. This is especially problematic as the default shortcut to switch input source is Super+Space, and as such, the last inputted syllable is constantly getting removed when switching to another layout.
Can not reproduce on elementary OS's Pantheon.

Steps to reproduce:
1. Type a word using ibus-hangul (ex: 한글 [ㅎ+ㅏ+ㄴ]+[ㄱ+ㅡ+ㄹ])
2. Press the Super key, alone or as part of a keyboard shortcut (ex: the default GNOME shortcut to switch input methods: Super+Space)
3. The syllable that's currently being inputted (in this example, 글) is deleted

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
Seems Super key deletes the preedit text in GNOME desktop.
I think you can change the IME switcher shortcut key to Ctrl-space or else with `gnome-control-center` or change overview shortcut key to Right Super with `gnome-tweaks` -> "Keyboard & Mouse" -> "Overview Shortcut" ?
