### ISSUE TITLE
ibus does not properly implement GtkIMContext::reset

### ISSUE THREAD

**Issue by matthiasclasen** [ibus/ibus#2334]
This was observed on a Fedora 34 system:

1. I start typing in a GTK4 GtkTextView, and produce some preedit.
2. Clicking around, the preedit moves around with cursor.
3. Closing the window, the same preedit text pops up in the terminal

GTK calls gtk_im_context_reset() as soon as I click in 2., but IBus does not seem to actually reset its state.

This does not happen with GtkIMContextSimple.

**Comment by fujiwarat** [comment]
Thank you for the issue. Now I can reproduce your issue and will push the patch next week.
The patch have to be applied to client/gtk3/ibusimcontext.c and client/gtk4/ibusimcontext.c besides client/gtk2/ibusimcontext.c
