### ISSUE TITLE
Wrong candidate window position in 1.5.25

### ISSUE THREAD

**Issue by zhmars** [ibus/ibus#2337]
Which distribution and version?: 

`Arch Linux`

Which desktop environment and version?: 

`GNOME 40.4`

Which session type?: 

`X11`

Which application and version?: 

- gedit 40.1
- chromium 92.0.4515.159

IBus version?: 

`1.5.25`

Issue description:

After upgrade to `1.5.25`, the candidate window appears at the bottom of application window instead of following the cursor position. Similar issue was reported at [here](https://bugs.archlinux.org/task/71881). It seems https://github.com/ibus/ibus/commit/a823161768c8f6916dbdebe73842a9fc04521369 is the first bad commit.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

`yes`

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

`no`

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

`yes`

**Comment by IsSkyfalls** [comment]
I think this bug affects all gtk applications. In qt based ones it works as intended.
Tested on arch+kde+firefox and vivaldi(both using gtk3) with ibus 1.15.25, the candidate selection window is always offsetted from the actual cursor for a certain distance. 1.15.24 works as intended.
The bug is can be reproduced by updating to 1.15.25 and relog/reboot.

**Comment by AlynxZhou** [comment]
reproduced with gnome-terminal/firefox/chrome, gnome-shell not updated so it seems ibus report wrong position?

**Comment by AlynxZhou** [comment]
I tried to build a package that revert https://github.com/ibus/ibus/commit/a823161768c8f6916dbdebe73842a9fc04521369 with patch -R, seems not fix it, so maybe other commit leads into this bug...

**Comment by AlynxZhou** [comment]
emm, bisect said https://github.com/ibus/ibus/commit/a823161768c8f6916dbdebe73842a9fc04521369 is the first bad commit, but it seems only revert it does not fix.

**Comment by dongsibo** [comment]
@AlynxZhou Hm, applying a patch to revert just a823161 works for me on Arch Linux.

**Comment by AlynxZhou** [comment]
> @AlynxZhou Hm, applying a patch to revert just [a823161](https://github.com/ibus/ibus/commit/a823161768c8f6916dbdebe73842a9fc04521369) works for me on Arch Linux.

How did you revert it? I test again and still not work.

**Comment by AlynxZhou** [comment]
emm, I cleaned packaging dir and it works now, interesting

**Comment by AlynxZhou** [comment]
> @AlynxZhou Hm, applying a patch to revert just [a823161](https://github.com/ibus/ibus/commit/a823161768c8f6916dbdebe73842a9fc04521369) works for me on Arch Linux.

I know my problem, `makepkg -si` runs `prepare()` and gives a lot of output and I think it just finished packaging again, but in fact it did not and just show a warning that will install the previous package...

**Comment by AlynxZhou** [comment]
https://github.com/ibus/ibus/pull/2339

I think this fixed problem for me, though I do not really understand the code.

**Comment by escape0707** [comment]
Weird tho. I'm on latest Arch, GNOME, Firefox, iBus and don't experience the same problem at all in GTK apps and GNOME apps, even with HiDPI and scale 200%.

But Qt apps' candidate panel position is always wrong under Wayland. Panel may be outside of screen. #2103

And even under XWayland, the Panel's position seems to be appearing at the middle of top left of the screen and cursor. #2221

**Comment by AlynxZhou** [comment]
> Weird tho. I'm on latest Arch, GNOME, Firefox, iBus and don't experience the same problem at all in GTK apps and GNOME apps, even with HiDPI and scale 200%.
> 
> But Qt apps' candidate panel position is always wrong under Wayland. Panel may be outside of screen. #2103
> 
> And even under XWayland, the Panel's position seems to be appearing at the middle of top left of the screen and cursor. #2221

I am using NVIDIA GPU so I'm not going to test this recently, but will do it when I can.

**Comment by fujiwarat** [comment]
Thank you for the report. The GTK4 change was a complicated and sorry my mistake.

**Comment by fujiwarat** [comment]
If you apply this patch in your tarball, please also apply this to  client/gtk3/ibusimcontext.c besides client/gtk2/ibusimcontext.c .

**Comment by lockywolf** [comment]
I think, in my case the problem is still there.

Moreover, the pull request #2339 only changes the client for gtk2. Doesn't the one for gtk3 need this change too?

But, as I said, in my case the candidates window for pinyin is still in the wrong place about 80% of the screen lower than it should be. How do I debug this?

**Comment by fujiwarat** [comment]
> Moreover, the pull request #2339 only changes the client for gtk2. Doesn't the one for gtk3 need this change too?

As I explained the patch description, you should make for gtk3. Git repo has the symlink but tarball has the copied file.

**Comment by AlynxZhou** [comment]
> Moreover, the pull request #2339 only changes the client for gtk2. Doesn't the one for gtk3 need this change too?

It's symlink, gtk3 and gtk2 share the same file and if you check the preprocessor you'll find the code is not for gtk2 but gtk3.

**Comment by lockywolf** [comment]
Yeah, that was confusing, sorry.

Maybe any chance of making a release any time soon? If the version 1.5.25 contains such an obious and frequently manifesting inconvenience?
