### ISSUE TITLE
I can't make changes

### ISSUE THREAD

**Issue by TranQuan123** [ibus/ibus#2341]
So i have installed ibus, but i can't restart, so i turn on setup and it display:
**(ibus-setup:9773): IBUS-WARNING **: Can not get stat of file /usr/share/xml/iso-codes/iso_639.xml**
When i make changes it display:
**(ibus-setup:9773): dconf-WARNING **: failed to commit changes to dconf: Failed to execute child process "dbus-launch" (No such file or directory)**
Can some one explain?

**Comment by fujiwarat** [comment]
I'm not sure how you built & installed IBus.
The XML file is required by IBus and seems your desktop does not run D-Bus.

```
% rpm -qf /usr/share/xml/iso-codes/iso_639.xml 
iso-codes-4.6.0-1.fc34.noarch

% dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
method return time=1632532996.126470 sender=org.freedesktop.DBus -> destination=:1.232 serial=4294967295 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "ca.desrt.dconf"
      string "org.a11y.Bus"
      string "org.bluez.obex"
      string "org.freedesktop.IBus"
      string "org.freedesktop.IBus.Panel.Extension.Gtk3"
      string "org.freedesktop.PackageKit"
      string "org.freedesktop.ScreenSaver"
      string "org.freedesktop.impl.portal.desktop.gnome"
      string "org.freedesktop.portal.IBus"
      string "org.freedesktop.systemd1"
```
