### ISSUE TITLE
Feature Request: Remember input mode/state between engine switch

### ISSUE THREAD

**Issue by OliverLew** [ibus/ibus#2344]
There are some issues requesting remembering input mode between ibus restart. I am requesting a different one, not sure if someone else already did (this request should be quite common, I searched but didn't find any):

- Remember input mode/state between engine switch.

E.g., I am trying to use `ibus engine xxx` to switch engines every time I enter/exit vim's normal mode. But when I switch to an engine such as RIME from `xkb:us::eng`, the input mode is always reset to Chinese input, even if I was in RIME's English input mode before changing the engine. Thus, I would like an option that remembers the input mode between engine switch, so I can use the last input mode.

(The reason I am not switching to `xkb:us::eng` for English input is simply that requires a key combination, which is at least two keys (Ctrl+space, for example). It will be too exhausting to constantly switch between English and Chinese input, a single shift is much better.)

I also saw in https://github.com/ibus/ibus/issues/2230#issuecomment-684795305 something like this can be implemented within each engine, but I hope it will be in ibus so every engine can use the feature.

**Comment by mike-fabian** [comment]
This really depends on each engine, this should be implemented in RIME, not
ibus.

**Comment by OliverLew** [comment]
Thanks, I will check in ibus-rime repo, then.

**Comment by OliverLew** [comment]
It seems that RIME has this functionality (should, I am trying the configurations), so I am closing this issue here.
