### ISSUE TITLE
Wrong candidates position for Chromium/Chrome and Electron apps when using ibus-1.5.25

### ISSUE THREAD

**Issue by leavers** [ibus/ibus#2345]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Arch Linux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 40

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Both X11 and Wayland reproduce this issue

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Chrome
Chromium
Typora
VSCode

IBus version?: 
(Run `ibus version`)
1.5.25

Issue description:
When the cursor moves, the selection box can follow normally, but there is a large vertical distance between the candidate box and the cursor position. This issue can be reproduced when using either X11 or Wayland, with the screen scale of 100% or 200%. ibus-1.5.24 doesn't have this issue and I downgraded ibus and libibus as a temporary workaround. 

Steps to reproduce:
1. Open Chromium/Chrome or an Electron app (Typora, VSCode);
1. activate an ibus input method (i.e. ibus-libpinyin, ibus-rime);
1. Type something into the app. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

![Screenshot from 2021-09-03 00-44-08](https://user-images.githubusercontent.com/7592608/131884005-d8705e0c-d6c2-4d47-a7d7-257a7fffb009.png)

**Comment by fujiwarat** [comment]
Did you check #2337 ?

**Comment by leavers** [comment]
Thanks for your prompt, it helped me a lot. I've confirmed that commit [936a0e7](https://github.com/ibus/ibus/commit/936a0e76df79d92a8bdc03e9205330fb84a2083e) solved this issue.
