### ISSUE TITLE
Candidates window for pinyin input doesn't show up in the right place in Firefox (and some other apps)

### ISSUE THREAD

**Issue by esbutterworth** [ibus/ibus#2347]
Please fill in the following items if you don't know the root cause.

Which distribution and version?:  Arch
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: KDE Plasma 5.22.5
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: X11
(X11 or Wayland. Check $XDG_SESSION_TYPE)

Which application and version?: firefox 91.0.2
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 1.5.25
(Run `ibus version`)

Issue description:
in Firefox and electron-based apps, the candidate window appears at the bottom of the Firefox window and is unusable.

Steps to reproduce:
1. start ibus-daemon
2. start firefox
3. switch input method to ibus-libpinyin 
4. type and the window will not appear under the cursor as it should

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: 
```cannot open ../lua/base.lua: No such file or directory```
not sure if this is related.
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

**Comment by fujiwarat** [comment]
Did you check the fix of #2337 ?

**Comment by esbutterworth** [comment]
that fixed it! thank you very much @fujiwarat
