### ISSUE TITLE
ibus not working in KDE Plasma Wayland

### ISSUE THREAD

**Issue by juhp** [ibus/ibus#2352]
Which distribution and version?: 

Fedora 35 (pre-Beta)

Which desktop environment and version?: 
KDE Plasma

Which session type?: 
Wayland

Which application and version?: 
kwrite (any KDE/qt app under KDE)

IBus version?: 
ibus-1.5.25

Issue description:
ibus seems not working at all in Plasma Wayland (Plasma Xorg seems fine).

Steps to reproduce:
1. install ibus-anthy
2. enable ibus with im-chooser
3. try to add Anthy IME
4. try to switch input source
5. try to input Japanese

Cannot input any Japanese text: input is just direct Latin.

**Comment by fujiwarat** [comment]
Please file your issue to https://bugreports.qt.io/secure/Dashboard.jspa

**Comment by juhp** [comment]
I opened https://bugreports.qt.io/browse/QTBUG-96872
