### ISSUE TITLE
Failed to get iBus to work

### ISSUE THREAD

**Issue by capfredf** [ibus/ibus#2355]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
opensuse tumbleweed

Which desktop environment and version?: 
Gnome 40

Which session type?: 
wayland

Which application and version?: 
gedit

IBus version?: 
1.5.25

Issue description:
I have installed ibus, ibus-gtk3 and ibus-libpinyin. But I can't find ibus in the Gnome's input sources setting. 
Running `ibus-daemon` just shows `current session already has an ibus-daemon`, but I can't find any ibus related process (via `ps aux| grep ibus`. 

Running other ibus commands (like `ibus restart`) shows a warning 

```
(process:32195): IBUS-WARNING **: 14:24:40.849: ibus_bus_call_sync: org.freedesktop.IBus.Exit: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Unknown method Exit or interface org.freedesktop.IBus.
```

Also, there is no input methods I can add in the configure app
![Screenshot from 2021-09-29 14-28-06](https://user-images.githubusercontent.com/512906/135327720-72f92ada-059a-49c0-a00b-d4bbab65ddd1.png)

### Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I haven't tried this yet.

**Comment by Yakkhini** [comment]
have you reboot your computer?

**Comment by capfredf** [comment]
Yes, I have.

**Comment by fujiwarat** [comment]
Seems you have problems in D-Bus.

Probably you could check it with dbus-send.
`dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus  org.freedesktop.DBus.Introspectable.Introspect`
`ibus address`
`ibus engine`
