### ISSUE TITLE
In the flameshot screenshot tool, the candidate word list is not displayed when adding a text box to enter Chinese

### ISSUE THREAD

**Issue by miaoerwu** [ibus/ibus#2357]
Which distribution and version?: pop!_os 21.04

Which desktop environment and version?: GNOME 3.38.4

Which session type?: x11

Which application and version?: flameshot 0.10.1

IBus version?: 1.5.24

Issue description:
![image](https://user-images.githubusercontent.com/14366467/136512153-f7e77798-c2c6-4648-963b-b1ab09c2e072.png)
![image](https://user-images.githubusercontent.com/14366467/136512170-6e1dadc3-0131-41c1-964d-75d0280e72b7.png)
When using flameshot to take screenshots, the list of candidate words is not displayed. When the mouse is pointing to the icon in the red box, the box will be displayed after the screen flashes below. This problem has been raised in flameshot's issues. This problem will not occur when using fctix. The maintainer thinks that this problem should be raised to ibus. Personally, I feel that this problem is not at the top level when the list of candidate words is displayed. Level, can you look at this question? thank you very much!

Steps to reproduce:
1. Use flameshot to select the area that needs to be shot
2. Click the text box button (it looks like a T icon), and place the text box where you need to enter text
3. Input Chinese

Can you reproduce your problem when you restart ibus-daemon?: yes 

Do you see any errors when you run ibus-daemon with the verbose option?: can't see any errors

Can you reproduce your problem with a new user account instead of the current your account?: yes

**Comment by fujiwarat** [comment]
Seems the candidate pop window receives the candidate words and coordinate correctly from ibus-daemon but failed to show the window in GNOME 3.38.
I confirmed flameshot works fine in GNOME 41.

I think you can use `gnome-screenshot -i` instead of the QT based flameshot for the workaround.
