### ISSUE TITLE
Emoji shortcut not working with French keyboard

### ISSUE THREAD

**Issue by bigon** [ibus/ibus#2360]
Hello,

Since https://github.com/ibus/ibus/issues/2325, the emoji shortcut is not working on my (Belgian) French Keyboard anymore.

This is happening since the period key is not the 1st level and requires shift to be pressed as well

This is breaking the OOTB user experience

**Comment by julienfalque** [comment]
I have the same issue with my french keyboard: `<Control>period` does not work. I was able to workaround the issue by running `ibus-setup` and adding `<Control>KP_Decimal` as a new shortcut.

**Comment by fujiwarat** [comment]
OK, probably I should add  `<Control>semicolon` too.
