### ISSUE TITLE
Add basic checks for a runaway ibus

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#2361]
There should be some basic checks,
e.g., if the program is getting more than 1000 inputs within a second,
etc. to prevent a runaway ibus from using all the CPU,
so that even attempts to stop it from another terminal,
```
Login: root

Login timed out after 60 seconds
```
fail as it took too long to ask for a password because ibus used too much CPU.

No steps to reproduce it. It could happen due to various things. Just have a check to stop it, please.

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.

>> e.g., if the program is getting more than 1000 inputs within a second,

I don't know why 1000 inputs can happen within a second.

**Comment by jidanni** [comment]
OK, maybe 30 inputs, due to some stuck key. 如鍵盤故障。

**Comment by fujiwarat** [comment]
I don't understand how do you setup the stuck key.
Please use bug template and describe your reproducing steps exactly.

**Comment by jidanni** [comment]
(I don't know how the problem happened either.
All I know is that day top(1) said that ibus was using all the CPU.)
