### ISSUE TITLE
ibus applet very hard to see on the dark KDE Plasma panel

### ISSUE THREAD

**Issue by juhp** [ibus/ibus#2364]
Which distribution and version?: 
Fedora 35

Which desktop environment and version?: 
KDE Plasma 5
F35-KDE-x86_64-LIVE-20211201.iso

Which session type?: 
Both X11 and Wayland

IBus version?: 
1.5.25

Issue description:
It is very hard to see the dark ibus applet in the dark KDE panel.

Steps to reproduce:
1. Setup ibus in Fedora KDE Plasma
1. Look for applet in the KDE panel

![Screenshot from 2021-12-13 23-21-19](https://user-images.githubusercontent.com/82731/145839302-a0461c69-3a01-4dd1-9aed-084e6d4b46e3.png) <- EN keyboard
![Screenshot from 2021-12-13 23-22-03](https://user-images.githubusercontent.com/82731/145839368-ddf3ba51-4e9f-4712-ac7b-bc87a80ffb1b.png) <- anthy hiragana

Can anything be done to improve the contrast here for this?

**Comment by fujiwarat** [comment]
OK, I see.
I'm thinking a new branding color #51a2da for all desktops and I tested XFCE and Plasma.

You can check the result with the following command:
`gsettings set org.freedesktop.ibus.panel xkb-icon-rgba '#51a2da'`

**Comment by ariasuni** [comment]
I think this is a good idea, and a pretty nice color. The ideal solution would be to draw some kind of line with a light color around the characters so that it’s perfectly legible everywhere, but I suppose it’s much harder to do.

**Comment by fujiwarat** [comment]
BTW drawing bleary character line issue would be relative with libappindicator and KDE and you can see the enhanced line with `ibus restart`.
