### ISSUE TITLE
Cannot Backspace While Holding Shift

### ISSUE THREAD

**Issue by wanwandrew** [ibus/ibus#2365]
I don't know how hard this would be to implement, but Microsoft's IME does it, so it shouldn't be too hard, right? :D Right...? Anyway, That's the gist. I can enter a unique character with a shift+'x character' but I cannot backspace while still holding down shift, in the event that I mistyped a ゃ as a ゅ, for instance. I have tried this in two slightly different environments: Clear on Focus Out and Hold on Focus Out. Upon further inspection, I see that the muhenkan and henkan keys, which are set to the shift keys, deal with character conversion. This is probably related to that. (No, I didn't know what they did prior to this. Don't judge me. :c) So, technically, you could argue that this is working as intended, but, as I said, it works fine with Microsoft's IME and, to my knowledge, I did not change the muhenkan and henkan keybinds in that IME. If my memory is as crystal clear as I am thinking it is, though, their muhenkan key is bound to the tilde key...? Maybe? It is worth checking out.
[EDIT: Then again, backspace does work while holding down the right shift key. Not sure if this is important or not.]

Here are the specs:

Kernel (Unmodified by me, currently; yes, Linux): 5.15.7-200.fc35.x86_64
Distribution: Fedora 35 (Workstation Edition)

Environment: GNOME 41.2

Window Compositor/Manager: Mutter and Wayland

This occurs in Firefox (modified for privacy, etc.) and in the stock GNOME Terminal Version 3.42.1 (I messed around with the color scheme a bit, but I changed it all back to either the defaults or "Use System Settings".)

IBus 1.5.25

Issue description is at BOF.

Steps to reproduce:
1. Prepare your Japanese typing fingers
2. Type a big ol' character while holding down the Left Shift key
3. Continue holding down the shift key
4. Attempt to backspace the character that was just typed

Can you reproduce your problem when you restart ibus-daemon? (yes / no):
The bug persists through a restart, and, by the way... I cannot dele normal sized characters while holding down the shift key, either. I don't particularly think any of my settings have anything to do with this, but that is always a possibility. I'll include some screenshots.)

Do you see any errors when you run ibus-daemon with the verbose option?:
I see some errors related to what appears to be kernel object files not being loaded because my desired input language is Japanese, but nothing specifically related to this.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I really really really really don't feel like testing this, so, as I said prior, I will include screenshots of my current configuration.

![ibus05](https://user-images.githubusercontent.com/30514081/146311611-b7d39545-5be8-4619-8686-0ea3c96a1309.png)
![ibus04](https://user-images.githubusercontent.com/30514081/146311612-bcd86db9-8c0b-44a7-841b-899f97eab023.png)
![ibus03](https://user-images.githubusercontent.com/30514081/146311614-a4202be1-4851-48a1-9bf0-b129a8724d69.png)
![ibus02](https://user-images.githubusercontent.com/30514081/146311615-9baad34b-f9bd-4b27-9bf6-3a59127969e7.png)
![ibus01](https://user-images.githubusercontent.com/30514081/146311616-225f78aa-5578-4bac-ac71-b94115740dd0.png)

**Comment by fujiwarat** [comment]
It's an ibus-anthy issue but not ibus core one.

You can configure Shift-Backspace in `backspace` command in "Key Binding" tab in the setup dialog.
Probably I can think Shift-Backspace and Shift-Delete by default.

**Comment by wanwandrew** [comment]
> It's an ibus-anthy issue but not ibus core one.
> 
> You can configure Shift-Backspace in `backspace` command in "Key Binding" tab in the setup dialog. Probably I can think Shift-Backspace and Shift-Delete by default.

Sorry. I usually check with all parties before posting something like this, but team members with so closely related projects often work together, so I figured it would be caught by someone who could, if not fix the issue, direct it to someone who can...

**Comment by fujiwarat** [comment]
Did you check the setting?

**Comment by wanwandrew** [comment]
I only checked what I listed here.

**Comment by fujiwarat** [comment]
You should try my suggested setting.
