### ISSUE TITLE
ibus-extension-gtk3: Segmentation fault in `_gtk_css_section_new (libgtk-3.so.0)`

### ISSUE THREAD

**Issue by paulmenzel** [ibus/ibus#2366]
On Debian sid/unstable with *ibus* 1.5.25-3, `coredumpctl` lists a crash of ibus-extension-gtk3 with a segmentation fault for the user *gdm* used for running the graphical login manager GDM.

Pleas find the GDB backtrace [attached](https://github.com/ibus/ibus/files/7775173/ibus-extension-gtk3-gdb-taabtf.txt).

    Stack trace of thread 1353:
    #0  0x00007fe08e0cc2c6 g_slice_alloc (libglib-2.0.so.0 + 0x722c6)
    #1  0x00007fe08e6ee15d _gtk_css_section_new (libgtk-3.so.0 + 0x19915d)
    #2  0x00007fe08e6eb80b gtk_css_scanner_push_section (libgtk-3.so.0 + 0x19680b)
    #3  0x00007fe08e6eb7b5 parse_import (libgtk-3.so.0 + 0x1967b5)
    #4  0x00007fe08e6eceeb gtk_css_provider_load_from_file (libgtk-3.so.0 + 0x197eeb)
    #5  0x00007fe08e6ed081 gtk_css_provider_load_from_resource (libgtk-3.so.0 + 0x198081)
    #6  0x00007fe08e6ed3eb _gtk_css_provider_load_named (libgtk-3.so.0 + 0x1983eb)
    #7  0x00007fe08e83150a settings_update_theme (libgtk-3.so.0 + 0x2dc50a)
    #8  0x00007fe08e8349a8 settings_init_style (libgtk-3.so.0 + 0x2df9a8)
    #9  0x00007fe08e7bef68 display_opened_cb (libgtk-3.so.0 + 0x269f68)
    #10 0x00007fe08e1a7a21 g_cclosure_marshal_VOID__OBJECTv (libgobject-2.0.so.0 + 0x17a21)
    #11 0x00007fe08e1a4909 n/a (libgobject-2.0.so.0 + 0x14909)
    #12 0x00007fe08e1bd2d9 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2d2d9)
    #13 0x00007fe08e1bd4ff g_signal_emit (libgobject-2.0.so.0 + 0x2d4ff)
    #14 0x00007fe08e1a4909 n/a (libgobject-2.0.so.0 + 0x14909)
    #15 0x00007fe08e1bd2d9 g_signal_emit_valist (libgobject-2.0.so.0 + 0x2d2d9)
    #16 0x00007fe08e1bd72e g_signal_emit_by_name (libgobject-2.0.so.0 + 0x2d72e)
    #17 0x00007fe08e4e70ea _gdk_wayland_display_open (libgdk-3.so.0 + 0x980ea)
    #18 0x00007fe08e487d97 gdk_display_manager_open_display (libgdk-3.so.0 + 0x38d97)
    #19 0x00007fe08e7a0083 gtk_init_check (libgtk-3.so.0 + 0x24b083)
    #20 0x00007fe08e7a00b9 gtk_init (libgtk-3.so.0 + 0x24b0b9)
    #21 0x000055c2a619785e n/a (ibus-extension-gtk3 + 0x1585e)
    #22 0x000055c2a618b5f2 n/a (ibus-extension-gtk3 + 0x95f2)
    #23 0x00007fe08dce47ed __libc_start_main (libc.so.6 + 0x277ed)
    #24 0x000055c2a618b64a n/a (ibus-extension-gtk3 + 0x964a)

**Comment by fujiwarat** [comment]
I guess you use the wrong custom GTK theme and it's not only a gtk-extension-gtk3 issue but common GTK issue.
That's why I asked to use the bug template.

**Comment by paulmenzel** [comment]
It’s *libgtk-3-0* 3.24.30-4, *gdm* 41.0-3 and *gnome-shell* 41.2-1. GDM is using Wayland.

I do not know how to reproduce the problem. It only happened once.
