### ISSUE TITLE
ibus-anthy only available in gnome with networking enabled

### ISSUE THREAD

**Issue by wanwandrew** [ibus/ibus#2367]
Not it! :)
I turned my networking off before trying to change from english to japanese with anthy input in fedora (35) and gnome. I am unaware as of why. The machine is new. I run a DNS server and a caching and ad-blocking proxy that is supposed to (but usually doesn't) run through tor. My firewall is set up correctly. I leave the outbound ports open because I am too lazy to write xml for specific applications.

**Comment by fujiwarat** [comment]
> ibus-anthy only available in gnome with networking enabled 

How is ibus-anthy available in gnome with network?
Please describe the problem with reproducing steps using the bug template.
