### ISSUE TITLE
Switch the input method and change the insertion point, the line between the insertion point becomes selected.

### ISSUE THREAD

**Issue by inoton** [ibus/ibus#2369]
### Which distribution and version?
Fedora release 35 (Thirty Five)  

### Which desktop environment and version?
GNOME 41.2  

### Which session type?
Wayland.  

### Which application and version?
gedit 41.alpha, Mozilla Firefox 95.0.2, vscode 1.63.2  

### IBus version?
```
~ $ rpm -qa | grep '^ibus' | sort
ibus-1.5.25-6.fc35.x86_64
ibus-gtk2-1.5.25-6.fc35.x86_64
ibus-gtk3-1.5.25-6.fc35.x86_64
ibus-libs-1.5.25-6.fc35.x86_64
ibus-setup-1.5.25-6.fc35.noarch
ibus-table-1.14.1-1.fc35.noarch
ibus-table-chinese-wubi-jidian.noarch
```

### Issue description:
Switch the input method and change the insertion point, the line between the insertion point becomes selected.  

### Steps to reproduce:  
1. First, place the cursor insertion point on the first line of text.  
2. Next, use the left SHIFT to switch the input method from Chinese to English (or English to Chinese).  
3. Then, click anywhere on the third row to change the cursor insertion point.  
4. At this time, the content between the cursor insertion points in row 1 to row 3 becomes selected.  
5. It has been verified in the Fedora 35 LiveCD environment and normal operating system, and the issue can be reproduced in firefox, gedit, vscode and other software.  
6. Note: Line 1 and Line 3 can also be other lines.  

### Can you reproduce your problem when you restart ibus-daemon? 
Yes, I can.

### Do you see any errors when you run ibus-daemon with the verbose option?:  
There is no output content.

### Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes, also in livecd.

**Comment by inoton** [comment]
**Additional information:**
1. Use the **left SHIFT key** to switch between English and Chinese.  
2. This issue is only reproduced under the wayland protocol.  
3. The principle is that the program thinks that SHIFT is not released, which is a problem with the processing logic of the SHIFT key. (Analysis from the developer of [the fcitx5 input method framework](https://github.com/fcitx/fcitx5))

**Comment by inoton** [comment]
https://user-images.githubusercontent.com/54309560/148677841-ce96ce29-bbcf-462c-a7bb-6dc8f540f228.mp4

Moving the cursor insertion point works fine because the esc key is pressed.

**Comment by fujiwarat** [comment]
CC'ing @epico 
I don't understand this issue yet but I guess it's relative with https://gitlab.gnome.org/GNOME/mutter/-/issues/1876

**Comment by inoton** [comment]
Hi.   
I thought it was a bug of ibus-table,so I moved it here.   
https://bugzilla.redhat.com/show_bug.cgi?id=2038973
