### ISSUE TITLE
Disable preedit/preview text for dead keys

### ISSUE THREAD

**Issue by xolott** [ibus/ibus#2371]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 21.10

Which desktop environment and version?: 
ubuntu:GNOME

Which session type?: 
x11

Which application and version?: 
System-wide

IBus version?: 
IBus 1.5.25

Issue description:

Is there a way to disable this feature? I don't want any "preview" of my dead keys because this mess with some nice features I use on other apps, like VSCode and Chrome.

On ubuntu 20.04 (and 18.04 before I did the upgrade) I never had this issue and don't remember if I touched something (but again, I used the system for almost 4 years without a reinstall)

I use a Latin American Spanish layout keyboard

![Peek 2022-01-19 10-59](https://user-images.githubusercontent.com/5204776/150145438-ea424a3a-fb95-47ba-b8c7-07591d61fac0.gif)

![OW8qQ](https://user-images.githubusercontent.com/5204776/150145105-e064a7c1-57de-47f9-b7bb-44d7f075a853.gif)

**Comment by fujiwarat** [comment]
Currently IBus follows the GTK compose preedit and it was discussed there:
https://gitlab.gnome.org/GNOME/gtk/-/issues/3669

**Comment by InFerYes** [comment]
The discussion you linked to says "This is the exact behaviour when using IBus", you are referring to eachother.

Could this be made optional, still?
