### ISSUE TITLE
【Bug？】 Cannot switch to Chinese engines from any Non-English Engine

### ISSUE THREAD

**Issue by djypku** [ibus/ibus#2378]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora Silverblue 35
(Check for Fedora 35, Ubuntu 21.10, Xubuntu 20.04 too)

Which desktop environment and version?: 
Gnome 41
(Check for Gnome 3.x and Xfce 4.16 too)

Which session type?: 
Both X11 and Wayland checked

Which application and version?: 
Not a matter

IBus version?: 
1.5.25

Issue description:
Cannot switch to any Chinese input engine from Non-English engines like Russian or Greek. Both changing with `<super>+<space>` and directly with tray button ( or Gnome topbar button ) are tried and both not work. Tray ( or Gnome topbar ) applets show I am using Chinese engine, but actually former engine, for example, Russian one, still works.
It is OK to switch to Chinese engine from English engine. Not only en_US but like UK English or others also works. Now I have to use like Greek -> English -> Chinese to make Chinese engine works. Thankfully I use Greek and Russian both not often. 
If I only remain Chinese engine and Russian engine for example, without any English engine, then it is never possible to switch to Chinese anymore. 

I have Checked:
former engine: Russian, Greek
later engine: Libpinyin, Rime
DE: Gnome41, Gnome3.x, xfce4.16
OS: Fedora 35, Fedora Silverblue 35, Ubuntu 21.10, Xubuntu 20.04
both X11 and Wayland
They all do not make any difference. Gnome-ibus and vanilla ibus in xfce have the same problem too.

Steps to reproduce:
1. Install OS and ibus, then choose Libpinyin, Russian and English (US) for example. Make all these work.
2. Switch to Russian, then switch to Libpinyin
3. tray tells me Libpinyin is working but actually I type Russian as output

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
Every time I switch to Libpinyin there shows:
```
cannot open ../lua/base.lua: 没有那个文件或目录
lua script loaded.
```
Whatever former engine is English or not.
The Chinese characters `没有那个文件或目录` here means `No such file or directory`

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
I think your issue is not Silverblue specific.
ibus-libpiyin does not have any keymaps and follows the current session keymap so you have to switch the current keymap to English at first.
ibus-libpinyin setup does not have the feature to customize the keymap.
If you wish to have the fixed keymap for ibus-libpinyin you need to modify layout tag in /usr/share/ibus/component/libpinyin.xml
