### ISSUE TITLE
Switching windows/workspaces restores the input method to the default config

### ISSUE THREAD

**Issue by HymanZHAN** [ibus/ibus#2379]
Please fill in the following items if you don't know the root cause.

### Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)

Fedora 35

### Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

GNOME 41.3

### Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)

X11 (also happens with Wayland, reproduced on a different machine)

### Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)

Basically all applications (but I will use Firefox as an example).

### IBus version?: 
(Run `ibus version`)

IBus 1.5.25

### Issue description:

After setting "Switch input sources individually for each window" in Gnome Settings, switching windows or workspaces will restore the input method of the original window to its default configuration.

### Steps to reproduce:

1. Switch to Intelligent Pinyin on the Firefox window
2. Change to input **Traditional Chinese** with Ctrl+Shift+F (default is Simplified Chinese)
3. Go to the second workspace
4. Go back to the previous workspace (autofocusing on the original Firefox window)
5. Try to input, only to discover that it's now inputting **Simplified Chinese**

### Screencasts:

https://user-images.githubusercontent.com/26806995/152723599-760fe7cf-52d9-4288-9fb9-cc36630908ee.mp4

### Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Yes

### Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

I am not sure if this output contains the relevant error:
```
[1]  + running    ibus-daemon --xim --verbose
cannot open ../lua/base.lua: No such file or directory
lua script loaded.
cannot open /home/xzhan/.config/ibus/libpinyin/user.lua: No such file or directory
cannot open ../lua/base.lua: No such file or directory
lua script loaded.
cannot open /home/xzhan/.config/ibus/libpinyin/user.lua: No such file or directory
```

### Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

Yes.

#### Relevant issue in `ibus-libpinyin`: https://github.com/libpinyin/ibus-libpinyin/issues/349

**Comment by fujiwarat** [comment]
My understanding is your problem dos not happen in non-GNOME desktop, i.e. the setting is handled by ibus-setup but not gnome-control-center.

Please report your issue to gnome-shell.

**Comment by fujiwarat** [comment]
I confirmed the input context paths are different between workspaces in XFCE4 desktop.
