### ISSUE TITLE
Missing g_free() after gdk_display_map_keyval()

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2380]
According to [the reference for `gdk_display_map_keyval()`](https://docs.gtk.org/gdk4/method.Display.map_keyval.html#description), the returned array of GdkKeymapKey should be freed. But `client/gtk?/ibusimcontext.c` lack `g_free()`.

https://github.com/ibus/ibus/blob/c69b61aa66239e1b13c9764b2d3bf6f02d086785/client/gtk2/ibusimcontext.c#L1953

**Comment by fujiwarat** [comment]
Thank you for the report.
