### ISSUE TITLE
Incorrect key forwarded on gtk4 with immodule

### ISSUE THREAD

**Issue by changwoo** [ibus/ibus#2382]
Which distribution and version?:  Debian unstable

Which desktop environment and version?: GNOME 41.3

Which session type?: Reproducible both on Wayland and on X11

Which application and version?: All, reproducible on gtk4-demo

IBus version?: 1.5.25, with ibus-hangul 1.5.4

Issue description:

With ibus-hangul, some keys like space key are "forwarded" into ibus but the resulting input is not correct. The problem only occurs with GTK immodule (GTK_IM_MODULE=ibus), the Wayland input works as expected.

Steps to reproduce:
1. Run `env GTK_IM_MODULE=ibus gtk4-demo
1. Switch ibus-hangul to Hangul mode
1. Open Entry demo or Text View demo.
1. Typing ' '(space) will produce '5', '9' will produce '1', '0' will produce '2'.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):  yes

**Comment by changwoo** [comment]
I think I found the cause:

https://github.com/ibus/ibus/blob/a076b388d856aeb4c8f8317dd6cd9dd6d61fe9ac/client/gtk2/ibusimcontext.c#L1948

I think the keycode should be converted from IBus keycodes to GTK ones in case of `keycode != 0`. (Maybe `+8` ?)

**Comment by changwoo** [comment]
It works correctly with this PR  https://github.com/ibus/ibus/pull/2384

**Comment by fujiwarat** [comment]
Thank you for the report.
