### ISSUE TITLE
Unable to start ibus-daemon on Wayland: portal is not running

### ISSUE THREAD

**Issue by arbitrary-dev** [ibus/ibus#2383]
Which distribution and version?: 
Gentoo/Linux x86_64

Which desktop environment and version?: 
None

Which session type?: 
Wayland

Which application and version?: 
None

IBus version?: 
IBus 1.5.25

Issue description:
Unable to start ibus-daemon on Wayland, getting following:
```
$ ibus-daemon -rx
portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1
```

Though under root it behaves slightly different:
```
# ibus-daemon -rx &
[1] 5337

# ibus-setup
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified

(ibus-setup:5351): Gtk-CRITICAL **: 22:30:39.779: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Traceback (most recent call last):
  File "/usr/share/ibus/setup/main.py", line 54, in <module>
    from emojilang import EmojiLangButton
  File "/usr/share/ibus/setup/emojilang.py", line 40, in <module>
    from icon import load_icon
  File "/usr/share/ibus/setup/icon.py", line 36, in <module>
    icon_theme.prepend_search_path(icondir)
AttributeError: 'NoneType' object has no attribute 'prepend_search_path'
```

Do you see any errors when you run ibus-daemon with the verbose option?:
```
$ ibus-daemon -rx --verbose
portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1

(ibus-ui-gtk3:5376): IBUS-WARNING **: 22:31:54.471: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
IBUS_ERROR: Failed to execute child process “setxkbmap” (No such file or directory)

(ibus-ui-gtk3:5376): IBUS-WARNING **: 22:31:54.481: xkblayout.vala:198: Execute setxkbmap failed: Failed to execute child process “setxkbmap” (No such file or directory)
```

**Comment by dongdigua** [comment]
+1

**Comment by zhouguannan** [comment]
+1, gentoo ibus-1.5.27 same issue

**Comment by Piturnah** [comment]
+1, NixOS, ibus v1.5.28

```console
$ ibus-daemon --verbose
portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1

(ibus-ui-gtk3:2588): IBUS-WARNING **: 13:23:51.509: panel.vala:310: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
```

nixos/configuration.nix:
```nix
i18n.inputMethod = {
  enabled = "ibus";
  ibus.engines = with pkgs.ibus-engines; [ mozc ];
};
```

**Comment by fujiwarat** [comment]
> portal is not running: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildExited: Process org.freedesktop.portal.IBus exited with status 1

I guess you run ibus-daemon in the sandbox likes using Flatpak but you need to run ibus-daemon in the host side.
ibus-daemon can run in Wayland.

**Comment by arbitrary-dev** [comment]
>I guess you run `ibus-daemon` in the sandbox likes using Flatpak

Nope, I'm running it plain.

>Not sure exactly what changed, but the issue was fixed just by running `ibus-setup`

`ibus-setup` proposes to start `ibus-daemon` by himself and seems to do the job successfully, yet I still can't change my input nor can I open preferences for "Japanese (Mozc)".

Also `ibus-setup` notifies that I may need to export some envs in `.bashrc` to run daemon, yet adding them to `.zshrc` does nothing to resolve the issue.

**Comment by fujiwarat** [comment]
Seems you have multiple settings errors in yourself.

> 
(ibus-setup:5351): Gtk-CRITICAL **: 22:30:39.779: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed

You should run ibus-setup with the display.

> 
(ibus-ui-gtk3:5376): IBUS-WARNING **: 22:31:54.481: xkblayout.vala:198: Execute setxkbmap failed: Failed to execute child process “setxkbmap” (No such file or directory)


You should install setxkbmap.

> yet I still can't change my input nor can I open preferences for "Japanese (Mozc)".

You should run application with the environment variables.

**Comment by arbitrary-dev** [comment]
>Seems you have multiple settings errors in yourself.

No, man, I'm flawless 😄

>You should run ibus-setup with the display.

Well, I do.

>You should install `setxkbmap

Why should I do it on Wayland? Besides this warning is not logged for me anymore.

>You should run application with the environment variables.

Well, I do.

```
$ echo $GTK_IM_MODULE
ibus

$ echo $XMODIFIERS
@im==ibus

$ echo $QT_IM_MODULE
ibus

$ echo $DISPLAY
:0

$ command setxkbmap
zsh: command not found: setxkbmap

$ ibus-setup
<no warnings or any log output>
```

**Comment by fujiwarat** [comment]
> Why should I do it on Wayland? Besides this warning is not logged for me anymore.

If you use Wayland, IBus panel is not supported currently but you could switch IBus engines with `ibus engine` command.
You need to run both `ibus-daemon --panel disable &` and ibus-wayland.

I've been working on IBus panel for Plasma Wayland with #2408 and the initial target will be 1.5.29
