### ISSUE TITLE
Compose key takes very long to execute on large (invalid) input

### ISSUE THREAD

**Issue by Marckvdv** [ibus/ibus#2385]
### Which distribution and version?: 
Debian 5.10.84-1

### Which desktop environment and version?: 
Tested on both awesome v4.3 and xfce4

### Which session type?: 
X11

### Which application and version?: 
Anything with input

### IBus version?: 
1.5.23

### Issue description:
Not sure if this is the right spot to open this issue, as the problem can be caused by lots of programs along the way. 

The problem occurs when I type: \`~~~~~~~~~ , i.e. pressing backtick followed by pressing tilde numerous times. The more times I press tilde, the longer it takes to resolve, where pressing it 9 times takes a second or two of 100% CPU power and any more causes the system to be unusable (very long delay between input being processed). The process that uses all this processing power is called 'ibus-engine-simple'. I suspect it might have something to do with some programs not taking `IBUS_MAX_COMPOSE_LEN` into account but I am not familiar with the code base or how ibus works.

This is using the keyboard mapping: `setxkbmap -layout us -variant alt-intl`

### Steps to reproduce:
1. Run `setxkbmap -layout us -variant alt-intl`
1. Type \`~~~~~~~~~ in any input
1. Wait two seconds for the compose part to disappear
1. Try it with more tildes and observe that the system becomes unusable

### Can you reproduce your problem when you restart ibus-daemon?: 
yes

### Do you see any errors when you run ibus-daemon with the verbose option?:
no

### Can you reproduce your problem with a new user account instead of the current your account?: 
yes

**Comment by fujiwarat** [comment]
Thank you for the report.
I can reproduce your issue.
