### ISSUE TITLE
Emoji hotkey (ctrl + semicolon) conflicts with LibreOffice Calc hotkey

### ISSUE THREAD

**Issue by zerkerX** [ibus/ibus#2390]
Per the fix to #2360, Ctrl + Semicolon has been added as a default hotkey for the Emoji picker. I recently received this update on my Debian Testing install and was surprised to see an unexpected `e` appear when I was attempting to insert the current date into a spreadsheet in LibreOffice Calc.

As someone unfamiliar with the emoji insert method, it took me a while to figure out that this behaviour was even coming from ibus and that I could use `ibus-setup` to change the hotkey (and that it was even an emoji picker, but that's a separate topic).

Perhaps ctrl + comma is a better alternative default?

**Comment by Susensio** [comment]
`ctrl + comma` and `ctrl + dot` are google docs shortcuts to superscript and subscript.

**Comment by juhp** [comment]
I think the best solution would be to use Super+period (like Windows does?).
However the problem is that Gnome kind of "owns" Super: maybe something should be done to improve that?

**Comment by zerkerX** [comment]
Gnome already has a (separate) emoji picker on that hotkey. KDE does too.

**Comment by juhp** [comment]
I believe Gtk's Emoji picker uses the same Ctrl+period and Ctrl+semicolon shortcuts as ibus - though the former don't seem to work in LO Writer. Are you seeing something different?

I do see Super+Period in KDE.

**Comment by fujiwarat** [comment]
I also confirmed GNOME uses Ctrl-period and Ctrl-semicolon because GNOME thinks the shortcut keys should not depend on desktops while I suggest to move the GTK emoji feature to GNOME-Shell. Application(GTK) shortcut keys are Ctrl-* and desktop shortcut keys are Super-*.

IBus will continue to use Ctrl-* for the emoji shortcut keys until the GTK emoji functions are moved to GNOME-Shell.

**Comment by narFnarF** [comment]
Sorry if this obvious but if Gnome already has an emoji picker, why is there another one?

**Comment by fujiwarat** [comment]
> Sorry if this obvious but if Gnome already has an emoji picker, why is there another one?

IBus is not for GTK applications only but also other applications and also supports language annotations.

**Comment by hadess** [comment]
Ran into this today as well.

> IBus is not for GTK applications only but also other applications and also supports language annotations.

Seeing as ibus has toolkit specific plugins, it would be nice if it didn't trample on the emoji chooser for GTK 3 and 4 applications, specifically. It doesn't break GTK4's emoji chooser in Fedora 36 yet, but will in F37 it seems...

**Comment by fujiwarat** [comment]
I'd propose to move the GTK shortcut keys to gnome-shell.
IBus provides the D-Bus method to override IBus emoji UI and i think Super-period is better than Ctrl-period for the emoji shortcut key to compare MS-Window, Macintosh. IBus emoji UI connects to the input method and provides the language emoji annotations.

**Comment by fujiwarat** [comment]
I think I will move the IBus emoji shortcut key Ctrl-period to Super-space soon unless others override the shorcut keys with non-emoji shortcut keys.
IBus shortcut keys are global and I think it's not good use Ctrl-* keys for the global shortcut keys even if GTK emoji uses Ctrl-period.
