### ISSUE TITLE
Stateless layout switching?

### ISSUE THREAD

**Issue by ulidtko** [ibus/ibus#2392]
Hi all, any thought about **acyclic** (a.k.a. **stateless** or **modeless**) layout switching?

The basic idea:
 * `key_combo_1` *always* activates `layout_1`,
 * `key_combo_2` *always* activates `layout_2`,
 * `key_combo_3` *always* activates `layout_3`, and so on.

This works really well with muscle memory and eliminates **[mode errors][]**. Issues like #2303 too.

My user story is described [here](https://askubuntu.com/q/1123163/9061) for anyone interested. I want to employ Ibus to help myself learn another language with an involved writing system (Japanese).

But not seeing any option in ibus to have stateless hotkeys is a complete blocker for me.

XKB can do it, can ibus?

![image](https://user-images.githubusercontent.com/365338/160301292-f7d29fd7-7055-4dee-ad82-916e73f82f9e.png)

[mode errors]: https://en.wikipedia.org/wiki/Mode_(user_interface)#Mode_errors

**Comment by fujiwarat** [comment]
XKB options can switch the layouts in the combined layouts but IBus uses owned shortcut key and the switcher popup window can be hidden with switcher-delay-time in org.freedesktop.ibus/general gsetting value to -1.

**Comment by ulidtko** [comment]
Hi @fujiwarat, I think you missed my point.

The point is about **Stateless** layout switching (without the notion of "the current layout").

**Comment by fujiwarat** [comment]
I answered it with gsettings.
