### ISSUE TITLE
iBus causes Gnome Settings to freeze or crash when trying to change iBus-related Keyboard settings (Gnome 42)

### ISSUE THREAD

**Issue by sith-on-mars** [ibus/ibus#2395]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
OpenSUSE Tumbleweed

Which desktop environment and version?: 
Gnome 42

Which session type?: 
Wayland

Which application and version?: 
Gnome Settings

IBus version?: 
1.5.26

Issues description:
Issue 1: Gnome Settings freezes when trying to change the setting of a input method.
Issue 2: Gnome Settings crashes when trying to add a new input method.

Steps to reproduce issue 1:
1. Open Keyboard settings in Gnome Settings.
2. Click the three dot button of the existing iBus input method, such as Chinese (Intelligent Pinyin).
3. Click Preferences.
4. Gnome Settings freeze and ask me if I want to force-quit. 

Steps to reproduce issue 2:
1. Open Keyboard settings in Gnome Settings.
2. Click the plus button to select a new iBus input method, then press add.
3. Gnome Settings crash.
4. Go back to Keyboard settings, realise that the input method that I intend to add is added despite the crash.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by PhilippeRo** [comment]
I have the same problem here (running fedora 36 + Gnome 42, Wayland, IBUS 1.5.26).
It happens with all the input methods.

**Comment by PhilippeRo** [comment]
I tried again with gnome 43 and it now seems fixed. So I guess the bug can be closed.

**Comment by fujiwarat** [comment]
Right. Seems it's a GNOME issue.
