### ISSUE TITLE
systemd service uses bash's built-in compound command in POSIX sh context

### ISSUE THREAD

**Issue by m-shibata** [ibus/ibus#2397]
Which distribution and version?: Ubuntu 22.04 LTS

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu Jammy Jellyfish (development branch)"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jamm
```

Which desktop environment and version?: nearly GNOME 42

```
$ echo $XDG_CURRENT_DESKTOP 
ubuntu:GNOME
```

Which session type?: x11

```
$ echo $XDG_SESSION_TYPE
x11
```

Which application and version?:  gedit 41

IBus version?: 1.5.26

```
$ ibus version
IBus 1.5.26
```

Issue description:

This report is an escalation from a bug report in Ubuntu.
https://bugs.launchpad.net/ubuntu/+source/ibus/+bug/1968459

The org.freedesktop.IBus.session.GNOME.service.in calls sh command with bash's built-in compound command, [[ xxx ]].

https://github.com/ibus/ibus/blob/17648f0522910480b6c5dd4f5356ca1f6c160bf5/bus/services/org.freedesktop.IBus.session.GNOME.service.in#L21

This should be fixed by using bash or using test command as like followings.

```
ExecStart=sh -c '/usr/bin/ibus-daemon --panel disable $([ "$XDG_SESSION_TYPE" = "x11" ] && echo "--xim")'
```

Edit: add double quatations

Steps to reproduce:
1. Start Ubuntu 22.04 LTS with Japanese language packs
2. Select "Ubuntu on Xorg" on login screen
3. Startup gedit and other applications
4. Type "Hankaku/Zenkaku" key
5. Cannot input Japanese words

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes and no

Manually restart with "--xim" will be fixed this problem.

Do you see any errors when you run ibus-daemon with the verbose option?: no

Restart "--xim" is no problmes.

Can you reproduce your problem with a new user account instead of the current your account?: yes

**Comment by fujiwarat** [comment]
Thank you for the report and patch.
