### ISSUE TITLE
Candidate window appears in the bottom left hand corner

### ISSUE THREAD

**Issue by loulou921222** [ibus/ibus#2401]
Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
GNOME 42.0

Which session type?: 
X11

Which application and version?: 
All applications as far as I can tell (I have confirmed in Chrome, Discord, Writer, Gedit, Gnome Shell, Gnome Settings)

IBus version?: 
IBus 1.5.26-2 (was not present before upgrade from 1.5.25-3)

Issue description:
The candidate window apperas in the bottom left hand corner of the window. On a 2 monitor setup, a full screen window on the right monitor makes it appear on the buttom right hand corner of the left monitor. In Gnome Settings, it doesn't seem to appear at all, and in search in Gnome it apperas in the bottom left hand corner of the screen for the first key stroke and then corrects its position to the correct position after that.

Steps to reproduce:
1. Switch to an IME in IBus
2. Start typing

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Do you see any errors when you run ibus-daemon with the verbose option?: no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): Yes, and even on multiple systems.

![image](https://user-images.githubusercontent.com/39203111/163563576-215f781a-3e89-41b3-b5af-2fe49a21d5fa.png)
![image](https://user-images.githubusercontent.com/39203111/163563740-8363079b-28d3-4e3f-ab47-a3c5e49ce733.png)

**Comment by 196082** [comment]
I have the same problem!
Help me, please!!!

**Comment by fujiwarat** [comment]
I cannot reproduce your problem.
I guess you need to update your GNOME to the latest and export GTK_IM_MODULE=ibus .

**Comment by loulou921222** [comment]
I have stated the version I am using clearly
![image](https://user-images.githubusercontent.com/39203111/164778873-b02794aa-13e9-4d18-81ce-45a387d262ed.png)

**Comment by gunnarhj** [comment]
I see the issue with a misplaced candidate window in Ubuntu 22.04 if `LC_CTYPE` is set to e.g. `zh_CN.UTF-8` or `ja_JP.UTF-8`.

This `gnome-settings-daemon` issue may be related:

https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/682

**Comment by 196082** [comment]
> I see the issue with a misplaced candidate window in Ubuntu 22.04 if `LC_CTYPE` is set to e.g. `zh_CN.UTF-8` or `ja_JP.UTF-8`.
> 
> This `gnome-settings-daemon` issue may be related:
> 
> https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/issues/682

That's correct! thank you so much!

**Comment by fujiwarat** [comment]
> I see the issue with a misplaced candidate window in Ubuntu 22.04 if LC_CTYPE is set to e.g. zh_CN.UTF-8 or ja_JP.UTF-8.

I don't understand why you point out zh_CN.UTF-8 and ja_JP.UTF-8. The patches are not relative with locales but can set the gtk-im-module to wayland by default.

> All applications as far as I can tell (I have confirmed in Chrome, Discord, Writer, Gedit, Gnome Shell, Gnome Settings)

Are you really use gedit?
I know there is a position issue in GTK4 in Xorg but not GTK3.

**Comment by gunnarhj** [comment]
>> I see the issue with a misplaced candidate window in Ubuntu 22.04 if LC_CTYPE is set to e.g. zh_CN.UTF-8 or ja_JP.UTF-8.
>
> I don't understand why you point out zh_CN.UTF-8 and ja_JP.UTF-8.

Because the issue is not present on Ubuntu 22.04 if `LC_CTYPE` is `C.UTF-8` or some latin locale. (Don't ask me why the locale makes a difference.)

> The patches are not relative with locales but can set the gtk-im-module to wayland by default in GTK4.

Which patches are you referring to here?

**Comment by fujiwarat** [comment]
> Because the issue is not present on Ubuntu 22.04 if LC_CTYPE is C.UTF-8 or some latin locale. 

Do you mean you use ibus-anthy or ibus-libpinyin in LC_CTYPE=C.UTF-8 and you can reproduce the issue? LANG is not set?

> Which patches are you referring to here?

I mean: [e2d268eb](https://github.com/GNOME/gnome-settings-daemon/-/commit/e2d268eb00f06f497b2f62ae9f3b6e7e1fe4bd9e) and/or [c8981ef0](https://github.com/GNOME/gnome-settings-daemon/-/commit/c8981ef0b1e915e89c79e301080541baef0f9fa9) have probably something to do with it.

**Comment by gunnarhj** [comment]
> Do you mean you use ibus-anthy or ibus-libpinyin in LC_CTYPE=C.UTF-8 and you can reproduce the issue? LANG is not set?

Well, normally I have `LANG` set, of course, and `LC_CTYPE` is not set explicitly, which means that `LC_CTYPE` inherits the `LANG` value.

But the observation with the locale impact was discovered by Ikuya Awashiro during the discussion at [this Ubuntu bug](https://launchpad.net/bugs/1969637). And since I'm disinclined to switch to Chinese or Japanese as display language, I confirmed that the locale makes a difference by only changing `LC_CTYPE`.

**Comment by fujiwarat** [comment]
> Well, normally I have LANG set, of course, and LC_CTYPE is not set explicitly, which means that LC_CTYPE inherits the LANG value.

OK, I asked if you set different values between LANG and LC_CTYPE and seems you normally sets LANG only.

Now I understood your problem.
The latest GNOME does not set gtk-im-module to "ibus" by default and it's good for GNOME Wayland because the default is "wayland". But it's a problem in GNOME Xorg.
I could not reproduce your problem in Fedora because imsettings-daemon always runs in Fedora GNOME by mistake and it exports GTK_IM_MODULLE=ibus unfortunately or fortunately.
My suggestion is gtk-im-module should be "ibus" in Xorg and NONE in Wayland.

The workaround would be export GTK_IM_MODULE="ibus" or sets the gtk-im-module gsettings value to "ibus" in GNOME Xorg.

**Comment by gunnarhj** [comment]
> I could not reproduce your problem in Fedora because imsettings-daemon always runs in Fedora GNOME by mistake and it exports GTK_IM_MODULLE=ibus unfortunately or fortunately.

Yeah, I suspected that. :wink:

For a while, Debian's equivalent to `imsettings-daemon` (`im-config`) has not done anything in case of IBus on a GNOME desktop, but we have deferred to GNOME. That works fine on Debian 11 and Ubuntu 20.04/21.10, but is the explanation why we run into issues on x11 now with GNOME 42.

> My suggestion is gtk-im-module should be "ibus" in Xorg and NONE in Wayland.

Thanks for your comment on the `gnome-settings-daemon` issue!

> The workaround would be export GTK_IM_MODULE="ibus" or sets the gtk-im-module gsettings value to "ibus" in GNOME Xorg.

Right. An `im-config` workaround, where we set `GTK_IM_MODULE=ibus`, is on its way.
