### ISSUE TITLE
[Build] Fatal error: gdk/gdkwayland.h: No such file or directory

### ISSUE THREAD

**Issue by K1ngst0m** [ibus/ibus#2403]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Gentoo Base System release 2.8 x86_64 
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
bspwm 0.9.10
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
ibus build error
IBus version?: 
(Run `ibus version`)
ibus-1.5.26
Issue description:
when installing ibus-1.15.26 portage produce emake error like this:
Fatal error: gdk/gdkwayland.h: No such file or directory
complete logs: https://pastebin.ubuntu.com/p/dKGGycSQcW/ 
Steps to reproduce:
1. sudo emerge --update ibus
2. ebuild print build error message (ERROR: app-i18n/ibus-1.5.26::gentoo failed (compile phase))

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
/
Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
/

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
no

**Comment by fujiwarat** [comment]
I guess your distro separate the GDK 3.0 devel package from GTK 3.0 devel package.

You need to find which package includes /usr/include/gtk-3.0/gdk/gdkwayland.h file.

**Comment by fujiwarat** [comment]
If you don't have wayland, ibus build should not require wayland.

**Comment by K1ngst0m** [comment]
but why do I have to include the `gdk/gdkwayland.h` header when using X11?

gentoo's package manager manages the source code of the ibus. So through the package manager ibus will first be compiled before installation, and it will cause the compiler error in X11 only system because there's nowhere to find `gdk/gdkwayland.h`.

so currently if someone needs to build the ibus the system must contain the xxxwayland environment even if they use X11 only.

**Comment by fujiwarat** [comment]
> but why do I have to include the gdk/gdkwayland.h header when using X11?

Again, if you disable wayland build, ibus wont' need gdkwayland.h.

**Comment by nonno-cicala** [comment]
Again, if you disable wayland build, ibus still needs `gdkwayland.h` :slightly_smiling_face: 
To keep things as simple as possible from the uncompressed 1.5.27 tarball I ran:
```
./configure --disable-wayland --disable-systemd-services --with-ucd-dir=/usr/share/unicode-data && make
```
and it failed with:
```
panel.c:37:10: fatal error: gdk/gdkwayland.h: No such file or directory
   37 | #include <gdk/gdkwayland.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by fujiwarat** [comment]
You should delete panel.c

**Comment by fujiwarat** [comment]
See the error with detail. Obviously you don't understand if you disable wayland build, ibus won't need gdkwayland.h.
