### ISSUE TITLE
iBus can not working on any gtk4 apps with gnome 42

### ISSUE THREAD

**Issue by TaylorHere** [ibus/ibus#2406]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Manjaro Linux
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 42
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
any gtk4 apps
IBus version?: 
(Run `ibus version`)
IBus 1.5.26

Issue description:
Can not type Chinese in any gtk4 apps

Steps to reproduce:
1. using arch unstable channel
2. upgrade everything

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
no
Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no
Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
not tested

**Comment by fujiwarat** [comment]
You have to install IBus GTK4 module - /usr/lib*/gtk-4.0/4.0.0/immodules/libim-ibus.so and export GTK_IM_MODULE=ibus .

**Comment by chenxiex** [comment]
I still meet this problem in Manjaro Gnome, X11. I have already had libim-ibus.so in /usr/lib/gtk-4.0/4.0.0/immodules/ and GTK_IM_MODULE set to ibus. ibus can input words, but the panel isn't displayed and make choosing the word I want impossible.
