### ISSUE TITLE
Keyboard layout changes do not work in Plasma Wayland

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#2408]
Currently `ibus-ui-gtk3` runs `setxkbmap` command  internally to set XKB keymaps when IBus XKB engines are switched but `setxkbmap` does not work in Wayland desktops.
Now the Plasma desktop uses Wayland by default and when users try to switch IBus XKB engines in Plasma Wayland, keymap changes do not happen and users could be confused since Plasma desktop uses `ibus-ui-gtk3`.

This problem does not happen in Plasma Xorg desktop and GNOME desktops.

**Comment by fujiwarat** [comment]
I will implement another keymap settings in the next IBus but disable IBus XKB engines in Wayland display for the workaround and show a notification window until the implementation is done.

It means IBus panel icon won't be shown until users add input method engines with ibus-setup and systemsettigns5 is used to switch keymaps.

**Comment by fujiwarat** [comment]
I think the better way is to implement IBus InputContext to Plasma Wayland compositor.
https://bugs.kde.org/show_bug.cgi?id=453369

**Comment by ilya-fedin** [comment]
@fujiwarat I managed to launch IBus using text-input by creating the following desktop file:
```
[Desktop Entry]
Name=IBus Wayland
Exec=/usr/libexec/ibus-wayland
Icon=ibus
Terminal=false
Type=Application
NoDisplay=true
StartupNotify=false
X-KDE-Wayland-VirtualKeyboard=true
```

It's then available in system settings' virtual keyboard section:
![изображение](https://user-images.githubusercontent.com/17829319/202038740-1fd0365a-da64-4ef7-ba82-e1c3e8dcda68.png)

As soon as I chose IBus Wayland, ibus-wayland has started and space+period launches emoji chooser without any extra environment variables. kwin also tries to launch ibus-wayland on system start with this applied, so apparently ibus-wayland should be teached to launch ibus-daemon or ibus-daemon should get an XDG autostart desktop file to specify KDE-specific autostart phase (i'm not sure what phase should be specified though, it's just first idea came to my mind) in order to be launched before kwin attempts to start the virtual keyboard daemon (ibus-wayland). Specifying some shell script to .desktop file launching both ibus-daemon + ibus-wayland won't work as kwin won't be able to associate such a child process with the desktop file to give access to input-method which is treat as a privileged protocol.

**Comment by fujiwarat** [comment]
ibus-wayland does not handle space+period.
You should refer the above devel branch in fujiwarat/ibus and fujiwarat/ibus-qt

**Comment by ilya-fedin** [comment]
@fujiwarat doesn't it forward all the key events to ibus-daemon?

**Comment by ilya-fedin** [comment]
You're already using xkbcommon in ibus-wayland, wouldn't making it follow ibus layout rather than the one provided by fd be a better solution? You would need to change only one place rather than plugins for every toolkit.

**Comment by fujiwarat** [comment]
ibus-wayland does not connect to qt im module and it's not a right solution.

**Comment by ilya-fedin** [comment]
@fujiwarat I managed to connect it, that's what I described in https://github.com/ibus/ibus/issues/2408#issuecomment-1315973692. After those manipulations Qt applications access ibus just fine via text-input on Plasma Wayland.

**Comment by fujiwarat** [comment]
> @fujiwarat I managed to connect it,

Now ibus-qt can switch XKB but ibus-wayland does not. Also ibus-wayland cannot forward key events without QT APIs.

**Comment by ilya-fedin** [comment]
> Also ibus-wayland cannot forward key events without QT APIs.

Isn't this key event forwarding?
https://github.com/ibus/ibus/blob/506ac9993d5166196b7c4e9bfa9fb0f9d3792ffa/client/wayland/main.c#L472-L475

**Comment by fujiwarat** [comment]
I think zwp_input_method_context_v1_keysym() cannot forward keys to applications.
Also ibus-wayland uses protocol version 1 but I think it needs to connect wl_seat instead in Plasma.

**Comment by ilya-fedin** [comment]
@fujiwarat I believe either keysym or commit_string do that, what's the purpose of the protocol otherwise?

**Comment by fujiwarat** [comment]
>  I believe either keysym or commit_string do that

commit_string is a different purpose obviously.

> what's the purpose of the protocol otherwise?

I don't understand your question. I mean Plasma Wayland does not use zwp_input__method_v1 and ibus-wayland does not work at present.

**Comment by ilya-fedin** [comment]
> I mean Plasma Wayland does not use zwp_input__method_v1 and ibus-wayland does not work at present.

But it does! It's just privileged and won't work for random binaries, in https://github.com/ibus/ibus/issues/2408#issuecomment-1315973692 I explained how to make ibus-wayland to be detected by Plasma as privileged binary. Note that Plasma has to start ibus-wayland on its own, so ibus-daemon should already be running when you will do that, if you try to launch ibus-wayland manually after these actions, it will still day 'No input_method global'. If you will do that right, you will see ibus-wayland in the list of processes after you choose it as virtual keyboard.

**Comment by ilya-fedin** [comment]
ah, don't forget to log out & log in after creating the desktop file, kwin checks desktop files only on start it seems

**Comment by fujiwarat** [comment]
>  Note that Plasma has to start ibus-wayland on its own, so ibus-daemon should already be running when you will do that

I don't think it has to and ibus-wayland can connect to Wayland if ibus doesn't use version 1 as I explained.

**Comment by ilya-fedin** [comment]
https://invent.kde.org/search?search=zwp_input_method_context_v1&nav_source=navbar&project_id=2612&group_id=1568&search_code=true&repository_ref=master

**Comment by ilya-fedin** [comment]
> I don't think it has to

Well, I checked in practice and it works only when I let Plasma to start ibus-wayland on its own :man_shrugging: 
It works just fine using input_method_v1 and text-input then

**Comment by fujiwarat** [comment]
I  works using wl_seat without version 1 with my test.

**Comment by ilya-fedin** [comment]
> I works using wl_seat without version 1

What do you mean? Intercepting global input using just wl_seat?

**Comment by fujiwarat** [comment]
@ilya-fedin 
I evaluated ibus-wayland again and can get wl_keyboard from wl_seat in case interface == "wl_seat" in ibus-wayland:registry_handle_global() but I didn't notice zwp_input_method is still required to get the input method contexts. wl_keyboard does not handle the input methods. Very sorry for my confusion.

> @fujiwarat I managed to launch IBus using text-input by creating the following desktop file:

I confirmed your suggestion can enable ibus-wayland.

I tried to add /usr/lib/systemd/user/plasma-core.target.d/ibus.conf to run ibus-wayland and I modified ibus-wayland slightly to wait for wl_display_connect() but ibus-wayland could not get the zwp_input_method.
Seems ibus-wayland cannot start out of the Wayland compositor while I noticed the relative issue:
https://invent.kde.org/plasma/kwin/-/issues/17

Currently I notice the only replacing the virtual keyboard can enable ibus-wayland.

**Comment by ilya-fedin** [comment]
> Currently I notice the only replacing the virtual keyboard can enable ibus-wayland.

It seems virtual keyboard is just how KDE names input methods, so it's the UI where the user can choose the input method

> Seems ibus-wayland cannot start out of the Wayland compositor while I noticed the relative issue:

Yeah, it seems to be due to security, I guess starting ibus-daemon from inside ibus-wayland can make it work like a charm.

**Comment by fujiwarat** [comment]
> Yeah, it seems to be due to security, I guess starting ibus-daemon from inside ibus-wayland can make it work like a charm.

OK, I tried to run ibus-daemon from ibus-wayland:
https://github.com/fujiwarat/ibus/commit/0f514f026661a12df96d04aedea7e26c3a63b294

But I have no idea to get the input cursor position with ibus-wayland.
I looked at input-method and text-input client protocols and seems the input cursor position is not provided while the pointer position can be retrieved from wl_pointer.

**Comment by ilya-fedin** [comment]
I wonder how does e.g. fcitx handle that? It supports input-method protocol as well and even displays in Plasma settings out of the box: https://github.com/fcitx/fcitx5/blob/3a46edf0c83c40285e5fd8dc76f9b95990024e47/data/org.fcitx.Fcitx5.desktop.in.in#L15

**Comment by fujiwarat** [comment]
I think it uses Qt5 module and it may have a virtual keyboard for the desktop file.

**Comment by ilya-fedin** [comment]
It doesn't mix Qt5 module with the input-method implementation: it works either via input-method protocol or via its own D-Bus protocol through Qt5 module, just like IBus currently. I'm not sure what you mean by 'it may have a virtual keyboard for the desktop file', it declares itself as a virtual keyboard solely to being able to use input-method protocol.

**Comment by fujiwarat** [comment]
I observed key events are received from the Qt5 module in Plasma Wayland when I export QT_IM_MODULE.
I guess a similar GUI likes maliit keyboard and OSK does not require the input cursor position.

**Comment by ilya-fedin** [comment]
fcitx is not a virtual keyboard, it's input method like ibus...

**Comment by fujiwarat** [comment]
I know it and I mean to provide a tool GUI. Anyway I observed input cursor position works without the desktop file.
BTW, I also looked plasmoid panel APIs but seems they also don't provide the position API.

**Comment by ilya-fedin** [comment]
I ask because the protocol has `set_overlay_panel` method, so if you need some popup to be displayed near the cursor, you should use that method and the compositor will place it for you. Although that means that input-method implementation should be in the same process and use the same wayland connection as the code showing the popup, so you may need to merge ibus-wayland and ibus-daemon code.

**Comment by fujiwarat** [comment]
Input methods wish to put the candidate window near the input cursor and IBus manages the pop up position. But probably I need to think how to send the candidate list to the Wayland compositor since Wayland does not support to put a window at the specific position.

**Comment by fujiwarat** [comment]
OK, thank you. Probably set_overlay_panel method could fix the cursor position.

**Comment by jgcodes2020** [comment]
@fujiwarat How is progress on this? Is there anything that could perhaps be done by an MR?

**Comment by jgcodes2020** [comment]
> I wonder how does e.g. fcitx handle that? It supports input-method protocol as well and even displays in Plasma settings out of the box: https://github.com/fcitx/fcitx5/blob/3a46edf0c83c40285e5fd8dc76f9b95990024e47/data/org.fcitx.Fcitx5.desktop.in.in#L15

Plasma settings are handled via KConfig Modules: https://develop.kde.org/docs/features/configuration/kcm/

**Comment by ilya-fedin** [comment]
How is that related to text input position discussed in the message you quoted?

**Comment by jgcodes2020** [comment]
It *is* completely unrelated to the whole input position problem (which you said was already solved by `set_overlay_panel`), but the settings part should be a separate project.

**Comment by ilya-fedin** [comment]
I'm not quite sure why did you quote the message? It's about text input position.

**Comment by fujiwarat** [comment]
Sorry, I had worked on other critical issues. I will work on this issue next week.

**Comment by jgcodes2020** [comment]
Thank you for taking the time to work on this. If there's anything that I can do to help out (e.g. creating a settings module for Plasma), please let me know.

**Comment by fujiwarat** [comment]
I investigated set_overlay_panel function.
Seems `zwp_input_panel_surface_v1_set_overlay_panel(struct zwp_input_panel_surface_v1 *zwp_input_panel_surface_v1)` is provided by input-method protocol.
To get `zwp_input_panel_surface_v1`, `zwp_input_panel_v1_get_input_panel_surface(struct zwp_input_panel_v1 *zwp_input_panel_v1, struct wl_surface *surface)` is available.
But my understanding is, wl_surface is not provided by input-method protocol.

Seems maliit-keyboard does not use set_overlay_panel function.

Weston calls `wl_compositor_create_surface()` to get wl_surface.

I guess set_overlay_panel is available for compositor only?

**Comment by ilya-fedin** [comment]
You get wl_surface from the toolkit, you're using gtk in ibus-daemon, so you have to use `gdk_wayland_window_get_wl_surface` which is available when including `<gdk/gdkwayland.h>`, like this:
```
#include <gdk/gdk.h>

#ifdef GDK_WINDOWING_WAYLAND
#include <gdk/gdkwayland.h>
#endif
```

GDK_WINDOWING_WAYLAND implies gdk is built with wayland support (or the header won't exist), you have to first include gdk.h to get it defined of course.

Here are other Wayland specific functions for GdkWindow on Wayland: https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gdk/wayland/gdkwaylandwindow.h

**Comment by fujiwarat** [comment]
Thank you.
Currently the candidate window is made by GtkDisplayX11 popup window with `gtk_window_new (GTK_WINDOW_POPUP)` in Wayland:
https://github.com/ibus/ibus/blob/main/ui/gtk3/application.vala#L118

If I disable it for `gdk_wayland_window_get_wl_surface`, GtkDisplayWayland popup window takes focus in Wayland and seems Qt commits the preedt text with the focus changes and IBus cannot launch the candidate window.
E.g. QWidgetWindow::event(QEvent*) and QApplication::setActiveWindow(QWidget*) calls QinputMethod::commit()

Probably I need to find another GTK popup window not to take focus in Wayland or Qt.

**Comment by ilya-fedin** [comment]
Probably you need to do that after the native surface is created but before presented?

**Comment by ilya-fedin** [comment]
You probably have to subscribe to this signal: https://docs.gtk.org/gdk3/signal.Window.create-surface.html

**Comment by ilya-fedin** [comment]
Oops, looks like I've confused a bit, tat signal is about offscreen surface, it's possible to get native surface created with https://docs.gtk.org/gdk3/method.Window.ensure_native.html.

**Comment by ilya-fedin** [comment]
Apparently I wanted to suggest to subscribe to this signal: https://docs.gtk.org/gtk3/signal.Widget.realize.html
So the GdkWindow is created when calling ensure_native and getting wl_surface

**Comment by ilya-fedin** [comment]
It means the compositor has disconnected the application due to a protocol error, you can get the log of Wayland requests by setting `WAYLAND_DEBUG=1` environment variable for ibus-ui-gtk3, it also can be that the compositor logs the cause of the protocol error (`systemctl --user status plasma-kwin_wayland`).

**Comment by ilya-fedin** [comment]
KDE has channels where you can contact compositor developers and consult how they expect applications to work with the protocol: https://community.kde.org/Goals/Wayland#Contact. My guess is the order of the calls is the problem most likely, they should know the right order.

**Comment by ilya-fedin** [comment]
oh, i've looked at the code, looks like you're using a separate Wayland connection for your Wayland code. That is not going to work, you can't manipulate gtk's Wayland objects from your custom connection, you have to get wl_display from gtk: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/wayland/gdkwaylanddisplay.h#L48

**Comment by ilya-fedin** [comment]
yes, because you have a separate Wayland connection

**Comment by ilya-fedin** [comment]
to get the display in context of the window: https://docs.gtk.org/gdk3/method.Window.get_display.html
to get the display while not having a window pointer: https://docs.gtk.org/gdk3/type_func.Display.get_default.html

**Comment by fujiwarat** [comment]
I try to narrow my problem with a simple GTK popup without ibus codes.
This is the [main.c](https://github.com/ibus/ibus/files/11228060/main.c.txt)

If you type "abc" on `kwrite` text buffer, you will see the poup window is vanished.

**Comment by ilya-fedin** [comment]
It still uses its own connection, after making it use wl_display from gtk I see `wl_display@1.error(xdg_surface@37, 2, "the surface already has a role assigned input_panel_surface_v1")` what means there should be a deeper integration with gtk requiring new API from gtk side (I heard gtk4 already has such API though) to use custom shell integration for a surface (i.e. gtk should create a input_panel_surface_v1 object **instead** of xdg_surface object).

**Comment by fujiwarat** [comment]
> By the way, adding gdk_wayland_window_set_use_custom_surface before gdk_wayland_window_get_wl_surface makes it not crash and presents a positioned window to me which has no content.

I don't know how to create a custom surface.

I tried GTK4 [main.c](https://github.com/ibus/ibus/files/11261276/main.c.txt) but it causes the same error. Also GTK4 window seems not a popup window so taking the focus is not good for the IBus candidate popup window. GtkPopover seems to require a parent GtkWidget.

Reading https://discourse.gnome.org/t/is-there-subsurface-support-for-wayland/11215/12 , it would be complicated for me to get wl_surface.

**Comment by ilya-fedin** [comment]
> I don't know how to create a custom surface.

I'm not quite sure what you mean by this, I've just added a `gdk_wayland_window_set_use_custom_surface(window);` line

**Comment by ilya-fedin** [comment]
you have to move gtk_init before that line of course

**Comment by fujiwarat** [comment]
@ilya-fedin Thank you very much. Now I confirmed set_overlay_panel() works with GTK3.

**Comment by fujiwarat** [comment]
Now the very basic implementation is done in https://github.com/fujiwarat/ibus/commits/wayland-xkb3

The current problem is:
1. Unexpected repeating keys happen. Maybe there is a problem to convert the virtual keysyms.
2. Panel menu is activated only when an input context is enabled because GtkMenu is generated with GdkDislpayX11 but GdkDevice pointer is generated with GdkDisplayWayland.
3. Super-space is not implemented yet.

**Comment by ilya-fedin** [comment]
Oh well... You can't use GtkStatusIcon on Wayland as it uses XEmbed under the hood. To make a Wayland-friendly context menu with SNI (StatusNotifierItem which you seem to refer to as AppIndicator), you have to expose the menu using the DBusMenu protocol (the libdbusmenu library family is probably of help here) via the Menu D-Bus property. This also means you can have only one menu, yes. There's ItemIsMenu property to make the menu appear on left click.

**Comment by fujiwarat** [comment]
Thank you. Probably I need to investigate how to implement DBusMenu later. Seems my AppIndicator uses GtkMenu while it handles "Activate" and "ContextMenu" GDBusInterfaceMethodCallFunc .

**Comment by ilya-fedin** [comment]
I recommend to look at https://github.com/AyatanaIndicators/libayatana-appindicator/blob/master/src/app-indicator.c as an example of dbusmenu usage (or you can use lib(ayatana-)appindicator on Wayland given that you probably won't have any action to do at Activate, so libappindicator API should be enough probably)

**Comment by fujiwarat** [comment]
@ilya-fedin Thank you for the reference for the dbusmenu.
Now dbusmenu is implemented in https://github.com/fujiwarat/ibus/commits/wayland-xkb3

I remembered that IBus has been used the GtkMenu positioning instead of the dbusmenu because that way provides the both the activate and context menus.
Seems dbusmenu provides the same menu on either left or right click because "Menu" D-Bus method only is provided.

Now the workaround is to use the middle mouse click and "SecondaryActivate" D-Bus method to toggle the activate and context menus.

**Comment by fujiwarat** [comment]
Thank you for the interesting info. Probably I'm fine the current workaround to toggle menus with the mouse middle click.

The some panel icons in Plasma Wayland can shows the black activate menu and white context menu. Maybe it accesses the KDE APIs.
E.g. ![Network icon](https://github.com/ibus/ibus/assets/105929/a865fce8-753c-46ac-baaa-7139b2f5d459)

**Comment by ilya-fedin** [comment]
Yeah, those are plasmoids (shell extensions)

**Comment by fujiwarat** [comment]
I see Xwayland is running in Plasma Wayland but `wl_keyboard_listener.key()` is not called with xterm.
I guess I need to use XIM in Wayland with exporting `XMODIFIERS=@im=ibus`. 

Do you know how to run `IBus Wayland` without running systemsettings5?
If I write the IBus desktop file in `$HOME/.config/kwinrc`, the KDE UI enables `IBus Wayland` but I don't know how to run `IBus Wayland` and I have to log in the session again at the moment.
```
[Wayland]
InputMethod[$e]=/usr/share/applications/org.freedesktop.IBus.Panel.Wayland.Gtk3.desktop
```

**Comment by ilya-fedin** [comment]
So I monitored D-Bus with Bustle after applying the settings with systemsettings5 and got this
![изображение](https://github.com/ibus/ibus/assets/17829319/64bc8ca4-b575-4a6f-8df5-c35be7475ae6)
:1.64 is systemsettigns5 itself, so I assume kwin listens for a signal with such object path/interface globally (apparently hidden by the KConfig library API).

**Comment by fujiwarat** [comment]
@ilya-fedin Great, thank you.

**Comment by fujiwarat** [comment]
I implemented IME switcher popup window(Super-space shortcut key).

**Comment by fujiwarat** [comment]
@ilya-fedin I have two issues.
1. ibus-wayland causes a infinite loop of key events.
https://github.com/fujiwarat/ibus/blob/wayland-xkb3/client/wayland/ibuswaylandim.c#L620
ibus-wayland uses the async key events with `ibus_input_context_process_key_event_async()` currently and forwards the key events with `zwp_input_method_context_v1_key()` in case ibus does not handle the events and the same key events can be fallen back to `wl_keyboard_listener.key()` again but time and serial numbers are updated and ibus cannot recognize if the key events are received previously.
I'd think if the Wayland server does not send the key events to the input method with `ZWP_INPUT_METHOD_CONTEXT_V1_KEY` flag.

2. ibus-wayland cannot effect `set_overlay_panel()` with X applications.
https://github.com/fujiwarat/ibus/blob/wayland-xkb3/client/wayland/ibuswaylandim.c#L1267
Seems `zwp_input_panel_surface_v1_set_overlay_panel()` can be effective in case `zwp_input_method_v1_listener.activate()` is called. We use `XMODIFIERS=@im=ibus` to get key events in ibus-x11 from XIM but `zwp_input_method_v1_listener.deactivate()` is called when X applications likes xterm gets the input focus and then seems `set_overlay_panel()` always hide the popup window.
GNOME Wayland does not use  `set_overlay_panel()` because the compositor handles both key events and the popup window and sends the key events to ibus-daemon directly even if X applications get the focus. My understandnig is the Wayland input-method protocol cannot send key events if X applications get the focus and I use `XMODIFIERS=@im=ibus`.

**Comment by ilya-fedin** [comment]
> 2\. ibus-wayland cannot effect `set_overlay_panel()` with X applications.

The Wayland protocol is for Wayland applications, so you have to have a process with Wayland UI (gtk operating with Wayland backend) that gets events via the Wayland protocol and a process with X11 UI (gtk operating with X11 backend) that gets events from XIM/toolkit plugins. I guess X11 UI could be started on demand?

> 1. ibus-wayland causes a infinite loop of key events.

Why do you listen for wl_keyboard events? I don't think [that's right](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/text-input/text-input-unstable-v1.xml#L34-39).

**Comment by fujiwarat** [comment]
>  I guess X11 UI could be started on demand?

I mean ibus-wayland always uses GTK popup window and sends the wl_surface so I don't use X11 UI but set_overlay_panel() seems to hide the popup when X11 applications get the focus. On the other hand, I use ibus-x11 to get the key events with XIM because my undersntanding is the Wayland protocol cannot send the key events of the X11 applications.

> Why do you listen for wl_keyboard events? I don't think that's right.

Could you elaborate your suggestion?
I think `zwp_input_method_context_v1_listener` does not provide the key events and use `wl_keyboard_listener.key()` to get the key events.
My understanding is text-input protocol is used by the Wayland compositor and it does not provide the key event listener.
If I don't use the Wayland input-method protocol, I think IBus needs to use Qt IM module to get the application's key events and it works with the async key events currently.

**Comment by ilya-fedin** [comment]
> On the other hand, I use ibus-x11 to get the key events with XIM because my undersntanding is the Wayland protocol cannot send the key events of the X11 applications.

You have to also use it for the popup on X11 applications

> I think `zwp_input_method_context_v1_listener` does not provide the key events

As far as I understand, you're supposed to use this: "The information about entered text is sent to the text_input object via the pre-edit and commit events."

**Comment by ilya-fedin** [comment]
Oh, I'm looking the wrong protocol

**Comment by ilya-fedin** [comment]
Isn't this event for getting the entered text? I guess you're not supposed to handle individual key events
https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/main/unstable/input-method/input-method-unstable-v1.xml#L208-219

**Comment by ilya-fedin** [comment]
Ah, I see, it has grab_keyboard method... Maybe look at what fcitx dpes?
https://github.com/fcitx/fcitx5/blob/master/src/frontend/waylandim/waylandimserver.cpp

**Comment by fujiwarat** [comment]
> Ah, I see, it has grab_keyboard method... Maybe look at what fcitx does?

I guess the `keyboard_.reset(ic_->grabKeyboard())` gets the wl_keyboard:
https://github.com/fcitx/fcitx5/blob/master/src/lib/fcitx-wayland/input-method/zwp_input_method_context_v1.cpp#L88

And this would be `wl_keyboard_listener.key()`
```
    keyboard_->key().connect(
        [this](uint32_t serial, uint32_t time, uint32_t key, uint32_t state) {
            keyCallback(serial, time, key, state);
        });
```

I guess fcitx uses the sync key event API and it works fine but ibus-wayland uses async API and use `zwp_input_method_context_v1_key()` for the result at the moment.

> Isn't this event for getting the entered text? I guess you're not supposed to handle individual key events

The surrounding_text API is used for the output text but input method also needs to get the key events before any text is inserted into the application so surrounding_text API is used for the other purposes.

**Comment by ilya-fedin** [comment]
> I guess fcitx uses the sync key event API

I don't quite what you mean by "the sync key event API", I don't see any other API in the protocol

I see it uses zwp_input_method_context_v1_key as well:
https://github.com/fcitx/fcitx5/blob/master/src/frontend/waylandim/waylandimserver.cpp#L472
https://github.com/fcitx/fcitx5/blob/master/src/lib/fcitx-wayland/input-method/zwp_input_method_context_v1.cpp#L93

**Comment by fujiwarat** [comment]
> I don't quite underdtand what you mean by "the sync key event API", I don't see any other API in the protocol

You could see the ibus-wayland implementation in `wl_keyboard_listener.key()`.
https://github.com/fujiwarat/ibus/blob/wayland-xkb3/client/wayland/ibuswaylandim.c#L672
With the asynchronized API,  `wl_keyboard_listener.key()` does not wait for the return of IBus async API `ibus_input_context_process_key_event_async()` and the callback will call `zwp_input_method_context_v1_key()` with a time lag later in case that the input method does not process the key events.
IBus has been used the async API because each language input method engine spend time to handle the key events and IBus uses D-Bus methods to send the key events to each input method engine with a D-Bus timeout.
Currently IBus synchronized API has a problem with commit_text API and IBus asynchronized API  has been used.

So I mentioned I'd think if the Wayland server does not send the key events to the input method with ZWP_INPUT_METHOD_CONTEXT_V1_KEY flag. It would be a Plasma compositor problem not to check the time and serial number and send the key event to input method again.


>>  On the other hand, I use ibus-x11 to get the key events with XIM because my undersntanding is the Wayland protocol cannot send the key events of the X11 applications.
> You have to also use it for the popup on X11 applications

Now I'm thinking one possible solution; ibus-x11 forwards the key events to the Wayland compositor using the Wayland text-input protocol from XIM server and ibus-wayland receives the key events using the Wayland input-method protocol and hope `set_overlay_panel()` works fine.

**Comment by ilya-fedin** [comment]
> With the asynchronized API, `wl_keyboard_listener.key()` does not wait for the return of IBus async API

Wayland is completely asynchronous, I'm hardly doubt it waits for your C function to complete. But you can always spawn a nested event loop and check that.

**Comment by fujiwarat** [comment]
> Wayland is completely asynchronous, I'm hardly doubt it waits for your C function to complete. But you can always spawn a nested event loop and check that.

As I noted, the problem is that the same key events can be fallen back to `wl_keyboard_listener.key()` again but time and serial numbers are updated and ibus cannot recognize if the key events are received previously.
You can reproduce the issue with that IBus Git branch. Once you type Ctrl key, `wl_keyboard_listener.key()` sends the key twice. If you type p keys multiple times, during pressing Ctrl key, it causes an infinite loop of key events.
I think the problem does not hapepn if sync key events are used.

**Comment by fujiwarat** [comment]
> I'll repeat again: what prevents you from checking it's due to async API or not? 

ibus-wayland has _use_sync_mode internal variable. If the value is TRUE, the problem does not happen.

> I'd rather assume it's because you modify the `state` argument 

I may not understand the timing to call `xkb_state_update_key()`.

I think ibus-wayland does not modify the `state` argument of `wl_keyboard_listener.key()` because ibus-wayland just checks the state for KeyPress or KeyRelease.
ibus-wayland modifies  `struct xkb_state` in both sync and async mode so I think the problem is not relative with `struct xkb_state`.

The problem is that the compositor sends the key event with `wl_keyboard_listener.key()` and compositor sends the same key event again with `wl_keyboard_listener.key()` before the async `zwp_input_method_context_v1_key()` and `xkb_state_update_key()` are called.
I guess that the compositor might have a time out during pressing a modifier  key.

**Comment by ilya-fedin** [comment]
Wouldn't such a workaround work?
```
diff --git a/client/wayland/ibuswaylandim.c b/client/wayland/ibuswaylandim.c
index 448d5866..a926f3c5 100644
--- a/client/wayland/ibuswaylandim.c
+++ b/client/wayland/ibuswaylandim.c
@@ -84,13 +84,8 @@ struct _IBusWaylandIMPrivate
 
 struct _IBusWaylandKeyEvent
 {
-    struct zwp_input_method_context_v1 *context;
-    uint32_t serial;
-    uint32_t time;
-    uint32_t key;
-    enum wl_keyboard_key_state state;
-    uint32_t modifiers;
-    IBusWaylandIM *wlim;
+    GMainLoop *loop;
+    gboolean retval;
 };
 typedef struct _IBusWaylandKeyEvent IBusWaylandKeyEvent;
 
@@ -590,41 +585,18 @@ _process_key_event_done (GObject      *object,
     IBusInputContext *context = (IBusInputContext *)object;
     IBusWaylandKeyEvent *event = (IBusWaylandKeyEvent *) user_data;
     GError *error = NULL;
-    gboolean retval = ibus_input_context_process_key_event_async_finish (
+    event->retval = ibus_input_context_process_key_event_async_finish (
             context,
             res,
             &error);
-    IBusWaylandIMPrivate *priv;
 
     if (error != NULL) {
         g_warning ("Process Key Event failed: %s.", error->message);
         g_error_free (error);
     }
-    g_return_if_fail (event);
-    g_return_if_fail (IBUS_IS_WAYLAND_IM (event->wlim));
 
-    priv = ibus_wayland_im_get_instance_private (event->wlim);
-    /* Should ignore key events after input_method_deactivate() is called
-     * even if context->ref_count is not 0 yet but priv->ibuscontext is null
-     * because of the async time lag.
-     */
-    if (priv->ibuscontext) {
-        retval = ibus_wayland_im_post_key (event->wlim,
-                                           event->key,
-                                           event->modifiers,
-                                           event->state,
-                                           retval);
-    }
-    /* Check retral from ibus_wayland_im_post_key() */
-    if (priv->ibuscontext && !retval) {
-        zwp_input_method_context_v1_key (event->context,
-                                         event->serial,
-                                         event->time,
-                                         event->key,
-                                         event->state);
-    }
+    g_main_loop_quit (loop);
 
-    g_free (event);
 }
 
 
@@ -643,6 +615,7 @@ input_method_keyboard_key (void               *data,
     const xkb_keysym_t *syms;
     xkb_keysym_t sym;
     uint32_t modifiers;
+    gboolean retval;
 
     g_return_if_fail (IBUS_IS_WAYLAND_IM (wlim));
     priv = ibus_wayland_im_get_instance_private (wlim);
@@ -670,28 +643,13 @@ input_method_keyboard_key (void               *data,
         modifiers |= IBUS_RELEASE_MASK;
 
     if (_use_sync_mode) {
-        gboolean retval =
-            ibus_input_context_process_key_event (priv->ibuscontext,
-                                                  sym,
-                                                  code,
-                                                  modifiers);
-        retval = ibus_wayland_im_post_key (wlim, key, modifiers, state, retval);
-        if (!retval) {
-            zwp_input_method_context_v1_key (priv->context,
-                                             serial,
-                                             time,
-                                             key,
-                                             state);
-        }
+        retval = ibus_input_context_process_key_event (priv->ibuscontext,
+                                                       sym,
+                                                       code,
+                                                       modifiers);
     } else {
         IBusWaylandKeyEvent *event = g_new (IBusWaylandKeyEvent, 1);
-        event->context = priv->context;
-        event->serial = serial;
-        event->time = time;
-        event->key = key;
-        event->modifiers = modifiers & ~IBUS_RELEASE_MASK;
-        event->state = state;
-        event->wlim = wlim;
+        event->loop = g_main_loop_new (NULL, FALSE);
         ibus_input_context_process_key_event_async (priv->ibuscontext,
                                                     sym,
                                                     code,
@@ -700,6 +658,19 @@ input_method_keyboard_key (void               *data,
                                                     NULL,
                                                     _process_key_event_done,
                                                     event);
+        g_main_loop_run (event->loop);
+        retval = event->retval;
+        g_main_loop_unref (event->loop);
+        g_free (event);
+    }
+
+    retval = ibus_wayland_im_post_key (wlim, key, modifiers, state, retval);
+    if (!retval) {
+        zwp_input_method_context_v1_key (priv->context,
+                                         serial,
+                                         time,
+                                         key,
+                                         state);
     }
 }
 
```

**Comment by fujiwarat** [comment]
Thank you for the suggestion. I will try to fix the issue.

**Comment by fujiwarat** [comment]
Now the async key event issue is fixed.

**Comment by fujiwarat** [comment]
@ilya-fedin I have another question.
When I type Alt-Tab keys several times to switch application focuses in Plasma Wayland desktop session, `zwp_input_method_v1_listener.activate()` sends different `zwp_input_method_context_v1` and IBus cannot recognize if the context is previously used.
Do you have any ideas to get the unique input context until the application exits in the Wayland input-method protocol #1? I wish to keep some states by input context.

E.g. If an API `zwp_input_method_context_v1_get_id()` will be provided, input-methods can recognize if the context is used previously.

**Comment by ilya-fedin** [comment]
I don't know what to suggest rather than asking the fcitx developer (he actively participated in the development of text-input-v4 IIRC and generally in related discussions) or kwin developers. The conversation room [I linked earlier](https://github.com/ibus/ibus/issues/2408#issuecomment-1505414409) has both of them.

**Comment by fujiwarat** [comment]
@ilya-fedin Thank you!
I will ask kwin later.

**Comment by ilya-fedin** [comment]
(I meant these ones)
![изображение](https://github.com/ibus/ibus/assets/17829319/2722e859-415b-41e1-88c9-74a01b12cc32)

**Comment by fujiwarat** [comment]
Right, I noticed your link. Thank you.

**Comment by fujiwarat** [comment]
The left issues are:
1. Migrate XIM applications to ibus-wayland
1. Panel menu without IBus input focus
1. Several misc issues

I separate those issues issue from this issue. I will work on them for 1.5.30

@ilya-fedin Thank you for your suggestions.
