### ISSUE TITLE
ctrl + ; No emoji picker, only e displays

### ISSUE THREAD

**Issue by daudix-UFO** [ibus/ibus#2409]
Fedora 36

Gnome 42.0

Wayland

IBus 1.5.26

Issue description:
ctrl + ; not displays emoji picker

Steps to reproduce:
1. Open any gtk app
2. click ctrl + e or ctrl + ;
3. See, there is no moji picker, only underlined "e"

**Comment by fujiwarat** [comment]
"e" is a preedit text and you have to type any annotation strings and space key likes "smile".
