### ISSUE TITLE
Surrounding text is not updated when changing tabs (in gedit, gnome-text-editor)

### ISSUE THREAD

**Issue by PhilippeRo** [ibus/ibus#2423]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Fedora 36

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
gnome 42

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Gedit, gnome-text-editor

IBus version?: 
(Run `ibus version`)
1.5.26

Issue description:
When using gedit or gnome-text-editor, say you have two tabs open with some text in each.
If you are on Tab 1 and click on Tab 2, surrounding text is not updated / do_set_surrounding_text() not called.
I use python to write my IM. This happens in gedit, gnome-text-editor at least.

Steps to reproduce:
See above

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes, it does not change anything

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
None

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

**Comment by PhilippeRo** [comment]
I'd like to find a solution by myself to this bug as having a reliable do_set_surrounding_text() could be really helpful for IM engine developers.
Do you have any pointer that could help me? Is the problem in IBus, in the applications or in the toolkit, in your opinion?
Thanks.

**Comment by PhilippeRo** [comment]
I read the code and did some tests. I might have found the origin of the problem.

First, I should mention two things:
- I use gtk3 IBus client (I set GTK_IM_MODULE=ibus and launch gedit, the test application) ;
- the problem is broader than I first reported and in fact could be rephrased as "No update to surrounding text on focus in events" since it happens when we change tab, when we  create a new tab or when we switch from one application to another; in every case, the surrounding text is set to the last set by a commit or a key press (the only two cases in which the text is updated) in the previous window/widget.

Reading the code of client/gtk3/ibusimcontext.c and src/ibusinputcontext.c the problem seems to be this:
ibus_im_context_focus_in() calls _request_surrounding_text() - as it should - which in turn emits a signal to request the widget (the one which got the focus) to return its current text. This triggers the virtual method of GtkIMContext::set_surrounded_with_selection() which finally calls ibus_im_context_set_surrounding_with_selection() in (src/ibusinputcontext.c) with this check before it sends the message over DBus:
    if (cursor_pos != priv->surrounding_cursor_pos ||
        anchor_pos != priv->selection_anchor_pos ||
        priv->surrounding_text == NULL ||
        g_strcmp0 (text->text, priv->surrounding_text->text) != 0) 

This seems to never work after a focus-in event since the text (returned by the widget) is always the same as priv->surrounding_text and for a good reason: the widget was focused out and therefore has not been updated since it focused out or was created (or in some very rare instances).

As a consequence, surrounding text is almost never updated when the focus switches between widgets (be they in the same application or not).

When using gtk3 IBus client, I managed to fix the problem by caching the surrounding text values for each context on the server side (in bus/inputcontext.c).
Each time _ic_set_surrounding_text() is invoked, the values are cached (even without the focus).
Then, as soon as an input context is activated, after setting its engine in bus_input_context_set_engine(), bus_engine_proxy_set_surrounding_text() is called unconditionally with cached values to update the text for the IM engine.

One of the advantages I see, is that we always have surrounding text updated after focus-in and if the test in ibus_im_context_set_surrounding_with_selection() works, because there was a change, then it can still update everything.

I tested it and it solves the issues reported (but it might introduce new bugs that my shallow understanding of IBus inner workings missed).

The result of these changes is in the pull request:
https://github.com/ibus/ibus/pull/2434

If I went in the wrong direction or if you think this can be improved please let me know.

Of course this only works for ibus client modules. With native gtk ones, used by default on wayland, it is a different story. The same problems appear after a focus-in (and partly because of the same kind of check) but it is not as easy to solve. I will file a bug for these modules in GTK.

**Comment by PhilippeRo** [comment]
Just for the record, GTK has fixed this issue in its client (https://gitlab.gnome.org/GNOME/gtk/-/issues/5106).

**Comment by fujiwarat** [comment]
Thank you for the link and info. I will evaluate the issue when I get time.

**Comment by fujiwarat** [comment]
> Just for the record, GTK has fixed this issue in its client (https://gitlab.gnome.org/GNOME/gtk/-/issues/5106).

I think that patch is bad because preedit is broken by many reset signals and should be reverted and even your issue is not fixed.

**Comment by PhilippeRo** [comment]
Thanks for the information. I have to confess that I could not test the patch as my distro is too old. Now that fedora 37 is in Beta, I will (though I know the patch will not work since you tested it and you are more skillfull than I) and reopen the bug report.
Do not hesitate to comment as I can really fathom how the whole gtk/mutter/gnome-shell/ibus chain works.
I suppose I could contribute to the bug report with a test IM plugin (unless there is already one around).

**Comment by fujiwarat** [comment]
Could you test the linked patch?
I will evaluate GNOME Wayland later.

**Comment by PhilippeRo** [comment]
I tested your branch "surrounding", but there seems to be a problem since I don't get surrounding text updates any more from gedit when it's started with the patched gtk3 client (and I made sure it uses the patched client and the patched library).

There was only one case when I got updates while typing. The IM engine was started with a gedit page already open. But then, I created a new tab and whatever I did (click somewhere in a text, type, ...) the IM module didn't receive any surrounding-text update any more.

**Comment by PhilippeRo** [comment]
> > Just for the record, GTK has fixed this issue in its client (https://gitlab.gnome.org/GNOME/gtk/-/issues/5106).
> 
> I think that patch is bad because preedit is broken by many reset signals and should be reverted and even your issue is not fixed.

I updated to fedora 37 and tested it. It doesn't fix everything but there is one area of progress: when you switch tab, you do get surrounding text updates.
But it doesn't fix the cases when you switch between applications or when you open a new tab (you don't get an "empty" update).

**Comment by PhilippeRo** [comment]
Just for the record, I tried the newest fedora package (1.5.27-2) that is said to include patches for surrounding text this morning. But it does not change anything.

**Comment by fujiwarat** [comment]
> But it doesn't fix the cases when you switch between applications or when you open a new tab (you don't get an "empty" update).

I think you need to bind "set-surrounding-text" signal in your engine. Set surrounding text event is not same timing with focus-in/out event.

**Comment by PhilippeRo** [comment]
I use do_set_surrounding_text() in my engine (at the very end of the file); does it not do the same as connecting to the signal?
I will try though.

BTW: I updated the bug against gtk with a comment.

**Comment by fujiwarat** [comment]
> I use do_set_surrounding_text() in my engine (at the very end of the file); does it not do the same as connecting to the signal?
I will try though.

Then probably you don't use the IBus GTK modules. It might be good to try non-GNOME desktops likes XFCE.

> BTW: I updated the bug against gtk with a comment.

I will update it and please wait for it.

**Comment by PhilippeRo** [comment]
As for using the GTK module, I am pretty sure I did since to be certain of it I added a g_print() statement on module loading, and it does appear in the console when I launch "GTK_IM_MODULE=ibus gedit".
But maybe I'm doing something wrong indeed.

Anyway, thanks, I'll wait for further instructions.

**Comment by fujiwarat** [comment]
Probably I think you need to call ibus_engine_get_surrounding_text() with focus-in event and then the set-surronding-text signal is always called after the focus-in event.

**Comment by PhilippeRo** [comment]
I can confirm that it did the trick, thanks a lot!
With your patch, it has indeed become necessary to call ibus_engine_get_surrounding_text() in focus-in. If you don't, you have no update whatsoever, if you do it works (switching tabs, opening a new one, closing one tab).

There seems to be just one small issue when you click on the title bar of a window to switch between two (I tried with two instances of "GTK_IM_MODULE=ibus gedit -s"). There is no update apparently while switching from a window with text "aaaa" to another with "bbbb".

I suppose that the necessity to call ibus_engine_get_surrounding_text() in focus-in should be documented somewhere just like the necessity to call the same function in enable() is (though the latter has become useless since focus-in is always called after enable()).

If I may offer a suggestion, I wonder if it could not be made more persistent with a gobject property for example? From a developper's point of view it seems a bit awkward to have to call a function regularly that return values, the IM module should not use as they are stale (I checked, the returned values of ibus_engine_get_surrounding_text() in focus-in are most of the time the values of the previous context).

But it's a detail I suppose, now it has improved (minus the glitch I mentioned before). Let's hope GTK developpers will be as swift as you to fix their client.
Again thanks a lot.

**Comment by fujiwarat** [comment]
Thank you for the tests.

> There seems to be just one small issue when you click on the title bar of a window to switch between two (I tried with two instances of "GTK_IM_MODULE=ibus gedit -s"). There is no update apparently while switching from a window with text "aaaa" to another with "bbbb".

I updated ibus_input_context_set_surrounding_text() again in the patch to fix this issue and GNOME issue.

> I suppose that the necessity to call ibus_engine_get_surrounding_text() in focus-in should be documented 

OK, probably we could update the API comments.

> If I may offer a suggestion, I wonder if it could not be made more persistent with a gobject property for example? 

Do you mean to set a property of IBusEngine constructor and IBusEngine always calls the get_surrounding_text() with the property and focus-in events? Probably we could implement it.

> IM module should not use as they are stale (I checked, the returned values of ibus_engine_get_surrounding_text() in focus-in are most of the time the values of the previous context).

IM module always send the fresh surrounding text but IM engines's  ibus_engine_get_surrounding_text()  does not receive the real time value. It is the current specification because to get the value, the engine calls D-Bus method to ibus-daemon to IM client and IM clients return the value with D-Bus method to ibus-daemon to the engine - It should take too much time and can be a D-Bus time out.

**Comment by ermshiperete** [comment]
Thanks for your work on this @fujiwarat !

I did some testing of https://github.com/fujiwarat/ibus/commit/7bbcce66e1ca694b7a62553327161290bf4ee283 with a slightly modified version of ibus-braille.py from #2054 (attached). (The difference is that I also call `get_surrounding_text` in `do_focus_in`). Tested under Ubuntu 22.04 with X11.

Unfortunately it's still not quite working right :disappointed:. Here's what I did:

- start ibus-braille.py
- opened LO Writer
- added the text "uvwxyz"
- opened gedit
- added the text "abcdef".

The console output of ibus-braille.py correctly shows "abcdef" with cursor/anchor 6/6. Good!

But then:
- switch back to Writer
--> ibus-braille.py still gets "abcdef" 6/6. 
- in Writer, press the Home key
--> ibus-braille.py gets "uvwxyz" 6/6
- press End key 
--> ibus-braille.py gets "uvwxyz" 0/0.

This looks like it's always one step behind.

**Comment by PhilippeRo** [comment]
You seems to have had some feedback that it worked (surprisingly the messages don't appear in this thread though I received a mail notification) and I can confirm that your patch fixed it. Now surrounding text works flawlessly as far as I can tell.
Thank you so much for you work and thank you also for making sure it works in Wayland (I read the bug reports you opened against gtk and gnome-shell).

About the idea of having a gobject property instead of calling the function  ibus_engine_get_surrounding_text(), what you propose is what I had in mind. It would make things a bit easier I think.
Would you like me to open another bug?

**Comment by fujiwarat** [comment]
Yes, please report your request if you wish to implement it.
