### ISSUE TITLE
Standalone binary and ibus as input mechanism 

### ISSUE THREAD

**Issue by anmathew** [ibus/ibus#2427]
Please consider this question:

I've been working on an application  which grabs the underlying keyboard with a `ioctl(fd, EVIOCGRAB, 1)`, intercepts and translates the keycode events, example: from `manu` to `മനു` et al. (kind of like[ this gist.](https://gist.github.com/matthewaveryusa/a721aad80ae89a5c69f7c964fa20fec1))

I'd like to further explore if it is possible to hook this binary up with ibus and have this developed as an input mechanism. My binary would intercept and generate the payload that needs to be handed over, ibus IME does the rest.

Any pointers would be much appreciated, thanks!

**Comment by fujiwarat** [comment]
Probably I think you could refer https://github.com/ibus/ibus-tmpl
