### ISSUE TITLE
Changing "candidates orientation" setting in "IBus Preferences" to "Horizontal" doesnt work

### ISSUE THREAD

**Issue by Rinkaa** [ibus/ibus#2437]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Linux Mint 21 Cinnamon

Which desktop environment and version?: 
Cinnamon 5.4.10

Which session type?: 
X11

Which application and version?: 
All applications

IBus version?: 
IBus 1.5.26
Installed via apt: ibus 1.5.26-4

Issue description:
I'm using ibus-rime.
The candidate orientation is always vertical even when I set it to horizontal in the preferences window.
Other settings("Show property panel", "Use custom font") work as expected.

Steps to reproduce:
1. Open "IBus Preferences" window and switch the "Candidates orientation" then close the window. It doesnt work. Changing "Show property panel" or "Use custom font" still work as excepted.

![图片](https://user-images.githubusercontent.com/8685221/185172614-28bff681-9c8e-4ed1-a59e-df03b6ed82fd.png)

![图片](https://user-images.githubusercontent.com/8685221/185174121-a08533d8-c48d-482f-b470-083db8c1caf6.png)

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes, the issue persists

Do you see any errors when you run ibus-daemon with the verbose option?:
(Maybe unrelated though)
```
(ibus-ui-gtk3:148050): IBUS-WARNING **: 23:04:29.006: panel.vala:280: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:148050): IBUS-WARNING **: 23:04:29.031: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
E0817 23:04:29.046871 148075 deployment_tasks.cc:673] boost::filesystem::status: Permission denied: "/tmp/rime.ibus.ERROR"

(ibus-ui-gtk3:148050): Gdk-CRITICAL **: 23:04:30.046: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes, I can reproduce the problem on a new user account

**Comment by HelyaHsiung** [comment]
Hello! Gnome Shell Extension: `Ibus-Tweaker` or `Customize IBus` both take effect on this problem.

**Comment by fujiwarat** [comment]
It would be ibus-rime issue. ibus-anthy works fine.
