### ISSUE TITLE
[kde plasma] ibus only changes keyboard layout when focus is given to a text input

### ISSUE THREAD

**Issue by foormea** [ibus/ibus#2441]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
KDE Neon 22.04 5.24

Which desktop environment and version?: 
KDE Plasma Version: 5.25.4
KDE Frameworks Version: 5.97.0
Qt Version: 5.15.5

Which session type?: 
x11

Which application and version?: 
n/a

IBus version?: 
IBus 1.5.26

Issue description:
Ibus only changes keyboard layout after focus is given to a text input.
If I switch layouts and focus is currently not on a text input, the change is not reflected in the systray icon, and the change will actually happen next time focus is on a text input.

This is annoying because the layout indicator doesn't always reflect what is actually selected, because it makes using shortcuts awkward (I have to make sure that my "base" keymap is selected and activated for shortcuts to work).
Also it is impossible to switch layouts in Plasma's log-on screen.

STEPS TO REPRODUCE
1. I configured 3 layouts in ibus: EN US qwerty, FR FR azerty, EN dvorak int'l dead keys.
2. I switch layouts using super-space.
3. The problem that I described happens.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by mike-fabian** [comment]
Here is a video  showing the same problem on XFCE (ibus-1.5.27-1.fc37.x86_64):

https://user-images.githubusercontent.com/2330175/190072844-b0d5e7ef-162b-4121-8256-4ad478c0b1be.mp4

**Comment by mike-fabian** [comment]
Here is a video on Gnome Xorg (Fedora 37) showing that on Gnome the input methods indictor in the panel is updated immediately after changing the input method with Super+Space,  even when nothing has input focus:

https://user-images.githubusercontent.com/2330175/190126532-93fb3d48-d491-40c6-b3c3-ac9e2a0b7b40.mp4

**Comment by fujiwarat** [comment]
IBus requires input contexts and furthermore says, IBus won't support a global XKB in Plasma Wayland as the specification.
