### ISSUE TITLE
ibus panel places wrong in gtk4 program

### ISSUE THREAD

**Issue by CongTiankong** [ibus/ibus#2449]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Archlinux latest, also tested Fedora 37

Which desktop environment and version?: 
GNOME 42/43

Which session type?: 
X11 and Wayland

Which application and version?: 
many gtk3 and gtk4 applications

IBus version?: 
IBus 1.5.27

In any gtk4 application, the candidate panel shows a very long distance from cursor, and in other applications (gtk3, qt...) it performs well. The distance seems just equal to the window's height, when window height changed the distance will follow. If set GTK_IM_MODULE to "wayland" instead "ibus", the position becomes correct, and of course, some other issues will occur.

在gtk4应用中，选词面板的位置与光标之间有一段非常长的距离，而在其他应用（gtk3，qt...）中没有这个问题。距离正好和窗口的高度相同，并且会随之变化。如果把GTK_IM_MODULE从"ibus"设成"wayland"，面板的位置就正常了，但是这样当然会产生一些其他的问题。

GTK_IM_MODULE=ibus, shows wrong position:
![截图 2022-10-10 14-42-29](https://user-images.githubusercontent.com/101567377/194816974-8e0df0a5-2ed2-4bb6-ae62-601672857313.png)

GTK_IM_MODULE=wayland, correct position:
![截图 2022-10-10 14-42-52](https://user-images.githubusercontent.com/101567377/194819230-718da6a8-95d6-4a5a-93bf-06f5d8d48b39.png)

**Comment by CongTiankong** [comment]
some pictures shows the distance:
![截图 2022-10-10 14-42-292](https://user-images.githubusercontent.com/101567377/194820737-6548d80f-918b-4e6b-9661-dc73334ebce4.png)
![截图 2022-10-10 14-44-072](https://user-images.githubusercontent.com/101567377/194821280-673ae566-a815-4e9d-a7e5-334cafe974e1.png)



when near bottom of screen, the position changed to above the cursor, but still not good:
![截图 2022-10-10 15-02-23](https://user-images.githubusercontent.com/101567377/194821628-4e761747-8496-4946-8d14-d04740194699.png)


the correct position is:
![截图 2022-10-10 15-03-52](https://user-images.githubusercontent.com/101567377/194821725-76142354-9b69-41ea-9922-b5ecd599d5bc.png)

**Comment by xqqy** [comment]
Ubuntu 22.10 also has the same problem, with IBUS 1.5.27
Tested in Gnome-text-editor

**Comment by fujiwarat** [comment]
> Which session type?:
> X11 and Wayland

The problem should be X11 only.

GTK4 focus on Wayland and the exact cursor position is no longer supported on X11.
Currently I use the X11 API but X11 provides the postion of the window but not cursor position and this cannot be fixed in ibus.

https://gitlab.gnome.org/GNOME/gtk/-/issues/3024#note_987835
