### ISSUE TITLE
Miniconda install breaks Japanese input

### ISSUE THREAD

**Issue by ramenspazz** [ibus/ibus#2454]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 36 Workstation edition

Which desktop environment and version?: 
GNOME 42.4

Which session type?: 
X11

Which application and version?: 
system wide

IBus version?: 
1.5.26

Issue description:
Japanese input stops working entirely, can only type in English.

Steps to reproduce:
install miniconda

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
```
Traceback (most recent call last):
  File "/usr/share/ibus-anthy/engine/main.py", line 31, in <module>
    from gi import require_version as gi_require_version
ModuleNotFoundError: No module named 'gi'
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes, install miniconda

**Comment by fujiwarat** [comment]
Please report your issue to ibus-anthy instead of ibus next time for Japanese  issues.

I think your issue is Miniconda's pacakge issue. ibus-anthy should depends on pygobject.
https://pygobject.readthedocs.io/en/latest/

```
% rpm -qf /usr/lib64/python3.10/site-packages/gi/_gi.cpython-310-x86_64-linux-gnu.so 
python3-gobject-base-3.42.1-1.fc36.x86_64
```
