### ISSUE TITLE
Ibus menu randomly popup on KDE

### ISSUE THREAD

**Issue by zenfas** [ibus/ibus#2455]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: MXLinux 21.2.1 

Which desktop environment and version?:  KDE default

Which session type?: 
X11

Which application and version?: any

IBus version?: default with distro

Issue description: Ibus menu randomly pops up  on system tray

Steps to reproduce: random display menu when I'm using

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes

Other people have this issue on Fedora KDE also  https://www.reddit.com/r/Fedora/comments/xomewa/ibus_menu_randomly_pops_up_while_writing_super/

**Comment by fujiwarat** [comment]
Yes, it's a known issue and I think it's caused by Plasma KDE since we don't reproduce it in Plasma Xorg.

**Comment by zenfas** [comment]
Not happen again on Kubuntu 23.10
