### ISSUE TITLE
Chrome won't respect Korean(Hangul) input type and defaults to Latin

### ISSUE THREAD

**Issue by onursoyer** [ibus/ibus#2456]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Fedora release 36 (Thirty Six)

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 42.4 

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Google Chrome 107.0.5304.87 

IBus version?: 
(Run `ibus version`)
IBus 1.5.26

Issue description:
Google Chrome does not respect selected input method Korean(Hangul) and defaults to Latin characters. Korean(Hangul) is selected layout with Hangul mode enabled. It works well as expected on every other app.
I have also tried following languages and some of them don't work either.

Russian: OK
Arabic: OK
Korean: Failed
Chinese: Failed
Japanese: Failed

Steps to reproduce:
1. Set Keyboard Layout to Korean(Hangul)
2. Enable Hangul Mode
3. Start Google Chrome 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
No

**Comment by fujiwarat** [comment]
I think your issue is resolved in google-chrome 106.0.5249.119 in Fedora 37.
