### ISSUE TITLE
Expect to update the Github Wiki section on Ubuntu installations

### ISSUE THREAD

**Issue by linghengqian** [ibus/ibus#2458]
- At https://github.com/ibus/ibus/wiki/Ubuntu, ibus-qt4 , which does not exist in Ubuntu 22.04, is still required, and ibus-gtk4 is omitted.  
- It doesn't say that `im-switch` needs to be installed.  

- I was expecting to be able to update the Github Wiki section on Ubuntu installations.

**Comment by Domiii** [comment]
I would say, there are far bigger issues here. Most importantly:

1. It does not even mention any remotely recent version of Ubuntu because it was last updated in 2015 :(
2. None of the hackfixes floating about will make `ibus` work in most apps, especially GTK apps apparently, including Chrome and VSCode. Do you have a solution to that? I would love to learn more

**Comment by linghengqian** [comment]
@Domiii I'm not sure what you mean, ibus works fine in most applications. I use ibus directly through the WSLg layer in windows11's WSL2. The reason I can't fix this issue is that I don't have permission to edit the Github Wiki, and I'd be happy to update the instructions in a git location if a maintainer could get back to me.

**Comment by Domiii** [comment]
What Linux do you use in your WSL? I use Ubuntu 22.04 (without a VM), and `ibus` absolutely does not work at all in any GTK applications, even after trying all kinds of suggestions posted in all kinds of places - can you use yours in Chrome for example?

**Comment by linghengqian** [comment]
> What Linux do you use in your WSL? I use Ubuntu 22.04 (without a VM), and `ibus` absolutely does not work at all in any GTK applications, even after trying all kinds of suggestions posted in all kinds of places - can you use yours in Chrome for example?

I have three WSL instance, Ubuntu 22.04, respectively, Ubuntu22.10, Pengwin, they are installed and used normally ibus. I can normally use ibus in GUI software installed by Apt, snapcraft and flatpak, including but not limited to Gedit,GIMP, VLCChrome,Microsoft Edge,Jetbrains Toolbox,IntelliJ IDEA, Webstorm, Wechat.

**Comment by Domiii** [comment]
I wonder if I'm missing something in my installation since I originally only installed English language support and added Chinese later... I remember, old Windows had a similar problem where a Chinese installation was just fundamentally different from non-Chinese installations (at least encoding, and I remember there were other things that functioned differently)... I must be missing something, I wonder what it is

**Comment by linghengqian** [comment]
- As a matter of fact, you should not follow the current Github Wiki. With WSL, installing Chinese first and installing Chinese later doesn't matter, because adding language support is just a simple configuration. 

- I'm still waiting for input from the ibus committer to determine what I should do.

**Comment by Domiii** [comment]
Good luck!

FYI: I just learned that `ibus` problems vary not just with language but with individual input methods. A friend mentioned that Taiwan ChangJie works but Taiwan PinYin does not. So yeah there is that :/

**Comment by gunnarhj** [comment]
@linghengqian: Thanks for pointing at the need to update the Ubuntu wiki page. I just made a couple of edits at [the Debian equivalent](https://github.com/ibus/ibus/wiki/Debian), and copied that contents into the Ubuntu page. That makes more sense to me than what was there previously.

@Domiii: Please seek support about your problem to make IBus work for you. Don't use a random issue like this one to complain.

**Comment by linghengqian** [comment]
@gunnarhj 

- Thanks for the update, I didn't see your reply earlier due to message squeeze. 
- But for Ubuntu WSL users, ibus is not installed by default. Shouldn't we add something like the following in passing?
```shell
sudo apt-get install ibus ibus-gtk ibus-gtk3 fonts-noto-cjk fonts-noto-color-emoji dbus-x11 zenity -y
sudo apt-get install ibus-gtk4 -y # If ibus-gtk4 is available, you need to install
sudo apt-get install ibus-libpinyin -y # or other engine(s) you want
export XIM=ibus
export XIM_PROGRAM=/usr/bin/ibus
export QT_IM_MODULE=ibus
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export DefaultIMModule=ibus
sudo sh -c 'echo "export XIM=ibus" > /etc/profile.d/ibus.sh'
sudo sh -c 'echo "export XIM_PROGRAM=/usr/bin/ibus" >> /etc/profile.d/ibus.sh'
sudo sh -c 'echo "export QT_IM_MODULE=ibus" >> /etc/profile.d/ibus.sh'
sudo sh -c 'echo "export GTK_IM_MODULE=ibus" >> /etc/profile.d/ibus.sh'
sudo sh -c 'echo "export XMODIFIERS=@im=ibus" >> /etc/profile.d/ibus.sh'
sudo sh -c 'echo "export DefaultIMModule=ibus" >> /etc/profile.d/ibus.sh'
ibus-daemon -x -d
ibus-setup # add input methods you want
sudo pkill ibus-daemon
ibus-daemon -x -d
sudo sh -c 'echo "ibus-daemon -drx > /dev/null 2>&1" >> /etc/profile.d/ibus.sh'
```

**Comment by gunnarhj** [comment]
IBus is not installed by default on the other Ubuntu flavors (Ubuntu with alternative desktop environments) either, and my short instruction doesn't assume it is. When installing an IBus engine, `ibus` itself together with the other packages needed (including `im-config`) are installed.

My knowledge about Ubuntu WSL is close to zero, though. But in general it ought to work in the same way, even if adding an applicable font package may be needed.

Do you have a chance to test my theory about Ubuntu WSL? Doesn't `im-config` work there?

**Comment by linghengqian** [comment]
@gunnarhj From my experience, im-config doesn't seem to work under WSL, and I'm not sure it requires a more complete gnome environment.

**Comment by gunnarhj** [comment]
@linghengqian wrote:
> From my experience, im-config doesn't seem to work under WSL, and I'm not sure it requires a more complete gnome environment.

A complete GNOME environment won't affect `im-config`. Actually, even if `im-config` is installed, it's disabled in case of IBus on a GNOME desktop. GNOME itself starts `ibus-daemon` and configures IBus.

If `im-config` does not work under WSL, it may be a bug that we should try to fix. But this is not an appropriate place to continue the discussion. Instead it would be good if you could file an `im-config` bug, where we can investigate it further.

http://bugs.launchpad.net/ubuntu/+source/im-config/+filebug?no-redirect

**Comment by linghengqian** [comment]
- @gunnarhj Let me try to determine, what do you think the installation process should look like?

```shell
sudo apt-get install ibus ibus-gtk ibus-gtk3 fonts-noto-cjk fonts-noto-color-emoji dbus-x11 zenity -y
sudo apt-get install ibus-gtk4 -y # If ibus-gtk4 is available, you need to install
sudo apt-get install ibus-libpinyin -y # or other engine(s) you want
sudo im-config -n ibus
ibus-setup # add input methods you want
```

- If this were the expected configuration, there would be several bugs associated with d-bus on the WSL.

**Comment by linghengqian** [comment]
@gunnarhj Thanks for the clarification. I'm going to close this issue first, there's some discussion on that aspect of WSL.
