### ISSUE TITLE
建议主键盘和小键盘区的数字及符号区别分开

### ISSUE THREAD

**Issue by loongson444** [ibus/ibus#2464]
我用三维天然码，编码为26个字母＋1－9数字，以前1.2的版本是可以区分主键盘的数字和小键盘的数字的，只有主键盘的数字可以作为编码，现在为毛不可以了。

**Comment by fujiwarat** [comment]
Which ibus engine do you use?
Maybe you could report your issue to https://github.com/libpinyin/ibus-libpinyin/issues
