### ISSUE TITLE
ibus doesn't work in VLC media player

### ISSUE THREAD

**Issue by GuShaocheng** [ibus/ibus#2468]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
ubuntu 22.04

Which desktop environment and version?: 
GNOME 42.5

Which session type?: 
X11

Which application and version?: 
VLC media player 3.08

IBus version?: 
1.5.26

Issue description:
it just doesn't work only in VLC. I can't type any characters via ibus apart from Latin letters whatever I try.

Steps to reproduce:
open VLC, type non-Latin letter;
restart, type again;
change to other input methods, open VLC and type non-Latin letters again.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes. I already did.

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no error. it only doesn't work in VLC and works for other apps.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes. including reinstalling VLC.

**Comment by gunnarhj** [comment]
Is VLC installed as a snap? You can check by running this terminal command:

    which vlc

**Comment by wvanrooijen** [comment]
In GNOME (GTK window system), ibus (usually) does not work in applications based on QT5 (such as VLC). I guess it can be configured but I have given up.

**Comment by fujiwarat** [comment]
> In GNOME (GTK window system), ibus (usually) does not work in applications based on QT5

It would be an Ubuntu issue.

**Comment by gunnarhj** [comment]
@wvanrooijen wrote:
> In GNOME (GTK window system), ibus (usually) does not work in applications based on QT5 (such as VLC). You can try to add the following to ~/.bashrc or ~/.xinitrc:
> 
> export XMODIFIERS=@im=ibus
> export GTK_IM_MODULE=ibus
> export QT_IM_MODULE=ibus

That comment is mostly incorrect. GNOME sets the `XMODIFIERS` and `QT_IM_MODULE` variables, which normally is sufficient for QT5 apps. As regards Ubuntu 22.04, which this issue was about, also `GTK_IM-MODULE` is set by the system in x11 sessions on an updated 22.04 installation.

So please don't mislead IBus users by suggesting redundant and inappropriate changes to  e.g. `~/.bashrc`.
