### ISSUE TITLE
Using shell cmd to change keyboard in wayland

### ISSUE THREAD

**Issue by kevinfis** [ibus/ibus#2473]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Arch linux  6.1.9-arch1-1

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Gnome 43.2

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
GNOME Terminal Version 3.46.7 for GNOME 43, emacs 29.06

IBus version?: 
(Run `ibus version`)
IBus 1.5.27

Issue description:
 I want to switch keyboard layout using shell cmd:
`ibus engine xkb:us::eng English`

It return "WARNING: Running setxkbmap against an XWayland server"
and it broke xkb setting:
 (i am using gnome-tweaks to change menu key to 5th-key,
 now it return function of original menu key.
by the way, `ibus engine rime - Rime` did not get error message)
this cmd worked `ibus engine xkb:us::eng English`, last month before i reinstall system,
and no error.
maybe gnome's new version change something.

After see manual of setxkbmap , 
it says:  xwayland ,setxkbmap will come into bug. 
and i found ibus 1.5.27 using setxkbcomp to change layout.

question:
1. Could ibus be possible support shell cmd  switch layout in wayland?
or have other method let me switch layout by shell cmd?

2. i found icon in system tray do not changed after cmd executed before i reinstall system, is it normal?

i have searched these method in internet, 
setxkbmap do not support by wayland,
gdus returned (false, '') :
`gdbus call --session --dest org.gnome.Shell \
    --object-path /org/gnome/Shell \
    --method org.gnome.Shell.Eval \
    "imports.ui.status.keyboard.getInputSourceManager().inputSources[1].activate()"`

Steps to reproduce:
1. `ibus engine xkb:us::eng English` get error
1. 
1. 
1. 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
Currently IBus does not touch the layout changes in Wayland.
You could try to change the layout using GNOME GSettings get/set commands.
```
% gsettings get org.gnome.desktop.input-sources sources
[('xkb', 'jp'), ('ibus', 'anthy')]
% gsettings set org.gnome.desktop.input-sources sources "[('ibus', 'anthy'), ('xkb', 'jp')]"
```

I'm not sure if the ibus command will support the Wayland layout changes while I'm working on the layout changes in Plasma Wayland.

**Comment by kevinfis** [comment]
fujiwarat ,
thank your reply,
after test, this method worked.

previously, i use those command,
 gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us')]"
 gsettings set org.gnome.desktop.input-sources sources "[('ibus', 'rime')]"
because these command of one value will cause tray icon disappear in gnome,
so i thought all though gsettings can't change input layout,
now i got it.

If wayland include such accord about layout change, hope ibus can solved someday.
now gnome is also using wayland's compositor by default,
but a lot tutorial remains cmd of xorg such as x keyboard extension,
this will cause lot of inconvenience.

My issue is solved, 
if gnome does not allow tray icon showed with one layout value, 
i though that is not cause by ibus, so i closed this issue.
Thanks.

**Comment by fujiwarat** [comment]
> because these command of one value will cause tray icon disappear in gnome,

Because I guess you tried to register one source only. You could add both XKB source and input method source in the value. If you register one source only, gnome-shell does not show the icon.
