### ISSUE TITLE
Issue with ibus_serializable_deserialize_object

### ISSUE THREAD

**Issue by mrclnz** [ibus/ibus#2476]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
LFS (but did a *huge* package update, before that ibus worked correctly)

Which desktop environment and version?: 
Sort-of xfce4 and i3

Which session type?: 
X11

Which application and version?: 
Core ibus services
(E.g. gedit 3.24, leafpad, kate, xterm)

IBus version?: 
1.5.28

Issue description:
Substantially, unicode and emoji input stopped working. Normal composes are fine.
Tried resetting the configuration, restarting ibus-daemon and then noticed a flurry of trip on an
assertion

    g_return_val_if_fail (g_type_is_a (type, IBUS_TYPE_SERIALIZABLE), NULL);

I'm not a GObject expert but I traced back to the issue: when the emojifier panel try to read the .dict files the IBusUnicodeData, IBusUnicodeBlock and IBusEmojiData classes are not yet registered with the GType system so the g_type_from_name call fails and nothing get loaded; from that nothing works (obviously, it need the dict data).

As a workaround I added dummy calls to ibus_unicode_data_get_type(), ibus_unicode_block_get_type() and ibus_emoji_data_get_type() before to get the classes registered and everything worked again.

The real issue for me is *how* it could have worked before since I didn't find where these classes could have been registered. Maybe some magic GObject macro? who knows

**Comment by fujiwarat** [comment]
@mrclnz  could you test if the patch [7da18d0](https://github.com/fujiwarat/ibus/commit/7da18d08ce85405e41ba7bf363661292bc97ca39) fixes your issue?

**Comment by mrclnz** [comment]
Takao Fujiwara ***@***.***> writes:

> @mrclnz could you test if the patch 7da18d0 fixes your issue?

That fixed it thanks. The same thing I did but in its correct place…

--
Lorenzo Marcantonio
