### ISSUE TITLE
Ibus switcher steals focus of other app

### ISSUE THREAD

**Issue by hieudmg** [ibus/ibus#2489]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Ubuntu 22.04

Which desktop environment and version?: 
KDE Plasma

Which session type?: 
X11

Which application and version?: 
All application

IBus version?: 
1.5.26

Issue description:
When switching input method by pressing the hot key, the switcher popup and take the focus state of current window. It's not a big deal until I set the hotkey to switch method to `<Ctrl>Shift_L`. Now every keyboard shortcuts of all applications that involve ctrl+shift no longer work. Example: Ctrl+Shift+T to re open tab on browsers.

Steps to reproduce:
1.  Open iBus preferences
1.  Set keyboard shortcut for Next input method to `<Ctrl>Shift_L`
1.  Go to Firefox, close a tab then press ctrl+shift+T, the input switcher opens and the tab is not re-open.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): Yes

Do you see any errors when you run ibus-daemon with the verbose option?: No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

I tried to set `desktop.ibus.general switcher-delay-time=-1` and the switcher is hidden, but the hotkey in other app still not working.

**Comment by fujiwarat** [comment]
I have no idea. When you type Ctrl-Shift, the IBus switcher popup runs immediately before you type Ctrl-Shift-t.
I think the solution is to change the IBus switcher shortcut key from Ctrl-Shift to something else.
