### ISSUE TITLE
Cannot use ibus-libpinyin in microsoft edge or brave

### ISSUE THREAD

**Issue by YerongLi3** [ibus/ibus#2493]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

Which desktop environment and version?: 
```
$ echo $XDG_CURRENT_DESKTOP
icewm
```

Which session type?: 
```
$ echo $XDG_SESSION_TYPE
x11
```

Which application and version?: 
```
$ microsoft-edge --version
Microsoft Edge 111.0.1661.54 
$ brave-browser --version
Brave Browser 111.1.49.128 
```

IBus version?: 
```
$ ibus version
IBus 1.5.23
```

Issue description:
I cannot use ibus-lib-pinyin Chinese input in microsoft edge and brave broswer. While I can use it in the firefox, leafpad and terminal.

Steps to reproduce:
1. Install antix linux in virtualbox
2. Install microsoft edge  

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
Yes, restart ibus after `ibus-daemon --xim` does not help
Do you see any errors when you run ibus-daemon with the verbose option?:
```
(ibus-ui-gtk3:9868): dconf-WARNING **: 21:59:34.058: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=5dbed128db782981321dcb53628c8cdd --binary-syntax --close-stderr”: Child process exited with code 1
cannot open ../lua/base.lua: No such file or directory
lua script loaded.
cannot open /home/yerong/.config/ibus/libpinyin/user.lua: No such file or directory
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by YerongLi** [comment]
Adding following bash variable works for me while I have to start the browser from command line to get ibus working.
```
#ibus
export GTK_IM_MODULE=xim #Fix for Chrome and Brave, when I start either of them from command lines
export XMODIFIERS=@im=ibus
```

When I start browsers from .**desktop** icon does **NOT** work though. 

`Exec=env GTK_IM_MODULE=xim XMODIFIERS=@im=ibus /usr/bin/microsoft-edge`

**Comment by fujiwarat** [comment]
> (ibus-ui-gtk3:9868): dconf-WARNING **: 21:59:34.058: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=5dbed128db782981321dcb53628c8cdd --binary-syntax --close-stderr”: Child process exited with code 1


Seems your desktop lacks some configurations.
`gsettings list-schemas` and `gsettings list-recursively org.freedesktop.ibus.panel` work in your box?

**Comment by YerongLi** [comment]
```
$ gsettings list-schemas
org.gnome.FileRoller.Dialogs.Add
org.gnome.FileRoller.Dialogs.Extract
org.freedesktop.ibus.general.hotkey
guake.keybindings.local
org.blueman.transfer
guake.style
org.gnome.desktop.datetime
org.gnome.desktop.default-applications
guake.keybindings.global
org.gnome.desktop.a11y.mouse
org.gnome.desktop.interface
org.freedesktop.ibus.panel.emoji
org.gnome.desktop.default-applications.terminal
org.blueman.plugins.netusages
guake.style.background
org.gnome.FileRoller.UI
com.github.libpinyin.ibus-libpinyin.libbopomofo
org.freedesktop.ibus.panel
org.gnome.desktop.media-handling
org.gnome.desktop.sound
guake
org.gnome.desktop.app-folders
com.github.libpinyin.ibus-libpinyin.libpinyin
org.gnome.desktop.default-applications.office
org.gnome.system.proxy.http
org.gnome.system.proxy.socks
guake.general
org.gnome.desktop.a11y.applications
org.blueman.network
org.gnome.Evince.Default
org.gnome.desktop.search-providers
org.gnome.desktop.screensaver
org.blueman.plugins.powermanager
org.blueman
org.gnome.gnome-screenshot
org.gnome.desktop.a11y.keyboard
org.gnome.desktop.peripherals.mouse
org.gnome.desktop.thumbnailers
org.gnome.desktop.input-sources
org.gtk.Settings.FileChooser
org.blueman.gsmsettings
org.gnome.desktop.notifications
org.freedesktop.ibus.general
org.gnome.system.proxy
org.gnome.Evince
org.freedesktop.ibus
org.gnome.desktop.peripherals.touchpad
org.blueman.plugins.serialmanager
org.gnome.desktop.peripherals.keyboard
org.gtk.Settings.Debug
guake.keybindings
org.gnome.system.location
org.blueman.plugins.discvmanager
org.gtk.Settings.EmojiChooser
guake.style.font
org.gnome.desktop.background
org.gnome.desktop.session
org.gnome.desktop.wm.preferences
org.gnome.FileRoller.Dialogs.LastOutput
org.gnome.SimpleScan
org.gnome.system.locale
org.gnome.desktop.wm.keybindings
org.gnome.desktop.default-applications.office.calendar
org.gnome.FileRoller.Dialogs
guake.hooks
org.gnome.desktop.peripherals
org.gnome.FileRoller.Dialogs.New
org.gnome.desktop.thumbnail-cache
org.gnome.FileRoller.General
org.blueman.general
org.gnome.desktop.a11y
org.gnome.desktop.calendar
org.blueman.plugins.killswitch
org.gnome.desktop.default-applications.office.tasks
org.gnome.FileRoller.Listing
org.gtk.Settings.ColorChooser
org.gnome.desktop.lockdown
org.gnome.desktop.peripherals.trackball
org.gnome.system.proxy.https
org.gnome.FileRoller.FileSelector
org.gnome.system.proxy.ftp
org.blueman.plugins.recentconns
org.gnome.desktop.a11y.magnifier
org.gnome.desktop.privacy
org.gnome.FileRoller
com.canonical.notify-osd
```
```
$ gsettings list-recursively org.freedesktop.ibus.panel
org.freedesktop.ibus.panel show 0
org.freedesktop.ibus.panel show-im-name false
org.freedesktop.ibus.panel y -1
org.freedesktop.ibus.panel use-glyph-from-engine-lang true
org.freedesktop.ibus.panel show-icon-on-systray true
org.freedesktop.ibus.panel auto-hide-timeout 10000
org.freedesktop.ibus.panel lookup-table-orientation 1
org.freedesktop.ibus.panel custom-font 'Sans 10'
org.freedesktop.ibus.panel xkb-icon-rgba '#415099'
org.freedesktop.ibus.panel use-custom-font false
org.freedesktop.ibus.panel property-icon-delay-time 500
org.freedesktop.ibus.panel follow-input-cursor-when-always-shown false
org.freedesktop.ibus.panel x -1
org.freedesktop.ibus.panel.emoji has-partial-match false
org.freedesktop.ibus.panel.emoji favorite-annotations @as []
org.freedesktop.ibus.panel.emoji load-unicode-at-startup false
org.freedesktop.ibus.panel.emoji partial-match-length 3
org.freedesktop.ibus.panel.emoji favorites @as []
org.freedesktop.ibus.panel.emoji hotkey ['<Control><Shift>e']
org.freedesktop.ibus.panel.emoji lang 'en'
org.freedesktop.ibus.panel.emoji font 'Monospace 16'
org.freedesktop.ibus.panel.emoji load-emoji-at-startup true
org.freedesktop.ibus.panel.emoji unicode-hotkey ['<Control><Shift>u']
org.freedesktop.ibus.panel.emoji partial-match-condition 0
```

**Comment by fujiwarat** [comment]
OK, my understanding is the dconf error is caused by the write operation but not read operation.
So can you modify any gsettings values during the problem session?
E.g.
```
% gsettings get org.freedesktop.ibus.panel show
0
% gsettings set org.freedesktop.ibus.panel show 2
% gsettings get org.freedesktop.ibus.panel show
2
```

**Comment by YerongLi3** [comment]
I exported **XMODIFIERS** and **XMODIFIERS** in the script `/usr/bin/microsoft-edge-stable` and fixed the problem.
```
#!/bin/bash
#
# Copyright 2011 The Chromium Authors
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
#ibus
export GTK_IM_MODULE=xim #Fix for Chrome and Brave, when I start either of them from command lines
export XMODIFIERS=@im=ibus
# Let the wrapped binary know that it has been run through the wrapper.
export CHROME_WRAPPER="`readlink -f "$0"`"
```

**Comment by fujiwarat** [comment]
If you set GTK_IM_MODULE=xim, XMODFIERS is not recommended to set ibus.
It causes other problems and good to disable ibus.

**Comment by YerongLi** [comment]
XMODFIERS is critical. If I disable it .bashrc, ibus will not work in microsoft-edge or brave when I start them from command line.
If I remove XMODFIERS in the /usr/bin/microsoft-edge-stable. ibus does not work in the edge browser any more.

**Comment by fujiwarat** [comment]
So I think your issue is not resolved yet and your instruction is a workaround but I don't expect it.

> Yes, I am able to edit the show value as this.

It's strange with me.
I think it means running ibus-ui-gtk3 does not output such an error.

> (ibus-ui-gtk3:9868): dconf-WARNING **: 21:59:34.058: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=5dbed128db782981321dcb53628c8cdd --binary-syntax --close-stderr”: Child process exited with code 1
cannot open ../lua/base.lua: No such file or directory

When you restart ibus-ui-gtk3, do you see the warning?

```
ps -ef | grep ibus-ui-gtk3
pkill ibus-ui-gtk3
/usr/lib*/ibus-ui-gtk3 &
```

**Comment by YerongLi** [comment]
I am not on debian with icewm so I don't have **ibus-ui-gtk3**:
```
$ ibus
ibus         ibus-daemon  ibus-setup 
```

**Comment by fujiwarat** [comment]
> I am not on debian with icewm so I don't have ibus-ui-gtk3:

ibus-ui-gtk3 would not be a package name.

> (ibus-ui-gtk3:9868): dconf-WARNING **: 21:59:34.058: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=5dbed128db782981321dcb53628c8cdd --binary-syntax --close-stderr”: Child process exited with code 1

This is your error and it means you have ibus-ui-gtk3 and I suggest the test.
Again, When you restart ibus-ui-gtk3, do you see the warning?

```
ps -ef | grep ibus-ui-gtk3
pkill ibus-ui-gtk3
/usr/lib*/ibus-ui-gtk3 &
```

**Comment by YerongLi** [comment]
I see.  **/usr/libexec/ibus-ui-gtk3** outputs no warning even when I switch input languages.
```
$ pkill ibus-ui-gtk3
yerong@mac:~/Documents/recyclebin
$ ^C
yerong@mac:~/Documents/recyclebin
$ /usr/libexec/ibus-ui-gtk3 &
[1] 5296

```


> > I am not on debian with icewm so I don't have ibus-ui-gtk3:
> 
> ibus-ui-gtk3 would not be a package name.
> 
> > (ibus-ui-gtk3:9868): dconf-WARNING **: 21:59:34.058: failed to commit changes to dconf: Error spawning command line “dbus-launch --autolaunch=5dbed128db782981321dcb53628c8cdd --binary-syntax --close-stderr”: Child process exited with code 1
> 
> This is your error and it means you have ibus-ui-gtk3 and I suggest the test. Again, When you restart ibus-ui-gtk3, do you see the warning?
> 
> ```
> ps -ef | grep ibus-ui-gtk3
> pkill ibus-ui-gtk3
> /usr/lib*/ibus-ui-gtk3 &
> ```

**Comment by bibaodi** [comment]
I am using Debian12 and ms-edge, input method using ibus-libpinyin, also got this error. fixed by `export GTK_IM_MODULE=ibus`, no others change but default.

hope this can help others.
