### ISSUE TITLE
Conflict with pointerkeys: Shift + Numlock = Arab character

### ISSUE THREAD

**Issue by nteodosio** [ibus/ibus#2495]
Which distribution and version?: 
Ubuntu Lunar

Which desktop environment and version?: 
ubuntu:GNOME

Which session type?: 
X11.

Which application and version?: 
Xterm(379), Firefox 111.0.1, ...

IBus version?: 
1.5.28

Issue description:

[Pointer keys](https://en.wikipedia.org/wiki/Mouse_keys) allows to control mouse pointer with numeric pad. From [man xkeyboard-config](https://man.openbsd.org/xkeyboard-config.7),

> keypad:pointerkeys | Shift + NumLock toggles PointerKeys

Pressing that combination produces a spurious character.

Steps to reproduce:

```
xsetkbmap -layout <any> -option keypad:pointerkeys
```
Press Shift+Numlock and see لإ inserted.
```
$ od -c <<< لإ
 331 204 330 245  \n 
```

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
No.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes.

Can you reproduce the issue after killing Ibus?
No.

**Comment by fujiwarat** [comment]
Thank you for the report. Interesting.
IBus 1.5.28 supports the one compose key in Arabic:
https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/nls/en_US.UTF-8/Compose.pre#L4559

The Arabic compose sequence is one U+FEF9 but Shift + NumLock also provides the keysym U+FEF9.

I investigated this issue and found the actual Arabic keysym is U+100FEF9 and the I can distinguish the two keys.

I checked GTK4 again and it seems GTK4 does not support the one compose key yet and the key is handled by no_sequence_matches() but it's not an accurate output.

**Comment by fujiwarat** [comment]
I created a tentative patch with above the link.
It would be great if you could test it.

**Comment by nteodosio** [comment]
Thanks for your quick answer and patch!

I built the deb, confirmed that the patch was applied:
```
dpkg-source: info: using patch list from debian/patches/series
dpkg-source: info: applying 611da536255cfb741e59fd2c68d66ea6b6e9d412.patch
```
installed all resulting Ibus packages (ibus-data_1.5.28-2_all.deb       ibus-gtk_1.5.28-2_amd64.deb      ibus-gtk4_1.5.28-2_amd64.deb     ibus-wayland_1.5.28-2_amd64.deb       ibus_1.5.28-2_amd64.deb          ibus-doc_1.5.28-2_all.deb        ibus-gtk3_1.5.28-2_amd64.deb     ibus-tests_1.5.28-2_amd64.deb), killed all ibus processes and restarted Gnome.

Unfortunately  the issue is still present here. :/

**Comment by fujiwarat** [comment]
@nteodosio 

Does ibus_1.5.28-2_amd64.deb include libibus-1.0.so.5* ?

**Comment by nteodosio** [comment]
Yes I made a mistake, by `apt install ./ibus*.deb` I missed e.g. `libibus*.deb`. I confirm the problem is fixed once I install all them, thanks again!

**Comment by fujiwarat** [comment]
I don't push the change to ibus/ibus yet.
