### ISSUE TITLE
Code point feature broken without commit 7c8abbe8

### ISSUE THREAD

**Issue by gunnarhj** [ibus/ibus#2496]
This may or may not be an IBus bug, but I would appreciate input from others. Related Ubuntu bug: https://launchpad.net/bugs/2012788

In the coming Ubuntu 23.04 we see that using code points for entering Unicode characters no longer works. If I press for instance

`Ctrl+Shift+U` followed by `2014`

I see <ins>u2014</ins> on the screen. But it's not replaced with the expected character (in this case an Em Dash) when I confirm with Space or Enter — it just disappears.

The problem started with the Ubuntu build of ibus 1.5.28-2. The problem is not present if I downgrade to ibus 1.5.28-1. Neither is it present if I install the binaries from the 1.5.28-2 build for Debian experimental.

So what's the common denominators in the two latter cases? One thing is that they were both built with glib 2.74. So my suspicion is that building ibus with glib > 2.74 somehow breaks the code point feature.

@fujiwarat: Is this possibly something you can confirm, i.e. will building ibus with latest glib result in this issue?

**Comment by gunnarhj** [comment]
This is the buildlog for the latest (broken) Ubuntu build:

https://launchpadlibrarian.net/656257694/buildlog_ubuntu-lunar-amd64.ibus_1.5.28-2_BUILDING.txt.gz

**Comment by gunnarhj** [comment]
Don't think so. Ubuntu is on libx11 1.8.4, and the issue above happens both on x11 and wayland.

**Comment by gunnarhj** [comment]
OTOH, another common denominator for the ibus builds which work is that they were both built with libx11 1.8.3, while the latest problematic version in Ubuntu was built with libx11 1.8.4.

**Comment by gunnarhj** [comment]
> Sorry, do you mean Ubuntu 1.5.28-2 has the problem and Debian 1.5.28-2 does not?

Yes. Same source, but different build environments.

> Seems ibus 1.5.28-1 works fine with you. What is the difference between 1.5.28-1 and 1.5.28-2 in Ubuntu?

1. 497f0c74 and 8f706d16 added as patches.
2. 1.5.28-2 was built later, i.e. with later versions of some build dependencies.

Can https://github.com/ibus/ibus/commit/7c8abbe89403c2fcb08e3fda42049a97187e53ab resolve your issue?

Will test that.

**Comment by gunnarhj** [comment]
@fujiwarat: Yes,  7c8abbe8 was it. I hadn't realized the significance of that commit.

Thanks!

**Comment by fujiwarat** [comment]
Thank you for the quick test.

Duplicate of #2476
