### ISSUE TITLE
IBus + anthy: Japanese characters (hiragana) invisible while typing

### ISSUE THREAD

**Issue by wvanrooijen** [ibus/ibus#2503]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Gentoo Linux

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 43.3

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
All applications

IBus version?: 
(Run `ibus version`)
IBus 1.5.27

Issue description:
I updated my installation this morning, and suddenly the Japanese input does not show up while typing. I have confirmed this with both ibus-anthy and ibus-mozc. After typing some text (nothing on the screen) I can hit the space-bar and the "kanji selection popup" is displayed. I can then select the kanji, hit "enter" and the kanji is displayed correctly on the screen. It is very irritating since it becomes (nearly) impossible to use Japanese input. Since the "candidate selection popup" works, and the characters are also displayed on the screen after selection, it appears that only the "display while typing" is affected.

I am using IBus 1.5.27 and ibus-anty 1.5.14. I uninstalled and re-installed ibus, ibus-anthy and ibus-mozc but the result is always the same: the Japanese text does not show up while typing.

Steps to reproduce:
1. Switch ibus-anthy to "hiragana" input
2. Type some text (nothing shows up on the screen)
3. Hit space bar and the "kanji selection candidate window" shows up, and I can select kanji
4. Hit "enter" and the kanji shows up on the screen.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): don't know

**Comment by wvanrooijen** [comment]
Thank you. I upgraded to ibus-1.5.28 and I can confirm that the issue is solved.

Notes:
- at the time of writing (May 2023), ibus-1.5.27 is marked "stable" in Gentoo Linux under the desktop/gnome/systemd profile. Users who wish to upgrade ibus should do:
 
root@pc > echo "app-i18n/ibus ~amd64" >> /etc/portage/package.accept_keywords
root@pc > emerge ibus

- I have several computers running Gentoo, and this problem with ibus only occurred on one of them. Perhaps the issue is related to hardware and/or the presence/absence of certain software libraries

**Comment by fujiwarat** [comment]
I checked changes between 1.5.28 and 1.5.28 and I could not find any changes relative with anthy typing.
