### ISSUE TITLE
Bijoy Bayanno keyboard not working on Ubuntu 22.10

### ISSUE THREAD

**Issue by chinmayroy** [ibus/ibus#2504]
I recently upgraded my system to Ubuntu 22.10, and I'm having trouble using the Bijoy Bayanno keyboard with the IBus input method. Whenever I switch to the Bijoy keyboard layout, the keyboard stops responding, and I'm unable to type anything. I've tried restarting IBus and the system, but the problem persists. This issue is preventing me from using my preferred keyboard layout, and I'd appreciate any help in resolving it.

Steps to Reproduce:
    Install IBus and Bijoy Bayanno keyboard layout.
    Switch to the Bijoy keyboard layout.
    Attempt to type anything.

Expected Result:
The Bijoy keyboard layout should work as expected, and I should be able to type in Bengali.

Actual Result:
The keyboard stops responding, and I'm unable to type anything.

Additional Information:
    I'm using Ubuntu 22.10 with GNOME 41.0.
    IBus version: 1.5.25
    Bijoy Bayanno keyboard layout version: 2.0.0

Thanks for your attention to this matter.

**Comment by mike-fabian** [comment]
I don't know what the Bijoy Bayanno keyboard layout (version: 2.0.0) is.
Is that maybe OpenBangla? https://github.com/OpenBangla/OpenBangla-Keyboard

**Comment by chinmayroy** [comment]
It's a Bangladeshi Bangla typing software

**Comment by mike-fabian** [comment]
Yes, but there are many. Which one exactly? From where did you install? Ist this an Ubuntu package from the official repository or did you install from somewhere else?

**Comment by chinmayroy** [comment]
I'm using Bijoy bayanno from somewhere because the software is not available on the ubuntu package.

**Comment by mike-fabian** [comment]
But then you need to tell us where that somewhere is so we can try to reproduce the problem.

**Comment by chinmayroy** [comment]
can you call me on skype: mr.chinmayroy?

**Comment by fujiwarat** [comment]
I cannot find "Bijoy Bayanno" from IBus embedded layouts.
You can check your current engine name with `ibus engine` command.
