### ISSUE TITLE
tray icon flashing during window focusing

### ISSUE THREAD

**Issue by WXZhao7** [ibus/ibus#2505]
Issue description:
The tray icon flashed during the window focusing. I set the global input method to `share the same input method all apps`.

https://user-images.githubusercontent.com/56864878/233534140-de04954d-0875-4368-801b-8803b7925e48.mp4

relative https://github.com/libpinyin/ibus-libpinyin/issues/419 

Which distribution and version?: 
Ubuntu22.04

Which desktop environment and version?: 
xfce4-session 4.18.1

Which session type?: 
X11

Which application and version?: 
any

IBus version?: 
IBus 1.5.26

Steps to reproduce:

1. install ibus and ibus-libpinyin
2. configure
3. focus on diff apps, the tray icon of ibus-libpinyin zoom out and zoom in during focus changing

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
No errors, only unrelated warnings about user script.
```
(ibus-ui-gtk3:21003): IBUS-WARNING **: 11:16:35.407: panel.vala:280: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.

(ibus-ui-gtk3:21003): IBUS-WARNING **: 11:16:35.451: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
cannot open ../lua/base.lua: No such file or directory
lua script loaded.
cannot open /home/wxz/.config/ibus/libpinyin/user.lua: No such file or director
```
Can you reproduce your problem with a new user account instead of the current your account? (yes / no):

**Comment by fujiwarat** [comment]
It's not a bug but expected result.
When an input context is enabled, the engine icon "Pinyin" is shown and after a few seconds later, the input mode icon English or Hanji is shown because the status icon supports one icon only.

**Comment by hoshino873** [comment]
@WXZhao7
I have the same issue, so I made a patch and it works fine as far as I tested on Cinnamon on Gentoo Linux. However, it might not work on KDE. I did not test it.
Hope this helps you.
[ibus-1.5.28-src-fix-status-icon-flashing.patch](https://github.com/ibus/ibus/files/12454842/ibus-1.5.28-src-fix-status-icon-flashing.patch)
