### ISSUE TITLE
wrong position of candidate bar when i type on gnome 44 offical apps

### ISSUE THREAD

**Issue by ventoso** [ibus/ibus#2507]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
NixOS 23.05.20230426.d6b863f (Stoat) x86_64 

Which desktop environment and version?: 
Gnome 44

Which session type?: 
Wayland

Which application and version?: 
almost all gnome 44 offical app

IBus version?: 
IBus 1.5.28

Issue description:
wrong position of candidate bar when i type on gnome 44 offical apps

Steps to reproduce:
1. typing with ibus-rime

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

![image](https://user-images.githubusercontent.com/61822407/235180954-83bdbac1-e43d-49bf-ad9c-b38f211f4143.png)

**Comment by ventoso** [comment]
I have solve this problem by setting `GTK_IM_MODULE` equal to `"wayldnd"`and everything work is fine now

**Comment by ventoso** [comment]
All electron apps are not work and print the error info as follow when i set the enviroment variable equal to `wayland`
```
Gdk: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed
```

**Comment by fujiwarat** [comment]
Wayland does not support application puts the  specific window position.
At the moment, There is no solution if you don't export GTK_IM_MODULE=wayland and it's the default in GNOME Wayland now.

https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5510

> Gdk: gdk_wayland_display_get_wl_display: assertion 'GDK_IS_WAYLAND_DISPLAY (display)' failed

The API is not called by the current IBus so it would be a GTK internal error and you have a configuration error with election or your election app does not support Wayland yet.
