### ISSUE TITLE
IBus Emojier category dialog cannot be launched since GNOME Wayland 44

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#2509]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Fedora 38

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME 44

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
gnome-terminal, gedit

IBus version?: 
(Run `ibus version`)
1.5.28

Issue description:
After the change of gnome-shell of https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2512, ibus cannot receive focus events correctly.

Steps to reproduce:
1. Log into GNOME Wayland
2. Configure some ibus engines with gnome-control-center keyboard not to enable gtk-im-context-simple
3. Enable an XKB layout
4. Launch gnome-terminal
5. Type Super-Period and show "e" prompt
6. Type space to launch IBus Emojier category dialog

And Emoer category dialog is not launched.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
I added a workaround at the moment to launch Emojier category dialog.
But it still cannot commit the selected emoji char to the focused application.
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/6518

The workaround is to use Ctrl-Shift-c to copy the selected emoji char on the dialog and paste the char to the focused application.

**Comment by gunnarhj** [comment]
FWIW I can launch the emoijer selection window in Ubuntu 23.04 (wayland, gnome-shell 44.0) without 310c442b. But I do see the remaining part of the issue.

**Comment by fujiwarat** [comment]
@gunnarhj Thank you for your check.
It would be fine if you cannot reproduce the former issue. I will check it again later. I could reproduced it with 100% last month.
