### ISSUE TITLE
Add support for compressed emoji dictonaries

### ISSUE THREAD

**Issue by evelikov** [ibus/ibus#2510]
Which distribution and version?: 
Arch, rolling

Which desktop environment and version?: 
KDE/Plasma v5.27.4

Which session type?: 
X11

Which application and version?: 
NA

IBus version?: 
1.5.28-4

Issue description:
Currently a fully installed ibus is well over 100M, where over 90% of that is the dictionary files.

At a glance they can be trivially compressed (be that zlib or the more popular zstd), without any affect on the day to day user experience. Casual test with zstd (+ it's default level 3 compression) show a 90M -> 15M a six fold improvement.

This is particularly beneficial for space constrained devices. For example, on my SteamDeck ibus is in the top 10 largest packages.

Steps to reproduce:
1. NA

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
NA

Do you see any errors when you run ibus-daemon with the verbose option?:
NA

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
NA

**Comment by fujiwarat** [comment]
If you mind the file sizes, I'd suggest to delete unnecessary dictionaries. There are all languages by default but I guess you need a few languages only, e.g. emoji-en.dict, emoji-fr.dict, unicode-blocks.dict and unicode-names.dict

**Comment by evelikov** [comment]
Manually going through the list and removing/splitting them to sub-packages does not scale.

**Comment by fujiwarat** [comment]
> If writing the code is a concern, I may be tempted at doing so

It would be good to reopen this when you will has the better patch.
Currently I'm thinking to move any dictionaries to mmap not to spend memories and also each file is already a little compressed and small file but many languages. So compressing files is not eough to be accepted for mmap and it's not so important for me. Probably I won't get time for this task.

**Comment by evelikov** [comment]
@fujiwarat can you elaborate a little here? The English is a bit strange to read, although the issue can be on my end - being a non-native speaker and all.

How does switching to mmap relate to my compression suggestion - is it a hard-requirement/blocker for any dictionary related work or perhaps that's your todo/wishlist for the area?

You mentioned that the dictionaries are "already compressed a little" - what compression is that? Do you have any references where to look in the code?

I'm not sure why the issue got closed - your comment says "Probably I won't get time for this task".

Does this mean that upstream does not want this, even if there are patches available or we're looking at getting time to write/review the code?

Thanks o/

**Comment by fujiwarat** [comment]
> How does switching to mmap relate to my compression suggestion - is it a hard-requirement/blocker for any dictionary related work or perhaps that's your todo/wishlist for the area?

I think just compressing the dictionary file prevents IBus from accessing the file with mmap and compressing/uncompressing process needs more attentions. Since each dictionary file size is small, the compressing file would be the second task after the mmap implementation is finished.

> You mentioned that the dictionaries are "already compressed a little" - what compression is that? Do you have any references where to look in the code?

IBus converts the Emoji data to GVariant. If you read the emoji file, it's not a simple text file. You could see ibus_emoji_data_save().

> even if there are patches available or we're looking at getting time to write/review the code?

I have other prioritized tasks and I  won't get time to writhe the codes of the compressing data by myself at the moment. But if you provide any patches, I can review them but I guess the code would includes several problems.

**Comment by evelikov** [comment]
> the compressing file would be the second task after the mmap implementation is finished

I see, thank you. Is there a way to track that status? At a glance I could not see any open issue, MR or a branch.

> You could see ibus_emoji_data_save().

From a quick look the function contains an trivial conversion and serialisation. There is no compression that I can see in there.

Apologies in advance for my ignorance, but it seems like you're saying "there could be problems" without elaborating what those are (or might be). Are you talking about performance (is there a test suite one can use to measure those), code complexity or something else?

**Comment by fujiwarat** [comment]
> I see, thank you. Is there a way to track that status? At a glance I could not see any open issue, MR or a branch.

I didn't make public my plan yet. The relative issue is #2419.

> From a quick look the function contains an a trivial conversion and serialisation. There is no compression that I can see in there.

OK, sure.

> but it seems like you're saying "there could be problems" without elaborating what those are (or might be).

Right. I mind both the performance and the code complexity. IBus can put the dictionary files in /usr/share as the static files at present but probably I guess a temporary repository is needed to mmap the unzipped files and and the performance is unknown. And the current my plan is to move g_file_get_contents() to GResource and mmap and adding the unzip feature would be more complex codes.
