### ISSUE TITLE
ibus keyboard shortcut, configure next input method, implicitly takes away shift key for previous input method 

### ISSUE THREAD

**Issue by Inc0n** [ibus/ibus#2524]
Which distribution and version?: 
Ubuntu 22
(E.g. Fedora 27. Check /etc/fedora-release)

Which desktop environment and version?: GNOME

Which session type?:  x11

Which application and version?: 
all

IBus version?: IBus 1.5.26

Issue description:
Setting next input method will make the its key combination with shift to be mapped to previous input method.
This is undesired in my case, where I need the shift version for another shortcut.

Steps to reproduce:
- Configure shortcut for next input method to: `<super>space` 
- now `<super>space` will change to next input method 
- but also `<super><shift>space` will change to previous input method

Can you reproduce your problem when you restart ibus-daemon? (yes / no): Yes

Do you see any errors when you run ibus-daemon with the verbose option?: No

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): Yes

My proposal/suggestion is to have a separate entry for previous input method, where the user can configure to disable/enable with key combination of their choice, instead of taking away shift key implicitly.

Additionally, when Next input method is configured to `<shift><super>space` it, previous input method cannot be activated with `<super>space`.

**Comment by fujiwarat** [comment]
If you bind <Super><Shift>space to another application, it would be good to change the shortcut in ibus or your application.
I have no plan to change it.

**Comment by Inc0n** [comment]
Actually it's the other way round. Ibus is configured to be `super space`, where as some other application is configured to have `super shift space`. But ibus implicitly took over `super shift space` and `super space`. Can you re-consider this knowing the situation to be this instead?
