### ISSUE TITLE
Disable switcher popup while still allowing multiple layouts

### ISSUE THREAD

**Issue by hatkidchan** [ibus/ibus#2529]
IBus version?: 1.5.28

Issue description:
I'm trying to hide switcher popup because for me it's really annoying, since I have tray icon for that anyways. I can hide it using `gsettings set org.freedesktop.ibus.general switcher-delay-time -1`, but that makes other layouts (I have 4 of them) inaccessible. Is there a setting that I missed that just.. hides switcher window? Or maybe there is a way to make ibus not shuffle layouts after I choose one? For me problem is not _hiding_ it, but making other layouts accessible, because with small switcher delay it just jumps to other layout without any time for me to select other one

Fix I would like to see:
A checkbox, tied to dconf property that just hides switcher window

**Comment by fujiwarat** [comment]
If you switch more than 3 IBus engines, I think it makes sense to show the engine switcher popup.

**Comment by hatkidchan** [comment]
It does, but it also would be nice to be able to disable it, since I have a tray icon anyways. The main problem is that it shuffles layouts every time I switch them and that _doesn't_ make sense to me

**Comment by fujiwarat** [comment]
>  but it also would be nice to be able to disable it,

If the popup is now shown, you don't know which engine is now selected with the some space keys of Super-space shortcut key.

> The other problem is that it shuffles layouts every time I switch them 

What is the problem when it shuffles layouts?

**Comment by hatkidchan** [comment]
> What is the problem when it shuffles layouts?

Exactly that I can't predict what the next layout will be once I switch it without looking at the pop-up. When I'm using the default X keyboard switcher, it just moves to the other one in the list, without shuffling.

**Comment by fujiwarat** [comment]
It would be good for you to look at the IME switcher popup window and you don't have to predict it.

**Comment by hatkidchan** [comment]
I might as well look at the tray icon, popup is redundant in this case, so I want to hide it. But hiding it _also_ makes impossible for me to use more than 2 layouts

**Comment by fujiwarat** [comment]
I don't think the popup is redundant in the case of more than 2 layouts because try icon shows the current icon only but the IME switcher popup shows the order.
