### ISSUE TITLE
iBus as an offline server but weirdly reporting ‘‘connections reset by peers’’ and doesn’t starts

### ISSUE THREAD

**Issue by petra-pannia** [ibus/ibus#2538]
```
% ibus-setup
(ibus-setup:8366): IBUS-WARNING **: 09:11:19.768: Unable to connect to ibus: Error receiving data: Connection reset by peer
% ibus-daemon
Can not execute default config program
%
```
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Artix runit 23.07

Which desktop environment and version?: 
KDE Plasma 5.27.6-1

Which session type?: 
Plasma Wayland session on SDDM 0.20.x being run on X11

Which application and version?: 
The whole system

IBus version?: 
1.5.28

Issue description:
iBus server wrongly reporting ‘‘connections reset by peers’’ which shouldn’t be reported to me for iBus which is an offline server and doesn’t require internet in order to be started

Steps to reproduce:
1. Remove everything ibus related
2. Reinstall everything removed
3. run `ibus-daemon` anywhere, even including TTY’s, if seeing sth wrong and/or weird
4. run `ibus-setup` on QTerminal if seeing sth wrong and/or weird

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Another Artix installed on the another SSD inside a same h/w system

**Comment by fujiwarat** [comment]
You should not delete questions in the report template.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

**Comment by petra-pannia** [comment]
```
% ibus exit && ibus-daemon --xim &
[1] 6224
% Can't connect to IBus.
^C
[1]+  Exit 1                  ibus exit && ibus-daemon --xim
% ibus-daemon --xim --verbose &
[1] 6246
% Can not execute default config program
^C
[1]+  Exit 255                ibus-daemon --xim --verbose
% ibus exit && ibus-daemon --xim --verbose
Can't connect to IBus
%
```

**Comment by fujiwarat** [comment]
Hmm.., the verbose option does not give any information.
Probably I need to add more warning messages after we understand why your problem happens.

> Artix runit 23.07

Does Artix runit provide IBus packages prepared by the distribution likes RPM or other package formats? Or do you install ibus from the source codes with make, gcc by yourself?
I'd suggest to install the distribution packages if available.

Do you have /usr/share/ibus/component/dconf.xml and can you see an `exec` tag in that file?

 The file should describes the command path likes` /usr/libexec/ibus-dconf`

**Comment by petra-pannia** [comment]
I however saw the ‘‘exec’’ line with `/usr/lib/ibus/ibus-dconf`
(Both 2 Artix systems are with everything iBus installed by `pacman`, the Arch **binary** *pac*kage *man*ager
and both **as well never** required anything iBus to be sourcecodedly installed
`/usr/libexec/ibus-dconf` is instead an FreeBSD dir in order to do for the same)
```
$ cat /usr/share/ibus/component/dconf.xml
<!--  filename: dconf.xml  -->
<component>
<name>org.freedesktop.IBus.Config</name>
<description>Dconf Config Component</description>
<exec>/usr/lib/ibus/ibus-dconf</exec>
<version>1.5.28</version>
<author>Daiki Ueno <ueno@unixuser.org></author>
<license>GPL</license>
<homepage>https://github.com/ibus/ibus/wiki</homepage>
<textdomain>ibus</textdomain>
</component>
```
Both 2 Artix systems on a same h/w system are with an identical file like this

**Comment by fujiwarat** [comment]
Do you see any errors when you invoke `/usr/lib/ibus/ibus-dconf` by manual after ibus-daemon runs?
```
% ibus-daemon --xim --verbose &
% ps -ef | grep ibus
% /usr/lib/ibus/ibus-dconf
```

**Comment by petra-pannia** [comment]
Nothing runs seamlessly, or reacts with error details
(I however have another Artix on a same h/w system (different BtrFS root partitions on different SSD’s) whose iBus is ok)
```
% ibus-daemon --xim --verbose &
[1] 22069
Can not execute default config program
[1]+  Exit 255                ibus-daemon --xim --verbose
% ps -ef | grep ibus
hd_scan+ 22089 20061  0 19:57 pts/3    00:00:00 grep --colour=auto ibus
% /usr/lib/ibus/ibus-dconf
%```

**Comment by fujiwarat** [comment]
OK, I mistook the test case. The correct one is:
```
% ibus-daemon --xim --verbose --config disable &
% ps -ef | grep ibus
% /usr/lib/ibus/ibus-dconf
```

**Comment by petra-pannia** [comment]
`/usr/lib/ibus/ibus-dconf` just however runs and exits w/o showing any outputs
```% ibus-daemon --xim --verbose &
[2] 24003
[1]   Exit 1                  cd ibus-daemon --xim --verbose
% Can not execute default config program
^C
[2]+  Exit 255                ibus-daemon --xim --verbose
% ps -ef | grep ibus
hd_scan+ 24040 23810  0 09:01 pts/4    00:00:00 grep --colour=auto ibus
% /usr/lib/ibus/ibus-dconf
%
```

**Comment by fujiwarat** [comment]
@petra-pannia You mistook the ibus argument.
I suggested `--xim --verbose --config disable` but not `--xim --verbose`.

**Comment by petra-pannia** [comment]
```
% ibus-daemon --xim --verbose --config disable &
[1] 11179
% Can not execute default panel program
ps -ef | grep ibus
hd_scan+ 11195 10367  0 20:52 pts/1    00:00:00 grep --colour=auto ibus
[1]+  Exit 255                ibus-daemon --xim --verbose --config disable
% ps -ef | grep ibus
hd_scan+ 11199 10367  0 20:52 pts/1    00:00:00 grep --colour=auto ibus
% /usr/lib/ibus/ibus-dconf
%
```

**Comment by fujiwarat** [comment]
> Can not execute default panel program

OK, The panel requires the config and failed.
The correct test case is:
```
% ibus-daemon --verbose --config disable --panel disable --emoji-extension disable &
% ps -ef | grep ibus
% /usr/lib/ibus/ibus-dconf
```

**Comment by petra-pannia** [comment]
```
% ibus-daemon --verbose --config disable --panel disable --emoji-extension disable &
[1] 7252 (Exited w/o outputs)
% ps -ef | grep ibus
hd_scan+  7252  4622  0 09:27 pts/3    00:00:00 ibus-daemon --verbose --config disable --panel disable --emoji-extension disable
hd_scan+  7260     1  0 09:27 tty8     00:00:00 /usr/lib/ibus/ibus-portal
hd_scan+  7275  4622  0 09:27 pts/3    00:00:00 grep --colour=auto ibus
% /usr/lib/ibus/ibus-dconf
(Running w/o outputs ...)
```

**Comment by fujiwarat** [comment]
> Only running with the below, but how to reset the configs? On the home side or the system wide side?

I don't know why you want to reset the config?

> % ibus-daemon --verbose --config disable --panel disable &
> [1] 7252 (Exited w/o outputs)

I think ibus-daemon did not exit but run.

> % /usr/lib/ibus/ibus-dconf
> (Running w/o outputs ...)

Curious, ibus-daemmon just invokes the command.

I think you can run `exec` tag in `/usr/share/ibus/component/gtkpanel.xml` file by manual after `/usr/lib/ibus/ibus-dconf` runs as the workaround.

> Can not execute default config program

Reading your error again, I think more error messages should be output if ibus-daemon run /usr/lib/ibus/ibus-dconf so I guess your ibus-daemon failed to find /usr/share/ibus/component/dconf.xml

I'd ask another test cases.

Test Case 1
```
% which ibus-daemon
% sudo mv /var/cache/ibus/bus/registry /var/cache/ibus/bus/registry.bak
% mv $HOME/.cache/ibus/bus/registry $HOME/.cache/ibus/bus/registry.bak
% ibus-daemon &
```

Test Case 2
```
% which strace
% strace ibus-daemon |& grep component
```

**Comment by petra-pannia** [comment]
Maybe `ibus-daemon` **never fails** to find `/usr/share/ibus/component/dconf.xml` which **has never been missing**
The final issue is, `ibus-daemon` now reports ‘‘Couldn’t run default panel program’’ but `ibus-daemon --panel disable` works
(I also entirely removed `~/.cache` and never `/var/cache/ibus` was caught to me) After then iBus works but panels have to be disabled, but w/o a panel working i couldn’t switch between English, Japanese, and traditional Chinese

**Comment by fujiwarat** [comment]
> (I also entirely removed ~/.cache and never /var/cache/ibus was caught to me) After then iBus works

I didn't ask to remove those but move them to investigate them with your bad configurations.

>  but panels have to be disabled, but w/o a panel working i couldn’t switch between English, Japanese, and traditional Chinese inputs as i require everything for use personally

And then can you run `exec` line in `/usr/share/ibus/component/gtkpanel.xml` by manual after you run ibus-daemon to check any error messages?

**Comment by petra-pannia** [comment]
I got an empty `/usr/share/ibus/component/gtkpanel.xml`
And that line to be added feels like `<exec>/usr/bin/$your_gtk_panel_cmd_name</exec>`?

**Comment by fujiwarat** [comment]
> I got an empty /usr/share/ibus/component/gtkpanel.xml

It cannot be empty and your build environment is broken. It has the path of ibus-ui-gtk3 and /usr/libexec/ibus-ui-gtk3 in Fedora.

Totally your environment is broken in the config and panel.

**Comment by petra-pannia** [comment]
However, why don’t parts of distroes also offer `ibus-ui-gtk3` commands or libraries-to-be-run?
Of course Fedora (your example) is GNOME centric, and both projects are heavily tied to RedHat, to make iBus in order to be easily dealt with on Fedora
Artix and/or Manjaro (mine), on the other hand, aren’t that however tied to a certain graphical project, but are that way more anarchist of any graphical project

**Comment by petra-pannia** [comment]
I caught the panel app to be at `/usr/lib/ibus/ibus-ui-gtk3` on my Artix and how to get it set to the panel app for iBus in order to be run?

**Comment by petra-pannia** [comment]
`ibus-daemon --panel=/usr/lib/ibus/ibus-ui-gtk3` now works normally and thanks! :)
