### ISSUE TITLE
My IBus cannot read the configuration properly

### ISSUE THREAD

**Issue by saltfishexcapel** [ibus/ibus#2546]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux with kernel 6.4.6

Which desktop environment and version?: 
Gnome 44.3

Which session type?: 
Both in X11 and Wayland

Which application and version?: 
gnome

IBus version?: 
IBus 1.5.28

Issue description:
I installed ibus and libpinyin according to the operation of arch wiki, and completed the configuration using "ibus-setup". But I cannot switch input methods through shortcut keys, and I need to use "ibus engine libpinyin" every time to enable it. After using "ibus read-config", I found that an error related to the Gnome Schema was reported, such as:
(ibus read configuration: 57975): GLib GIO CRITICAL * *: 19:26:20.759: g_ Settings_ Schema_ List_ Keys: assertion 'schema= NULL 'failed
SCHEMA: org.freedesktop.ibus
And there is no program display on the panel either!

Steps to reproduce:
1. Install ibus and ibus-libpinyin in Arch Linux;
2. In Gnome - control center - Keyboard - Input source, add "Chinese" in it, (汉语);
3. Use "ibus-setup" to set libpinyin, and use dconf-edit to confirm it (engines-order: ['libpinyin', 'xkb:us::eng'], preload-engine: ['lib-pinyin', 'xkb:us::eng'];  panel - show: 2);
4. Envirment is ok, GTK_IM_MODULE=ibus, ...
5. Add an auto script in ~/.config/autostart, use "ibus-daemon -xdr" command to pull it up when login;
6. Reboot completed, use "ps aux | grep ibus" command and confirm ibus was run.
7. I cannot use the shortcut keys to switch to libpinyin, and no ibus icon in panel, type "ibus engine" find response "xkb:us::eng". Only type "ibus engine libpinyin" can use in global Gnome envirments.
8. Typing "ibus daemon -xdr" at any time can reset the status to "xkb:us::eng", and input methods can only be used with "ibus engine libpinyin", there's no ibus icon in panel.
9. My gnome dconf about ibus is right? Type "ibus read-config" shows:
(ibus read-config:60465): GLib-GIO-CRITICAL **: 20:11:21.935: g_settings_schema_list_keys: assertion 'schema != NULL' failed
(ibus read-config:60465): GLib-GIO-CRITICAL **: 20:11:21.935: g_settings_schema_list_keys: assertion 'schema != NULL' failed
(ibus read-config:60465): GLib-GIO-CRITICAL **: 20:11:21.936: g_settings_schema_list_keys: assertion 'schema != NULL' failed
(ibus read-config:60465): GLib-GIO-CRITICAL **: 20:11:21.936: g_settings_schema_list_keys: assertion 'schema != NULL' failed
(ibus read-config:60465): GLib-GIO-CRITICAL **: 20:11:21.936: g_settings_schema_list_keys: assertion 'schema != NULL' failed
SCHEMA: org.freedesktop.ibus
SCHEMA: org.freedesktop.ibus.general
SCHEMA: org.freedesktop.ibus.general.hotkey
SCHEMA: org.freedesktop.ibus.panel
SCHEMA: org.freedesktop.ibus.panel.emoji
And I use "gsettings list-keys org.freedesktop.ibus.general" can find keys, no warnings.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
no

Do you see any errors when you run ibus-daemon with the verbose option?:
no warning and errors in stdout and journal.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes, I reproduce it at all.

**Comment by saltfishexcapel** [comment]
It's so magic. I install KDE Plasm in same computer, and I can use ibus rightly now. In the KDE I can see ibus panel in desktop and I can change input method by shortcut keys. Now may I only want know how can run in Gnome, Is the SCHEMA warning a bug? Thanks for authors.

**Comment by saltfishexcapel** [comment]
Thanks for author, I solved my problem accidentally. I use dconf-editor to revise /org/gnome/desktop/input-sources/source to [('ibus', 'libpinyin'), ('xkb', 'us')], after logging in again and it's seem ok. My Arch system does not provide an option about ibus for me, now may solved this.

**Comment by fujiwarat** [comment]
For GNOME:

> Add an auto script in ~/.config/autostart, use "ibus-daemon -xdr" command to pull it up when login;

You should not modify ~/.config/autostart but gnome-session runs ibus-daemon with /usr/lib/systemd/user/org.freedesktop.IBus.session.GNOME.service file.

```
% systemctl --user status org.freedesktop.IBus.session.GNOME
● org.freedesktop.IBus.session.GNOME.service - IBus Daemon for GNOME
     Loaded: loaded (/usr/lib/systemd/user/org.freedesktop.IBus.session.GNOME.s>
    Drop-In: /usr/lib/systemd/user/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Mon 2023-07-31 19:35:52 JST; 1h 48min ago
   Main PID: 2525 (ibus-daemon)
      Tasks: 44 (limit: 9281)
     Memory: 115.3M
        CPU: 1min 35.359s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/org.fr>
             ├─2525 /usr/bin/ibus-daemon --panel disable --xim
             ├─2644 /usr/libexec/ibus-dconf
             ├─2646 /usr/libexec/ibus-extension-gtk3
             ├─2661 /usr/libexec/ibus-x11 --kill-daemon
             ├─3037 python3 /usr/share/ibus-anthy/engine/main.py --ibus
             └─3615 /usr/libexec/ibus-engine-simple

 7月 31 19:35:52 dream systemd[1786]: Starting org.freedesktop.IBus.session.GNO>
 7月 31 19:35:52 dream systemd[1786]: Started org.freedesktop.IBus.session.GNOM>
```

And you can configure IBus engines with `gnome-control-center keyboard` utility so you don't have to run gsettings or dconf directly.

**Comment by saltfishexcapel** [comment]
Thank you for your suggestion!
