### ISSUE TITLE
feature request: build ibus to Appimage format file

### ISSUE THREAD

**Issue by newyorkthink** [ibus/ibus#2557]
```
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2023.3"
VERSION="2023.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"
```

```
i3 version 4.22 (2023-01-02) © 2009 Michael Stapelberg and contributors
```

```
x11
```

```
IBus 1.5.29-beta1
```

i want to ibus APPimage format file

APPimage format is better than deb or rpm

APPimage format file it can run ibus everywhere, and abandon use apt or other package manager command

just one file all in one file and give it all function

so, I hope  ibus team can create build ibus APPimage file

**Comment by fujiwarat** [comment]
Sorry, I'm not familiar with Appimage.
Any contributions are welcome.
Otherwise probably you could think about Flatpak.
