### ISSUE TITLE
Popup/suggestions/menu missing/not working

### ISSUE THREAD

**Issue by Fabian42** [ibus/ibus#2558]
Which distribution and version: Manjaro 23.0
Which desktop environment and version: KDE 5.27.7
Which session type: X11 21.1.8
Which application and version: all, e.g. gedit
IBus version: 1.5.28

Issue description:
I never get any visible functionality from any special input method. Tried for example "Japanese SKK" and "Typing booster". The tray icon lets me select the input methods and in some situations there is a bar with buttons at the bottom right, but I don't get any word/kanji/emoji/… suggestions, replacements or spellcheck.

Steps to reproduce:
1. Some installed packages: `ibus 1.5.28-4`, `ibus-akaza 0.2.0-1`, `ibus-anthy 1.5.14-2`, `ibus-kkc 1.5.22-3`, `ibus-skk 1.4.3-2`, `ibus-table 1.17.0-2`, `ibus-table-tlim2 2.4.245-1`, `ibus-typing-booster 2.23.1-1`, `lib32-libusb 1.0.26-2`, `libibus 1.5.28-4`, `libusb 1.0.26-2`, `libusb-compat 0.1.8-1`, `libusbmuxd 2.0.2-3`, `python-libusb1 3.0.0-2`
2. Following this tutorial: https://mike-fabian.github.io/ibus-typing-booster/docs/user/ (`ibus-setup`, add it, start `gedit` with the `export`s, select the input method, etc.)
3. Type something, try `_something`, press tab, Enter, Win+Space, …
4. Change some settings, modes, etc.
5. And a bunch more over time, but this was the main attempt from today.

Can you reproduce your problem when you restart ibus-daemon? yes

Do you see any errors when you run ibus-daemon with the verbose option?:
`(ibus-ui-impanel:819961): IBUS-WARNING **: 22:36:06.612: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.`

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): didn't try, `ibus` never worked

**Comment by Fabian42** [comment]
Oh, `kimtoy` works! It does not look at all like I expected it, but I can type kanji with it, at least in some programs!

**Comment by fujiwarat** [comment]
Which value is returned wint `ibus im-module --type gtk3` ?

**Comment by Fabian42** [comment]
Initially "`fcitx`", after the setup steps I linked it outputs "`ibus`" in that terminal, but e.g. `gedit` started from it still does not show anything special.

**Comment by fujiwarat** [comment]
> (ibus-ui-impanel:819961): IBUS-WARNING **: 22:36:06.612: ibus_bus_call_sync: 

I think it does not exist in ibus source codes.
I'd suggest to use ibus-ui-gtk3 instead. I'm not sure how they are packaged in Manjaro 

They are called by ibus-daemon from /usr/share/ibus/component/
