### ISSUE TITLE
XIM input sometimes jumbled

### ISSUE THREAD

**Issue by juhp** [ibus/ibus#2560]
Which distribution and version?: Fedora Linux

Which desktop environment and version?: GNOME

Which session type?: Wayland and Xorg

IBus version?: 1.5.29-rc1 and earlier

Issue description:
Direct input to an X app can get scrambled (misordered) sometimes.

Prepare environment:
eg in Fedora 38 Gnome with `XMODIFIERS=@im=ibus`:
```shellsession
$ sudo dnf install evemu xterm
$ xterm &
$ wget https://gitlab.gnome.org/GNOME/gnome-shell/uploads/638f63efdb622745be311187c435234a/log.txt
$ sudo evemu-play log.txt
```

Steps to reproduce:
1. press Enter after `Hit enter to start replaying`
2. immediately press Alt-Tab to switch the focus to the X app (xterm)
3. watch the input 
4. when it stops Alt-Tab back to the terminal and repeat from step 2

Eventually the input appearing in input the X app becomes misordered/jumbled/scrambled:

`mreoac-@talklanet#1alknaelt#1anll#a1ketalklanet#1akalln#et1alklaten1#@tea-rmocakll1tna#e`

versus expected input:

`@team-rocalklanet#1alklanet#1alklaneT#1`...

Further it looks like occasionally Shift modifier may be lost (2 <-> @)?

(Alternatively it can also be reproduced with say this perl Tk script
from https://bugzilla.redhat.com/show_bug.cgi?id=2230440#c0 which can be copied:
$ cat > test.pl
$ perl test.pl
)

**Comment by juhp** [comment]
A workaround seems to be unsetting XMODIFIERS.

**Comment by mike-fabian** [comment]
It also happens when using `xterm` instead of `perl test.pl`:
(This video is on Gnome Wayland using `XMODIFIERS=@im=ibus`)

https://github.com/ibus/ibus/assets/2330175/5d06c20d-ad5b-4b11-9d83-a247ed723370

**Comment by fujiwarat** [comment]
> (This video is on Fedora 38 using Gnome Wayland using XMODIFIERS=@im=ibus)

I think your video does not show any problems.

**Comment by fujiwarat** [comment]
> mreoac-@talklanet#1alknaelt#1anll#a1ketalklanet#1akalln#et1alklaten1#@tea-rmocakll1tna#e

I guess it happens only when you switch the focus too quickly after you press Enter key.

I press Enter key and Alt-Tab and see the result - OK, press BackSpace and reset the testl result, and focus on evemu again.
Repeating this sequence above does not happen the issue.
Probably you don't reset the result.

**Comment by mike-fabian** [comment]
> > (This video is on Fedora 38 using Gnome Wayland using XMODIFIERS=@im=ibus)
> 
> I think your video does not show any problems.

It does, in the xterm `@team-rco` appears instead of `@team-roc`. I.e. `o` and `c` are reversed.

**Comment by juhp** [comment]
In Fedora Rawhide, consecutive runs:

```shellsession
petersen@fedora:~$ perl test.pl 
Input: @tema-rocalklanet#1alklanet#1alklanet#1
          ^
petersen@fedora:~$ perl test.pl 
Input: @team-rocalklanet#1alkalnet#1alklanet#1
                             ^
petersen@fedora:~$ perl test.pl 
Input: allank#et1alklanet#1alklanet#1
         ^ ^ ^
petersen@fedora:~$ perl test.pl 
Input: @team-rocalklanet#1alklanet#1alklanet#1
petersen@fedora:~$ perl test.pl 
Input: @team-rocalklanet#1alklanet#1alklanet#1
petersen@fedora:~$ perl test.pl 
Input: tea@m-rocalklanet#1alklanet#1alklanet#1
          ^
petersen@fedora:~$ perl test.pl 
Input: @team-rocalklanet#1alklanet#1alklanet#1
petersen@fedora:~$ perl test.pl 
Input: alklanet#1alklanet#1aklanelt#1
                            ^    ^
petersen@fedora:~$ perl test.pl 
Input: @team-rocalklanet#1alklanet#1al1klanet#
                                      ^
```

**Comment by fujiwarat** [comment]
Some environment requires the IBus patch but basically the libX11 patch would be enough to fix the issue.
