### ISSUE TITLE
Keyboard shortcut to switch input method doesn't work under KDE Wayland

### ISSUE THREAD

**Issue by miklcct** [ibus/ibus#2561]
Forwarded downstream report from [here](https://bugzilla.redhat.com/show_bug.cgi?id=2054719):

Please fill in the following items if you don't know the root cause.

Which distribution and version?:  Ubuntu 23.04
Which desktop environment and version?: KDE Plasma 5.27.4
Which session type?: Wayland
Which application and version?: Konsole
IBus version?: 1.5.28

Issue description: Keyboard shortcut to switch input method does not work (except in GTK apps)

Steps to reproduce:
1. Launch Plasma Wayland session
1. Launch iBus
1. Configure Super - Space to switch input method
1. Press the buttom

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
The latest is 1.5.29 and I explained it.
https://groups.google.com/g/ibus-user/c/iXaBdVm_lV0
