### ISSUE TITLE
Remove recommended dependency on GTK 2

### ISSUE THREAD

**Issue by ChaseKnowlden** [ibus/ibus#2565]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Linux from Scratch 12.0

Which desktop environment and version?: 
GNOME 44

Which session type?: 
X11

Which application and version?: 
Gedit 46.1

IBus version?: 
1.5.28

Issue description:
GTK 2 was not updated since 2020.

Steps to reproduce:
1. Run configure.
2. It tries to look for GTK 2.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
no

Do you see any errors when you run ibus-daemon with the verbose option?:
none

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
I don't understand your suggestion.
GTK2 is stable but the stable does not mean deprecated since some GTK2 applications exit likes gimp.

You can specify `./configure --disable-gtk2`
