### ISSUE TITLE
Inconsistency of cursor_pos value returned from IBus.Engine.get_surrounding_text() on Wayland

### ISSUE THREAD

**Issue by ShikiOkasaka** [ibus/ibus#2573]
Which distribution and version?: 
Fedora 39 Beta

Which desktop environment and version?: 
GNOME 45.0

Which session type?: 
Wayland

Which application and version?: 
gnome-text-editor 45.0
gedit 45.0

IBus version?: 
1.5.29-rc1 using IBus Python API

Issue description:

The unit of cursor_pos returned from IBus.Engine.get_surrounding_text() appears to be inconsistent.
With GTK_IM_MODULE=ibus, cursor_pos is given by the number of UCS-4 characters.
Without GTK_IM_MODULE=ibus, cursor_pos is given by the number of bytes in the UTF-8 encoded surrounding text.

Is this inconsistency a bug or is it on purpose?
To develop an IME in Python, I think it is preferable to count cursor_pos by the number of UCS-4 characters.

Steps to reproduce:
1. Type any characters in the text editor.
2. Check cursor_pos values passed to IBus.Engine.do_set_surrounding_text().

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
I made https://gitlab.gnome.org/GNOME/mutter/-/issues/3102
But seems some relative issues are already reported in mutter.
