### ISSUE TITLE
Set global engine failed.

### ISSUE THREAD

**Issue by Taki132** [ibus/ibus#2574]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Arch Linux
Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
Hyprland
Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
Wayland
Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
kitty 0.29.2
IBus version?: 
(Run `ibus version`)
IBus 1.5.28
Issue description:

(process:12420): IBUS-CRITICAL **: 17:47:24.653: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
Set global engine failed.
Steps to reproduce:
1.  run command ibus-daemon -xdr && ibus engine Bamboo
Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:yes
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**I want to autostart ibus on hyprland by exec but It's have some error to autostart

**Comment by Taki132** [comment]
> ps -ef | grep ibus

this is output on command
karuto     71431       1  0 19:40 ?        00:00:00 ibus-daemon -xdr
karuto     71450   71431  0 19:40 ?        00:00:00 /usr/lib/ibus/ibus-dconf
karuto     71452   71431 10 19:40 ?        00:00:02 /usr/lib/ibus/ibus-extension-gtk3
karuto     71457     568  0 19:40 ?        00:00:00 /usr/lib/ibus/ibus-portal
karuto     71724   10688  0 19:41 pts/0    00:00:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox ibus

**Comment by fujiwarat** [comment]
>  (process:12420): IBUS-CRITICAL **: 17:47:24.653: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed

Which process was this error output by?

**Comment by Taki132** [comment]
> >  (process:12420): IBUS-CRITICAL **: 17:47:24.653: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
> 
> Which process was this error output by?

I exec this on one line or running sh file, hyprland config (merge or spilt this has error)
If i split this command on terminal (run ibus manually) it does not have error

**Comment by Taki132** [comment]
> > >  (process:12420): IBUS-CRITICAL **: 17:47:24.653: ibus_bus_set_global_engine: assertion 'IBUS_IS_BUS (bus)' failed
> > 
> > Which process was this error output by?
> 
> I exec this on one line or running sh file, hyprland config (merge or spilt this has error)
> If i split this command on terminal (run ibus manually on two command) it does not have error

**Comment by fujiwarat** [comment]
Do you mean the error is the output of a script file whose content is `ibus-daemon -xdr && ibus engine Bamboo` ?
ibus-daemon does not exit and the client command ibus has to wait for the ibus-daemon ready.

> If i split this command on terminal (run ibus manually on two command) it does not have error

Do you mean you won't see your problem if you add a idle time between two commands?
E.g. `ibus-daemon -xdr && sleep 10 &&  ibus engine Bamboo`
