### ISSUE TITLE
Is there any way to add country flag icons for the current selected language on system tray?

### ISSUE THREAD

**Issue by ItzCamm** [ibus/ibus#2583]
I'm using ibus with AwesomeWM / OpenSuse. 

This would be a great feature, though I'm sure it's possible to add replace the "en" icon for english with a US/UK flag.

Has there been achieved before?

Thank you.

**Comment by fujiwarat** [comment]
I think the "en" icon will have an appeded "_2" if you have both US and UK layout.
I also think many strings causes small a font size and the current implementation is good.
If you still discuss the issue, it would be good to report your issue in gnome-shell while I don't agree with your idea.
