### ISSUE TITLE
Can't type accented characters properly in OmegaT with IBus 1.5.29-rc2 (Fedora 39)

### ISSUE THREAD

**Issue by JulioCinquina** [ibus/ibus#2585]
Hi there. I use an open-source tool called [OmegaT](https://github.com/omegat-org/omegat) to do my work as a translator. After the latest IBus update on Fedora 39, I was unable to type accented characters properly in OmegaT anymore, so I had to downgrade IBus back to the previous version.

I'd really appreciate it if you could look into this issue. Please let me know if you need any additional information. Thank you for your time.

---

**Which distribution and version?:** 
Fedora 39

**Which desktop environment and version?:** 
GNOME 45.1

**Which session type?:** 
Wayland

**Which application and version?:** 
OmegaT 6.0.0 (1bf1729c) running on Java 11.0.19 (included with the application)

**IBus version?:** 
IBUs 1.5.29-rc2 (ibus-1.5.29~rc2-1.fc39.x86_64)

**Issue description:** 

After upgrading IBus to the version stated above, I can't type accented characters properly in OmegaT. For example, the sequence `´` + `o` does not result in `ó`. If I type `o` again, I get `o´` (please watch the video below).

This does not happen on any other application that I use.

I've had to downgrade back to version 1.5.29-rc1 (ibus-1.5.29~rc1-3.fc39.x86_64) for the time being. I can type accented characters properly in OmegaT using that version.

https://github.com/ibus/ibus/assets/66167767/0623e311-fdba-4346-8fe2-9f7014ed30d5

**Steps to reproduce:** 
1. Download OmegaT 6.0.0 (Linux with 64-bit JRE): [direct download](https://sourceforge.net/projects/omegat/files/OmegaT%20-%20Standard/OmegaT%206.0.0/OmegaT_6.0.0_Linux_64.tar.bz2/download) or [download page on official website](https://omegat.org/download).
1. Extract it: `tar xvjf OmegaT_6.0.0_Linux_64.tar.bz2`.
1. Run `linux-install.sh` to install it. (You can run `OmegaT` directly from the extracted directory, but I haven't tested the issue that way.)
1. Open it using `omegat` command or via the Apps panel.
1. Create a new project, set source and target languages (e.g.: English to Portuguese), and add a text file with some lines of text as a source file.
1. Try typing accented characters in the translation field below source text. E.g.:  `´` + `o`.
1. Note that the sequence above does not result in `ó`.
1. Typing `´` + `o` + `o` results in `o´`.

**Can you reproduce your problem when you restart ibus-daemon?:** 
Yes

**Do you see any errors when you run ibus-daemon with the verbose option?:** 
Yes, I pasted it below. However, I can see that Fedora 39 runs ibus-daemon with the `--panel disable` option by default, so I believe the error below is not related to my issue.

```
(ibus-daemon:107296): IBUS-WARNING **: 22:29:17.165: 22:29:17.165397: Can not execute component org.freedesktop.IBus.Panel: Failed to execute child process “/usr/libexec/ibus-ui-gtk3” (No such file or directory)
Can not execute default panel program
```
**Can you reproduce your problem with a new user account instead of the current your account?:** 
Yes, I created a new one for the video above.

**Comment by mike-fabian** [comment]
I can reproduce this exactly as described. Using Compose sequence to type accented characters works correctly in OmegaT 6.0.0 on Gnome Wayland when ibus-1.5.29~rc1-3.fc39.x86_64 is used but it does not work correctly with ibus-1.5.29~rc2-1.fc39.x86_64.

**Comment by mike-fabian** [comment]
Because `OmegaT 6.0.0` uses XIM, I also tested what happens when typing into `xterm` (because that also uses XIM). 
But in xterm  cannot reproduce the problem, compose works fine there.

**Comment by JulioCinquina** [comment]
@mike-fabian Thank you for investigating the issue. Could the problem be in OmegaT, and not IBus, then?

**Comment by HolonProduction** [comment]
I encounter the same behavior in Godot Engine. So it is likely not an OmegaT issue. While debugging, the Engine never received an `preeditDoneCallback` and `preeditDrawCallback` only was called once.

(Fedora 39 on Wayland, Downgrading IBus do 1.5.29-rc1 to solves the issue)

**Comment by mike-fabian** [comment]
What is Godot engine?

**Comment by MateusRodCosta** [comment]
Hi, I believe I'm having the same issue on Fedora Silverblue 39.

Programs affected are Android studio and also Godot.

Basically I run using the US International keyboard layout, when I type the double quotes every new keypress end up stuck and appearing on the same place as the last preedit text, only switching apps solves it.

On Godot the preedit text apaprently prevents any further text inut on the code editor.



> What is Godot engine?

It's a game engine, see https://godotengine.org/

**Comment by mike-fabian** [comment]
> @mike-fabian Thank you for investigating the issue. Could the problem be in OmegaT, and not IBus, then?

I guess it is an IBus problem.

**Comment by bmenant** [comment]
Having similar issue with Jetbrains’ IDE. Others Fedora 39 users have reported the issue:
https://youtrack.jetbrains.com/issue/IDEA-59679/Cannot-type-dead-keys-in-Linux#focus=Comments-27-8390027.0-0

**Comment by MateusRodCosta** [comment]
Filled downstream issue on RedHat Bugzilla to be able to create a Common Issues thread on Fedora Discussion: https://bugzilla.redhat.com/show_bug.cgi?id=2251423

**Comment by fujiwarat** [comment]
ibus-x11 sends "ó" to the application but the problem happens.
I will investigate the issue again.

**Comment by JulioCinquina** [comment]
@fujiwarat I've installed the new version on my system (ibus-1.5.29~rc2-4.fc39) and the issue is now fixed. Thank you!

**Comment by eigan** [comment]
I might not have the best setup, but pressing "Dead Grave" on my keyboard yields no result in PHPStorm for me.  I can type just fine in other software. 

Whats interesting is that it does recognize that I press the key in some parts of the UI.. 

![swappy-20240213_194422](https://github.com/ibus/ibus/assets/41789/fff8d834-eaee-45ad-a973-3387a00278d1)

Tested on `1.5.29-3`  ([pkgbuild](https://gitlab.archlinux.org/archlinux/packaging/packages/ibus/-/blob/main/PKGBUILD?ref_type=heads)) and `1.5.30+beta1-1` ([pkgbuild](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ibus-git))


My xkb symbol

```
default partial
xkb_symbols "basic" {
        include "no"

        // ...
        key <AE12> { [ backslash, dead_grave, dead_grave ] };
        
};
```

**Comment by danielsanfr** [comment]
On Manjaro Gnome I've installed the ibus and libibus `1.5.28`. I will need to wait until the `1.5.30` to try the fix.
