### ISSUE TITLE
Can't not use <Super>space shortcuts to change input methods

### ISSUE THREAD

**Issue by ryan-rober** [ibus/ibus#2587]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch

Which desktop environment and version?: 
Plasma 5.27.10 

Which session type?: 
 Wayland

IBus version?: 
IBus 1.5.29-rc2

Issue description:
Can't not use <Super>space shortcuts to change input methods

**Comment by fujiwarat** [comment]
I described how to setup IBus in PLasma Wayland.
https://groups.google.com/g/ibus-user/c/iXaBdVm_lV0
