### ISSUE TITLE
stuck in java application when type chinese

### ISSUE THREAD

**Issue by wonderfulyeah** [ibus/ibus#2589]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux(6.6.6-arch1-1pa)

Which desktop environment and version?: 
gnome 45

Which session type?: 
wayland

Which application and version?: 
all java application

IBus version?: 
IBus 1.5.29-rc2

Issue description:
In all java applications, the Chinese selected word will be stuck (press space), and the selected word can be displayed correctly after switching the input method.

![Screenshot from 2023-12-12 14-40-59](https://github.com/ibus/ibus/assets/17981532/d684fec6-ff51-4763-b78e-78dfc18f5d36)

**Comment by webmastercoolspot** [comment]
I thinks this bug is similar than mine in wine application that non US keyboard layout don't work.

@wonderfulyeah have you try to switch layout keyboard to qwerty US or/and revert to ibus 1.5.28 ?

**Comment by fujiwarat** [comment]
Deleted unrelative comment.

**Comment by wonderfulyeah** [comment]
> Which input method engine do you use? You can check it with `ibus engine` command.

rime,tried libpinyin and had the same problem。

**Comment by fujiwarat** [comment]
It's the preedit issue.
Duplicate of #2585

Currently I have a plan to release the 1.5.30 beta in  January.
