### ISSUE TITLE
Ibus can not input Chinese for some wine-based programs in Ubuntu20.04

### ISSUE THREAD

**Issue by hitbuyi** [ibus/ibus#2593]
My ubuntu use ibus as input method for Chinese, ibus work well for most of prgorams in ubuntu20.04,e.g., terminal, chrome, Libreoffice, BUT for some wine(wine5.0,6.0,8.0) program such wine-wechat,wine-qq, ibus doesn't work well,
I guess those wine-based program use QT-based window, and some one suggests install ibus-qt4 to solve this problem, I have some questions here
1, Does ibus need some QT librarys to support it? in my Ubuntu20.04, the installed Qt libs are bellow
```
root@george# dpkg --list | grep libqt

ii libqt5core5a:amd64        5.12.8+dfsg-0ubuntu2.1    amd64      Qt5 core module
ii libqt5dbus5:amd64         5.12.8+dfsg-0ubuntu2.1    amd64      Qt5 D-Bus module
ii libqt5gui5:amd64          5.12.8+dfsg-0ubuntu2.1    amd64      Qt5 GUI module
ii libqt5network5:amd64      5.12.8+dfsg-0ubuntu2.1    amd64      Qt5 network module
ii libqt5qml5:amd64          5.12.8-0ubuntu1           amd64      Qt5 QML module
ii libqt5quick5:amd64        5.12.8-0ubuntu1           amd64      Qt5 Quick library
ii libqt5quickwidgets5:amd64 5.12.8-0ubuntu1           amd64      Qt5 Quick Widgets library
ii libqt5svg5:amd64          5.12.8-0ubuntu1           amd64      Qt5 SVG module
ii libqt5widgets5:amd64      5.12.8+dfsg-0ubuntu2.1    amd64      Qt5 widgets module
```

if ibus need Qt libs to support Qt-based programs? Are thoese Qt LIBs above enough ? if they aren't enough, which parts needs to         be added?

2, Is ibus-qt4 not used now?

**Comment by fujiwarat** [comment]
I think you should test QT5 applications at first to identify your problem.

Qt5 GUI might have the IBus QT5 module but not sure.

ibus-qt4 is not used for QT5 applications.
