### ISSUE TITLE
Unicode character input: code input is recognised, the output is not the character

### ISSUE THREAD

**Issue by grahamperrin** [ibus/ibus#2595]
FreeBSD 15.0-CURRENT.

```text
% $XDG_CURRENT_DESKTOP
KDE: Command not found.
% pkg iinfo kde5
kde5-5.27.10.23.08.4_2
% uname -aKU
FreeBSD mowa219-gjp4-zbook-freebsd 15.0-CURRENT FreeBSD 15.0-CURRENT #0 main-n266992-604de40a024c: Tue Dec 19 01:34:50 GMT 2023     grahamperrin@mowa219-gjp4-zbook-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC amd64 1500007 1500007
% 
```

IBus 1.5.27

### Required characters do not appear

Steps to reproduce:

1. <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd>
2. <kbd>2</kbd><kbd>0</kbd><kbd>2</kbd><kbd>6</kbd>
3. observe _u2026_ (Unicode for `…` ellipsis character)
4. <kbd>Return</kbd> or <kbd>Enter</kbd>
5. nothing.

A screenshot of step 3: 

![image](https://github.com/ibus/ibus/assets/192271/3d7c957d-aeb1-400d-8555-99dbeab43649)

----

Can you reproduce your problem when you restart ibus-daemon? 

Not entirely reproducible. In Konsole: 

```text
% ibus exit

(process:90310): GVFS-RemoteVolumeMonitor-WARNING **: 02:11:19.781: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
% 
```

After that, Konsole became non-responsive to normal keyboard input. 

I used KRunner to run `ibus-daemon --xim &`, after which: 

1. Firefox is no longer bugged … Unicode character input succeeds
2. Konsole behaves as if the daemon is not running (steps 1 and 2 above produce a visible _2026_ **without** the letter _u_).

----

Do you see any errors when you run ibus-daemon with the verbose option?:

Yes. A 6.4 MiB file was produced (93353 lines). Extracts: 

```text
% ibus-daemon --xim --verbose &
[1] 90843
% 
(ibus-daemon:90843): GVFS-RemoteVolumeMonitor-WARNING **: 02:19:45.911: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

(ibus-dconf:90844): GVFS-RemoteVolumeMonitor-WARNING **: 02:19:45.966: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

(ibus-ui-gtk3:90845): GVFS-RemoteVolumeMonitor-WARNING **: 02:19:46.027: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

(ibus-extension-gtk3:90846): GVFS-RemoteVolumeMonitor-WARNING **: 02:19:46.057: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported
Gtk-Message: 02:19:46.183: Failed to load module "appmenu-gtk-module"
Gtk-Message: 02:19:46.249: Failed to load module "appmenu-gtk-module"

(process:90851): GVFS-RemoteVolumeMonitor-WARNING **: 02:19:46.253: remote volume monitor with dbus name org.gtk.vfs.UDisks2VolumeMonitor is not supported

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:46.503: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:46.503: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed
```

…

```text
(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:56.339: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:56.339: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:56.343: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:56.343: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed

```

…

```text
(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:20:12.160: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:20:12.166: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:20:12.166: ibus_emojier_update_emoji_to_data_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:20:12.166: ibus_emojier_update_annotation_to_emojis_dict: assertion 'data != NULL' failed

(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:20:12.166: ibus_emojier_update_category_to_emojis_dict: assertion 'data != NULL' failed```
```

----

Can you reproduce your problem with a new user account instead of the current your account? 

Yes.

**Comment by grahamperrin** [comment]
My original notes for this issue are at <https://codeberg.org/grahamperrin/freebsd-ports/issues/4>. 

> This began bugging me in August 2023.

Yesterday: 

> Reproducible with a fresh installation of [textproc/ibus](https://www.freshports.org/textproc/ibus/) on FreeBSD 14.0-RELEASE-p4 in a virtual machine.

**Comment by fujiwarat** [comment]
> IBus 1.5.27

It's an old version.

> 
(ibus-extension-gtk3:90846): IBUS-CRITICAL **: 02:19:46.503: ibus_serializable_deserialize_object: assertion 'g_type_is_a (type, IBUS_TYPE_SERIALIZABLE)' failed


I think it's fixed in the latest AFAIK.

**Comment by grahamperrin** [comment]
Thanks. For reference: 

- FreeBSD bug [276139 – textproc/ibus: update from 1.5.27 to 1.5.29](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276139)

(This complements portscout, e.g. <https://portscout.freebsd.org/henry.hu.sh@gmail.com.html>.)
