### ISSUE TITLE
is it possible to compile without systemd, how?

### ISSUE THREAD

**Issue by guyuming76** [ibus/ibus#2602]
i run what follows in main branch and get errors for missing systemd. But i don't use systemd in my system, anyway to disable it?
./autogen.sh --prefix=/usr --sysconfdir=/etc --enable-wayland

```

configure: error: Package requirements (
        systemd >= 0.7.5
    ) were not met:

Package 'systemd', required by 'virtual:world', not found
```

**Comment by fujiwarat** [comment]
I will find time but any contributors are welcome.

**Comment by fujiwarat** [comment]
Try `--help` option and `--disable-systemd-services`.
