### ISSUE TITLE
Inserting special unicode characters using name

### ISSUE THREAD

**Issue by psss** [ibus/ibus#2603]
I'm quite often using the `Ctrl-Shift-U` keyboard shortcut to insert special characters but it's not easy to remember all the numbers. Would it be possible to add support for inserting a special character based on the name? This could be much more user friendly than having to access an external window / dedicated application for searching and selecting the right char.

### Example

* Press `Ctrl-Shift-U`
* Type `non break space`
* Hit `Enter` to confirm

**Comment by fujiwarat** [comment]
Super-perid can show the Emoji preedit and you can type the annotation name or just enter space key shows the Emoji dialog which has the Unicode category.

**Comment by psss** [comment]
Btw, is there a documentation describing how it exactly works?
