### ISSUE TITLE
Is it possible to use IBus instead of GNOME's input method manager on Ubuntu 22.04?

### ISSUE THREAD

**Issue by RobberFox** [ibus/ibus#2604]
**Issue description:**
After following all steps in the wiki I can open IBus-Preferences through `ibus-setup` but after adding input methods (English and Russian in my case) I can't switch between them (despite setting up a shortcut).
Do I have to switch distros/desktop environment or I can actually set it up on Ubuntu 22.04?
P.S. I want to use IBus to make a bash script for changing my input method (since GNOME made it very complex)

Ubuntu 22.04
GNOME 42.9
X11
IBus 1.5.26

**Comment by fujiwarat** [comment]
`ibus-setup`'s "Input Method" configuration is used for IBus panel and IBus panel is not used in GNOME but GNOME provides gnome-control-center for the input method configuration.

You should run `gnome-control-center keyboard` to setup the input sources.
