### ISSUE TITLE
BUG: ibus-daemon gvariant deserialization crash

### ISSUE THREAD

**Issue by secext2022** [ibus/ibus#2611]
Currently I am writing an engine in pure rust (with `zbus`) for ibus.

When I send a bad format `IBusText` from the engine to `ibus-daemon`, the whole ibus-daemon process crash and exit.
(in `org.freedesktop.IBus.Engine` signal `CommitText`)

I think the crash happen in `ibus/src/ibustext.c` `ibus_text_deserialize()`

Maybe this should be fixed in ibus-daemon ?
I mean that when ibus-daemon receive a bad format message from D-Bus, it should not crash.

----
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
ArchLinux (latest)

Which desktop environment and version?: 
GNOME 45.3

Which session type?: 
wayland

Which application and version?: 
(An engine I am writing .. . )

IBus version?: 
IBus 1.5.29-rc2

Issue description:

Steps to reproduce:

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

**Comment by fujiwarat** [comment]
What bad format IBusText did you send?

**Comment by secext2022** [comment]
I use this rust code to serialize IBusText:

```rust
use zbus::zvariant::{Array, Signature, Structure, Value};

pub fn make_ibus_text(text: String) -> Value<'static> {
    // `@a{sv}`
    let sig1 = Signature::from_str_unchecked("{sv}");
    let a1 = Array::new(sig1);
    // `@av`
    let sig2 = Signature::from_str_unchecked("av"); // HERE: `v` is OK, `av` is BAD
    let a2 = Array::new(sig2);

    // inner variant  struct
    let st1 = Structure::from(("IBusAttrList", a1.clone(), a2.clone()));

    // outer variant  struct
    let st2 = Structure::from(("IBusText", a1.clone(), text, Value::new(st1)));

    Value::new(st2)
}
```

Then build my engine and run:

```
ibus-daemon --verbose
```

Then when the engine send CommitText to ibus-daemon, get this crash:

```
(ibus-daemon:27082): GLib-CRITICAL **: 15:08:16.864: the GVariant format string 'av' has a type of 'av' but the given value has a type of 'aav'

(ibus-daemon:27082): GLib-CRITICAL **: 15:08:16.864: g_variant_get_child: assertion 'valid_format_string (format_string, TRUE, child)' failed
fish: Job 1, 'ibus-daemon --verbose' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by secext2022** [comment]
I think ibus-daemon should handle this error more gracefully, instead of just crash.

For example, I think ibus-daemon is the same important as GNOME desktop environment.
Imagine that the whole GNOME desktop environment crash, just because a small program send a bad format message.
I think this is not acceptable.

Even worse, an untrusted application in a sandbox (such as flatpak) can still send a bad format message, which cause a crash on host.

**Comment by fujiwarat** [comment]
Permitted clients only can send IBusText with /usr/share/ibus/component and it's good to crash your wrong application before it's available in public.
