### ISSUE TITLE
Input focus jumps with chrome

### ISSUE THREAD

**Issue by jidanni** [ibus/ibus#2616]
Regarding chrome focus jumping,
於 chrome 跳前問題

When I am entering text in chrome,
當我於 chrome 填表時，

I type "nin2hao3" to get "您好"
原來輸入 "nin2hao3" 能得 "您好"。

But halfway I end up with "o您ha" .
結果輸入到一半， 變成 "o您ha" 。

OK, I will fill out forms elsewhere, and then paste them in to chrome,
field by field.

Versions of packages ibus-chewing depends on:
ibus                                         1.5.29-1

Package: google-chrome-beta
Version: 123.0.6312.4-1
on Debian sid.

**Comment by chuahou** [comment]
I also encounter this issue with a different input method (mozc), using ibus 1.5.29 on Firefox, Discord, Joplin with `GTK_IM_MODULE=xim` on NixOS. The issue is not present on ibus 1.5.28.

**Comment by fujiwarat** [comment]
I don't see any issues with the latest ibus and I think you should use GTK_IM_MODULE=ibus.
