### ISSUE TITLE
i-bus panel consumes a lot of memory 80-100 MB, can i run i-bus without it.

### ISSUE THREAD

**Issue by malnaanah** [ibus/ibus#2621]
i-bus panel consumes a lot of memory 80-100 MB, can i run i-bus without it. 
I use Kubuntu 22.04.

**Comment by fujiwarat** [comment]
`ibus-daemon --panel disable` works for Plasma Xorg but IBus panel is required for Plasma Wayland.

**Comment by malnaanah** [comment]
(ibus-daemon --panel disable) did not work. I use kubuntu 22.04 Xorg.

**Comment by fujiwarat** [comment]
> (ibus-daemon --panel disable) did not work. I use kubuntu 22.04 Xorg.

I guess you don't use IBus panel but another panel which is not maintained by this site.

**Comment by malnaanah** [comment]
The panel is installed by the package from kubuntu repository.
here is a picture of ibus related apps.
![Screenshot_20240403_135101](https://github.com/ibus/ibus/assets/45626803/40a10eef-f8b4-4ba8-8ebe-cf7c227196e0)

**Comment by fujiwarat** [comment]
OK, you use ibus-ui-gtk3 and then `ibus-daemon --panel disable` should works.

**Comment by malnaanah** [comment]
Most of the time it does not work, especially if I run it as a startup file. Some times it works, but not in  a reliable way.
I think that the panel should be rewritten to consume less memory.

**Comment by malnaanah** [comment]
My main problem is when pressing CTRL-B while using Arabic layout, which means pressing CTRL-ﻻ, in this case it types ﻻ instead of taking it as a short cut for bold font (when using libreoffice). Uninstalling **libobasis24.2-kde-integration** package solves the problem for libreoffice, since gtk will be used, but the gtk theme is terrible. 
I found the perfect solution is to install i-bus, but it consumed 80-100 MB of ram for the panel, which is large, especilly for low specs computers.

**Comment by fujiwarat** [comment]
> Most of the time it does not work,

What is it? You should confirm the result with `ps` command after you run `ibus-daemon --panel disable`.

> My main problem is when pressing CTRL-B while using Arabic layout, which means pressing CTRL-ﻻ, in this case it types ﻻ instead of taking it as a short cut for bold font (when using libreoffice). Uninstalling libobasis24.2-kde-integration package solves the problem for libreoffice, since gtk will be used, but the gtk theme is terrible.

It should be another issue and you should report your issue with a bug template with detail.

**Comment by malnaanah** [comment]
I figured out that when I disable ibus and re-login and run the command (ibus-daemon --daemonize  --panel disable) it works. However if restart the computer, it does not work.
The ibus processes in both cases are the same, as shown in the picture below:

![Without panel](https://github.com/ibus/ibus/assets/45626803/fbead5f2-296e-44e0-9426-fa30bb03eacd)

When I activate ibus with panel, the ibus processes are as shown in the picture below.

![With panel](https://github.com/ibus/ibus/assets/45626803/fc1d30cd-c99e-44d4-8ef4-b208f32312f1)

the CTRL-ﻻ problem is with the input system used by default in KDE plasma, and it is solved by ibus. However the panel memory consumption is annoying.

**Comment by fujiwarat** [comment]
> However if I restart the computer, it does not work.

Seems you still mistake the usage. Anyway --panel disable should work.

**Comment by malnaanah** [comment]
Maybe there is something in ibus that is not activated unless the panel is running (even if the daemon is running).

**Comment by fujiwarat** [comment]
I cannot comment your issue until you give the your problems with your exact producing logs with detail while you just said not activate, does not work.

**Comment by malnaanah** [comment]
Using "KDE Menu> Settings>Input Method" I reverted to the default settings (No Ibus), then restarted the computer and ran the commands (ibus-daemon --panel disable) and (ibus-daemon --xim --replace --daemonize) in both commands ibus did not work but in the second time the panel was shown. The ouput of the command (cat /var/log/syslog | grep ibus) is:


Apr  6 00:28:08 mahmoud-TAGTECH dbus-daemon[948]: [session uid=1000 pid=948] Activating service name='org.freedesktop.portal.IBus' requested by ':1.59' (uid=1000 pid=1773 comm="ibus-daemon --panel disable " label="unconfined")
Apr  6 00:35:54 mahmoud-TAGTECH dbus-daemon[907]: [session uid=1000 pid=907] Activating service name='org.freedesktop.portal.IBus' requested by ':1.48' (uid=1000 pid=1445 comm="ibus-daemon --xim --replace --daemonize " label="unconfined")


Then I activated ibus and restart the computer and ibus works fine. The ouput of the command (cat /var/log/syslog | grep ibus) is:


Apr  6 00:39:32 mahmoud-TAGTECH dbus-daemon[909]: [session uid=1000 pid=909] Activating service name='org.freedesktop.portal.IBus' requested by ':1.7' (uid=1000 pid=985 comm="/usr/bin/ibus-daemon --daemonize --xim " label="unconfined")
Apr  6 00:39:32 mahmoud-TAGTECH dbus-daemon[909]: [session uid=1000 pid=909] Activating via systemd: service name='org.a11y.Bus' unit='at-spi-dbus-bus.service' requested by ':1.12' (uid=1000 pid=995 comm="/usr/libexec/ibus-extension-gtk3 " label="unconfined")
Apr  6 00:39:32 mahmoud-TAGTECH at-spi-bus-launcher[1062]: dbus-daemon[1062]: Activating service name='org.a11y.atspi.Registry' requested by ':1.2' (uid=1000 pid=993 comm="/usr/libexec/ibus-ui-gtk3 " label="unconfined")
Apr  6 00:39:32 mahmoud-TAGTECH dbus-daemon[909]: [session uid=1000 pid=909] Activating via systemd: service name='org.freedesktop.portal.Desktop' unit='xdg-desktop-portal.service' requested by ':1.18' (uid=1000 pid=995 comm="/usr/libexec/ibus-extension-gtk3 " label="unconfined")


Maybe the problem is with ibus integration with KDE plasma.

**Comment by fujiwarat** [comment]
> Using "KDE Menu> Settings>Input Method" I reverted to the default settings (No Ibus), then restarted the computer 

What is the "Input Method" tool? Maybe it's a tool provided by your distro. Probably you could check it with `ps` command but anyway,
Can you check the result with `ps -ef | grep ibus` command to make sure any ibus processes do not run before you run ibus-daemon by manual?

and ran the commands (ibus-daemon --panel disable) and (ibus-daemon --xim --replace --daemonize) in both commands ibus did not work but in the second time the panel was shown. 

I don't ask to run `ibus-daemon --xim --replace --daemonize` which should run the panel.

Can you check the result with `ps -ef | grep ibus` command to make sure `ibus-ui-gtk3` does not run when you run ibus-daemon?

**Comment by malnaanah** [comment]
This is the output of  (ps -ef | grep ibus) command for the the following senarios:

Normal operation by desktop settings, ibus works fine.
mahmoud     1479       1  0 11:31 ?        00:00:00 /usr/bin/ibus-daemon --daemonize --xim
mahmoud     1492    1479  0 11:31 ?        00:00:00 /usr/libexec/ibus-dconf
mahmoud     1495    1479  0 11:31 ?        00:00:00 /usr/libexec/ibus-ui-gtk3
mahmoud     1496    1479  0 11:31 ?        00:00:01 /usr/libexec/ibus-extension-gtk3
mahmoud     1499       1  0 11:31 ?        00:00:00 /usr/libexec/ibus-x11 --kill-daemon
mahmoud     1503    1388  0 11:31 ?        00:00:00 /usr/libexec/ibus-portal
mahmoud     1613    1479  0 11:31 ?        00:00:00 /usr/libexec/ibus-engine-simple


command (ibus-daemon --panel disable), ibus does not work as expected.
mahmoud     2153    1859  0 12:23 pts/1    00:00:00 ibus-daemon --panel disable
mahmoud     2156    2153  0 12:23 pts/1    00:00:00 /usr/libexec/ibus-dconf
mahmoud     2158    2153  1 12:23 pts/1    00:00:00 /usr/libexec/ibus-extension-gtk3
mahmoud     2161    1318  0 12:23 ?        00:00:00 /usr/libexec/ibus-portal


command (ibus-daemon), ibus does not work as expected.
mahmoud     1882    1875  0 12:25 pts/2    00:00:00 ibus-daemon
mahmoud     1885    1882  0 12:25 pts/2    00:00:00 /usr/libexec/ibus-dconf
mahmoud     1887    1882  0 12:25 pts/2    00:00:00 /usr/libexec/ibus-ui-gtk3
mahmoud     1888    1882  3 12:25 pts/2    00:00:00 /usr/libexec/ibus-extension-gtk3
mahmoud     1893    1296  0 12:25 ?        00:00:00 /usr/libexec/ibus-portal
mahmoud     1905    1882  0 12:25 pts/2    00:00:00 /usr/libexec/ibus-engine-simple

**Comment by fujiwarat** [comment]
From your log, `--panel disable` works fine to disable the panel.

If you mean another meaning in `ibus does not work as expected`, file another issue using the issue template again instead of just mentioning "i-bus panel consumes a lot of memory 80-100 MB, can i run i-bus without it.".

> i-bus panel consumes a lot of memory 80-100 MB, can i run i-bus without it.

This issue is resolved.

**Comment by malnaanah** [comment]
I don't think the issue is resolved, and I suggest to try "ibus-daemon --panel disable" command on kubuntu and see if it works properly.   By properly I mean when CTRL-ﻻ  is pressed it should be taken as CTRL-B shortcut not typing the letter ﻻ in Arabic.

Anyway, I filed a new issue and I hope it describe the problem.
https://github.com/ibus/ibus/issues/2634

Regards,

**Comment by fujiwarat** [comment]
> I don't think the issue is resolved

Again, explain what is your issue at firsts with the bug template. I think your issue is not relative with the panel so you should not ask to disable the panel.
