### ISSUE TITLE
IBUS Compilation error

### ISSUE THREAD

**Issue by 96gawhale** [ibus/ibus#2625]
I have been trying to compile the **ibus** **source** from scratch in **debian** desktop environment.

Not have been able to solve the below problem:
checking for dconf >= 0.7.5... no
configure: error: Package requirements (dconf >= 0.7.5) were not met:

Package 'dconf', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DCONF_CFLAGS
and DCONF_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

I have tried to install dconf related packages. Also resorted to setting the flags manually but at the end it then gives problem while ding make.

Also, are there any dedicated ibus forums.

**Comment by fujiwarat** [comment]
> configure: error: Package requirements (dconf >= 0.7.5) were not met:

You didn't install dconf development package.
