### ISSUE TITLE
Can't type in graphical text fields in some GTK-based applications under XIM

### ISSUE THREAD

**Issue by spinnylights** [ibus/ibus#2633]
Which distribution and version?: 
Gentoo, vanilla kernel 6.8.2.

Which desktop environment and version?: 
i3 4.23.

Which session type?: 
X11.

Which application and version?: 
Firefox 124.0.1, Signal Desktop 7.3.0.

IBus version?: 
I've tested with the latest commit as of now ([7078329](https://github.com/ibus/ibus/commit/707832954e1aaaae9a695d9771e84a21844be605)) as well as versions 1.5.29 and 1.5.27.

Issue description:
In some GTK-based applications, after starting ibus with `ibus-daemon -drx`, typing in text input fields (such as any text input area in Firefox or Signal Desktop—the URL bar, text input fields on websites, the message entry and search widgets in Signal, etc.) does nothing. No characters appear, and also keyboard shortcuts stop working as long as the text field has focus (like Ctrl-T to open a new tab in Firefox). Some apparently-GTK-based applications do not seem have this issue, at least on my system (Ardour 8.4, Inkscape 1.3.2).

This problem first appeared after I upgraded the kernel from 6.8.1 to 6.8.2, without upgrading any other packages simultaneously, so I think it's possible that something in 6.8.2 is related. I can downgrade to 6.8.1 if it would help for troubleshooting purposes.

Steps to reproduce:
1. With ibus running under XIM, open an application such as Firefox 124.0.1 or Signal Desktop 7.3.0.
1. Focus on a text input field, such as by clicking on it, using the tab key, a special shortcut such as Ctrl-L in Firefox for the URL bar, etc.
1. Try to type anything.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes.

Do you see any errors when you run ibus-daemon with the verbose option?:
No errors, only the following warnings:
```
(ibus-ui-gtk3:5092): IBUS-WARNING **: 19:42:31.689: panel.vala:120: Checking Wayland is disabled

(ibus-extension-gtk3:5094): IBUS-WARNING **: 19:42:31.711: panelbinding.vala:246: Checking Wayland is disabled

(ibus-ui-gtk3:5092): IBUS-WARNING **: 19:42:31.771: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
```

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
This would be a bit labor-intensive to attempt, but I'll give it a go if it sounds helpful.

**Comment by fujiwarat** [comment]
I cannot reproduce your issue.
You could check your ibus enviroment with `ibus im-module --type gtk3` command.

**Comment by johndo100** [comment]
Same issue here.
I couldn't type anything in firefox when I set GTK_IM_MODULE=xim.
Same as with fcitx, seems it is not ibus bug.

**Comment by fujiwarat** [comment]
You should use GTK_IM_MODULE~ibus

**Comment by johndo100** [comment]
Yes. I'm using it now but ibus will not work: vscode, choromium..

**Comment by johndo100** [comment]
Yes. My config is bellow:

```
# ~/.profile
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
QT4_IM_MODULE=ibus
CLUTTER_IM_MODULE=ibus
GLFW_IM_MODULE=ibus
```

**Comment by fujiwarat** [comment]
> It worked perfect before when I set GTK_IM_MODULE=xim

That would be another issue but I don't suppose to use XIM in GTK applications.

> And yes, my current config is bellow:

I wonder if you install the application with a specific location likes snap.
E.g. /usr/bin/google-chrome uses /opt/google/chrome/chrome

**Comment by johndo100** [comment]
> I wonder if you install the application with a specific location likes snap.
> E.g. /usr/bin/google-chrome uses /opt/google/chrome/chrome

Yes. New programs install on Void Linux always place in `/usr/bin/`.
```
$ whereis chromium
chromium: /usr/bin/chromium /usr/lib/chromium /usr/share/man/man1/chromium.1
```

**Comment by fujiwarat** [comment]
I mean /usr/bin/chromium is a pointer and the entity exists in another location which cannot be shown with which and whereis command.

**Comment by johndo100** [comment]
> I mean /usr/bin/chromium is a pointer and the entity exists in another location which cannot be shown with which and whereis command.

No. It place in `/usr/bin/chromium` without any soft-link.
Ibus doesn't work on it and some apps and that's why I need to set `GTK_IM_MODULE=xim` before.
Firefox and many other apps are fine.

https://github.com/ibus/ibus/assets/99111848/81f2a329-b19d-4727-baca-1c15653112bf

**Comment by fujiwarat** [comment]
> No. It place in /usr/bin/chromium without any soft-link.

Which distro do you use? I assumed Ubuntu but not.
And how do you install it?

I think you could try chrome from https://www.google.com/chrome/ and it works with GTK_IM_MODULE.

>

**Comment by johndo100** [comment]
> > No. It place in /usr/bin/chromium without any soft-link.
> 
> Which distro do you use? I assumed Ubuntu but not. And how do you install it?
> 
> I think you could try chrome from https://www.google.com/chrome/ and it works with GTK_IM_MODULE.
> 
> >

It is Void Linux. I install it by package manager (xbps).
It is not working on all chromim based browsers and some Electron apps like vscode.
There is no Chrome available in Void Linux repos but I will search and try it.

**Comment by fujiwarat** [comment]
> It is Void Linux. I install it by package manager (xbps).

Ah, sorry, you already mentioned it.
Seems your distro build chromium with a specific way.

I confirmed vscode can switch the im client with GTK_IM_MODULE with https://azure.microsoft.com/ja-jp/products/visual-studio-code in Fedora.

**Comment by spinnylights** [comment]
Hi, sorry I haven't said anything else until now—I've been swamped getting taxes ready and haven't wanted to shut down the X server in the interest of time (maybe a little extreme but I'm getting nervous). Anyway, today I'm doing weekly updates so I finally rebooted, and found that

```
export GTK_IM_MODULE='ibus'
export QT_IM_MODULE='ibus'
export XMODIFIERS='@im=ibus'
```

in my `.xinitrc` seems to have fixed this issue. I had `GTK_IM_MODULE` and `QT_IM_MODULE` set to `xim` before. The issue reappears if I change them back so this seems to be an effective solution.

fujiwarat, thank you for trying to reproduce the issue I was having and also for the advice. ありがとうございました。今またFirefoxに日本語を入力できるんです。😛
