### ISSUE TITLE
"--panel disable" option does not work properly in kubuntu 22.04

### ISSUE THREAD

**Issue by malnaanah** [ibus/ibus#2634]
By default, in Kubuntu 22.04 when I press CTRL-ﻻ in arabic layout, which corresponds to CTRL-B, it does not take it as CTRL-B (does not make the font bold for example in LibreOffice), instead it types the letter ﻻ, which is rather annoying.

To solve the problem I installed ibus package and it solved the problem. However, they systemtray panel consumes about 80 MB which is large for limited memory computers. I tried running ibus-daemon with "--panel disable" option, and it runs ibus processes but it does not work as supposed, where when I press CTRL-ﻻ it types the letter ﻻ instead of taking CTRL-B shortcut. And even if run ibus-daemon without the "--penel disable" option it does not work as supposed even though the panel is shown in the systemtray. Currently I just activated ibus using "input method" utility in Kubuntu and it works fine, however I wish i can minimize the consumed memory.
Maybe the panel code could be revised to consume less memory, or the "--panel disable" option could be reviwed.
Note: After I disable the ibus using "input method" utility, I restart the computer and then apply the ibus-daemon comand.

Regards,

**Comment by fujiwarat** [comment]
Please use the bug template.
