### ISSUE TITLE
How can toggle between three input methods?

### ISSUE THREAD

**Issue by hwypengsir** [ibus/ibus#2635]
There are three input methods in my ibus framework:

![set1](https://github.com/ibus/ibus/assets/512610/0913399a-367f-4840-8be8-e9ad52f04d44)

I have set the `ctrl + space`  as toggling key between the three input methods.

![set2](https://github.com/ibus/ibus/assets/512610/edfc8953-f453-40be-932d-1fdb43e96574)

I want to toggle between the three input methods when click `ctrl+space`:

    English-English(US)
    Chinese-Intelligent PinYin
    Chinese-Rime

When the initial input method is `English-English(US)`，

click `ctrl+space` ，toggle to `Chinese-Intelligent PinYin`    
click `ctrl+space` ，toggle to `English-English(US)`    
click `ctrl+space` ，toggle to `Chinese-Intelligent PinYin`    

The `Chinese-Rime` never called out ,How can toggle between three input methods?

**Comment by fujiwarat** [comment]
You should use the bug template.
Normally an engine list popup window is launched with the shortcut key and I don't think your issue an ibus issue.
