### ISSUE TITLE
Can not switch input method without GTK_IM_MODULE=ibus in GTK4 popover

### ISSUE THREAD

**Issue by everyx** [ibus/ibus#2638]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
GNOME 46.1

Which session type?: 
Wayland

Which application and version?: 
```
❯ gnome-text-editor --version
Text Editor 46.1 (46.1)

            GTK: 4.14.4 (Compiled against 4.14.2)
  GtkSourceView: 5.12.0 (Compiled against 5.12.0)
        Enchant: 2.6.5
```

IBus version?: 
IBus 1.5.30

Issue description:
I use rime input engine with IBus, and I cann't switch input method in GTK4 popover when `GTK_IM_MODULE=ibus`, this issue seems to have appeared after the GTK4 update, I have opened a issue at GTK project https://gitlab.gnome.org/GNOME/gtk/-/issues/6593 , but the maintainer said that "I am considering this to be a problem of the affected input methods (ibus, fcitx, etc)."

https://gitlab.gnome.org/GNOME/gtk/uploads/bcaaae56c0ded838ed34d3b1347d1ddf/with-text-input-v3.webm

Steps to reproduce:
1. Make sure not use IM module (set GTK_IM_MODULE) with GNOME wayland session
2. Run nautilus, select a file or directory, then try to rename it.
3. Press shift to switch Input Method to a Chinese Input Method (iBus with rime engine) and try to rename with some Chinese words.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 

**UPDATE:**
> I think this might be a mutter bug introduced with the grab changes in 46
> 2024-05-26 by @skeller, see https://gitlab.gnome.org/GNOME/mutter/-/issues/3502

**Comment by Xutong-J** [comment]
i met the issue too.
and how to solve it?

**Comment by coolkys** [comment]
Experienced this issue as well

**Comment by juhp** [comment]
Setting GTK_IM_MODULE should be unnecessary in GNOME Wayland for gtk >= 3 I think.

**Comment by coolkys** [comment]
That's what the GTK devs said, yes. Regardless, input is still broken.

**Comment by fujiwarat** [comment]
I think Super-space works in Wayland and I assume this issue for GTK_IM_MODULE=ibus . I confirmed it with nautilus.

If you has the similar issue in GNOME Wayland, you might have a wrong configuration or your issue would be an engine specific but not ibus core.

**Comment by coolkys** [comment]
Just to clarify for "Super-space works", are you talking about input method switching?
If so, that already works for us too, that's not the complaint here. I can switch inputs fine, it's just that the input is in English.
Do you mean that you succeeded in inputting IME required languages(Anthy etc.) in Nautilus rename popup?

**Comment by fujiwarat** [comment]
@coolkys  Right. I didn't test the input bug switching only.

Input methods require the focus-in event to get the input cursor is activated but I guess GtkPopoer does not provide the focus-in/out events since it's a popup.

Probably we need to add another feature to enable input methods on no focus text box.
E.g.
GTK_INPUT_PURPOSE_POPUP in GtkInputPurpose enum and content_purpose.popup in Wayland text-input protocol.

**Comment by kanru** [comment]
Observed this today. I can't use ibus in the Nautilus rename popup.

It looks like a patch has been created for mutter https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3787

**Comment by coolkys** [comment]
If you're using fedora, there's a guide on reddit to patch this yourself

[](https://www.reddit.com/r/Fedora/comments/1d4v2c0/tutorial_how_to_fix_broken_ime_inputs_for_gtk4 )

**Comment by everyx** [comment]
closed by upstream https://gitlab.gnome.org/GNOME/mutter/-/issues/3502
