### ISSUE TITLE
Per-window state does not work

### ISSUE THREAD

**Issue by Yukinoroh** [ibus/ibus#2641]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
LinuxMint 21.3

Which desktop environment and version?: 
MATE 1.26.0

Which session type?: 
X11

Which application and version?: 
All applications

IBus version?: 
IBus 1.5.26

Issue description:
In ibus config I have 全てのアプリケーション間で同じ入力メソッドを共有する checked off.
If I understand well it should allow to have a per-window state of the IME (between Japanese or English), but it does not work. Checkin it on does not change anything either: ibus only has a global-state.

Steps to reproduce:
1. Change input to Japanese in app A.
1. Go to app B. Change input to English.
1. Go back to app A. Try to type and notice it types in English.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
yes
-
(ibus-ui-gtk3:7861): IBUS-WARNING **: 11:58:21.569: panel.vala:280: If you launch KDE5 on xterm, export XDG_CURRENT_DESKTOP=KDE before launch KDE5.
(ibus-ui-gtk3:7861): IBUS-WARNING **: 11:58:21.584: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
Removing imported_words_ibus__oldchar
Removing imported_words_ibus__era
Removing imported_words_ibus__zipcode
Removing ibus__symbol
(and this "Removing" thing keeps repeating)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
I don't think this is user-related, I'm on a fresh install.

**Comment by fujiwarat** [comment]
I think you mean the input modes of Hiragana or English per window in ibus-anthy.
Actually the main frame is already implemented in ibus core but I don't implement it in ibus-anthy yet.
It would be good to report your RFE to ibus-anthy.

**Comment by Yukinoroh** [comment]
I'm confused. What is the purpose of "全てのアプリケーション間で同じ入力メソッドを共有する" exactly?
How is it supposed to work?

**Comment by fujiwarat** [comment]
It provides IME level and you could check the global engine names with `ibus engine` when you enable the setup option and I think the disable mode works.
I'm talking about the input modes of Hiragana, Katanaka, Eisu and so on.

**Comment by Yukinoroh** [comment]
What do you mean by "It provides IME level". Could you explain in Japanese? I feel that either this feature really does not work, or the label is misleading.

**Comment by fujiwarat** [comment]
IME - input method engine whose name can be shown with `ibus engine` command as I noted above.

```
    Change input to Japanese in app A.
    Go to app B. Change input to English.
    Go back to app A. Try to type and notice it types in English.
```

Please rephrase your steps. A -> gedit, B -> gnome-terminal, Japanese & English to the IME names  and describe your issue with detail.
I cannot reproduce your issue.

**Comment by Yukinoroh** [comment]
I am using ibus-anthy.
App A and B can be any application. I get the bug using gedit and gnome-terminal, yes.

What is "全てのアプリケーション間で同じ入力メソッドを共有する" supposed to mean in case there is only one input method installed?

**Comment by Yukinoroh** [comment]
For your information, Fcitx has an option labeled ウィンドウ間で状態を共有

The label in ibus is kind of cryptic as I am not sure it is a similar feature.

**Comment by fujiwarat** [comment]
I cannot reproduce your issue in Fedora 40 and I upload my result.
https://github.com/ibus/ibus/assets/105929/29fc57a2-a086-46d8-b87a-344714d911f5

**Comment by Yukinoroh** [comment]
You can't test the bug with only one application!
This is what happens on my side.

https://github.com/ibus/ibus/assets/5343988/42a8dbc6-1d9c-494f-a72b-62cce3be47fd

**Comment by Yukinoroh** [comment]
And the same thing happens with the option on. It just does nothing.

https://github.com/ibus/ibus/assets/5343988/8fbf9143-9b51-41d5-b660-67b115e4b9c8

**Comment by fujiwarat** [comment]
Why you changed applications.
Again you should describe your issue with detail.

**Comment by fujiwarat** [comment]
You should see my screen record which shows gnome-terminal is xkb:us::eng and gedit is anthy.

**Comment by Yukinoroh** [comment]
I have described that in the bug description!
I wrote "per-window state". Should I post it in Japanese?

**Comment by Yukinoroh** [comment]
per-window state -> アプリケーションごとの状態
 
You can't test that with only one application open!

**Comment by Yukinoroh** [comment]
I am using ibus-anthy as well.
It will not remember the state when I switch applications.

**Comment by fujiwarat** [comment]
Again
You should see my screen record which shows gnome-terminal is xkb:us::eng and gedit is anthy.

**Comment by Yukinoroh** [comment]
> Again You should see my screen record which shows gnome-terminal is xkb:us::eng and gedit is anthy.
And how does that relate to my bug report? You're not even testing the input in two different applications...

**Comment by Yukinoroh** [comment]
1. アプリAの中、日本語に切り替えて入力する
2. アプリBの中、英語に切り替えて入力する
3. アプリAの中、入力してみる。日本語のはずですが、英語になってる。

**Comment by fujiwarat** [comment]
Stop to use App A and App B as I said many times.

**Comment by fujiwarat** [comment]
> You're not even testing the input in two different applications...

I test gnoem-terminal and gedit.

**Comment by Yukinoroh** [comment]
↑AもBみお個別で起動したアプリです。

**Comment by Yukinoroh** [comment]
I am in MATE, I don't have gnome-terminal and gedit, but I can try with mate-terminal and xed.

**Comment by Yukinoroh** [comment]
It doesn't matter which application is A and which is B.

**Comment by Yukinoroh** [comment]
グローバルメソッドの設定がオフとなってますが、グローバルメソッドのようになってます（アプリごとの状態が記憶されていない）

**Comment by Yukinoroh** [comment]
Same testing with Fcitx. Per-window state works.

https://github.com/ibus/ibus/assets/5343988/00f7eb31-3152-4492-8721-2a823ab1a937

**Comment by fujiwarat** [comment]
> ↑AもBみお個別で起動したアプリです。

You should describe your actual application names.

> App A and B can be any application. I get the bug using gedit and gnome-terminal, yes.
> I am in MATE, I don't have gnome-terminal and gedit, but I can try with mate-terminal and xed.

Why you continue to tell a lie as you didn't try any applications.

> It doesn't matter which application is A and which is B.

I does mutter for me.
It would be good to report your issue again with detail.

If you don't have gedit, it would be good to install a text application for the test. E.g. gnote or leafpad as I can see gedit and gnote in my MATE desktop.
As I suggested the example with the screen record, try:

1. Set xkb:us::eng on mate-terminal and confirm IBus panel icon shows "EN"
2. Switch to gnote and set anthy on gnote and confirm IBus panel icno shows "あ" or "_A"
3. Switch back to mate-termianl and confirm IBus panel icon shows "EN"

Of course, when I switch back to gnote, IBus panel icon shows "あ" again.

**Comment by fujiwarat** [comment]
> IBus icon panel does not show "EN".

You should check my screen record again. 

I already explained you should check the engine name with `ibus engine` command.

>> it provides IME level and you could check the global engine names with `ibus engine` when you enable the setup option and I think the disable mode works.

**Comment by Yukinoroh** [comment]
"ibus engine" says "anthy"

**Comment by fujiwarat** [comment]
And switch the current engine with Supers-space or click on the IBus panel icon to "English - English (US)" and check the engine name with the command again.

**Comment by Yukinoroh** [comment]
My keyboard layout is "fr_ca", not "en".

**Comment by Yukinoroh** [comment]
On the IBUS panel I only have "日本語 - Anthy"

**Comment by fujiwarat** [comment]
> On the IBUS panel I only have "日本語 - Anthy"

You should configure two more engines to use the target feature.
In your case, probably it's good to add "French - French (Canada)" engine with ibus-setup -> "Input Method" tab.

Set "French - French (Canda)" on mate-terminal and "Anthy" on gnote or gedit.

**Comment by Yukinoroh** [comment]
So I added "FR" now, but hitting Ctrl+Space does not trigger the IME.
Do I need to first turn on the IME, and then turn on Japanese input? That would be two key strokes to change language!

**Comment by Yukinoroh** [comment]
I added "FR" now, but I can't turn on IBUS. It stays FR even if I select "日本語 - Anthy" from the IBUS icon.

**Comment by fujiwarat** [comment]
I added "FR" now, but I can't turn on IBUS. It stays FR even if I select "日本語 - Anthy" from the IBUS icon.

It's another issue. You mightn't configure your environment correctly.

You could run `env GTK_IM_MODULE=ibus gnote` or `env GTK_IM_MODULLE=ibus gedit` by manual for the workaround and switch IMEs again when you focus on the application.

**Comment by Yukinoroh** [comment]
I tried adding a keyboard shortcut to toggle between FR and 日本語 - Anthy, but it does nothing. It stays FR.

**Comment by Yukinoroh** [comment]
> You could run `env GTK_IM_MODULE=ibus gnote` or `env GTK_IM_MODULLE=ibus gedit` by manual for the workaround and switch IMEs again when you focus on the application.

It does not work either. Besides, FR is not an engine, it's a keyboard layout. It shouldn't matter which keyboard layout runs under an engine...

**Comment by Yukinoroh** [comment]
In Windows French AZERTY keyboard users are forced to QWERTY by the IME, in Linux fortunately it does not work like that.

**Comment by fujiwarat** [comment]
Follow my suggestion instead of updating unrelative topics.

**Comment by Yukinoroh** [comment]
> Follow my suggestion instead of updating unrelative topics.

I have followed your suggestion. "env GTK_IM_MODULLE=ibus gedit" does not work. I am stuck in FR and can't turn on IBUS.

**Comment by Yukinoroh** [comment]
btw I am under japanese locale (ja_JP.utf-8) with fr_ca keyboard.

**Comment by fujiwarat** [comment]
> I have followed your suggestion. "env GTK_IM_MODULLE=ibus gedit" does not work. I am stuck in FR and can't turn on IBUS, even if I select "日本語 - Anthy" from the tray icon, it goes back to FR right away.

And then I'd ask you to upload the screen cast here to check if you tried my suggestion expectedly.

Did you bring back the setting as I asked it for the test purpose? 
>> it provides IME level and you could check the global engine names with ibus engine when you enable the setup option and I think the disable mode works.

**Comment by Yukinoroh** [comment]
https://github.com/ibus/ibus/assets/5343988/db0d8138-c189-42a6-ae6a-22175d87fb0b

**Comment by Yukinoroh** [comment]
![2024-06-04 18-46-46](https://github.com/ibus/ibus/assets/5343988/64040b0a-c0d9-4c6f-b80a-0d1c7741e573)

**Comment by Yukinoroh** [comment]
Though I just tried to remove "FR" and add "EN" and I get the same problem, I can't get out of "EN" and can't turn on IBUS.

**Comment by fujiwarat** [comment]
You should describe you tried "env GTK_IM_MODULLE=ibus xed" exactly.
I'd suggest to install a GTK text application gedit or leafpad for the test while I never use xed.

**Comment by Yukinoroh** [comment]
Now with "EN" but I can't turn on Japanese input (Cltr+Space) at all, no matter if it shows EN or _A in the tray icon. Same issue as with "FR".

https://github.com/ibus/ibus/assets/5343988/dcdb4d84-28b1-4c11-920a-148f7c2df513

**Comment by Yukinoroh** [comment]
I see this error in terminal

(gedit:80644): dbind-WARNING **: 18:53:39.374: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: 許可がありません

**Comment by fujiwarat** [comment]
> Now with "EN" but I can't turn on Japanese input (Cltr+Space) at all,

Of course, it's an expected behavior because "EN" is xkb:us::eng engine but not anthy.

Now I confirmed switching IME works on gedit on your screencast and I also expect it works on mate-terminal too.
When you set "English - English (US)" on gedit or mate-terminal, `ibus engine` shows the xkb:us::eng
When you set "Japanese - Anthy", `ibus engine` shows anthy.

After you confirm the configuration, try to disable "share the same input method among..." check box in ibus-setup and the test again:

1. Set xkb:us::eng on mate-terminal and confirm IBus panel icon shows "EN"
2. Switch to gnote and set anthy on gnote and confirm IBus panel icno shows "あ" or "_A"
3. Switch back to mate-termianl and confirm IBus panel icon shows "EN"

**Comment by Yukinoroh** [comment]
> try to disable "share the same input method among...

It is disabled already. Let me re-take a video that shows that.

**Comment by fujiwarat** [comment]
> It is disabled already. Let me re-take a video that shows that.

I asked changed the setting. it's a bad configration by you again.

You should check the following test with the enabled option.
```
Now I confirmed switching IME works on gedit on your screencast and I also expect it works on mate-terminal too.
When you set "English - English (US)" on gedit or mate-terminal, ibus engine shows the xkb:us::eng
When you set "Japanese - Anthy", ibus engine shows anthy.
```

**Comment by Yukinoroh** [comment]
The problem is I can't get "あ" with this setting.

**Comment by fujiwarat** [comment]
> The problem is I can't get "あ" with this setting.

ibus-anthy menu provides the "Input Mode" pull down menu and you can choose "Hiragana", "Katakana", "Eisu" and when you choose "Hiragana", ibus-anthy shows "あ" on the panel menu.

**Comment by Yukinoroh** [comment]
The issue with this setting of adding a keyboard is there's no way I can turn Japanese input on.
Same problem, with share the same input method "on" or "off".


https://github.com/ibus/ibus/assets/5343988/897e41de-ff25-4000-b6cc-672a830addb4


https://github.com/ibus/ibus/assets/5343988/9d90e6b7-db08-47e9-a2b4-90a171e6b321

**Comment by Yukinoroh** [comment]
> ibus-anthy menu provides the "Input Mode" pull down menu and you can choose "Hiragana", "Katakana", "Eisu" and when you choose "Hiragana", ibus-anthy shows "あ" on the panel menu.

It is set to "eisuu", I have never changed it.

**Comment by Yukinoroh** [comment]
https://github.com/ibus/ibus/assets/5343988/a86ad0f7-c522-4f4c-a26b-92faf72b5471

**Comment by Yukinoroh** [comment]
I've had the same issue with my students last year. With "Japanese - Japan" keyboard installed by default in IBUS, there's no way to turn Japanese input on. You have to delete that keyboard and so then only it starts working.

**Comment by Yukinoroh** [comment]
In other words, the only way to get Japanese input is to only have "日本語 - Anthy" left.

**Comment by fujiwarat** [comment]
ibus-setup option ""Share the same input method among..." sets IME by window but your last screencast  set anthy only for all windows.

As I saied at first.
I think you mean the input modes of Hiragana or English per window in ibus-anthy.
Actually the main frame is already implemented in ibus core but I don't implement it in ibus-anthy yet.
It would be good to report your RFE to ibus-anthy.

FYI.
ibus-anthy default input mode is Eisu but you can customize it in anthy setup dialog instead of ibus-setup and the default shortcut key is Ctrl-j to switch Eisu and Hiragana but also you can customize it.

**Comment by Yukinoroh** [comment]
> Actually the main frame is already implemented in ibus core but I don't implement it in ibus-anthy yet.

If it's not implemented yet, perhaps it should be grayed out.

**Comment by fujiwarat** [comment]
> If it's not implemented yet, perhaps it should be grayed out.

Disagreed. Anyway it's not an ibus core issue.

**Comment by Yukinoroh** [comment]
> I think you mean the input modes of Hiragana or English per window in ibus-anthy.

You probably mean Japanese input ON or OFF. As I mentioned, in Linux you can't assume that the underlying keyboard layout is English.

**Comment by fujiwarat** [comment]
I don't mean it.

**Comment by Yukinoroh** [comment]
> I don't mean it.

Then this is totally confusing. Not everyone uses an English keyboard layout outside of Japan.

**Comment by fujiwarat** [comment]
You still don't understand my meaning but your issue isn't an ibus core.

**Comment by Yukinoroh** [comment]
> You still don't understand my meaning but your issue isn't an ibus core.

I'm more thinking about the other users that will also notice it's not working and that will end up here... Until ibus-anthy follows ibus, I do think there should be some kind of indication, or warning, that the setting is engine-dependant.
