### ISSUE TITLE
Ibus cannot not change keyboard layout on Wayland

### ISSUE THREAD

**Issue by glottophilos-jon** [ibus/ibus#2644]
### Which distribution and version?: 
Manjaro Arch kernel 6.9.0-1-MANJARO

### Which desktop environment and version: 
KDE Plasma 6.0.4

### Which session type: 
Wayland

### Which application and version: 
--

### IBus version: 
1.5.30-1

## Issue description:
Ibus will not input anything other than English Latin characters, no accents, no other alphabets, nothing but the English character set, regardless of selected keyboard layout. Additionally, starting ibus creates a notification error 

> IBus should be called from the desktop session in Wayland. For KDE, you can launch 'systemsettings5' utility and go to "Input Devices" -> "Virtual Keyboard" section and select "IBus Wayland" icon and click "Apply" button to configure IBus in Wayland. For other desktop sessions, you can copy the 'Exec=' line in org.freedesktop.IBus.Panel.Wayland.Gtk3.desktop file to a configuration file of the session. Please refer each document about the "Wayland input method" configuration. Before you configure the "Wayland input method", you should make sure that QT_IM_MODULE and GTK_IM_MODULE environment variables are unset in the desktop session. 

Following these instructions does not solve the problem, it persists regardless.

## Steps to reproduce:
1. Switch to alternate keyboard via ibus (e.g., Russian)
2. Attempt to type in new alphabet

### Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

### Do you see any errors when you run ibus-daemon with the verbose option?:

Yes,  

```
(ibus-ui-gtk3:8691): IBUS-WARNING **: 10:09:29.784: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:8691): GLib-CRITICAL **: 10:09:52.244: Source ID 38 was not found when attempting to remove it
```

### Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes, this seems to be a global issue.

**Comment by glottophilos-jon** [comment]
Thank you for looking into this! Unfortunately, as I stated, taking the steps listed in the notification does not solve the problem. I have already tried unsetting both environment variables and enabling ibus via the systemsettings utility, but the problem persists.

**Comment by Dwarsen** [comment]
I have a similar problem, and a similar setup also using KDE6 on Manjaro with Wayland.

Environment variables are not set, and I've configured ibus under virtual keyboard as instructed.  The warning with the instructions did go away as well.

I can change keyboard layout between Swedish and Japanese (anthy) using the panel for ibus, but the keyboard combination super+space doesn't work properly.

It should be noted that in some applications, such as Konsole, it does KIND OF work, but it doesn't seem to take until I click the window again, whereas in most applications (Slack, Vivaldi, etc) the combination will do nothing.

**Comment by fujiwarat** [comment]
I'm not sure about your issue but I found ibus-ui-gtk3 has a memory issue and fixed it.
Are you able to test the linked patch?

**Comment by glottophilos-jon** [comment]
I'd be happy to! How would I go about testing it and what am I looking for?

**Comment by fujiwarat** [comment]
1. Get the build env of Manjaro and the IBus source package
2. Apply the above linked patch
3. Build IBus and test it

**Comment by rajeeshknambiar** [comment]
I have very similar problems with ibus-1.5.30 on Fedora 40, KDE Plasma 6.0.5 (I think the issue started after recent update of ibus package in F40). No IM_MODULE env vars set.

I'm unable to switch input methods using `Super+Space`, but manually switching using the system tray icon works (but it is fiddly).

Journalctl shows similar logs:
```
ibus-ui-gtk3[1591]: Source ID 13984 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13917 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13892 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13876 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13840 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13804 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Create input context failed: Operation was cancelled.
ibus-ui-gtk3[1591]: Source ID 13765 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13699 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Source ID 13661 was not found when attempting to remove it
ibus-ui-gtk3[1591]: Create input context failed: Operation was cancelled.
...
```
Anything further I can try to troubleshoot?

**Comment by fujiwarat** [comment]
@rajeeshknambiar I think the log is not relative with your issue.
If you use Fedora, ibus-1.5.30-3.fc40  is available.

**Comment by rajeeshknambiar** [comment]
I have tested ibus-1.5.30-3.fc40 and it does have the same issue (unable to switch input methods using super+space). Do you recommend opening a bug report in Fedora?

**Comment by fujiwarat** [comment]
@rajeeshknambiar 

> I have tested ibus-1.5.30-3.fc40 and it does have the same issue (unable to switch input methods using super+space).

How about rebooting the system?

> Do you recommend opening a bug report in Fedora?

Maybe. I'm not sure if your issue is Fedora specific at the moment.

Do you still see the IBus notification dialog of `IBus should be called from the desktop session in Wayland. For KDE, you can launch 'systemsettings5' utility and go to "Input Devices" -> ...` when you log into the Plasma Wayland desktop session?

**Comment by rajeeshknambiar** [comment]
> How about rebooting the system?

Issue persists.

> Do you still see the IBus notification dialog of `IBus should be called from the desktop session in Wayland. For KDE, you can launch 'systemsettings5' utility and go to "Input Devices" -> ...` when you log into the Plasma Wayland desktop session?

No, I don't see this message when logging into Plasma Wayland.

**Comment by fujiwarat** [comment]
> No, I don't see this message when logging into Plasma Wayland.

Then your issue is not this.

> I have tested ibus-1.5.30-3.fc40 and it does have the same issue (unable to switch input methods using super+space). 

Which do you mean Super-space does not show the IBus IME switcher popup window? Or you can switch IMEs but cannot enable the selected input method?

It would be good to check some configurations.
1. Check if the parent process of ibus-ui-gtk3 is kwin_wayland with `ps` or `pstree` command
2. Check if enviroment variables are not set with `env | grep ibus` command
3. Check if Gsettings values are not set with `gsettings get org.gnome.desktop.interface gtk-im-module` command

**Comment by rajeeshknambiar** [comment]
> Which do you mean Super-space does not show the IBus IME switcher popup window? Or you can switch IMEs but cannot enable the selected input method?

Pressing Super+Space does not switch input method. It does not show IME switcher popup window either.

>     1. Check if the parent process of ibus-ui-gtk3 is kwin_wayland with `ps` or `pstree` command
```
 |-kwin_wayland_wr-+-kwin_wayland-+-Xwayland---4*[{Xwayland}]
 |                 |              |-ibus-ui-gtk3-+-ibus-daemon-+-ibus-dconf---4*[{ibus-dconf}]
 |                 |              |              |             |-ibus-engine-m17---3*[{ibus-engine-m17}]
 |                 |              |              |             |-ibus-engine-sim---3*[{ibus-engine-sim}]
 |                 |              |              |             |-ibus-extension----4*[{ibus-extension-}]
 |                 |              |              |             `-3*[{ibus-daemon}]
 |                 |              |              `-7*[{ibus-ui-gtk3}]
```
>
>     2. Check if enviroment variables are not set with `env | grep ibus` command
Empty, as mentioned earlier.
> 
>     3. Check if Gsettings values are not set with `gsettings get org.gnome.desktop.interface gtk-im-module` command
`''` (empty)

**Comment by rajeeshknambiar** [comment]
I have done the same as instructed, here is a video recording of the same.
Please note, `ibus-1.5.30-1.fc40` works fine.
[input-method-switching-kwrite.webm](https://github.com/ibus/ibus/assets/424259/a7b6f54c-4f79-4ec3-8b89-ffc57e91c352)

**Comment by fujiwarat** [comment]
@rajeeshknambiar 

> Please note, ibus-1.5.30-1.fc40 works fine.

OK, I understand your issue is a regression after I fix this issue. I think " s" is output when you type Super-space.
It would be good to file a bug to Fedora.

**Comment by rajeeshknambiar** [comment]
Thanks, created https://bugzilla.redhat.com/show_bug.cgi?id=2290842

**Comment by fujiwarat** [comment]
I didn't receive any reports during the Fedora testing with this patch.
Let's close the issue.
