### ISSUE TITLE
Toggle Status of ibus Input Method Programmatically

### ISSUE THREAD

**Issue by neur1n** [ibus/ibus#2650]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
(E.g. Fedora 27. Check /etc/fedora-release)
Ubuntu 22.04

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)
GNOME (I'm not sure about the detailed version number since I don't have access to a desktop currently.)

Which session type?: 
(X11 or Wayland. Check $XDG_SESSION_TYPE)
X11

Which application and version?: 
(E.g. gedit 3.24, leafpad, kate, xterm)
Anything

IBus version?: 
(Run `ibus version`)
1.5.26

Issue description:
I'm trying to toggle the status of an ibus input method using another program. For example, I'm using `sunpinyin` in Vim, and I want to toggle Chinese mode and English mode with another program written in C/C++. My issue is that I don't know which APIs I should use. I went through the documentations and some source code in this repository, it seems that I should work with `IBusEngine` and `IBusEngineClass`, but how to get access to the existing ibus instance (if there is any) and get/set the status of the engine?

Steps to reproduce:
n/a

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
no

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
n/a

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
no

**Comment by mike-fabian** [comment]
Which ibus input method are you  using?
The input method you are using may have a gsettings key which you could set to change behaviour of the input method.

ibus-typing-booster for example has a key `inputmode` which  can be set to `True` (which means it is switched on) or `False` which means it is switched off and all keys are passed through unchanged. 

The input method you  are using might have that as well.

**Comment by neur1n** [comment]
I'm using ibus-libpinyin (schema name `com.github.libpinyin.ibus-libpinyin.libpinyin`). It seems that there is no such gsettings key in this schema.

So is such toggling all done by the gsetting "frontend" (I'm not sure about this term) instead of libibus?

**Comment by fujiwarat** [comment]
I don't think the status should be exported from each ibus engine.

**Comment by fujiwarat** [comment]
I have no plan to provide any APIs in ibus core as I think the status should not be  exported commonly.
Some IBus engines might like to export it but generally I think it's not a good idea.

**Comment by neur1n** [comment]
Thanks for your clarification. :)
