### ISSUE TITLE
Can't Type '<' on X apps under Kubuntu/Wayland

### ISSUE THREAD

**Issue by xavier2910** [ibus/ibus#2651]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Kubuntu 24.04

Which desktop environment and version?: 
Plasma 5.27.11, KDE Framework 5.115.0, Qt 5.15.13

Which session type?: 
Wayland

Which application and version?: 
Neovide 0.12.2, goneovim v0.6.8
N.B. these are both X-native apps being run thru whatever compatibility layer there is. (XWayland or something?)

IBus version?: 
1.5.29-2 (from the Ubuntu repositories).

Issue description:
* Cannot type '<'. Other keys and sequences seem to be working fine. N.B. this is only observed in the apps above. I can type '<' normally in Konsole, Chrome, etc.
* Key repeats don't work for letter keys. (duplicate of #2610 ?)

Steps to reproduce:
1. Install IBus from Ubuntu repositories.
2. Add `unset QT_IM_MODULE`  and `unset GTK_IM_MODULE` to your `~/.profile`.
3. Log out and back in to Plasma under Wayland.
4. Go to settings and set Virtual Keyboard to IBus (you can search or it's under 'Input Devices').
5. Log out and in again.
6. Open neovide and type i, then try to type '<'.
7. similarly for goneovim.

Steps to *not* reproduce:
1. Having done steps 1-5 above:
2. Open Konsole and try to type '<' into the search bar.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)
No I cannot. (Though it was a little tricky to run the second command having run the first! : )

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
it spat this out:
```
(ibus-ui-gtk3:7795): IBUS-WARNING **: 16:49:04.417: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:27.764: Source ID 36 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:28.726: Source ID 64 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:33.254: Source ID 102 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:47.322: Source ID 157 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:50.854: Source ID 171 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:54.801: Source ID 211 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:49:55.709: Source ID 246 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:50:30.473: Source ID 281 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:50:32.685: Source ID 427 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:50:40.554: Source ID 464 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:50:43.880: Source ID 507 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:50:45.837: Source ID 542 was not found when attempting to remove it

(ibus-ui-gtk3:7795): GLib-CRITICAL **: 16:50:54.273: Source ID 578 was not found when attempting to remove it

```
The GLib stuff I think was later.

Can you reproduce your problem with a new user account instead of your current account? (yes / no): 

Yes, the bug is reproducible on fresh account. Restarting IBus as instructed removes the problem (Incidentally, I could type normally before restarting IBus this time). With --verbose I get only the first warning from above:
```
(ibus-ui-gtk3:7795): IBUS-WARNING **: 16:49:04.417: ibus_bus_call_sync: org.freedesktop.DBus.Properties.Get: GDBus.Error:org.freedesktop.DBus.Error.Failed: No global engine.
```

**Comment by xavier2910** [comment]
N.B. selecting a different Virtual Keyboard also resolves the issue, without log out-log in.

**Comment by jhayar0719** [comment]
how did you fix?

**Comment by fujiwarat** [comment]
I cannot reproduce your issue with kwrite.
The package of neither Neovide or goneovim is available in Fedora.
I tried to install Neovide from snap but failed to launch it.

```
% /snap/bin/neovide 
[wayland-client error] Attempted to dispatch unknown opcode 0 for wl_shm, aborting.
```

Probably I have to build the source codes while the original issue was caused in Ubuntu.

**Comment by xavier2910** [comment]
@jhayar0719, I used the system settings to select a virtual keyboard that was not ibus. So I guess I did not really fix it.

**Comment by fujiwarat** [comment]
Finally I could install neovide using rust in Fedora and reproduce your issue with neovide.
I also reproduce the same issue with neovim-qt in Fedora, which is pakaged in Fedora.
I think neovide and neovim-qt have the same logic but I can debug neovim-qt in Fedora more easily.

`nvim-qt` comand from `neovim-qt` package runs `nvim` command internally from `neovim` package. `nvim-qt` communicates with `nvim`.

```
# ps -ef | grep nvim
fujiwara   12523    2226  0 09:02 ?        00:00:00 nvim-qt --nofork
fujiwara  12533   12523  0 09:02 ?        00:00:00 /usr/bin/nvim --embed --cmd set termguicolors
```
IBus push `<' with VIM commits instead of returning the key events for this test case because IBus manages the keyboard layouts in Wayland but NVIM applications does not handle "nvm_input" API correctly.

NVIM handles special key events enclosed with `<' and '>' so NVIM applications should not send the raw '<' data directly but "<lt>" instead.

After I modify the neovim-qt codes, I confirmed this issue can be fixed.
```
--- neovim-qt-0.2.18/src/auto/neovimapi0.cpp.orig	2024-10-16 08:42:44.793593969 +0900
+++ neovim-qt-0.2.18/src/auto/neovimapi0.cpp	2024-10-16 08:46:24.758058229 +0900
@@ -390,7 +390,11 @@ MsgpackRequest* NeovimApi0::vim_input(QB
 	r->setFunction(NeovimApi0::NEOVIM_FN_VIM_INPUT);
 	connect(r, &MsgpackRequest::finished, this, &NeovimApi0::handleResponse);
 	connect(r, &MsgpackRequest::error, this, &NeovimApi0::handleResponseError);
-	m_c->m_dev->send(keys);
+	QByteArray lt("<lt>");
+	if (keys == "<")
+		m_c->m_dev->send(lt);
+	else
+		m_c->m_dev->send(keys);
 	return r;
 }
 MsgpackRequest* NeovimApi0::vim_replace_termcodes(QByteArray str, bool from_part, bool do_lt, bool special)
```

Then I think the root cause of this issue is in the NVIM applications but not IBus.
