### ISSUE TITLE
 GTK set my keyboard layout always to US after new start

### ISSUE THREAD

**Issue by aotto1968** [ibus/ibus#2652]
Hi,

my problem is that **xface** (gnome,ibus) alway set my keyboard to US and I don't know how to fix it permanent.
temporary fix with "`xsetkbmap de`" works but not as default.
I changed the `/usr/bin/xsetkbmap` to a script just to figure out who done this:

```
aotto     2847     1  1 21:02 ?        00:00:00 ibus-daemon --xim -d
aotto     2900  2847  0 21:02 ?        00:00:00  \_ /usr/lib64/ibus/ibus-dconf
aotto     2903  2847  6 21:02 ?        00:00:00  \_ /usr/lib64/ibus/ibus-ui-gtk3
aotto     2988  2903  0 21:02 ?        00:00:00  |   \_ /bin/bash /usr/bin/setxkbmap -layout us -option -option terminate:ctrl_alt_bksp
aotto     2996  2988  0 21:02 ?        00:00:00  |       \_ ps -ef --forest
aotto     2904  2847 10 21:02 ?        00:00:00  \_ /usr/lib64/ibus/ibus-extension-gtk3
aotto     2973  2847  0 21:02 ?        00:00:00  \_ /usr/lib64/ibus/ibus-engine-simple
```

as you see it is **ibus** internal tool who do the change.

question → how to change this?

environment: opensuse VERSION = 15.5 in Virtualbox
 Linux linux02 5.14.21-150500.55.65-default #1 SMP PREEMPT_DYNAMIC Thu May 23 04:57:11 UTC 2024 (a46829d) x86_64 x86_64 x86_64 GNU/Linux

**Comment by fujiwarat** [comment]
> my problem is that xface (gnome,ibus) alway set my keyboard to US and I don't know how to fix it permanent.

Do you mean you use XFCE and GNOME desktop sessions?

> question → how to change this?

You should make sure to configure your XKB kemaps with ibus-setup utility at first for XFCE. IBus starts the XKB keymap which you used the last previously.
You could check the last value with `gsettings get org.freedesktop.ibus.general engines-order`.

You should check `gnome-control-center keyboard` for GNOME.

**Comment by aotto1968** [comment]
> gsettings get org.freedesktop.ibus.general engines-order
@as []

> gnome-control-center was *not* installed → done
> keyboard→"Input Sources" was empty, add "German"
> logout/in but the US still be there. 
> In addition I figure out that the session start as DE (german→keyboard flag symbol on the panel) but very late switch zu US.

![image](https://github.com/ibus/ibus/assets/27886664/a8da1048-28a8-4519-b2a0-d703c02acf1b)
