### ISSUE TITLE
ibus not work error on Hyperland Wayland

### ISSUE THREAD

**Issue by langbach364** [ibus/ibus#2653]
OS: Arch
DE: Hyprland ver: 0.40.0-1
detail: ibus is working but probably only works with applications ported to X11 however with firefox it works normally with X11 or hyprland

These are the variables used in my hyprland configuration
https://wiki.hyprland.org/Configuring/Environment-variables/

#environment-variables
env = CLUTTER_BACKEND,wayland
env = GDK_BACKEND,wayland,x11
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprlandn
env = XDG_SESSION_TYPE,wayland

# firefox
env = MOZ_ENABLE_WAYLAND,1

i not sure if deleting the variable env=ELECTRON_OZONE_PLATFORM_HINT,auto will cause applications to switch to X11, but if deleted, the ibus keyboard will still work normally.

# electron >28 apps 
 env = ELECTRON_OZONE_PLATFORM_HINT,auto

I added the environment variables GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus
DefaultIMModule=ibus 
Go to etc/environment

to make sure the environment variables are added to wayland and get the results in the picture
![image](https://github.com/ibus/ibus/assets/96160493/df0d84b9-8944-4fbe-8bc1-ae442aed9501)

**Comment by fujiwarat** [comment]
I tried https://github.com/electron/electron-api-demos in Plasma Wayland and it works fine with ibus.

I downloaded electron-v32.0.0-beta.4-darwin-x64.zip from https://github.com/electron/electron/releases and extract it in electron directory.
I checkout electron-api-demos  with git and run `npm install` and run `../electron/electron .` In Plasma Wayland.

I assume your issue is to support Hyprland.

**Comment by vuongtuha** [comment]
try not to add env system wide. Add them to hyprland.conf in your dot

**Comment by langbach364** [comment]
@vuongtuha I added hyprland.conf bro but it doesn't seem to work however I use fxcit5 instead and it works for some applications I add the --enable-wayland-ime flag to .desktop to create text-input- v1, although it's a bit buggy, it's still okay to use @@

**Comment by juhp** [comment]
The hyprland compositor is packaged in Fedora btw
