### ISSUE TITLE
iBus Panel/Untranslated string in English appearing when hovering the iBus icon

### ISSUE THREAD

**Issue by xbesnard** [ibus/ibus#2655]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Kubuntu development version 24.10 (oracular)

Which desktop environment and version?: 
(E.g. GNOME 3.24. Check $XDG_CURRENT_DESKTOP and your ISO image.)

Which session type?: 
X11 

Which application and version?: 
Linux/KDE Plasma: plasmashell -v: plasmashell 5.27.11

IBus version?: 
ibus version
IBus 1.5.29-rc2

Issue description:
Hi.
I am running currently Kubuntu development version 24.10 (oracular) but what I reported was already present in previous Kubuntu & KDE Plasma version. I am also a French translator for KDE Plasma.
In my systray, I added the widget related to the keyboard configuration. So, a "FR" is correctly displayed in the bottom dashboard.
When hovering with the mouse pointer, the following pieces of text are displayed:
* Panneau iBUS ==> Correct/French translated sentence, 
* You can tooggle the activate menu and context one with clicking the mouse middle button on the panel icon. ==> Incorrect as in English

When performing a grep in all po files, this string is missing from the KDE po files. So, I suppose this string is not  taken into account for translation.

Please, could you check that situation and fix it, if it is really a bug.
Many thanks. I remain available for any further information.
Regards. Xavier
Note: bug reported to KDE Plasma : https://bugs.kde.org/show_bug.cgi?id=488408 and with a request to report it to https://github.com/ibus/ibus/issues

Steps to reproduce:
1. Hovering the iBUS widget in the dahsboard 

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Systematic, including on previous versions of Kubuntu

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
No error reported

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes
![BugIBUS](https://github.com/ibus/ibus/assets/35624286/6a184212-6a09-42c1-9ae2-aa0f330a36f5)

**Comment by fujiwarat** [comment]
> When performing a grep in all po files, this string is missing from the KDE po files. So, I suppose this string is not taken into account for translation.

When you use the  Japanese desktop session, the string is translated.
https://github.com/ibus/ibus/blob/main/po/ja.po#L3576
