### ISSUE TITLE
“Use system keyboard layout” for e.g. Anthy doesn’t work under KDE Wayland

### ISSUE THREAD

**Issue by ariasuni** [ibus/ibus#2661]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch Linux

Which desktop environment and version?: 
KDE Plasma 6.1.2

Which session type?: 
Wayland

Which application and version?: 
Anything

IBus version?: 
IBus 1.5.30

Issue description:
When typing text with IBus (selected as a virtual keyboard in Plasma’s System Settings), the current system keyboard layout isn’t used by e.g. Anthy, it uses the previously used one in IBus, which is inconvenient to use. For example, if I select my secondary keyboard layout by mistake, then I need to switch back to my main one then switch to Anthy instead of switching directly to Anthy.

So my use case is that I want to be able to use Anthy with my usual/main keyboard layout which isn’t listed in Anthy’s Preferences. Also it’s a very confusing experience to have two ways of switching keyboard layouts, not sure if some synchronization between e.g. Plasma and IBus is possible on that front (to signal that the keyboard layout is being “overwritten” by IBus).

Steps to reproduce:
1. Use KDE Plasma under Wayland and configure several keyboard layouts
1. Set IBus as virtual keyboard in System Settings
1. Enable “Use system keyboard layout” in ibus-setup
1. Switch between keyboard layout with Plasma shortcuts/widget

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
Not tried (not sure how to do that on KDE Wayland)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Not tried

**Comment by fujiwarat** [comment]
I think ibus-anthy's default is no keymap and whether you enable “Use system keyboard layout” or not, IBus should keep the session keymap.

I hope your issue was resolved by https://github.com/ibus/ibus/commit/f190da19b53c267ca1c9730e18f1b53c089c0247
The problem was `setxkbmap` command cannot get the session layout in Wayland and I replaced `setxkbamp` with localectl` to get the session layout.
