### ISSUE TITLE
Changing input method with keyboard shortcut doesn't work when not focused on textbox

### ISSUE THREAD

**Issue by tinnamchoi** [ibus/ibus#2666]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Arch

Which desktop environment and version?: 
dwm-6.3

Which session type?: 
X11

Which application and version?: 
All apps that I've tested, inc. `st 0.8.5`, `Google Chrome 126.0.6478.126`

IBus version?: 
IBus 1.5.30

Issue description:
Changing input method with keyboard shortcut when not focused on textbox

Steps to reproduce:
1. Open `st`
2. Change input method with keyboard shortcut (alt + space for me)
3. Type

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
yes

See attached video. The input change graphic shows up so ibus is clearly able to detect the keypress, but the input method doesn't change. In the example typing, I am pressing the key directly to the right of the left shift key, which is a 'z' in the English keyboard and a 'y' in the German one.

https://github.com/user-attachments/assets/25bd28d4-3254-4f72-973c-2fe0a993fa7d

**Comment by fujiwarat** [comment]
I confirmed st and chrome works fine with ibus in Fedora 40.
dwm-6.5-1.fc40.x86_64
dmenu-5.2-5.fc40.x86_64
st-0.9-4.fc40.x86_64
google-chrome-unstable-129.0.6614.3-1.x86_64

st uses XIM and google-chrome uses GTK3.
You can confirm which IM module is used by each app with `env | grep ibus` and `ibus im-module --type gtk3` commands.

**Comment by tinnamchoi** [comment]
@fujiwarat Well as you can see from the video it doesn't work on my machine, what's the solution then?

**Comment by fujiwarat** [comment]
> @fujiwarat Well as you can see from the video it doesn't work on my machine, what's the solution then?

I already replied the solution:

>> st uses XIM and google-chrome uses GTK3.
>> You can confirm which IM module is used by each app with `env | grep ibus` and `ibus im-module --type gtk3` commands.

**Comment by hungnkb** [comment]
![image](https://github.com/user-attachments/assets/a60c4c09-6e0f-4fea-a565-5791c42e2c71)
I have same issue about any keypair shortcuts to change input , my env = ibus. How could i fix this?
