### ISSUE TITLE
Handle ISO Level3/Level5 Modifier Keys for Neo2

### ISSUE THREAD

**Issue by Janfel** [ibus/ibus#2667]
Which distribution and version?: Manjaro 24.0.3

Which desktop environment and version?: Plasma 6.0

Which session type?: X11

Which application and version?: All applications

IBus version?: ibus 1.5.30

Issue description:

I am using the keyboard layout `de neo2`. Compose sequences are interrupted when pressing `IBUS_KEY_ISO_Level3_Lock`, `IBUS_KEY_ISO_Level5_Shift`, `IBUS_KEY_ISO_Level5_Lock`. These keys are used to access higher levels of the keyboard layout, just like the standard Shift key. They should not be bindable as accelerators or be interpreted as part of a compose sequence.

Steps to reproduce:
1. Set your keyboard layout to “German (Neo2)“.
1. Input a partial compose sequence.
1. Press Right_Alt (sends `IBUS_KEY_ISO_Level5_{Shift,Lock}`)
1. The compose sequence is cancelled.

I have been using the patch below for a while now. It fixes both problems by adding the keys in question to the respective exclusion lists.

``` diff
diff '--color=auto' -ur ibus.orig/src/ibusaccelgroup.c ibus.new/src/ibusaccelgroup.c
--- ibus.orig/src/ibusaccelgroup.c	2021-11-10 11:08:45.223754171 +0100
+++ ibus.new/src/ibusaccelgroup.c	2021-11-10 11:18:09.584690550 +0100
@@ -68,6 +68,7 @@
         IBUS_KEY_Control_R, IBUS_KEY_Meta_L, IBUS_KEY_Meta_R,
         IBUS_KEY_Alt_L, IBUS_KEY_Alt_R, IBUS_KEY_Super_L, IBUS_KEY_Super_R,
         IBUS_KEY_Hyper_L, IBUS_KEY_Hyper_R, IBUS_KEY_ISO_Level3_Shift,
+        IBUS_KEY_ISO_Level3_Lock, IBUS_KEY_ISO_Level5_Shift, IBUS_KEY_ISO_Level5_Lock,
         IBUS_KEY_ISO_Next_Group, IBUS_KEY_ISO_Prev_Group,
         IBUS_KEY_ISO_First_Group, IBUS_KEY_ISO_Last_Group,
         IBUS_KEY_Mode_switch, IBUS_KEY_Num_Lock, IBUS_KEY_Multi_key,
diff '--color=auto' -ur ibus.orig/src/ibusenginesimple.h ibus.new/src/ibusenginesimple.h
--- ibus.orig/src/ibusenginesimple.h	2021-11-10 11:08:45.227087267 +0100
+++ ibus.new/src/ibusenginesimple.h	2021-11-10 11:19:33.699887058 +0100
@@ -111,7 +111,10 @@
     IBUS_KEY_Hyper_L,
     IBUS_KEY_Hyper_R,
     IBUS_KEY_Mode_switch,
-    IBUS_KEY_ISO_Level3_Shift
+    IBUS_KEY_ISO_Level3_Shift,
+    IBUS_KEY_ISO_Level3_Lock,
+    IBUS_KEY_ISO_Level5_Shift,
+    IBUS_KEY_ISO_Level5_Lock
 };
 
 GType   ibus_engine_simple_get_type       (void);
```

**Comment by fujiwarat** [comment]
Thank you for the patch.
