### ISSUE TITLE
Spurious `sync()` in IMdkit produces multi-second delays in typing

### ISSUE THREAD

**Issue by tomsmeding** [ibus/ibus#2668]
Lifting this to a separate issue from my comment [here](https://github.com/ibus/ibus/pull/2591#issuecomment-2161654893).

session type: X11
IBus version: 1.5.30
Reproduces after restarting IBus, no messages in `--verbose` mode.

Issue description:
The `sync()` call introduced in #2591 locks up keyboard input for arbitrary delays, often up to seconds, if the system has a hard disk (HDD) mounted and this HDD is being written to. This holds both for internal disks and for external (e.g. USB) disks.

This is because `sync()` (`man 2 sync`) flushes disk caches of all disks mounted on the system, which defeats the buffering that the Linux kernel normally does, lowering throughput to all disks in the system and also producing more wear, especially on HDDs. This all in addition to the random, _long_ typing delays observed while the HDD is being used. (This all is applicable to SSDs as well as HDDs, but because HDDs have non-negligible seek and write times, the issue is much more easily observed there.)

Furthermore, I'm quite convinced that IBus has no need to do anything this drastic -- from the PR description in #2591, a small `nanosleep()` would have produced the same effect. :)

Steps to reproduce:
1. Make sure ibus is running.
1. Make sure your system has a hard disk attached (or some other slow medium or file system), and `cd` to it.
1. Run the following `bash` code: `while true; do echo a >>afile; sleep 1; done`. This will write two bytes (`a` and a newline) to the file `afile` in the current directory every second.
1. Type continuously in another window.

When I do this, I observe delays of up to 2 seconds sometimes during typing, even with this extremely simplistic "disk using program". When downloading torrents, these delays can go up to 10 seconds.

Reproduction video: https://github.com/user-attachments/assets/db6dfc46-8079-4a20-9981-3250d8da1ea2
- Command in middle-left window is `sudo strace -p "$(pgrep ibus-x11)" -e 'trace=sync' 2>&1 | while true; do read -r line; echo "$(date) $line"; done`; this prints a time stamp for every `sync()` system call performed by `ibus-x11`.
- Command in top-left window is `while true; do echo a >>afile; sleep 1; done` on a slow external USB HDD.

**Comment by fujiwarat** [comment]
I cannot reproduce your issue.

>> Furthermore, I'm quite convinced that IBus has no need to do anything this drastic -- from the PR description in https://github.com/ibus/ibus/pull/2591, a small nanosleep() would have produced the same effect. :)

This is a sync for multiple threads and I don't think nanosleep() can fix the segv.

**Comment by tomsmeding** [comment]
Thank you for looking into this!

I'm also not sure what the original issue was that this `sync()` was supposed to fix, so I may very well be wrong with my suggestion of `nanosleep()`. Sorry about that.

However, this part I don't understand:
> This is a sync for multiple threads

`sync()` does not synchronise threads. It is a Linux system call (see `$ man 2 sync`) that flushes kernel buffers for physical disk drives; it just has an unintuitive name. Is this what you intended?

> I cannot reproduce your issue.

Hm, do you get any calls to `sync()` at all on your system? Perhaps the conditions under which `sync()` get called are dependent on the system, somehow.

**Comment by juhp** [comment]
It is easy to reproduce: using autorepeat I can see over 30 sync() calls per second!

**Comment by fujiwarat** [comment]
> Using auto-repeat for direct input in xterm, I see about 33 sync() calls per second!

That's an expected result and you don't have to comment it.

**Comment by fujiwarat** [comment]
> sync() does not synchronise threads. It is a Linux system call (see $ man 2 sync) that flushes kernel buffers for physical disk drives; it just has an unintuitive name. Is this what you intended?

As I commented, sync() was needed to avoid the SEGV to make sure the  order of the multi threads.

**Comment by fujiwarat** [comment]
From the evaluation of #2673, seems I have fixed the original issue in the libX11 1.8.10 and I could delete sync() safely.
