### ISSUE TITLE
[question] how to avoid `Service name 'org.freedesktop.IBus' is owned by IBus.`

### ISSUE THREAD

**Issue by Freed-Wu** [ibus/ibus#2669]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
NixOS unstable

Which desktop environment and version?: 
Gnome 46.3.1

Which session type?: 
Wayland

Which application and version?: 
no

IBus version?: 
1.5.30

Issue description:

After set `DBUS_SESSION_BUS_ADDRESS`

```sh
export DBUS_SESSION_BUS_ADDRESS=unix:path=/home/wzy/.cache/ibus/dbus-6CmFxHNk,guid=cebb828e8d4c654da89633ad669e6cb3
```

I can run dbus-send for ibus:

```sh
dbus-send --print-reply --dest=org.freedesktop.IBus /org/freedesktop/IBus org.freedesktop.DBus.Introspectable.Introspect
```

However, I cannot in lua

```lua
p = require'dbus_proxy'
proxy = p.Proxy:new(
  {
    bus = p.Bus.SESSION,
    name = "org.freedesktop.IBus",
    interface = "org.freedesktop.IBus",
    path = "/org/freedesktop/IBus"
  }
)
```

Because:

```
Error calling StartServiceByName for org.freedesktop.IBus: Service name 'org.freedesktop.IBus' is owned by IBus.

Stack trace:
        #0 [C]: in function ?
        #1 [C]: in function 'error'
        #2 /home/wzy/.local/share/lua/5.1/dbus_proxy/_proxy.lua:584: in function 'new'
        #3 lua:1: in the main chunk
```

How to avoid this error?

Refer https://www.rocksaying.tw/archives/18844532.html

**Comment by fujiwarat** [comment]
My understanding is lua's 'dbus_proxy' is binded to `GDBusProxy` and I think you need to set `G_DBUS_PROXY_FLAGS_DO_NOT_AUTO_START` to the flags in `p.Proxy:new`

I can show the exmple for Python binding:

```
#! /usr/bin/python3
gi.require_version('Gio', '2.0')
from gi.repository import Gio

proxy = Gio.DBusProxy.new_for_bus_sync(Gio.BusType.SESSION,
                                       Gio.DBusProxyFlags.DO_NOT_AUTO_START,
                                       None,
                                       "org.freedesktop.IBus",
                                       "/org/freedesktop/IBus",
                                       "org.freedesktop.IBus",
                                       None)

variant = proxy.call_sync("org.freedesktop.DBus.Introspectable.Introspect",
                          None,
                          Gio.DBusCallFlags.NONE,
                          -1,
                          None)
print(variant)

```

**Comment by Freed-Wu** [comment]
Is it any DBusConnectionFlags for ibus new_for_address_sync?

**Comment by Freed-Wu** [comment]
https://github.com/ibus/ibus/blob/main/src/ibusbus.c#L532-533

**Comment by fujiwarat** [comment]
> Is any DBusConnectionFlags for ibus new_for_address_sync?

You don't have to use it. As I noted, `Gio.DBusProxy.new_for_bus_sync()` should work.

> https://github.com/ibus/ibus/blob/main/src/ibusbus.c#L532-533

Bad link. your usage is not `IBusBus` but `GDBusProxy`.
