### ISSUE TITLE
[question] How to dynamically change the input method icon?

### ISSUE THREAD

**Issue by yookoala** [ibus/ibus#2670]
Which distribution and version?: 
Fedora 40

Which desktop environment and version?: 
GNOME 46

Which session type?: 
Wayland

Which application and version?: 
-

IBus version?: 
1.5.30

Issue description:
I am maintaining a custom iBus engine implementation written with Python. I've implemented a new mode switch for it. And I'd want to dynamically change the top right corner symbol when the mode is changed.

I see this is implemented in ibus-tables-cangjie (ibus-tables). In Chinese mode, the symbol shown is "中". If I switch to direct-input mode, the symbol becomes "英".

| Chinese input mode | Direct input mode |
| --- | --- |
| ![圖片](https://github.com/user-attachments/assets/91ad7fe9-c99a-4b11-aac5-ebce1e91a9b5) |  ![圖片](https://github.com/user-attachments/assets/ce39cfa2-c081-4557-8d4e-d0a2e4b93551) |

But I have problem implementing this with code. Please help and show me some indicator(s) how this can be implemented. Thanks.

**Comment by fujiwarat** [comment]
ibus-anthy specifies `<symbol>` tag and `<icon_prop_key>` tags in the target `<engine>` tag in /usr/share/ibus/component/anthy.xml

`<icon_prop_key>` indicates which IBus.Property has the symbol text for the panel icon.

```
% /usr/libexec/ibus-engine-anthy --xml
<?xml version="1.0" encoding="utf-8"?>
<engines>
	<engine>
		<name>anthy</name>
		<language>ja</language>
		<license>GPL</license>
...
		<symbol>&#x3042;</symbol>
		<icon_prop_key>InputMode</icon_prop_key>
...
	</engine>
</engines>

```

Your engine can use `IBus.Engine.update_property()` function with the property name specified by `icon_prop_key` tag and the symbol tag.
https://github.com/ibus/ibus-anthy/blob/main/engine/python3/engine.py#L907

**Comment by yookoala** [comment]
Thanks for your answer.
