### ISSUE TITLE
Don't grab Ctrl+Shift+F and fuck up people's day

### ISSUE THREAD

**Issue by kiwec** [ibus/ibus#2672]
An update to this made it so that it just silently grabs Ctrl+Shift+F. Any program that uses this as a keybind would no longer accept it. Roll that shit back

**Comment by yookoala** [comment]
Not an iBus developer here, but I think there are things you'd need to clarify to get help.

1. Are you using a development version of IBus? If so, which commit are you on?
2. If you're only using this as a user, which input method engine are you using?
