### ISSUE TITLE
Setting tooltip of IBus.Property doesn't show on UI

### ISSUE THREAD

**Issue by yookoala** [ibus/ibus#2674]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
Fedora 40

Which desktop environment and version?: 
GNOME 46

Which session type?: 
Wayland

Which application and version?: 
-

IBus version?: 
1.5.30

Issue description:
I'm maintaining an IBus engine implementation (written in Python). And I'm recently working on the UI updates. I noticed that even if I create an IBus.Property with .tooltip set to `IBus.Text.new_from_string("something")`, the tooltip is not shown when I hover over the indicator dropdown menu.

Steps to reproduce:
1. Write a minimal IBus.Engine implementation.
2. Create an `IBus.Property` of `IBus.PropType.TOGGLE` type, `label` with text, a proper `key`, and property setup tooltip with text.
3. Load up the engine to iBus.
4. Switch to this engine.
5. Click on the indicator icon to show the dropdown menu
6. Use cursor to hover on the toggle button.

Expected to see the tooltip text but see nothing.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
Yes

Do you see any errors when you run ibus-daemon with the verbose option?:
No error message.

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
Yes

**Comment by fujiwarat** [comment]
You're right. Seems any tooltip text no longer works at present.

For non-GNOME desktops, the tooltip text feature has been deleted in GTK as the design AFAIR.
For GNOME desktop, we have never implemented tooltip to follow GTK.
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/status/keyboard.js?ref_type=heads#L997

I think it would be a design issue in gnome-shell.

**Comment by yookoala** [comment]
If IBus.Property.tooltip is deprecated, please mark it deprecated somewhere in the [documentations](https://ibus.github.io/docs/ibus-1.5/IBusProperty.html#IBusProperty.properties). Thanks.
