### ISSUE TITLE
Support changing keyboard layout without changing input method

### ISSUE THREAD

**Issue by jeanas** [ibus/ibus#2675]
Some input methods such as [ibus-uniemoji](https://github.com/salty-horse/ibus-uniemoji/) are not language-specific. When switching to such an IM, the keyboard layout is currently kept to the one used for the previous IM, e.g., if I want to use uniemoji with a French layout, I should first switch to French (`xkb:fr:something`), then switch to uniemoji, which is not very intuitive. It would be nice to be able to separately configure the keyboard layout and the input method in the IBus panel and with the `ibus` command.

**Comment by fujiwarat** [comment]
It would be the issue of ibus-uniemoji.
ibus-anthy has a setting in the dialog to customize the layouts.
