### ISSUE TITLE
Wrong key map for Apple Magic Keyboard with Numeric Keypad - Japanese

### ISSUE THREAD

**Issue by sukeya** [ibus/ibus#2681]
Hi,

I have a trouble that the key map of my keyboard "Apple Magic Keyboard with Numeric Keypad - Japanese" is wrong.

Which distribution and version?: 
Ubuntu 24.04

Which desktop environment and version?: 
GNOME 46.0

Which session type?: 
X11

Which application and version?: 
gedit, leafpad, kate and xterm are not installed.

IBus version?: 
1.5.29-rc2

Issue description:
The maps of keys "Kana", "Eisu" and "CapsLock" are wrong. The output of `xev` is following:

```
Kana
KeyRelease event, serial 38, synthetic NO, window 0x2800001,
    root 0x1fe, subw 0x0, time 12970293, (440,-271), root:(1752,450),
    state 0x0, keycode 130 (keysym 0xff31, Hangul), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

Eisu
KeyRelease event, serial 38, synthetic NO, window 0x2800001,
    root 0x1fe, subw 0x0, time 13056428, (56,-14), root:(1368,707),
    state 0x0, keycode 131 (keysym 0xff34, Hangul_Hanja), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False

CapsLock
KeyRelease event, serial 38, synthetic NO, window 0x2800001,
    root 0x1fe, subw 0x0, time 13079628, (55,-27), root:(1367,694),
    state 0x2, keycode 66 (keysym 0xff30, Eisu_toggle), same_screen YES,
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

Steps to reproduce:
1. `sudo dpkg-reconfigure keyboard-configuration`
1. Select `Apple Aluminium (JIS)`
1. Select `Japanese`
1. Select `Japanese - Japanese (Macintosh)`
2. Select `No toggling`
3. Select `No temporary switch`
4. Select `The default for the keyboard layout`
5. Select `No compose key`
6. Select `No`

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
yes

Do you see any errors when you run ibus-daemon with the verbose option?:
no

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): 
maybe yes

**Comment by fujiwarat** [comment]
I guess your issue would be in Ubuntu desktop.

> 2. Select Apple Aluminium (JIS)

Neither GNOME and IBus settings does not have the XKB models but layouts, variants, optoins so probably I think an Ubuntu UI can configure it.

How about Japanese 106 or 109 keyboards? Do you have the hardwares?

I don'T have "Apple Magic Keyboard" hardware but I tried `Japanese - Japanese (Macintosh)` in GNOME Xorg in Fedora 40 without `Select Apple Aluminium (JIS)`.

> The maps of keys "Kana", "Eisu" and "CapsLock" are wrong. The output of xev is following:

I confirmed `Eisu_toggle` and `Caps_Lock` work fine with xev. I'm not sure what you mean in "Kana" but `Hiragana_Katakana`,  `kana_A`, `kana_I` et el works fine.

**Comment by fujiwarat** [comment]
> I have a Japanese 109 keyboard, but I would like to use Apple's one because switching the input mode between hiragana and hankaku-eisu is easier.

I'd ask if you can reproduce your issue with the 109 keyboard using `Japanese - Japanese (Macintosh)` without `Apple Aluminium (JIS)` to understand your issue.

> Kana means the right key of space

And then, you mean `Hiragana_Katakana` keysym and it works with `Japanese - Japanese (Macintosh)`.

> It seems that this problem is not caused by ibus.

No, ibus keymap is not used in GNOME desktop at least.

**Comment by sukeya** [comment]
I see.

> I'd ask if you can reproduce your issue with the 109 keyboard using Japanese - Japanese (Macintosh) without Apple Aluminium (JIS) to understand your issue.

I couldn't reproduce my issue with my 109 keyboard replaced the right windows key with a function key.

**Comment by fujiwarat** [comment]
IBus panel just runs setxkbmap internally for the layout and variant only.
If you cannot reproduce your issue in other desktop sessions likes XFCE, your issue would be Ubuntu.

> sudo dpkg-reconfigure keyboard-configuration
> Select Apple Aluminium (JIS)

There is no such a configuration in GNOME but an Ubuntu specific configuration.

You can set `Option "XkbModel" "applealu_jis"` to /xorg.conf.d/00-keyboard.conf for the default model and log into the session and confirm the model is set with `setxkbmap -query` command in non-GNOME session and runs `setxkbmap -layout jp -variant mac` and if you can reproduce your issue, your issue is caused by XKB.

**Comment by sukeya** [comment]
In XFCE, I can reproduce the same result for `Kana` and `Eisu` , but `Caps Lock` works fine.

I'm not sure that I have done the right setting.
The output of `setxkbmap -query` is following:

```
rules:      evdev
model:      applealu_jis
layout:     jp
variant:    mac
options:    grp_led:scroll
```

**Comment by fujiwarat** [comment]
If you reproduce your issue with setxkbmap, it would be an XKB issue.
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commit/f80def1157191c432df544eb45f3c3f09d6aa126
