### ISSUE TITLE
ibus: calls dbus_get_local_machine_id() which has bad error-handling

### ISSUE THREAD

**Issue by hosiet** [ibus/ibus#2686]
Forwarding downstream bug report made by @smcv :

> `src/tests/ibus-share.c` calls `dbus_get_local_machine_id()`, which has no good mechanism for reporting an error, and therefore will spam warnings to standard error (and possibly crash) if the D-Bus machine ID has not been set up correctly. This function should be considered deprecated.
> 
> Please prefer to use dbus_`try_get_local_machine_id()`, which takes a DBusError parameter (same calling convention as e.g. `dbus_validate_path()`) and therefore can be used to report errors in whatever way is considered to be most appropriate by the caller. This has been available in upstream stable releases since dbus 1.12.0 (2017).

You may find the downstream Debian bug report at https://bugs.debian.org/1085342 .

**Comment by fujiwarat** [comment]
I made the candidate patch above and will integrate it soon.
