### ISSUE TITLE
Firefox url bar autocomplete stopped working with IBus running

### ISSUE THREAD

**Issue by DeinAlptraum** [ibus/ibus#2690]
Which distribution and version?: 
Arch Linux, 6.11.4-arch2-1

Which desktop environment and version?: 
KDE Plasma Version: 6.2.1
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Kernel Version: 6.11.4-arch2-1 (64-bit)

Which session type?: 
Wayland

Which application and version?: 
Firefox 131.0.3

IBus version?: 
IBus 1.5.30

Issue description:
Firefox URL autocomplete stopped working about 2 weeks ago with ibus-daemon running.
Previously if I typed e.g. "yout" into the URL address bar, it would autocomplete to "youtube.com" or similar. This stopped working roughly two weeks ago on my laptop, and after a system update+reboot on my PC, the exact same issue started appearing there (it also uses Arch Linux, KDE, Wayland and IBus with Firefox)

If I type only a single letter, I get autocomplete as usual. If it doesn't work and I click outside of the address bar once, then back inside, it also autocompletes.

Steps to reproduce:
Not sure. I've installed IBus with a German keyboard and IBus Anthy for Japanese. Start typing into the URL address bar in Firefox (with the German keyboard), and no autocomplete appears.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
No

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)
Can't test this since the issue disappears when restarting ibus-daemon

Can you reproduce your problem with a new user account instead of the current your account? (yes / no):
Yes

**Comment by fujiwarat** [comment]
Probably I think your issue is caused by firefox but not ibus because the URL autocompletion is not touched by ibus.
I see the feature works in Xorg.
