### ISSUE TITLE
Crash with `ibus_engine_delete_surrounding_text` on Wayland

### ISSUE THREAD

**Issue by ermshiperete** [ibus/ibus#2698]
_Which distribution and version?:_ 
Ubuntu 24.04, 24.10

_Which desktop environment and version?:_ 
Gnome 46

_Which session type?:_ 
Wayland

_Which application and version?:_ 
Firefox
```
$ snap list firefox
Name     Version    Rev   Tracking         Publisher  Notes
firefox  132.0.1-2  5239  latest/stable/…  mozilla✓   -
```

_IBus version?:_ 
1.5.29, 1.5.30

_Issue description:_
When pressing a key that results in the ibus engine calling `ibus_engine_delete_surrounding_text` (e.g. `ibus_engine_delete_surrounding_text(engine, -1, 1)`), the Gnome session crashes.

_Steps to reproduce:_
1. Compile and install the test program (https://github.com/ermshiperete/ibus-bugtest), install it as keyboard
2. Open Firefox (installed as Snap package), go to google.com and place cursor in search field
3. type <kbd>a</kbd> and <kbd>x</kbd>

_Can you reproduce your problem when you restart ibus-daemon? (yes / no):_ 
yes

_Do you see any errors when you run ibus-daemon with the verbose option?_:
no

_Can you reproduce your problem with a new user account instead of the current your account? (yes / no):_ 
yes

The crash only happens in the search field, not in the address bar of Firefox.

**Comment by fujiwarat** [comment]
There is a known issue that calling ibus_engine_delete_surrounding_text() causes SEGV in gnome-shell if the application does not support the surrounding-text feature.
One patch is upstreamed but another is still under the review.

https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3604
https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3069

**Comment by ermshiperete** [comment]
Thanks that you looked into this and linked the issues!
