### ISSUE TITLE
[Firefox] Candidate window obscures text input

### ISSUE THREAD

**Issue by musjj** [ibus/ibus#2699]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
NixOS 24.11

Which desktop environment and version?:
GNOME 47.1

Which session type?: 
Wayland

Which application and version?: 
Firefox

IBus version?: 
1.5.30

Issue description:
When using IBus with mozc and `MOZC_IBUS_CANDIDATE_WINDOW=ibus`, the candidate window covers up the current text:

![firefox](https://github.com/user-attachments/assets/b334135e-d26a-4029-a262-216f22bf798c)

On Chrome (running on XWayland), the window is placed so that it doesn't cover up the current text:

![chrome](https://github.com/user-attachments/assets/1c7bd8f8-4946-4948-a9f1-9fc2367806d6)

Also, in Firefox the candidate window doesn't follow the end of your text input, unlike Chrome as shown above.

Steps to reproduce:
1. Install ibus with the mozc engine
2. Ensure that your environment is set correctly:
   ```bash
   GTK_IM_MODULE=ibus
   QT_IM_MODULE=ibus
   XMODIFIERS=@im=ibus
   MOZC_IBUS_CANDIDATE_WINDOW=ibus
   ```
3. Open Firefox and type something with the mozc input source activated

Can you reproduce your problem when you restart ibus-daemon? (yes / no): yes
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?: no
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

Can you reproduce your problem with a new user account instead of the current your account? (yes / no): yes

**Comment by fujiwarat** [comment]
I cannot reproduce your issue with ibus-anthy.
Since it might be a specific issue with ibus-mozc and firefox, I'd suggest you to consult ibus-mozc.

**Comment by musjj** [comment]
To clarify, does `ibus-anthy` use the native ibus candidate window?

**Comment by fujiwarat** [comment]
What is the native ibus candidate window. I guess you mean a native candidate window which is not an ibus feature but mozc feature.

**Comment by PepperJo** [comment]
@musjj Did you find any solution? I'm facing the same problem.

**Comment by PepperJo** [comment]
Turns out setting `GTK_IM_MODULE=ibus` breaks the candidate window placement, both for the native renderer and mozc. Removing it fixed the issue described above for me.
