### ISSUE TITLE
Ubuntu 24.04 LTS - 'ibus' package update request (to fix special character keys dead on 1.5.29/1.5.29-rc2)

### ISSUE THREAD

**Issue by BetterToAutomateTheWorld** [ibus/ibus#2703]
Please fill in the following items if you don't know the root cause.

Which distribution and version?: 
- Ubuntu 24.04 LTS up to date

Which desktop environment and version?: 
- KDE 5

Which session type?: 
- X11

Which application and version?: 
- All Wine applications (standalone, inside Lutris, inside HeroicGame Launcher, etc.)

IBus version?: 
- 1.5.29
![image](https://github.com/user-attachments/assets/fd362b53-a6d0-43ce-a794-17757e4d3d16)

Issue description:
- ![image](https://github.com/user-attachments/assets/9310d64b-ede5-4481-984a-102ffcf34ca7)

Steps to reproduce:
1. Install Ubuntu 24.04 LTS
2. Do updates (just in case, anyway you only have 1 ibus package version)
3. Set your keyboard layout to something with special characters (like french layout with 'é' or 'è')
4. Run any Wine game/application
5. Try to type these keys (push 2 and 7 key on your keyboard) : it's "empty" / not working

Can you reproduce your problem when you restart ibus-daemon?
- Restarting ibus fix the issue temporarly, but it introduce other issues (like renaming desktop files in KDE 5 becomes broken)

Do you see any errors when you run ibus-daemon with the verbose option?:
- Nope

Can you reproduce your problem with a new user account instead of the current your account? 
- Yes

---

This issue is linked to https://github.com/ibus/ibus/issues/2588

I know  @fujiwarat fix it, The only thing i'm asking is an Ubuntu 24.04 LTS ibus package fix/update, do we have an ibus Ubuntu package maintainer available here, or any way to push it ? The current version can't be more 'up to date' in an official way...

I personally fixed the issue by installing manually the ibus `1.5.31` packages manually myself to my (Kubuntu)Ubuntu 24.04 LTS, which is breaking part of my system, so for now i'm not using apt / doing any updates. But this is annoying in the long term.

Thank you!

**Comment by fujiwarat** [comment]
I may not understand your question clearly.

> I know @fujiwarat fix it, The only thing i'm asking is an Ubuntu 24.04 LTS ibus package fix/update, do we have an ibus Ubuntu package maintainer available here, or any way to push it ? 

If you wish to install the 1.5.31 package, you could ask the Ubuntu maintainer to update the package. I have no idea about it.

Or you could get the Ubuntu source file and replace the tarball. My understanding is you could get it with `apt-get source ibus` and the latest tarball is available in this site and you could run `dh_make`.

Or you could build IBus from the git main repo. The latest build way is described in:
https://github.com/ibus/ibus/actions/runs/12197999188/job/34028810291

**Comment by BetterToAutomateTheWorld** [comment]
Hi @fujiwarat 

I apologize if my initial post was unclear. I do not want to build or install ibus locally, as I prefer system-integrated packages for critical / shared components. I'm probably not alone to have this mindset. For individual or standalone applications, I would have no issue building or installing them myself, but ibus is not in that category.

I created this ticket in the hope that you might know the Ubuntu maintainer or work with him/them, given the popularity of Ubuntu-based OS. If you don't have that connection, I will reach out to the maintainer directly.

Thank you for your prompt response!

**Comment by juhp** [comment]
https://launchpad.net/ubuntu/+source/ibus/+bugs
