### ISSUE TITLE
[Suggestion] Allow implementing something like "ibus-type" tool that's similar to "xdotool type" or "wtype"

### ISSUE THREAD

**Issue by Nekotekina** [ibus/ibus#2704]
It's hard to type Unicode programmatically. There are very few tools to my knowledge that can do it to some extent.
What I mean is, running some script would cause currently focused input to receive "virtual" keystrokes.
`xdotool` and `wtype` rely on a hack that creates new xkb mapping or something for unmapped Unicode characters.
xdotool is extremely slow because of this, not to mention it only works on Xorg.
wtype does something similar and isn't supported on GNOME Wayland, for example.
Finally there's a `keyd` tool that is capable of typing some Unicode character... via XCompose mechanism. A huge table of various Compose combination for (limited) set of Unicode character. It works more universally, but it has limitations. For example, it's impossible to type unicode like this inside an explicit compose, inside of IME, inside of some programs that don't even support Compose key.

So would it be possible to speak to IBus, at least for sudoer, to force it to type any Unicode character without hassle? This would allow implementing a hypothetical "ibus-type" tool I mentioned in the title.

**Comment by fujiwarat** [comment]
I think you can use Ctrl-Shift-u key?
