### ISSUE TITLE
IBus version 1.5.30 has a keyboard latency for Wine on Ubuntu 24.10

### ISSUE THREAD

**Issue by robstarmcdonald** [ibus/ibus#2705]
# System Details Report
---

## Report details
- **Date generated:**                              2024-12-17 22:51:09

## Hardware Information:
- **Hardware Model:**                              Acer Nitro AN515-57
- **Memory:**                                      32.0 GiB
- **Processor:**                                   11th Gen Intel® Core™ i7-11800H × 16
- **Graphics:**                                    Intel® UHD Graphics (TGL GT1)
- **Graphics 1:**                                  NVIDIA GeForce RTX™ 3050 Ti Laptop GPU
- **Disk Capacity:**                               2.0 TB

## Software Information:
- **Firmware Version:**                            V1.17
- **OS Name:**                                     Ubuntu 24.10
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.11.0-12-generic

IBus version?: 
(Run 1.5.30)

Text Editor app?:
gnome-text-editor

Issue description:
Unfortunately, ever since I upgraded to 1.5.30 from 1.5.29, keyboard latency has occurred for [Wine](https://www.winehq.org/) so I hope a new version has that fixed.

Steps to reproduce may not solve this issues for me, this is a first time for me. So, I don't know there are ways to fix that myself.

Can you reproduce your problem when you restart ibus-daemon? (yes / no): 
(Run `ibus exit` and `ibus-daemon --xim &`)

Do you see any errors when you run ibus-daemon with the verbose option?:
(Run `ibus-daemon --xim --verbose &` and look at the output when you encounter your problem.)

I tried to find it, this is a first time for me to send this bug report, so I can't unless there is help, but this is what I got.
# im-config(8) generated on Tue, 17 Dec 2024 22:56:34 -0800
run_im ibus
# im-config signature: b95d4448efbd5f776f1bfcd5c918dce7  -

Can you reproduce your problem with a new user account instead of the current your account? 
No, because again, steps to reproduce may not solve this issues for me, this is a first time for me.

**Comment by fujiwarat** [comment]
I'd ask you to try 1.5.31 or later.

**Comment by robstarmcdonald** [comment]
I hope Ubuntu 25.04 (Plucky Puffin) has that version or later to prevent keyboard latency.
