### ISSUE TITLE
How to make the order of input methods static, if possible?

### ISSUE THREAD

**Issue by N3xtery** [ibus/ibus#2707]
I have 4 input methods: 1, 2, 3, 4, the first being the active one. When I press the change input method hotkey, the second input method becomes active, and the order of input methods changes to 2, 1, 3, 4. When, after the selection menu is gone, I press the hotkey again, the first input method becomes active again. Is it possible to make the order not change, so that the third input method becomes active instead, which is the typical behavior on Windows and default Linux layout switchers?

**Comment by fujiwarat** [comment]
IBus remembers the last used input method.

**Comment by N3xtery** [comment]
Shouldn't there be an option to change that behavior? It's unusual. It should be possible to go through input methods one by one using a hotkey without the selection menu
