### ISSUE TITLE
Problem in characters mapped with more than 1 key combinations.

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#647]
```
ubuntu 9.10
我使用的是万能五笔 for ibus
参见 http://forum.ubuntu.org.cn/viewtopic.php?f=8&t=238004
目前我发现ibus的字频调整有问题（不知是不是我不会设置）
情况是这样的比如我习惯打L: “国”  G:“一”
但是当我打L: “国”的次数比较多的时候，就会出现我再打G的时候默认的是“国”，"
一"到第二位了

我有查看.ibus/tables下的wnwb-user.db文件
发现同国个字的user_freq的值是一样的，
322|1|1|7||||||||||||3|国|0|98
324|1|1|12||||||||||||3|国|0|98
个人认为应该分别记录不同按键下的国字的user_freq.

我想不单是万能五笔有这个问题，别的输入法应该也会有这个问题，
只是万能五笔是混合输入 同一个字 有不同的输入方法
国：g l 了：l b 所以才感觉这个问题很明显







```

Original issue reported on code.google.com by `liuke.forever` on 2009-11-05 07:24:49

**Comment by mike-fabian** [comment]
original issue on google code was: https://code.google.com/p/ibus/issues/detail?id=627

**Comment by mike-fabian** [comment]
I cannot read Chinese so I am just trying to make sense of the report using google translate.
I believe I have fixed this issue in ibus table already.

In the report, the user ends up having two entries for 国
in the database, one when the letter “g” has been typed (wrong)
and one when the letter “l” has been typed (correct):

322|1|1|7||||||||||||3|国|0|98    <- 7 is the letter “g”
324|1|1|12||||||||||||3|国|0|98   <- 12 is the letter “l”

This doesn’t happen anymore, now I get stuff like this in the
user database (the database has a new format):

sqlite> select * from phrases where phrase='国';
27|l|国|0|6
43|lgy|国|0|4
sqlite> select * from phrases where phrase='一';
42|g|一|0|2
sqlite> 

This looks correct.
