### ISSUE TITLE
Latex table has incorrect/incomplete symbols

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#655]
```
The current latex table has many incorrect and incomplete symbols. (I'm
looking at you especially, ⊤.) I've made a new table, with data sourced
from <http://www.w3.org/2003/entities/2007xml/unicode.xml>, that is much
more comprehensive. (I meant to source it from the character table from the
STIX font project, but I can't seem to find an easily available copy of
it.) Maybe it'll be useful to others too.

latex.txt is the new table.
ibus-table-latex.tar.gz has the source file as well as the script to
extract the data from the source file and make the new table.
```

Original issue reported on code.google.com by `martin.k.tang` on 2009-11-09 22:44:56
<hr>
 * *Attachment: [latex.txt](https://storage.googleapis.com/google-code-attachments/ibus/issue-635/comment-0/latex.txt)*
 * *Attachment: [ibus-table-latex.tar.gz](https://storage.googleapis.com/google-code-attachments/ibus/issue-635/comment-0/ibus-table-latex.tar.gz)*

**Comment by mike-fabian** [comment]
This is probably fixed, I received an update from the original author of the
latex table in July 2014.

See:

https://github.com/moebiuscurve/ibus-table-others/commit/879b13882cd570cd69e3923b118522a898995f9a

**Comment by mike-fabian** [comment]
Original issue on google code was: https://code.google.com/p/ibus/issues/detail?id=635
