### ISSUE TITLE
Show key combinations or decomposition rules after character commit.

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#718]
```
希望ibus-table加入查碼的功能，如用倉頡打完一個字時便顯示使用者自定的輸入法
(如注音)對應的拆碼
這對使用者來說是有學習的作用，這功能在windows上很早就有了，我覺得不錯用

建議可加入此功能…感謝各位辛苦的大大… :)

```

Original issue reported on code.google.com by `scsichen` on 2009-12-18 01:38:00

**Comment by mike-fabian** [comment]
google code issue was: https://code.google.com/p/ibus/issues/detail?id=698

**Comment by mike-fabian** [comment]
I think this can be considered fixed as the key sequences are displayed
as described above.
