### ISSUE TITLE
Custom font doesn't seem to work

### ISSUE THREAD

**Issue by fujiwarat** [ibus/ibus#757]
```
What version of the product are you using? On what operating system?
OS (Linux distributions, UNIX or ...): Gentoo Linux
Architecture (i386, x86_64): x86_64
IBus version: 1.2.0.20100111
Input method name and version: all
Python version: 2.6.4
dbus version: 1.2.3
dbus-python version: 0.83.0
gtk version (if bug is about gtk applications): 2.16.6
qt version (if bug is about qt applications): 4.6.0

What steps will reproduce the problem?
1. Open the ibus-settings panel
2. Set the custom font size to 20 (or 30 or 40 or to a different family 
altogether)
3. Switch to ibus-pinyin for example and try to type anything
4. 

What is the expected output? What do you see instead?
The font for the selection window should be the selected family and the 
selected size. But instead it is still the original small-sized one.
```

Original issue reported on code.google.com by `yankyo` on 2010-01-13 21:39:08

**Comment by wsxy162** [comment]
This is a old issue, but it still exist. If I use third-party themes for gnome, modifying .candidate-popup-content entry in gnome-shell.css file of the theme can successfully customize fonts and size of ibus panel. But if I use defautl gnome theme - adwaita, this way won't work cause there is no gnome-shell.css file for default theme for me to modify. Anyway, modifying gnome-shell.css file is just a work around way, still does't fix the exact issue.

**Comment by fujiwarat** [comment]
> This is a old issue, but it still exist.

I don't think your issue and this are same.
The font size is handled by gnome-shell but not IBus.

**Comment by wsxy162** [comment]
Sorry, I forget this is a old issue when ibus had not been include in gnome
desktop. So should I open another issue? And there is noway to change font
size if using default gnome-shell theme, don't count on change the global
font size of the desktop.

2016-04-18 18:16 GMT+08:00 Takao Fujiwara <notifications@github.com>:

**Comment by wsxy162** [comment]
Sorry, I forgot this is a old issue when ibus had not been include in gnome desktop. So should I open another issue? And there is noway to change font size if using default gnome-shell theme, don't count on change the global font size of the desktop.

**Comment by fujiwarat** [comment]
Please file a bug in bugzilla.gnome.org instead of ibus.

**Comment by wsxy162** [comment]
But ibus maintainers don't care about weither if ibus-setup can works in
gnome desktop? Or you don't join the intergration between ibus and gnome
side?

2016-04-18 18:45 GMT+08:00 Takao Fujiwara <notifications@github.com>:

**Comment by fujiwarat** [comment]
No, ibus-setup is not used for GNOME desktop.
Use gnome-control-center instead.
